Repository Kong/docs.konghq.com, pull requests merged in 2018-12, with the labels that each got.

#1064 docs(hub): add kong-plugin-url-rewrite by stone-payments
  app/_assets/images/icons/hub/stone-payments_kong-plugin-url-rewrite.png
  app/_hub/stone-payments/kong-plugin-url-rewrite/index.md
Labels: hub

#1088 docs(organization) invite admin inst.
  app/enterprise/0.34-x/kong-manager/organization-management/managing-admins.md
Labels: wip

#827 feat(conf) Adding documentation for keepalive disable
  app/1.0.x/configuration.md
Labels: release
