Repository Kong/docs.konghq.com, pull requests merged in 2018-10, with the labels that each got.

#916 feat(*) add Delighted CSAT survey widget
  app/_includes/delighted.html
  app/_includes/head.html
Labels: needs review

#910 fix(new relic) update JS and correct app name
  app/_includes/newrelic.html
Labels: needs review

#895 Docs/rate limiting add EE 0.31
  app/_data/extensions/kong-inc/rate-limiting-advanced/versions.yml
  app/_hub/kong-inc/rate-limiting-advanced/0.31-x.md
Labels: needs review

#850 docs(ce/admin) add missing attributes for plugins endpoints
  app/0.14.x/admin-api.md
Labels: needs review

#810 creation
  app/_data/docs_nav_ee_0.33-x.yml
  app/enterprise/0.33-x/developer-portal/best-practices.md
Labels: needs review

#941 feat(dev-portal) document Admin API for Developers
  app/enterprise/0.33-x/developer-portal/managing-developers.md
Labels: needs review

#945 docs(prometheus) typos and wording improvement
  app/_hub/kong-inc/prometheus/index.md
Labels: needs review

#959 Update gulpfile.js
  gulpfile.js
Labels: invalid

#965 Make numbered list styling consistent
  app/_assets/css/hub.css
  app/_assets/stylesheets/page.less
  app/_assets/stylesheets/pages/extension.less
Labels: needs changes

#969 style(syntax) dont allow selecting generic prompt symbol
  app/_assets/stylesheets/syntax.less
Labels: needs review

#987 chore(*) add dead code warning
  app/about/advantages.md
  app/about/benchmark.md
  app/about/faq.md
  app/about/index.md
  app/about/pci-dss.md
  app/about/who.html
  app/community/index.html
  app/license/index.md
Labels: needs review

#964 docs(admin) Add info about regex priority to documentation
  app/0.13.x/admin-api.md
  app/0.14.x/admin-api.md
Labels: needs review

#995 docs: fix typo
  app/0.14.x/plugin-development/custom-logic.md
Labels: invalid

#922 Docs/loadbalancing dns clarifications
  app/0.14.x/loadbalancing.md
Labels: needs review

#1000 Fix akward formatting in tables in Hub pages
  app/_hub/peter-evans/paseto/index.md
Labels: needs changes
