Repository Kong/docs.konghq.com, pull requests merged in 2019-11, with the labels that each got.

#1592 Change to parameters and curl
  app/free-trial/guide/index.html
Labels: pr/wip

#1591 docs(openid-connect) update OpenID Connect docs
  app/_hub/kong-inc/openid-connect/index.md
Labels: pr/please review

#1634 feat(studio) 1.1.0 docs
  app/_data/docs_nav_studio_1.1.x.yml
  app/_data/kong_versions.yml
  app/_layouts/changelog.html
  app/studio/1.0.x/overview.md
  app/studio/1.1.x/debugging-with-insomnia.md
  app/studio/1.1.x/deploy-to-dev-portal.md
  app/studio/1.1.x/download-install.md
  app/studio/1.1.x/editing-specs.md
  app/studio/1.1.x/git-sync.md
  app/studio/1.1.x/graphql.md
  app/studio/1.1.x/index.md
  app/studio/1.1.x/live-preview.md
  app/studio/1.1.x/overview.md
  app/studio/1.1.x/release-notes.md
  app/studio/changelog.md
  package-lock.json
Labels: release
