Repository Kong/docs.konghq.com, pull requests merged in 2019-03, with the labels that each got.

#1169 style(reqtran) fix broken tables
  app/_assets/stylesheets/page.less
  app/_hub/kong-inc/request-transformer/0.1-x.md
  app/_hub/kong-inc/request-transformer/index.md
Labels: wip

#982 Grammar Correction
  app/0.13.x/getting-started/adding-consumers.md
Labels: invalid, needs changes

#1193 docs(hub) updating oauth2-instrospection flow diagram
  app/_assets/images/docs/oauth2/oauth2-introspection.png
  app/_hub/kong-inc/oauth2-introspection/0.31-x.md
  app/_hub/kong-inc/oauth2-introspection/0.32-x.md
  app/_hub/kong-inc/oauth2-introspection/0.33-x.md
  app/_hub/kong-inc/oauth2-introspection/index.md
Labels: hub

#1172 docs(docker-install) revise docker installation guide
  app/enterprise/0.34-x/installation/docker.md
Labels: wip

#1012 added missing alt text
  app/_includes/header.html
Labels: invalid, needs changes
