Repository Kong/docs.konghq.com, pull requests merged in 2020-04, with the labels that each got.

#1905 Release: 2.0.3
  app/_data/kong_versions.yml
Labels: pr/please review

#1898 Removed Alpha tag
  app/enterprise/1.3-x/db-encryption.md
Labels: do not merge

#1715 docs(salt-security) Initial commit plugin
  app/_assets/images/icons/hub/salt_salt.png
  app/_hub/salt/salt/index.md
Labels: pending plugin approval

#1551 Feat/datadog tags
  app/_hub/kong-inc/datadog/index.md
Labels: Core Team review

#1893 fix(health) update CE according to EE
  app/2.0.x/health-checks-circuit-breakers.md
Labels: good first issue

#1894 Adding proper section names to Steps section
  app/enterprise/1.3-x/getting-started/start-kong.md
Labels: good first issue

#1963 added google analytics plugin to plugins hub
  app/_assets/images/icons/hub/yesinteractive_kong-log-google.png
  app/_hub/yesinteractive/kong-log-google/index.md
Labels: pending plugin approval
