Repository Kong/docs.konghq.com, pull requests merged in 2020-10, with the labels that each got.

#2328 Add curl example for quotas Response Rate Limiting plugin
  app/_hub/kong-inc/response-ratelimiting/index.md
Labels: pr/please review

#2276 Application Registration Documentation Enhancements Part 1
  app/enterprise/2.1.x/developer-portal/administration/application-registration/enable-application-registration.md
  app/enterprise/2.1.x/developer-portal/administration/application-registration/index.md
  app/enterprise/2.1.x/developer-portal/administration/application-registration/okta-config.md
  app/enterprise/2.1.x/plugins/oidc-okta.md
Labels: pr/please review, pr/wip

#2363 Response Transformer Advanced plugin correction
  app/_hub/kong-inc/response-transformer-advanced/1.3-x.md
Labels: pr/please review

#2357 LDAP Auth Header & Ports updates
  app/_hub/kong-inc/ldap-auth-advanced/index.md
Labels: pr/please review

#2384 Exit Transformer plugin icon
  app/_assets/images/icons/hub/kong-inc_exit-transformer.png
Labels: pr/please review

#2392 fix(file-log) Soften performance warning
  app/_hub/kong-inc/file-log/0.1-x.md
  app/_hub/kong-inc/file-log/index.md
Labels: pr/please review

#2391 fix(k8s) Improvements to enterprise K8s installation page
  app/enterprise/1.5.x/kong-for-kubernetes/install-on-kubernetes.md
  app/enterprise/2.1.x/kong-for-kubernetes/install-on-kubernetes.md
Labels: bug, pr/please review

#2403 docs(version support) change 2.1.3.x to 2.1.x
  app/enterprise/2.1.x/support-policy.md
Labels: pr/please review

#2399 docs(brain) added important brain deprecated
  app/enterprise/2.1.x/brain-immunity/auto-generated-specs.md
  app/enterprise/2.1.x/brain-immunity/changelog.md
  app/enterprise/2.1.x/brain-immunity/install-configure.md
  app/enterprise/2.1.x/brain-immunity/overview.md
  app/enterprise/2.1.x/brain-immunity/service-map.md
  app/enterprise/2.1.x/brain-immunity/troubleshooting.md
Labels: pr/please review

#2397 docs(release notes) added "Deprecated" section
  app/enterprise/2.1.x/release-notes.md
Labels: pr/please review

#2396 docs(new-in-docs) update version number
  app/enterprise/2.1.x/doc-updates.md
Labels: pr/please review

#2395 docs(changelog) Kong Brain deprecated in 2.1.4.0
  app/enterprise/changelog.md
Labels: pr/please review

#2424 Correct version compatibility for gRPC plugins
  app/_data/extensions/kong-inc/grpc-gateway/versions.yml
  app/_hub/kong-inc/grpc-gateway/index.md
  app/_hub/kong-inc/grpc-web/0.1.x.md
  app/_hub/kong-inc/grpc-web/index.md
Labels: pr/please review

#2410 fix(statsd-exporter) remove obsolete api entries
  app/enterprise/2.1.x/plugins/statsd.rules.yaml
Labels: pr/please review

#2423 docs(ee-install) Add Google Cloud to marketplace installations
  app/_assets/images/icons/documentation/cloud_icon_color.png
  app/_data/docs_nav_ee_2.1.x.yml
  app/enterprise/2.1.x/deployment/installation/overview.md
Labels: pr/please review

#2422 docs(k8s) Move k8s topics into deployment section and update
  app/_assets/images/docs/ee/kubernetes/k4k8s-enterprise.png
  app/_assets/images/docs/ee/kubernetes/kong-enterprise-on-kubernetes.png
  app/_data/docs_nav_ee_2.1.x.yml
  app/enterprise/2.1.x/deployment/hybrid-mode.md
  app/enterprise/2.1.x/deployment/installation/kong-for-kubernetes.md
  app/enterprise/2.1.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.1.x/deployment/installation/overview.md
  app/enterprise/2.1.x/deployment/kong-for-kubernetes-enterprise.md
  app/enterprise/2.1.x/deployment/kubernetes-deployment-options.md
  app/enterprise/2.1.x/deployment/using-kong-for-kubernetes.md
  app/enterprise/2.1.x/doc-updates.md
  app/enterprise/2.1.x/index.md
  app/enterprise/2.1.x/introduction/index.md
  app/enterprise/2.1.x/kong-for-kubernetes/changelog.md
  app/enterprise/2.1.x/kong-for-kubernetes/index.md
  app/enterprise/2.1.x/release-notes.md
  app/enterprise/k8s-changelog.md
Labels: pr/please review
