Repository Kong/docs.konghq.com, pull requests merged in 2020-07, with the labels that each got.

#2132 docs(go) rework go guide
  app/2.1.x/go.md
Labels: pr/wip

#2147 chore(kubernetes) make redirect point to latest version of the document
  app/install/kubernetes.md
Labels: pr/please review

#2144 fix(install/source) update source installation instructions to use kong build tools
  app/_data/kong_versions.yml
  app/install/source.md
Labels: pr/please review

#2153 fix(kubernetes) install redirect page
  app/install/kubernetes.md
Labels: pr/please review

#2145 Release: 2.0.5
  app/_data/kong_versions.yml
Labels: pr/do not merge, pr/please review

#2154 fix(kubernetes) install redirect page, part 2
  app/install/kubernetes.md
Labels: pr/please review

#2151 docs(proxy) add documentation for dynamic default sni `*`
  app/2.1.x/proxy.md
Labels: pr/please review

#2149 grpc-web plugin: missing links in description
  app/_hub/kong-inc/grpc-web/index.md
Labels: broken-link, pr/please review

#2148 grpc-gateway plugin: missing link in image credit
  app/_hub/kong-inc/grpc-gateway/index.md
Labels: broken-link, pr/please review

#2171 docs(oauth2) add missing documentation for pkce parameter
  app/_hub/kong-inc/oauth2/index.md
Labels: pr/please review

#2177 Update migrate/upgrade for Dev Portal to beta placeholder
  app/_data/docs_nav_ee_2.1.x.yml
Labels: pr/please review
