Repository Kong/docs.konghq.com, pull requests merged in 2020-12, with the labels that each got.

#2476 doc(support-policy) update to new support policy
  app/enterprise/2.2.x/support-policy.md
Labels: do not merge, pr/wip

#2483 Release: 2.2.1
  app/_data/kong_versions.yml
Labels: pr/do not merge, pr/please review

#2494 docs(ee-license) Add note to use your own license for Docker installs
  app/enterprise/1.3-x/deployment/installation/docker.md
  app/enterprise/1.5.x/deployment/installation/docker.md
  app/enterprise/2.1.x/deployment/installation/docker.md
  app/enterprise/2.2.x/deployment/installation/docker.md
Labels: pr/please review

#2493 docs(mesh) Installation categories and marketplaces
  app/_assets/images/icons/documentation/debian-logo.jpg
  app/_assets/images/icons/documentation/helm-icon-color.svg
  app/_assets/images/icons/documentation/kubernetes-logo.png
  app/_assets/images/icons/documentation/macos-logo.png
  app/_assets/images/icons/documentation/openshift-logo.png
  app/_data/docs_nav_mesh_1.1.x.yml
  app/mesh/1.1.x/install.md
Labels: pr/please review

#2488 docs(ee-install) Update AWS AMI links for 2.2
  app/_data/docs_nav_ee_2.2.x.yml
  app/enterprise/2.2.x/deployment/installation/overview.md
Labels: pr/please review

#2492 docs(kic) Replace product name with variables
  app/kubernetes-ingress-controller/1.0.x/concepts/custom-resources.md
  app/kubernetes-ingress-controller/1.0.x/concepts/deployment.md
  app/kubernetes-ingress-controller/1.0.x/concepts/design.md
  app/kubernetes-ingress-controller/1.0.x/concepts/ha-and-scaling.md
  app/kubernetes-ingress-controller/1.0.x/concepts/ingress-classes.md
  app/kubernetes-ingress-controller/1.0.x/concepts/k4k8s-with-kong-enterprise.md
  app/kubernetes-ingress-controller/1.0.x/concepts/security.md
  app/kubernetes-ingress-controller/1.0.x/deployment/admission-webhook.md
  app/kubernetes-ingress-controller/1.0.x/deployment/aks.md
  app/kubernetes-ingress-controller/1.0.x/deployment/eks.md
  app/kubernetes-ingress-controller/1.0.x/deployment/gke.md
  app/kubernetes-ingress-controller/1.0.x/deployment/k4k8s-enterprise.md
  app/kubernetes-ingress-controller/1.0.x/deployment/kong-enterprise.md
  app/kubernetes-ingress-controller/1.0.x/deployment/minikube.md
  app/kubernetes-ingress-controller/1.0.x/deployment/overview.md
  app/kubernetes-ingress-controller/1.0.x/faq.md
  app/kubernetes-ingress-controller/1.0.x/guides/cert-manager.md
  app/kubernetes-ingress-controller/1.0.x/guides/configure-acl-plugin.md
  app/kubernetes-ingress-controller/1.0.x/guides/configuring-custom-entities.md
  app/kubernetes-ingress-controller/1.0.x/guides/configuring-fallback-service.md
  app/kubernetes-ingress-controller/1.0.x/guides/configuring-health-checks.md
  app/kubernetes-ingress-controller/1.0.x/guides/configuring-https-redirect.md
  app/kubernetes-ingress-controller/1.0.x/guides/getting-started-istio.md
  app/kubernetes-ingress-controller/1.0.x/guides/getting-started.md
  app/kubernetes-ingress-controller/1.0.x/guides/overview.md
  app/kubernetes-ingress-controller/1.0.x/guides/prometheus-grafana.md
  app/kubernetes-ingress-controller/1.0.x/guides/redis-rate-limiting.md
  app/kubernetes-ingress-controller/1.0.x/guides/setting-up-custom-plugins.md
  app/kubernetes-ingress-controller/1.0.x/guides/using-consumer-credential-resource.md
  app/kubernetes-ingress-controller/1.0.x/guides/using-external-service.md
  app/kubernetes-ingress-controller/1.0.x/guides/using-ingress-with-grpc.md
  app/kubernetes-ingress-controller/1.0.x/guides/using-kong-with-knative.md
  app/kubernetes-ingress-controller/1.0.x/guides/using-kongclusterplugin-resource.md
  app/kubernetes-ingress-controller/1.0.x/guides/using-kongingress-resource.md
  app/kubernetes-ingress-controller/1.0.x/guides/using-kongplugin-resource.md
  app/kubernetes-ingress-controller/1.0.x/guides/using-mtls-auth-plugin.md
  app/kubernetes-ingress-controller/1.0.x/guides/using-oidc-plugin.md
  app/kubernetes-ingress-controller/1.0.x/guides/using-rewrites.md
  app/kubernetes-ingress-controller/1.0.x/guides/using-tcpingress.md
  app/kubernetes-ingress-controller/1.0.x/introduction.md
  app/kubernetes-ingress-controller/1.0.x/references/annotations.md
  app/kubernetes-ingress-controller/1.0.x/references/cli-arguments.md
  app/kubernetes-ingress-controller/1.0.x/references/custom-resources.md
  app/kubernetes-ingress-controller/1.0.x/references/version-compatibility.md
Labels: pr/please review

#2495 fix(decK+KIC) Remove Harry's email from docs
  app/deck/overview.md
  app/kubernetes-ingress-controller/1.0.x/deployment/gke.md
Labels: pr/please review

#2508 LDAPs port fix
  app/_hub/kong-inc/ldap-auth-advanced/index.md
  app/_hub/kong-inc/ldap-auth/index.md
Labels: pr/please review

#2509 docs(plugins) Remove api fortress plugin
  app/_assets/images/icons/hub/api-fortress_api-fortress-http-log.png
  app/_hub/api-fortress/api-fortress-http-log/index.md
  app/_hub/plugins/compatibility/index.md
Labels: pr/please review

#2510 fix(systemd) Fix typo in systemd header
  app/2.2.x/systemd.md
Labels: pr/please review

#2503 docs(ee-immunity) Add icon for immunity and replace brain icon in nav
  app/_assets/images/icons/documentation/icn-immunity-color.svg
  app/_data/docs_nav_ee_2.2.x.yml
Labels: pr/please review

#2501 docs(kic) Updating plugins.konghq.com annotation to konghq.com/plugins
  app/_assets/images/docs/kubernetes-ingress-controller/kong-plugin-association1.png
  app/_assets/images/docs/kubernetes-ingress-controller/kong-plugin-association2.png
Labels: pr/please review
