Repository Kong/docs.konghq.com, pull requests merged in 2020-08, with the labels that each got.

#2187 Reedelk transformer 3rd-party plugin
  app/_assets/images/docs/plugins/reedelk-runtime-start.png
  app/_assets/images/icons/hub/reedelk_reedelk-transformer.png
  app/_hub/plugins/compatibility/index.md
  app/_hub/reedelk/reedelk-transformer/index.md
Labels: do not merge, pr/please review

#2200 Document response phase.
  app/2.1.x/go.md
  app/2.1.x/plugin-development/custom-logic.md
Labels: pr/please review

#2224 Release: 2.1.2
  README.md
  app/2.1.x/admin-api.md
  app/2.1.x/configuration.md
  app/2.1.x/db-less-admin-api.md
  app/_data/kong_versions.yml
  autodoc-admin-api/data.lua
  autodoc-admin-api/run.lua
  autodoc-cli/data.lua
  autodoc-cli/run.lua
  autodoc-conf/data.lua
  autodoc-conf/parser.lua
  autodoc-conf/run.lua
  autodoc-nav/docs_nav_1.4.x.yml.admin-api.in
  autodoc-nav/docs_nav_1.4.x.yml.head.in
  autodoc-nav/docs_nav_2.0.x.yml.admin-api.in
  autodoc-nav/docs_nav_2.0.x.yml.head.in
  autodoc-nav/docs_nav_2.1.x.yml.admin-api.in
  autodoc-nav/docs_nav_2.1.x.yml.head.in
  autodoc-nav/run.lua
  gulpfile.js
  ldoc/config.ld
  ldoc/filters.lua
  ldoc/json.ltp
  ldoc/ldoc.ltp
  ldoc/nav_yml.ltp
  package.json
Labels: pr/please review

#2226 DOCS-1243 fix end curly brace (customer issue)
  app/enterprise/1.3-x/developer-portal/working-with-templates.md
  app/enterprise/1.5.x/developer-portal/working-with-templates.md
  app/enterprise/2.1.x/developer-portal/working-with-templates.md
Labels: pr/please review

#2215 Docs/grpc plugins
  app/_data/docs_nav_ee_2.1.x.yml
  app/_hub/kong-inc/grpc-gateway/index.md
  app/_hub/kong-inc/grpc-web/index.md
  app/enterprise/2.1.x/plugins/grpc.md
Labels: pr/please review

#2243 Release: 2.1.3
  app/_data/kong_versions.yml
Labels: pr/please review

#2259 add link to Enrique's new blog post on Zipkin
  app/_hub/kong-inc/zipkin/index.md
Labels: pr/please review

#2258 docs(keyring) add clarification for the keyring functionality on hybr…
  app/enterprise/2.1.x/db-encryption.md
Labels: pr/please review

#2257 fix typo in deprecated Route by Header plugin
  app/_hub/kong-inc/route-by-header/index.md
Labels: pr/please review

#2236 doc(2.1.x) update brain-immunity topics
  app/_data/docs_nav_ee_2.1.x.yml
  app/enterprise/2.1.x/brain-immunity/alerts.md
  app/enterprise/2.1.x/brain-immunity/install-configure.md
  app/enterprise/2.1.x/brain-immunity/model-training
  app/enterprise/2.1.x/brain-immunity/overview.md
  app/enterprise/2.1.x/brain-immunity/slack-integration
Labels: do not merge, pr/wip

#2269 docs (release-notes) update version used in title
  app/enterprise/2.1.x/release-notes.md
Labels: pr/please review

#2261 docs (deployment) Classic deployment mode
  app/_data/docs_nav_ee_2.1.x.yml
  app/enterprise/2.1.x/deployment/classic-deployment.md
Labels: pr/please review

#2270 docs(docs-updates) What's New in the Docs
  app/_data/docs_nav_ee_2.1.x.yml
  app/enterprise/2.1.x/doc-updates.md
Labels: pr/please review

#2266 docs(hybrid-mode) use "database" instead of "storage" when enabling
  app/2.1.x/hybrid-mode.md
Labels: pr/please review

#2271 decompose migrations topics
  app/_data/docs_nav_ee_2.1.x.yml
  app/enterprise/2.1.x/deployment/upgrades/migrate-ce-to-ke.md
  app/enterprise/2.1.x/deployment/upgrades/migrations.md
Labels: pr/please review

#2281 docs(changelog) update for 2.1.3.1
  app/enterprise/changelog.md
Labels: pr/please review

#2278 docs(2.1.x) doc-updates
  app/enterprise/2.1.x/doc-updates.md
Labels: pr/please review
