Repository Kong/docs.konghq.com, pull requests merged in 2020-05, with the labels that each got.

#2022 more info on cookie_domain in dev portal auth sessions
  app/_hub/kong-inc/session/index.md
  app/enterprise/1.5.x/developer-portal/configuration/authentication/sessions.md
Labels: pr/please review

#2005 Portal Application Registration Plugin Docs
  app/_assets/images/icons/hub/kong-inc_application-registration.png
  app/_data/extensions/kong-inc/application-registration/versions.yml
  app/_hub/kong-inc/application-registration/index.md
Labels: pr/please review

#2067 mTLS plugin ca_certs generated example field incorrect
  app/_hub/kong-inc/mtls-auth/index.md
Labels: pr/wip

#1892 docs(portal): add helpers to template
  app/enterprise/1.3-x/developer-portal/working-with-templates.md
Labels: pr/wip

#2070 docs(support_policy) Created new topic for Support Policy
  app/enterprise/1.5.x/support-policy.md
Labels: do not merge
