Repository Kong/docs.konghq.com, pull requests merged in 2020-01, with the labels that each got.

#1702 Release: 1.2.3
  app/_data/kong_versions.yml
Labels: pr/do not merge, pr/please review

#1703 Release: 1.3.1
  app/_data/kong_versions.yml
Labels: pr/do not merge, pr/please review

#1704 Release: 1.4.3
  app/_data/kong_versions.yml
Labels: pr/do not merge, pr/please review

#1720 Studio 1.2
  app/_data/docs_nav_studio_1.2.x.yml
  app/_data/kong_versions.yml
  app/studio/1.2.x/best-practices.md
  app/studio/1.2.x/debugging-with-insomnia.md
  app/studio/1.2.x/dec-conf-studio.md
  app/studio/1.2.x/deploy-to-dev-portal.md
  app/studio/1.2.x/download-install.md
  app/studio/1.2.x/editing-specs.md
  app/studio/1.2.x/git-sync.md
  app/studio/1.2.x/graphql.md
  app/studio/1.2.x/index.md
  app/studio/1.2.x/linting.md
  app/studio/1.2.x/live-preview.md
  app/studio/1.2.x/overview.md
  app/studio/1.2.x/release-notes.md
  app/studio/1.2.x/user-interface.md
  app/studio/changelog.md
Labels: do not merge, release

#544 added ldaps parameter to ldap authentication documentation
  app/_hub/kong-inc/ldap-auth/index.md
Labels: pr/changes requested

#1671 doc(plugins) add doc for acme plugin
  app/_assets/images/icons/hub/kong-inc_acme.png
  app/_data/extensions/kong-inc/acme/versions.yml
  app/_hub/kong-inc/acme/index.md
Labels: pr/please review
