Repository Kong/docs.konghq.com, pull requests merged in 2020-09, with the labels that each got.

#2279 docs(getting started guide) Declarative config examples and instructions
  app/getting-started-guide/2.1.x/expose-services.md
  app/getting-started-guide/2.1.x/improve-performance.md
  app/getting-started-guide/2.1.x/load-balancing.md
  app/getting-started-guide/2.1.x/manage-teams.md
  app/getting-started-guide/2.1.x/overview.md
  app/getting-started-guide/2.1.x/prepare.md
  app/getting-started-guide/2.1.x/protect-services.md
  app/getting-started-guide/2.1.x/secure-services.md
Labels: pr/please review

#2287 docs(1.5.x) update TOC/topics for brain & immunity
  app/_data/docs_nav_ee_1.5.x.yml
  app/enterprise/1.5.x/brain-immunity/alerts.md
  app/enterprise/1.5.x/brain-immunity/auto-generated-specs.md
  app/enterprise/1.5.x/brain-immunity/install-configure.md
  app/enterprise/1.5.x/brain-immunity/model-training.md
  app/enterprise/1.5.x/brain-immunity/overview.md
  app/enterprise/1.5.x/brain-immunity/service-map.md
  app/enterprise/1.5.x/brain-immunity/slack-integration.md
Labels: pr/please review

#2288 docs(2.1.x) moving version info from B&I
  app/enterprise/2.1.x/brain-immunity/auto-generated-specs.md
  app/enterprise/2.1.x/brain-immunity/install-configure.md
  app/enterprise/2.1.x/brain-immunity/overview.md
Labels: pr/please review

#2291 docs(1.5.x) update install & version info for B&I
  app/enterprise/1.5.x/brain-immunity/install-configure.md
Labels: pr/please review

#2289 docs(mesh) Landing page and overview
  app/mesh/1.0.x/index.md
  app/mesh/1.0.x/overview.md
Labels: pr/please review

#2290 docs(mesh) Formatting and image name fixes for installation
  app/mesh/1.0.x/gettingstarted.md
  app/mesh/1.0.x/install.md
  app/mesh/1.0.x/installation/amazonlinux.md
  app/mesh/1.0.x/installation/centos.md
  app/mesh/1.0.x/installation/debian.md
  app/mesh/1.0.x/installation/docker.md
  app/mesh/1.0.x/installation/helm.md
  app/mesh/1.0.x/installation/kubernetes.md
  app/mesh/1.0.x/installation/macos.md
  app/mesh/1.0.x/installation/openshift.md
  app/mesh/1.0.x/installation/redhat.md
  app/mesh/1.0.x/installation/ubuntu.md
Labels: pr/please review

#2214 docs(deployment) adding marketplace installation
  app/_data/docs_nav_ee_2.1.x.yml
  app/enterprise/2.1.x/deployment/installation/overview.md
Labels: do not merge, pr/wip

#2301 fix(*) Fixes dependabot vulnerabilities
  Gemfile
  Gemfile.lock
  package-lock.json
Labels: dependencies

#2286 docs(autodoc-conf-ee) Create autodocs for EE and generate new file
  app/enterprise/2.1.x/property-reference.md
  autodoc-conf-ee/data.lua
  autodoc-conf-ee/parser.lua
  autodoc-conf-ee/run.lua
  package.json
Labels: Core Team review

#2312 fix consumer and route links in plugin template
  app/_layouts/extension.html
Labels: pr/please review

#2315 Docs/cors limits proxy link latest
  app/_hub/kong-inc/cors/index.md
  app/_layouts/extension.html
Labels: pr/please review

#2314 ACL link update; other fixes and copy edits
  app/_hub/kong-inc/acl/index.md
Labels: pr/please review

#2313 update link to schema topic
  app/_hub/kong-inc/request-validator/index.md
Labels: pr/please review

#2310 docs (ldap) service directory mapping workaround
  app/_hub/kong-inc/ldap-auth-advanced/index.md
  app/_hub/kong-inc/ldap-auth/index.md
  app/_includes/md/2.1.x/ldap/ldap-service-directory-mapping.md
  app/enterprise/2.1.x/kong-manager/authentication/ldap.md
  app/enterprise/2.1.x/release-notes.md
  app/enterprise/changelog.md
Labels: pr/please review

#2319 fix azure function name field
  app/_hub/kong-inc/azure-functions/0.1-x.md
  app/_hub/kong-inc/azure-functions/index.md
Labels: pr/please review

#2324 Release: 2.1.4
  app/_data/kong_versions.yml
Labels: pr/please review

#2327 Terraform integration module
  app/_hub/kong-inc/kong-terraform-aws/index.md
Labels: pr/please review

#2300 Set up External Portal Application Authentication with Azure AD OIDC
  app/_assets/images/docs/dev-portal/azure-app-details.png
  app/_assets/images/docs/dev-portal/azure-app-reg.png
  app/_assets/images/docs/dev-portal/azure-app.png
  app/_assets/images/docs/dev-portal/azure-manifest.png
  app/_assets/images/docs/dev-portal/jwt-converter.png
  app/_assets/images/docs/dev-portal/ms-azure-app-reg.png
  app/_data/docs_nav_ee_2.1.x.yml
  app/enterprise/2.1.x/developer-portal/administration/application-registration/3rd-party-oauth.md
  app/enterprise/2.1.x/developer-portal/administration/application-registration/azure-oidc-config.md
  app/enterprise/2.1.x/developer-portal/administration/application-registration/enable-application-registration.md
  app/enterprise/2.1.x/developer-portal/administration/application-registration/index.md
  app/enterprise/2.1.x/plugins/oidc-azuread.md
Labels: pr/please review

#2338 JWT w/auth0 add regions id in download pem cert url
  app/_hub/kong-inc/jwt/index.md
Labels: pr/please review
