Repository Kong/docs.konghq.com, pull requests merged in 2021-09, with the labels that each got.

#3165 docs: add udpingress to crd toc
  app/kubernetes-ingress-controller/2.0.x/references/custom-resources.md
Labels: KIC Team

#3058 [DOCU-1062][DOCU-1776][DOCU-1784] Support matrix/compatibility guide v1
  app/_assets/javascripts/app.js
  app/_assets/javascripts/compat-dropdown.js
  app/_assets/stylesheets/base.less
  app/_assets/stylesheets/compat-form.less
  app/_assets/stylesheets/index.less
  app/_data/docs_nav_konnect_platform.yml
  app/_data/tables/compat.json
  app/konnect-platform/compatibility/index.md
  app/konnect-platform/compatibility/plugins.md
  gulpfile.js
Labels: pr/wip

#3173 chore: Copy changes to Mesh 1.4
  app/mesh/1.4.x/installation/helm.md
Labels: pr/please review

#3174 docs: add prom metrics to kic 2.x toc
  app/_data/docs_nav_kic_2.0.x.yml
Labels: KIC Team

#3168 Update search to index latest versions [skip ci]
  algolia/config-full-docs.json
Labels: pr/please review

#3157 doc(kic) fix v1 Ingress specs
  app/kubernetes-ingress-controller/2.0.x/concepts/ingress-classes.md
  app/kubernetes-ingress-controller/2.0.x/guides/cert-manager.md
  app/kubernetes-ingress-controller/2.0.x/guides/configure-acl-plugin.md
  app/kubernetes-ingress-controller/2.0.x/guides/configuring-fallback-service.md
  app/kubernetes-ingress-controller/2.0.x/guides/configuring-health-checks.md
  app/kubernetes-ingress-controller/2.0.x/guides/configuring-https-redirect.md
  app/kubernetes-ingress-controller/2.0.x/guides/getting-started-istio.md
  app/kubernetes-ingress-controller/2.0.x/guides/getting-started.md
  app/kubernetes-ingress-controller/2.0.x/guides/prometheus-grafana.md
  app/kubernetes-ingress-controller/2.0.x/guides/redis-rate-limiting.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-consumer-credential-resource.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-external-service.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-kongclusterplugin-resource.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-kongingress-resource.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-kongplugin-resource.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-mtls-auth-plugin.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-oidc-plugin.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-rewrites.md
  app/kubernetes-ingress-controller/2.0.x/references/custom-resources.md
Labels: KIC Team

#3179 Remove duplicate KIC overview page and fix broken links
  app/_data/docs_nav_ee_2.5.x.yml
  app/_redirects
  app/enterprise/2.5.x/deployment/installation/kong-for-kubernetes.md
  app/enterprise/2.5.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.5.x/deployment/kong-for-kubernetes-enterprise.md
  app/enterprise/2.5.x/deployment/kubernetes-deployment-options.md
  app/enterprise/2.5.x/deployment/using-kong-for-kubernetes.md
Labels: pr/please review

#3163 [DOCU-1650][DOCU-1653] Konnect deploy Aug31
  app/konnect/deployment/index.md
  app/konnect/runtime-manager/gateway-runtime-conf.md
  app/konnect/runtime-manager/gateway-runtime-docker.md
  app/konnect/runtime-manager/gateway-runtime-kubernetes.md
  app/konnect/runtime-manager/runtime-parameter-reference.md
  app/konnect/updates.md
Labels: pr/please review

#3167 [DOCU-1796] Remove duplicate autodoc folders
  autodoc-admin-api/data.lua
  autodoc-admin-api/run.lua
  autodoc-cli/data.lua
  autodoc-cli/run.lua
  autodoc-conf/data.lua
  autodoc-conf/parser.lua
  autodoc-conf/run.lua
  ldoc/config.ld
  ldoc/filters.lua
  ldoc/json.ltp
  ldoc/ldoc.ltp
  ldoc/nav_yml.ltp
Labels: pr/please review

#3171 [DOCU-1775] Compat guide: Add help text based on selected product
  app/konnect-platform/compatibility/index.md
Labels: pr/please review

#3210 [DOCU-1821][DOCU-1758][DOCU-1710] Refactor plugin hub stylesheet
  app/_assets/css/hub.css
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/hub-landing-page.less
  app/_assets/stylesheets/index.less
  app/_hub/index.html
  app/_includes/head.html
  app/_includes/hub_cards.html
  app/_layouts/default.html
  gulpfile.js
  spec/plugin_spec.rb
Labels: pr/please review

#3216 Introduce a "no-icon" option for admonitions and remove "tip"
  app/_assets/stylesheets/page.less
  app/_hub/kong-inc/ldap-auth-advanced/index.md
  app/_hub/kong-inc/ldap-auth/index.md
  app/_hub/kong-inc/mocking/index.md
  app/_hub/kong-inc/statsd-advanced/index.md
  app/_hub/kong-inc/statsd/index.md
  app/contributing/markdown-rules.md
Labels: pr/please review

#3180 Gateway OSS Kubernetes docs: Fixing links and removing duplicate files
  app/_data/docs_nav_ce_2.6.x.yml
  app/_redirects
  app/gateway-oss/2.6.x/kong-for-kubernetes/changelog.md
  app/gateway-oss/2.6.x/kong-for-kubernetes/index.md
  app/gateway-oss/2.6.x/kong-for-kubernetes/install.md
  app/gateway-oss/2.6.x/kong-for-kubernetes/using-kong-for-kubernetes.md
Labels: pr/please review

#3209 docs: cleaning up KIC 2.0 docs "concepts" pages
  app/kubernetes-ingress-controller/2.0.x/concepts/deployment.md
  app/kubernetes-ingress-controller/2.0.x/concepts/design.md
  app/kubernetes-ingress-controller/2.0.x/concepts/ha-and-scaling.md
  app/kubernetes-ingress-controller/2.0.x/concepts/ingress-classes.md
  app/kubernetes-ingress-controller/2.0.x/concepts/ingress-versions.md
  app/kubernetes-ingress-controller/2.0.x/concepts/k4k8s-with-kong-enterprise.md
Labels: KIC Team

#3213 docs: cleaning up KIC 2.0 docs "CRD" guides
  app/_data/docs_nav_kic_2.0.x.yml
  app/kubernetes-ingress-controller/2.0.x/guides/using-consumer-credential-resource.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-external-service.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-ingress-with-grpc.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-kong-with-knative.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-kongclusterplugin-resource.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-kongingress-resource.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-kongplugin-resource.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-mtls-auth-plugin.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-oidc-plugin.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-rewrites.md
  app/kubernetes-ingress-controller/2.0.x/guides/using-tcpingress.md
Labels: KIC Team

#3225 [DOCU-1837] Fix broken links
  Makefile
  app/404.html
  app/_data/extensions/kong-inc/hmac-auth/versions.yml
  app/_data/extensions/kong-inc/ldap-auth/versions.yml
  app/_data/extensions/kong-inc/proxy-cache/versions.yml
  app/_data/extensions/kong-inc/upstream-tls/versions.yml
  app/_hub/kong-inc/canary/0.36-x.md
  app/_hub/kong-inc/canary/1.3-x.md
  app/_hub/kong-inc/canary/index.md
  app/_hub/kong-inc/jwt-signer/index.md
  app/_hub/kong-inc/prometheus/0.1-x.md
  app/_hub/kong-inc/prometheus/0.8.x.md
  app/_hub/kong-inc/prometheus/0.9.x.md
  app/_hub/kong-inc/prometheus/index.md
  app/_hub/kong-inc/session/1.2-x.md
  app/_hub/kong-inc/session/2.2-x.md
  app/_hub/kong-inc/session/index.md
  app/_hub/kong-inc/zipkin/0.1-x.md
  app/_hub/kong-inc/zipkin/1.0.x.md
  app/_hub/kong-inc/zipkin/1.1.x.md
  app/_hub/kong-inc/zipkin/1.2.x.md
  app/_hub/kong-inc/zipkin/1.3.x.md
  app/_hub/kong-inc/zipkin/index.md
  app/_includes/md/plugins-hub/log_custom_fields_by_lua.md
  app/_includes/md/rpm.md
  app/_redirects
  app/enterprise/0.36-x/admin-api/rbac/reference.md
  app/enterprise/1.5.x/deployment/migrations.md
  app/enterprise/1.5.x/introduction/index.md
  app/enterprise/2.1.x/introduction/index.md
  app/enterprise/2.1.x/release-notes.md
  app/enterprise/2.3.x/auth.md
  app/enterprise/2.3.x/kong-manager/authentication/ldap.md
  app/enterprise/2.3.x/secure-admin-api.md
  app/enterprise/2.4.x/auth.md
  app/enterprise/2.4.x/kong-manager/authentication/ldap.md
  app/enterprise/2.4.x/secure-admin-api.md
  app/enterprise/2.5.x/auth.md
  app/enterprise/2.5.x/kong-manager/authentication/ldap.md
  app/enterprise/2.5.x/secure-admin-api.md
  app/enterprise/changelog.md
  app/gateway-oss/0.10.x/getting-started/adding-consumers.md
  app/gateway-oss/0.11.x/getting-started/adding-consumers.md
  app/gateway-oss/0.12.x/getting-started/adding-consumers.md
  app/gateway-oss/0.13.x/getting-started/adding-consumers.md
  app/gateway-oss/0.14.x/getting-started/adding-consumers.md
  app/gateway-oss/1.0.x/getting-started/adding-consumers.md
  app/gateway-oss/1.1.x/getting-started/adding-consumers.md
  app/gateway-oss/1.2.x/getting-started/adding-consumers.md
  app/gateway-oss/1.3.x/getting-started/adding-consumers.md
  app/gateway-oss/1.4.x/getting-started/adding-consumers.md
  app/gateway-oss/1.5.x/getting-started/adding-consumers.md
  app/gateway-oss/2.0.x/getting-started/adding-consumers.md
  app/gateway-oss/2.1.x/getting-started/adding-consumers.md
  app/gateway-oss/2.1.x/upgrading.md
  app/gateway-oss/2.2.x/getting-started/adding-consumers.md
  app/gateway-oss/2.3.x/getting-started/adding-consumers.md
  app/gateway-oss/2.4.x/getting-started/adding-consumers.md
  app/gateway-oss/2.5.x/getting-started/adding-consumers.md
Labels: pr/please review

#3197 [DOCU-1814] Fix link and other issues in KIC 2.0 prometheus guide
  app/kubernetes-ingress-controller/2.0.x/guides/prometheus-grafana.md
Labels: pr/please review

#3234 Plugin page title adjustment
  app/_includes/head.html
  app/_layouts/default.html
Labels: pr/please review

#3224 docs: major updates of istio guide
  app/kubernetes-ingress-controller/2.0.x/guides/getting-started-istio.md
Labels: KIC Team

#3238 Chore/KIC v2 beta metadata
  app/_layouts/docs-v2.html
  app/_redirects
Labels: pr/please review

#3233 [DOCU-1646] Remove redirect-only /plugins folder
  Makefile
  app/_redirects
  app/plugins/acl.md
  app/plugins/aws-lambda.md
  app/plugins/azure-functions.md
  app/plugins/basic-authentication.md
  app/plugins/bot-detection.md
  app/plugins/correlation-id.md
  app/plugins/cors.md
  app/plugins/datadog.md
  app/plugins/ee-canary-release.md
  app/plugins/ee-forward-proxy.md
  app/plugins/ee-ldap-authentication.md
  app/plugins/ee-oauth2-introspection.md
  app/plugins/ee-openid-connect-rp.md
  app/plugins/ee-openid-connect.md
  app/plugins/ee-proxy-caching.md
  app/plugins/ee-rate-limiting.md
  app/plugins/ee-request-transformer.md
  app/plugins/ee-response-transformer.md
  app/plugins/ee-statsd.md
  app/plugins/file-log.md
  app/plugins/galileo.md
  app/plugins/hmac-authentication.md
  app/plugins/http-log.md
  app/plugins/index.md
  app/plugins/ip-restriction.md
  app/plugins/jwt.md
  app/plugins/key-authentication.md
  app/plugins/ldap-authentication.md
  app/plugins/loggly.md
  app/plugins/mashape-analytics.md
  app/plugins/oauth2-authentication.md
  app/plugins/openwhisk.md
  app/plugins/prometheus.md
  app/plugins/rate-limiting.md
  app/plugins/request-size-limiting.md
  app/plugins/request-termination.md
  app/plugins/request-transformer.md
  app/plugins/response-rate-limiting.md
  app/plugins/response-transformer.md
  app/plugins/serverless-functions.md
  app/plugins/statsd.md
  app/plugins/syslog.md
  app/plugins/tcp-log.md
  app/plugins/udp-log.md
  app/plugins/zipkin.md
Labels: pr/please review

#3229 [DOCU-1843] Guide for using defaults with decK
  app/_data/docs_nav_deck_1.8.x.yml
  app/deck/1.8.x/guides/defaults.md
Labels: pr/please review

#3275 docs(aws-lambda) update aws lambda docs to match the latest plugin version
  app/_hub/kong-inc/aws-lambda/3.5.x.md
  app/_hub/kong-inc/aws-lambda/index.md
Labels: pr/please review

#3268 docs: add istio version compat table
  app/kubernetes-ingress-controller/2.0.x/guides/getting-started-istio.md
  app/kubernetes-ingress-controller/2.0.x/references/version-compatibility.md
Labels: KIC Team
