Repository Kong/docs.konghq.com, pull requests merged in 2021-04, with the labels that each got.

#2732 (no ticket) Fix edit this page links and adjust spacing
  app/_assets/stylesheets/pages/docs.less
  app/_layouts/docs-v2.html
  app/_layouts/extension.html
Labels: pr/please review

#2735 added ee 2.1.4.5 changelog entry
  app/enterprise/changelog.md
Labels: pr/please review

#2733 (no ticket) Fix key_name syntax for key auth plugins
  app/_hub/kong-inc/key-auth-enc/1.0.x.md
  app/_hub/kong-inc/key-auth-enc/index.md
  app/_hub/kong-inc/key-auth/0.2.x.md
  app/_hub/kong-inc/key-auth/2.1.x.md
  app/_hub/kong-inc/key-auth/2.2.x.md
  app/_hub/kong-inc/key-auth/index.md
  app/_includes/hub-examples.html
Labels: pr/please review

#2730 http-log headers example
  app/_hub/kong-inc/http-log/index.md
Labels: pr/please review

#2719 [DOCU-678] JWT plugin datatypes
  app/_hub/kong-inc/jwt/index.md
Labels: pr/please review

#2747 [DOCU-670][DOCU-481] GraphQL proxy adv plugin datatypes, menu fix
  app/_data/extensions/kong-inc/graphql-proxy-cache-advanced/versions.yml
  app/_hub/kong-inc/graphql-proxy-cache-advanced/index.md
Labels: pr/please review

#2746 [DOCU-679] Session plugin add datatypes
  app/_hub/kong-inc/session/index.md
Labels: pr/please review

#2751 [DOCU-685] mTLS plugin add datatypes, formatting, editing
  app/_hub/kong-inc/mtls-auth/index.md
Labels: pr/please review

#2765 Update EE metadata to latest patch version
  app/_data/kong_versions.yml
Labels: pr/please review

#2764 Optum 3rd party plugin expose specs
  app/_hub/optum/kong-spec-expose/index.md
Labels: pr/please review

#2763 Optum 3rd party plugin JWT
  app/_hub/optum/kong-upstream-jwt/index.md
Labels: pr/please review

#2762 Optum 3rd party plugin
  app/_hub/optum/kong-response-size-limiting/index.md
Labels: pr/please review

#2761 Optum 3rd party plugin
  app/_hub/optum/kong-service-virtualization/index.md
Labels: pr/please review

#2760 Inspur 3rd party plugin
  app/_hub/inspur/apig-request-transformer/index.md
Labels: pr/please review

#2759 Inspur 3rd party plugin
  app/_hub/inspur/apig-response-transform/index.md
Labels: pr/please review

#2758 Kongverge 3rd party plugin
  app/_hub/justeat/kongverge/index.md
Labels: pr/please review

#2757 Splunk 3rd party plugin
  app/_hub/optum/kong-splunk-log/index.md
Labels: pr/please review

#2756 API Transformer 3rd party plugin
  app/_hub/qnap/api-transformer/index.md
Labels: pr/please review

#2755 Okta integration remove incompatible versions
  app/_hub/okta/okta/index.md
Labels: pr/please review

#2752 (no ticket, fix) Simplify Dockerfile and Makefile
  Dockerfile
  Makefile
Labels: pr/please review

#2769 Update decK version to 1.6.0 and adjust dockerfile with build fix
  Dockerfile
  app/_data/kong_versions.yml
Labels: pr/please review

#2775 fix(external-plugins) add note for extra dependencies for JS plugins
  app/gateway-oss/2.4.x/external-plugins.md
Labels: pr/please review

#2778 Update 3rd-party-oauth.md
  app/enterprise/2.1.x/developer-portal/administration/application-registration/3rd-party-oauth.md
Labels: pr/please review

#2777 Update 3rd-party-oauth.md
  app/enterprise/2.2.x/developer-portal/administration/application-registration/3rd-party-oauth.md
Labels: pr/please review

#2804 [DOCU-1415] Update SW license link on EE install pages
  app/enterprise/2.3.x/deployment/installation/amazon-linux-2.md
  app/enterprise/2.3.x/deployment/installation/amazon-linux.md
  app/enterprise/2.3.x/deployment/installation/centos.md
  app/enterprise/2.3.x/deployment/installation/docker.md
  app/enterprise/2.3.x/deployment/installation/kong-for-kubernetes.md
  app/enterprise/2.3.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.3.x/deployment/installation/rhel.md
  app/enterprise/2.3.x/deployment/installation/ubuntu.md
Labels: pr/wip

#2807 [DOCU-14O5] OPA plugin icon
  app/_assets/images/icons/hub/kong-inc_opa.png
Labels: pr/please review

#2811 [DOCU-1545] Enable Dev Portal fix install instructions
  app/enterprise/2.3.x/deployment/installation/docker.md
Labels: pr/please review

#2668 CLD-2502: chore(download) migrate downloads off of bintray
  app/_includes/md/deb.md
  app/_includes/md/installation.md
  app/_includes/md/rpm.md
  app/install/aws-linux.md
  app/install/centos.md
  app/install/debian.md
  app/install/redhat.md
  app/install/ubuntu.md
  jekyll-dev.yml
  jekyll.yml
Labels: Core Team review, do not merge, pr/please review

#2815 Bintray migration: Docker updates
  app/_data/kong_versions.yml
  app/enterprise/1.5.x/deployment/installation/docker.md
  app/enterprise/2.1.x/deployment/installation/docker.md
  app/enterprise/2.2.x/deployment/installation/docker.md
  app/enterprise/2.3.x/deployment/installation/docker.md
Labels: pr/please review

#2808 Fix typo under kubernetes-ingress-controller deployment concepts
  app/kubernetes-ingress-controller/1.0.x/concepts/deployment.md
  app/kubernetes-ingress-controller/1.1.x/concepts/deployment.md
  app/kubernetes-ingress-controller/1.2.x/concepts/deployment.md
Labels: pr/please review, typo

#2818 [DOCU-1434] Fix declarative config example syntax
  app/_includes/hub-examples.html
Labels: pr/please review

#2820 [DOCU-1429] Fix footer link to oss gateway
  app/_includes/footer.html
Labels: pr/please review
