Repository Kong/docs.konghq.com, pull requests merged in 2021-08, with the labels that each got.

#3094 [DOCU-1661]Updates support policy table by adding the 2.5.x.x release
  app/enterprise/2.5.x/support-policy.md
Labels: pr/please review

#3095 [DOCU-1671]Eradicates RedHat from site
  app/_data/docs_nav_ee_0.31-x.yml
  app/_data/docs_nav_ee_0.32-x.yml
  app/_data/docs_nav_ee_0.33-x.yml
  app/_data/docs_nav_ee_0.34-x.yml
  app/_data/docs_nav_ee_2.1.x.yml
  app/_data/docs_nav_ee_2.2.x.yml
  app/_data/docs_nav_ee_2.3.x.yml
  app/_data/docs_nav_ee_2.4.x.yml
  app/_data/docs_nav_ee_2.5.x.yml
  app/_data/docs_nav_mesh_1.0.x.yml
  app/_data/docs_nav_mesh_1.1.x.yml
  app/_data/docs_nav_mesh_1.2.x.yml
  app/_data/docs_nav_mesh_1.3.x.yml
  app/_includes/md/rpm.md
  app/enterprise/0.31-x/postgresql-redhat.md
  app/enterprise/0.32-x/postgresql-redhat.md
  app/enterprise/0.33-x/postgresql-redhat.md
  app/enterprise/0.34-x/postgresql-redhat.md
  app/enterprise/2.1.x/deployment/installation/overview.md
  app/enterprise/2.2.x/deployment/installation/overview.md
  app/enterprise/2.3.x/deployment/installation/overview.md
  app/enterprise/2.4.x/deployment/installation/overview.md
  app/enterprise/2.5.x/deployment/installation/overview.md
  app/gateway-oss/2.2.x/kong-user.md
  app/gateway-oss/2.3.x/kong-user.md
  app/gateway-oss/2.4.x/kong-user.md
  app/gateway-oss/2.5.x/kong-user.md
  app/mesh/1.0.x/install.md
  app/mesh/1.0.x/installation/docker.md
  app/mesh/1.0.x/installation/kubernetes.md
  app/mesh/1.0.x/installation/openshift.md
  app/mesh/1.0.x/installation/redhat.md
  app/mesh/1.1.x/install.md
  app/mesh/1.1.x/installation/docker.md
  app/mesh/1.1.x/installation/kubernetes.md
  app/mesh/1.1.x/installation/openshift.md
  app/mesh/1.1.x/installation/redhat.md
  app/mesh/1.2.x/install.md
  app/mesh/1.2.x/installation/docker.md
  app/mesh/1.2.x/installation/kubernetes.md
  app/mesh/1.2.x/installation/openshift.md
  app/mesh/1.2.x/installation/redhat.md
  app/mesh/1.3.x/install.md
  app/mesh/1.3.x/installation/docker.md
  app/mesh/1.3.x/installation/kubernetes.md
  app/mesh/1.3.x/installation/openshift.md
  app/mesh/1.3.x/installation/redhat.md
Labels: pr/please review

#3106 [DOCU-1705] Updates ee changelog with 5 new minor releases
  app/enterprise/2.3.x/deployment/hybrid-mode.md
  app/enterprise/2.4.x/deployment/hybrid-mode.md
  app/enterprise/changelog.md
Labels: pr/wip

#3121 docs: udp guide for kic v2
  app/kubernetes-ingress-controller/2.0.x/guides/using-udpingress.md
Labels: KIC Team

#3123 docs: add a UDPIngress guide
  app/_data/docs_nav_kic_2.0.x.yml
  app/kubernetes-ingress-controller/2.0.x/guides/using-udpingress.md
Labels: KIC Team
