Repository Kong/docs.konghq.com, pull requests merged in 2021-03, with the labels that each got.

#2631 [DOCS-1607] Port 2.2 dev portal key auth self-hosted to 2.3
  app/_data/docs_nav_ee_2.3.x.yml
  app/enterprise/2.3.x/developer-portal/administration/application-registration/3rd-party-oauth.md
  app/enterprise/2.3.x/developer-portal/administration/application-registration/auth-provider-strategy.md
  app/enterprise/2.3.x/developer-portal/administration/application-registration/azure-oidc-config.md
  app/enterprise/2.3.x/developer-portal/administration/application-registration/enable-application-registration.md
  app/enterprise/2.3.x/developer-portal/administration/application-registration/enable-key-auth-plugin.md
  app/enterprise/2.3.x/developer-portal/administration/application-registration/index.md
Labels: pr/please review

#2649 [DOCS-1604] remove erroneous statements Redis not supported
  app/_hub/kong-inc/openid-connect/index.md
Labels: pr/please review

#2646 follow up to public contributor PR, fix other versions
  app/gateway-oss/2.1.x/pdk/kong.response.md
  app/gateway-oss/2.2.x/pdk/kong.response.md
Labels: pr/please review

#2595 Kafka Logging plugin datatypes
  app/_hub/kong-inc/kafka-log/1.3-x.md
  app/_hub/kong-inc/kafka-log/index.md
Labels: pr/please review

#2654 [DOCS-1601] Go plugin doc corrections per customer issues
  app/enterprise/2.3.x/external-plugins.md
  app/gateway-oss/2.3.x/external-plugins.md
Labels: pr/please review

#2647 StatsD Advanced plugin add datatypes
  app/_hub/kong-inc/statsd-advanced/index.md
Labels: pr/please review

#2650 Request Validator plugin add datatypes
  app/_hub/kong-inc/request-validator/index.md
Labels: pr/please review

#2655 Docs/update deleting an entity
  app/enterprise/0.35-x/plugin-development/custom-entities.md
  app/enterprise/0.36-x/plugin-development/custom-entities.md
  app/enterprise/1.3-x/plugin-development/custom-entities.md
  app/enterprise/1.5.x/plugin-development/custom-entities.md
  app/enterprise/2.1.x/plugin-development/custom-entities.md
  app/enterprise/2.2.x/plugin-development/custom-entities.md
  app/gateway-oss/1.0.x/plugin-development/custom-entities.md
  app/gateway-oss/1.1.x/plugin-development/custom-entities.md
  app/gateway-oss/1.3.x/plugin-development/custom-entities.md
  app/gateway-oss/1.4.x/plugin-development/custom-entities.md
  app/gateway-oss/1.5.x/plugin-development/custom-entities.md
  app/gateway-oss/2.0.x/plugin-development/custom-entities.md
  app/gateway-oss/2.1.x/plugin-development/custom-entities.md
  app/gateway-oss/2.2.x/plugin-development/custom-entities.md
Labels: pr/please review

#2604 Response Transformer datatypes
  app/_hub/kong-inc/response-transformer/index.md
Labels: pr/please review, pr/wip

#2658 Release: 2.3.3
  app/_data/kong_versions.yml
Labels: pr/please review

#2659 chore(*) update release metadata for 2.2.2
  app/_data/kong_versions.yml
Labels: pr/please review

#2597 Kafka Upstream plugin datatypes, schema corrections to params
  app/_hub/kong-inc/kafka-upstream/index.md
Labels: pr/please review

#2665 (no ticket) Add feedback widget to landing page
  app/_layouts/landing-page.html
Labels: pr/please review

#2670 [DOCS-1605] Optional license, new image for k8s db-backed installation
  app/enterprise/2.3.x/deployment/installation/kong-on-kubernetes.md
Labels: pr/please review

#2676 [DOCS-1463] Add group and roles parameters
  app/_hub/kong-inc/openid-connect/index.md
Labels: pr/please review

#2677 [DOCS-1625] Konnect: Add step for HTTP method when adding a route
  app/konnect/getting-started/implement-service.md
  app/konnect/servicehub/manage-services.md
Labels: pr/please review

#2678 Stats d take2
  app/_hub/kong-inc/statsd-advanced/index.md
  app/_hub/kong-inc/statsd/index.md
Labels: pr/please review

#2656 [DOCS-1612] update plugin log format
  app/_data/extensions/kong-inc/file-log/versions.yml
  app/_data/extensions/kong-inc/http-log/versions.yml
  app/_data/extensions/kong-inc/loggly/versions.yml
  app/_data/extensions/kong-inc/syslog/versions.yml
  app/_data/extensions/kong-inc/tcp-log/versions.yml
  app/_data/extensions/kong-inc/udp-log/versions.yml
  app/_hub/kong-inc/file-log/1.0.x.md
  app/_hub/kong-inc/file-log/index.md
  app/_hub/kong-inc/http-log/1.0.x.md
  app/_hub/kong-inc/http-log/index.md
  app/_hub/kong-inc/loggly/1.0.x.md
  app/_hub/kong-inc/loggly/index.md
  app/_hub/kong-inc/syslog/1.0.x.md
  app/_hub/kong-inc/syslog/index.md
  app/_hub/kong-inc/tcp-log/1.0.x.md
  app/_hub/kong-inc/tcp-log/index.md
  app/_hub/kong-inc/udp-log/1.0.x.md
  app/_hub/kong-inc/udp-log/index.md
  app/_includes/md/plugins-hub/json-object-log.md
  app/_includes/md/plugins-hub/log-format.md
Labels: pr/please review

#2660 [DOCS-1248] Redesign docs
  app/_assets/stylesheets/accordion.less
  app/_assets/stylesheets/dropdown.less
  app/_assets/stylesheets/header-v2.less
  app/_assets/stylesheets/page.less
  app/_assets/stylesheets/pages/docs.less
  app/_assets/stylesheets/variables.less
  app/_data/docs_nav_ce_2.0.x.yml
  app/_data/docs_nav_ce_2.1.x.yml
  app/_data/docs_nav_ce_2.2.x.yml
  app/_data/docs_nav_ce_2.3.x.yml
  app/_data/docs_nav_ee_2.1.x.yml
  app/_data/docs_nav_ee_2.2.x.yml
  app/_data/docs_nav_ee_2.3.x.yml
  app/_data/docs_nav_kic_1.0.x.yml
  app/_data/docs_nav_kic_1.1.x.yml
  app/_data/docs_nav_konnect.yml
  app/_includes/accordion-item.html
  app/_includes/breadcrumbs.html
  app/_includes/docs-sidebar.html
  app/_includes/nav-v2.html
  app/_layouts/docs-v2.html
  jekyll-dev.yml
  jekyll.yml
Labels: pr/wip

#2681 [DOCS-1665] Fix license command and clean up Dev Portal setup
  app/enterprise/2.3.x/deployment/installation/amazon-linux-2.md
  app/enterprise/2.3.x/deployment/installation/amazon-linux.md
  app/enterprise/2.3.x/deployment/installation/centos.md
  app/enterprise/2.3.x/deployment/installation/docker.md
  app/enterprise/2.3.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.3.x/deployment/installation/rhel.md
  app/enterprise/2.3.x/deployment/installation/ubuntu.md
  app/enterprise/2.3.x/deployment/licenses/deploy-license.md
Labels: pr/please review

#2652 [DOCS-1582] updated titles, version numbers, and minor formatting issues for 2.3.x
  app/_data/docs_nav_ee_2.3.x.yml
  app/enterprise/2.3.x/deployment/upgrades/migrate-ce-to-ke.md
  app/enterprise/2.3.x/deployment/upgrades/migrations.md
Labels: pr/wip

#2386 [DOCS-1260] Add cookie_domain to Dev Portal session config example
  app/_assets/images/docs/dev-portal/portal-settings-auth-plugin.png
  app/enterprise/2.1.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.1.x/developer-portal/configuration/authentication/basic-auth.md
  app/enterprise/2.1.x/developer-portal/configuration/authentication/sessions.md
  app/enterprise/2.2.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.2.x/developer-portal/configuration/authentication/basic-auth.md
  app/enterprise/2.3.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.3.x/developer-portal/configuration/authentication/basic-auth.md
Labels: pr/wip

#2694 [DOCS-1684] legacy portal no longer supported 2.1 release notes
  app/enterprise/2.1.x/release-notes.md
Labels: pr/please review

#2695 [DOCS-1368] Route transformer plugin version menu
  app/_data/extensions/kong-inc/route-transformer-advanced/versions.yml
  app/_hub/kong-inc/route-transformer-advanced/index.md
Labels: pr/please review

#2696 [DOCS-1674] fixed link issue redirecting to wrong version
  app/enterprise/2.1.x/deployment/classic-deployment.md
  app/enterprise/2.2.x/deployment/classic-deployment.md
  app/enterprise/2.3.x/deployment/classic-deployment.md
Labels: pr/please review

#2701 [DOCS-1685] Konnect: Renewing certs
  app/_data/docs_nav_konnect.yml
  app/konnect/getting-started/configure-runtime.md
  app/konnect/runtime-manager/kong-gateway-runtime.md
  app/konnect/runtime-manager/renew-certificates.md
Labels: pr/please review

#2705 [DOCS-1646] gRPC Web plugin add datatypes
  app/_hub/kong-inc/grpc-web/index.md
Labels: pr/please review

#2704 [DOCS-1654] Correlation ID plugin add datatypes; corrections
  app/_hub/kong-inc/correlation-id/index.md
Labels: pr/please review

#2707 [DOCS-1690] Switch Manager and Admin API tab order for 2.3.x
  app/getting-started-guide/2.3.x/dev-portal.md
  app/getting-started-guide/2.3.x/expose-services.md
  app/getting-started-guide/2.3.x/improve-performance.md
  app/getting-started-guide/2.3.x/load-balancing.md
  app/getting-started-guide/2.3.x/prepare.md
  app/getting-started-guide/2.3.x/protect-services.md
  app/getting-started-guide/2.3.x/secure-services.md
Labels: pr/please review

#2698 [DOCS-1650] Konnect runtime manager: Helm config instructions
  app/konnect/runtime-manager/kong-gateway-runtime.md
Labels: pr/please review

#2709 [DOCS-1692] Serverless functions plugin sandbox *.os clarification
  app/_hub/kong-inc/serverless-functions/index.md
Labels: pr/please review

#2714 (no ticket) Add links to github from main doc set
  app/_assets/stylesheets/pages/docs.less
  app/_layouts/docs-v2.html
  app/_layouts/extension.html
Labels: pr/please review

#2711 [DOCS-1647] Datadog add datatypes
  app/_hub/kong-inc/datadog/index.md
Labels: pr/please review

#2715 [DOCS-1637] LDAP plugin datatypes; advertise enterprise version of plugin
  app/_hub/kong-inc/ldap-auth-advanced/index.md
  app/_hub/kong-inc/ldap-auth/index.md
Labels: pr/please review

#2717 (no ticket) Remove empty readmes from ee docs [skip ci]
  app/enterprise/0.35-x/README.md
  app/enterprise/0.36-x/README.md
  app/enterprise/1.3-x/README.md
  app/enterprise/1.5.x/README.md
  app/enterprise/2.1.x/README.md
  app/enterprise/2.2.x/README.md
  app/enterprise/2.3.x/README.md
Labels: pr/please review

#2718 [DOCS-1640] OAuth2 Introspection plugin add datatypes per schema
  app/_hub/kong-inc/oauth2-introspection/index.md
Labels: pr/please review

#2706 [DOCS-1660] Vault plugin add datatypes
  app/_hub/kong-inc/vault-auth/index.md
Labels: pr/wip

#2630 [DOCS-1608][DOCS-1609] Patch release notes for 2.1.4.4, 2.2.1.1, and 1.5.0.10
  app/enterprise/changelog.md
Labels: do not merge

#2653 [DOCS-1583] added upgrade guide for 2.3.x and removed prior versions
  app/gateway-oss/2.3.x/upgrading.md
Labels: do not merge, pr/please review

#2725 (chore) Update kramdown
  Gemfile.lock
  package-lock.json
Labels: pr/please review

#2723 Fixing issues with the 2.3.3.0 changelog
  app/enterprise/changelog.md
Labels: pr/wip

#2724 [DOCS-1361] Line numbers for codeblocks
  CONTRIBUTING.md
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/page.less
  app/_assets/stylesheets/pages/docs.less
  app/enterprise/2.3.x/deployment/installation/docker.md
  jekyll-dev.yml
  jekyll.yml
Labels: pr/please review
