Repository Kong/docs.konghq.com, pull requests merged in 2021-12, with the labels that each got.

#3373 doc(router) add docs for TLS passthrough
  app/gateway/2.7.x/admin-api/index.md
  app/gateway/2.7.x/reference/proxy.md
Labels: release, gateway OSS

#3431 [DOCU-2055] Prepare Konnect Okta doc for GA
  app/konnect/org-management/okta-idp.md
  app/konnect/updates.md
Labels: release

#3454 chore/ Update 2.7 scope
  app/_data/docs_nav_gateway_2.6.x.yml
  jekyll-dev.yml
  jekyll.yml
Labels: release, gateway EE, gateway OSS

#3367 [TDX-1628] Dev Portal: Archive a Service Version
  app/konnect/servicehub/manage-services.md
Labels: release, do not merge, gateway EE

#3424 [DOCU-2061] Add tls_passthrough to supported plugins
  app/_hub/kong-inc/datadog/index.md
  app/_hub/kong-inc/http-log/index.md
  app/_hub/kong-inc/loggly/index.md
  app/_hub/kong-inc/statsd/index.md
  app/_hub/kong-inc/syslog/index.md
  app/_hub/kong-inc/tcp-log/index.md
  app/_hub/kong-inc/udp-log/index.md
Labels: release, gateway EE, gateway OSS

#3459 [DOCU-2079] Gateway request count report
  app/gateway/2.7.x/admin-api/licenses/examples.md
  app/gateway/2.7.x/admin-api/licenses/reference.md
  app/gateway/2.7.x/plan-and-deploy/licenses/report.md
Labels: release, gateway EE

#3472 [DOCU-2082] Enterprise install & download instructions for Debian
  app/gateway/2.7.x/install-and-run/debian.md
Labels: release, gateway EE

#3474 chore/Sync 2.6.x and 2.7.x directories
  app/_data/docs_nav_gateway_2.7.x.yml
  app/gateway/2.7.x/configure/graphql-quickstart.md
  app/gateway/2.7.x/developer-portal/working-with-templates.md
  app/gateway/2.7.x/install-and-run/amazon-linux.md
  app/gateway/2.7.x/install-and-run/centos.md
  app/gateway/2.7.x/install-and-run/helm.md
  app/gateway/2.7.x/install-and-run/index.md
  app/gateway/2.7.x/install-and-run/macos.md
  app/gateway/2.7.x/install-and-run/rhel.md
  app/gateway/2.7.x/install-and-run/ubuntu.md
  app/gateway/2.7.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
  app/gateway/2.7.x/plan-and-deploy/security/db-encryption.md
  app/gateway/2.7.x/plugin-development/access-the-datastore.md
  app/gateway/2.7.x/plugin-development/admin-api.md
  app/gateway/2.7.x/plugin-development/custom-entities.md
  app/gateway/2.7.x/plugin-development/custom-logic.md
  app/gateway/2.7.x/plugin-development/distribution.md
  app/gateway/2.7.x/plugin-development/entities-cache.md
  app/gateway/2.7.x/plugin-development/file-structure.md
  app/gateway/2.7.x/plugin-development/index.md
  app/gateway/2.7.x/plugin-development/plugin-configuration.md
  app/gateway/2.7.x/plugin-development/tests.md
  app/gateway/2.7.x/reference/external-plugins.md
Labels: release

#3464 [DOCU-2048] OIDC use case guides updates
  app/_assets/images/docs/ee/plugins/oidc-use-case/OIDCaccess.png
  app/_assets/images/docs/ee/plugins/oidc-use-case/OIDCsession.png
  app/_assets/images/docs/ee/plugins/oidc-use-case/OIDCsignin.png
  app/gateway/2.7.x/configure/auth/oidc-okta.md
  app/gateway/2.7.x/configure/auth/oidc-use-case.md
Labels: release, gateway EE

#3491 [DOCU-2091] Encrypted cache for data planes
  app/gateway/2.7.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
  app/gateway/2.7.x/plan-and-deploy/hybrid-mode/index.md
Labels: release, gateway EE, review:general, review:copyedit

#3494 [DOCU-2053] Generate configuration reference for Gateway 2.7
  app/gateway/2.7.x/reference/configuration.md
  autodoc-conf-ee/run.lua
Labels: release, review:general

#3386 docs(c*): cassandra deprecation
  app/_hub/kong-inc/session/index.md
  app/_includes/md/enterprise/cassandra-deprecation.md
  app/_includes/md/gateway/setup.md
  app/_includes/md/installation.md
  app/deck/pre-1.7/faqs.md
  app/enterprise/references/rate-limiting.md
  app/gateway/2.7.x/get-started/quickstart/index.md
  app/gateway/2.7.x/install-and-run/docker.md
  app/gateway/2.7.x/install-and-run/macos.md
  app/gateway/2.7.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
  app/gateway/2.7.x/plan-and-deploy/hybrid-mode/index.md
  app/gateway/2.7.x/plan-and-deploy/kubernetes-deployment-options.md
  app/gateway/2.7.x/plan-and-deploy/security/db-encryption.md
  app/gateway/2.7.x/plan-and-deploy/sizing-guidelines.md
  app/gateway/2.7.x/plugin-development/access-the-datastore.md
  app/gateway/2.7.x/plugin-development/custom-entities.md
  app/gateway/2.7.x/reference/clustering.md
  app/gateway/2.7.x/reference/configuration.md
  app/gateway/2.7.x/reference/db-less-and-declarative-config.md
  app/gateway/2.7.x/reference/rate-limiting.md
  app/gateway/2.7.x/vitals/index.md
  app/gateway/2.7.x/vitals/vitals-influx-strategy.md
  app/gateway/2.7.x/vitals/vitals-prometheus-strategy.md
Labels: release, gateway EE, gateway OSS

#3479 [DOCU-2056] OIDC for KM auth improvements
  app/_data/docs_nav_gateway_2.7.x.yml
  app/_hub/kong-inc/openid-connect/index.md
  app/_redirects
  app/gateway/2.7.x/configure/auth/kong-manager/oidc-mapping.md
  app/gateway/2.7.x/configure/auth/kong-manager/oidc.md
  app/gateway/2.7.x/configure/auth/oidc-mapping.md
Labels: pr/please review

#3499 chore/Sync 2.6.x and 2.7.x directories
  app/gateway/2.7.x/get-started/comprehensive/dev-portal.md
  app/gateway/2.7.x/get-started/comprehensive/manage-teams.md
  app/gateway/2.7.x/install-and-run/docker.md
  app/gateway/2.7.x/vitals/vitals-prometheus-strategy.md
Labels: review:general

#3488 [DOCU-2050] Gateway 2.7 changelog
  app/_data/kong_versions.yml
  app/gateway/changelog.md
  app/konnect-platform/support-policy.md
Labels: release, do not merge, gateway EE, gateway OSS

#3498 [bug fix] Let right ToC wrap instead of cutting off
  app/_assets/stylesheets/pages/docs.less
Labels: review:general

#3468 [DOCU-2077] Deprecate cookie policy banner in favor of Onetrust
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/cookie-policy.less
  app/_assets/stylesheets/index.less
  app/_includes/cookie-policy.html
  app/_includes/head.html
Labels: do not merge, review:general
