Repository Kong/docs.konghq.com, pull requests merged in 2021-05, with the labels that each got.

#2827 [DOCU-1444] Cleafy plugin update logo
  app/_assets/images/icons/hub/cleafy_cleafy.png
Labels: pr/please review

#2828 [DOCU-1445] plugin custom logos now required, size guidelines
  CONTRIBUTING.md
Labels: pr/please review

#2819 Expand example content for extended markdown usage
  app/enterprise/2.3.x/developer-portal/theme-customization/markdown-extended.md
Labels: pr/please review

#2837 Release: 2.4.1
  app/_data/kong_versions.yml
Labels: pr/do not merge, pr/please review

#2839 [DOCU-1476] HTTP log plugin custom header code block
  app/_hub/kong-inc/http-log/index.md
Labels: pr/please review

#2848 [DOCU-912] Kafka Log plugin remove install section
  app/_hub/kong-inc/kafka-log/index.md
Labels: pr/please review

#2850 [DOCU-1483] kakfa log plugin cleanup cont
  app/_hub/kong-inc/kafka-log/index.md
Labels: pr/please review

#2852 [DOCU-677] Request Transformer Advanced plugin port datatypes /examples from corresponding OSS plugin
  app/_hub/kong-inc/request-transformer-advanced/index.md
Labels: pr/please review

#2823 [DOC-1407] OPA plugin remove beta tag, version note for GA (merge for 2.4 EE GA)
  app/_hub/kong-inc/opa/index.md
Labels: do not merge

#2781 [DOCU-1399] Mocking plugin EE 2.4 GA
  app/_assets/images/docs/dev-portal/km-config-api-spec-txt-fld.png
  app/_assets/images/docs/dev-portal/km-copy-plugin-id.png
  app/_assets/images/docs/dev-portal/km-service-url.png
  app/_assets/images/docs/dev-portal/stock-service.png
  app/_assets/images/docs/dev-portal/stock-spec-mock-example.png
  app/_assets/images/docs/dev-portal/stock_service.png
  app/_assets/images/docs/dev-portal/tryitout-portal.png
  app/_assets/images/docs/insomnia/insomnia-deploy-spec-dev-portal.png
  app/_assets/images/docs/insomnia/insomnia-import-spec.png
  app/_assets/images/docs/insomnia/insomnia-stock-spec.png
  app/_assets/images/docs/insomnia/tryitout-insomnia.png
  app/_assets/images/icons/hub/kong-inc_mocking.png
  app/_data/extensions/kong-inc/mocking/versions.yml
  app/_hub/kong-inc/mocking/index.md
Labels: do not merge, pr/please review

#2853 [DOCU-672] Azure Functions plugin add datatypes from schema
  app/_hub/kong-inc/azure-functions/index.md
Labels: pr/please review

#2869 [DOCU-671] AWS Lambda plugin datatypes
  app/_hub/kong-inc/aws-lambda/index.md
Labels: pr/please review

#2855 [DOCU-1491] Remove unsupported plugins from Plus filter
  app/_hub/index.html
  app/_hub/kong-inc/request-transformer-advanced/index.md
  app/_hub/kong-inc/request-transformer/index.md
  app/_hub/kong-inc/response-transformer-advanced/index.md
Labels: pr/please review

#2854 [DOCU-1477] Runtime manager: Windows instructions for Docker
  app/konnect/getting-started/configure-runtime.md
  app/konnect/runtime-manager/gateway-runtime-conf.md
  app/konnect/runtime-manager/gateway-runtime-docker.md
  app/konnect/runtime-manager/gateway-runtime-kubernetes.md
Labels: pr/please review

#2871 [DOCU-1502] OPA plugin correct config rather than package example
  app/_hub/kong-inc/opa/index.md
Labels: pr/please review

#2878 [DOCU-1504]Removes centos 6 from available download options
  app/_includes/md/enterprise/download/centos.md
  app/enterprise/2.4.x/deployment/installation/centos.md
Labels: pr/please review

#2883 [DOCU-803] Refactor alert/callout design
  app/_assets/stylesheets/page.less
  app/_hub/kong-inc/ldap-auth-advanced/index.md
  app/_hub/kong-inc/ldap-auth/index.md
  app/_hub/kong-inc/mocking/index.md
  app/_hub/kong-inc/oauth2/1.0.x.md
  app/_hub/kong-inc/oauth2/index.md
  app/_hub/kong-inc/statsd-advanced/index.md
  app/_hub/kong-inc/statsd/index.md
  app/_hub/tomkerkhove/microsoft_azure/index.md
  app/_hub/tomkerkhove/microsoft_azure_container_instances/index.md
  app/enterprise/1.5.x/kong-for-kubernetes/install-on-kubernetes.md
  app/enterprise/2.1.x/deployment/classic-deployment.md
  app/enterprise/2.1.x/deployment/deployment-options.md
  app/enterprise/2.1.x/deployment/hybrid-mode-setup.md
  app/enterprise/2.1.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.1.x/developer-portal/configuration/authentication/sessions.md
  app/enterprise/2.1.x/kong-manager/authentication/sessions.md
  app/enterprise/2.2.x/deployment/classic-deployment.md
  app/enterprise/2.2.x/deployment/deployment-options.md
  app/enterprise/2.2.x/deployment/hybrid-mode-setup.md
  app/enterprise/2.2.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.2.x/developer-portal/configuration/authentication/sessions.md
  app/enterprise/2.2.x/kong-manager/authentication/sessions.md
  app/enterprise/2.3.x/deployment/classic-deployment.md
  app/enterprise/2.3.x/deployment/deployment-options.md
  app/enterprise/2.3.x/deployment/hybrid-mode-setup.md
  app/enterprise/2.3.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.3.x/developer-portal/configuration/authentication/sessions.md
  app/enterprise/2.3.x/kong-manager/authentication/sessions.md
  app/enterprise/2.4.x/deployment/classic-deployment.md
  app/enterprise/2.4.x/deployment/deployment-options.md
  app/enterprise/2.4.x/deployment/hybrid-mode-setup.md
  app/enterprise/2.4.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.4.x/developer-portal/configuration/authentication/sessions.md
  app/enterprise/2.4.x/kong-manager/authentication/sessions.md
  app/getting-started-guide/2.1.x/expose-services.md
  app/getting-started-guide/2.1.x/prepare.md
  app/getting-started-guide/2.2.x/expose-services.md
  app/getting-started-guide/2.2.x/prepare.md
  app/getting-started-guide/2.3.x/expose-services.md
  app/getting-started-guide/2.3.x/prepare.md
  app/getting-started-guide/2.4.x/expose-services.md
  app/getting-started-guide/2.4.x/prepare.md
  app/install/aws-cloudformation.md
  app/install/vagrant.md
  app/kubernetes-ingress-controller/1.0.x/concepts/ingress-versions.md
  app/kubernetes-ingress-controller/1.1.x/concepts/ingress-versions.md
  app/kubernetes-ingress-controller/1.2.x/concepts/ingress-versions.md
Labels: pr/please review

#2892 Add image modal to plugins
  app/_layouts/extension.html
Labels: pr/please review

#2888 Fix "Try Kong Gateway" section in docs intro
  app/enterprise/1.3-x/kong-for-kubernetes/install.md
  app/enterprise/1.5.x/introduction.md
  app/enterprise/2.1.x/introduction.md
  app/enterprise/2.2.x/introduction/index.md
  app/enterprise/2.3.x/index.md
  app/enterprise/2.4.x/index.md
Labels: pr/please review
