Repository Kong/docs.konghq.com, pull requests merged in 2021-01, with the labels that each got.

#2529 docs(changelog) added 2.2.1.0, 2.1.4.3, and 1.5.0.9 patch releases
  app/enterprise/changelog.md
Labels: do not merge, pr/wip

#2527 EE: Document key-auth support in on-prem (self-hosted) application registration, 2.2.1.0 patch release (READY FOR DOCS REVIEW)
  app/_assets/images/docs/dev-portal/gen-client-id-secret.png
  app/_assets/images/docs/dev-portal/key-auth-plugin-panel.png
  app/_assets/images/docs/dev-portal/portal-info-modal-key-auth.png
  app/_assets/images/docs/dev-portal/service-details-key-auth-usage.png
  app/_data/docs_nav_ee_2.2.x.yml
  app/_data/extensions/kong-inc/key-auth/versions.yml
  app/_hub/kong-inc/application-registration/index.md
  app/_hub/kong-inc/key-auth/index.md
  app/_hub/kong-inc/openid-connect/index.md
  app/enterprise/2.2.x/developer-portal/administration/application-registration/3rd-party-oauth.md
  app/enterprise/2.2.x/developer-portal/administration/application-registration/auth-provider-strategy.md
  app/enterprise/2.2.x/developer-portal/administration/application-registration/azure-oidc-config.md
  app/enterprise/2.2.x/developer-portal/administration/application-registration/enable-application-registration.md
  app/enterprise/2.2.x/developer-portal/administration/application-registration/enable-key-auth-plugin.md
  app/enterprise/2.2.x/developer-portal/administration/application-registration/index.md
Labels: pr/please review

#2519 docs(gsg) Add tabs for cURL and HTTPie example pairs and fix examples
  app/getting-started-guide/2.2.x/dev-portal.md
  app/getting-started-guide/2.2.x/expose-services.md
  app/getting-started-guide/2.2.x/improve-performance.md
  app/getting-started-guide/2.2.x/load-balancing.md
  app/getting-started-guide/2.2.x/manage-teams.md
  app/getting-started-guide/2.2.x/prepare.md
  app/getting-started-guide/2.2.x/protect-services.md
  app/getting-started-guide/2.2.x/secure-services.md
Labels: pr/please review

#2531 docs(kic) Fix syntax for TLS certs
  app/kubernetes-ingress-controller/1.0.x/guides/cert-manager.md
  app/kubernetes-ingress-controller/1.1.x/guides/cert-manager.md
Labels: pr/please review

#2534 docs(old versions) Adjust older versions banner
  app/_layouts/docs-v2.html
Labels: pr/please review

#2550 redirect for new external plugin file, formerly Go plugins
  app/2.3.x/external-plugins.md
  app/2.3.x/go.md
Labels: pr/please review

#2552 Release: 2.3.1
  app/_data/kong_versions.yml
Labels: pr/do not merge, pr/please review

#2551 Removed all content related to /entities endpoint as it was removed from this version
  app/enterprise/2.1.x/admin-api/workspaces/examples.md
  app/enterprise/2.1.x/admin-api/workspaces/reference.md
  app/enterprise/2.2.x/admin-api/workspaces/examples.md
  app/enterprise/2.2.x/admin-api/workspaces/reference.md
  app/enterprise/2.3.x/admin-api/workspaces/examples.md
  app/enterprise/2.3.x/admin-api/workspaces/reference.md
Labels: pr/please review
