Repository Kong/docs.konghq.com, pull requests merged in 2022-09, with the labels that each got.

#4374 Update plugin compatibility table
  app/_data/tables/plugin_index.yml
Labels: review:general

#4377 Add moved_urls.yml detection tool
  tools/moved-urls-checker/README.md
  tools/moved-urls-checker/package-lock.json
  tools/moved-urls-checker/package.json
  tools/moved-urls-checker/run.js
Labels: review:tech

#4378 Update default policy/strategy for rate limiting plugins
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
  app/_hub/kong-inc/rate-limiting/_index.md
  app/_hub/kong-inc/response-ratelimiting/_index.md
  app/gateway/changelog.md
  src/gateway/get-started/ratelimiting.md
  src/gateway/kong-enterprise/consumer-groups/index.md
Labels: review:general

#4380 Open external links in new tab
  app/_layouts/default.html
  app/_layouts/docs-v2.html
  app/_layouts/extension.html
Labels: review:general

#4373 Update moved urls
  app/moved_urls.yml
Labels: review:general

#4384 Update _index.md
  app/_hub/kong-inc/request-termination/_index.md
Labels: review:copyedit

#4382 Style guide: capitalization
  app/contributing/style-guide.md
  app/contributing/word-choice.md
Labels: review:copyedit

#4385 Konnect August Release Notes
  app/konnect/updates.md
Labels: review:copyedit

#4388 Apply Helm chart feedback + fix sed inconsistenies
  src/gateway/install/kubernetes/helm-quickstart.md
Labels: review:general, review:copyedit

#4391 fix(changelog): add missing entries for GW 2.8.x.x
  app/gateway/changelog.md
Labels: review:copyedit

#4392 Clarify "unsupported" in installation table
  src/gateway/install/index.md
Labels: review:general

#4393 Update End of Full Support dates for 2.6 and 2.7
  app/konnect-platform/support-policy.md
Labels: review:general

#4394 Update End of Full Support dates for 2.6 and 2.7
  src/gateway/support-policy.md
Labels: review:general

#4375 Broken links, continued
  app/_includes/md/admin-listen.md
  app/_includes/md/enterprise/deploy-license.md
  app/_includes/md/enterprise/turn-on-rbac.md
  app/_includes/md/gateway/deployment-options.md
  app/_includes/md/gateway/root-user-note.md
  app/_includes/md/gateway/setup.md
  app/enterprise/2.1.x/plugin-development/custom-entities.md
  app/enterprise/2.1.x/plugin-development/tests.md
  app/enterprise/2.2.x/plugin-development/custom-entities.md
  app/enterprise/2.2.x/plugin-development/tests.md
  app/enterprise/2.3.x/plugin-development/custom-entities.md
  app/enterprise/2.3.x/plugin-development/tests.md
  app/enterprise/2.4.x/plugin-development/custom-entities.md
  app/enterprise/2.4.x/plugin-development/tests.md
  app/enterprise/2.5.x/plugin-development/custom-entities.md
  app/enterprise/2.5.x/plugin-development/tests.md
  app/gateway-oss/2.0.x/plugin-development/admin-api.md
  app/gateway-oss/2.0.x/plugin-development/custom-entities.md
  app/gateway-oss/2.0.x/plugin-development/tests.md
  app/gateway-oss/2.1.x/plugin-development/admin-api.md
  app/gateway-oss/2.1.x/plugin-development/custom-entities.md
  app/gateway-oss/2.1.x/plugin-development/tests.md
  app/gateway-oss/2.2.x/plugin-development/admin-api.md
  app/gateway-oss/2.2.x/plugin-development/custom-entities.md
  app/gateway-oss/2.2.x/plugin-development/tests.md
  app/gateway-oss/2.3.x/plugin-development/admin-api.md
  app/gateway-oss/2.3.x/plugin-development/custom-entities.md
  app/gateway-oss/2.3.x/plugin-development/tests.md
  app/gateway-oss/2.4.x/plugin-development/admin-api.md
  app/gateway-oss/2.4.x/plugin-development/custom-entities.md
  app/gateway-oss/2.4.x/plugin-development/tests.md
  app/gateway-oss/2.5.x/plugin-development/admin-api.md
  app/gateway-oss/2.5.x/plugin-development/custom-entities.md
  app/gateway-oss/2.5.x/plugin-development/tests.md
  app/gateway/2.6.x/configure/auth/kong-manager/networking.md
  app/gateway/2.6.x/configure/auth/oidc-cognito.md
  app/gateway/2.6.x/configure/network.md
  app/gateway/2.6.x/install-and-run/docker.md
  app/gateway/2.6.x/plan-and-deploy/security/start-kong-securely.md
  app/gateway/2.6.x/plugin-development/admin-api.md
  app/gateway/2.6.x/plugin-development/tests.md
  app/gateway/2.6.x/reference/proxy.md
  app/gateway/2.6.x/vitals/vitals-influx-strategy.md
  app/gateway/2.7.x/configure/auth/kong-manager/networking.md
  app/gateway/2.7.x/configure/auth/oidc-cognito.md
  app/gateway/2.7.x/configure/network.md
  app/gateway/2.7.x/install-and-run/docker.md
  app/gateway/2.7.x/plan-and-deploy/security/start-kong-securely.md
  app/gateway/2.7.x/plugin-development/admin-api.md
  app/gateway/2.7.x/plugin-development/tests.md
  app/gateway/2.7.x/reference/proxy.md
  app/gateway/2.7.x/vitals/vitals-influx-strategy.md
  app/gateway/2.8.x/configure/auth/kong-manager/networking.md
  app/gateway/2.8.x/configure/auth/oidc-cognito.md
  app/gateway/2.8.x/configure/network.md
  app/gateway/2.8.x/install-and-run/docker.md
  app/gateway/2.8.x/plan-and-deploy/security/start-kong-securely.md
  app/gateway/2.8.x/plugin-development/tests.md
  app/gateway/2.8.x/reference/proxy.md
  app/gateway/2.8.x/vitals/vitals-influx-strategy.md
Labels: review:general, ci:check-skipped:generated-files

#4398 docs(gateway) add 3.0 dependencies versions
  app/_data/kong_versions.yml
  app/_hub/kong-inc/ldap-auth-advanced/_index.md
Labels: review:general

#4399 update beta status for websockets
  app/gateway/changelog.md
Labels: review:general

#4400 Changelog: Blue-green deployment fixes + missing info
  app/gateway/changelog.md
  jekyll-dev.yml
  jekyll.yml
  src/gateway/upgrade.md
  tests/breadcrumbs.test.js
Labels: review:general, review:copyedit

#4396 Add Gateway quick links section
  src/gateway/index.md
Labels: review:general

#4395 Include sample: how can configure dbless with Visual Studio Code.
  .github/styles/kong/Terms.yml
  .github/styles/kong/dictionary.txt
  app/gateway/2.8.x/reference/db-less-and-declarative-config.md
  src/deck/faqs.md
Labels: review:copyedit

#4376 Add new per-product broken link checker
  README.md
  broken-link-checker/excluded.json
  broken-link-checker/package-lock.json
  broken-link-checker/package.json
  broken-link-checker/product.js
Labels: review:tech

#4405 Bump deck format version to 3.0
  app/_hub/kong-inc/acme/_index.md
  app/_hub/kong-inc/grpc-gateway/_index.md
  app/_hub/kong-inc/grpc-web/_index.md
  src/deck/guides/defaults-v2.md
  src/deck/guides/defaults.md
  src/deck/guides/environment-variables.md
  src/deck/guides/getting-started.md
  src/deck/guides/kong-enterprise.md
  src/deck/guides/konnect.md
  src/deck/guides/multi-file-state.md
  src/gateway/install/docker/index.md
  src/gateway/kong-enterprise/plugin-ordering/get-started.md
  src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
  src/gateway/production/running-kong/secure-admin-api.md
Labels: review:general

#4409 Correct statements of blue-green deploys
  app/gateway/changelog.md
  src/gateway/upgrade.md
Labels: review:copyedit

#4410 Fix KIC's kustomize manifests path
  src/kubernetes-ingress-controller/deployment/k4k8s-enterprise.md
  src/kubernetes-ingress-controller/deployment/k4k8s.md
Labels: ready, review:general, area/docs

#4379 docs(secret-management) update secret management docs for GA
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/acme/_index.md
  app/_hub/kong-inc/aws-lambda/_index.md
  app/_hub/kong-inc/azure-functions/_index.md
  app/_hub/kong-inc/forward-proxy/_index.md
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
  app/_hub/kong-inc/kafka-log/_index.md
  app/_hub/kong-inc/kafka-upstream/_index.md
  app/_hub/kong-inc/ldap-auth-advanced/_index.md
  app/_hub/kong-inc/loggly/_index.md
  app/_hub/kong-inc/openid-connect/_index.md
  app/_hub/kong-inc/proxy-cache-advanced/_index.md
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
  app/_hub/kong-inc/rate-limiting/_index.md
  app/_hub/kong-inc/request-transformer-advanced/_index.md
  app/_hub/kong-inc/response-ratelimiting/_index.md
  app/_hub/kong-inc/session/_index.md
  app/_hub/kong-inc/vault-auth/_index.md
  app/gateway/changelog.md
  src/gateway/kong-enterprise/secrets-management/advanced-usage.md
  src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
  src/gateway/kong-enterprise/secrets-management/backends/env.md
  src/gateway/kong-enterprise/secrets-management/backends/gcp-sm.md
  src/gateway/kong-enterprise/secrets-management/backends/index.md
  src/gateway/kong-enterprise/secrets-management/getting-started.md
  src/gateway/kong-enterprise/secrets-management/index.md
  src/gateway/kong-enterprise/secrets-management/reference-format.md
Labels: release, do not merge, review:copyedit, ci:check-skipped:generated-files

#4411 Rename source_url to source_code for plugins
  app/_hub/SmartParkingTechnology/google-logging/_index.md
  app/_hub/_init/my-extension/_index.md
  app/_hub/arecabay/ab-microsensor/_index.md
  app/_hub/bitnami/microsoft_azure/_index.md
  app/_hub/critical-blue/approov/_index.md
  app/_hub/flash/set-dynamic-upstream-host/_index.md
  app/_hub/inspur/apig-request-transformer/_index.md
  app/_hub/inspur/apig-response-transform/_index.md
  app/_hub/justeat/kongverge/_index.md
  app/_hub/kong-inc/kong-terraform-aws/_index.md
  app/_hub/kong-inc/openwhisk/_index.md
  app/_hub/moesif/kong-plugin-moesif/_index.md
  app/_hub/okta/okta/_index.md
  app/_hub/optum/kong-response-size-limiting/_index.md
  app/_hub/optum/kong-service-virtualization/_index.md
  app/_hub/optum/kong-spec-expose/_index.md
  app/_hub/optum/kong-splunk-log/_index.md
  app/_hub/optum/kong-upstream-jwt/_index.md
  app/_hub/peter-evans/paseto/_index.md
  app/_hub/qnap/api-transformer/_index.md
  app/_hub/reedelk/reedelk-transformer/_index.md
  app/_hub/revolution_systems/upstream-auth-basic/_index.md
  app/_hub/salt/salt/_index.md
  app/_hub/seifchen/kong-path-allow/_index.md
  app/_hub/signal_sciences/signal-sciences/_index.md
  app/_hub/signalfx/signalfx/_index.md
  app/_hub/stone-payments/kong-plugin-template-transformer/_index.md
  app/_hub/stone-payments/kong-plugin-url-rewrite/_index.md
  app/_hub/tomkerkhove/microsoft_azure/_index.md
  app/_hub/tomkerkhove/microsoft_azure_container_instances/_index.md
  app/_hub/wallarm/wallarm/_index.md
  app/_hub/yesinteractive/kong-jwt2header/_index.md
  app/_hub/yesinteractive/kong-log-google/_index.md
  app/_hub/yesinteractive/kongmap/_index.md
  app/_layouts/extension.html
Labels: review:general

#4414 Add OpenTracing item to Known Limitations
  app/gateway/changelog.md
Labels: review:general, review:copyedit

#4415 We accidently removed RFC3987 validation from route paths
  app/gateway/changelog.md
Labels: review:general

#4418 Replace Playwright with fetch+cheerio
  .github/workflows/run-smoke-tests.yml
  Makefile
  README.md
  package-lock.json
  package.json
  tests/__utils__/customMatchers.js
  tests/__utils__/fetchPage.js
  tests/breadcrumbs.test.js
  tests/edit_link.test.js
  tests/home.test.js
  tests/install.test.js
  tests/plugin.test.js
  tests/seo.test.js
  tests/sidebar.test.js
  tests/titles.test.js
Labels: review:tech

#4177 [DOCU-2771] Konnect OIDC config
  app/_data/docs_nav_konnect.yml
  app/konnect/org-management/oidc-idp.md
  app/konnect/org-management/okta-idp.md
Labels: do not merge, review:tech, review:copyedit

#4402 [DOCU-2274] Upstream timeout plugin
  .github/styles/kong/dictionary.txt
  app/_assets/images/icons/hub/kong-inc_upstream-timeout.png
  app/_data/tables/plugin_index.yml
  app/_hub/kong-inc/upstream-timeout/_index.md
  app/_hub/kong-inc/upstream-timeout/versions.yml
  src/gateway/how-kong-works/routing-traffic.md
  src/gateway/plugin-development/custom-logic.md
Labels: do not merge, review:copyedit

#4420 Changelog & upgrade: clarify declarative config + update release date
  app/gateway/changelog.md
  src/gateway/upgrade.md
Labels: review:copyedit

#4419 Removing reference to Verbose in the CLI
  app/gateway/2.8.x/developer-portal/helpers/cli.md
Labels: review:general

#4403 Blue green deployments 2
  app/gateway/changelog.md
  src/gateway/upgrade.md
Labels: do not merge, review:copyedit

#4421 Fix 2.8.x nav
  app/_data/docs_nav_gateway_2.8.x.yml
Labels: do not merge, review:general

#4422 We switched our convenience tags from Alpine base to Debian base
  app/gateway/changelog.md
Labels: review:copyedit

#4427 Use OSS release branch in URLs
  src/gateway/plugin-development/custom-entities.md
  src/gateway/upgrade.md
Labels: review:general

#4428 Fix Kong Gateway overview breadcrumb
  src/gateway/index.md
Labels: review:general

#4430 Fix AmazonLinux2 install instructions
  src/gateway/install/linux/amazon-linux.md
Labels: review:general

#4431 Fix homepage links
  app/_data/landing_page.yml
Labels: review:general

#4434 Rename atc to expression
  src/gateway/key-concepts/routes/expressions.md
Labels: review:general

#4429 Clean up k8s install (Gateway)
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/install/kubernetes/kubectl.md
Labels: review:general

#4433 Update faq.md
  src/gateway/reference/faq.md
Labels: review:copyedit

#4401 [DOCU-2453] Documentation for Konnect Personal Access Tokens
  app/konnect/getting-started/import.md
  app/konnect/runtime-manager/runtime-groups/declarative-config.md
  src/deck/guides/konnect.md
Labels: review:general, review:copyedit

#4435 chore: Remove @tomkerkhove contributions
  app/_hub/tomkerkhove/microsoft_azure/_index.md
  app/_hub/tomkerkhove/microsoft_azure_container_instances/_index.md
Labels: review:general

#4437 Add review label to workflow
  .github/workflows/require-review-label.yml
Labels: review:sme

#4438 Add broken Alpine image to 3.0 Known Issues
  app/gateway/changelog.md
Labels: review:general

#4417 [DOCU-2478] Konnect 3.0 support
  app/_data/tables/version_errors_konnect.yml
  app/konnect/compatibility.md
  app/konnect/index.md
  app/konnect/runtime-manager/gateway-config.md
  app/konnect/runtime-manager/index.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-docker.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-kubernetes.md
  app/konnect/runtime-manager/runtime-instances/upgrade.md
  app/konnect/runtime-manager/troubleshoot.md
  app/konnect/servicehub/index.md
  app/konnect/servicehub/service-implementations.md
  app/konnect/updates.md
Labels: do not merge, review:copyedit

#4412 [DOCU-2466][DOCU-2463] Konnect Rename + Reorder
  app/_assets/images/icons/konnect/icn-analytics-bargraph.svg
  app/_assets/images/icons/konnect/icn-analytics-horizontal.svg
  app/_assets/images/icons/konnect/icn-analytics-nav.svg
  app/_assets/images/icons/konnect/icn-analytics.svg
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/analytics/generate-reports.md
  app/konnect/analytics/index.md
  app/konnect/analytics/overview-dashboard.md
  app/konnect/analytics/services-and-routes.md
  app/konnect/dev-portal/access-and-approval/manage-app-connections.md
  app/konnect/dev-portal/access-and-approval/manage-app-reg-requests.md
  app/konnect/dev-portal/access-and-approval/manage-devs.md
  app/konnect/getting-started/publish-service.md
  app/konnect/index.md
  app/konnect/network-resiliency.md
  app/konnect/org-management/teams-and-roles/roles-reference.md
  app/konnect/org-management/teams-and-roles/teams-reference.md
  app/konnect/runtime-manager/runtime-instances/renew-certificates.md
  app/konnect/runtime-manager/runtime-instances/runtime-parameter-reference.md
  app/konnect/updates.md
  app/moved_urls.yml
Labels: review:copyedit

#4442 Clean up remains of tomkerkhove's plugins
  app/_assets/images/icons/hub/tomkerkhove_microsoft_azure.png
  app/_assets/images/icons/hub/tomkerkhove_microsoft_azure_container_instances.png
  app/_redirects
Labels: review:general

#4443 Add missing knative guide to nav
  app/_data/docs_nav_kic_2.5.x.yml
Labels: review:general

#4441 TLS plugin icons
  app/_assets/images/icons/hub/kong-inc_tls-handshake-modifier.png
  app/_assets/images/icons/hub/kong-inc_tls-metadata-headers.png
Labels: review:general

#4449 Fix for get-started rate limiting test command
  src/gateway/get-started/rate-limiting.md
Labels: review:general

#4447 File log plugin: missing `params` key
  app/_hub/kong-inc/file-log/_index.md
Labels: review:general

#4440 Konnect Rename + Reorder (#4412)
  app/_assets/images/icons/konnect/icn-analytics-bargraph.svg
  app/_assets/images/icons/konnect/icn-analytics-horizontal.svg
  app/_assets/images/icons/konnect/icn-analytics-nav.svg
  app/_assets/images/icons/konnect/icn-analytics.svg
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/analytics/generate-reports.md
  app/konnect/analytics/index.md
  app/konnect/analytics/overview-dashboard.md
  app/konnect/analytics/services-and-routes.md
  app/konnect/dev-portal/access-and-approval/manage-app-connections.md
  app/konnect/dev-portal/access-and-approval/manage-app-reg-requests.md
  app/konnect/dev-portal/access-and-approval/manage-devs.md
  app/konnect/getting-started/publish-service.md
  app/konnect/index.md
  app/konnect/network-resiliency.md
  app/konnect/org-management/teams-and-roles/roles-reference.md
  app/konnect/org-management/teams-and-roles/teams-reference.md
  app/konnect/runtime-manager/runtime-instances/renew-certificates.md
  app/konnect/runtime-manager/runtime-instances/runtime-parameter-reference.md
  app/konnect/updates.md
Labels: review:general

#4445 [DOCU-2480] CTA in Konnect
  app/konnect/architecture.md
  app/konnect/getting-started/access-account.md
  app/konnect/index.md
  app/konnect/updates.md
Labels: review:copyedit

#4451 [Cherry Pick] CTA in Konnect (#4445)
  app/konnect/architecture.md
  app/konnect/getting-started/access-account.md
  app/konnect/index.md
  app/konnect/updates.md
Labels: review:general, review:copyedit

#4455 Add missing port to get-started/proxy-caching code snippet
  src/gateway/get-started/proxy-caching.md
Labels: review:general

#4454 Make 'referenceable' a parameter attribute in plugins
  app/_hub/kong-inc/acme/_index.md
  app/_hub/kong-inc/aws-lambda/_index.md
  app/_hub/kong-inc/azure-functions/_index.md
  app/_hub/kong-inc/forward-proxy/_index.md
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
  app/_hub/kong-inc/kafka-log/_index.md
  app/_hub/kong-inc/kafka-upstream/_index.md
  app/_hub/kong-inc/ldap-auth-advanced/_index.md
  app/_hub/kong-inc/loggly/_index.md
  app/_hub/kong-inc/openid-connect/_2.2.x.md
  app/_hub/kong-inc/openid-connect/_index.md
  app/_hub/kong-inc/proxy-cache-advanced/_index.md
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
  app/_hub/kong-inc/rate-limiting/_index.md
  app/_hub/kong-inc/request-transformer-advanced/_index.md
  app/_hub/kong-inc/response-ratelimiting/_index.md
  app/_hub/kong-inc/session/_index.md
  app/_layouts/extension.html
Labels: review:general

#4408 update gatewayAPI to v1beta1 in KIC >= 2.6.x
  src/kubernetes-ingress-controller/guides/using-gateway-api.md
  src/kubernetes-ingress-controller/references/gateway-api-support.md
Labels: ready, review:general, area/gateway-api

#4457 [fix] Fix portal API docs not loading
  src/gateway/kong-enterprise/dev-portal/portal-api.md
Labels: review:general

#4458 Upgrade guide: remove old instructions
  src/gateway/upgrade.md
Labels: review:general

#4448 Konnect cloud rename
  .github/styles/kong/Terms.yml
  .vale.ini
  app/_data/docs_nav_konnect.yml
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
  app/_hub/kong-inc/jq/_index.md
  app/_hub/kong-inc/mtls-auth/_index.md
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
  app/_hub/kong-inc/rate-limiting/_index.md
  app/_hub/kong-inc/response-ratelimiting/_index.md
  app/_includes/docs-sidebar.html
  app/_includes/nav-v2.html
  app/_layouts/landing-page.html
  app/contributing/word-choice.md
  app/enterprise/2.5.x/admin-api/event-hooks/reference.md
  app/gateway/2.6.x/admin-api/event-hooks/reference.md
  app/gateway/2.7.x/admin-api/event-hooks/reference.md
  app/gateway/2.8.x/admin-api/event-hooks/reference.md
  app/konnect/getting-started/access-account.md
  app/konnect/getting-started/import.md
  app/konnect/getting-started/index.md
  app/konnect/index.md
  app/konnect/updates.md
  docs/vale.md
  jekyll-dev.yml
  jekyll.yml
  src/gateway/admin-api/event-hooks/reference.md
Labels: review:general, review:copyedit

#4459 Update Predefined Teams
  .github/styles/kong/dictionary.txt
  app/konnect/org-management/teams-and-roles/teams-reference.md
Labels: review:copyedit

#4461 Fix curl for consumer rate limiting plugin
  src/gateway/get-started/rate-limiting.md
Labels: review:copyedit

#4436 [DOCU-2462] Runtime Groups Dashboard
  app/_data/docs_nav_konnect.yml
  app/konnect/analytics/overview-dashboard.md
  app/konnect/runtime-manager/runtime-groups/dashboard.md
  app/konnect/runtime-manager/runtime-groups/index.md
Labels: review:copyedit

#4462 Fix Secrets Management link in 3.0 release notes
  app/gateway/changelog.md
Labels: review:general

#4444 doc: add KIC 2.6 and Kong 3.x controller guide
  app/_data/docs_nav_kic_2.6.x.yml
  app/_data/kong_versions.yml
  src/kubernetes-ingress-controller/guides/upgrade-kong-3x.md
  src/kubernetes-ingress-controller/references/version-compatibility.md
Labels: review:general, review:copyedit

#4463 Adding FIPS 3.0.0.0 release documentation
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/tables/features/gateway.yml
  app/gateway/changelog.md
  src/gateway/kong-enterprise/fips-support.md
  src/gateway/kong-enterprise/index.md
  src/gateway/reference/configuration.md
Labels: review:general, ci:check-skipped:generated-files

#4464 Fixing a FIPS typo
  app/_data/tables/features/gateway.yml
Labels: review:general

#4468 No more limitation for TLS connections in Alpine builds
  app/gateway/changelog.md
Labels: review:general

#4467 docs(gateway) add note on pg_sql and fips
  app/gateway/changelog.md
Labels: review:general

#4481 update gateway api related docs for KIC 2.6
  src/kubernetes-ingress-controller/guides/using-gateway-api.md
  src/kubernetes-ingress-controller/references/cli-arguments.md
  src/kubernetes-ingress-controller/references/feature-gates.md
Labels: review:general, area/gateway-api

#4470 KIC 2.6: Clarification for upgrading to Kong Gateway 3.x
  src/kubernetes-ingress-controller/guides/upgrade-kong-3x.md
Labels: review:copyedit

#4486 Add support for frontmatter overrides
  app/_plugins/generators/single_source_generator.rb
  docs/single-sourced-versions.md
Labels: review:tech

#4487 Fix vale ignore rules
  .vale.ini
Labels: review:general

#4466 Add support for /src/ to broken-link-checker
  .github/workflows/check-links.yml
  README.md
  tools/broken-link-checker/README.md
  tools/broken-link-checker/excluded.json
  tools/broken-link-checker/full.js
  tools/broken-link-checker/package-lock.json
  tools/broken-link-checker/package.json
  tools/broken-link-checker/pr.js
  tools/broken-link-checker/product.js
Labels: review:tech

#4488 feat(openid-connect) support both anonymous username and UUID
  app/_hub/kong-inc/openid-connect/_index.md
Labels: review:copyedit

#4492 Kong Quickstart: Pipes quickstart to script to bash instead of sh
  src/gateway/get-started/index.md
  src/gateway/production/monitoring/prometheus.md
  src/gateway/production/monitoring/statsd.md
Labels: review:general

#4495 Router integer priority
  src/gateway/key-concepts/routes/expressions.md
Labels: review:copyedit

#4491 Change "control plane" to "data planes"
  app/konnect/network-resiliency.md
  app/konnect/network.md
Labels: review:copyedit, review:sme

#4496 chore: uncomment domain name restrictions (TDX-2341)
  app/konnect/dev-portal/customization/index.md
Labels: review:general

#4490 feat: create document for using okta as provider for DCR (TDX-2370)
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/applications/dynamic-client-registration/okta.md
Labels: review:general, review:copyedit

#4493 Add ability to provide k8s-specific examples
  app/_hub/kong-inc/exit-transformer/_index.md
  app/_includes/hub-examples.html
Labels: review:general

#4499 PAT docs for Konnect
  app/_includes/md/personal-access-token.md
  app/konnect/getting-started/import.md
  app/konnect/runtime-manager/runtime-groups/declarative-config.md
  src/deck/guides/konnect.md
Labels: review:copyedit

#4513 [fix] Broken link in changelog
  app/gateway/changelog.md
Labels: review:general

#4485 [DOCU-2499] decK: 3.0 migration guide
  app/_data/docs_nav_deck_1.15.x.yml
  src/deck/guides/3.0-upgrade.md
  src/deck/reference/deck_convert.md
Labels: do not merge, review:copyedit, ci:check-skipped:generated-files, review:sme

#4498 [DOCU-2522] decK: order of precedence for Gateway vs Konnect modes
  src/deck/guides/konnect.md
Labels: review:copyedit

#4510 fix(admin-api): fix wrong api path
  src/gateway/admin-api/index.md
Labels: review:tech, review:general

#4508 fix(auth): update reset token steps.
  src/gateway/kong-manager/auth/reset-password.md
Labels: review:copyedit

#4506 Updated the annotation for KongIngress
  app/kubernetes-ingress-controller/2.1.x/concepts/custom-resources.md
Labels: review:copyedit

#4515 Fix decK link
  app/_data/docs_nav_deck_1.15.x.yml
  src/deck/3.0-upgrade.md
Labels: review:general

#4519 Pin KIC install versions
  src/kubernetes-ingress-controller/deployment/admission-webhook.md
  src/kubernetes-ingress-controller/deployment/aks.md
  src/kubernetes-ingress-controller/deployment/eks.md
  src/kubernetes-ingress-controller/deployment/gke.md
  src/kubernetes-ingress-controller/deployment/k4k8s-enterprise.md
  src/kubernetes-ingress-controller/deployment/kong-enterprise.md
  src/kubernetes-ingress-controller/deployment/minikube.md
Labels: review:general

#4497 [DOCU-2496] Kong Enterprise Overview page
  .github/styles/kong/Terms.yml
  src/gateway/kong-enterprise/index.md
Labels: review:sme

#4503 doc(kic) add 2.7 docs
  app/_data/docs_nav_kic_2.7.x.yml
  app/_data/kong_versions.yml
  src/kubernetes-ingress-controller/guides/upgrade-kong-3x.md
  src/kubernetes-ingress-controller/references/version-compatibility.md
Labels: do not merge, review:general, review:copyedit

#4523 [fix] Add links to router docs in router object api documentation
  src/gateway/admin-api/index.md
Labels: review:general, ci:prevent-merge:generated-files, ci:check-skipped:generated-files

#4524 Add missing router_flavor property to conf ref
  src/gateway/reference/configuration.md
Labels: review:general, ci:prevent-merge:generated-files

#4525 Add enterprise badges to params in configuration.md
  src/gateway/reference/configuration.md
Labels: review:copyedit

#4528 [DOCU-2585] Update runtime terminology
  app/konnect/getting-started/index.md
Labels: review:general

#4507 fix: Updated the `jwt` response for consumer id
  app/_hub/kong-inc/jwt/_index.md
Labels: review:sme

#4500 Add ingress_controller_configuration_push_count.failure_reason label description
  src/kubernetes-ingress-controller/references/prometheus.md
Labels: Kubernetes Team, review:general

#4530 [KIC] Add multiple authentication methods
  app/_data/docs_nav_kic_2.7.x.yml
  src/kubernetes-ingress-controller/guides/allowing-multiple-authentication-methods.md
  src/kubernetes-ingress-controller/guides/overview.md
Labels: review:general

#4531 Add KIC Gateway API and Kubernetes support table
  src/kubernetes-ingress-controller/references/version-compatibility.md
Labels: Kubernetes Team, review:general

#4532 [update] Update responses examples in JWT plugin docs
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/jwt/_index.md
Labels: review:general

#4516 Updated index.md for OAuth2 Authentication
  app/_hub/kong-inc/oauth2/_index.md
Labels: review:copyedit

#4514 Remove Summit promo banner
  app/_assets/stylesheets/header.less
  app/_includes/nav-v2.html
  gulpfile.js
Labels: do not merge, review:general

#4537 [fix] remove placeholder workflow
  .github/workflows/plugin-lint.yml
Labels: review:general

#4535 Add grant_type to plugin ignore list
  .github/styles/kongplugins/plugin-ignore.txt
Labels: review:general

#4536 Update _index.md
  app/_hub/wallarm/wallarm/_index.md
Labels: review:copyedit

#4538 add filter mode to vale
  .github/workflows/linting.yml
Labels: review:general
