Repository Kong/docs.konghq.com, pull requests merged in 2022-06, with the labels that each got.

#3988 Remove mention of AWS Aurora
  app/gateway/2.8.x/reference/clustering.md
Labels: review:copyedit

#3990 Combine plugin examples into tabs for better UX
  app/_assets/stylesheets/navtabs.less
  app/_assets/stylesheets/variables.less
  app/_includes/hub-examples.html
  app/_layouts/extension.html
Labels: review:tech, review:copyedit

#3992 (chore) Bump decK version
  app/_data/kong_versions.yml
Labels: review:general

#3929 fix(httplog) update for 3.0 changes
  app/_hub/kong-inc/http-log/0.1-x.md
  app/_hub/kong-inc/http-log/1.0.x.md
  app/_hub/kong-inc/http-log/2.0.x.md
  app/_hub/kong-inc/http-log/_index.md
  app/_hub/kong-inc/http-log/versions.yml
Labels: review:copyedit

#3905 docs(gateway): dynamic plugin ordering
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/configure/dynamic-plugin-ordering/get-started.md
  src/gateway/configure/dynamic-plugin-ordering/index.md
  src/gateway/plugin-development/custom-logic.md
Labels: Core Team review, pending plugin approval, review:tech, review:general, review:copyedit

#3920 Add Ruby Debug instructions
  .gitignore
  docs/development/ruby-debug.md
Labels: review:tech

#3995 [DOCU-2360] Portal application/service emails
  app/gateway/2.8.x/reference/configuration.md
  app/gateway/changelog.md
Labels: review:general, ci:check-skipped:generated-files

#3835 Fix jwt plugin doc
  app/_hub/kong-inc/jwt/0.1-x.md
  app/_hub/kong-inc/jwt/2.1-x.md
  app/_hub/kong-inc/jwt/_index.md
Labels: review:tech

#3999 [DOCU-2360] Portal email recipients and developer metadata
  app/gateway/2.8.x/developer-portal/theme-customization/emails.md
  app/gateway/2.8.x/reference/configuration.md
  app/gateway/changelog.md
Labels: review:general, ci:check-skipped:generated-files

#4001 fix(docs) update key-auths-enc endpoint
  app/_hub/kong-inc/key-auth-enc/_index.md
Labels: pr/please review, review:copyedit

#3998 Fixes examples on request transformer plugins
  app/_hub/kong-inc/request-transformer-advanced/_index.md
  app/_hub/kong-inc/request-transformer/_index.md
Labels: review:general

#4005 Update cert-manager.md
  app/kubernetes-ingress-controller/2.3.x/guides/cert-manager.md
Labels: review:copyedit

#4003 Update _index.md to include kong.conf changes to enable Moesif plugin
  app/_hub/moesif/kong-plugin-moesif/_index.md
Labels: review:general

#3987 Adding Vale to CI/CD
  .github/styles/kong/Spelling.yml
  .github/styles/kong/Terms.yml
  .github/styles/kong/dictionary.txt
  .github/workflows/vale_linter.yml
  README.md
  docs/vale.md
  src/deck/faqs.md
  src/deck/guides/defaults.md
  src/deck/guides/getting-started.md
  src/deck/index.md
  src/deck/reference/deck.md
  src/deck/reference/deck_completion.md
  src/deck/reference/deck_convert.md
  src/deck/reference/deck_diff.md
  src/deck/reference/deck_dump.md
  src/deck/reference/deck_konnect.md
  src/deck/reference/deck_konnect_diff.md
  src/deck/reference/deck_konnect_dump.md
  src/deck/reference/deck_konnect_ping.md
  src/deck/reference/deck_konnect_sync.md
  src/deck/reference/deck_ping.md
  src/deck/reference/deck_reset.md
  src/deck/reference/deck_sync.md
  src/deck/reference/deck_validate.md
  src/deck/reference/deck_version.md
  vale.ini
Labels: review:tech

#4006 Vale
  .github/workflows/vale_linter.yml
Labels: Core Team review, review:general

#4008 Update: Kong Moesif Plugin versions
  .github/styles/kong/dictionary.txt
  app/_hub/moesif/kong-plugin-moesif/_index.md
Labels: Core Team review, review:copyedit, ci:check-skipped:generated-files

#4011 Updated time preview
  app/konnect/vitals/generate-reports.md
Labels: Core Team review, review:copyedit

#4012 Fix edit link on /latest/ pages
  app/_plugins/generators/latest_version_generator.rb
Labels: review:tech

#4010 Clarify what each report type entitles
  app/konnect/vitals/generate-reports.md
Labels: review:copyedit

#4017 docs(kong-mesh) add cert-manager documentation
  .github/styles/kong/Terms.yml
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_mesh_1.6.x.yml
  app/_data/docs_nav_mesh_1.8.x.yml
  src/mesh/features/acmpca.md
  src/mesh/features/cert-manager.md
  src/mesh/features/vault.md
  src/mesh/gettingstarted.md
  src/mesh/index.md
  vale.ini
Labels: review:tech, review:general

#3979 Konnect nav redux + intro draft
  app/_assets/images/docs/konnect/konnect-intro.png
  app/_assets/images/icons/konnect/icn-runtimes-nav.svg
  app/_assets/images/icons/konnect/icn-servicehub-nav.svg
  app/_data/docs_nav_konnect.yml
  app/_includes/md/konnect/docker-runtime.md
  app/_includes/md/konnect/runtime-certs.md
  app/_includes/md/konnect/service-version.md
  app/_redirects
  app/konnect/account-management/index.md
  app/konnect/architecture.md
  app/konnect/compatibility.md
  app/konnect/configure/servicehub/manage-services.md
  app/konnect/deployment/license-management.md
  app/konnect/dev-portal/Troubleshooting/index.md
  app/konnect/dev-portal/access-and-approval/auto-approve-devs-apps.md
  app/konnect/dev-portal/access-and-approval/manage-app-connections.md
  app/konnect/dev-portal/access-and-approval/manage-app-reg-requests.md
  app/konnect/dev-portal/access-and-approval/manage-devs.md
  app/konnect/dev-portal/access.md
  app/konnect/dev-portal/applications/application-overview.md
  app/konnect/dev-portal/applications/disable-app-reg.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/dev-portal/customization/index.md
  app/konnect/dev-portal/dev-reg.md
  app/konnect/dev-portal/index.md
  app/konnect/dev-portal/publish.md
  app/konnect/getting-started/configure-runtime.md
  app/konnect/getting-started/configure-service.md
  app/konnect/getting-started/import.md
  app/konnect/getting-started/publish-service.md
  app/konnect/index.md
  app/konnect/legacy/dev-portal/access-and-approval/manage-devs.md
  app/konnect/legacy/index.md
  app/konnect/network-resiliency.md
  app/konnect/network.md
  app/konnect/org-management/teams-and-roles/index.md
  app/konnect/runtime-manager/gateway-config.md
  app/konnect/runtime-manager/index.md
  app/konnect/runtime-manager/manage-proxy-config.md
  app/konnect/runtime-manager/runtime-groups/declarative-config.md
  app/konnect/runtime-manager/runtime-groups/index.md
  app/konnect/runtime-manager/runtime-groups/manage.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-conf.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-docker.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-kubernetes.md
  app/konnect/runtime-manager/runtime-instances/renew-certificates.md
  app/konnect/runtime-manager/runtime-instances/runtime-parameter-reference.md
  app/konnect/runtime-manager/runtime-instances/upgrade.md
  app/konnect/runtime-manager/troubleshoot.md
  app/konnect/servicehub/enable-route-plugin.md
  app/konnect/servicehub/enable-service-plugin.md
  app/konnect/servicehub/index.md
  app/konnect/servicehub/manage-services.md
  app/konnect/servicehub/plugins.md
  app/konnect/servicehub/service-documentation.md
  app/konnect/servicehub/service-implementations.md
  app/konnect/servicehub/service-versions.md
  app/konnect/updates.md
Labels: review:general, review:copyedit, ci:check-skipped:generated-files

#3960 [DOCU-2349] GraphQL server path
  app/_hub/kong-inc/degraphql/_index.md
  app/_hub/kong-inc/degraphql/versions.yml
Labels: review:tech, review:general

#4019 Remove old titles from breadcrumbs
  app/_includes/breadcrumbs.html
  tests/breadcrumbs.test.js
Labels: review:general

#4015 docs(km) note Kong Manager perf issue in traditional mode
  app/gateway/2.8.x/index.md
Labels: pr/please review, gateway EE, review:general

#4016 chore: add release dates + one feature and upgrade
  app/mesh/changelog.md
Labels: review:copyedit

#4000 [DOCU-2329] Linux OS support and deprecation
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/tables/os_support.yml
  app/_redirects
  app/gateway/changelog.md
  src/gateway/install-and-run/amazon-linux.md
  src/gateway/install-and-run/centos.md
  src/gateway/install-and-run/debian.md
  src/gateway/install-and-run/docker.md
  src/gateway/install-and-run/index.md
  src/gateway/install-and-run/macos.md
  src/gateway/install-and-run/os-support.md
  src/gateway/install-and-run/rhel.md
  src/gateway/install-and-run/ubuntu.md
  src/gateway/plan-and-deploy/kong-user.md
  tests/sidebar.test.js
Labels: review:tech, review:general

#4027 Update sidebar and nav
  app/_includes/docs-sidebar.html
  app/_includes/nav-v2.html
Labels: Core Team review, review:general

#4037 Add missing kong admin cli flags from #2416
  src/kubernetes-ingress-controller/references/cli-arguments.md
Labels: review:copyedit

#4036 Update _index.md
  app/_hub/kong-inc/jwt-signer/_index.md
Labels: Core Team review, review:copyedit

#4035 fix: description of generation of refresh token in OAuth2 plugin documentation
  app/_hub/kong-inc/oauth2/_index.md
Labels: review:copyedit

#4038 Add missing info for nginx templates
  .github/styles/kong/dictionary.txt
  app/gateway/2.6.x/reference/configuration.md
  app/gateway/2.7.x/reference/configuration.md
  app/gateway/2.8.x/reference/configuration.md
  autodoc-conf-ee/data.lua
Labels: review:general, ci:prevent-merge:generated-files

#4040 [DOCU-2172] Clarify https URL requirement for Oauth2 Introspection plugin
  app/_hub/kong-inc/oauth2-introspection/_index.md
Labels: review:copyedit

#4039 [DOCU-2371] Konnect hostnames and ports
  app/_includes/md/gateway-ports.md
  app/konnect/network.md
Labels: review:tech, review:copyedit

#4023 [DOCU-2341] Improve Okta issuer URL instructions
  app/_data/docs_nav_konnect.yml
  app/konnect/org-management/okta-idp.md
  app/konnect/org-management/troubleshoot.md
Labels: review:copyedit

#4049 Update docs platform install instructions
  docs/platform-install.md
Labels: review:general, review:copyedit

#4051 key-auth-enc plugin: Remove non-existent ttl parameter
  app/_hub/kong-inc/key-auth-enc/_index.md
Labels: review:general

#4052 Update promo banner for Kong Summit 2022
  app/_assets/javascripts/promo-banner.js
  app/_includes/nav-v2.html
Labels: review:general

#4045 Update plugin template file
  app/_hub/_init/my-extension/_index.md
Labels: review:general, review:copyedit

#4030 [DOCU-2308] DecK Konnect guide
  app/_data/docs_nav_deck_1.12.x.yml
  src/deck/faqs.md
  src/deck/guides/konnect.md
Labels: review:tech, review:copyedit

#4055 Fix `layout` type in Working with Templates
  src/gateway/developer-portal/working-with-templates.md
Labels: review:general

#4043 Style guide updates: placeholders, fake values, and capitalization
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_contributing.yml
  app/contributing/STYLEGUIDE.md
  app/contributing/markdown-rules.md
  app/contributing/style-guide.md
  app/contributing/word-choice.md
Labels: review:copyedit

#4053 docs(keyring) add recovery key for 3.0
  src/gateway/admin-api/db-encryption.md
  src/gateway/plan-and-deploy/security/db-encryption.md
Labels: pr/please review, review:copyedit

#4062 Vale: Adjust rules for curly brackets
  .github/styles/kong/Terms.yml
  vale.ini
Labels: do not merge, review:tech

#4069 Updated migrations `reset` command in auto docs
  app/gateway/2.6.x/reference/cli.md
  app/gateway/2.7.x/reference/cli.md
  app/gateway/2.8.x/reference/cli.md
Labels: review:general

#4046 doc(acme) add missing Admin API section and explain `domains` behaviour
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/acme/0.2.11.md
  app/_hub/kong-inc/acme/0.2.13.md
  app/_hub/kong-inc/acme/0.2.14.md
  app/_hub/kong-inc/acme/0.3.x.md
  app/_hub/kong-inc/acme/_index.md
Labels: review:copyedit, ci:check-skipped:generated-files

#4061 Tweaks KIC install
  .github/styles/kong/dictionary.txt
  app/gateway/2.8.x/install-and-run/kubernetes.md
Labels: review:general

#4064 DOCU-2377: Cleanup KIC using kongplugin resource guide
  src/kubernetes-ingress-controller/guides/using-kongplugin-resource.md
Labels: review:general

#4024 [FT-2378] [ENGEN-452] Add notes for ubi-minimal usage
  app/_includes/md/rpm.md
Labels: review:general

#4075 [DOCU-2233] config.token_post_args_client description
  app/_hub/kong-inc/openid-connect/_index.md
Labels: review:copyedit
