Repository Kong/docs.konghq.com, pull requests merged in 2022-01, with the labels that each got.

#3502 [DOCU-1953] Make navtabs accessible
  app/_assets/javascripts/app.js
  app/_plugins/navtabs.rb
Labels: review:general

#3505 [bugfix] RLA plugin: add 1.6.x version
  app/_data/extensions/kong-inc/rate-limiting-advanced/versions.yml
Labels: review:general

#3515 Link to hybrid mode doc
  app/gateway/2.7.x/get-started/comprehensive/prepare.md
Labels: review:general

#3503 fix: Load cookie policy only on prod
  app/_includes/head.html
Labels: review:general

#3516 Fix link in mesh doc
  app/mesh/1.5.x/features/kds-auth.md
Labels: review:general

#3520 Remove OSS-only label from Debian tile
  app/gateway/2.7.x/install-and-run/index.md
Labels: review:general

#3521 [DOCU-1973] Fix attribute and broken formatting in db keyring encryption
  app/enterprise/1.3-x/admin-api/db-encryption.md
  app/enterprise/1.5.x/admin-api/db-encryption.md
  app/enterprise/2.1.x/admin-api/db-encryption.md
  app/enterprise/2.2.x/admin-api/db-encryption.md
  app/enterprise/2.3.x/admin-api/db-encryption.md
  app/enterprise/2.4.x/admin-api/db-encryption.md
  app/enterprise/2.5.x/admin-api/db-encryption.md
  app/gateway/2.6.x/admin-api/db-encryption.md
  app/gateway/2.7.x/admin-api/db-encryption.md
Labels: review:general

#3522 OIDC plugin: Fix typo in param name
  app/_hub/kong-inc/openid-connect/2.0.x.md
  app/_hub/kong-inc/openid-connect/2.1.x.md
  app/_hub/kong-inc/openid-connect/index.md
Labels: review:general

#3523 [DOCU-2035] Badge tooltips
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/badges.less
  app/_assets/stylesheets/page.less
Labels: review:tech, review:copyedit

#3539 [DOCU-2117] Consumer groups not supported with deck
  app/_hub/kong-inc/rate-limiting-advanced/index.md
  app/gateway/2.7.x/admin-api/consumer-groups/examples.md
  app/gateway/2.7.x/admin-api/consumer-groups/reference.md
  app/gateway/changelog.md
Labels: review:general

#3551 [DOCU-2123] Cloud Dev Portal: Add custom domain page
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/customization/custom-domain.md
Labels: do not merge, review:copyedit

#3568 [DOCU-866] Remove marketplaces install tab from mesh docs
  app/_data/docs_nav_mesh_1.1.x.yml
  app/_data/docs_nav_mesh_1.2.x.yml
  app/_data/docs_nav_mesh_1.3.x.yml
  app/_data/docs_nav_mesh_1.4.x.yml
  app/_data/docs_nav_mesh_1.5.x.yml
  app/mesh/1.1.x/install.md
  app/mesh/1.2.x/install.md
  app/mesh/1.3.x/install.md
  app/mesh/1.4.x/install.md
  app/mesh/1.5.x/install.md
Labels: review:general

#3566 Make sidebar consistent with site top nav
  app/_includes/docs-sidebar.html
Labels: review:general

#3569 [DOCU-2112][DOCU-2113] Remove 25-hour limit for Vitals with InfluxDB
  app/enterprise/2.1.x/vitals/vitals-influx-strategy.md
  app/enterprise/2.2.x/vitals/vitals-influx-strategy.md
  app/enterprise/2.3.x/vitals/vitals-influx-strategy.md
  app/enterprise/2.4.x/vitals/vitals-influx-strategy.md
  app/enterprise/2.5.x/vitals/vitals-influx-strategy.md
  app/gateway/2.6.x/vitals/vitals-influx-strategy.md
  app/gateway/2.7.x/vitals/vitals-influx-strategy.md
Labels: review:general

#3564 Improve Gateway EE upgrade guide and fix wrong versions
  app/gateway-oss/2.4.x/upgrading.md
  app/gateway-oss/2.5.x/upgrading.md
  app/gateway/2.6.x/install-and-run/upgrade-enterprise.md
  app/gateway/2.6.x/install-and-run/upgrade-oss.md
  app/gateway/2.7.x/install-and-run/migrate-ce-to-ke.md
  app/gateway/2.7.x/install-and-run/upgrade-enterprise.md
  app/gateway/2.7.x/install-and-run/upgrade-oss.md
Labels: review:general

#3570 Fix Debian install and download links
  app/gateway/2.7.x/install-and-run/debian.md
Labels: review:general

#3562 Ensure there's a review:* label on all PRs
  .github/workflows/require-review-label.yml
  README.md
Labels: review:tech

#3559 Fix link in Wallarm plugin doc
  app/_hub/wallarm/wallarm/index.md
Labels: review:general

#3558 Fix link formatting in k8s custom resource ref
  app/kubernetes-ingress-controller/2.1.x/references/custom-resources.md
Labels: review:general

#3578 [DOCU-2151] add headers are modifiable
  app/konnect/updates.md
Labels: review:general

#3576 Automatically apply review:tech to Renovate PRs
  .github/renovate.json
Labels: review:tech

#3563 Full site link checker
  .github/workflows/check-links.yml
  README.md
  broken-link-checker/excluded.json
  broken-link-checker/full.js
  broken-link-checker/package-lock.json
  broken-link-checker/package.json
  broken-link-checker/pr.js
Labels: review:tech

#3560 Add ability to mark link checker as manually reviewed
  .github/workflows/check-links.yml
  README.md
Labels: ci:manual-approve:link-validation

#3581 [DOCU-2149] chore: Promo banner for webinar
  app/_assets/javascripts/app.js
  app/_assets/javascripts/promo-banner.js
  app/_includes/nav-v2.html
Labels: review:tech, review:general

#3561 [DOCU-1859] Deactivated orgs in Konnect
  app/_data/docs_nav_konnect.yml
  app/konnect/org-management/deactivation.md
Labels: review:general, review:copyedit

#3577 Fix positioning of `name` datatype for plugins
  app/_layouts/extension.html
Labels: review:general

#3583 Run npm audit fix
  package-lock.json
Labels: review:tech

#3585 doc(kic) update version compatibility tables
  app/kubernetes-ingress-controller/2.0.x/references/version-compatibility.md
  app/kubernetes-ingress-controller/2.1.x/references/version-compatibility.md
Labels: review:general

#3588 Remove max height from codeblocks
  app/_assets/stylesheets/page.less
Labels: review:general

#3591 Update require-review-label.yml
  .github/workflows/require-review-label.yml
Labels: review:tech

#3590 Add labels reminder to PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: review:general

#3592 Release: Gateway patches 2.7.1.0 and 2.6.0.3
  app/gateway/2.6.x/reference/configuration.md
  app/gateway/2.7.x/reference/configuration.md
  app/gateway/changelog.md
Labels: review:tech, review:general, ci:manual-approve:link-validation

#3587 Toggle all nav tabs with the same title
  app/_assets/javascripts/app.js
Labels: review:tech, review:general

#3589 Ensure sidebar + top nav module list is consistent
  app/_includes/nav-v2.html
  spec/sidebar_spec.rb
Labels: review:tech

#3593 [DOCU-1942] Consistent tab titles
  app/_includes/hub-examples.html
  app/gateway/2.6.x/get-started/comprehensive/expose-services.md
  app/gateway/2.7.x/get-started/comprehensive/expose-services.md
Labels: review:general

#3586 Add more vitals redirects
  app/_redirects
Labels: review:general

#3580 Replace OPA JWT example with long-lived token to fix #3579
  app/mesh/1.2.x/features/opa.md
  app/mesh/1.3.x/features/opa.md
  app/mesh/1.4.x/features/opa.md
  app/mesh/1.5.x/features/opa.md
Labels: review:general

#3596 Sidebar rendering speed improvements
  app/_includes/breadcrumbs.html
  app/_includes/docs-sidebar-item.html
  app/_includes/docs-sidebar.html
  app/_includes/head.html
  app/_includes/md/deb.md
  app/_includes/md/installation.md
  app/_includes/md/rpm.md
Labels: review:tech

#3595 Don't check 'Edit this page' links on forks
  broken-link-checker/pr.js
Labels: review:tech

#3597 Fix codeblock in Mesh Vault doc
  app/mesh/1.4.x/features/vault.md
  app/mesh/1.5.x/features/vault.md
Labels: review:general

#3599 Fix sidebar toggle visibility on mobile
  app/_includes/breadcrumbs.html
  app/_layouts/docs-v2.html
Labels: review:general

#3598 Remove scroll-to-top button from mobile
  app/_assets/stylesheets/page.less
Labels: review:general

#3582 [DOCU-1720] MVP Embedded Spotlight API documentation
  app/_assets/javascripts/promo-banner.js
  app/_assets/stylesheets/header-v2.less
  app/_assets/stylesheets/page.less
  app/_data/docs_nav_gateway_2.7.x.yml
  app/_redirects
  app/api/developer-portal.json
  app/gateway/2.7.x/developer-portal/files-api.md
  app/gateway/2.7.x/developer-portal/portal-api.md
Labels: do not merge, pr/wip

#3602 docs(oauth2) remove the nonexistent persistent_refresh_token field
  app/_hub/kong-inc/oauth2/index.md
Labels: review:general
