Repository Kong/docs.konghq.com, pull requests merged in 2022-11, with the labels that each got.

#4660 Add API documentation to Konnect (#4633)
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/api/identity.yaml
  app/konnect/api/filtering.md
  app/konnect/api/identity-management/identity-integration.md
  app/konnect/api/index.md
  app/konnect/identity-management-api.md
  app/konnect/updates.md
Labels: review:general, ci:check-skipped:generated-files

#4684 Remove stray todo
  src/gateway/production/deployment-topologies/hybrid-mode/index.md
Labels: review:general

#4685 Add beta banner to DCR doc
  app/konnect/dev-portal/applications/dynamic-client-registration/okta.md
  app/konnect/updates.md
Labels: review:general

#4686 [update] fips
  src/gateway/kong-enterprise/fips-support.md
Labels: review:copyedit

#4682 feat(acme): add support for Redis SSL
  .github/styles/kongplugins/auto-ignore.txt
  app/_hub/kong-inc/acme/_index.md
Labels: review:general, ci:check-skipped:generated-files

#4651 Change docs vaults link `vaults-entity` to `vaults-object`
  app/_data/docs_nav_gateway_3.0.x.yml
  app/gateway/2.8.x/plan-and-deploy/security/secrets-management/advanced-usage.md
  src/gateway/kong-enterprise/secrets-management/advanced-usage.md
Labels: review:copyedit

#4643 Release: Changelog for Gateway 3.0.1.0
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, review:sme

#4614 fix(auth): update reset token steps.
  app/gateway/2.8.x/configure/auth/kong-manager/reset-password.md
Labels: review:copyedit

#4694 Update identity.yaml with latest specs
  app/api/identity.yaml
Labels: review:copyedit

#4692 Release: 2.8.3
  app/_data/kong_versions.yml
Labels: review:general, pr/please review

#4698 Add manifests to gulps pipeline
  app/_assets/manifests/kubernetes-ingress-controller/examples/echo-service.yaml
  app/_assets/manifests/kubernetes-ingress-controller/examples/echo-services.yaml
  gulpfile.js
  src/kubernetes-ingress-controller/guides/using-gateway-api.md
Labels: review:tech

#4701 Set links web url accordingly
  gulpfile.js
  jekyll-dev.yml
Labels: review:tech

#4658 Add automatic submodule update workflow
  .github/workflows/sync-submodules.yml
Labels: review:tech

#4699 docs(mesh) Add docs for mesh RBAC for new policies
  src/mesh/features/rbac.md
Labels: review:copyedit

#4690 Update Getting Started to remove references to Kuma docs
  src/mesh/gettingstarted.md
Labels: review:copyedit

#4703 Add Kuma contribution link to Mesh intro.
  src/mesh/index.md
Labels: review:general

#4702 Version links to Kuma
  app/_includes/md/mesh/install-universal-quickstart.md
  app/_includes/md/mesh/install-universal-run.md
  src/mesh/features/acmpca.md
  src/mesh/features/cert-manager.md
  src/mesh/features/kds-auth.md
  src/mesh/features/opa.md
  src/mesh/features/vault.md
  src/mesh/gettingstarted.md
  src/mesh/index.md
  src/mesh/installation/docker.md
  src/mesh/installation/ecs.md
  src/mesh/installation/helm.md
  src/mesh/installation/kubernetes.md
  src/mesh/installation/openshift.md
  src/mesh/installation/windows.md
Labels: review:general, ci:manual-approve:link-validation

#4704 Update Identity OAS
  app/api/identity.yaml
Labels: review:copyedit

#4688 docs(compat) specify the minor version of RHEL 7
  app/_data/tables/os_support.yml
Labels: review:general

#4705 Add default namespace variable
  jekyll-dev.yml
  jekyll.yml
Labels: review:general

#4706 Update fips-support.md
  src/gateway/kong-enterprise/fips-support.md
Labels: review:copyedit

#4708 Kong Mesh Policies landing page
  .github/styles/kong/dictionary.txt
  app/_assets/images/icons/policies/icon-circuitbreaker.png
  app/_assets/images/icons/policies/icon-dataplane-metrics@2x.png
  app/_assets/images/icons/policies/icon-dp-cp-security@2x.png
  app/_assets/images/icons/policies/icon-external-services.png
  app/_assets/images/icons/policies/icon-fault-injection@2x.png
  app/_assets/images/icons/policies/icon-healthcheck@2x.png
  app/_assets/images/icons/policies/icon-kong-logo.png
  app/_assets/images/icons/policies/icon-mesh-multi-tenancy@2x.png
  app/_assets/images/icons/policies/icon-mtls@2x.png
  app/_assets/images/icons/policies/icon-proxy-template@2x.png
  app/_assets/images/icons/policies/icon-rate-limits.png
  app/_assets/images/icons/policies/icon-timeout@2x-80.jpg
  app/_assets/images/icons/policies/icon-traffic-control@2x.png
  app/_assets/images/icons/policies/icon-traffic-log@2x.png
  app/_assets/images/icons/policies/icon-traffic-route@2x.png
  app/_assets/images/icons/policies/icon-traffic-trace@2x.png
  app/_assets/images/icons/policies/retry@2x.png
  app/_assets/images/icons/policies/service-map@2x.png
  app/_assets/images/icons/policies/virtual-outbound@2x.png
  app/_data/docs_nav_mesh_2.0.x.yml
  app/_redirects
  src/mesh/policies.md
Labels: review:general

#4709 QA: Explore + Deploy
  app/_redirects
  src/mesh/plan-and-deploy/license.md
Labels: review:copyedit

#4710 Fix QA issues in Networking, Monitor & Manage, Resource Docs
  app/_data/docs_nav_mesh_2.0.x.yml
  app/_redirects
Labels: review:general

#4712 Kong Mesh QA: Intro, getting started, and install
  app/_data/docs_nav_mesh_2.0.x.yml
  app/_includes/md/mesh/install-universal-run.md
  app/_redirects
  src/mesh/features/kds-auth.md
  src/mesh/features/rbac.md
  src/mesh/index.md
  src/mesh/installation/kubernetes.md
Labels: review:general, ci:manual-approve:link-validation

#4696 fix: add table headers in String Transformations section
  src/gateway/reference/router-expressions-language.md
Labels: review:general, review:copyedit

#4564 mesh: rbac wildcard tag value
  src/mesh/features/rbac.md
Labels: review:general

#4714 QA for Policies in Mesh 2.0
  app/_data/docs_nav_mesh_2.0.x.yml
  app/_redirects
Labels: review:general

#4683 chore(request-validator): add more explanation for allowed_content_types of request-validator
  .github/styles/kongplugins/auto-ignore.txt
  app/_hub/kong-inc/request-validator/_index.md
Labels: review:general

#4720 Replace web url inline instead of appending the config to the file
  gulpfile.js
Labels: review:tech

#4681 feat(response-ratelimiting): add support for Redis SSL
  app/_hub/kong-inc/response-ratelimiting/_index.md
Labels: review:general

#4717 docs(mesh): update ECS docs for new workload identity feature
  app/mesh/changelog.md
  src/mesh/installation/ecs.md
Labels: review:copyedit

#4722 Add Kuma 2.0.0 to changelog
  app/mesh/changelog.md
Labels: review:copyedit

#4707 Update 2.0 Mesh nav to point to the correct folder
  app/_data/docs_nav_mesh_2.0.x.yml
Labels: do not merge, review:general

#4728 Add OIDC to list of sample enterprise plugins
  .github/workflows/linting.yml
  src/gateway/kong-enterprise/index.md
Labels: review:general

#4743 [fix] Support policy table issue
  app/_includes/md/support-policy.md
  src/gateway/support-policy.md
Labels: review:general

#4742 Add missing global plugins scope fix
  app/gateway/changelog.md
Labels: review:general

#4729 Add missing beta docs to Policies section
  app/_data/docs_nav_mesh_2.0.x.yml
Labels: review:general

#4741 feat: remove duplicate replace.body
  app/_hub/kong-inc/request-transformer/_index.md
Labels: review:general

#4727 feat(vault-auth): secrets engine v2 compatibility
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/vault-auth/_index.md
Labels: review:general, review:copyedit

#4744 fix typo
  .github/styles/kong/dictionary.txt
  app/enterprise/2.4.x/plugin-development/custom-logic.md
  app/enterprise/2.5.x/plugin-development/custom-logic.md
  app/gateway/2.6.x/plugin-development/custom-logic.md
  app/gateway/2.7.x/plugin-development/custom-logic.md
  app/gateway/2.8.x/plugin-development/custom-logic.md
Labels: review:general

#4746 Konnect DCR: Fix broken step
  app/konnect/dev-portal/applications/dynamic-client-registration/okta.md
Labels: review:general

#4716 feat(dcr): how to request with DCR [tdx-2587]
  app/konnect/dev-portal/applications/dynamic-client-registration/okta.md
Labels: review:general

#4473 [TDX-2195] Dev portal app reg with multi-runtime group support
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/runtime-manager/runtime-groups/index.md
Labels: review:general

#4749 decK: add env variable masking flag
  src/deck/reference/deck_diff.md
  src/deck/reference/deck_konnect_diff.md
  src/deck/reference/deck_konnect_sync.md
  src/deck/reference/deck_reset.md
  src/deck/reference/deck_sync.md
Labels: review:general, ci:check-skipped:generated-files

#4648 decK Release 1.16
  app/_data/docs_nav_deck_1.16.x.yml
  app/_data/kong_versions.yml
  src/deck/3.0-upgrade.md
  src/deck/availability-stages.md
  src/deck/compatibility-promise.md
  src/deck/design-architecture.md
  src/deck/faqs.md
  src/deck/guides/backup-restore.md
  src/deck/guides/best-practices.md
  src/deck/guides/ci-driven-configuration.md
  src/deck/guides/deduplicate-plugin-configuration.md
  src/deck/guides/defaults-v2.md
  src/deck/guides/defaults.md
  src/deck/guides/distributed-configuration.md
  src/deck/guides/environment-variables.md
  src/deck/guides/kong-enterprise.md
  src/deck/guides/multi-file-state.md
  src/deck/guides/security.md
  src/deck/guides/vaults.md
  src/deck/index.md
  src/deck/reference/deck.md
  src/deck/reference/deck_completion.md
  src/deck/reference/deck_convert.md
  src/deck/reference/deck_diff.md
  src/deck/reference/deck_dump.md
  src/deck/reference/deck_konnect.md
  src/deck/reference/deck_konnect_diff.md
  src/deck/reference/deck_konnect_dump.md
  src/deck/reference/deck_konnect_ping.md
  src/deck/reference/deck_konnect_sync.md
  src/deck/reference/deck_ping.md
  src/deck/reference/deck_reset.md
  src/deck/reference/deck_sync.md
  src/deck/reference/deck_validate.md
  src/deck/reference/deck_version.md
  src/gateway/kong-enterprise/secrets-management/advanced-usage.md
  src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
  src/gateway/kong-enterprise/secrets-management/backends/env.md
  src/gateway/kong-enterprise/secrets-management/backends/gcp-sm.md
  src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
Labels: review:copyedit, ci:check-skipped:generated-files

#4750 Add missing config parameter for AWS secrets vault
  src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
  src/gateway/kong-enterprise/secrets-management/how-to/aws-secrets-manager.md
Labels: review:general, review:sme

#4735 move API to Konnect
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_2.7.x.yml
  app/_data/docs_nav_gateway_2.8.x.yml
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/gateway/2.6.x/developer-portal/structure-and-file-types.md
  app/gateway/2.7.x/developer-portal/structure-and-file-types.md
  app/gateway/2.8.x/admin-api/developers/reference.md
  app/gateway/2.8.x/developer-portal/structure-and-file-types.md
  app/konnect/api/filtering.md
  app/konnect/api/identity-management/identity-integration.md
  app/konnect/api/index.md
  app/konnect/identity-management-api.md
  app/konnect/updates.md
  src/gateway/admin-api/developers/reference.md
  src/gateway/kong-enterprise/dev-portal/portal-api.md
  src/gateway/kong-enterprise/dev-portal/structure-and-file-types.md
Labels: review:general

#4752 chore: bump decK patch version
  app/_data/kong_versions.yml
Labels: review:general

#4739 Add specs to plugins
  .github/workflows/run-tests.yml
  Gemfile
  Gemfile.lock
  app/_plugins/generators/kuma_to_kong_mesh.rb
  spec/app/_plugins/generators/kuma_to_kong_mesh_spec.rb
  spec/fixtures/app/kuma-to-kong-mesh.md
  spec/spec_helper.rb
  spec/support/shared_contexts/site.rb
Labels: review:tech

#4737 Dead link #4736
  app/_hub/kong-inc/application-registration/_index.md
Labels: review:general

#4534 DOCU-2494 - CTA for onboarding nurture campaign
  app/_assets/javascripts/app.js
  src/gateway/index.md
Labels: review:general

#4755 [FTI-3281] add an option `config.disable_penalty` to rate-limiting-advanced plugin
  .github/styles/kongplugins/auto-ignore.txt
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
Labels: review:general

#4715 [FTI-4430] mtls-auth plugin supports sending ca dn in ssl handshake essage
  .github/styles/kongplugins/auto-ignore.txt
  .github/styles/kongplugins/dictionary.txt
  app/_hub/kong-inc/mtls-auth/_index.md
Labels: review:general

#4758 CTA to HTTPS
  src/gateway/index.md
Labels: review:general

#4756 chore(konnect-portal): remove section regarding supported TLDs (TDX-2586)
  app/konnect/dev-portal/customization/index.md
Labels: do not merge, review:general

#4753 Clean up CTA form styling and move to stylesheet
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/cta-form.less
  app/_assets/stylesheets/index.less
  src/gateway/index.md
Labels: review:general

#4747 [DOCU-2778] Rework installation doc support tables and overview pages
  app/_assets/images/icons/documentation/alpinelinux-icon.svg
  app/_assets/images/icons/documentation/linux-logo.svg
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_konnect.yml
  app/_data/tables/install_options.yml
  app/_data/tables/install_options_konnect.yml
  app/_includes/install.html
  app/konnect/install-support.md
  app/konnect/runtime-manager/runtime-instances/index.md
  app/moved_urls.yml
  src/gateway/install-support.md
  src/gateway/install/index.md
  src/gateway/os-support.md
  tests/sidebar.test.js
Labels: review:general

#4754 Allow version for protocols
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/_init/my-extension/_index.md
  app/_hub/amberflo/kong-plugin-amberflo/_index.md
  app/_hub/flash/set-dynamic-upstream-host/_index.md
  app/_hub/kong-inc/acl/_index.md
  app/_hub/kong-inc/acme/_index.md
  app/_hub/kong-inc/application-registration/_index.md
  app/_hub/kong-inc/aws-lambda/_index.md
  app/_hub/kong-inc/azure-functions/_index.md
  app/_hub/kong-inc/basic-auth/_index.md
  app/_hub/kong-inc/bot-detection/_index.md
  app/_hub/kong-inc/correlation-id/_index.md
  app/_hub/kong-inc/cors/_index.md
  app/_hub/kong-inc/datadog/_index.md
  app/_hub/kong-inc/exit-transformer/_index.md
  app/_hub/kong-inc/file-log/_index.md
  app/_hub/kong-inc/grpc-gateway/_index.md
  app/_hub/kong-inc/grpc-web/_index.md
  app/_hub/kong-inc/hmac-auth/_index.md
  app/_hub/kong-inc/http-log/_index.md
  app/_hub/kong-inc/ip-restriction/_index.md
  app/_hub/kong-inc/jq/_index.md
  app/_hub/kong-inc/jwt-signer/_index.md
  app/_hub/kong-inc/jwt/_index.md
  app/_hub/kong-inc/key-auth-enc/_index.md
  app/_hub/kong-inc/key-auth/_index.md
  app/_hub/kong-inc/ldap-auth-advanced/_index.md
  app/_hub/kong-inc/ldap-auth/_index.md
  app/_hub/kong-inc/loggly/_index.md
  app/_hub/kong-inc/mocking/_index.md
  app/_hub/kong-inc/mtls-auth/_index.md
  app/_hub/kong-inc/oauth2/_index.md
  app/_hub/kong-inc/opa/_index.md
  app/_hub/kong-inc/openid-connect/_index.md
  app/_hub/kong-inc/opentelemetry/_index.md
  app/_hub/kong-inc/prometheus/_1.6.0.md
  app/_hub/kong-inc/prometheus/_index.md
  app/_hub/kong-inc/proxy-cache-advanced/_index.md
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
  app/_hub/kong-inc/rate-limiting/_index.md
  app/_hub/kong-inc/request-size-limiting/_index.md
  app/_hub/kong-inc/request-termination/_index.md
  app/_hub/kong-inc/request-transformer/_index.md
  app/_hub/kong-inc/response-ratelimiting/_index.md
  app/_hub/kong-inc/response-transformer/_index.md
  app/_hub/kong-inc/serverless-functions/_index.md
  app/_hub/kong-inc/statsd-advanced/_2.2.x.md
  app/_hub/kong-inc/statsd-advanced/_index.md
  app/_hub/kong-inc/statsd/_index.md
  app/_hub/kong-inc/syslog/_index.md
  app/_hub/kong-inc/tcp-log/_index.md
  app/_hub/kong-inc/tls-handshake-modifier/_index.md
  app/_hub/kong-inc/tls-metadata-headers/_index.md
  app/_hub/kong-inc/udp-log/_index.md
  app/_hub/kong-inc/upstream-timeout/_index.md
  app/_hub/kong-inc/zipkin/_index.md
  app/_hub/moesif/kong-plugin-moesif/_index.md
  app/_layouts/extension.html
Labels: review:tech, ci:check-skipped:generated-files

#4760 Plugin broken links
  .github/workflows/check-links.yml
  tools/broken-link-checker/README.md
  tools/broken-link-checker/config/ignored_paths.json
  tools/broken-link-checker/config/ignored_targets.json
  tools/broken-link-checker/lib/check-url-list.js
  tools/broken-link-checker/lib/nav-to-url.js
  tools/broken-link-checker/lib/src-to-urls.js
  tools/broken-link-checker/pr.js
  tools/broken-link-checker/product.js
  tools/broken-link-checker/run.js
Labels: review:tech

#4759 [fix] remove empty achor link from URL
  app/gateway/2.6.x/reference/configuration.md
  app/gateway/2.7.x/reference/configuration.md
  app/gateway/2.8.x/reference/configuration.md
  src/gateway/reference/configuration.md
Labels: review:general, ci:manual-approve:link-validation, ci:manual-approve:generated-files

#4764 fix(plugins): update konnect cloud link in konnect-compatible plugin badge
  app/_includes/header.html
Labels: review:general

#4761 fix(response-rl): explanation of month and year
  app/_hub/kong-inc/response-ratelimiting/_index.md
Labels: review:general

#4763 chore(kong-gateway): remove Kong Manager tip in plugin ordering
  src/gateway/kong-enterprise/plugin-ordering/index.md
Labels: review:general

#4723 docs(plugins): add WebSocket protocols to supported plugins
  app/_hub/kong-inc/basic-auth/_index.md
  app/_hub/kong-inc/file-log/_index.md
  app/_hub/kong-inc/hmac-auth/_index.md
  app/_hub/kong-inc/http-log/_index.md
  app/_hub/kong-inc/kafka-log/_index.md
  app/_hub/kong-inc/key-auth-enc/_index.md
  app/_hub/kong-inc/key-auth/_index.md
  app/_hub/kong-inc/ldap-auth-advanced/_index.md
  app/_hub/kong-inc/ldap-auth/_index.md
  app/_hub/kong-inc/loggly/_index.md
  app/_hub/kong-inc/oauth2/_index.md
  app/_hub/kong-inc/serverless-functions/_index.md
  app/_hub/kong-inc/syslog/_index.md
  app/_hub/kong-inc/tcp-log/_index.md
  app/_hub/kong-inc/udp-log/_index.md
Labels: review:general

#4765 Fix typo in `config.add.querystring` description
  app/_hub/kong-inc/request-transformer/_index.md
Labels: review:general

#4697 update for forward proxy: x_headers
  .github/styles/kong/dictionary.txt
  .github/styles/kongplugins/dictionary.txt
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/forward-proxy/_index.md
Labels: review:sme

#4770 chore: uses REPO argument in installer.sh script
  app/mesh/installer.sh
Labels: review:copyedit

#4774 Fix broken link checker
  tools/broken-link-checker/lib/src-to-urls.js
Labels: review:tech

#4689 update for runtime cert management feature
  app/konnect/runtime-manager/gateway-config.md
  app/konnect/runtime-manager/index.md
  app/konnect/runtime-manager/runtime-instances/renew-certificates.md
  app/konnect/updates.md
Labels: review:copyedit

#4740 plugin(xml-threat) adds new plugin documentation
  .github/styles/kongplugins/plugin-ignore.txt
  app/_assets/images/icons/hub/kong-inc_xml-threat-protection.png
  app/_hub/kong-inc/xml-threat-protection/_index.md
  app/_hub/kong-inc/xml-threat-protection/versions.yml
Labels: review:general

#4778 Plugin protocols: fix errors, use new formatting, and set min versions
  app/_hub/SmartParkingTechnology/google-logging/_index.md
  app/_hub/inspur/apig-request-transformer/_index.md
  app/_hub/inspur/apig-response-transform/_index.md
  app/_hub/kong-inc/basic-auth/_index.md
  app/_hub/kong-inc/file-log/_index.md
  app/_hub/kong-inc/hmac-auth/_index.md
  app/_hub/kong-inc/http-log/_index.md
  app/_hub/kong-inc/kafka-log/_index.md
  app/_hub/kong-inc/key-auth-enc/_index.md
  app/_hub/kong-inc/key-auth/_index.md
  app/_hub/kong-inc/ldap-auth-advanced/_index.md
  app/_hub/kong-inc/ldap-auth/_index.md
  app/_hub/kong-inc/loggly/_index.md
  app/_hub/kong-inc/oauth2/_index.md
  app/_hub/kong-inc/serverless-functions/_index.md
  app/_hub/kong-inc/syslog/_index.md
  app/_hub/kong-inc/tcp-log/_index.md
  app/_hub/kong-inc/udp-log/_index.md
  app/_hub/kong-inc/websocket-size-limit/_index.md
  app/_hub/kong-inc/websocket-validator/_index.md
  app/_hub/qnap/api-transformer/_index.md
  app/_hub/reedelk/reedelk-transformer/_index.md
  app/_hub/seifchen/kong-path-allow/_index.md
  app/_hub/yesinteractive/kong-jwt2header/_index.md
  app/_hub/yesinteractive/kong-log-google/_index.md
Labels: review:general

#4780 docs(readme): add submodule update instructions
  README.md
Labels: review:general

#4779 kic: add translation failures troubleshooting section
  .github/styles/kong/auto-ignore.txt
  src/kubernetes-ingress-controller/references/prometheus.md
  src/kubernetes-ingress-controller/troubleshooting.md
Labels: Kubernetes Team, review:general

#4732 [DOCU-2464] Document new Analytics roles
  app/konnect/analytics/index.md
  app/konnect/org-management/teams-and-roles/teams-reference.md
  app/konnect/updates.md
Labels: do not merge, review:sme

#4781 Add uninstall instructions to Ubuntu
  src/gateway/install/linux/ubuntu.md
Labels: review:copyedit

#4124 [DOCU-1924] New "Manage decK with Docker" page
  app/_data/docs_nav_deck_1.10.x.yml
  app/_data/docs_nav_deck_1.11.x.yml
  app/_data/docs_nav_deck_1.12.x.yml
  app/_data/docs_nav_deck_1.13.x.yml
  app/_data/docs_nav_deck_1.14.x.yml
  app/_data/docs_nav_deck_1.15.x.yml
  app/_data/docs_nav_deck_1.16.x.yml
  app/_data/docs_nav_deck_1.7.x.yml
  app/_data/docs_nav_deck_1.8.x.yml
  app/_data/docs_nav_deck_1.9.x.yml
  src/deck/guides/run-with-docker.md
  src/deck/installation.md
Labels: review:general, review:copyedit

#3986 [FTI-3323]add include_uri_captures_in_opa_input option to OPA plugin
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/opa/_index.md
Labels: review:general, ci:check-skipped:generated-files

#4783 Plugin template: Update and add sample versions file
  app/_hub/_init/my-extension/_index.md
  app/_hub/_init/my-extension/versions.yml
Labels: review:copyedit

#4748 [DOCU-2517] App Reg Multiple RGs and DCR - GA release
  app/konnect/dev-portal/applications/dynamic-client-registration/okta.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/runtime-manager/runtime-groups/index.md
  app/konnect/updates.md
Labels: review:general

#3902 [FT-1816] new enterprise OAS Validation plugin
  .github/styles/kongplugins/plugin-ignore.txt
  app/_assets/images/icons/hub/kong-inc_oas-validation.png
  app/_hub/kong-inc/oas-validation/_index.md
  app/_hub/kong-inc/oas-validation/versions.yml
Labels: review:general, review:copyedit, review:sme

#4788 Add a/b test support for the top CTA
  app/_assets/javascripts/ab-test.js
  app/_includes/nav-v2.html
  gulpfile.js
  package-lock.json
  package.json
Labels: review:tech

#4786 chore: Bump plugin versions for 3.1
  app/_hub/kong-inc/jq/versions.yml
  app/_hub/kong-inc/kong-terraform-aws/_index.md
  app/_hub/kong-inc/mocking/versions.yml
  app/_hub/kong-inc/opa/versions.yml
  app/_hub/kong-inc/opentelemetry/_index.md
  app/_hub/kong-inc/opentelemetry/versions.yml
  app/_hub/kong-inc/tls-handshake-modifier/_index.md
  app/_hub/kong-inc/tls-handshake-modifier/versions.yml
  app/_hub/kong-inc/tls-metadata-headers/_index.md
  app/_hub/kong-inc/tls-metadata-headers/versions.yml
  app/_hub/kong-inc/websocket-size-limit/_index.md
  app/_hub/kong-inc/websocket-size-limit/versions.yml
  app/_hub/kong-inc/websocket-validator/_index.md
  app/_hub/kong-inc/websocket-validator/versions.yml
Labels: review:general

#4792 Merge branch 'main' into konnect
  .github/styles/kong/auto-ignore.txt
  README.md
  app/_assets/javascripts/ab-test.js
  app/_data/docs_nav_deck_1.10.x.yml
  app/_data/docs_nav_deck_1.11.x.yml
  app/_data/docs_nav_deck_1.12.x.yml
  app/_data/docs_nav_deck_1.13.x.yml
  app/_data/docs_nav_deck_1.14.x.yml
  app/_data/docs_nav_deck_1.15.x.yml
  app/_data/docs_nav_deck_1.16.x.yml
  app/_data/docs_nav_deck_1.7.x.yml
  app/_data/docs_nav_deck_1.8.x.yml
  app/_data/docs_nav_deck_1.9.x.yml
  app/_hub/_init/my-extension/_index.md
  app/_hub/_init/my-extension/versions.yml
  app/_hub/kong-inc/request-transformer/_index.md
  app/_includes/nav-v2.html
  app/konnect/dev-portal/applications/dynamic-client-registration/okta.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/runtime-manager/runtime-groups/index.md
  app/konnect/updates.md
  app/mesh/installer.sh
  gulpfile.js
  package-lock.json
  package.json
  src/deck/guides/run-with-docker.md
  src/deck/installation.md
  src/gateway/install/linux/ubuntu.md
  src/kubernetes-ingress-controller/references/prometheus.md
  src/kubernetes-ingress-controller/troubleshooting.md
  tools/broken-link-checker/lib/src-to-urls.js
Labels: review:general

#4782 New Analytics roles cherry pick (#4732)
  app/konnect/analytics/index.md
  app/konnect/org-management/teams-and-roles/teams-reference.md
  app/konnect/updates.md
Labels: review:general

#4794 Remove kongverge plugin
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/justeat/kongverge/_index.md
  app/_redirects
Labels: review:general

#4776 [chore] Cherry pick #4689
  app/konnect/runtime-manager/gateway-config.md
  app/konnect/runtime-manager/index.md
  app/konnect/runtime-manager/runtime-instances/renew-certificates.md
  app/konnect/updates.md
Labels: review:general

#4771 Refactor the Single Source Plugin generator and add specs
  app/_plugins/generators/plugin_single_source/kong_versions.rb
  app/_plugins/generators/plugin_single_source/plugin/base.rb
  app/_plugins/generators/plugin_single_source/plugin/releases_generator.rb
  app/_plugins/generators/plugin_single_source/plugin/unversioned.rb
  app/_plugins/generators/plugin_single_source/plugin/versioned.rb
  app/_plugins/generators/plugin_single_source/single_source_page.rb
  app/_plugins/generators/plugin_single_source_generator.rb
  spec/app/_plugins/generators/plugin_single_source/kong_versions_spec.rb
  spec/app/_plugins/generators/plugin_single_source/plugin/base_spec.rb
  spec/app/_plugins/generators/plugin_single_source/plugin/releases_generator_spec.rb
  spec/app/_plugins/generators/plugin_single_source/plugin/unversioned_spec.rb
  spec/app/_plugins/generators/plugin_single_source/plugin/versioned_spec.rb
  spec/app/_plugins/generators/plugin_single_source/single_source_page_spec.rb
  spec/app/_plugins/generators/plugin_single_source_generator_spec.rb
  spec/fixtures/app/_data/kong_versions.yml
  spec/fixtures/app/_hub/_init/my-extension/_index.md
  spec/fixtures/app/_hub/acme/jq/_index.md
  spec/fixtures/app/_hub/acme/jq/versions.yml
  spec/fixtures/app/_hub/acme/jwt-signer/2.1.x.md
  spec/fixtures/app/_hub/acme/jwt-signer/_2.2.x.md
  spec/fixtures/app/_hub/acme/jwt-signer/_index.md
  spec/fixtures/app/_hub/acme/jwt-signer/versions.yml
  spec/fixtures/app/_hub/acme/kong-plugin/_index.md
  spec/spec_helper.rb
  spec/support/shared_examples/plugin_single_source/plugin.rb
Labels: review:tech

#4801 Fix flaky spec
  tests/seo.test.js
Labels: review:tech

#4785 docs(consumer_group): add delete api for consumer group configuration
  src/gateway/admin-api/consumer-groups/reference.md
  src/gateway/kong-enterprise/consumer-groups/index.md
Labels: review:sme

#4784 [DOCU-2633] Release: Gateway 2.8.2.1
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit

#4800 fix link for installing services in promstack guide
  src/kubernetes-ingress-controller/guides/prometheus-grafana.md
Labels: review:copyedit

#4797 DOCU-2809
  app/konnect/network.md
Labels: review:general

#4807 Fix HCV mount name in Result object
  app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/hashicorp-vault.md
  src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
Labels: review:copyedit

#4806 chore(portal): add note for multi rg regarding plugins (TDX-2637)
  app/konnect/dev-portal/applications/enable-app-reg.md
Labels: review:general

#4808 DOCU-2803 - AppReg for multi RGs GA
  app/konnect/updates.md
Labels: review:general

#4700 docs(plugin): Add AppDynamics plugin documentation
  app/_assets/images/icons/hub/kong-inc_app-dynamics.png
  app/_data/tables/plugin_index.yml
  app/_hub/kong-inc/app-dynamics/_index.md
  app/_hub/kong-inc/app-dynamics/versions.yml
Labels: review:general, review:copyedit, ci:check-skipped:generated-files, review:sme

#4734 docs(plugin): Add SAML plugin documentation
  .github/styles/kong/dictionary.txt
  .github/styles/kongplugins/dictionary.txt
  .github/styles/kongplugins/plugin-ignore.txt
  app/_assets/images/docs/saml/azuread_basic_config.png
  app/_assets/images/docs/saml/azuread_sso_url.png
  app/_assets/images/icons/hub/kong-inc_saml.png
  app/_data/tables/plugin_index.yml
  app/_hub/kong-inc/saml/_index.md
  app/_hub/kong-inc/saml/versions.yml
Labels: review:general, review:copyedit, review:sme

#4815 Update KongVersions to fetch the file relative to the site's source
  app/_plugins/generators/plugin_single_source/kong_versions.rb
  app/_plugins/generators/plugin_single_source/plugin/versioned.rb
  spec/app/_plugins/generators/plugin_single_source/kong_versions_spec.rb
Labels: review:tech

#4814 Update plugin versions and compatibility table
  app/_data/tables/plugin_index.yml
  app/_hub/kong-inc/app-dynamics/_index.md
  app/_hub/kong-inc/app-dynamics/versions.yml
  app/_hub/kong-inc/oas-validation/versions.yml
  app/_hub/kong-inc/saml/versions.yml
  app/_hub/kong-inc/xml-threat-protection/versions.yml
Labels: review:general

#4816 Clarify minimum_version in plugin template [skip ci]
  app/_hub/_init/my-extension/versions.yml
Labels: review:copyedit, ci:manual-approve:link-validation

#4791 [DOCU-2779] Allow root path to be specified for Kong Manager
  app/gateway/changelog.md
  src/gateway/kong-manager/enable.md
Labels: review:copyedit

#4465 Content type templates
  docs/templates/explanation-template.md
  docs/templates/how-to-template.md
  docs/templates/reference-template.md
  docs/templates/tutorial-template.md
Labels: review:general

#4821 (docs)mesh remove operator feature
  app/_data/tables/features/mesh.yml
Labels: review:general

#4802 docs(plugis): add jwe-decrypt plugin docs
  .github/styles/kongplugins/plugin-ignore.txt
  app/_assets/images/icons/hub/kong-inc_jwe-decrypt.png
  app/_data/tables/plugin_index.yml
  app/_hub/kong-inc/jwe-decrypt/_index.md
  app/_hub/kong-inc/jwe-decrypt/versions.yml
  app/_redirects
Labels: do not merge, review:copyedit

#4789 [docu-2751] Dynamic log levels
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_redirects
  src/gateway/production/logging.md
  src/gateway/production/logging/customize-gateway-logs.md
  src/gateway/production/logging/log-reference.md
  src/gateway/production/logging/update-log-level-dynamically.md
Labels: review:copyedit

#4827 Fix link to key management page on JWE Decrypt plugin
  app/_hub/kong-inc/jwe-decrypt/_index.md
Labels: review:general

#4790 [DOCU-2783] Plugin ordering in Kong Manager
  src/gateway/kong-enterprise/plugin-ordering/get-started.md
  src/gateway/kong-enterprise/plugin-ordering/index.md
Labels: review:copyedit

#4835 docs(vitals): remove content for vitals reports
  app/_data/docs_nav_gateway_3.1.x.yml
  src/gateway/kong-enterprise/analytics/index.md
Labels: review:copyedit

#4833 chore: Plugin priority 3.1 updates
  src/gateway/plugin-development/custom-logic.md
Labels: review:general

#4812 Runtime group API Konnect
  app/_data/docs_nav_konnect.yml
  app/konnect/api/filtering.md
  app/konnect/api/index.md
  app/konnect/updates.md
Labels: review:general

#4832 [DOCU-2763] Secrets management in Kong Manager
  .github/styles/kong/dictionary.txt
  app/_assets/images/docs/gateway/km_workspace_3.0.png
  app/_assets/images/docs/gateway/km_workspace_3.1.png
  src/gateway/kong-enterprise/secrets-management/advanced-usage.md
  src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
  src/gateway/kong-enterprise/secrets-management/backends/env.md
  src/gateway/kong-enterprise/secrets-management/backends/gcp-sm.md
  src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
  src/gateway/kong-manager/index.md
Labels: review:copyedit

#4718 Add Deck Windows installation instructions
  src/deck/installation.md
Labels: ci:manual-approve:link-validation, review:sme

#4775 feat: Kubernetes Auth Method
  src/gateway/kong-enterprise/db-encryption.md
  src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
  src/gateway/reference/configuration.md
Labels: review:copyedit, ci:manual-approve:link-validation, review:sme, ci:manual-approve:linting, ci:manual-approve:generated-files

#4840 chore: Config reference for 3.1
  autodoc-conf-ee/data.lua
  src/gateway/reference/configuration.md
Labels: review:general, ci:manual-approve:generated-files

#4842 [docu-2777] Konnect release notes for GW 3.1
  app/konnect/compatibility.md
  app/konnect/updates.md
Labels: review:general

#4843 [docu-2777] Konnect release notes for GW 3.1 (#4842)
  app/konnect/compatibility.md
  app/konnect/updates.md
Labels: review:general
