Repository Kong/docs.konghq.com, pull requests merged in 2022-07, with the labels that each got.

#4013 [DOCU-2357]Overview Dashboard page for Konnect
  app/_data/docs_nav_konnect.yml
  app/konnect/vitals/analyze.md
  app/konnect/vitals/overview-dashboard.md
Labels: do not merge, review:copyedit

#4074 DOCU-2369: Removes prompts from instruction commands
  src/kubernetes-ingress-controller/guides/getting-started.md
Labels: review:general

#4079 fix(mesh): add missing group in rbac example
  app/mesh/1.6.x/features/rbac.md
  src/mesh/features/rbac.md
Labels: review:copyedit

#4073 Consolidate Konnect getting started guides
  app/_data/docs_nav_konnect.yml
  app/_includes/md/konnect/create-service.md
  app/_includes/md/konnect/dev-portal-access.md
  app/_includes/md/konnect/dev-portal-description.md
  app/_includes/md/konnect/dev-portal-spec.md
  app/_includes/md/konnect/docker-runtime.md
  app/_includes/md/konnect/implement-service.md
  app/_includes/md/konnect/service-version.md
  app/konnect/getting-started/access-account.md
  app/konnect/getting-started/app-registration.md
  app/konnect/getting-started/configure-runtime.md
  app/konnect/getting-started/configure-service.md
  app/konnect/getting-started/implement-service.md
  app/konnect/getting-started/import.md
  app/konnect/getting-started/index.md
  app/konnect/getting-started/publish-service.md
  app/konnect/getting-started/spec/implement.md
  app/konnect/getting-started/spec/publish.md
  app/konnect/getting-started/spec/service.md
Labels: review:copyedit

#4086 Fix broken link in https://docs.konghq.com/mesh/latest/features/cert-manager/
  src/mesh/features/cert-manager.md
Labels: review:general

#4092 chore: Bump decK version to 1.12.3
  app/_data/kong_versions.yml
Labels: review:general

#4090 Konnect: Remove language on the number of runtime groups
  app/konnect/runtime-manager/runtime-groups/index.md
Labels: review:copyedit

#4078 docs(acl) fix an Admin API usage error
  app/_hub/kong-inc/acl/_index.md
Labels: review:copyedit

#4071 FTI-4122 note forward-proxy with upstream
  app/_hub/kong-inc/forward-proxy/_index.md
Labels: review:copyedit

#4081 Add UBI install instructions to the correct doc
  app/_includes/md/rpm.md
  app/gateway/2.8.x/install-and-run/rhel.md
Labels: review:tech, review:general

#4099 docs(mesh) update Kong Mesh support policy dates
  app/konnect-platform/support-policy.md
Labels: pr/please review, review:general, size/S

#4100 [fix] Vale ignore terms values in anchor tags
  vale.ini
Labels: Core Team review, review:general

#4096 Konnect intro section cleanup
  .github/styles/kong/dictionary.txt
  app/konnect/architecture.md
  app/konnect/compatibility.md
  app/konnect/network-resiliency.md
Labels: review:general

#4095 [DOCU-2315] Dev Portal section copy edits
  .github/styles/kong/Terms.yml
  .github/styles/kong/dictionary.txt
  app/konnect/dev-portal/Troubleshooting/index.md
  app/konnect/dev-portal/access-and-approval/auto-approve-devs-apps.md
  app/konnect/dev-portal/access-and-approval/manage-app-connections.md
  app/konnect/dev-portal/access-and-approval/manage-app-reg-requests.md
  app/konnect/dev-portal/access-and-approval/manage-devs.md
  app/konnect/dev-portal/access.md
  app/konnect/dev-portal/applications/application-overview.md
  app/konnect/dev-portal/applications/dev-apps.md
  app/konnect/dev-portal/applications/dev-gen-creds.md
  app/konnect/dev-portal/applications/dev-reg-app-service.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/dev-portal/customization/index.md
  app/konnect/dev-portal/dev-reg.md
  app/konnect/dev-portal/index.md
  app/konnect/legacy/dev-portal/applications/enable-app-reg.md
Labels: Core Team review, review:general

#4097 doc(keyring) reorder the structure, mention new options for Data Plane
  src/gateway/admin-api/db-encryption.md
  src/gateway/plan-and-deploy/security/db-encryption.md
Labels: pr/please review, review:copyedit

#4088 feat(portal): Improve Dev Portal Customization page and remove Allowed TLDs section
  app/konnect/dev-portal/customization/index.md
Labels: review:copyedit

#4091 [DOCU-2317] Konnect administer section clean-up and validation
  app/_data/docs_nav_konnect.yml
  app/konnect/account-management/billing.md
  app/konnect/account-management/change-plan.md
  app/konnect/account-management/index.md
  app/konnect/org-management/okta-idp.md
  app/konnect/org-management/teams-and-roles/index.md
  app/konnect/org-management/teams-and-roles/manage.md
  app/konnect/org-management/teams-and-roles/roles-reference.md
  app/konnect/org-management/teams-and-roles/teams-reference.md
  app/konnect/org-management/users.md
Labels: review:copyedit

#4106 Update kong-enterprise.md
  src/deck/guides/kong-enterprise.md
Labels: review:copyedit

#4082 [DOCU-2314] Konnect Service Hub: UI validation and style cleanup
  app/_assets/images/icons/konnect/icn-markdown.svg
  app/konnect/servicehub/enable-route-plugin.md
  app/konnect/servicehub/enable-service-plugin.md
  app/konnect/servicehub/index.md
  app/konnect/servicehub/manage-services.md
  app/konnect/servicehub/plugins.md
  app/konnect/servicehub/service-documentation.md
  app/konnect/servicehub/service-implementations.md
  app/konnect/servicehub/service-versions.md
Labels: review:copyedit

#4104 chore(Issue Templates) Fix improve-existing-docs.yaml grammar issues
  .github/ISSUE_TEMPLATE/improve-existing-docs.yaml
Labels: review:copyedit

#4087 Fixed mixture of Kong schema and Draft 4
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/request-validator/_index.md
Labels: review:general

#4108 Badge adjustments
  app/_assets/stylesheets/badges.less
  app/_layouts/docs-v2.html
Labels: review:general

#4105 Add Kong PG SSL for Azure postgres database
  app/_hub/tomkerkhove/microsoft_azure_container_instances/_index.md
Labels: review:copyedit, ci:check-skipped:generated-files

#4102 Konnect nav rework redirects
  app/_redirects
  app/konnect/dev-portal/index.md
  app/konnect/getting-started/import.md
  app/konnect/reference/proxy-traffic.md
Labels: review:general

#4080 [DOCU-268] Note about setting the KONG_PASSWORD
  app/_includes/md/gateway/setup.md
  app/gateway/2.6.x/plan-and-deploy/security/start-kong-securely.md
  app/gateway/2.7.x/plan-and-deploy/security/start-kong-securely.md
  app/gateway/2.8.x/plan-and-deploy/security/start-kong-securely.md
Labels: review:copyedit

#4112 [DOCU-2385] Product links in footer
  app/_includes/footer.html
Labels: review:general

#4115 Add support for moving URLs and setting canonical URL correctly
  app/_plugins/generators/canonical_url_generator.rb
  app/moved_urls.yml
  docs/seo.md
  tests/seo.test.js
Labels: review:tech

#4121 [fix] Small copy edits
  app/konnect/servicehub/index.md
Labels: review:copyedit

#4113 fix(mTLS-auth) revise the inaccurate descriptions
  app/_hub/kong-inc/mtls-auth/1.3-x.md
  app/_hub/kong-inc/mtls-auth/_index.md
Labels: review:general

#4119 feat(portal): update list of supported TLDs for Dev Portal Custom URLs [TDX-2218]
  app/konnect/dev-portal/customization/index.md
Labels: review:copyedit

#4120 [DOCU-2157] Konnect with decK: app registration and migration
  app/konnect/getting-started/import.md
  src/deck/guides/konnect.md
Labels: review:copyedit

#4117 Kong GW quickstart remove C* config and use PG_HOST
  app/gateway/2.8.x/get-started/quickstart/index.md
Labels: review:general

#4125 chore/Copy changes from 2.8.x to src directory
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/admin-api/index.md
  src/gateway/configure/auth/kong-manager/sessions.md
  src/gateway/configure/graphql-quickstart.md
  src/gateway/developer-portal/administration/managing-developers.md
  src/gateway/developer-portal/configuration/smtp.md
  src/gateway/developer-portal/theme-customization/emails.md
  src/gateway/developer-portal/working-with-templates.md
  src/gateway/get-started/comprehensive/expose-services.md
  src/gateway/get-started/comprehensive/secure-services.md
  src/gateway/get-started/quickstart/configuring-a-service.md
  src/gateway/index.md
  src/gateway/install-and-run/amazon-linux.md
  src/gateway/install-and-run/centos.md
  src/gateway/install-and-run/debian.md
  src/gateway/install-and-run/docker.md
  src/gateway/install-and-run/helm.md
  src/gateway/install-and-run/index.md
  src/gateway/install-and-run/kubernetes.md
  src/gateway/install-and-run/openshift.md
  src/gateway/install-and-run/rhel.md
  src/gateway/install-and-run/ubuntu.md
  src/gateway/install-and-run/upgrade-oss.md
  src/gateway/pdk/index.md
  src/gateway/pdk/kong.client.md
  src/gateway/pdk/kong.client.tls.md
  src/gateway/pdk/kong.cluster.md
  src/gateway/pdk/kong.ctx.md
  src/gateway/pdk/kong.ip.md
  src/gateway/pdk/kong.log.md
  src/gateway/pdk/kong.nginx.md
  src/gateway/pdk/kong.node.md
  src/gateway/pdk/kong.request.md
  src/gateway/pdk/kong.response.md
  src/gateway/pdk/kong.router.md
  src/gateway/pdk/kong.service.md
  src/gateway/pdk/kong.service.request.md
  src/gateway/pdk/kong.service.response.md
  src/gateway/pdk/kong.table.md
  src/gateway/pdk/kong.vault.md
  src/gateway/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
  src/gateway/plan-and-deploy/licenses/access-license.md
  src/gateway/plan-and-deploy/security/start-kong-securely.md
  src/gateway/plugin-development/custom-logic.md
  src/gateway/reference/cli.md
  src/gateway/reference/clustering.md
  src/gateway/reference/configuration.md
  src/gateway/reference/external-plugins.md
  src/gateway/reference/health-checks-circuit-breakers.md
  tests/edit_link.test.js
Labels: review:general, ci:check-skipped:generated-files

#4070 Release: Gateway 2.8.1.2
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#4126 Clean up branding and descriptions for Konnect
  app/_data/landing_page.yml
  app/_hub/kong-inc/application-registration/_index.md
  app/_includes/breadcrumbs.html
  app/_includes/hub-examples.html
  app/_layouts/landing-page.html
  app/contributing/word-choice.md
  app/konnect/servicehub/service-implementations.md
Labels: review:general

#4130 Update index.md
  app/gateway/2.8.x/pdk/index.md
Labels: review:general

#4129 Guide `ingress-class` instead of `ingress.class` for Knative
  app/_data/docs_nav_kic_2.2.x.yml
  app/_data/docs_nav_kic_2.3.x.yml
  app/_data/docs_nav_kic_2.4.x.yml
  src/kubernetes-ingress-controller/guides/using-kong-with-knative.md
Labels: review:copyedit

#4136 Single source plugin batch
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/azure-functions/0.1-x.md
  app/_hub/kong-inc/azure-functions/_index.md
  app/_hub/kong-inc/azure-functions/versions.yml
  app/_hub/kong-inc/cors/0.1-x.md
  app/_hub/kong-inc/cors/_index.md
  app/_hub/kong-inc/cors/versions.yml
  app/_hub/kong-inc/ee-openid-connect-rp/_index.md
  app/_hub/kong-inc/exit-transformer/1.3-x.md
  app/_hub/kong-inc/exit-transformer/_index.md
  app/_hub/kong-inc/exit-transformer/versions.yml
  app/_hub/kong-inc/graphql-proxy-cache-advanced/_index.md
  app/_hub/kong-inc/graphql-proxy-cache-advanced/versions.yml
  app/_hub/kong-inc/graphql-rate-limiting-advanced/0.1.x.md
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
  app/_hub/kong-inc/graphql-rate-limiting-advanced/versions.yml
  app/_hub/kong-inc/jq/_index.md
  app/_hub/kong-inc/jq/versions.yml
  app/_hub/kong-inc/kubernetes-sidecar-injector/_index.md
  app/_hub/kong-inc/mocking/0.1.x.md
  app/_hub/kong-inc/mocking/_index.md
  app/_hub/kong-inc/mocking/versions.yml
  app/_hub/kong-inc/opa/0.1.x.md
  app/_hub/kong-inc/opa/_index.md
  app/_hub/kong-inc/opa/versions.yml
  app/_redirects
Labels: review:general, ci:check-skipped:generated-files

#4138 cert-manager kic guide fixes/enhancements
  src/kubernetes-ingress-controller/guides/cert-manager.md
Labels: review:tech

#4141 Fix migration code example
  .github/styles/kong/dictionary.txt
  app/gateway/2.8.x/plugin-development/custom-entities.md
Labels: review:general

#4139 Plugin Hub examples and common parameters
  app/_includes/hub-examples.html
  app/_layouts/extension.html
Labels: review:general, review:copyedit

#4140 Create feature-gates docs page
  app/_data/docs_nav_kic_2.5.x.yml
  src/kubernetes-ingress-controller/references/feature-gates.md
Labels: review:general

#4137 [DOCU-2402] Remove KM and decK, and HTTPie instructions from comprehensive docs.
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/get-started/comprehensive/dev-portal.md
  src/gateway/get-started/comprehensive/expose-services.md
  src/gateway/get-started/comprehensive/improve-performance.md
  src/gateway/get-started/comprehensive/load-balancing.md
  src/gateway/get-started/comprehensive/manage-teams.md
  src/gateway/get-started/comprehensive/prepare.md
  src/gateway/get-started/comprehensive/protect-services.md
  src/gateway/get-started/comprehensive/secure-services.md
Labels: review:copyedit

#4143 Further improve the plugin template
  app/_hub/_init/my-extension/_index.md
  app/_plugins/generators/plugin_single_source_generator.rb
Labels: review:copyedit

#4146 Update support policy to include KIC
  app/konnect-platform/support-policy.md
Labels: review:general

#4135 chore: release KongMesh 1.8.1 and 1.7.2
  .github/styles/kong/Terms.yml
  .github/styles/kong/dictionary.txt
  app/_data/kong_versions.yml
  app/mesh/changelog.md
Labels: review:general, review:copyedit

#4148 [chore] Update 3.0 Config.md file
  src/gateway/reference/configuration.md
Labels: review:copyedit

#4145 Add Kong Mesh tooltips
  .github/styles/kong/dictionary.txt
  app/_assets/stylesheets/features-table.less
  app/_plugins/tags/info_tooltip_tag.rb
  src/mesh/index.md
Labels: review:copyedit

#4153 Fix typo in Mesh comparison table
  src/mesh/index.md
Labels: review:general

#4131 [DOCU-2401] Add cluster_telemetry_server_name into 2.6-2.8 docs
  app/gateway/2.6.x/reference/configuration.md
  app/gateway/2.7.x/reference/configuration.md
  app/gateway/2.8.x/reference/configuration.md
Labels: review:tech, review:general, ci:prevent-merge:generated-files, ci:check-skipped:generated-files

#4154 Add OpenTelemetry plugin for gateway 3.0
  .github/styles/kong/dictionary.txt
  app/_assets/images/icons/hub/kong-inc_opentelemetry.png
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_hub/kong-inc/opentelemetry/_index.md
  app/_hub/kong-inc/opentelemetry/versions.yml
  app/_includes/hub-examples.html
Labels: review:copyedit

#4163 [fix] KIC table Update
  app/konnect-platform/support-policy.md
Labels: review:copyedit
