Repository Kong/docs.konghq.com, pull requests merged in 2022-12, with the labels that each got.

#4848 DOCU-2818 changelog 2.8.2.2
  app/gateway/changelog.md
Labels: review:general

#4844 [DOCU-2782] KM Consumer Groups
  app/_data/docs_nav_gateway_3.1.x.yml
  src/gateway/kong-enterprise/consumer-groups/index.md
  src/gateway/kong-manager/consumer-groups.md
Labels: review:general, review:copyedit

#4850 fix(plugin): Update SAML plugin documentation to reflect last-minute …
  app/_hub/kong-inc/saml/_index.md
Labels: review:copyedit

#4852 fix: Separate files for Admin API index in 3.0 and 3.1
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/admin-api/admin-api-3.0.x.md
Labels: review:general, ci:manual-approve:generated-files

#4826 Changelog 3.1
  app/_hub/kong-inc/proxy-cache-advanced/_index.md
  app/gateway/changelog.md
Labels: review:general, review:copyedit

#4853 FIPS support for ubuntu 22.04
  src/gateway/kong-enterprise/fips-support.md
Labels: review:general

#4846 [DOCU-2757] CP/DP forward proxy config
  app/_data/docs_nav_gateway_3.1.x.yml
  src/gateway/production/networking/cp-dp-proxy.md
Labels: do not merge, review:copyedit, review:sme

#4854 Gateway 2.8.2.2: Expand the changelog entry for the timer fix and bump 2.8.x version
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#4855 Update support policy for 3.1
  app/_includes/md/support-policy.md
Labels: review:general

#4861 [DOCU-2824] 3.1 fast-follow: Ubuntu 22.04 support
  app/_data/tables/os_support.yml
  app/gateway/changelog.md
Labels: review:general

#4863 [DOCU-2815] 3.1 Plugin updates
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/aws-lambda/_index.md
  app/_hub/kong-inc/basic-auth/_index.md
  app/_hub/kong-inc/hmac-auth/_index.md
  app/_hub/kong-inc/jwt/_index.md
  app/_hub/kong-inc/key-auth-enc/_index.md
  app/_hub/kong-inc/key-auth/_index.md
  app/_hub/kong-inc/ldap-auth-advanced/_index.md
  app/_hub/kong-inc/ldap-auth/_index.md
  app/_hub/kong-inc/mtls-auth/_index.md
  app/_hub/kong-inc/oauth2-introspection/_index.md
  app/_hub/kong-inc/oauth2/_index.md
  app/_hub/kong-inc/openid-connect/_index.md
  app/_hub/kong-inc/opentelemetry/_index.md
  app/_hub/kong-inc/rate-limiting/_index.md
  app/_hub/kong-inc/route-transformer-advanced/_index.md
  app/_hub/kong-inc/session/_index.md
  app/_hub/kong-inc/vault-auth/_index.md
  app/_hub/kong-inc/zipkin/_index.md
  app/gateway/changelog.md
Labels: review:general, review:copyedit

#4834 docs(kic): add compatibilities of router flavors of Kong
  app/_data/docs_nav_kic_2.7.x.yml
  src/kubernetes-ingress-controller/references/supported-router-flavors.md
Labels: Kubernetes Team, review:general

#4866 Updated references to 2.8.2
  src/gateway/upgrade.md
Labels: review:general, review:copyedit

#4847 Remove duplicate text in routing-traffic.md
  src/gateway/how-kong-works/routing-traffic.md
Labels: review:general

#4865 [DOCU-2825] 3.1 fast-follow: HashiCorp vault config parameters
  src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
Labels: review:general

#4864 Minor grammar fix
  src/kubernetes-ingress-controller/concepts/design.md
Labels: review:copyedit

#4871 Remove privileged worker from 3.1
  app/gateway/changelog.md
Labels: review:general

#4862 [DOCU-2827] 3.1 fast-follow: Amazon Linux 2022 support
  app/_data/tables/os_support.yml
  app/gateway/changelog.md
Labels: review:general

#4875 Update support policy w/ new 3.1 date
  app/_includes/md/support-policy.md
Labels: review:general

#4874 Update changelog w/ new 3.1 date
  app/gateway/changelog.md
Labels: review:general

#4873 DOCU-2830 Dynamic Log known issue
  app/gateway/changelog.md
Labels: review:general

#4876 [DOCU-2823] New 3.1.x Upgrade doc
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_redirects
  src/gateway/migrate-ce-to-ke.md
  src/gateway/upgrade-31x.md
Labels: review:copyedit

#4879 Revert "[DOCU-2823] New 3.1.x Upgrade doc"
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_redirects
  src/gateway/migrate-ce-to-ke.md
  src/gateway/upgrade-31x.md
Labels: review:general

#4880 DOCU-2823 3.1.x Upgrade doc
  app/_data/docs_nav_gateway_3.1.x.yml
  app/gateway/changelog.md
  src/gateway/migrate-ce-to-ke.md
  src/gateway/upgrade-31x.md
Labels: review:general

#4883 Update upgrade-31x.md
  src/gateway/upgrade-31x.md
Labels: review:general

#4869 doc(kic) change support of GWAPI into changelog format
  src/kubernetes-ingress-controller/references/gateway-api-support.md
Labels: review:copyedit

#4817 Add links to content templates
  README.md
  app/contributing/index.md
  app/contributing/style-guide.md
Labels: review:copyedit

#4885 [fix] Remove entry from changelog
  app/konnect/updates.md
Labels: review:general

#4799 doc(kic) deprecate KongIngress for 2.8
  src/kubernetes-ingress-controller/guides/routing-by-header.md
  src/kubernetes-ingress-controller/guides/using-kongingress-resource.md
  src/kubernetes-ingress-controller/references/annotations.md
  src/kubernetes-ingress-controller/references/custom-resources.md
Labels: review:general, review:copyedit

#4899 [fix] Change API url
  app/konnect/api/index.md
Labels: review:general

#4896 Update plugins-kubernetes.md
  src/gateway/plugin-development/pluginserver/plugins-kubernetes.md
Labels: review:general

#4912 Bump version
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general

#4889 docs(kic): add port matching unsupported note for udp routes
  src/kubernetes-ingress-controller/references/gateway-api-support.md
Labels: Kubernetes Team, review:general, area/gateway-api

#4913 docs(redis) redis.username cannot be 'default'
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
  app/_hub/kong-inc/rate-limiting/_index.md
Labels: review:general

#4890 docs link in gateway changelog
  app/gateway/changelog.md
Labels: review:general

#4872 Add "External plugin performance" back
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_redirects
  src/gateway/plugin-development/pluginserver/performance.md
Labels: review:general

#4915 StatsD Plugin: Converts ordered list to unordered list for non-instruction list
  app/_hub/kong-inc/statsd/_index.md
Labels: review:general

#4916 add changelog for 2.0.1 and fix support-policy with 2.0.x
  app/mesh/changelog.md
  src/mesh/support-policy.md
Labels: review:general

#4918 Content Templates added to contribution guide
  app/_data/docs_nav_contributing.yml
  app/contributing/contribution-templates.md
Labels: review:general

#4787 chore(mesh): add set_flag_values_prefix var
  jekyll.yml
Labels: review:sme

#4882 docs(zipkin): add `phase_duration_flavor` in 3.2
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/zipkin/_index.md
Labels: review:copyedit

#4893 feat(portal-dcr): how-to configure Curity DCR for konnect portal [TDX-2644]
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
Labels: review:general, pending:release

#4870 docs(rate-limiting-advanced): add suggestions on namespace field in DB-less mode
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
Labels: review:general

#4920 Update contribution-templates.md
  app/contributing/contribution-templates.md
Labels: review:general

#4922 Fix Gateway EE versions
  app/_data/kong_versions.yml
Labels: review:general

#4923 Fix quotes in cert-manager example for KIC
  app/_src/kubernetes-ingress-controller/guides/cert-manager.md
  app/kubernetes-ingress-controller/2.1.x/guides/cert-manager.md
  app/kubernetes-ingress-controller/2.2.x/guides/cert-manager.md
Labels: review:general

#4928 Make `vale`, actually `reviewdog` fail on error
  .github/workflows/linting.yml
Labels: review:tech

#4766 Expand Gateway API documentation coverage
  app/_assets/manifests/kubernetes-ingress-controller/examples/tcp-echo-service.yaml
  app/_data/docs_nav_kic_2.2.x.yml
  app/_data/docs_nav_kic_2.3.x.yml
  app/_data/docs_nav_kic_2.4.x.yml
  app/_data/docs_nav_kic_2.5.x.yml
  app/_data/docs_nav_kic_2.6.x.yml
  app/_data/docs_nav_kic_2.7.x.yml
  app/_includes/md/kic/add-certificate.md
  app/_includes/md/kic/class.md
  app/_includes/md/kic/http-test-service.md
  app/_includes/md/kic/installation.md
  app/_src/kubernetes-ingress-controller/concepts/deployment.md
  app/_src/kubernetes-ingress-controller/concepts/design.md
  app/_src/kubernetes-ingress-controller/concepts/gateway-api.md
  app/_src/kubernetes-ingress-controller/deployment/install-gateway-apis.md
  app/_src/kubernetes-ingress-controller/deployment/k4k8s-enterprise.md
  app/_src/kubernetes-ingress-controller/deployment/overview.md
  app/_src/kubernetes-ingress-controller/guides/configuring-custom-entities.md
  app/_src/kubernetes-ingress-controller/guides/getting-started-istio.md
  app/_src/kubernetes-ingress-controller/guides/getting-started.md
  app/_src/kubernetes-ingress-controller/guides/setting-up-custom-plugins.md
  app/_src/kubernetes-ingress-controller/guides/upgrade-kong-3x.md
  app/_src/kubernetes-ingress-controller/guides/upgrade.md
  app/_src/kubernetes-ingress-controller/guides/using-gateway-api.md
  app/_src/kubernetes-ingress-controller/guides/using-kongclusterplugin-resource.md
  app/_src/kubernetes-ingress-controller/guides/using-kongplugin-resource.md
  app/_src/kubernetes-ingress-controller/guides/using-multiple-backends.md
  app/_src/kubernetes-ingress-controller/guides/using-tcpingress.md
  app/_src/kubernetes-ingress-controller/guides/using-udpingress.md
  app/_src/kubernetes-ingress-controller/index.md
  app/_src/kubernetes-ingress-controller/references/annotations.md
  app/_src/kubernetes-ingress-controller/references/cli-arguments.md
  app/_src/kubernetes-ingress-controller/references/custom-resources.md
  app/_src/kubernetes-ingress-controller/references/gateway-api-support.md
  app/_src/kubernetes-ingress-controller/references/prometheus.md
  app/_src/kubernetes-ingress-controller/support-policy.md
  app/_src/kubernetes-ingress-controller/troubleshooting.md
  app/kubernetes-ingress-controller/2.2.x/deployment/install-gateway-apis.md
Labels: review:copyedit, pending:release

#4933 fix(nav) add file access permissions link to nav
  app/_data/docs_nav_gateway_3.1.x.yml
Labels: review:general

#4944 kic: update compatibility matrix for release 2.8
  app/_src/kubernetes-ingress-controller/references/version-compatibility.md
Labels: Kubernetes Team, review:general

#4949 kic: update support of router flavors
  app/_src/kubernetes-ingress-controller/references/supported-router-flavors.md
Labels: Kubernetes Team, review:general

#4943 kic: add docs for annotation
  app/_src/kubernetes-ingress-controller/references/annotations.md
Labels: Kubernetes Team, review:general

#4948 Remake: Konnect externalized API Spec PR
  app/_data/docs_nav_konnect.yml
Labels: review:general, ci:manual-approve:link-validation, ci:manual-approve:linting, ci:manual-approve:generated-files, pending:release

#4941 fix(key-auth): add missing docs
  app/_hub/kong-inc/key-auth/_index.md
Labels: review:copyedit

#4951 Minor grammar update
  app/_src/kubernetes-ingress-controller/concepts/deployment.md
Labels: review:copyedit

#4811 [DOCU-2516] New Konnect Overview page
  app/_assets/images/docs/konnect/dashboard/dashboard-annotated.png
  app/_assets/images/docs/konnect/dashboard/konnect-dashboard.png
  app/konnect/index.md
Labels: review:general, pending:release

#4956 add version support of KIC 2.6,2.7,2.8
  app/_includes/md/support-policy.md
  app/_src/kubernetes-ingress-controller/support-policy.md
Labels: Kubernetes Team, review:general

#4929 [Release] decK version 1.17
  app/_data/docs_nav_deck_1.17.x.yml
  app/_data/kong_versions.yml
Labels: review:general, pending:release

#4795 updated content and added release notes for MA-846
  app/konnect/analytics/generate-reports.md
  app/konnect/updates.md
Labels: review:copyedit, pending:release

#4961 feat(konnect-portal): adds guide for setting up rbac via API endpoints
  app/_data/docs_nav_konnect.yml
  app/konnect/api/portal-auth/portal-rbac-guide.md
Labels: review:copyedit

#4964 fix(nav): add debug routes to nav sidebar
  app/_data/docs_nav_gateway_3.1.x.yml
Labels: review:tech, review:general, review:autodoc, pr/please review

#4965 Force top CTA to always go to Sales demo
  app/_assets/javascripts/ab-test.js
Labels: review:general

#4952 feat(konnect-portal): how-to configure Auth0 DCR [TDX-2715]
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
  app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
Labels: review:general

#4845 [DOCU-2617] Cherry-pick of secrets management in konnect (#4828)
  app/_assets/images/docs/konnect/konnect-vaults.png
  app/_data/docs_nav_konnect.yml
  app/konnect/runtime-manager/manage-proxy-config.md
  app/konnect/runtime-manager/vaults/how-to.md
  app/konnect/runtime-manager/vaults/index.md
  app/konnect/updates.md
Labels: review:general, review:sme, pending:release

#4887 December Konnect Changelog
  app/konnect/updates.md
Labels: review:general

#4959 Cherry-pick - Curity DCR
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
Labels: review:general, pending:release

#4968 Add Curity DCR changelog
  app/konnect/updates.md
Labels: review:general

#4957 fix(admin-api): remove duplicate text
  app/_src/gateway/admin-api/admin-api-3.0.x.md
  app/_src/gateway/admin-api/index.md
  app/gateway/2.7.x/admin-api/index.md
  app/gateway/2.8.x/admin-api/index.md
  app/konnect/api/runtime-groups-config/index.md
Labels: ci:prevent-merge:generated-files

#4969 Remove note about decK + consumer groups
  app/_src/gateway/admin-api/consumer-groups/reference.md
Labels: review:general

#4970 Use site.data.kong_latest_gateway.ee-version in Konnect
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-docker.md
Labels: review:general

#4971 Redirect moved file for KIC Gateway API guide
  app/_redirects
Labels: review:general
