Repository Kong/docs.konghq.com, pull requests merged in 2022-02, with the labels that each got.

#3600 Cleaning up legacy docker compose references
  .github/workflows/build-test.yml
  Makefile
Labels: review:tech

#3605 Update gateway versions based on 2.7 and 2.6 patch releases
  app/_data/kong_versions.yml
Labels: review:general

#3603 Change upstream name in getting started guide
  app/gateway/2.6.x/get-started/comprehensive/load-balancing.md
  app/gateway/2.7.x/get-started/comprehensive/load-balancing.md
  app/getting-started-guide/2.1.x/load-balancing.md
  app/getting-started-guide/2.2.x/load-balancing.md
  app/getting-started-guide/2.3.x/load-balancing.md
  app/getting-started-guide/2.4.x/load-balancing.md
  app/getting-started-guide/2.5.x/load-balancing.md
  app/getting-started-guide/CE-2.0.x_KE-1.5.x/load-balancing.md
Labels: review:general

#3604 Improve header contrast
  app/_assets/stylesheets/base.less
  app/_assets/stylesheets/hub-landing-page.less
  app/_assets/stylesheets/page.less
  app/_assets/stylesheets/pages/docs.less
  app/_assets/stylesheets/pages/extension.less
  app/_assets/stylesheets/pages/landing-page.less
  app/gateway/2.7.x/install-and-run/index.md
Labels: review:tech, review:general

#3606 [DOCU-2166] Fix decK 1.9 and 1.10 installation instructions
  app/deck/1.10.x/installation.md
  app/deck/1.9.x/installation.md
Labels: review:general

#3614 Use quoted struct tags for golang configuration
  app/gateway/2.7.x/reference/external-plugins.md
Labels: review:tech, review:general

#3611 Adjust phrasing for Dev Portal OIDC changelog entry
  app/gateway/changelog.md
Labels: review:general

#3618 Dev Portal API doc disclaimer
  app/api/developer-portal.json
Labels: review:general

#3610 [DOCU-1698] External link icons + update font awesome
  app/_assets/stylesheets/pages/docs.less
  app/_includes/head.html
Labels: review:tech, review:general

#3608 [DOCU-2114] Fix Docker install instructions
  app/gateway/2.6.x/install-and-run/docker.md
  app/gateway/2.7.x/install-and-run/docker.md
Labels: review:tech, review:copyedit

#3609 Prometheus plugin minor fixes
  app/_hub/kong-inc/prometheus/index.md
Labels: review:general

#3617 Update konglabs links and variables
  app/_includes/nav-v2.html
  app/contributing/variables.md
  app/enterprise/1.3-x/kong-for-kubernetes/install.md
  app/enterprise/2.2.x/introduction/index.md
  app/enterprise/2.3.x/index.md
  app/enterprise/2.4.x/index.md
  app/enterprise/2.5.x/index.md
  app/gateway/2.6.x/index.md
  app/gateway/2.7.x/index.md
  jekyll-dev.yml
  jekyll.yml
Labels: review:general

#3620 Target deck tabs for db-less getting started guide links
  app/gateway/2.6.x/install-and-run/docker.md
  app/gateway/2.7.x/install-and-run/docker.md
Labels: review:general

#3607 Gulpfile updates
  gulpfile.js
Labels: review:tech

#3615 [DOCU-2167] add Appearance page and custom domain updates
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/dev-portal/access-and-approval/dev-reg.md
  app/konnect/dev-portal/customization/appearance.md
  app/konnect/dev-portal/customization/customization-overview.md
  app/konnect/servicehub/dev-portal/publish.md
Labels: review:copyedit

#3612 doc(kic) add KIC Grafana dashboard
  app/kubernetes-ingress-controller/2.0.x/guides/prometheus-grafana.md
  app/kubernetes-ingress-controller/2.1.x/guides/prometheus-grafana.md
Labels: review:general

#3625 Re-add missing alpha and beta banners
  app/_assets/stylesheets/badges.less
  app/_layouts/docs-v2.html
  app/_layouts/extension.html
  app/contributing/markdown-rules.md
Labels: review:general

#3623 Release: Gateway 2.7.1.1
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general

#3626 Update OSS gateway version to 2.7.1
  app/_data/kong_versions.yml
Labels: review:general

#3629 [DOCU-449] Add missing kong user info
  app/enterprise/2.3.x/deployment/kong-user.md
  app/enterprise/2.4.x/deployment/kong-user.md
  app/enterprise/2.5.x/deployment/kong-user.md
  app/gateway-oss/2.3.x/kong-user.md
  app/gateway-oss/2.4.x/kong-user.md
  app/gateway-oss/2.5.x/kong-user.md
  app/gateway/2.6.x/plan-and-deploy/kong-user.md
  app/gateway/2.7.x/plan-and-deploy/kong-user.md
Labels: review:general

#3624 Improve "on this page" & github links sidebar
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/header.less
  app/_assets/stylesheets/page.less
  app/_assets/stylesheets/pages/docs.less
  app/_includes/toc.html
  app/_layouts/docs-v2.html
  app/_layouts/extension.html
  app/contributing/markdown-rules.md
  app/deck/1.10.x/compatibility-promise.md
  app/deck/1.10.x/guides/backup-restore.md
  app/deck/1.10.x/guides/best-practices.md
  app/deck/1.10.x/guides/ci-driven-configuration.md
  app/deck/1.10.x/guides/deduplicate-plugin-configuration.md
  app/deck/1.10.x/guides/environment-variables.md
  app/deck/1.10.x/guides/multi-file-state.md
  app/konnect-platform/compatibility/index.md
  app/konnect-platform/guides.md
  app/konnect/deployment/license-management.md
  app/konnect/dev-portal/index.md
  app/konnect/shared-config/index.md
  app/mesh/1.5.x/features/fips-support.md
Labels: review:tech, review:general

#3632 Update oidc.md
  app/gateway/2.6.x/configure/auth/kong-manager/oidc.md
Labels: review:general

#3640 [DOCU-1643] Update links in Canary Release plugin
  app/_hub/kong-inc/canary/0.3.x.md
  app/_hub/kong-inc/canary/0.4.x.md
  app/_hub/kong-inc/canary/index.md
Labels: review:general

#3641 [DOCU-1612] Remove db version content from Property Reference datastore section
  app/gateway/2.7.x/reference/configuration.md
Labels: review:general

#3631 Update Konnect docs with 2.7 gateway support
  app/konnect/deployment/index.md
  app/konnect/runtime-manager/gateway-runtime-docker.md
  app/konnect/runtime-manager/gateway-runtime-kubernetes.md
  app/konnect/updates.md
Labels: review:general

#3630 [DOCU-1651] Fix hybrid mode docker instructions
  app/enterprise/2.1.x/deployment/hybrid-mode-setup.md
  app/enterprise/2.2.x/deployment/hybrid-mode-setup.md
  app/enterprise/2.3.x/deployment/hybrid-mode-setup.md
  app/enterprise/2.4.x/deployment/hybrid-mode-setup.md
  app/enterprise/2.5.x/deployment/hybrid-mode-setup.md
  app/gateway/2.6.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
  app/gateway/2.7.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
Labels: review:general, ci:manual-approve:link-validation

#3633 [DOCU-360] Note for db_export support
  app/gateway/2.6.x/reference/cli.md
  app/gateway/2.7.x/reference/cli.md
Labels: review:general

#3634 [DOCU-1472] Fix Kong-Debug header name
  app/enterprise/0.35-x/proxy.md
  app/enterprise/0.36-x/proxy.md
  app/gateway-oss/1.2.x/proxy.md
  app/gateway-oss/1.3.x/proxy.md
  app/gateway-oss/1.4.x/proxy.md
  app/gateway-oss/1.5.x/proxy.md
  app/gateway-oss/2.0.x/proxy.md
  app/gateway-oss/2.1.x/proxy.md
  app/gateway-oss/2.2.x/proxy.md
  app/gateway-oss/2.3.x/proxy.md
  app/gateway-oss/2.4.x/proxy.md
  app/gateway-oss/2.5.x/proxy.md
Labels: review:general

#3643 [DOCU-2128] remove version-specific text from on-prem Dev Portal docs
  app/gateway/2.7.x/developer-portal/administration/application-registration/auth-provider-strategy.md
  app/gateway/2.7.x/developer-portal/administration/application-registration/enable-application-registration.md
  app/gateway/2.7.x/developer-portal/administration/application-registration/enable-key-auth-plugin.md
  app/gateway/2.7.x/developer-portal/configuration/smtp.md
  app/gateway/2.7.x/developer-portal/theme-customization/adding-javascript-assets.md
  app/gateway/2.7.x/developer-portal/theme-customization/easy-theme-editing.md
  app/gateway/2.7.x/developer-portal/theme-customization/emails.md
  app/gateway/2.7.x/developer-portal/theme-customization/markdown-extended.md
  app/gateway/2.7.x/developer-portal/theme-customization/single-page-app.md
  app/gateway/2.7.x/developer-portal/using-the-editor.md
Labels: review:general

#3650 [DOCU-2162] Update Dev Portal Azure requests
  app/gateway/2.7.x/developer-portal/administration/application-registration/azure-oidc-config.md
Labels: review:general

#3646 [DOCU-1929] Supported response codes for Mocking plugin
  app/_hub/kong-inc/mocking/0.1.x.md
  app/_hub/kong-inc/mocking/index.md
Labels: review:general

#3639 [DOCU-2127] Remove and replace outdated on-prem Dev Portal screenshots
  app/_assets/images/docs/dev-portal/appearance-dev-portal.png
  app/_assets/images/docs/dev-portal/developer-portal-homepage.png
  app/_assets/images/docs/dev-portal/editor-dev-portal.png
  app/_assets/images/docs/dev-portal/editor-mode-numbered.png
  app/_assets/images/docs/dev-portal/generate-cred-dev-portal.png
  app/gateway/2.7.x/developer-portal/administration/application-registration/azure-oidc-config.md
  app/gateway/2.7.x/developer-portal/administration/application-registration/enable-key-auth-plugin.md
  app/gateway/2.7.x/developer-portal/administration/application-registration/okta-config.md
  app/gateway/2.7.x/developer-portal/administration/managing-developers.md
  app/gateway/2.7.x/developer-portal/configuration/authentication/basic-auth.md
  app/gateway/2.7.x/developer-portal/index.md
  app/gateway/2.7.x/developer-portal/theme-customization/easy-theme-editing.md
  app/gateway/2.7.x/developer-portal/theme-customization/emails.md
  app/gateway/2.7.x/developer-portal/using-the-editor.md
Labels: review:general

#3647 [DOCU-2174] Add note about reg flow to OIDC for Dev Portal
  app/gateway/2.7.x/developer-portal/configuration/authentication/oidc.md
Labels: review:general

#3654 Breaking change note for Kong Manager changelog entry in 2.7.0.0
  app/gateway/changelog.md
Labels: review:general

#3652 [DOCU-1583] Fix Mesh license variable
  app/_includes/md/mesh/install-universal-run.md
Labels: review:general

#3651 [DOCU-486] Fix typos and styling issues
  app/kubernetes-ingress-controller/1.0.x/deployment/aks.md
  app/kubernetes-ingress-controller/1.1.x/deployment/aks.md
  app/kubernetes-ingress-controller/1.2.x/deployment/aks.md
  app/kubernetes-ingress-controller/1.3.x/deployment/aks.md
  app/kubernetes-ingress-controller/2.0.x/deployment/aks.md
  app/kubernetes-ingress-controller/2.1.x/deployment/aks.md
Labels: review:general

#3636 [DOCU-2177] Deck support for plugin defaults
  app/deck/1.11.x/guides/defaults.md
Labels: review:copyedit, ci:manual-approve:link-validation

#3653 [DOCU-2185] Update Admin API note
  app/gateway-oss/2.4.x/admin-api.md
  app/gateway-oss/2.5.x/admin-api.md
  app/gateway/2.6.x/admin-api/index.md
  app/gateway/2.7.x/admin-api/index.md
Labels: review:general, ci:manual-approve:link-validation

#3644 Release: Gateway 2.6.0.4
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general

#3660 [DOCU-2186] Add EE badge to cluster_mtls pki_check_cn
  app/gateway/2.7.x/reference/configuration.md
Labels: review:general

#3664 Update prometheus-grafana.md
  app/kubernetes-ingress-controller/2.1.x/guides/prometheus-grafana.md
Labels: review:general

#3665 Chore: Disable promo banner
  app/_assets/stylesheets/header.less
  app/_includes/nav-v2.html
  gulpfile.js
Labels: review:general

#3663 [DOCU-2140] Admin API: Remove wording about cannot delete/modify
  app/gateway/2.7.x/admin-api/index.md
Labels: review:general, ci:manual-approve:link-validation

#3662 [DOCU-1813] 2.1.x migrate Dev Portal URL updates
  app/_includes/md/2.1.x/migrations/migrate-dev-portal.md
Labels: review:general

#3667 [DOCU-1068] Hybrid Mode: rm Vitals from telemetry mentions
  app/enterprise/2.1.x/deployment/hybrid-mode-setup.md
  app/enterprise/2.2.x/deployment/hybrid-mode-setup.md
  app/enterprise/2.3.x/deployment/hybrid-mode-setup.md
  app/enterprise/2.4.x/deployment/hybrid-mode-setup.md
  app/enterprise/2.5.x/deployment/hybrid-mode-setup.md
  app/gateway/2.6.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
  app/gateway/2.7.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
Labels: review:general

#3668 [DOCU-2179] Add note on how to deploy multiple workspaces
  app/deck/1.11.x/guides/kong-enterprise.md
Labels: review:general

#3670 decK CLI ref cleanup for 1.11
  app/deck/1.11.x/reference/deck.md
  app/deck/1.11.x/reference/deck_completion.md
  app/deck/1.11.x/reference/deck_convert.md
  app/deck/1.11.x/reference/deck_diff.md
  app/deck/1.11.x/reference/deck_dump.md
  app/deck/1.11.x/reference/deck_konnect.md
  app/deck/1.11.x/reference/deck_konnect_diff.md
  app/deck/1.11.x/reference/deck_konnect_dump.md
  app/deck/1.11.x/reference/deck_konnect_ping.md
  app/deck/1.11.x/reference/deck_konnect_sync.md
  app/deck/1.11.x/reference/deck_ping.md
  app/deck/1.11.x/reference/deck_reset.md
  app/deck/1.11.x/reference/deck_sync.md
  app/deck/1.11.x/reference/deck_validate.md
  app/deck/1.11.x/reference/deck_version.md
Labels: review:general

#3661 Update Vault documentation
  app/mesh/1.5.x/features/vault.md
Labels: review:tech, review:general

#3656 [DOCU-876] Correlation ID Plugin: edit Nginx param
  app/_hub/kong-inc/correlation-id/index.md
Labels: review:tech, review:general

#3682 [DOCU-493] response trans adv plugin: missing params
  app/_hub/kong-inc/response-transformer-advanced/index.md
Labels: review:tech, review:general

#3677 [DOCU-885] Add missing status_listen
  app/enterprise/1.5.x/property-reference.md
  app/enterprise/2.1.x/property-reference.md
Labels: review:general, ci:manual-approve:link-validation

#3681 Related to DOCU-2140 Admin API rm cannot del/mod
  app/enterprise/2.2.x/admin-api/index.md
  app/enterprise/2.3.x/admin-api/index.md
  app/enterprise/2.4.x/admin-api/index.md
  app/enterprise/2.5.x/admin-api/index.md
  app/gateway-oss/2.2.x/admin-api.md
  app/gateway-oss/2.3.x/admin-api.md
  app/gateway-oss/2.4.x/admin-api.md
  app/gateway-oss/2.5.x/admin-api.md
  app/gateway/2.6.x/admin-api/index.md
Labels: review:general

#3674 [DOCU-1647] Add desc to Serverless Functions plugin
  app/_hub/kong-inc/serverless-functions/index.md
Labels: review:general

#3675 [DOCU-385] Dev Portal styling doesn't carry over
  app/gateway/2.7.x/developer-portal/theme-customization/easy-theme-editing.md
Labels: review:general

#3676 [DOCU-1848] Clarify wording in Kong Manager
  app/enterprise/2.1.x/kong-manager/administration/workspaces/add-workspace.md
  app/enterprise/2.2.x/kong-manager/administration/workspaces/add-workspace.md
  app/enterprise/2.3.x/kong-manager/administration/workspaces/add-workspace.md
  app/enterprise/2.4.x/kong-manager/administration/workspaces/add-workspace.md
  app/enterprise/2.5.x/kong-manager/administration/workspaces/add-workspace.md
  app/gateway/2.6.x/configure/auth/kong-manager/workspaces.md
  app/gateway/2.7.x/configure/auth/kong-manager/workspaces.md
Labels: review:general

#3686 remove unnecessary / in the URL
  app/gateway/2.6.x/get-started/comprehensive/secure-services.md
  app/gateway/2.7.x/get-started/comprehensive/secure-services.md
Labels: review:copyedit, ci:manual-approve:link-validation

#3613 add zone token access to Kong Mesh RBAC
  app/mesh/1.6.x/features/rbac.md
Labels: review:general

#3703 docs(mesh): fix windows installation docs
  app/mesh/1.5.x/installation/windows.md
  app/mesh/1.6.x/installation/windows.md
Labels: review:general, ci:manual-approve:link-validation

#3680 Kong Mesh license
  app/_data/docs_nav_mesh_1.6.x.yml
  app/mesh/1.6.x/plan-and-deploy/license.md
Labels: review:general, review:copyedit

#3683 Changelogs and version fixes for 2.8 plugins
  app/_data/extensions/kong-inc/graphql-rate-limiting-advanced/versions.yml
  app/_data/extensions/kong-inc/proxy-cache-advanced/versions.yml
  app/_data/extensions/kong-inc/response-ratelimiting/versions.yml
  app/_hub/kong-inc/graphql-rate-limiting-advanced/0.1.x.md
  app/_hub/kong-inc/graphql-rate-limiting-advanced/index.md
  app/_hub/kong-inc/openid-connect/index.md
  app/_hub/kong-inc/proxy-cache-advanced/0.4.x.md
  app/_hub/kong-inc/proxy-cache-advanced/index.md
  app/_hub/kong-inc/rate-limiting-advanced/index.md
  app/_hub/kong-inc/rate-limiting/index.md
  app/_hub/kong-inc/response-ratelimiting/1.0.x.md
  app/_hub/kong-inc/response-ratelimiting/index.md
Labels: review:general

#3702 Update index.md
  app/_hub/kong-inc/correlation-id/index.md
Labels: bug, review:tech

#3687 doc(external-plugins) use pip3 and mention API reference
  app/enterprise/2.4.x/external-plugins.md
  app/enterprise/2.5.x/external-plugins.md
  app/gateway-oss/2.4.x/external-plugins.md
  app/gateway-oss/2.5.x/external-plugins.md
  app/gateway/2.6.x/reference/external-plugins.md
  app/gateway/2.7.x/reference/external-plugins.md
Labels: review:tech, review:general

#3711 add changelog for KongMesh 1.6
  app/mesh/changelog.md
Labels: review:general, review:copyedit

#3698 Update Go pdk docs
  app/gateway/2.8.x/reference/external-plugins.md
Labels: review:tech, review:general

#3622 Add KIC Gateway API Guide
  app/_data/docs_nav_kic_2.2.x.yml
  app/kubernetes-ingress-controller/2.2.x/guides/using-gateway-api.md
Labels: blocked (Kong PR), review:tech, review:copyedit

#3715 (chore) Copy changes from 2.7.x to 2.8.x
  app/gateway/2.8.x/configure/auth/index.md
  app/gateway/2.8.x/configure/auth/kong-manager/workspaces.md
  app/gateway/2.8.x/developer-portal/administration/application-registration/auth-provider-strategy.md
  app/gateway/2.8.x/developer-portal/administration/application-registration/azure-oidc-config.md
  app/gateway/2.8.x/developer-portal/administration/application-registration/enable-application-registration.md
  app/gateway/2.8.x/developer-portal/administration/application-registration/enable-key-auth-plugin.md
  app/gateway/2.8.x/developer-portal/administration/application-registration/okta-config.md
  app/gateway/2.8.x/developer-portal/configuration/authentication/oidc.md
  app/gateway/2.8.x/developer-portal/configuration/smtp.md
  app/gateway/2.8.x/developer-portal/index.md
  app/gateway/2.8.x/developer-portal/theme-customization/adding-javascript-assets.md
  app/gateway/2.8.x/developer-portal/theme-customization/easy-theme-editing.md
  app/gateway/2.8.x/developer-portal/theme-customization/emails.md
  app/gateway/2.8.x/developer-portal/theme-customization/markdown-extended.md
  app/gateway/2.8.x/developer-portal/theme-customization/single-page-app.md
  app/gateway/2.8.x/developer-portal/using-the-editor.md
  app/gateway/2.8.x/get-started/comprehensive/secure-services.md
  app/gateway/2.8.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
  app/gateway/2.8.x/reference/configuration.md
  app/gateway/2.8.x/reference/external-plugins.md
Labels: review:general

#3716 (chore) Update dependencies for 2.8
  app/_data/kong_versions.yml
Labels: review:general

#3712 document new version of the Prometheus plugin in 2.8
  app/_hub/kong-inc/prometheus/index.md
Labels: review:tech, review:copyedit

#3721 Bump prometheus plugin nav version
  app/_data/extensions/kong-inc/prometheus/versions.yml
Labels: review:general
