Repository Kong/docs.konghq.com, pull requests merged in 2022-08, with the labels that each got.

#4172 Fix response typo in request-transformer page
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/request-transformer-advanced/_index.md
  app/_hub/kong-inc/request-transformer/_index.md
Labels: review:copyedit

#4175 [fix]remove login_email from okta idp custom claims
  app/konnect/org-management/okta-idp.md
Labels: review:tech

#4174 kong.cache function parameters precision
  .github/styles/kong/dictionary.txt
  app/gateway/2.8.x/plugin-development/entities-cache.md
Labels: review:tech

#4179 fix(portal) remove examples of portal_gui_host with a path
  app/enterprise/2.1.x/property-reference.md
  app/enterprise/2.2.x/property-reference.md
  app/enterprise/2.3.x/property-reference.md
  app/enterprise/2.4.x/property-reference.md
  app/enterprise/2.5.x/property-reference.md
  app/gateway/2.6.x/reference/configuration.md
  app/gateway/2.7.x/reference/configuration.md
  app/gateway/2.8.x/reference/configuration.md
Labels: review:general, ci:check-skipped:generated-files

#4155 How-To Kong
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/understanding-kong/how-to/kong-gateway.md
  src/gateway/understanding-kong/how-to/request-transformations.md
Labels: do not merge, review:general

#4181 Update allowing-multiple-authentication-methods.md
  app/gateway/2.7.x/configure/auth/allowing-multiple-authentication-methods.md
Labels: review:copyedit

#4180 Update allowing-multiple-authentication-methods.md
  app/gateway/2.7.x/configure/auth/allowing-multiple-authentication-methods.md
  app/gateway/2.8.x/configure/auth/allowing-multiple-authentication-methods.md
Labels: review:copyedit

#4182 Update plugin serverless-functions docs.
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/serverless-functions/_index.md
Labels: review:copyedit, ci:check-skipped:generated-files

#4186 [DOCU-2418] Kong.conf config
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/kong-production/environment-variables.md
  src/gateway/kong-production/kong-conf.md
Labels: review:copyedit

#4187 [DOCU-2419] Open Resty
  src/gateway/kong-production/kong-openresty.md
  src/gateway/reference/configuration.md
Labels: review:general, ci:check-skipped:generated-files

#4149 [chore] Gateway 2.8.1.3 support for Lambda plugin
  app/_hub/kong-inc/aws-lambda/_index.md
Labels: review:general

#4189 Fix install icons
  app/_assets/images/icons/documentation/amazon-linux.png
  app/_assets/images/icons/documentation/centos.gif
  app/_assets/images/icons/documentation/docker.png
  app/_assets/images/icons/documentation/rhel.jpg
  app/_assets/images/icons/documentation/ubuntu.png
  app/gateway/2.6.x/install-and-run/index.md
  app/gateway/2.7.x/install-and-run/index.md
  app/gateway/2.8.x/install-and-run/index.md
Labels: review:general

#4190 Fix db-less rendering in plugin hub
  app/_layouts/extension.html
Labels: review:general

#4191 Add link to arm Mesh downloads
  src/mesh/installation/macos.md
Labels: review:general

#4192 Show k8s examples before Universal on Mesh RBAC
  src/mesh/features/rbac.md
Labels: review:general

#4199 [fix] Port changes to serverless functions doc to Gateway 3.0
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/serverless-functions/_index.md
Labels: review:tech, ci:check-skipped:generated-files

#4194 Add status enum docs to Admin endpoint
  app/gateway/2.8.x/admin-api/admins/reference.md
Labels: review:general

#4198 3.0 Add status enum docs to Admin endpoint
  app/gateway/2.8.x/admin-api/admins/reference.md
  src/gateway/admin-api/admins/reference.md
Labels: review:general

#4197 Workflow cleanup
  .github/workflows/linting.yml
  .github/workflows/repo-sync.yml
  .github/workflows/vale_linter.yml
  .vale.ini
  docs/vale.md
Labels: review:tech

#4158 docs(perf) update perf test framework API
  .github/styles/kong/dictionary.txt
  src/gateway/reference/performance-testing-framework.md
Labels: review:copyedit

#4196 Remove grpc from mocking plugin protocols
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/mocking/0.1.x.md
  app/_hub/kong-inc/mocking/_index.md
Labels: review:general

#4195 Add params.global entry to plugins
  app/_hub/kong-inc/application-registration/_index.md
  app/_includes/hub-examples.html
  app/_layouts/extension.html
Labels: review:tech, review:general

#4193 Add minimum version for custom_fields_by_lua
  app/_hub/kong-inc/file-log/_index.md
Labels: review:general

#4200 [docu-2420] Website and API in the same Kong Gateway instance
  .github/styles/kong/dictionary.txt
  src/gateway/kong-production/environment-variables.md
  src/gateway/kong-production/kong-conf.md
  src/gateway/kong-production/kong-openresty.md
  src/gateway/kong-production/website-api-serving.md
Labels: review:copyedit

#4202 [Docu-2446] Nginx directives reference
  src/gateway/reference/nginx-directives.md
Labels: review:general

#4203 [DOCU-2424] Kong in Production: Blue Green deployments
  .github/styles/kong/dictionary.txt
  src/gateway/kong-production/blue-green.md
  src/gateway/understanding-kong/loadbalancing.md
Labels: review:copyedit

#4185 fix(prometheus-switch-3.0.0): Adding 3.0.0 prometheus changelog docs
  app/_hub/kong-inc/prometheus/_index.md
Labels: review:copyedit

#4183 docs(prometheus) add new options for 3.0
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/prometheus/0.1-x.md
  app/_hub/kong-inc/prometheus/1.6.0.md
  app/_hub/kong-inc/prometheus/_0.8.x.md
  app/_hub/kong-inc/prometheus/_index.md
  app/_hub/kong-inc/prometheus/versions.yml
Labels: pr/please review, review:copyedit

#4205 release Kong Mesh 1.8.2
  app/_data/kong_versions.yml
  app/mesh/changelog.md
Labels: review:general

#3708 [FTI-2203] tls-metdata-headers plugin docs
  app/_assets/images/icons/hub/kong-inc_tls-metadata-headers.png
  app/_data/tables/plugin_index.yml
  app/_hub/kong-inc/tls-metadata-headers/_index.md
  app/_hub/kong-inc/tls-metadata-headers/versions.yml
Labels: do not merge

#3710 [FTI-2203] tls-handshake-modifier plugin docs
  app/_assets/images/icons/hub/kong-inc_tls-handshake-modifier.png
  app/_data/tables/plugin_index.yml
  app/_hub/kong-inc/tls-handshake-modifier/_index.md
  app/_hub/kong-inc/tls-handshake-modifier/versions.yml
Labels: do not merge, review:general, review:copyedit

#4014 Add tracing sections for gateway 3.0
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/kong-production/tracing/api.md
  src/gateway/kong-production/tracing/index.md
  src/gateway/kong-production/tracing/write-custom-trace-exporter.md
Labels: pr/please review, review:copyedit

#4208 [docu-2441-2443] Write plugins in other languages
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/plugin-development/other/go.md
  src/gateway/plugin-development/other/javascript.md
  src/gateway/plugin-development/other/plugins-kubernetes.md
  src/gateway/plugin-development/other/python.md
Labels: review:copyedit

#4201 [DOCU-2408] Understanding Kong: Services
  src/gateway/understanding-kong/key-concepts/services.md
Labels: review:copyedit

#4211 [FT-2788]fix opa documents undefined return
  app/_hub/kong-inc/opa/_index.md
Labels: review:tech, review:general

#4212 [chore] OPA documents undefined return 3.0
  app/_hub/kong-inc/opa/_index.md
Labels: review:copyedit

#4213 Update smoke tests for new IA
  app/moved_urls.yml
  tests/install.test.js
  tests/seo.test.js
  tests/sidebar.test.js
Labels: review:general

#4178 [DOCU-2450] Azure Dev Portal SSO
  app/_assets/images/docs/konnect/azure/group-claim.png
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/access-and-approval/azure.md
Labels: review:copyedit

#4210 [DOCU-2413] and [DOCU-2447] Performance Testing Framework IA rework
  src/gateway/reference/performance-testing-framework.md
  src/gateway/understanding-kong/kong-performance-testing.md
Labels: review:copyedit

#4209 [DOCU 2411] and [DOCU-2444] Plugin Overviews
  app/_hub/plugins/overview/_index.md
  app/_includes/md/about-plugins.md
  src/gateway/kong-plugins/index.md
  src/gateway/understanding-kong/key-concepts/plugins.md
Labels: review:copyedit

#4206 [DOCU-2425] Kong in Production: Canary Deployments
  src/gateway/kong-production/canary.md
  src/gateway/understanding-kong/loadbalancing.md
Labels: review:copyedit

#4222 [fix] Vaults bundled
  app/gateway/2.8.x/reference/configuration.md
Labels: review:copyedit, ci:prevent-merge:generated-files, ci:check-skipped:generated-files

#4220 fix(changelog) add a missing bug fix to 2.8.1.1/2 changelog
  app/gateway/changelog.md
Labels: review:general

#4225 Fix statsd plugin doc
  app/_hub/kong-inc/statsd/0.1-x.md
  app/_hub/kong-inc/statsd/_index.md
  app/_hub/kong-inc/statsd/versions.yml
Labels: review:general

#4226 Vaults GA changes
  app/gateway/2.8.x/plan-and-deploy/security/secrets-management/getting-started.md
  app/gateway/2.8.x/plan-and-deploy/security/secrets-management/index.md
Labels: review:general

#4223 Correct typo
  app/_includes/md/enterprise/event-hooks-intro.md
Labels: review:tech

#4224 fix(add-datadog-prometheus): docs
  src/gateway/kong-production/monitoring/datadog.md
Labels: review:copyedit

#4227 Port vaults doc updates into 3.0
  app/gateway/2.8.x/plan-and-deploy/security/secrets-management/getting-started.md
  app/gateway/2.8.x/plan-and-deploy/security/secrets-management/index.md
  src/gateway/kong-enterprise/secrets-management/getting-started.md
  src/gateway/kong-enterprise/secrets-management/index.md
Labels: review:general, ci:manual-approve:link-validation

#4228 [MA-365] Collect Prometheus metrics with Datadog
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/kong-production/monitoring/datadog.md
Labels: review:copyedit

#4232 Fix lb upstream and JSON objects
  .github/styles/kong/dictionary.txt
  app/gateway/2.8.x/reference/loadbalancing.md
Labels: review:general

#4217 [DOCU-2415] Configure Routes and Services
  src/gateway/get-started/configure-services-and-routes.md
Labels: review:copyedit

#4236 [update] Update decK version
  app/_data/docs_nav_deck_1.13.x.yml
  app/_data/kong_versions.yml
Labels: review:autodoc

#4234 Update CODEOWNERS
  .github/CODEOWNERS
Labels: review:tech

#4243 Update ingress-versions.md
  src/kubernetes-ingress-controller/concepts/ingress-versions.md
Labels: review:copyedit

#4239 Update deployment.md
  src/kubernetes-ingress-controller/concepts/deployment.md
Labels: review:copyedit

#4244 Update admission-webhook.md
  src/kubernetes-ingress-controller/deployment/admission-webhook.md
Labels: review:copyedit

#4249 Add Redis disconnect behavior to Rate Limiting Advanced plugin
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
Labels: review:copyedit

#4247 docs: fix issues with plugin-ordering examples
  src/gateway/kong-enterprise/plugin-ordering/get-started.md
Labels: review:general

#4233 DEVREL-372: Adds a how-to guide for PG Secrets via AWS Secrets Manager
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/understanding-kong/how-to/aws-secrets-manager.md
Labels: review:general

#4252 Automatic Jekyll rebuild when changing src
  gulpfile.js
Labels: review:tech

#4253 Update using-kongclusterplugin-resource.md
  src/kubernetes-ingress-controller/guides/using-kongclusterplugin-resource.md
Labels: review:general, review:copyedit

#4251 [docu-2457] Router Reference, Router Route creation
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/get-started/configure-services-and-routes.md
  src/gateway/reference/router-operators.md
  src/gateway/understanding-kong/how-to/router-atc.md
Labels: review:copyedit

#4207 [DOCU-2445] Reference: Configuration Reference
  autodoc-conf-ee/data.lua
  src/gateway/reference/configuration.md
Labels: review:copyedit, ci:prevent-merge:generated-files, ci:check-skipped:generated-files

#4216 [DOCU-2409] Understanding Kong: Routes
  src/gateway/understanding-kong/key-concepts/routes.md
Labels: review:copyedit

#4218 [DOCU-2410] Understanding Kong: Upstreams
  src/gateway/understanding-kong/key-concepts/upstreams.md
Labels: review:copyedit

#4259 docs(router/atc) update to reflect the actual implementation in Kong 3.0
  src/gateway/reference/router-operators.md
  src/gateway/understanding-kong/how-to/router-atc.md
Labels: review:general

#4077 Kong Manger 3.0 documentation
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_includes/md/enterprise/turn-on-rbac.md
  app/_includes/md/gateway/setup.md
  src/gateway/kong-manager/auth/basic.md
  src/gateway/kong-manager/auth/ldap/configure.md
  src/gateway/kong-manager/auth/ldap/service-directory-mapping.md
  src/gateway/kong-manager/auth/oidc/configure.md
  src/gateway/kong-manager/auth/oidc/mapping.md
  src/gateway/kong-manager/auth/overview.md
  src/gateway/kong-manager/auth/rbac/add-admin.md
  src/gateway/kong-manager/auth/rbac/add-role.md
  src/gateway/kong-manager/auth/rbac/add-user.md
  src/gateway/kong-manager/auth/rbac/enable.md
  src/gateway/kong-manager/auth/rbac/index.md
  src/gateway/kong-manager/auth/reset-password.md
  src/gateway/kong-manager/auth/sessions.md
  src/gateway/kong-manager/auth/super-admin.md
  src/gateway/kong-manager/auth/workspaces-and-teams.md
  src/gateway/kong-manager/authentication/basic.md
  src/gateway/kong-manager/authentication/index.md
  src/gateway/kong-manager/authentication/rbac/add-admin.md
  src/gateway/kong-manager/authentication/rbac/add-role.md
  src/gateway/kong-manager/authentication/rbac/add-user.md
  src/gateway/kong-manager/authentication/rbac/index.md
  src/gateway/kong-manager/authentication/reset-password.md
  src/gateway/kong-manager/authentication/service-directory-mapping.md
  src/gateway/kong-manager/authentication/super-admin.md
  src/gateway/kong-manager/authentication/workspaces.md
  src/gateway/kong-manager/configuring-to-send-email.md
  src/gateway/kong-manager/enable-km.md
  src/gateway/kong-manager/enable.md
  src/gateway/kong-manager/get-started/authentication.md
  src/gateway/kong-manager/get-started/consumers.md
  src/gateway/kong-manager/get-started/load-balancing.md
  src/gateway/kong-manager/get-started/proxy-caching.md
  src/gateway/kong-manager/get-started/rate-limiting.md
  src/gateway/kong-manager/get-started/services-and-routes.md
  src/gateway/kong-manager/get-started/services-routes.md
  src/gateway/kong-manager/index.md
  src/gateway/kong-manager/networking.md
  src/gateway/kong-manager/overview.md
  src/gateway/kong-manager/workspaces.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#4231 doc: add gateway API features in KIC 2.4
  app/_data/docs_nav_kic_2.4.x.yml
  app/_data/docs_nav_kic_2.5.x.yml
  src/kubernetes-ingress-controller/guides/using-gateway-api.md
  src/kubernetes-ingress-controller/references/gateway-api-support.md
Labels: review:tech, review:general, review:copyedit

#4214 ldap-auth-advanced changes for 3.0
  app/_hub/kong-inc/ldap-auth-advanced/0.33-x.md
  app/_hub/kong-inc/ldap-auth-advanced/0.34-x.md
  app/_hub/kong-inc/ldap-auth-advanced/0.35-x.md
  app/_hub/kong-inc/ldap-auth-advanced/0.36-x.md
  app/_hub/kong-inc/ldap-auth-advanced/1.3.x.md
  app/_hub/kong-inc/ldap-auth-advanced/2.2.x.md
  app/_hub/kong-inc/ldap-auth-advanced/2.3.x.md
  app/_hub/kong-inc/ldap-auth-advanced/2.7.x.md
  app/_hub/kong-inc/ldap-auth-advanced/_index.md
  app/_hub/kong-inc/ldap-auth-advanced/versions.yml
Labels: pr/please review, review:general, review:copyedit

#4264 [DOCU-2291] Copy vaults GA edits to 3.0
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/kong-enterprise/secrets-management/advanced-usage.md
  src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
  src/gateway/kong-enterprise/secrets-management/backends/env.md
  src/gateway/kong-enterprise/secrets-management/backends/gcp-sm.md
  src/gateway/kong-enterprise/secrets-management/backends/google-sm.md
  src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
  src/gateway/kong-enterprise/secrets-management/backends/index.md
  src/gateway/kong-enterprise/secrets-management/getting-started.md
  src/gateway/kong-enterprise/secrets-management/index.md
  src/gateway/kong-enterprise/secrets-management/reference-format.md
Labels: review:general

#4238 docs: handle beta GW apis for 2.6.x KIC
  app/_data/docs_nav_kic_2.6.x.yml
  app/_data/kong_versions.yml
  src/kubernetes-ingress-controller/guides/using-gateway-api.md
Labels: Kubernetes Team

#4268 [DOCU-2459] Gateway icons
  app/_assets/images/icons/documentation/icn-flag.svg
  app/_assets/images/icons/documentation/icn-learning.svg
  app/_data/docs_nav_gateway_3.0.x.yml
Labels: review:general, ci:manual-approve:link-validation

#4270 [Docu 2470] Configure Rate Limiting
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/get-started/configure-ratelimiting.md
  src/gateway/get-started/configure-services-and-routes.md
  src/gateway/get-started/protect-services.md
Labels: review:copyedit

#3977 Add `ssl_verify` option to OPA plugin
  app/_hub/kong-inc/opa/_index.md
Labels: review:copyedit, ci:manual-approve:link-validation, ci:check-skipped:generated-files

#4266 [Docu 2405] How to publish an API spec on Dev Portal
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/kong-enterprise/developer-portal/dev-portal.md
  src/gateway/kong-enterprise/developer-portal/publish-spec.md
Labels: review:general

#4272 Fix duplicate page generation in KIC
  app/_data/docs_nav_kic_2.3.x.yml
  app/_data/docs_nav_kic_2.4.x.yml
  app/_data/docs_nav_kic_2.5.x.yml
Labels: review:general

#4275 add missing single quote
  .github/styles/kong/dictionary.txt
  src/gateway/understanding-kong/how-to/router-atc.md
Labels: review:tech, review:general

#4276 Fix PDF generation for single sourced content
  pdf-generation/build-urls.js
Labels: review:tech

#4262 Fix vault bundles description
  app/gateway/2.8.x/reference/configuration.md
Labels: review:copyedit, ci:check-skipped:generated-files

#4277 [docu-2471] Proxy caching
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/get-started/configure-ratelimiting.md
  src/gateway/get-started/improve-performance.md
  src/gateway/get-started/proxy-caching.md
Labels: review:copyedit

#4273 Adds required flag to get.konghq.com/quickstart script for adding a s…
  src/gateway/understanding-kong/how-to/kong-gateway.md
Labels: review:general

#4271 Fix breadcrumb links
  app/_includes/breadcrumbs.html
  app/_layouts/docs-v2.html
Labels: review:tech, review:general

#4280 fix the http_proxy_host example value
  app/_hub/kong-inc/forward-proxy/_index.md
Labels: review:general

#4278 [DOCU-2432] Kong Manager overview
  app/_assets/images/docs/gateway/km_workspace.png
  src/gateway/kong-manager/overview.md
Labels: review:copyedit

#4263 [DOCU-2426] Kong Enterprise: Overview
  src/gateway/kong-enterprise/index.md
Labels: review:copyedit

#4281 Use netlify dev for PDF generation
  .github/workflows/build-docs-pdf.yml
  pdf-generation/build-urls.js
  pdf-generation/package-lock.json
  pdf-generation/package.json
  pdf-generation/run.js
Labels: review:tech

#4282 fix the service name in graphql quickstart
  .github/styles/kong/dictionary.txt
  app/enterprise/1.3-x/plugins/graphql-quickstart.md
  app/enterprise/1.5.x/plugins/graphql-quickstart.md
  app/enterprise/2.1.x/plugins/graphql-quickstart.md
  app/enterprise/2.2.x/plugins/graphql-quickstart.md
  app/enterprise/2.3.x/plugins/graphql-quickstart.md
  app/enterprise/2.4.x/plugins/graphql-quickstart.md
  app/enterprise/2.5.x/plugins/graphql-quickstart.md
  app/gateway/2.6.x/configure/graphql-quickstart.md
  app/gateway/2.7.x/configure/graphql-quickstart.md
  app/gateway/2.8.x/configure/graphql-quickstart.md
Labels: pr/please review, review:tech, ci:manual-approve:link-validation

#4283 [DOCU-2301] Mocking plugin: remove openapi2kong link
  app/_hub/kong-inc/mocking/0.1.x.md
  app/_hub/kong-inc/mocking/_index.md
  app/_hub/kong-inc/mocking/versions.yml
Labels: review:general

#4260 DOCU-2423: Adds StatsD monitoring page under Kong in Production
  .github/styles/kong/dictionary.txt
  src/gateway/kong-production/monitoring/statsd.md
Labels: review:general

#4285 [DOCU-2311] Request transformer differences
  app/_hub/kong-inc/request-transformer-advanced/0.31-x.md
  app/_hub/kong-inc/request-transformer-advanced/0.32-x.md
  app/_hub/kong-inc/request-transformer-advanced/0.33-x.md
  app/_hub/kong-inc/request-transformer-advanced/0.34-x.md
  app/_hub/kong-inc/request-transformer-advanced/0.35-x.md
  app/_hub/kong-inc/request-transformer-advanced/0.36-x.md
  app/_hub/kong-inc/request-transformer-advanced/1.3-x.md
  app/_hub/kong-inc/request-transformer-advanced/1.5.x.md
  app/_hub/kong-inc/request-transformer-advanced/_index.md
  app/_hub/kong-inc/request-transformer-advanced/versions.yml
  app/_hub/kong-inc/request-transformer/0.1-x.md
  app/_hub/kong-inc/request-transformer/1.2.x.md
  app/_hub/kong-inc/request-transformer/_index.md
  app/_hub/kong-inc/request-transformer/versions.yml
Labels: review:general

#4287 [DOCU-2296] Serverless plugin: remove deprecated param and single-source
  app/_hub/kong-inc/serverless-functions/0.1-x.md
  app/_hub/kong-inc/serverless-functions/0.2-x.md
  app/_hub/kong-inc/serverless-functions/0.3-x.md
  app/_hub/kong-inc/serverless-functions/1.0-x.md
  app/_hub/kong-inc/serverless-functions/_index.md
  app/_hub/kong-inc/serverless-functions/versions.yml
Labels: review:general

#4230 doc(kic) add Gateway API concepts
  app/_data/docs_nav_kic_2.5.x.yml
  src/kubernetes-ingress-controller/concepts/gateway-api.md
  src/kubernetes-ingress-controller/guides/using-gateway-api.md
Labels: review:tech, review:general, review:copyedit

#4267 DOCU-2422: Adds How to monitor with Prometheus
  src/gateway/kong-production/monitoring/prometheus.md
Labels: review:general

#4297 Fix Docker logo on Runtime Manager overview
  app/konnect/runtime-manager/index.md
Labels: review:general

#4298 Add LMDB corruption FAQ
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/reference/faq.md
Labels: review:general

#4295 Update PDK docs for 3.0
  src/gateway/plugin-development/pdk/index.md
  src/gateway/plugin-development/pdk/kong.nginx.md
  src/gateway/plugin-development/pdk/kong.request.md
  src/gateway/plugin-development/pdk/kong.response.md
  src/gateway/plugin-development/pdk/kong.service.md
  src/gateway/plugin-development/pdk/kong.tracing.md
  src/gateway/plugin-development/pdk/kong.vault.md
Labels: review:autodoc, ci:check-skipped:generated-files

#4292 mesh: replace characters in common name
  src/mesh/features/vault.md
Labels: review:general

#4294 Remove config.cache in favour of LMDB
  src/gateway/reference/configuration.md
Labels: review:general

#4291 Switch AWS Secrets Manager examples to use curl
  app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/aws-sm.md
  src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
Labels: review:general

#4299 [DOCU-2387] Workspace name is not editable
  src/gateway/configure/auth/kong-manager/workspaces.md
  src/gateway/kong-manager/workspaces.md
Labels: review:general

#4300 [DOCU-2387] Workspace name is not editable (main branch)
  app/enterprise/2.1.x/kong-manager/administration/workspaces/workspaces.md
  app/enterprise/2.2.x/kong-manager/administration/workspaces/workspaces.md
  app/enterprise/2.3.x/kong-manager/administration/workspaces/workspaces.md
  app/enterprise/2.4.x/kong-manager/administration/workspaces/workspaces.md
  app/enterprise/2.5.x/kong-manager/administration/workspaces/workspaces.md
  app/gateway/2.6.x/configure/auth/kong-manager/workspaces.md
  app/gateway/2.7.x/configure/auth/kong-manager/workspaces.md
  app/gateway/2.8.x/configure/auth/kong-manager/workspaces.md
Labels: review:general

#4301 [fix]Remove config cache
  src/gateway/kong-production/deployment-topologies/hybrid-mode/hybrid-mode-setup.md
Labels: review:general, review:copyedit

#4274 Changelog and version bump for 2.8.1.4
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general, review:copyedit

#4305 [changelog] version update
  app/gateway/changelog.md
Labels: review:copyedit

#4302 Config reference for 3.0
  app/_data/docs_nav_gateway_3.0.x.yml
  autodoc-conf-ee/data.lua
  autodoc-conf-ee/run.lua
  src/gateway/reference/configuration.md
Labels: review:general, ci:manual-approve:link-validation, ci:check-skipped:generated-files

#4303 Release: decK 1.4.0
  app/_data/docs_nav_deck_1.14.x.yml
  app/_data/kong_versions.yml
  src/deck/guides/konnect.md
  src/deck/reference/deck.md
  src/deck/reference/deck_completion.md
  src/deck/reference/deck_convert.md
  src/deck/reference/deck_diff.md
  src/deck/reference/deck_dump.md
  src/deck/reference/deck_konnect_dump.md
  src/deck/reference/deck_ping.md
  src/deck/reference/deck_reset.md
  src/deck/reference/deck_sync.md
  src/deck/reference/deck_validate.md
  src/deck/reference/deck_version.md
Labels: review:general, ci:check-skipped:generated-files

#4308 Correcting AWS & GCP references in 2.8.1.4
  app/gateway/changelog.md
Labels: pr/please review, review:general

#4279 docs: update changelog
  app/mesh/changelog.md
Labels: review:general

#4312 Add Mesh 1.9.0 to support policy
  app/konnect-platform/support-policy.md
Labels: review:general

#4314 [Release] mesh 1.9
  app/_data/docs_nav_mesh_1.9.x.yml
  app/_data/kong_versions.yml
  app/konnect-platform/support-policy.md
  app/mesh/changelog.md
  src/mesh/features/vault.md
Labels: review:general

#4313 Add apt-mark hold instructions to Ubuntu/Debian
  .github/styles/kong/dictionary.txt
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/navtabs.less
  app/gateway/2.8.x/install-and-run/debian.md
  app/gateway/2.8.x/install-and-run/ubuntu.md
  src/gateway/kong-production/install-options/linux/debian.md
  src/gateway/kong-production/install-options/linux/ubuntu.md
Labels: review:general

#4307 [DOCU-2296] Acme plugin changes in 3.0
  app/_hub/kong-inc/acme/0.2.11.md
  app/_hub/kong-inc/acme/0.2.13.md
  app/_hub/kong-inc/acme/0.2.14.md
  app/_hub/kong-inc/acme/0.2.2.md
  app/_hub/kong-inc/acme/0.2.7.md
  app/_hub/kong-inc/acme/0.3.x.md
  app/_hub/kong-inc/acme/_index.md
  app/_hub/kong-inc/acme/versions.yml
Labels: review:general

#4316 Fix config.groups_required parameter for ldap-auth-advanced EE plugin
  app/_hub/kong-inc/ldap-auth-advanced/_index.md
Labels: pr/please review, review:general, review:copyedit

#4310 docs(*) hi-light referenceable fields in docs
  app/_hub/kong-inc/acme/_index.md
  app/_hub/kong-inc/aws-lambda/_index.md
  app/_hub/kong-inc/azure-functions/_index.md
  app/_hub/kong-inc/loggly/_index.md
  app/_hub/kong-inc/openid-connect/_index.md
  app/_hub/kong-inc/rate-limiting/_index.md
  app/_hub/kong-inc/response-ratelimiting/_index.md
  app/_hub/kong-inc/session/_index.md
Labels: pr/please review, review:general, ci:check-skipped:generated-files

#4290 [DOCU-1561] Version compatibility matrix
  app/_data/docs_nav_ee_1.3-x.yml
  app/_data/docs_nav_ee_1.5.x.yml
  app/_data/docs_nav_ee_2.1.x.yml
  app/_data/docs_nav_ee_2.2.x.yml
  app/_data/docs_nav_ee_2.3.x.yml
  app/_data/docs_nav_ee_2.4.x.yml
  app/_data/docs_nav_ee_2.5.x.yml
  app/_data/docs_nav_gateway_2.6.x.yml
  app/_data/docs_nav_gateway_2.7.x.yml
  app/_data/docs_nav_gateway_2.8.x.yml
  app/_data/docs_nav_konnect_platform.yml
  app/_data/tables/compat.json
  app/_plugins/filters/exception_filter.rb
  app/enterprise/1.3-x/compatibility.md
  app/enterprise/1.5.x/compatibility.md
  app/enterprise/2.1.x/compatibility.md
  app/enterprise/2.2.x/compatibility.md
  app/enterprise/2.3.x/compatibility.md
  app/enterprise/2.4.x/compatibility.md
  app/enterprise/2.5.x/compatibility.md
  app/gateway/2.6.x/compatibility.md
  app/gateway/2.7.x/compatibility.md
  app/gateway/2.8.x/compatibility.md
  app/konnect-platform/compatibility/index.md
Labels: review:general

#4289 doc(openid-connet) session_compressor default to 'none'
  app/_hub/kong-inc/openid-connect/_index.md
Labels: review:tech

#4309 docs(rate-limiting-advanced) disallow cluster strategy in DB-less or …
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
Labels: review:tech, review:copyedit

#4321 Titleize breadcrumbs
  Gemfile
  Gemfile.lock
  app/_includes/breadcrumbs.html
  app/_plugins/filters/titleize_filter.rb
Labels: review:tech

#4284 DOCU-2414: Adds Get Kong to getting started guide
  app/_data/docs_nav_gateway_3.0.x.yml
  app/moved_urls.yml
  src/gateway/get-started/configure-services-and-routes.md
  src/gateway/get-started/get-kong-with-docker.md
  src/gateway/get-started/get-kong.md
  src/gateway/get-started/index.md
Labels: review:copyedit

#4318 [DOCU-2296] Plugins: Remove deprecated X-credential-username, single-source
  app/_hub/kong-inc/basic-auth/0.1-x.md
  app/_hub/kong-inc/basic-auth/2.1-x.md
  app/_hub/kong-inc/basic-auth/_index.md
  app/_hub/kong-inc/basic-auth/versions.yml
  app/_hub/kong-inc/hmac-auth/0.1-x.md
  app/_hub/kong-inc/hmac-auth/2.1-x.md
  app/_hub/kong-inc/hmac-auth/2.4-x.md
  app/_hub/kong-inc/hmac-auth/_index.md
  app/_hub/kong-inc/hmac-auth/versions.yml
  app/_hub/kong-inc/key-auth-enc/1.0.x.md
  app/_hub/kong-inc/key-auth-enc/_index.md
  app/_hub/kong-inc/key-auth-enc/versions.yml
  app/_hub/kong-inc/key-auth/0.2.x.md
  app/_hub/kong-inc/key-auth/2.1.x.md
  app/_hub/kong-inc/key-auth/2.2.x.md
  app/_hub/kong-inc/key-auth/_index.md
  app/_hub/kong-inc/key-auth/versions.yml
  app/_hub/kong-inc/ldap-auth-advanced/_index.md
  app/_hub/kong-inc/ldap-auth/0.1-x.md
  app/_hub/kong-inc/ldap-auth/2.1-x.md
  app/_hub/kong-inc/ldap-auth/_index.md
  app/_hub/kong-inc/ldap-auth/versions.yml
  app/_hub/kong-inc/mtls-auth/0.36-x.md
  app/_hub/kong-inc/mtls-auth/1.3-x.md
  app/_hub/kong-inc/mtls-auth/_index.md
  app/_hub/kong-inc/mtls-auth/versions.yml
  app/_hub/kong-inc/oauth2-introspection/0.31-x.md
  app/_hub/kong-inc/oauth2-introspection/0.32-x.md
  app/_hub/kong-inc/oauth2-introspection/0.33-x.md
  app/_hub/kong-inc/oauth2-introspection/0.34-x.md
  app/_hub/kong-inc/oauth2-introspection/0.35-x.md
  app/_hub/kong-inc/oauth2-introspection/0.36-x.md
  app/_hub/kong-inc/oauth2-introspection/_index.md
  app/_hub/kong-inc/oauth2-introspection/versions.yml
  app/_includes/md/plugins-hub/upstream-headers.md
Labels: review:general

#4325 Fix smoke tests for newly linked breadcrumbs
  tests/breadcrumbs.test.js
Labels: review:tech

#4311 docs on path handling algorithm in Kong 3.0
  .github/styles/kong/dictionary.txt
  src/gateway/admin-api/index.md
Labels: review:tech, review:general

#4326 Traditional / Clustering Topology
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/kong-production/deployment-topologies/traditional.md
  src/gateway/kong-production/deployment-topologies/traditional/index.md
Labels: review:general

#4322 Custom Docker Builds
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/kong-production/install-options/docker/build-custom-images.md
  src/gateway/kong-production/install-options/docker/index.md
Labels: review:tech, review:copyedit, ci:manual-approve:link-validation

#4327 [Fix] Remove broken image from Rbac guide
  app/gateway/2.6.x/configure/auth/rbac/index.md
  app/gateway/2.7.x/configure/auth/rbac/index.md
  app/gateway/2.8.x/configure/auth/rbac/index.md
Labels: review:copyedit

#4304 DOCU-2415: updates Services and Routes getting started section
  app/_data/docs_nav_gateway_3.0.x.yml
  app/moved_urls.yml
  src/gateway/get-started/configure-services-and-routes.md
  src/gateway/get-started/services-and-routes.md
Labels: review:copyedit

#4269 [DOCU-2416] Kong in Production> Topologies: Overview
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/kong-production/deployment-topologies/index.md
  src/gateway/kong-production/deployment-topologies/overview.md
Labels: review:copyedit

#4328 Fix Gateway 2.8.x Overview nav link
  app/_data/docs_nav_gateway_2.8.x.yml
Labels: review:general, ci:manual-approve:link-validation

#3886 [docu-2475]Helm installation guides
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_2.8.x.yml
  app/_data/docs_nav_gateway_3.0.x.yml
  app/gateway/2.8.x/install-and-run/helm-quickstart-enterprise.md
  broken-link-checker/excluded.json
  src/gateway/kong-production/install-options/helm-quickstart.md
  tests/seo.test.js
Labels: do not merge

#4333 fix: sets access-control-allow-* headers
  app/_headers
Labels: review:tech

#4320 DOCU-2470: Updates the rate limiting section of the get-started guide
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/get-started/configure-ratelimiting.md
  src/gateway/get-started/rate-limiting.md
Labels: review:copyedit

#4329 Docker custom build feedback
  src/gateway/kong-production/install-options/docker/build-custom-images.md
Labels: review:general

#4319 [DOCU-1563] Kong Glossary
  src/gateway/understanding-kong/glossary.md
Labels: review:copyedit

#4330 DOCU-2471: Updates proxy-caching get-started guide for 3.0 release
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/get-started/proxy-caching.md
Labels: review:copyedit

#4336 Update get-kong.md
  src/gateway/get-started/get-kong.md
Labels: review:general

#4315 Kong Gateway comparison table
  .github/styles/kong/dictionary.txt
  app/_assets/stylesheets/features-table.less
  app/_data/tables/features/gateway.yml
  app/_data/tables/features/mesh.yml
  app/_includes/feature-table.html
  src/gateway/index.md
  src/mesh/index.md
Labels: review:general

#4343 Docu 2484 install index page
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/tables/features/gateway.yml
  app/_data/tables/install_options.yml
  app/_includes/feature-table.html
  src/gateway/kong-production/install-options/index.md
Labels: review:general

#4342 Moved urls redirects
  app/_plugins/generators/alias_generator.rb
Labels: review:tech

#4339 Add missing config options
  src/gateway/reference/configuration.md
Labels: review:general, ci:prevent-merge:generated-files, ci:check-skipped:generated-files

#4346 [fix] Empty pages, broken images, redirects
  app/_data/docs_nav_gateway_3.0.x.yml
  app/moved_urls.yml
  src/gateway/kong-enterprise/developer-portal/customize/theme-editing.md
  src/gateway/kong-plugins/authentication/oidc/cognito.md
  src/gateway/kong-plugins/configuring-a-grpc-service.md
  src/gateway/kong-production/monitoring/prometheus.md
  src/gateway/production-deployment/deployment-topologies/index.md
  src/gateway/production-deployment/monitoring/prometheus.md
Labels: review:general

#4350 Remove circular references in moved_urls
  app/_plugins/generators/canonical_url_generator.rb
  app/moved_urls.yml
Labels: review:tech

#4349 Get started fix route name
  src/gateway/get-started/proxy-caching.md
  src/gateway/get-started/rate-limiting.md
  src/gateway/get-started/services-and-routes.md
Labels: review:general

#4338 DOCU-2474: Removes workspaces and teams from the 3.0 get-started guide
  app/_data/docs_nav_gateway_3.0.x.yml
  src/gateway/get-started/manage-teams.md
Labels: review:copyedit

#4351 URL Structure Updates + Breadcrumbs
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_includes/breadcrumbs.html
  app/_plugins/filters/titleize_filter.rb
  app/moved_urls.yml
  src/gateway/how-kong-works/health-checks.md
  src/gateway/how-kong-works/load-balancing.md
  src/gateway/how-kong-works/routing-traffic.md
  src/gateway/install-and-run/index.md
  src/gateway/install/kubernetes/kubectl.md
  src/gateway/kong-production/deployment-topologies/hybrid-mode/hybrid-mode-setup.md
  src/gateway/kong-production/deployment-topologies/index.md
  src/gateway/production-deployment/deployment-topologies/traditional.md
  src/gateway/production-deployment/deployment-topologies/traditional/index.md
Labels: review:general

#4345 Update /install/ index page
  app/_data/tables/install_options.yml
  src/gateway/install/index.md
Labels: do not merge, review:general

#4354 Add / to plugin canonical URLs
  app/_plugins/generators/plugin_single_source_generator.rb
Labels: review:general

#4357 Plugin Development title cleanup
  src/gateway/plugin-development/access-the-datastore.md
  src/gateway/plugin-development/admin-api.md
  src/gateway/plugin-development/configuration.md
  src/gateway/plugin-development/custom-entities.md
  src/gateway/plugin-development/custom-logic.md
  src/gateway/plugin-development/distribution.md
  src/gateway/plugin-development/entities-cache.md
  src/gateway/plugin-development/file-structure.md
  src/gateway/plugin-development/index.md
  src/gateway/plugin-development/tests.md
Labels: review:general

#4337 DOCU-2473: Load Balancing get-started guide update
  src/gateway/get-started/load-balancing.md
Labels: review:copyedit

#4353 Get Started: Updates rate limiting advanced plugin discussion
  src/gateway/get-started/rate-limiting.md
Labels: review:general

#4358 Update plugin priorities
  src/gateway/plugin-development/custom-logic.md
Labels: review:general
