Repository Kong/docs.konghq.com, pull requests merged in 2022-04, with the labels that each got.

#3791 Update Portal Auth flow
  app/_assets/images/docs/konnect/konnect-devs-page.png
  app/_assets/images/docs/konnect/konnect-requests-dev-reg.png
  app/konnect/dev-portal/access-and-approval/dev-reg.md
  app/konnect/dev-portal/access-and-approval/manage-devs.md
Labels: review:general

#3808 Clean up plugins
  app/_assets/javascripts/app.js
  app/_plugins/blocks/kong_version_block.rb
  app/_plugins/blocks/navtabs.rb
  app/_plugins/edition.rb
  app/_plugins/filters/expand_nested_variable_filter.rb
  app/_plugins/filters/indent_filter.rb
  app/_plugins/filters/liquify.rb
  app/_plugins/generators/alias_generator.rb
  app/_plugins/generators/book.rb
  app/_plugins/generators/environment_variables.rb
  app/_plugins/generators/single_source_generator.rb
  app/_plugins/generators/versions.rb
  app/_plugins/tags/konnect_icon_tag.rb
  app/_plugins/tags/page_exists.rb
Labels: review:tech

#3812 fix: update instructions for Konnect Okta config
  app/konnect/org-management/okta-idp.md
Labels: review:general, ci:manual-approve:link-validation

#3809 doc(kic) add profiling instructions
  app/kubernetes-ingress-controller/2.2.x/troubleshooting.md
Labels: review:general

#3806 Fixing small references to non-encrypted plugin
  app/_hub/kong-inc/key-auth-enc/index.md
Labels: review:general

#3816 Docs/vault aws auth
  app/mesh/1.7.x/features/vault.md
Labels: review:general

#3819 fix(kong-mesh): fix support policy
  app/_data/docs_nav_mesh_1.5.x.yml
  app/_data/docs_nav_mesh_1.6.x.yml
  app/konnect-platform/support-policy.md
Labels: review:general

#3815 doc(kic) add 2.3.x
  algolia/config-full-docs.json
  app/_data/docs_nav_kic_2.3.x.yml
  app/_data/kong_versions.yml
  app/kubernetes-ingress-controller/2.3.x/concepts/custom-resources.md
  app/kubernetes-ingress-controller/2.3.x/concepts/deployment.md
  app/kubernetes-ingress-controller/2.3.x/concepts/design.md
  app/kubernetes-ingress-controller/2.3.x/concepts/ha-and-scaling.md
  app/kubernetes-ingress-controller/2.3.x/concepts/ingress-classes.md
  app/kubernetes-ingress-controller/2.3.x/concepts/ingress-versions.md
  app/kubernetes-ingress-controller/2.3.x/concepts/k4k8s-with-kong-enterprise.md
  app/kubernetes-ingress-controller/2.3.x/concepts/security.md
  app/kubernetes-ingress-controller/2.3.x/deployment/admission-webhook.md
  app/kubernetes-ingress-controller/2.3.x/deployment/aks.md
  app/kubernetes-ingress-controller/2.3.x/deployment/eks.md
  app/kubernetes-ingress-controller/2.3.x/deployment/gke.md
  app/kubernetes-ingress-controller/2.3.x/deployment/k4k8s-enterprise.md
  app/kubernetes-ingress-controller/2.3.x/deployment/k4k8s.md
  app/kubernetes-ingress-controller/2.3.x/deployment/kong-enterprise.md
  app/kubernetes-ingress-controller/2.3.x/deployment/minikube.md
  app/kubernetes-ingress-controller/2.3.x/deployment/overview.md
  app/kubernetes-ingress-controller/2.3.x/examples/001_multiple-services.yaml
  app/kubernetes-ingress-controller/2.3.x/faq.md
  app/kubernetes-ingress-controller/2.3.x/guides/cert-manager.md
  app/kubernetes-ingress-controller/2.3.x/guides/configure-acl-plugin.md
  app/kubernetes-ingress-controller/2.3.x/guides/configuring-custom-entities.md
  app/kubernetes-ingress-controller/2.3.x/guides/configuring-fallback-service.md
  app/kubernetes-ingress-controller/2.3.x/guides/configuring-health-checks.md
  app/kubernetes-ingress-controller/2.3.x/guides/configuring-https-redirect.md
  app/kubernetes-ingress-controller/2.3.x/guides/getting-started-istio.md
  app/kubernetes-ingress-controller/2.3.x/guides/getting-started.md
  app/kubernetes-ingress-controller/2.3.x/guides/overview.md
  app/kubernetes-ingress-controller/2.3.x/guides/preserve-client-ip.md
  app/kubernetes-ingress-controller/2.3.x/guides/prometheus-grafana.md
  app/kubernetes-ingress-controller/2.3.x/guides/redis-rate-limiting.md
  app/kubernetes-ingress-controller/2.3.x/guides/setting-up-custom-plugins.md
  app/kubernetes-ingress-controller/2.3.x/guides/upgrade.md
  app/kubernetes-ingress-controller/2.3.x/guides/upstream-mtls.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-consumer-credential-resource.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-external-service.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-gateway-api.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-ingress-with-grpc.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-kong-with-knative.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-kongclusterplugin-resource.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-kongingress-resource.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-kongplugin-resource.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-mtls-auth-plugin.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-oidc-plugin.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-rewrites.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-tcpingress.md
  app/kubernetes-ingress-controller/2.3.x/guides/using-udpingress.md
  app/kubernetes-ingress-controller/2.3.x/index.md
  app/kubernetes-ingress-controller/2.3.x/references/annotations.md
  app/kubernetes-ingress-controller/2.3.x/references/cli-arguments.md
  app/kubernetes-ingress-controller/2.3.x/references/custom-resources.md
  app/kubernetes-ingress-controller/2.3.x/references/plugin-compatibility.md
  app/kubernetes-ingress-controller/2.3.x/references/prometheus.md
  app/kubernetes-ingress-controller/2.3.x/references/version-compatibility.md
  app/kubernetes-ingress-controller/2.3.x/troubleshooting.md
Labels: review:general

#3823 Upgrade .ruby-version
  .ruby-version
  README.md
Labels: review:tech

#3822 docs(kuma-cp): Add documentation for ACM Private CA
  app/_data/docs_nav_mesh_1.7.x.yml
  app/mesh/1.7.x/features/acmpca.md
  app/mesh/1.7.x/features/vault.md
  app/mesh/1.7.x/gettingstarted.md
Labels: review:general

#3825 chore(mesh): clarify what happens when a license expires
  app/mesh/1.7.x/plan-and-deploy/license.md
Labels: review:copyedit

#3826 chore(mesh): make windows and ubi docs more prominent
  app/_data/docs_nav_mesh_1.7.x.yml
  app/_data/kong_versions.yml
  app/_redirects
  app/mesh/1.7.x/installation/docker.md
  app/mesh/1.7.x/installation/kubernetes.md
Labels: review:general

#3827 chore(mesh): add changelog for 1.6.1 and 1.7.0
  app/mesh/changelog.md
Labels: review:general

#3796 Replace Mesh graphic with features table
  app/mesh/1.7.x/index.md
Labels: review:general

#3830 fix: use correct deck flag for RGs
  app/konnect/configure/runtime-manager/runtime-groups/declarative-config.md
  app/konnect/configure/runtime-manager/runtime-groups/manage.md
  app/konnect/deployment/import.md
Labels: review:general

#3832 Mesh 1.7
  app/_data/docs_nav_mesh_1.7.x.yml
  app/_data/kong_versions.yml
  app/_redirects
  app/mesh/1.7.x/features/acmpca.md
  app/mesh/1.7.x/features/ca-rotation.md
  app/mesh/1.7.x/features/fips-support.md
  app/mesh/1.7.x/features/kds-auth.md
  app/mesh/1.7.x/features/opa.md
  app/mesh/1.7.x/features/rbac.md
  app/mesh/1.7.x/features/ubi-images.md
  app/mesh/1.7.x/features/vault.md
  app/mesh/1.7.x/gettingstarted.md
  app/mesh/1.7.x/index.md
  app/mesh/1.7.x/install.md
  app/mesh/1.7.x/installation/amazonlinux.md
  app/mesh/1.7.x/installation/centos.md
  app/mesh/1.7.x/installation/debian.md
  app/mesh/1.7.x/installation/docker.md
  app/mesh/1.7.x/installation/ecs.md
  app/mesh/1.7.x/installation/helm.md
  app/mesh/1.7.x/installation/kubernetes.md
  app/mesh/1.7.x/installation/macos.md
  app/mesh/1.7.x/installation/openshift.md
  app/mesh/1.7.x/installation/redhat.md
  app/mesh/1.7.x/installation/ubuntu.md
  app/mesh/1.7.x/installation/windows.md
  app/mesh/1.7.x/patches/opa-policy.yaml
  app/mesh/1.7.x/plan-and-deploy/license.md
  app/mesh/changelog.md
Labels: review:general

#3840 Update kuma.io links to match new site structure
  app/_includes/md/mesh/install-universal-run.md
  app/mesh/1.0.x/features/vault.md
  app/mesh/1.0.x/installation/docker.md
  app/mesh/1.0.x/installation/helm.md
  app/mesh/1.0.x/installation/kubernetes.md
  app/mesh/1.0.x/installation/openshift.md
  app/mesh/1.0.x/overview.md
  app/mesh/1.1.x/features/vault.md
  app/mesh/1.1.x/installation/docker.md
  app/mesh/1.1.x/installation/helm.md
  app/mesh/1.1.x/installation/kubernetes.md
  app/mesh/1.1.x/installation/openshift.md
  app/mesh/1.1.x/overview.md
  app/mesh/1.2.x/features/opa.md
  app/mesh/1.2.x/features/vault.md
  app/mesh/1.2.x/index.md
  app/mesh/1.2.x/installation/docker.md
  app/mesh/1.2.x/installation/helm.md
  app/mesh/1.2.x/installation/kubernetes.md
  app/mesh/1.2.x/installation/openshift.md
  app/mesh/1.3.x/features/opa.md
  app/mesh/1.3.x/features/vault.md
  app/mesh/1.3.x/index.md
  app/mesh/1.3.x/installation/docker.md
  app/mesh/1.3.x/installation/helm.md
  app/mesh/1.3.x/installation/kubernetes.md
  app/mesh/1.3.x/installation/openshift.md
  app/mesh/1.4.x/features/opa.md
  app/mesh/1.4.x/features/vault.md
  app/mesh/1.4.x/index.md
  app/mesh/1.4.x/installation/docker.md
  app/mesh/1.4.x/installation/helm.md
  app/mesh/1.4.x/installation/kubernetes.md
  app/mesh/1.4.x/installation/openshift.md
  app/mesh/1.5.x/features/opa.md
  app/mesh/1.5.x/features/vault.md
  app/mesh/1.5.x/index.md
  app/mesh/1.5.x/installation/docker.md
  app/mesh/1.5.x/installation/helm.md
  app/mesh/1.5.x/installation/kubernetes.md
  app/mesh/1.5.x/installation/openshift.md
  app/mesh/1.5.x/installation/windows.md
  app/mesh/1.6.x/features/vault.md
  app/mesh/1.6.x/index.md
  app/mesh/1.6.x/installation/docker.md
  app/mesh/1.6.x/installation/ecs.md
  app/mesh/1.6.x/installation/helm.md
  app/mesh/1.6.x/installation/kubernetes.md
  app/mesh/1.6.x/installation/openshift.md
  app/mesh/1.6.x/installation/windows.md
  app/mesh/1.7.x/features/acmpca.md
  app/mesh/1.7.x/features/vault.md
  app/mesh/1.7.x/index.md
  app/mesh/1.7.x/installation/docker.md
  app/mesh/1.7.x/installation/ecs.md
  app/mesh/1.7.x/installation/helm.md
  app/mesh/1.7.x/installation/kubernetes.md
  app/mesh/1.7.x/installation/openshift.md
  app/mesh/1.7.x/installation/windows.md
Labels: review:general

#3834 [DOCU-2265] Dev portal settings page relocation
  app/_includes/md/konnect/dev-portal-access.md
  app/konnect/dev-portal/access-and-approval/auto-approve-devs-apps.md
  app/konnect/dev-portal/customization/custom-domain.md
  app/konnect/dev-portal/customization/public-portal.md
Labels: review:general

#3628 [DOCU-1738] Vitals custom reports
  app/_assets/images/icons/konnect/icn-vitals-bargraph.svg
  app/_assets/images/icons/konnect/icn-vitals-horizontal.svg
  app/_assets/images/icons/konnect/icn-vitals.svg
  app/_data/docs_nav_konnect.yml
  app/konnect/vitals/analyze.md
  app/konnect/vitals/generate-reports.md
  app/konnect/vitals/index.md
Labels: do not merge, review:general, review:copyedit

#3842 Update helm install commands
  app/mesh/1.6.x/installation/helm.md
  app/mesh/1.7.x/installation/helm.md
Labels: review:copyedit

#3814 Update kubernetes.md
  app/gateway/2.8.x/install-and-run/kubernetes.md
Labels: review:tech, review:general

#3829 chore(client): update example for kong.client.get_forwared_ip
  app/gateway-oss/2.5.x/pdk/kong.client.md
Labels: review:general

#3817 Fix consumers groups rate limiting overrides attributes
  app/gateway/2.7.x/admin-api/consumer-groups/reference.md
  app/gateway/2.8.x/admin-api/consumer-groups/reference.md
Labels: review:tech

#3844 Platform setup
  Makefile
  README.md
  docs/platform-install.md
  package.json
Labels: review:general, review:copyedit

#3841 Add a warning when generated files are edited
  .github/workflows/autogenerated-warning.yml
  check-generated-content/package-lock.json
  check-generated-content/package.json
  check-generated-content/run.js
  docs/continuous-integration/generated-files.md
Labels: review:tech

#3838 Add Rubocop
  .github/workflows/linting.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/_plugins/blocks/kong_version_block.rb
  app/_plugins/blocks/navtabs.rb
  app/_plugins/filters/expand_nested_variable_filter.rb
  app/_plugins/filters/indent_filter.rb
  app/_plugins/filters/liquify.rb
  app/_plugins/generators/alias_generator.rb
  app/_plugins/generators/book.rb
  app/_plugins/generators/environment_variables.rb
  app/_plugins/generators/single_source_generator.rb
  app/_plugins/generators/versions.rb
  app/_plugins/tags/konnect_icon_tag.rb
  app/_plugins/tags/page_exists.rb
Labels: review:general

#3851 Update proxy.md
  app/gateway/2.8.x/reference/proxy.md
Labels: review:copyedit

#3855 Fix windows mesh install instructions
  app/mesh/1.5.x/installation/windows.md
  app/mesh/1.6.x/installation/windows.md
  app/mesh/1.7.x/installation/windows.md
  app/mesh/installer.ps1
Labels: review:tech, review:general

#3852 Update proxy.md
  app/gateway/2.8.x/reference/proxy.md
Labels: review:copyedit

#3854 Re-add 'enable app reg' doc
  app/gateway/2.8.x/developer-portal/administration/application-registration/enable-application-registration.md
Labels: review:general

#3846 PDK fix: kong.client typo
  app/enterprise/0.35-x/pdk/kong.client.md
  app/enterprise/0.36-x/pdk/kong.client.md
  app/enterprise/1.3-x/pdk/kong.client.md
  app/enterprise/1.5.x/pdk/kong.client.md
  app/enterprise/2.1.x/pdk/kong.client.md
  app/enterprise/2.2.x/pdk/kong.client.md
  app/enterprise/2.3.x/pdk/kong.client.md
  app/enterprise/2.4.x/pdk/kong.client.md
  app/enterprise/2.5.x/pdk/kong.client.md
  app/gateway-oss/0.14.x/pdk/kong.client.md
  app/gateway-oss/1.0.x/pdk/kong.client.md
  app/gateway-oss/1.1.x/pdk/kong.client.md
  app/gateway-oss/1.2.x/pdk/kong.client.md
  app/gateway-oss/1.3.x/pdk/kong.client.md
  app/gateway-oss/1.4.x/pdk/kong.client.md
  app/gateway-oss/1.5.x/pdk/kong.client.md
  app/gateway-oss/2.0.x/pdk/kong.client.md
  app/gateway-oss/2.1.x/pdk/kong.client.md
  app/gateway-oss/2.2.x/pdk/kong.client.md
  app/gateway-oss/2.3.x/pdk/kong.client.md
  app/gateway-oss/2.4.x/pdk/kong.client.md
  app/gateway/2.6.x/pdk/kong.client.md
Labels: review:general

#3853 Add `version` to single sourcing
  app/_plugins/generators/single_source_generator.rb
  docs/single-sourced-versions.md
Labels: review:tech

#3810 Seo/add evergreen urls
  app/_includes/docs-sidebar.html
  app/_includes/head.html
  app/_layouts/default.html
  app/_layouts/docs-v2.html
  app/_plugins/generators/canonical_url_generator.rb
  app/_plugins/generators/latest_version_generator.rb
  app/_plugins/generators/versions.rb
  app/robots.txt
  app/sitemap.xml
  tests/seo.test.js
  tests/sidebar.test.js
Labels: do not merge, review:tech

#3860 Fix broken Mesh Windows link
  app/_redirects
Labels: review:general

#3864 Fix Smoke Tests + run on `main`
  .github/workflows/run-smoke-tests.yml
  app/_plugins/blocks/plugin_version_block.rb
  app/_plugins/generators/plugin_single_source_generator.rb
Labels: review:tech

#3863 Redirect for broken link to vitals
  app/_redirects
Labels: review:general

#3858 Restyle Mesh features table
  app/_assets/images/logos/kong-mesh.png
  app/_assets/images/logos/kuma.png
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/features-table.less
  app/_assets/stylesheets/index.less
  app/_assets/stylesheets/pages/docs.less
  app/mesh/1.7.x/index.md
Labels: review:general

#3856 decK v1.12: Generate cli docs
  src/deck/reference/deck.md
  src/deck/reference/deck_completion.md
  src/deck/reference/deck_convert.md
  src/deck/reference/deck_diff.md
  src/deck/reference/deck_dump.md
  src/deck/reference/deck_konnect.md
  src/deck/reference/deck_konnect_diff.md
  src/deck/reference/deck_konnect_dump.md
  src/deck/reference/deck_konnect_ping.md
  src/deck/reference/deck_konnect_sync.md
  src/deck/reference/deck_ping.md
  src/deck/reference/deck_reset.md
  src/deck/reference/deck_sync.md
  src/deck/reference/deck_validate.md
  src/deck/reference/deck_version.md
Labels: review:general

#3868 Fix github edit link for plugins
  app/_layouts/extension.html
Labels: review:general

#3869 Fix missing version-index on /latest/ pages
  app/_plugins/generators/latest_version_generator.rb
  tests/install.test.js
Labels: review:general

#3845 Release: decK 1.12
  app/_data/docs_nav_deck_1.12.x.yml
  app/_data/kong_versions.yml
  src/deck/compatibility-promise.md
  src/deck/design-architecture.md
  src/deck/faqs.md
  src/deck/guides/backup-restore.md
  src/deck/guides/best-practices.md
  src/deck/guides/ci-driven-configuration.md
  src/deck/guides/deduplicate-plugin-configuration.md
  src/deck/guides/defaults.md
  src/deck/guides/distributed-configuration.md
  src/deck/guides/environment-variables.md
  src/deck/guides/getting-started.md
  src/deck/guides/kong-enterprise.md
  src/deck/guides/multi-file-state.md
  src/deck/index.md
  src/deck/installation.md
  src/deck/reference/deck.md
  src/deck/reference/deck_completion.md
  src/deck/reference/deck_convert.md
  src/deck/reference/deck_diff.md
  src/deck/reference/deck_dump.md
  src/deck/reference/deck_konnect.md
  src/deck/reference/deck_konnect_diff.md
  src/deck/reference/deck_konnect_dump.md
  src/deck/reference/deck_konnect_ping.md
  src/deck/reference/deck_konnect_sync.md
  src/deck/reference/deck_ping.md
  src/deck/reference/deck_reset.md
  src/deck/reference/deck_sync.md
  src/deck/reference/deck_validate.md
  src/deck/reference/deck_version.md
  src/deck/terminology.md
Labels: do not merge, review:general, ci:prevent-merge:generated-files

#3870 Backport license doc improvements
  app/enterprise/2.1.x/deployment/licenses/report.md
  app/enterprise/2.2.x/deployment/licenses/report.md
  app/enterprise/2.3.x/admin-api/licenses/reference.md
  app/enterprise/2.3.x/deployment/licenses/report.md
  app/enterprise/2.4.x/admin-api/licenses/reference.md
  app/enterprise/2.4.x/deployment/licenses/report.md
  app/enterprise/2.5.x/admin-api/licenses/reference.md
  app/enterprise/2.5.x/deployment/licenses/report.md
  app/gateway/2.6.x/admin-api/licenses/reference.md
  app/gateway/2.6.x/plan-and-deploy/licenses/report.md
Labels: review:general

#3882 Correct typo in helm command
  app/kubernetes-ingress-controller/2.3.x/deployment/k4k8s-enterprise.md
Labels: review:general

#3875 Remove external link icon from insomnia run button
  app/_assets/stylesheets/pages/docs.less
Labels: review:general

#3883 Remove Using the Konnect API guide
  app/_data/docs_nav_konnect.yml
  app/konnect/reference/konnect-api.md
Labels: review:general

#3866 Update Style Guide
  app/contributing/style-guide.md
  app/contributing/word-choice.md
Labels: review:general

#3874 Style guide and contribution guidelines for icons
  app/contributing/markdown-rules.md
  app/contributing/style-guide.md
  app/contributing/word-choice.md
Labels: review:copyedit

#3873 Konnect icons
  app/_assets/images/icons/konnect/icn-cogwheel-nav.svg
  app/_assets/images/icons/konnect/icn-cogwheel.svg
  app/_assets/images/icons/konnect/icn-connections.svg
  app/_assets/images/icons/konnect/icn-dev-portal-nav.svg
  app/_assets/images/icons/konnect/icn-dev-portal.svg
  app/_assets/images/icons/konnect/icn-organizations-nav.svg
  app/_assets/images/icons/konnect/icn-vitals-nav.svg
  app/_data/docs_nav_konnect.yml
  app/_includes/md/konnect/create-service.md
  app/_includes/md/konnect/dev-portal-access.md
  app/_includes/md/konnect/docker-runtime.md
  app/_includes/md/konnect/runtime-certs.md
  app/konnect/configure/runtime-manager/runtime-groups/manage-entities.md
  app/konnect/configure/runtime-manager/runtime-groups/manage.md
  app/konnect/configure/runtime-manager/runtime-instances/gateway-runtime-docker.md
  app/konnect/configure/runtime-manager/runtime-instances/renew-certificates.md
  app/konnect/configure/runtime-manager/runtime-instances/upgrade.md
  app/konnect/configure/servicehub/enable-route-plugin.md
  app/konnect/configure/servicehub/enable-service-plugin.md
  app/konnect/configure/servicehub/manage-services.md
  app/konnect/dev-portal/access-and-approval/auto-approve-devs-apps.md
  app/konnect/dev-portal/access-and-approval/dev-reg.md
  app/konnect/dev-portal/access-and-approval/manage-devs.md
  app/konnect/dev-portal/applications/disable-app-reg.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/dev-portal/applications/manage-app-connections.md
  app/konnect/dev-portal/applications/manage-app-reg-requests.md
  app/konnect/dev-portal/customization/appearance.md
  app/konnect/dev-portal/customization/custom-domain.md
  app/konnect/dev-portal/customization/public-portal.md
  app/konnect/dev-portal/publish.md
  app/konnect/dev-portal/service-documentation.md
  app/konnect/getting-started/publish-service.md
  app/konnect/getting-started/spec/app-registration.md
  app/konnect/org-management/teams-and-roles.md
  app/konnect/org-management/users.md
Labels: review:general

#3872 Konnect: Deleting a runtime group
  app/konnect/configure/runtime-manager/runtime-groups/manage.md
Labels: review:general

#3859 docs(oauth2) give more details to header X-Credential-Identifier
  app/_hub/kong-inc/oauth2/_index.md
Labels: review:general

#3884 Update URL when using in-page navigation
  app/_assets/javascripts/app.js
Labels: review:general

#3891 Don't check removed files for autogenerated content
  check-generated-content/run.js
Labels: review:tech

#3894 Update docs for latency to specify the unit
  app/_hub/kong-inc/prometheus/_index.md
Labels: review:general

#3889 Fix proxy-cache config.memory.dictionary_name default value
  app/_hub/kong-inc/graphql-proxy-cache-advanced/_index.md
  app/_hub/kong-inc/proxy-cache-advanced/0.4.x.md
  app/_hub/kong-inc/proxy-cache-advanced/_index.md
  app/_hub/kong-inc/proxy-cache/0.31-x.md
  app/_hub/kong-inc/proxy-cache/0.32-x.md
  app/_hub/kong-inc/proxy-cache/0.33-x.md
  app/_hub/kong-inc/proxy-cache/0.34-x.md
  app/_hub/kong-inc/proxy-cache/_index.md
Labels: review:general

#3888 Update _index.md
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
Labels: review:tech, review:copyedit
