Repository Kong/docs.konghq.com, pull requests merged in 2022-03, with the labels that each got.

#3725 Autodocs update
  app/_data/docs_nav_gateway_2.8.x.yml
  app/gateway/2.8.x/admin-api/index.md
  app/gateway/2.8.x/install-and-run/upgrade-oss.md
  app/gateway/2.8.x/pdk/index.md
  app/gateway/2.8.x/pdk/kong.client.md
  app/gateway/2.8.x/pdk/kong.client.tls.md
  app/gateway/2.8.x/pdk/kong.cluster.md
  app/gateway/2.8.x/pdk/kong.ctx.md
  app/gateway/2.8.x/pdk/kong.ip.md
  app/gateway/2.8.x/pdk/kong.log.md
  app/gateway/2.8.x/pdk/kong.nginx.md
  app/gateway/2.8.x/pdk/kong.node.md
  app/gateway/2.8.x/pdk/kong.request.md
  app/gateway/2.8.x/pdk/kong.response.md
  app/gateway/2.8.x/pdk/kong.router.md
  app/gateway/2.8.x/pdk/kong.service.md
  app/gateway/2.8.x/pdk/kong.service.request.md
  app/gateway/2.8.x/pdk/kong.service.response.md
  app/gateway/2.8.x/pdk/kong.table.md
  app/gateway/2.8.x/pdk/kong.vault.md
  app/gateway/2.8.x/reference/cli.md
Labels: review:general, review:autodoc

#3723 Fix autodoc label name
  .github/workflows/require-review-label.yml
Labels: review:general

#3726 [DOCU-2214] AWS lambda plugin: deprecate proxy_scheme
  app/_hub/kong-inc/aws-lambda/index.md
Labels: review:tech, review:general

#3727 Document admin_auto_create_rbac_token_disabled
  app/gateway/2.8.x/configure/auth/kong-manager/oidc-mapping.md
Labels: review:general

#3728 [DOCU-2211] Promo banner for gateway 2.8
  app/_assets/javascripts/promo-banner.js
  app/_assets/stylesheets/header.less
  app/_includes/nav-v2.html
  gulpfile.js
Labels: review:general

#3706 Clarify how to use deck with tags and multiple files
  app/deck/1.11.x/guides/multi-file-state.md
Labels: review:copyedit

#3693 Update & fix docs site footer
  app/_assets/stylesheets/footer.less
  app/_includes/footer.html
Labels: review:general

#3730 [DOCU-2195] Upgrade guide updates for 2.8
  app/gateway/2.8.x/install-and-run/migrate-ce-to-ke.md
  app/gateway/2.8.x/install-and-run/upgrade-enterprise.md
  app/gateway/2.8.x/install-and-run/upgrade-oss.md
Labels: review:general, ci:manual-approve:link-validation

#3731 [DOCU-2205] Remove tracking params from URLs to konghq.com
  app/enterprise/1.5.x/introduction/index.md
  app/enterprise/1.5.x/release-notes.md
  app/enterprise/2.1.x/introduction/index.md
Labels: review:general

#3729 [DOCU-2215] Deprecation notice for gateway OSS on centos
  app/gateway/2.8.x/install-and-run/centos.md
Labels: review:copyedit, ci:manual-approve:link-validation

#3717 (chore) Generate config reference for 2.8
  app/gateway/2.8.x/reference/configuration.md
Labels: review:tech, review:general

#3713 [DOCU-2183] Gateway 2.8 changelog
  app/gateway/changelog.md
Labels: review:tech, review:copyedit

#3736 Add workflow_dispatch option for algolia indexer
  .github/workflows/algolia.yml
Labels: review:general

#3734 Review label for plugin version GH action
  .github/workflows/add-plugin-version.yml
Labels: review:general

#3737 fix(mesh): add install for windows in logo page
  app/_assets/images/icons/documentation/windows-logo.svg
  app/mesh/1.5.x/install.md
  app/mesh/1.6.x/install.md
Labels: review:general, ci:manual-approve:link-validation

#3738 Fix broken link in footer
  app/_includes/footer.html
Labels: review:general

#3671 [DOCU-978] Add Hybrid Mode note for Vitals
  app/enterprise/2.1.x/vitals/vitals-influx-strategy.md
  app/enterprise/2.1.x/vitals/vitals-prometheus-strategy.md
  app/enterprise/2.2.x/vitals/vitals-influx-strategy.md
  app/enterprise/2.2.x/vitals/vitals-prometheus-strategy.md
  app/enterprise/2.3.x/vitals/vitals-influx-strategy.md
  app/enterprise/2.3.x/vitals/vitals-prometheus-strategy.md
  app/enterprise/2.4.x/vitals/vitals-influx-strategy.md
  app/enterprise/2.4.x/vitals/vitals-prometheus-strategy.md
  app/enterprise/2.5.x/vitals/vitals-influx-strategy.md
  app/enterprise/2.5.x/vitals/vitals-prometheus-strategy.md
  app/gateway/2.6.x/vitals/vitals-influx-strategy.md
  app/gateway/2.6.x/vitals/vitals-prometheus-strategy.md
  app/gateway/2.7.x/vitals/vitals-influx-strategy.md
  app/gateway/2.7.x/vitals/vitals-prometheus-strategy.md
  app/gateway/2.8.x/vitals/vitals-influx-strategy.md
  app/gateway/2.8.x/vitals/vitals-prometheus-strategy.md
Labels: review:general

#3741 fix(changelog) - remove dependecies item about pgmoon version bump
  app/gateway/changelog.md
Labels: review:copyedit

#3685 [DOCU-2198] Dev Portal: Add Migrating Templates page
  app/_data/docs_nav_gateway_2.7.x.yml
  app/_data/docs_nav_gateway_2.8.x.yml
  app/gateway/2.7.x/developer-portal/theme-customization/easy-theme-editing.md
  app/gateway/2.7.x/developer-portal/theme-customization/migrating-templates.md
  app/gateway/2.8.x/developer-portal/theme-customization/easy-theme-editing.md
  app/gateway/2.8.x/developer-portal/theme-customization/migrating-templates.md
Labels: review:general

#3740 [DOCU-348] Admin API: rm del service for route
  app/enterprise/1.3-x/admin-api/index.md
  app/enterprise/1.5.x/admin-api/index.md
  app/enterprise/2.1.x/admin-api/index.md
  app/enterprise/2.2.x/admin-api/index.md
  app/enterprise/2.3.x/admin-api/index.md
  app/enterprise/2.4.x/admin-api/index.md
  app/enterprise/2.5.x/admin-api/index.md
  app/gateway-oss/1.3.x/admin-api.md
  app/gateway-oss/1.4.x/admin-api.md
  app/gateway-oss/1.5.x/admin-api.md
  app/gateway-oss/2.0.x/admin-api.md
  app/gateway-oss/2.1.x/admin-api.md
  app/gateway-oss/2.2.x/admin-api.md
  app/gateway-oss/2.3.x/admin-api.md
  app/gateway-oss/2.4.x/admin-api.md
  app/gateway-oss/2.5.x/admin-api.md
  app/gateway/2.6.x/admin-api/index.md
  app/gateway/2.7.x/admin-api/index.md
  app/gateway/2.8.x/admin-api/index.md
Labels: review:general

#3700 [DOCU-2121] Add Alternate OpenAPI Renderer page
  app/_data/docs_nav_gateway_2.7.x.yml
  app/_data/docs_nav_gateway_2.8.x.yml
  app/code-snippets/spec-renderer.html
  app/code-snippets/statsd.rules.yaml
  app/gateway/2.7.x/developer-portal/theme-customization/alternate-openapi-renderer.md
  app/gateway/2.7.x/vitals/vitals-prometheus-strategy.md
  app/gateway/2.8.x/developer-portal/theme-customization/alternate-openapi-renderer.md
  app/gateway/2.8.x/vitals/vitals-prometheus-strategy.md
Labels: review:general

#3714 fix(mesh): add CORS header to /mesh/latest_version
  app/_headers
  jekyll-dev.yml
  jekyll.yml
  netlify.toml
Labels: review:tech, size/S

#3739 [DOCU-2217] Better license info in installation guides
  app/_includes/md/gateway/setup.md
  app/gateway/2.8.x/install-and-run/docker.md
Labels: review:tech, review:copyedit

#3747 Update changelog.md
  app/mesh/changelog.md
Labels: review:general

#3748 Update gettingstarted.md
  app/mesh/1.6.x/gettingstarted.md
Labels: review:general, ci:manual-approve:link-validation

#3684 [DOCU-1618] RM deprecated Target endpoints
  app/enterprise/2.1.x/admin-api/index.md
  app/enterprise/2.2.x/admin-api/index.md
  app/enterprise/2.3.x/admin-api/index.md
  app/enterprise/2.4.x/admin-api/index.md
  app/enterprise/2.5.x/admin-api/index.md
  app/gateway-oss/2.1.x/admin-api.md
  app/gateway-oss/2.2.x/admin-api.md
  app/gateway-oss/2.3.x/admin-api.md
  app/gateway-oss/2.4.x/admin-api.md
  app/gateway-oss/2.5.x/admin-api.md
  app/gateway/2.6.x/admin-api/index.md
  app/gateway/2.7.x/admin-api/index.md
  app/gateway/2.8.x/admin-api/index.md
Labels: review:general, ci:manual-approve:link-validation

#3746 Update index.md
  app/mesh/1.6.x/index.md
Labels: review:general

#3697 [DOCU-2197] Clarify license deployment
  app/_includes/md/enterprise/deploy-license.md
  app/gateway/2.6.x/plan-and-deploy/hybrid-mode/index.md
  app/gateway/2.6.x/plan-and-deploy/licenses/index.md
  app/gateway/2.7.x/plan-and-deploy/hybrid-mode/index.md
  app/gateway/2.7.x/plan-and-deploy/licenses/index.md
Labels: review:tech, review:copyedit, ci:manual-approve:link-validation

#3742 [DOCU-2209] Plugin example for decK defaults guide
  app/deck/1.11.x/guides/defaults.md
Labels: review:tech, review:general

#3750 [DOCU-510] Add diff: Response Transformer Advanced
  app/_hub/kong-inc/response-transformer-advanced/index.md
  app/_hub/kong-inc/response-transformer/index.md
Labels: review:general

#3744 Playwright
  .github/workflows/run-smoke-tests.yml
  Gemfile
  Gemfile.lock
  Makefile
  README.md
  netlify.toml
  package-lock.json
  package.json
  playwright.config.js
  spec/breadcrumbs_spec.rb
  spec/home_spec.rb
  spec/plugin_spec.rb
  spec/sidebar_spec.rb
  spec/spec_helper.rb
  tests/breadcrumbs.test.js
  tests/home.test.js
  tests/plugin.test.js
  tests/sidebar.test.js
Labels: review:tech, size/L

#3753 [DOCU-416] Add callouts about naming changes
  app/_hub/kong-inc/ip-restriction/index.md
Labels: review:general

#3749 [DOCU-2196] Update k8 install link
  app/gateway/2.6.x/plan-and-deploy/kubernetes-deployment-options.md
  app/gateway/2.7.x/plan-and-deploy/kubernetes-deployment-options.md
  app/gateway/2.8.x/plan-and-deploy/kubernetes-deployment-options.md
Labels: review:general

#3752 Konnect: Gateway 2.8 support
  app/konnect/deployment/index.md
  app/konnect/runtime-manager/gateway-runtime-docker.md
  app/konnect/runtime-manager/gateway-runtime-kubernetes.md
  app/konnect/updates.md
Labels: review:general

#3754 [DOCU-1968] Add missing redis params to plugins
  app/_hub/kong-inc/graphql-rate-limiting-advanced/index.md
  app/_hub/kong-inc/proxy-cache-advanced/index.md
  app/_hub/kong-inc/rate-limiting-advanced/index.md
  app/gateway/changelog.md
Labels: review:general

#3757 Add gateway 2.8 to version support policy
  app/konnect-platform/support-policy.md
Labels: review:general

#3755 [DOCU-2093] Remove breaking \ from get started
  app/_includes/md/enterprise/turn-on-rbac.md
Labels: review:general

#3756 [DOCU-1996] Remove code in headers
  app/contributing/markdown-rules.md
  app/gateway/2.6.x/configure/auth/kong-manager/networking.md
  app/gateway/2.6.x/developer-portal/working-with-templates.md
  app/gateway/2.6.x/install-and-run/upgrade-oss.md
  app/gateway/2.6.x/plan-and-deploy/systemd.md
  app/gateway/2.7.x/configure/auth/kong-manager/networking.md
  app/gateway/2.7.x/developer-portal/working-with-templates.md
  app/gateway/2.7.x/install-and-run/upgrade-oss.md
  app/gateway/2.7.x/plan-and-deploy/systemd.md
  app/gateway/2.7.x/plugin-development/custom-logic.md
  app/gateway/2.8.x/configure/auth/kong-manager/networking.md
  app/gateway/2.8.x/developer-portal/working-with-templates.md
  app/gateway/2.8.x/install-and-run/upgrade-oss.md
  app/gateway/2.8.x/plan-and-deploy/systemd.md
  app/gateway/2.8.x/plugin-development/custom-logic.md
Labels: review:general

#3760 Fix typo in allowing-multiple-authentication-methods.md
  app/gateway/2.8.x/configure/auth/allowing-multiple-authentication-methods.md
Labels: review:general

#3763 Additional podAnnotations for cert-manager
  app/kubernetes-ingress-controller/2.2.x/guides/cert-manager.md
Labels: review:general

#3767 Improve helm docs for mesh
  app/mesh/1.6.x/installation/helm.md
Labels: review:copyedit

#3766 Set nofollow rule for unsecured URLs only
  app/_layouts/default.html
Labels: review:general

#3769 Adjust positioning of badges and tooltips in headers
  app/_assets/stylesheets/badges.less
Labels: review:general

#3765 Add ability to reference existing content
  app/_layouts/docs-v2.html
  app/_plugins/kong_version_block.rb
  app/_plugins/page_exists.rb
  app/_plugins/single_source_generator.rb
  app/_plugins/versions.rb
  docs/single-sourced-versions.md
Labels: review:tech

#3777 Update health-checks-circuit-breakers.md
  app/gateway/2.7.x/reference/health-checks-circuit-breakers.md
Labels: review:tech, review:general, review:copyedit

#3775 Fix typo in getting started guide ( #3774)
  app/gateway/2.8.x/get-started/comprehensive/prepare.md
Labels: review:general

#3778 Backport #3777 to old versions
  app/enterprise/2.1.x/health-checks-circuit-breakers.md
  app/enterprise/2.2.x/health-checks-circuit-breakers.md
  app/enterprise/2.3.x/health-checks-circuit-breakers.md
  app/enterprise/2.4.x/health-checks-circuit-breakers.md
  app/enterprise/2.5.x/health-checks-circuit-breakers.md
  app/gateway-oss/2.0.x/health-checks-circuit-breakers.md
  app/gateway-oss/2.1.x/health-checks-circuit-breakers.md
  app/gateway-oss/2.2.x/health-checks-circuit-breakers.md
  app/gateway-oss/2.3.x/health-checks-circuit-breakers.md
  app/gateway-oss/2.4.x/health-checks-circuit-breakers.md
  app/gateway-oss/2.5.x/health-checks-circuit-breakers.md
  app/gateway/2.6.x/reference/health-checks-circuit-breakers.md
  app/gateway/2.8.x/reference/health-checks-circuit-breakers.md
Labels: review:general

#3772 Add show-version-diff utility
  show-version-diff/README.md
  show-version-diff/package-lock.json
  show-version-diff/package.json
  show-version-diff/run.js
Labels: review:tech

#3783 Update Gateway 2.8.x support dates
  app/konnect-platform/support-policy.md
Labels: review:general

#3779 Fixing all traces of old "remote" against "zone"
  app/mesh/1.6.x/features/kds-auth.md
Labels: pr/please review, review:general

#3786 Backport #3779
  app/mesh/1.3.x/features/kds-auth.md
  app/mesh/1.4.x/features/kds-auth.md
  app/mesh/1.5.x/features/kds-auth.md
Labels: review:general

#3787 Corrected the install URL for EE on Ubuntu
  app/gateway/2.8.x/install-and-run/ubuntu.md
Labels: review:general

#3701 [DOCU-280] Document the kong admin API /developers endpoint
  app/_data/docs_nav_gateway_2.8.x.yml
  app/gateway/2.8.x/admin-api/developers/reference.md
Labels: review:tech, review:copyedit

#3770 Konnect runtime groups intro + how tos
  app/_assets/images/icons/konnect/icn-runtimes.svg
  app/_assets/images/icons/konnect/icn-servicehub.svg
  app/_assets/stylesheets/page.less
  app/_data/docs_nav_konnect.yml
  app/_includes/md/konnect/runtime-certs.md
  app/_redirects
  app/konnect/configure/runtime-manager/index.md
  app/konnect/configure/runtime-manager/manage-entities.md
  app/konnect/configure/runtime-manager/runtime-groups/index.md
  app/konnect/configure/runtime-manager/runtime-groups/manage-entities.md
  app/konnect/configure/runtime-manager/runtime-groups/manage.md
  app/konnect/configure/runtime-manager/runtime-groups/use-case.md
  app/konnect/configure/runtime-manager/runtime-instances/gateway-runtime-conf.md
  app/konnect/configure/runtime-manager/runtime-instances/gateway-runtime-docker.md
  app/konnect/configure/runtime-manager/runtime-instances/gateway-runtime-kubernetes.md
  app/konnect/configure/runtime-manager/runtime-instances/renew-certificates.md
  app/konnect/configure/runtime-manager/runtime-instances/runtime-parameter-reference.md
  app/konnect/configure/runtime-manager/runtime-instances/upgrade.md
  app/konnect/configure/runtime-manager/upgrade.md
  app/konnect/configure/servicehub/index.md
  app/konnect/configure/servicehub/manage-services.md
  app/konnect/configure/servicehub/plugins.md
Labels: review:tech, review:copyedit, ci:manual-approve:link-validation

#3794 Added note about a feature being PostreSQL-applicable only
  app/gateway/changelog.md
Labels: review:general

#3781 Konnect teams and roles
  app/_assets/images/icons/konnect/icn-organizations.svg
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/org-management/auth.md
  app/konnect/org-management/deactivation.md
  app/konnect/org-management/okta-idp.md
  app/konnect/org-management/roles-reference.md
  app/konnect/org-management/teams-and-roles.md
  app/konnect/org-management/teams-reference.md
  app/konnect/org-management/users-and-roles.md
  app/konnect/org-management/users.md
Labels: review:tech, review:copyedit, ci:manual-approve:link-validation

#3797 Fix spec_render_type typo in Portal docs
  app/gateway/2.7.x/developer-portal/theme-customization/alternate-openapi-renderer.md
  app/gateway/2.8.x/developer-portal/theme-customization/alternate-openapi-renderer.md
Labels: review:general

#3758 [DOCU-1109] Dev Portal: Improve delete workspace instructions
  app/enterprise/1.3-x/kong-manager/administration/workspaces/workspaces.md
  app/enterprise/1.5.x/kong-manager/administration/workspaces/workspaces.md
  app/enterprise/2.1.x/kong-manager/administration/workspaces/workspaces.md
  app/enterprise/2.2.x/kong-manager/administration/workspaces/workspaces.md
  app/enterprise/2.3.x/kong-manager/administration/workspaces/workspaces.md
  app/enterprise/2.4.x/kong-manager/administration/workspaces/workspaces.md
  app/enterprise/2.5.x/kong-manager/administration/workspaces/workspaces.md
  app/gateway/2.6.x/configure/auth/kong-manager/workspaces.md
  app/gateway/2.7.x/configure/auth/kong-manager/workspaces.md
  app/gateway/2.8.x/configure/auth/kong-manager/workspaces.md
Labels: review:general

#3800 Fix RBAC typo
  app/enterprise/0.31-x/plugins/rbac-api.md
  app/enterprise/0.32-x/plugins/rbac-api.md
  app/enterprise/0.33-x/rbac/admin-api.md
  app/enterprise/0.34-x/rbac/admin-api.md
  app/enterprise/0.35-x/admin-api/rbac/reference.md
  app/enterprise/0.36-x/admin-api/rbac/reference.md
  app/enterprise/1.3-x/admin-api/rbac/reference.md
  app/enterprise/1.5.x/admin-api/rbac/reference.md
  app/enterprise/2.1.x/admin-api/rbac/reference.md
  app/enterprise/2.2.x/admin-api/rbac/reference.md
  app/enterprise/2.3.x/admin-api/rbac/reference.md
  app/enterprise/2.4.x/admin-api/rbac/reference.md
  app/enterprise/2.5.x/admin-api/rbac/reference.md
  app/gateway/2.6.x/admin-api/rbac/reference.md
  app/gateway/2.7.x/admin-api/rbac/reference.md
  app/gateway/2.8.x/admin-api/rbac/reference.md
Labels: review:general

#3799 Fix upstream name
  app/gateway/2.6.x/get-started/comprehensive/load-balancing.md
  app/gateway/2.7.x/get-started/comprehensive/load-balancing.md
  app/gateway/2.8.x/get-started/comprehensive/load-balancing.md
  app/getting-started-guide/2.3.x/load-balancing.md
  app/getting-started-guide/2.4.x/load-balancing.md
  app/getting-started-guide/2.5.x/load-balancing.md
Labels: review:general

#3793 Konnect decK docs
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/configure/runtime-manager/runtime-groups/declarative-config.md
  app/konnect/deployment/import.md
  app/konnect/deployment/migrate.md
  app/konnect/dev-portal/applications/application-overview.md
  app/konnect/getting-started/index.md
  app/konnect/reference/declarative-config.md
Labels: review:tech, review:copyedit, ci:manual-approve:link-validation

#3798 Add konnect_icon helper
  app/_plugins/konnect_icon_tag.rb
Labels: review:tech

#3805 Fixing a typo
  app/gateway/2.8.x/developer-portal/helpers/cli.md
Labels: review:general
