Repository Kong/docs.konghq.com, pull requests merged in 2022-10, with the labels that each got.

#4550 [fix] Add admin claim
  src/gateway/kong-manager/auth/oidc/configure.md
Labels: review:general

#4552 [fix] Vale on modified files
  .github/workflows/linting.yml
Labels: review:general

#4555 [fix] mesh install icons
  app/mesh/1.1.x/install.md
  app/mesh/1.2.x/install.md
  app/mesh/1.3.x/install.md
  app/mesh/1.4.x/install.md
  app/mesh/1.5.x/install.md
  app/mesh/1.6.x/install.md
  src/mesh/install.md
Labels: review:general

#4554 Swap comma for semicolon in Zipkin plugin docs
  app/_hub/kong-inc/zipkin/_index.md
Labels: review:general

#4560 Remove konnect UI examples from route by header plugin
  app/_hub/kong-inc/route-by-header/_index.md
Labels: review:general

#4558 Removing OS part of image tag names
  src/gateway/install/docker/index.md
Labels: review:general

#4556 Add Incubator to top nav
  app/_includes/nav-v2.html
Labels: review:general

#4561 Get kong quickstart https
  src/gateway/get-started/index.md
  src/gateway/production/monitoring/prometheus.md
  src/gateway/production/monitoring/statsd.md
Labels: review:general

#4476 chore: Adds instruction to platform-install to install all deps
  docs/platform-install.md
Labels: review:tech

#4563 [DOCU-2259] Key auth encrypted plugin example fix
  app/_hub/kong-inc/key-auth-enc/_index.md
Labels: review:general

#4147 [DOCU-2380] Multi-geo support
  app/_data/docs_nav_konnect.yml
  app/konnect/account-management/index.md
  app/konnect/dev-portal/access.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/dev-portal/dev-reg.md
  app/konnect/getting-started/access-account.md
  app/konnect/getting-started/configure-service.md
  app/konnect/index.md
  app/konnect/org-management/teams-and-roles/index.md
  app/konnect/org-management/teams-and-roles/manage.md
  app/konnect/org-management/teams-and-roles/roles-reference.md
  app/konnect/org-management/teams-and-roles/teams-reference.md
  app/konnect/regions.md
  app/konnect/runtime-manager/manage-proxy-config.md
  app/konnect/servicehub/service-documentation.md
  src/deck/guides/konnect.md
Labels: review:copyedit

#4553 Update _index.md
  app/_hub/wallarm/wallarm/_index.md
Labels: pending:author

#4570 Prometheus: fix latency typo
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/prometheus/_index.md
Labels: review:general

#4571 Updated cli.md to show workspace tag
  src/gateway/kong-enterprise/dev-portal/cli.md
Labels: review:copyedit

#4471 Rework KongIngress documentation.
  .github/styles/kong/auto-ignore.txt
  src/kubernetes-ingress-controller/concepts/custom-resources.md
  src/kubernetes-ingress-controller/guides/using-kongingress-resource.md
  src/kubernetes-ingress-controller/references/custom-resources.md
Labels: review:general, review:copyedit, ci:check-skipped:generated-files

#4566 Clean up Cassandra deprecation notes
  app/_includes/md/enterprise/cassandra-deprecation.md
  app/_includes/md/gateway/setup.md
  src/gateway/get-started/quickstart/adding-consumers.md
  src/gateway/get-started/quickstart/configuring-a-service.md
  src/gateway/get-started/quickstart/enabling-plugins.md
  src/gateway/get-started/quickstart/index.md
  src/gateway/install/docker/index.md
  src/gateway/install/macos.md
  src/gateway/kong-enterprise/analytics/index.md
  src/gateway/kong-plugins/rate-limiting/algorithms/rate-limiting.md
  src/gateway/plugin-development/access-the-datastore.md
  src/gateway/plugin-development/custom-entities.md
  src/gateway/production/clustering.md
  src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
  src/gateway/production/deployment-topologies/traditional/index.md
Labels: review:general, review:copyedit

#4574 Use correct gatewayClass annotation in the guide
  src/kubernetes-ingress-controller/guides/using-gateway-api.md
Labels: review:copyedit

#4575 [Fix] plugin file-structure doc rendering issue
  src/gateway/plugin-development/file-structure.md
Labels: review:general

#4572 Multi-geo API updates
  app/konnect/network.md
Labels: review:general

#4576 Updated for quick start release notes
  app/konnect/updates.md
Labels: review:copyedit

#4568 fix: diverse typos in mesh getting started docs
  src/mesh/installation/amazonlinux.md
  src/mesh/installation/centos.md
  src/mesh/installation/debian.md
  src/mesh/installation/docker.md
  src/mesh/installation/ecs.md
  src/mesh/installation/helm.md
  src/mesh/installation/kubernetes.md
  src/mesh/installation/macos.md
  src/mesh/installation/openshift.md
  src/mesh/installation/redhat.md
  src/mesh/installation/ubuntu.md
  src/mesh/installation/windows.md
Labels: review:general

#4577 Add Org Admin (Read Only) Predefined Team
  app/konnect/updates.md
Labels: review:copyedit

#4582 Update okta.md
  src/gateway/kong-plugins/authentication/oidc/okta.md
Labels: review:general

#4334 feat(service-version): adjust docs [tdx-2281]
  app/konnect/dev-portal/index.md
  app/konnect/servicehub/service-versions.md
Labels: do not merge, review:general

#4587 chore(build): add specific ruby requirement check in Makefile
  Makefile
Labels: review:general

#4588 kic: remove alpha for Gateway API
  src/kubernetes-ingress-controller/concepts/gateway-api.md
  src/kubernetes-ingress-controller/guides/using-gateway-api.md
Labels: review:copyedit

#4583 add the dev portal september release notes
  app/konnect/updates.md
Labels: review:general

#4589 kic: add alpha banner for Gateway API support in KIC in v2.4 and v2.5
  src/kubernetes-ingress-controller/guides/using-gateway-api.md
  src/kubernetes-ingress-controller/references/gateway-api-support.md
Labels: review:copyedit

#4551 [plugin] Add amberflo.io api metering plugin
  .github/styles/kong/dictionary.txt
  .github/styles/kongplugins/dictionary.txt
  .github/styles/kongplugins/plugin-ignore.txt
  app/_assets/images/icons/hub/amberflo_kong-plugin-amberflo.png
  app/_hub/amberflo/kong-plugin-amberflo/_index.md
Labels: review:copyedit, review:sme

#4469 Release: Gateway 2.8.2.0
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#4592 Update release date for 2.8.2
  app/gateway/changelog.md
Labels: review:copyedit

#4573 fix(admin-api): removed consumers type field
  src/gateway/admin-api/index.md
Labels: review:general, ci:check-skipped:generated-files

#4595 Added changelog for FTI-2744 for 2.8.2.0
  app/gateway/changelog.md
Labels: review:copyedit

#4591 Update Sept Konnect release notes w/ doc links
  app/konnect/updates.md
Labels: review:copyedit

#4597 Konnect release note fixes
  app/konnect/updates.md
Labels: review:general

#4596 fix(admin-api): remove consumers type field from examples
  src/gateway/admin-api/index.md
Labels: review:general

#4593 pr/okta-oidc-doc-changes
  src/gateway/kong-plugins/authentication/oidc/okta.md
Labels: review:tech, review:sme

#4590 Update OIDC Okta plugin doc
  src/gateway/kong-plugins/authentication/oidc/okta.md
Labels: review:sme

#4598 Change Fail to Ignore on failurePolicy for Admission Controller
  src/kubernetes-ingress-controller/deployment/admission-webhook.md
Labels: review:general

#4600 [fix] Key-auth hybrid mode
  src/gateway/kong-enterprise/dev-portal/applications/auth-provider-strategy.md
Labels: review:copyedit

#4601 [fix] 2.7 changelog known issue
  app/gateway/changelog.md
Labels: review:general

#4606 2.8.2 changelog fixes
  app/gateway/changelog.md
Labels: review:general

#4607 renamed overview to summary including the markdown file name
  app/_data/docs_nav_konnect.yml
  app/konnect/analytics/index.md
  app/konnect/analytics/summary-dashboard.md
Labels: review:copyedit

#4599 feat(request-validator): support config.allowed_content_types to be configured with parameter
  app/_hub/kong-inc/request-validator/_index.md
Labels: review:general

#4404 Allow anonymous to be configured as the username of consumer
  .github/styles/kongplugins/auto-ignore.txt
  .github/styles/kongplugins/dictionary.txt
  app/_hub/kong-inc/basic-auth/_index.md
  app/_hub/kong-inc/hmac-auth/_index.md
  app/_hub/kong-inc/jwt/_index.md
  app/_hub/kong-inc/key-auth-enc/_index.md
  app/_hub/kong-inc/key-auth/_index.md
  app/_hub/kong-inc/ldap-auth-advanced/_index.md
  app/_hub/kong-inc/ldap-auth/_index.md
  app/_hub/kong-inc/mtls-auth/_index.md
  app/_hub/kong-inc/oauth2-introspection/_index.md
  app/_hub/kong-inc/oauth2/_index.md
  app/_hub/kong-inc/openid-connect/_index.md
  app/_hub/kong-inc/vault-auth/_index.md
Labels: review:general, review:copyedit

#4609 [DOCU-275] Validate and improve the Dev Portal enablement doc
  src/gateway/kong-enterprise/dev-portal/enable.md
  src/gateway/kong-manager/enable.md
Labels: review:copyedit

#4610 Remove version-index from pages in `src`
  app/_plugins/generators/single_source_generator.rb
  jekyll-dev.yml
  jekyll.yml
  src/gateway/install/docker/build-custom-images.md
  src/gateway/install/docker/index.md
  src/gateway/install/linux/amazon-linux.md
  src/gateway/install/linux/centos.md
  src/gateway/install/linux/debian.md
  src/gateway/install/linux/rhel.md
  src/gateway/install/linux/ubuntu.md
  src/gateway/kong-enterprise/analytics/influx-strategy.md
  src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Labels: review:tech

#4612 Fix anchor scroll behaviour
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/base.less
Labels: review:tech

#4617 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: review:general

#4618 Make root-user-note.md shown in important section
  app/_includes/md/gateway/root-user-note.md
Labels: review:general

#4615 Removed tlsv1 from postgress settings docs
  src/gateway/reference/configuration.md
Labels: review:copyedit

#4619 Add missing .important class in non-root user content
  app/_includes/md/gateway/root-user-note.md
Labels: review:general

#4621 Remove standard JS linter
  package-lock.json
  package.json
Labels: review:tech

#4620 [fix] regex description for routes
  src/gateway/how-kong-works/routing-traffic.md
Labels: review:copyedit

#4623 Add jekyll generator single source
  .github/workflows/build-docs-pdf.yml
  .github/workflows/build-plugin-pdf.yml
  .github/workflows/linting.yml
  .github/workflows/run-smoke-tests.yml
  Gemfile
  Gemfile.lock
  app/_plugins/blocks/kong_version_block.rb
  app/_plugins/generators/single_source_generator.rb
  jekyll-dev.yml
  jekyll.yml
Labels: review:general

#4625 Add Kong Gateway to Plugin Hub title
  app/_hub/index.html
Labels: review:general

#4557 [DOCU-2556] Streamlined Gateway Creation in Customer Cloud Provider
  .github/styles/kong/dictionary.txt
  app/_assets/images/icons/documentation/aws.svg
  app/_assets/images/icons/documentation/azure.svg
  app/_data/docs_nav_konnect.yml
  app/konnect/runtime-manager/index.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-aws.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-azure.md
  app/konnect/runtime-manager/runtime-instances/upgrade.md
Labels: review:copyedit

#4630 [DOCU-2514] Konnect latency analytics
  app/_assets/images/docs/konnect/konnect-analytics-latency.png
  app/_assets/images/docs/konnect/konnect-vitals-errors.png
  app/_assets/images/docs/konnect/konnect-vitals-traffic.png
  app/_data/docs_nav_konnect.yml
  app/konnect/analytics/index.md
  app/konnect/analytics/summary-dashboard.md
  app/konnect/analytics/troubleshoot.md
  app/konnect/runtime-manager/runtime-groups/dashboard.md
  app/konnect/updates.md
Labels: do not merge, review:copyedit, review:sme

#4631 [FTI-4272] add escape_path to route-transformer-adv plugin
  .github/styles/kongplugins/auto-ignore.txt
  app/_hub/kong-inc/route-transformer-advanced/_index.md
Labels: review:copyedit

#4632 Merge Konnect cloud provider runtime docs into main
  .github/styles/kong/dictionary.txt
  app/_assets/images/icons/documentation/aws.svg
  app/_assets/images/icons/documentation/azure.svg
  app/_data/docs_nav_konnect.yml
  app/konnect/runtime-manager/index.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-aws.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-azure.md
  app/konnect/runtime-manager/runtime-instances/upgrade.md
Labels: review:general

#4639 add link to guides for using gateway api in gettingstarted page
  src/kubernetes-ingress-controller/guides/getting-started.md
Labels: review:general, area/gateway-api

#4642 fix helm install command
  src/kubernetes-ingress-controller/deployment/k4k8s.md
Labels: ready, review:general

#4644 [DOCU-2495] Runtime instances updates for October
  app/_data/docs_nav_konnect.yml
  app/_data/tables/install_options_konnect.yml
  app/_includes/feature-table.html
  app/_includes/md/konnect/runtime-certs.md
  app/konnect/index.md
  app/konnect/runtime-manager/index.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-conf.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-docker.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-kubernetes.md
  app/konnect/runtime-manager/runtime-instances/index.md
  app/konnect/runtime-manager/runtime-instances/renew-certificates.md
  app/konnect/runtime-manager/runtime-instances/runtime-parameter-reference.md
  src/gateway/install/index.md
Labels: review:copyedit

#4636 [DOCU-2631] Update Mesh nav bar and move files
  .github/workflows/run-smoke-tests.yml
  app/_data/docs_nav_mesh_2.0.x.yml
  app/_plugins/kuma-specific/tabs/tabs.rb
  app/_plugins/kuma-specific/tip.rb
  app/_plugins/kuma-specific/warning.rb
  src/mesh/production/gateway/kic.md
  tests/seo.test.js
Labels: review:general

#4650 fix priority order
  src/gateway/plugin-development/custom-logic.md
Labels: review:copyedit

#4627 kic: add Gateway API mention in KIC's architecture design overview
  src/kubernetes-ingress-controller/concepts/design.md
  src/kubernetes-ingress-controller/concepts/gateway-api.md
  src/kubernetes-ingress-controller/guides/using-gateway-api.md
  src/kubernetes-ingress-controller/references/gateway-api-support.md
Labels: review:copyedit

#4649 doc(compat) add back RHEL 7.9
  app/_data/tables/compat.json
Labels: review:general

#4633 Add API documentation to Konnect
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/api/identity.yaml
  app/konnect/api/filtering.md
  app/konnect/api/identity-management/identity-integration.md
  app/konnect/api/index.md
  app/konnect/identity-management-api.md
Labels: review:general

#4655 Link to declarative config schema
  src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
Labels: review:general

#4659 Replace Kuma with Kong Mesh in titles
  app/_plugins/generators/kuma_to_kong_mesh.rb
Labels: review:general

#4663 kic: add Gateway API HTTPRoute traffic splitting
  app/_assets/kubernetes-ingress-controller/examples/echo-service.yaml
  app/_assets/kubernetes-ingress-controller/examples/echo-services.yaml
  src/kubernetes-ingress-controller/guides/using-gateway-api.md
Labels: review:copyedit, area/gateway-api

#4666 [DOCU-2595] decK upgrade guide: correct descriptions for sync, diff, validate
  src/deck/3.0-upgrade.md
Labels: review:copyedit

#4667 doc(kic) add plugin ordering config
  src/gateway/kong-enterprise/plugin-ordering/get-started.md
  src/kubernetes-ingress-controller/references/custom-resources.md
Labels: review:general, review:copyedit

#4678 Make Segment events more reliable
  app/_layouts/default.html
  gulpfile.js
  package-lock.json
  package.json
Labels: review:tech

#4677 doc(security) add notice on file read and write permission for kong
  app/_data/docs_nav_gateway_2.7.x.yml
  app/_data/docs_nav_gateway_2.8.x.yml
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_kic_2.6.x.yml
  src/gateway/reference/file-access-permissions.md
Labels: review:copyedit

#4665 mesh: change kds auth to use zone token
  app/mesh/changelog.md
  src/mesh/features/kds-auth.md
Labels: review:general

#4637 fix(kong-manager): add how RBAC rules work in Kong section
  app/gateway/2.6.x/configure/auth/rbac/index.md
  app/gateway/2.7.x/configure/auth/rbac/index.md
  app/gateway/2.8.x/configure/auth/rbac/index.md
  src/gateway/kong-manager/auth/rbac/index.md
Labels: review:copyedit
