Repository Kong/docs.konghq.com, pull requests merged in 2022-05, with the labels that each got.

#3898 Typo
  app/kubernetes-ingress-controller/2.3.x/index.md
Labels: review:copyedit

#3903 [DOCU-2302] Clean out mentions of old BasePlugin module
  src/gateway/plugin-development/custom-logic.md
  src/gateway/plugin-development/entities-cache.md
  src/gateway/plugin-development/plugin-configuration.md
Labels: review:tech

#3807 Add OSS/EE toggle in sidebar for install topics
  app/_assets/images/icons/icn-enterprise-black.svg
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/navtabs.less
  app/_assets/stylesheets/pages/docs.less
  app/_layouts/docs-v2.html
  app/_plugins/blocks/navtabs.rb
  app/contributing/markdown-rules.md
  app/gateway/2.8.x/install-and-run/amazon-linux.md
  app/gateway/2.8.x/install-and-run/centos.md
  app/gateway/2.8.x/install-and-run/debian.md
  app/gateway/2.8.x/install-and-run/docker.md
  app/gateway/2.8.x/install-and-run/index.md
  app/gateway/2.8.x/install-and-run/rhel.md
  app/gateway/2.8.x/install-and-run/ubuntu.md
Labels: review:tech

#3906 Update Plugin compatibility in Konnect and adjust badges
  app/_assets/images/icons/hub/kong-inc_kafka-upstream.png
  app/_assets/images/icons/hub/kong-inc_kong-terraform-aws.png
  app/_assets/images/icons/hub/okta_okta.png
  app/_assets/images/icons/hub/signal_sciences_signal-sciences.png
  app/_assets/images/icons/hub/wallarm_wallarm.png
  app/_assets/stylesheets/badges.less
  app/_assets/stylesheets/page.less
  app/_data/tables/plugin_index.yml
  app/_hub/index.html
  app/_hub/kong-inc/application-registration/_index.md
  app/_hub/kong-inc/degraphql/_index.md
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
  app/_hub/kong-inc/key-auth-enc/_index.md
  app/_includes/header.html
  app/_layouts/extension.html
  app/konnect-platform/compatibility/plugins.md
Labels: review:tech, review:copyedit

#3908 Update rhel.md
  app/gateway/2.8.x/install-and-run/rhel.md
Labels: review:general

#3909 Move mode badges to the beginning of list items
  app/gateway/2.8.x/index.md
Labels: review:general

#3910 Certificate PKI Mode TLSv3 extension
  app/gateway/2.6.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
  app/gateway/2.7.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
  app/gateway/2.8.x/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
Labels: review:general

#3912 Fix badge for new site
  README.md
Labels: review:general

#3919 Correcting RFC number used for JWK records
  app/_hub/kong-inc/openid-connect/_index.md
Labels: review:copyedit

#3915 Remove Konnect API doc from legacy section
  app/_data/docs_nav_konnect.yml
  app/_redirects
  archive/konnect/konnect-api.md
Labels: review:general

#3913 [DOCU-2244][DOCU-2251] Konnect CA certs
  app/_assets/images/docs/konnect/konnect-runtime-manager.png
  app/_includes/md/konnect/runtime-certs.md
  app/konnect/configure/runtime-manager/runtime-instances/gateway-runtime-conf.md
  app/konnect/configure/runtime-manager/runtime-instances/gateway-runtime-docker.md
  app/konnect/configure/runtime-manager/runtime-instances/gateway-runtime-kubernetes.md
  app/konnect/configure/runtime-manager/runtime-instances/renew-certificates.md
  app/konnect/configure/runtime-manager/runtime-instances/runtime-parameter-reference.md
Labels: review:general

#3924 Kong Manager Session: Add missing commas to JSON configuration object
  app/gateway/2.8.x/configure/auth/kong-manager/sessions.md
Labels: review:general

#3922 Update KIC upgrade instructions for 2.x
  app/kubernetes-ingress-controller/2.2.x/guides/upgrade.md
  app/kubernetes-ingress-controller/2.3.x/guides/upgrade.md
Labels: review:copyedit

#3926 [fix] Plugins in other languages doc - Broken link
  app/gateway/2.8.x/reference/external-plugins.md
Labels: review:general

#3933 Fix variables in plugin development guides
  app/gateway/2.6.x/plugin-development/custom-logic.md
  app/gateway/2.7.x/plugin-development/custom-logic.md
  app/gateway/2.8.x/plugin-development/custom-logic.md
Labels: review:general

#3934 Konnect compatibility badges and filter
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/badges.less
  app/_assets/stylesheets/page.less
  app/_hub/index.html
  app/_includes/header.html
  app/_includes/hub_cards.html
  app/_layouts/docs-v2.html
  app/_layouts/extension.html
Labels: review:tech, review:general

#3935 Add Contact Sales to Enterprise tooltip
  app/_assets/javascripts/app.js
Labels: review:general

#3932 Remove deprecated blacklist/whitelist params and single-source plugins
  app/_hub/kong-inc/acl/0.1-x.md
  app/_hub/kong-inc/acl/_index.md
  app/_hub/kong-inc/acl/versions.yml
  app/_hub/kong-inc/bot-detection/0.1-x.md
  app/_hub/kong-inc/bot-detection/_index.md
  app/_hub/kong-inc/bot-detection/versions.yml
  app/_hub/kong-inc/ip-restriction/0.1-x.md
  app/_hub/kong-inc/ip-restriction/1.0-x.md
  app/_hub/kong-inc/ip-restriction/2.0.x.md
  app/_hub/kong-inc/ip-restriction/_index.md
  app/_hub/kong-inc/ip-restriction/versions.yml
  app/_layouts/extension.html
Labels: review:tech

#3914 [DOCU-2273] Troubleshoot runtime instances
  app/_data/docs_nav_konnect.yml
  app/konnect/configure/runtime-manager/runtime-instances/troubleshoot.md
  app/konnect/deployment/license-management.md
Labels: review:copyedit

#3937 Konnect ServiceHub, Runtime Manager, and action labels updates
  app/_data/docs_nav_konnect.yml
  app/_includes/md/konnect/create-service.md
  app/_includes/md/konnect/docker-runtime.md
  app/_includes/md/konnect/implement-service.md
  app/_includes/md/konnect/runtime-certs.md
  app/_includes/md/konnect/service-version.md
  app/konnect/configure/runtime-manager/runtime-groups/declarative-config.md
  app/konnect/configure/runtime-manager/runtime-groups/index.md
  app/konnect/configure/runtime-manager/runtime-groups/manage-entities.md
  app/konnect/configure/runtime-manager/runtime-groups/manage.md
  app/konnect/configure/runtime-manager/runtime-groups/use-case.md
  app/konnect/configure/runtime-manager/runtime-instances/gateway-runtime-docker.md
  app/konnect/configure/runtime-manager/runtime-instances/renew-certificates.md
  app/konnect/configure/runtime-manager/runtime-instances/upgrade.md
  app/konnect/configure/servicehub/enable-route-plugin.md
  app/konnect/configure/servicehub/enable-service-plugin.md
  app/konnect/configure/servicehub/index.md
  app/konnect/configure/servicehub/manage-services.md
  app/konnect/configure/servicehub/plugins.md
  app/konnect/deployment/import.md
  app/konnect/deployment/network-resiliency.md
  app/konnect/dev-portal/applications/disable-app-reg.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/dev-portal/customization/index.md
  app/konnect/dev-portal/publish.md
  app/konnect/dev-portal/service-documentation.md
  app/konnect/getting-started/configure-service.md
  app/konnect/getting-started/index.md
  app/konnect/getting-started/publish-service.md
  app/konnect/getting-started/spec/app-registration.md
  app/konnect/getting-started/spec/service.md
  app/konnect/index.md
  app/konnect/org-management/roles-reference.md
  app/konnect/org-management/teams-and-roles.md
  app/konnect/vitals/analyze.md
  app/konnect/vitals/generate-reports.md
  app/konnect/vitals/index.md
Labels: review:copyedit

#3946 Improve the overall readability by altering punctuations, articles and typos.
  README.md
Labels: review:general

#3944 [ENGEN-450] Chore(debian 8): add deprecations of Debian 8 "Jessie"
  .github/workflows/check-links.yml
  app/_includes/md/deb.md
  src/gateway/install-and-run/debian.md
Labels: review:general

#3936 Update decK version to 1.12.1
  app/_data/kong_versions.yml
Labels: review:general

#3948 Improves the Configuring a Service Quickstart page
  app/gateway/2.8.x/get-started/quickstart/configuring-a-service.md
Labels: review:general

#3949 Open badge links in new tab/page
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/badges.less
  app/_assets/stylesheets/base.less
  app/_includes/header.html
  app/_layouts/docs-v2.html
  app/contributing/markdown-rules.md
Labels: review:general

#3950 Improves the getting started comprehensive guide, expose services page
  app/gateway/2.8.x/get-started/comprehensive/expose-services.md
Labels: review:general

#3961 Fix margins when promo banner is active
  app/_assets/stylesheets/header.less
Labels: review:general

#3957 Ignore netlify test directory
  .gitignore
Labels: review:tech

#3956 Fix "edit this page" links
  app/_layouts/docs-v2.html
Labels: review:tech, review:general

#3959 [DOCU-846] Add service name as an option to route config.service description
  app/enterprise/2.1.x/admin-api/index.md
  app/enterprise/2.2.x/admin-api/index.md
  app/enterprise/2.3.x/admin-api/index.md
  app/enterprise/2.4.x/admin-api/index.md
  app/enterprise/2.5.x/admin-api/index.md
Labels: review:general

#3951 Generate 2.8.x conf for dev portal updates
  app/gateway/2.8.x/reference/configuration.md
Labels: review:general, ci:check-skipped:generated-files

#3751 WIP [DOCU-2126] rm duplicate ref
  app/gateway/2.8.x/developer-portal/administration/managing-developers.md
  app/gateway/2.8.x/developer-portal/configuration/smtp.md
Labels: pr/wip, review:general

#3971 [DOCU-2352] Document forward proxy fallback behavior
  app/_hub/kong-inc/forward-proxy/_index.md
Labels: review:copyedit

#3972 [DOCU-2353] mTLS auth plugin: proxy host and port parameters
  app/_hub/kong-inc/mtls-auth/_index.md
Labels: review:tech, review:copyedit

#3973 [DOCU-2354] Kafka scram-sha-512 support
  app/_hub/kong-inc/kafka-log/_index.md
  app/_hub/kong-inc/kafka-upstream/_index.md
Labels: review:tech, review:copyedit

#3966 [ENGEN-453] chore(amzn) add amazon linux 1 deprecate notice
  src/gateway/install-and-run/amazon-linux.md
Labels: review:general

#3955 Gateway nav improvements
  app/_data/docs_nav_gateway_2.8.x.yml
  tests/sidebar.test.js
Labels: review:general

#3865 chore/remove config cache
  src/gateway/plan-and-deploy/hybrid-mode/hybrid-mode-setup.md
  src/gateway/plan-and-deploy/hybrid-mode/index.md
  src/gateway/reference/configuration.md
Labels: review:general, review:copyedit

#3978 Fix changelog typo
  app/gateway/changelog.md
Labels: review:general

#3981 [ENGEN-451] chore(xenial) 👋
  app/_includes/md/deb.md
  src/gateway/install-and-run/ubuntu.md
Labels: review:general

#3967 Fix PDF Generation for plugins + docs
  pdf-generation/create-pdf.js
  pdf-generation/list-plugins.js
Labels: review:tech

#3958 Add generated path to conflict warning for single sourced documents
  app/_plugins/generators/latest_version_generator.rb
  app/_plugins/generators/single_source_generator.rb
  app/_plugins/generators/versions.rb
Labels: review:tech

#3985 [FTI-4021]add explanation for valid value range of key's ttl in key-auth plugin
  app/_hub/kong-inc/key-auth/_index.md
Labels: review:tech

#3983 Update algolia config
  algolia/config-full-docs.json
Labels: review:general

#3982 [Fix] data.lua link syntax
  app/gateway/2.8.x/reference/configuration.md
  autodoc-conf-ee/data.lua
Labels: Core Team review, review:general
