Repository Kong/docs.konghq.com, pull requests merged in 2023-09, with the labels that each got.

#6056 Fix "supported-router-flavors" typos.
  app/_src/kubernetes-ingress-controller/references/supported-router-flavors.md
Labels: review:general

#6058 Fix YAML assets
  jekyll-dev.yml
  jekyll.yml
Labels: review:tech

#6050 add konnect and update version compatibility
  app/_hub/salt/salt/_metadata.yml
Labels: review:general

#6059 Fix(plugin scopes): Consumer groups scope and application registration plugin
  app/_plugins/generators/plugin_single_source/plugin/schemas/base.rb
  app/hub/plugins/compatibility/index.md
Labels: review:general

#6060 fix: Partial revert of plugin scopes changes
  app/_plugins/generators/plugin_single_source/plugin/schemas/base.rb
Labels: review:general, skip-changelog

#6057 (fix) remove note about cloud launcher support
  app/konnect/runtime-manager/runtime-instances/upgrade.md
Labels: review:general

#6066 update urls to latest and remove mention of dev portal
  app/_src/gateway/admin-api/index.md
  app/konnect/api/index.md
Labels: review:general, skip-changelog

#5880 feat: Guide for using the HTTP Log plugin with Splunk
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/http-log/how-to/_splunk.md
  app/_hub/kong-inc/http-log/overview/_index.md
  app/_hub/kong-inc/http-log/overview/_log-format.md
  app/_hub/kong-inc/http-log/overview/_using-custom-fields.md
  app/_includes/md/plugins-hub/kong-process-errors.md
  app/_includes/md/plugins-hub/log_custom_fields_by_lua.md
Labels: review:copyedit

#6067 Post-launch tidy of Konnect API overview page + nav
  app/_data/docs_nav_konnect.yml
  app/konnect/api/index.md
Labels: review:general, skip-changelog

#6072 fix: Algolia config for specs landing page
  .github/workflows/algolia.yml
  algolia/config-full-docs.json
  algolia/old-configs/config-deck.json
  algolia/old-configs/config-kic.json
  algolia/old-configs/config-konnect.json
  algolia/old-configs/config-mesh.json
  app/_layouts/oas/index.html
Labels: review:general, skip-changelog

#6073 chore: Split the gateway changelogs to archive changelogs for sunset versions
  algolia/config-full-docs.json
  app/gateway/changelog.md
Labels: review:general, skip-changelog

#6081 [Fix]- KIC: Setting up Active and Passive health checks guide
  app/_includes/md/kic/installation.md
  app/_src/kubernetes-ingress-controller/guides/configuring-health-checks.md
Labels: review:general

#6084 Update Konnect modal
  app/_assets/javascripts/modal.js
  app/_assets/stylesheets/modal.less
  app/_layouts/docs-v2.html
Labels: review:general

#6068 fix: remove unsupported KIC feature
  app/_data/docs_nav_kic_2.0.x.yml
  app/_data/docs_nav_kic_2.1.x.yml
  app/_data/docs_nav_kic_2.10.x.yml
  app/_data/docs_nav_kic_2.11.x.yml
  app/_data/docs_nav_kic_2.2.x.yml
  app/_data/docs_nav_kic_2.3.x.yml
  app/_data/docs_nav_kic_2.4.x.yml
  app/_data/docs_nav_kic_2.5.x.yml
  app/_data/docs_nav_kic_2.6.x.yml
  app/_data/docs_nav_kic_2.7.x.yml
  app/_data/docs_nav_kic_2.8.x.yml
  app/_data/docs_nav_kic_2.9.x.yml
  app/_src/kubernetes-ingress-controller/guides/configuring-custom-entities.md
  app/kubernetes-ingress-controller/2.0.x/guides/configuring-custom-entities.md
  app/kubernetes-ingress-controller/2.1.x/guides/configuring-custom-entities.md
  app/kubernetes-ingress-controller/2.2.x/guides/configuring-custom-entities.md
Labels: review:general

#6085 Copy example .env when running make install
  Makefile
Labels: review:tech

#6063 Update vale to use the default dictionary with plugins docs
  .github/styles/kong/First-person.yml
  .github/styles/kong/We.yml
  .github/styles/kongplugins/Pluginspelling.yml
  .github/styles/kongplugins/auto-ignore.txt
  .github/styles/kongplugins/dictionary.txt
  .github/styles/kongplugins/plugin-ignore.txt
  .vale.ini
Labels: review:general, skip-changelog

#6082 Add prerequisite install include for KIC
  app/_includes/md/kic/prerequisites.md
  app/_src/kubernetes-ingress-controller/guides/configuring-health-checks.md
Labels: review:general

#6075 fix missing keyword config in curl data
  app/_hub/kong-inc/grpc-web/how-to/_index.md
Labels: review:copyedit

#6071 Rename Runtime Manager + update related terms
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/account-management/index.md
  app/konnect/analytics/index.md
  app/konnect/analytics/troubleshoot.md
  app/konnect/api-products/index.md
  app/konnect/api/index.md
  app/konnect/api/runtime-groups-config/index.md
  app/konnect/architecture.md
  app/konnect/dev-portal/access-and-approval/manage-teams.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/gateway-manager/backup-restore.md
  app/konnect/gateway-manager/configuration/consumer-groups.md
  app/konnect/gateway-manager/configuration/index.md
  app/konnect/gateway-manager/configuration/vaults/how-to.md
  app/konnect/gateway-manager/configuration/vaults/index.md
  app/konnect/gateway-manager/control-plane-groups/conflicts.md
  app/konnect/gateway-manager/control-plane-groups/how-to.md
  app/konnect/gateway-manager/control-plane-groups/index.md
  app/konnect/gateway-manager/control-plane-groups/migrate.md
  app/konnect/gateway-manager/data-plane-nodes/custom-dp-labels.md
  app/konnect/gateway-manager/data-plane-nodes/index.md
  app/konnect/gateway-manager/data-plane-nodes/parameter-reference.md
  app/konnect/gateway-manager/data-plane-nodes/renew-certificates.md
  app/konnect/gateway-manager/data-plane-nodes/upgrade.md
  app/konnect/gateway-manager/data-plane-nodes/verify-node.md
  app/konnect/gateway-manager/declarative-config.md
  app/konnect/gateway-manager/enable-route-plugin.md
  app/konnect/gateway-manager/enable-service-plugin.md
  app/konnect/gateway-manager/index.md
  app/konnect/gateway-manager/kic.md
  app/konnect/gateway-manager/plugins.md
  app/konnect/gateway-manager/troubleshoot.md
  app/konnect/gateway-manager/version-compatibility.md
  app/konnect/getting-started/configure-data-plane-node.md
  app/konnect/getting-started/deploy-service.md
  app/konnect/getting-started/import.md
  app/konnect/getting-started/productize-service.md
  app/konnect/index.md
  app/konnect/network-resiliency.md
  app/konnect/network.md
  app/konnect/org-management/deactivation.md
  app/konnect/org-management/teams-and-roles/roles-reference.md
  app/konnect/org-management/teams-and-roles/teams-reference.md
  app/konnect/reference/labels.md
  app/konnect/updates.md
  app/konnect/upgrade-faq.md
Labels: do not merge, review:copyedit

#6089 Update health-checks.md
  app/_src/gateway/how-kong-works/health-checks.md
Labels: review:copyedit

#6090 Update _index.md - GraphQL Introspection endpoint related note.
  app/_hub/kong-inc/graphql-rate-limiting-advanced/overview/_index.md
Labels: review:tech

#6074 [Fix] KIC: Allowing Multiple Authentication Methods
  app/_src/kubernetes-ingress-controller/guides/allowing-multiple-authentication-methods.md
Labels: review:general

#6030 Update installation options for Runtime Instances
  app/assets/images/docs/konnect/konnect-install-options.png
  app/konnect/gateway-manager/data-plane-nodes/index.md
Labels: review:general

#6100 feat: Add Mesh Manager tile to the docs landing page
  app/_data/landing_page.yml
  app/assets/images/landing-page/card-icons/mesh-manager.svg
Labels: review:general

#6105 changed the incorrect port number given in the docs for kic/using-external-service
  app/_includes/md/kic/http-test-routing-resource.md
  app/_src/kubernetes-ingress-controller/guides/using-external-service.md
Labels: review:general

#6106 Fix: Konnect nav duplicate entry
  app/_data/docs_nav_konnect.yml
  app/_redirects
Labels: review:general

#6102 fix(docs): Correct the influxdb flush frequency
  app/_src/gateway/kong-enterprise/analytics/influx-strategy.md
Labels: review:tech, review:general

#6083 Add tag descriptions to OSS and EE admin APIs
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
Labels: do not merge, review:general, skip-changelog

#6091 Update: New konnect diagrams for rename
  app/assets/images/docs/konnect/konnect-composite-rg.svg
  app/assets/images/docs/konnect/konnect-control-plane-group.svg
  app/assets/images/docs/konnect/konnect-control-plane.svg
  app/assets/images/docs/konnect/konnect-control-planes-example.png
  app/assets/images/docs/konnect/konnect-intro.png
  app/assets/images/docs/konnect/konnect-runtime-groups-example.png
  app/assets/images/docs/konnect/konnect-shared-conf-overview.png
  app/assets/images/docs/konnect/konnect-shared-config.png
  app/assets/images/docs/konnect/konnect-standard-rg.svg
  app/konnect/gateway-manager/control-plane-groups/index.md
  app/konnect/gateway-manager/index.md
Labels: review:general, ci:manual-approve:link-validation

#6069 Revise KIC rate-limiting guide to use Secrets Management
  app/_data/docs_nav_kic_2.11.x.yml
  app/_src/kubernetes-ingress-controller/guides/redis-rate-limiting.md
Labels: review:tech, review:general, review:copyedit

#6107 Great Rename: Screenshots
  app/assets/images/docs/konnect/api-products/api-products-overview.png
  app/assets/images/docs/konnect/custom-reports/latency/kong-latency.png
  app/assets/images/docs/konnect/custom-reports/latency/upstream-latency.png
  app/assets/images/docs/konnect/dashboard/konnect-dashboard.png
  app/assets/images/docs/konnect/konnect-runtime-instance-kic.png
  app/assets/images/docs/konnect/konnect-vaults.png
  app/konnect/gateway-manager/configuration/vaults/index.md
  tools/screenshots/api-products/api-products-dashboard.yaml
  tools/screenshots/macros.yaml
  tools/screenshots/overview/konnect-dashboard.yaml
  tools/screenshots/runtimes/kic.yaml
  tools/screenshots/vaults/overview.yaml
Labels: review:general

#6064 Clarify and improve DP Resilience feature notes
  app/_src/gateway/kong-enterprise/cp-outage-handling.md
Labels: review:general, review:sme

#6114 Add change notice
  app/konnect/org-management/audit-logging/reference.md
Labels: review:copyedit

#5947 chore: Add 3.2.2.4 changelog
  app/_src/gateway/breaking-changes/32x.md
  app/gateway/changelog.md
Labels: review:copyedit, pending:release

#6112 Update API urls to match rename changes
  app/_src/gateway/admin-api/admin-api-3.1.x.md
  app/_src/gateway/admin-api/index.md
  app/konnect/api/identity-management/identity-integration.md
  app/konnect/api/runtime-groups-config/index.md
  app/konnect/dev-portal/access-and-approval/manage-teams.md
  app/konnect/gateway-manager/control-plane-groups/how-to.md
  app/konnect/gateway-manager/control-plane-groups/migrate.md
  app/konnect/gateway-manager/data-plane-nodes/custom-dp-labels.md
  app/konnect/gateway-manager/data-plane-nodes/renew-certificates.md
  app/konnect/org-management/system-accounts.md
Labels: review:general

#6118 [fix] Exposing a TCP Service
  app/_src/kubernetes-ingress-controller/guides/using-tcpingress.md
  app/_src/kubernetes-ingress-controller/guides/using-udpingress.md
  app/assets/kubernetes-ingress-controller/examples/echo-service.yaml
Labels: review:tech

#6129 Chore: re-retire handwritten markdown documentation
  app/_data/docs_nav_konnect.yml
Labels: review:general

#6130 Remove script
  app/_includes/head.html
Labels: review:general

#6103 fix(docs): correct the influxdb - gateway startup order
  app/_src/gateway/kong-enterprise/analytics/influx-strategy.md
Labels: review:general

#6123 Update: Rename runtime-groups in decK and bump version
  app/_data/docs_nav_deck_1.26.x.yml
  app/_data/docs_nav_deck_1.27.x.yml
  app/_data/kong_versions.yml
  app/_includes/md/deck-global-flags.md
  app/_src/deck/3.0-upgrade.md
  app/_src/deck/guides/konnect.md
  app/_src/deck/reference/deck.md
  app/_src/deck/reference/deck_completion.md
  app/_src/deck/reference/deck_convert.md
  app/_src/deck/reference/deck_diff.md
  app/_src/deck/reference/deck_dump.md
  app/_src/deck/reference/deck_file.md
  app/_src/deck/reference/deck_file_add-plugins.md
  app/_src/deck/reference/deck_file_add-tags.md
  app/_src/deck/reference/deck_file_list-tags.md
  app/_src/deck/reference/deck_file_merge.md
  app/_src/deck/reference/deck_file_openapi2kong.md
  app/_src/deck/reference/deck_file_patch.md
  app/_src/deck/reference/deck_file_remove-tags.md
  app/_src/deck/reference/deck_file_render.md
  app/_src/deck/reference/deck_konnect.md
  app/_src/deck/reference/deck_konnect_diff.md
  app/_src/deck/reference/deck_konnect_dump.md
  app/_src/deck/reference/deck_konnect_ping.md
  app/_src/deck/reference/deck_konnect_sync.md
  app/_src/deck/reference/deck_ping.md
  app/_src/deck/reference/deck_reset.md
  app/_src/deck/reference/deck_sync.md
  app/_src/deck/reference/deck_validate.md
  app/_src/deck/reference/deck_version.md
  app/konnect/gateway-manager/backup-restore.md
  app/konnect/gateway-manager/control-plane-groups/migrate.md
  app/konnect/gateway-manager/declarative-config.md
Labels: review:general, review:copyedit, ci:check-skipped:generated-files

#6132 Rename: changelog
  app/konnect/updates.md
Labels: review:general

#6131 Konnect Rename: Adds Control Plane Config API spec
  api-specs/Konnect/control-planes-config/control-planes-config.json
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
  app/_api/konnect/control-plane-configuration/_index.md
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_oas_data.json
  app/konnect/api/index.md
Labels: review:general

#6133 Identity API v2 -> v3 changes
  app/_data/konnect_oas_data.json
Labels: review:general

#6135 add control planes v2 api to Konnect Great rename branch
  app/_api/konnect/control-planes/_index.md
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_oas_data.json
Labels: review:general

#6137 Rename: deprecated API specs section
  app/_data/docs_nav_konnect.yml
Labels: review:general

#6138 chore: Vale cleanup for konnect rename branch
  .github/styles/kong/Terms.yml
  .github/styles/kong/dictionary.txt
  app/konnect/api/identity-management/identity-integration.md
Labels: review:general

#6136 chore: Generate new gateway manager screenshot
  app/assets/images/docs/konnect/konnect-control-plane-dashboard.png
  app/assets/images/docs/konnect/konnect-runtime-manager-dashboard.png
  app/konnect/gateway-manager/index.md
  tools/screenshots/README.md
  tools/screenshots/overview/control-plane-dashboard.yaml
  tools/screenshots/overview/runtime-manager-dashboard.yaml
  tools/screenshots/runtimes/runtime-dashboard.yaml
Labels: review:general, ci:manual-approve:link-validation

#6139 Chore: Changelog fix
  app/konnect/updates.md
Labels: review:copyedit

#6145 chore: Sync Konnect OAS Data
  app/_data/konnect_oas_data.json
Labels: review:general, skip-changelog

#6147 Add deprecated to Runtime groups API
  app/_data/konnect_oas_data.json
Labels: review:general

#6142 Update webhook.md
  app/konnect/org-management/audit-logging/webhook.md
Labels: review:tech

#6149 chore: Remove link to KIC guide that doesn't exist
  app/_redirects
  app/_src/kubernetes-ingress-controller/guides/overview.md
  app/kubernetes-ingress-controller/1.0.x/guides/overview.md
  app/kubernetes-ingress-controller/1.1.x/guides/overview.md
  app/kubernetes-ingress-controller/1.2.x/guides/overview.md
  app/kubernetes-ingress-controller/1.3.x/guides/overview.md
  app/kubernetes-ingress-controller/2.0.x/guides/overview.md
  app/kubernetes-ingress-controller/2.1.x/guides/overview.md
  app/kubernetes-ingress-controller/2.2.x/guides/overview.md
Labels: review:general, skip-changelog

#6150 update insomnia link
  app/konnect/api/index.md
Labels: review:general, skip-changelog

#6151 Fix: alphabetize the specs in the nav
  app/_data/docs_nav_konnect.yml
Labels: review:general, skip-changelog

#6126 fix(dcr): add note about v1 endpoints
  app/konnect/dev-portal/applications/dynamic-client-registration/azure.md
Labels: review:general

#6119 Update: Add note about group filtering to Konnect SSO
  app/konnect/org-management/oidc-idp.md
Labels: review:general, review:copyedit

#6115 feat: Add note about MinK system accounts
  app/konnect/mesh-manager/service-mesh.md
  app/konnect/org-management/system-accounts.md
Labels: review:copyedit

#6153 fix: Layout issues with menus
  app/_assets/javascripts/views/SpecView.vue
  app/_assets/stylesheets/header-v2.less
  app/_assets/stylesheets/page.less
  app/_includes/nav-v2.html
Labels: review:general

#6157 fix: Rename runtime group id to control plane id
  app/_hub/kong-inc/jq/overview/_index.md
  app/_plugins/drops/plugins/examples/curl.rb
  app/_plugins/drops/plugins/examples/konnect.rb
  spec/app/_plugins/drops/plugins/examples/curl_spec.rb
Labels: review:general, skip-changelog

#6158 Fix: Mobile top nav
  app/_assets/stylesheets/header-v2.less
Labels: review:general, skip-changelog

#6162 fix: Replace Gateway API spec characters causing errors
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
Labels: review:general, skip-changelog

#6127 fix: Exposing UDP service
  app/_src/kubernetes-ingress-controller/guides/using-tcpingress.md
  app/_src/kubernetes-ingress-controller/guides/using-udpingress.md
Labels: review:general, skip-changelog

#6110 fix: Using Redis for rate limiting
  app/_includes/md/kic/http-test-routing.md
  app/_includes/md/kic/prerequisites.md
  app/_src/kubernetes-ingress-controller/guides/redis-rate-limiting.md
Labels: review:general, skip-changelog

#6167 Automated Changelog update
  changelog.md
Labels: review:copyedit, skip-changelog

#6171 update API specs to remove debug endpoint [skip ci]
  api-specs/Konnect/control-planes-config/control-planes-config.json
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
Labels: review:general, skip-changelog

#6122 feat: Mesh in Konnect changelog
  app/konnect/updates.md
Labels: review:copyedit, skip-changelog

#6128 feat: Mesh Manager API specs
  app/_api/konnect/mesh-manager/_index.md
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_oas_data.json
Labels: do not merge, review:general, review:sme

#6159 feat: MinK zone consumption billing notes
  app/konnect/getting-started/configure-mesh.md
  app/konnect/mesh-manager/service-mesh.md
Labels: review:copyedit

#6161 Social Login and Org Switcher
  app/_data/docs_nav_konnect.yml
  app/konnect/getting-started/access-account.md
  app/konnect/org-management/auth.md
  app/konnect/org-management/org-switcher.md
  app/konnect/org-management/social-identity-login.md
  app/konnect/updates.md
Labels: review:copyedit, pending:release

#6113 feat: Add Mesh Manager RBAC page
  app/konnect/mesh-manager/index.md
Labels: review:copyedit

#6172 Change control plane spec v1 -> v2 [skip-ci]
  app/_data/konnect_oas_data.json
Labels: review:general, skip-changelog

#6104 feat(api-requests): added api requests beta to docs
  app/_api/konnect/api-requests/_index.md
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_oas_data.json
  app/assets/images/docs/konnect/konnect-analytics-api-requests.png
  app/konnect/analytics/api-requests.md
  app/konnect/updates.md
Labels: do not merge, review:copyedit, pending:release

#6096 doc(portal): add documentation for auth0 dcr metadata TDX-3342
  app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
  app/konnect/updates.md
Labels: review:general, review:copyedit, pending:release

#6178 Feat: Changelog for konnect custom plugin management
  app/konnect/updates.md
Labels: review:copyedit

#5704 feat: MinK GA release
  .github/styles/kong/dictionary.txt
  app/_api/konnect/mesh-manager/_index.md
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_oas_data.json
  app/_data/landing_page.yml
  app/assets/images/diagrams/diagram-mesh-in-konnect.png
  app/assets/images/docs/konnect/konnect-intro.png
  app/assets/images/docs/konnect/konnect-mesh-control-plane-dashboard.png
  app/assets/images/icons/konnect/icn-mesh-manager-nav.svg
  app/assets/images/icons/konnect/icn-mesh-manager.svg
  app/assets/images/landing-page/card-icons/mesh-manager.svg
  app/konnect/compatibility.md
  app/konnect/index.md
  app/konnect/mesh-manager/index.md
  app/konnect/mesh-manager/service-mesh.md
  app/konnect/network-resiliency.md
  app/konnect/network.md
  app/konnect/org-management/deactivation.md
  app/konnect/org-management/system-accounts.md
  app/konnect/org-management/teams-and-roles/manage.md
  app/konnect/org-management/teams-and-roles/roles-reference.md
  app/konnect/reference/labels.md
  app/konnect/updates.md
Labels: do not merge, pending:release

#6141 fix: Expose an external application
  app/_includes/md/kic/http-test-routing-resource.md
  app/_src/kubernetes-ingress-controller/guides/using-external-service.md
Labels: review:general, skip-changelog

#6144 Add Kong Gateway Operator docs
  .github/styles/kong/dictionary.txt
  app/_assets/stylesheets/page.less
  app/_data/docs_nav_kgo_1.0.x.yml
  app/_data/docs_top_nav.yml
  app/_data/kong_versions.yml
  app/_data/landing_page.yml
  app/_includes/breadcrumbs.html
  app/_includes/docs-sidebar.html
  app/_includes/snippets/gateway-operator/install_with_kubectl.md
  app/_includes/snippets/gateway-operator/install_with_kubectl_all_controllers.md
  app/_layouts/docs-v2.html
  app/_plugins/generators/latest_version_generator.rb
  app/_plugins/generators/versions.rb
  app/_src/gateway-operator/concepts/gateway-api.md
  app/_src/gateway-operator/concepts/gateway-configuration.md
  app/_src/gateway-operator/customization/data-plane-image.md
  app/_src/gateway-operator/customization/pod-template-spec.md
  app/_src/gateway-operator/customization/sidecars.md
  app/_src/gateway-operator/faq.md
  app/_src/gateway-operator/get-started/kic/create-gateway.md
  app/_src/gateway-operator/get-started/kic/create-route.md
  app/_src/gateway-operator/get-started/kic/install.md
  app/_src/gateway-operator/get-started/konnect/create-route.md
  app/_src/gateway-operator/get-started/konnect/deploy-data-plane.md
  app/_src/gateway-operator/get-started/konnect/install.md
  app/_src/gateway-operator/index.md
  app/_src/gateway-operator/install.md
  app/_src/gateway-operator/production/index.md
  app/_src/gateway-operator/production/monitoring.md
  app/_src/gateway-operator/production/upgrade/data-plane/blue-green.md
  app/_src/gateway-operator/production/upgrade/data-plane/rolling.md
  app/_src/gateway-operator/production/upgrade/gateway-operator.md
  app/_src/gateway-operator/reference/custom-resources/index.md
  app/_src/gateway-operator/reference/license.md
  app/_src/gateway-operator/support.md
  app/_src/gateway-operator/topologies/dbless.md
  app/_src/gateway-operator/topologies/hybrid.md
  app/assets/gateway-operator/v1.0.0/all_controllers.yaml
  app/assets/gateway-operator/v1.0.0/crds.yaml
  app/assets/gateway-operator/v1.0.0/default.yaml
  app/breadcrumb_titles.yml
  app/gateway-operator/changelog.md
  jekyll-dev.yml
  jekyll.yml
  tools/_utilities/lib/nav-to-index-page.js
Labels: do not merge, review:general, review:copyedit, review:sme

#6184 Update tech preview/beta terminology to be Konnect friendly
  app/_includes/md/availability-stages.md
  app/_layouts/docs-v2.html
Labels: review:general

#6185 fix: Configuring https redirect
  app/_src/kubernetes-ingress-controller/guides/configuring-https-redirect.md
Labels: review:tech, skip-changelog

#6188 chore: Update kong_versions.yml
  app/_data/kong_versions.yml
Labels: review:general, skip-changelog

#6187 fix: MinK control plane diagram
  app/assets/images/diagrams/diagram-mesh-in-konnect.png
Labels: review:general

#6189 chore: CE patch version 2.8.4 bump
  app/_data/kong_versions.yml
Labels: review:general, skip-changelog

#6182 Add 'make kill-ports' command
  Makefile
Labels: review:tech

#6065 Sectioned cluster_fallback configs + added WebAssembly text to Wasm section
  app/_src/gateway/reference/configuration.md
  autodoc-conf-ee/run.lua
Labels: do not merge, review:general, ci:manual-approve:generated-files

#6183 Group renovate updates in to a single PR
  .github/renovate.json
Labels: review:tech

#6111 Feat: Add tool that detects broken markdown anchors
  .github/workflows/run-tests.yml
  app/_hub/kong-inc/vault-auth/_0.3.0/overview/_index.md
  app/_hub/kong-inc/vault-auth/overview/_index.md
  app/_src/gateway-operator/topologies/dbless.md
  app/_src/gateway/how-kong-works/routing-traffic.md
  app/_src/gateway/kong-plugins/authentication/oidc/azure-ad.md
  app/gateway/2.6.x/configure/auth/oidc-azuread.md
  app/gateway/2.6.x/reference/proxy.md
  app/gateway/2.7.x/configure/auth/oidc-azuread.md
  app/gateway/2.7.x/reference/proxy.md
  app/gateway/2.8.x/configure/auth/oidc-azuread.md
  app/gateway/2.8.x/reference/proxy.md
  tools/missing-markdown-anchor/run.sh
Labels: review:tech

#5936 Add KongConsumer examples to Kubernetes auth plugins
  app/_includes/plugins/hub-examples/global.html
  app/_includes/plugins/hub-examples/route.html
  app/_includes/plugins/hub-examples/service.html
  app/_includes/plugins/kubernetes_consumer.html
  app/_plugins/drops/plugins/examples/auth_plugins/base.rb
  app/_plugins/drops/plugins/examples/auth_plugins/basic_auth.rb
  app/_plugins/drops/plugins/examples/auth_plugins/hmac_auth.rb
  app/_plugins/drops/plugins/examples/auth_plugins/jwt_auth.rb
  app/_plugins/drops/plugins/examples/auth_plugins/key_auth.rb
  app/_plugins/drops/plugins/hub_examples.rb
Labels: review:tech, review:general

#6117 Update KIC EOL dates
  app/_src/kubernetes-ingress-controller/support-policy.md
Labels: review:general

#6164 Feat: Custom plugin management in Konnect
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/_src/gateway/plugin-development/distribution.md
  app/assets/images/docs/konnect/konnect-custom-plugins.png
  app/assets/images/docs/konnect/konnect-plugin-list.png
  app/konnect/gateway-manager/enable-route-plugin.md
  app/konnect/gateway-manager/enable-service-plugin.md
  app/konnect/gateway-manager/plugins.md
  app/konnect/gateway-manager/plugins/add-custom-plugin.md
  app/konnect/gateway-manager/plugins/index.md
  app/konnect/gateway-manager/plugins/troubleshoot-custom-plugins.md
  app/konnect/gateway-manager/plugins/update-custom-plugin.md
  tools/screenshots/plugins/custom-plugins.yaml
  tools/screenshots/plugins/plugin-list.yaml
Labels: review:copyedit, review:sme

#6194 chore: Rearrange org management section in Konnect nav
  app/_data/docs_nav_konnect.yml
Labels: review:general

#6195 Update: Service description in API specs [skip ci]
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
Labels: review:general, review:copyedit

#6199 Update: Add info about untrusted_lua param to exit transformer plugin
  app/_hub/kong-inc/exit-transformer/overview/_index.md
Labels: review:copyedit

#6200 fix: AWS Lambda plugin headers line
  app/_hub/kong-inc/aws-lambda/overview/_index.md
Labels: review:copyedit

#6203 fix: View Organizations
  app/konnect/org-management/org-switcher.md
Labels: review:copyedit

#6198 Update: Add link to routing reference from Request Transformer Advanced
  app/_hub/kong-inc/request-transformer-advanced/how-to/_templates.md
Labels: review:general
