Repository Kong/docs.konghq.com, pull requests merged in 2023-02, with the labels that each got.

#5070 [docu-2771] Configure TLS + Troubleshooting
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_src/gateway/production/networking/configure-postgres-tls.md
  app/_src/gateway/production/networking/troubleshoot-postgres-tls.md
Labels: review:copyedit

#5109 Revert "docs(aws-lambda): add new `https` config field in aws-lambda plugin"
  app/_hub/kong-inc/aws-lambda/_index.md
Labels: review:general

#5105 doc(kic) update admission webhook documentation
  app/_data/docs_nav_kic_2.8.x.yml
  app/_src/kubernetes-ingress-controller/deployment/admission-webhook.md
  app/_src/kubernetes-ingress-controller/deployment/overview.md
Labels: do not merge, review:copyedit

#5116 [DOCU-2957] Add missing 3.1.1.2 changelog entries
  app/gateway/changelog.md
Labels: review:copyedit

#5112 PR - Update Hybrid communication protocol to TCP
  app/enterprise/2.5.x/deployment/default-ports.md
Labels: review:tech

#5103 Postgres outdated version
  app/_src/gateway/install/docker/index.md
Labels: review:general, review:sme

#4881 Update NLB guide to preserve IP address on EKS using AWS Load Balancer Controller strategy
  app/_src/kubernetes-ingress-controller/guides/preserve-client-ip.md
Labels: review:general, review:sme

#5050 docs(log): improve docs on log serialization format
  app/_includes/md/plugins-hub/json-object-log.md
  app/_includes/md/plugins-hub/log-format.md
Labels: review:general

#5121 Keep consistent with current UI
  app/konnect/runtime-manager/runtime-groups/index.md
Labels: review:general

#4897 [DOCU-2943] Add portal auth API docs to Konnect docs
  app/_data/docs_nav_konnect.yml
  app/konnect/api/filtering.md
  app/konnect/api/index.md
  app/konnect/api/portal-auth/portal-rbac-guide.md
Labels: review:general, pending:release

#5126 Remove redundant Services paragraph
  app/_src/gateway/key-concepts/services.md
Labels: review:general

#5117 docs(saml): session library v4.0.0
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/saml/_index.md
Labels: review:general, review:copyedit

#5134 Fix typo in dev portal doc
  app/_src/gateway/kong-enterprise/dev-portal/working-with-templates.md
  app/gateway/2.6.x/developer-portal/working-with-templates.md
  app/gateway/2.7.x/developer-portal/working-with-templates.md
  app/gateway/2.8.x/developer-portal/working-with-templates.md
Labels: review:general

#5133 Changelog fix: Remove internal implementation info
  app/gateway/changelog.md
Labels: review:general

#5119 PR: Update default protocols for Hybrid communications in Kong 3.0 Production Page
  app/_src/gateway/production/networking/default-ports.md
Labels: review:tech

#5130 change docs keys link keys-entity to keys-object
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_redirects
  app/_src/gateway/admin-api/index.md
Labels: review:copyedit, ci:check-skipped:generated-files, ci:manual-approve:generated-files

#5138 Corrected hyperlink and added proxy-cache plugin
  app/_src/gateway/plugin-development/custom-logic.md
Labels: review:copyedit

#5136 Chore: Bump deck version to 1.17.3
  app/_data/kong_versions.yml
Labels: review:general

#5115 docs(openid-connect): session library v4.0.0
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/openid-connect/_index.md
Labels: review:general, review:copyedit

#5122 docs(session-plugin): docs for session library v4
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/session/_index.md
  app/_src/gateway/kong-enterprise/dev-portal/authentication/sessions.md
  app/_src/gateway/kong-manager/auth/sessions.md
Labels: review:copyedit

#5108 [DOCU-2899] Plugin compatibility table + protocols
  app/_assets/stylesheets/page.less
  app/_assets/stylesheets/pages/extension.less
  app/_data/tables/plugin_index.yml
  app/_hub/_init/my-extension/_index.md
  app/_hub/kong-inc/acl/_index.md
  app/_hub/kong-inc/acme/_index.md
  app/_hub/kong-inc/aws-lambda/_index.md
  app/_hub/kong-inc/azure-functions/_index.md
  app/_hub/kong-inc/bot-detection/_index.md
  app/_hub/kong-inc/canary/_index.md
  app/_hub/kong-inc/correlation-id/_index.md
  app/_hub/kong-inc/cors/_index.md
  app/_hub/kong-inc/datadog/_index.md
  app/_hub/kong-inc/degraphql/_index.md
  app/_hub/kong-inc/exit-transformer/_index.md
  app/_hub/kong-inc/file-log/_index.md
  app/_hub/kong-inc/forward-proxy/_index.md
  app/_hub/kong-inc/graphql-proxy-cache-advanced/_index.md
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
  app/_hub/kong-inc/grpc-gateway/_index.md
  app/_hub/kong-inc/grpc-web/_index.md
  app/_hub/kong-inc/http-log/_index.md
  app/_hub/kong-inc/ip-restriction/_index.md
  app/_hub/kong-inc/jq/_index.md
  app/_hub/kong-inc/kafka-upstream/_index.md
  app/_hub/kong-inc/ldap-auth/_index.md
  app/_hub/kong-inc/mocking/_index.md
  app/_hub/kong-inc/oauth2-introspection/_index.md
  app/_hub/kong-inc/opa/_index.md
  app/_hub/kong-inc/opentelemetry/_index.md
  app/_hub/kong-inc/prometheus/_index.md
  app/_hub/kong-inc/proxy-cache/_index.md
  app/_hub/kong-inc/rate-limiting/_index.md
  app/_hub/kong-inc/request-size-limiting/_index.md
  app/_hub/kong-inc/request-termination/_index.md
  app/_hub/kong-inc/request-transformer-advanced/_index.md
  app/_hub/kong-inc/request-transformer/_index.md
  app/_hub/kong-inc/request-validator/_index.md
  app/_hub/kong-inc/response-ratelimiting/_index.md
  app/_hub/kong-inc/response-transformer-advanced/_index.md
  app/_hub/kong-inc/response-transformer/_index.md
  app/_hub/kong-inc/route-by-header/_index.md
  app/_hub/kong-inc/route-transformer-advanced/_index.md
  app/_hub/kong-inc/saml/_index.md
  app/_hub/kong-inc/serverless-functions/_index.md
  app/_hub/kong-inc/session/_index.md
  app/_hub/kong-inc/statsd/_index.md
  app/_hub/kong-inc/upstream-timeout/_index.md
  app/_hub/kong-inc/xml-threat-protection/_index.md
  app/_hub/kong-inc/zipkin/_index.md
  app/hub/index.html
  app/hub/plugins/compatibility.md
  app/hub/plugins/license-tiers.md
  app/konnect/compatibility.md
Labels: review:tech, review:copyedit, ci:check-skipped:generated-files, ci:manual-approve:linting

#5143 Fix multiple authentication broken link
  app/_hub/kong-inc/session/_index.md
Labels: review:general

#5139 fix: kic 2.8 enabled CombinedRoutes by default
  app/_src/kubernetes-ingress-controller/references/feature-gates.md
Labels: Kubernetes Team, review:general, area/docs

#5144 [DOCU-2928] Kong-Debug header + configuration reference update
  app/_src/gateway/how-kong-works/routing-traffic.md
  app/_src/gateway/kong-plugins/configuring-a-grpc-service.md
  app/_src/gateway/reference/configuration.md
  autodoc-conf-ee/run.lua
Labels: review:copyedit, ci:prevent-merge:generated-files, ci:manual-approve:generated-files

#5147 Update kong.service.response.md
  app/_src/gateway/plugin-development/pdk/kong.service.response.md
Labels: review:copyedit

#5140 plugins(key-auth): various improvements
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/key-auth/_index.md
Labels: review:copyedit

#5046 feat(plugins): add datadog tracing plugin
  .github/styles/kongplugins/plugin-ignore.txt
  app/_assets/images/icons/hub/kong-inc_datadog-tracing.png
  app/_data/tables/plugin_index.yml
  app/_hub/kong-inc/datadog-tracing/_index.md
  app/_hub/kong-inc/datadog-tracing/versions.yml
  app/_hub/kong-inc/opentelemetry/_index.md
  app/_src/gateway/plugin-development/custom-logic.md
  app/_src/gateway/production/tracing/api.md
  app/_src/gateway/production/tracing/index.md
Labels: review:copyedit, ci:manual-approve:generated-files

#5162 Add more entries to kongplugins' dictionary
  .github/styles/kongplugins/dictionary.txt
Labels: review:general

#5164 [DOCU-2983] Plugin instance name + spacing fixes
  app/_layouts/extension.html
  app/hub/plugins/compatibility.md
Labels: review:copyedit

#5154 [docu-2922] Kong Manager + Konnect support for asymetric key storage
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/_src/gateway/kong-manager/index.md
  app/_src/gateway/reference/key-management.md
  app/konnect/runtime-manager/gateway-config.md
  app/konnect/runtime-manager/manage-proxy-config.md
Labels: review:copyedit

#5161 Update PDK autodoc for 3.2
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_src/gateway/plugin-development/pdk/index.md
  app/_src/gateway/plugin-development/pdk/kong.client.tls.md
  app/_src/gateway/plugin-development/pdk/kong.jwe.md
  app/_src/gateway/plugin-development/pdk/kong.request.md
  app/_src/gateway/plugin-development/pdk/kong.service.md
  app/_src/gateway/plugin-development/pdk/kong.websocket.client.md
  app/_src/gateway/plugin-development/pdk/kong.websocket.upstream.md
Labels: review:general, ci:check-skipped:generated-files

#5166 quick fixes
  app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
  app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md
  app/_src/gateway/production/deployment-topologies/index.md
Labels: review:general

#5157 Docu-2964: Revised upgrade paths
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_src/gateway/upgrade-31x.md
  app/gateway/changelog.md
Labels: review:copyedit, review:sme

#5156 [docu-2961] Update autodocs
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_src/gateway/admin-api/index.md
  app/konnect/api/runtime-groups-config/index.md
Labels: do not merge, review:general, ci:check-skipped:generated-files, ci:manual-approve:generated-files

#5159 [DOCU-2920] Changelog for Gateway 3.2
  app/_hub/kong-inc/canary/_index.md
  app/_hub/kong-inc/opentelemetry/_index.md
  app/_src/gateway/how-kong-works/load-balancing.md
  app/gateway/changelog.md
Labels: review:copyedit

#5135 FIPS Compliance for 3.2
  .github/styles/kong/auto-ignore.txt
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_src/gateway/kong-enterprise/fips-support.md
  app/_src/gateway/kong-enterprise/fips-support/index.md
  app/_src/gateway/kong-enterprise/fips-support/install.md
  app/_src/gateway/kong-enterprise/fips-support/plugins.md
Labels: review:copyedit

#5169 Gateway 3.2: QA edits
  app/_src/gateway/admin-api/licenses/reference.md
  app/_src/gateway/get-started/index.md
  app/_src/gateway/licenses/examples.md
  app/_src/gateway/licenses/report.md
  app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
  app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md
Labels: review:general

#5168 [DOCU-2982] Audit log updates for 3.2
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_src/gateway/admin-api/audit-logs.md
  app/_src/gateway/kong-enterprise/audit-log.md
Labels: review:copyedit

#5167 3.2 changelog edits + missing entries
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/session/_index.md
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:linting

#5172 Fix table styling
  app/_assets/stylesheets/features-table.less
  app/_assets/stylesheets/page.less
  app/_assets/stylesheets/pages/docs.less
Labels: review:general

#5171 oauth2_update
  app/_hub/kong-inc/oauth2/_index.md
Labels: review:general

#5059 Add support matrix
  app/_assets/images/icons/third-party/aws.svg
  app/_assets/images/icons/third-party/cassandra.svg
  app/_assets/images/icons/third-party/datadog.svg
  app/_assets/images/icons/third-party/gcp.svg
  app/_assets/images/icons/third-party/influxdb.svg
  app/_assets/images/icons/third-party/istio.svg
  app/_assets/images/icons/third-party/kafka.svg
  app/_assets/images/icons/third-party/kong.svg
  app/_assets/images/icons/third-party/loggly.svg
  app/_assets/images/icons/third-party/minio.svg
  app/_assets/images/icons/third-party/opentelemetry.svg
  app/_assets/images/icons/third-party/postgresql.svg
  app/_assets/images/icons/third-party/prometheus.svg
  app/_assets/images/icons/third-party/redis.svg
  app/_assets/images/icons/third-party/splunk.svg
  app/_assets/images/icons/third-party/statsd.svg
  app/_assets/images/icons/third-party/vaultproject.svg
  app/_assets/images/icons/third-party/zipkin.svg
  app/_assets/stylesheets/badges.less
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/tables/support/gateway/browsers.yml
  app/_data/tables/support/gateway/packages.yml
  app/_data/tables/support/gateway/third-party.yml
  app/_data/tables/support/gateway/versions/28.yml
  app/_data/tables/support/gateway/versions/30.yml
  app/_data/tables/support/gateway/versions/31.yml
  app/_data/tables/support/gateway/versions/32.yml
  app/_includes/gateway-support-browsers.html
  app/_includes/gateway-support-third-party.html
  app/_includes/gateway-support.html
  app/_plugins/blocks/navtabs.rb
  app/_plugins/filters/to_check.rb
  app/_plugins/read_data_file_liquid.rb
  app/_src/gateway/support/browser.md
  app/_src/gateway/support/index.md
  app/_src/gateway/support/third-party.md
  app/_src/kubernetes-ingress-controller/support-policy.md
  tests/sidebar.test.js
Labels: review:sme

#5175 release 3.2/datadog services routes
  app/_hub/kong-inc/datadog-tracing/_index.md
Labels: ci:check-skipped:generated-files

#5178 Update index.md
  app/_src/gateway/support/index.md
Labels: review:general

#5176 update Kong Mesh versions
  app/_data/kong_versions.yml
Labels: review:general

#5179 Update docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
Labels: review:general

#5181 [DOCU-2989] Upgrade guidance + sessions parameter cleanup
  app/_src/gateway/install/helm-quickstart.md
  app/_src/gateway/install/kubernetes/helm-quickstart.md
  app/_src/gateway/install/kubernetes/helm.md
  app/_src/gateway/install/kubernetes/openshift.md
  app/_src/gateway/kong-enterprise/dev-portal/authentication/basic-auth.md
  app/_src/gateway/kong-enterprise/dev-portal/authentication/sessions.md
  app/_src/gateway/kong-manager/auth/basic.md
  app/_src/gateway/kong-manager/auth/index.md
  app/_src/gateway/kong-manager/auth/ldap/configure.md
  app/_src/gateway/kong-manager/auth/ldap/service-directory-mapping.md
  app/_src/gateway/kong-manager/auth/oidc/configure.md
  app/_src/gateway/kong-manager/auth/sessions.md
  app/_src/gateway/production/access-control/start-securely.md
  app/_src/gateway/production/networking/dns-considerations.md
  app/_src/gateway/upgrade-31x.md
Labels: review:copyedit

#5182 Revert "[DOCU-2989] Upgrade guidance + sessions parameter cleanup"
  app/_src/gateway/install/helm-quickstart.md
  app/_src/gateway/install/kubernetes/helm-quickstart.md
  app/_src/gateway/install/kubernetes/helm.md
  app/_src/gateway/install/kubernetes/openshift.md
  app/_src/gateway/kong-enterprise/dev-portal/authentication/basic-auth.md
  app/_src/gateway/kong-enterprise/dev-portal/authentication/sessions.md
  app/_src/gateway/kong-manager/auth/basic.md
  app/_src/gateway/kong-manager/auth/index.md
  app/_src/gateway/kong-manager/auth/ldap/configure.md
  app/_src/gateway/kong-manager/auth/ldap/service-directory-mapping.md
  app/_src/gateway/kong-manager/auth/oidc/configure.md
  app/_src/gateway/kong-manager/auth/sessions.md
  app/_src/gateway/production/access-control/start-securely.md
  app/_src/gateway/production/networking/dns-considerations.md
  app/_src/gateway/upgrade-31x.md
Labels: review:general

#5184 [DOCU-2945] Konnect + Gateway 3.2 - Datadog EE plugin
  app/_data/tables/plugin_index.yml
Labels: review:general

#5180 changelog for new mesh versions
  .github/styles/kong/dictionary.txt
  app/mesh/changelog.md
Labels: review:general

#5165 docs(rate-limiting): remove wrongly placed information
  app/_hub/kong-inc/rate-limiting/_index.md
Labels: review:general

#5158 Explain the session_cookie_renew property in more detail
  app/_hub/kong-inc/openid-connect/_index.md
Labels: review:general, review:sme

#5183 [DOCU-2989] Upgrade guidance + sessions parameter cleanup
  app/_hub/kong-inc/openid-connect/_index.md
  app/_hub/kong-inc/saml/_index.md
  app/_hub/kong-inc/session/_index.md
  app/_src/gateway/install/helm-quickstart.md
  app/_src/gateway/install/kubernetes/helm-quickstart.md
  app/_src/gateway/install/kubernetes/helm.md
  app/_src/gateway/install/kubernetes/openshift.md
  app/_src/gateway/kong-enterprise/dev-portal/authentication/basic-auth.md
  app/_src/gateway/kong-enterprise/dev-portal/authentication/sessions.md
  app/_src/gateway/kong-manager/auth/basic.md
  app/_src/gateway/kong-manager/auth/index.md
  app/_src/gateway/kong-manager/auth/ldap/configure.md
  app/_src/gateway/kong-manager/auth/ldap/service-directory-mapping.md
  app/_src/gateway/kong-manager/auth/oidc/configure.md
  app/_src/gateway/kong-manager/auth/sessions.md
  app/_src/gateway/production/access-control/start-securely.md
  app/_src/gateway/production/networking/dns-considerations.md
  app/_src/gateway/upgrade-31x.md
Labels: review:copyedit, review:sme

#5173 [DOCU-2990] Changelog 3.2: late breaking changes
  app/gateway/changelog.md
Labels: do not merge, review:copyedit

#5186 [DOCU-2270] Remove drafts for entity sharing
  app/konnect/org-management/teams-and-roles/index.md
  app/konnect/servicehub/manage-services.md
Labels: review:general

#5191 Remove last bits of old `/apis` endpoint
  app/_hub/kong-inc/jwt-signer/_2.2.x.md
  app/_hub/kong-inc/oauth2/_index.md
  app/_hub/kong-inc/statsd-advanced/_1.3-x.md
  app/_src/gateway/admin-api/workspaces/reference.md
  app/gateway/2.6.x/admin-api/workspaces/reference.md
  app/gateway/2.7.x/admin-api/workspaces/reference.md
  app/gateway/2.8.x/admin-api/workspaces/reference.md
Labels: review:general

#5195 3.2 rollback notice to changelog
  app/gateway/changelog.md
Labels: review:general

#5193 Support policy URL
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_redirects
  app/moved_urls.yml
Labels: review:general

#5163 add 3.2 version, compatibility table updates
  app/_data/tables/version_errors_konnect.yml
  app/konnect/compatibility.md
Labels: review:general

#5177 Add Konnect support to the OAS plugin
  app/_data/tables/plugin_index.yml
  app/_hub/kong-inc/oas-validation/_index.md
Labels: review:general

#5185 [DOCU-2967] Share CP/DP proxy 3.1 content into Konnect
  app/konnect/runtime-manager/runtime-instances/index.md
Labels: review:copyedit

#5188 modify the description of latencies for logging plugins
  app/_includes/md/plugins-hub/json-object-log.md
Labels: review:tech, review:general, review:sme

#5192 Fix the upgrade path for 2.8.x traditional and DBless
  app/_src/gateway/upgrade-31x.md
Labels: review:general

#5199 add VERSION field
  app/_src/kubernetes-ingress-controller/guides/setting-up-custom-plugins.md
Labels: review:general

#5197 Release/deck 1.18.1 and 1.19.0
  app/_data/docs_nav_deck_1.18.x.yml
  app/_data/docs_nav_deck_1.19.x.yml
  app/_data/kong_versions.yml
  app/_src/deck/guides/defaults-v2.md
  app/_src/deck/guides/defaults.md
  app/_src/deck/guides/konnect.md
  app/konnect/getting-started/import.md
  app/konnect/runtime-manager/runtime-groups/declarative-config.md
Labels: review:general

#5205 docs(audit-logs): update example for webhook config
  app/konnect/org-management/audit-logging/webhook.md
Labels: review:copyedit

#5107 DOCU-2926: DCR overview page and new authentication methods
  app/_assets/images/docs/konnect/dcr-auth-methods.png
  app/_assets/images/docs/konnect/dcr-bearer-tokens.png
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/applications/dynamic-client-registration/index.md
Labels: review:general, pending:release

#5214 [DOCU-2518] Konnect login session duration
  app/_data/docs_nav_konnect.yml
  app/konnect/org-management/auth.md
  app/konnect/org-management/sessions-reference.md
Labels: review:copyedit

#4999 [DOCU-2838] Konnect System Accounts (GA)
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/konnect/org-management/system-accounts.md
  app/konnect/org-management/users.md
Labels: review:copyedit, pending:release

#5203 Using system account PATs with decK
  app/_includes/md/personal-access-token.md
  app/_src/deck/guides/konnect.md
Labels: review:copyedit, pending:release

#5217 [DOCU-3004] Remove profiling routes from admin api doc
  app/_src/gateway/admin-api/index.md
Labels: review:general, ci:manual-approve:generated-files

#5204 3.2 changelog + metadata
  app/_data/kong_versions.yml
  app/gateway/changelog.md
  app/konnect/compatibility.md
Labels: review:general

#5213 [DOCU-2588] Reference topic for labels in Konnect
  app/_data/docs_nav_konnect.yml
  app/konnect/reference/labels.md
  app/konnect/servicehub/manage-services.md
Labels: review:copyedit

#5215 Fix opentelemetry plugin configuration example
  app/_includes/hub-examples.html
Labels: review:general

#5212 [DOCU-2820][DOCU-2753] Improve license expiration description
  app/_src/gateway/licenses/index.md
Labels: review:copyedit

#5128 Konnect Feb 2023 Changelog
  app/konnect/updates.md
Labels: review:general
