Repository Kong/docs.konghq.com, pull requests merged in 2023-11, with the labels that each got.

#6421 Add KIC 3.0 install methods
  app/_data/docs_nav_kic_3.0.x.yml
  app/_includes/snippets/gateway-operator/install_with_kubectl_all_controllers.md
  app/_src/gateway-operator/get-started/kic/install.md
  app/_src/kubernetes-ingress-controller/get-started/index.md
  app/_src/kubernetes-ingress-controller/install/gateway-operator.md
  app/_src/kubernetes-ingress-controller/install/helm.md
Labels: review:copyedit

#6418 KIC 3.0: Install on GKE
  app/_src/kubernetes-ingress-controller/install/cloud/gke.md
Labels: review:copyedit, ci:manual-approve:link-validation

#6422 KIC 3.0: Rewrite annotation
  app/_includes/md/kic/http-test-routing-resource.md
  app/_includes/md/kic/http-test-routing.md
  app/_src/kubernetes-ingress-controller/guides/requests/rewrite-annotation.md
  app/_src/kubernetes-ingress-controller/guides/services/http.md
Labels: review:copyedit

#6423 KIC 3.0: Router FAQ
  app/_src/kubernetes-ingress-controller/reference/faq/router.md
Labels: review:copyedit

#6424 KIC 3.0: Security
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/guides/security/kong-vault.md
  app/_src/kubernetes-ingress-controller/guides/security/workspaces.md
Labels: review:copyedit

#6425 KIC 3.0: Events
  app/_src/kubernetes-ingress-controller/production/observability/events.md
  app/_src/kubernetes-ingress-controller/reference/troubleshooting.md
Labels: review:copyedit

#6428 fix: OIDC
  app/_src/kubernetes-ingress-controller/plugins/oidc.md
Labels: review:tech, skip-changelog

#6429 Topnav tweaks
  app/_assets/stylesheets/base.less
  app/_assets/stylesheets/header-v2.less
  app/_includes/nav-v2.html
  app/assets/images/landing-page/view-all-api-specs.png
Labels: review:general

#6002 feat: aws lambda plugin now supports more IAM-based authentication scenarios
  app/_hub/kong-inc/aws-lambda/_changelog.md
  app/_hub/kong-inc/aws-lambda/overview/_index.md
Labels: review:tech, review:general

#6414 Add Kong Mesh specific policies to the migration script
  app/konnect/mesh-manager/migrate-zone.md
Labels: review:tech

#6430 Automated OAS Update
  api-specs/Konnect/v2/yaml/portal-management.yaml
Labels: review:general

#6431 Update resource limit language
  app/konnect/gateway-manager/configuration/index.md
Labels: review:general

#6394 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6416 Fix: App registration doc lists hybrid mode as not supported
  app/_hub/kong-inc/application-registration/how-to/_index.md
  app/_hub/kong-inc/application-registration/overview/_index.md
  app/_src/gateway/kong-enterprise/dev-portal/applications/auth-provider-strategy.md
  app/_src/gateway/kong-enterprise/dev-portal/applications/enable-application-registration.md
  app/gateway/2.6.x/developer-portal/administration/application-registration/auth-provider-strategy.md
  app/gateway/2.6.x/developer-portal/administration/application-registration/enable-application-registration.md
  app/gateway/2.7.x/developer-portal/administration/application-registration/auth-provider-strategy.md
  app/gateway/2.7.x/developer-portal/administration/application-registration/enable-application-registration.md
  app/gateway/2.8.x/developer-portal/administration/application-registration/auth-provider-strategy.md
  app/gateway/2.8.x/developer-portal/administration/application-registration/enable-application-registration.md
Labels: review:copyedit

#6440 Fix: 2.8.1.3 changelog entry for aws-lambda plugin changes to match 3.0.0.0
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#6439 Fix: Align wording of 2.8.1.3 update for `aws_assume_role_arn` property
  app/_hub/kong-inc/aws-lambda/_changelog.md
Labels: review:general, ci:manual-approve:link-validation

#6434 Add gateway 35/36 repo pubkeys
  app/_data/installation/gateway.yml
Labels: review:tech

#6307 feat(license_report): update description of licensing report
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_src/gateway/licenses/report-v2.md
  app/_src/gateway/licenses/report.md
Labels: review:general

#6432 Add labels to the PR created in sync-kuma-submodule.yml
  .github/workflows/sync-kuma-submodule.yml
Labels: review:general, skip-changelog

#6442 feat: dedicated config processing
  app/_src/gateway/production/sizing-guidelines.md
Labels: review:general

#6388 Feat: Portal Management API
  app/_api/konnect/portal-management/_index.md
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_oas_data.json
  app/konnect/updates.md
Labels: review:general, pending:release

#6450 Fix search on mobile
  app/_assets/stylesheets/header-v2.less
  app/_includes/nav-v2.html
Labels: review:general

#6446 Update readme in api-specs directory to include updated information for the directory [skip-ci]
  api-specs/Konnect/v1/json/konnect.json
  api-specs/Konnect/v1/yaml/konnect.yaml
  api-specs/Konnect/v2/json/konnect-2.json
  api-specs/Konnect/v2/yaml/konnect-2.yaml
  api-specs/readme.md
Labels: review:general, skip-changelog

#6451 Remove Konnect beta warning from KIC
  app/_src/kic-v2/concepts/deployment.md
Labels: review:general

#6441 feat(openid-connect): cert-bound tokens doc edits
  app/_hub/kong-inc/openid-connect/overview/_index.md
Labels: review:copyedit

#6445 chore: Update Gateway config reference for 3.5
  app/_src/gateway/reference/configuration.md
Labels: review:general, ci:manual-approve:generated-files

#6452 chore: Remove performance testing framework from 3.5
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_redirects
  app/_src/gateway/how-kong-works/performance-testing.md
  app/_src/gateway/reference/performance-testing-framework.md
Labels: review:copyedit

#6407 chore: add customizing load-balancing with KongUpstreamPolicy
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/guides/requests/customizing-load-balancing.md
Labels: Kubernetes Team, review:copyedit, ci:manual-approve:link-validation

#6460 Upgrade KIC Gateway
  app/_src/kubernetes-ingress-controller/upgrade/gateway.md
Labels: review:tech, ci:manual-approve:link-validation, skip-changelog

#6369 chore: add KIC 3 upgrade guide
  app/_src/kubernetes-ingress-controller/guides/migrate/credential-kongcredtype-label.md
  app/_src/kubernetes-ingress-controller/guides/migrate/ingress-to-gateway.md
  app/_src/kubernetes-ingress-controller/guides/migrate/kongingress.md
  app/_src/kubernetes-ingress-controller/upgrade/kic.md
Labels: review:general, review:copyedit, ci:manual-approve:link-validation, review:sme

#6462 update gateway API version to v1 in KIC 3.0 docs
  app/_includes/md/kic/class.md
  app/_includes/md/kic/http-test-routing-resource.md
  app/_includes/md/kic/prerequisites.md
  app/_src/kic-v2/concepts/gateway-api.md
  app/_src/kic-v2/deployment/install-gateway-apis.md
  app/_src/kic-v2/guides/using-gateway-api.md
  app/_src/kic-v2/references/feature-gates.md
  app/_src/kubernetes-ingress-controller/guides/services/tls.md
  app/kubernetes-ingress-controller/2.2.x/deployment/install-gateway-apis.md
Labels: review:general

#6455 chore: Copy over nav changes from 3.4 to 3.5
  app/_data/docs_nav_gateway_3.5.x.yml
Labels: review:general

#6250 kic: update 2.12 CRD reference
  app/_src/kic-v2/references/custom-resources-2.12.x.md
Labels: review:general

#6419 Gateway 3.5 Autodocs
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
  api-specs/Gateway-OSS/3.5/kong-oss-3.5.yaml
  app/_src/gateway/plugin-development/pdk/kong.client.md
  app/_src/gateway/plugin-development/pdk/kong.log.md
  app/_src/gateway/plugin-development/pdk/kong.request.md
  app/_src/gateway/reference/cli.md
Labels: review:general, ci:check-skipped:generated-files

#6470 Chore: Support matrix updates for Gateway 3.5
  app/_data/tables/support/gateway/versions/35.yml
  app/_src/gateway/support/index.md
Labels: review:general

#6464 Updating link to IETF Draft
  app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
  app/_hub/kong-inc/rate-limiting/overview/_index.md
Labels: review:sme

#6458 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6387 fix: add acronyms
  app/_src/gateway/kong-enterprise/index.md
Labels: review:general, skip-changelog

#6481 Bump spec-renderer
  package-lock.json
  package.json
Labels: review:tech

#6474 chore: add compatibility updates for Gateway 3.5 release
  app/_data/tables/version_errors_konnect.yml
Labels: review:general

#6463 docs(plugins): add docs about `plugin:configure` handler
  app/_src/gateway/plugin-development/custom-logic.md
  app/_src/gateway/plugin-development/entities-cache.md
Labels: review:copyedit

#6459 Add wasm filter config schema document
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_src/gateway/plugin-development/wasm/filter-configuration.md
  app/_src/gateway/plugin-development/wasm/filter-development-guide.md
  app/_src/gateway/reference/wasm.md
Labels: review:general, review:copyedit

#6484 chore: Dev Portal broken links
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_includes/md/gateway/setup.md
  app/_redirects
  app/_src/gateway/install/linux/ubuntu.md
  app/_src/gateway/kong-plugins/authentication/oidc/azure-ad.md
  app/_src/gateway/kong-plugins/authentication/oidc/curity.md
  app/_src/gateway/kong-plugins/authentication/oidc/okta.md
Labels: review:general

#6471 Release 3.5 Changelog
  app/_hub/kong-inc/acme/_changelog.md
  app/_hub/kong-inc/aws-lambda/_changelog.md
  app/_hub/kong-inc/canary/_changelog.md
  app/_hub/kong-inc/cors/_changelog.md
  app/_hub/kong-inc/grpc-gateway/_changelog.md
  app/_hub/kong-inc/kafka-log/_changelog.md
  app/_hub/kong-inc/mocking/_changelog.md
  app/_hub/kong-inc/mtls-auth/_changelog.md
  app/_hub/kong-inc/oas-validation/_changelog.md
  app/_hub/kong-inc/oauth2-introspection/_changelog.md
  app/_hub/kong-inc/openid-connect/_changelog.md
  app/_hub/kong-inc/opentelemetry/_changelog.md
  app/_hub/kong-inc/prometheus/_changelog.md
  app/_hub/kong-inc/rate-limiting-advanced/_changelog.md
  app/_hub/kong-inc/request-validator/_changelog.md
  app/_hub/kong-inc/response-ratelimiting/_changelog.md
  app/_hub/kong-inc/response-transformer/_changelog.md
  app/_hub/kong-inc/saml/_changelog.md
  app/_hub/kong-inc/session/_changelog.md
  app/_hub/kong-inc/tcp-log/_changelog.md
  app/_hub/kong-inc/zipkin/_changelog.md
  app/_src/gateway/breaking-changes/35x.md
  app/gateway/changelog.md
Labels: review:general, review:copyedit, ci:manual-approve:link-validation

#6482 Chore: update upgrade paths for Gateway 3.5
  app/_src/gateway/upgrade-v2.md
Labels: review:general

#6472 kgo: release v1.0.3
  app/_data/kong_versions.yml
  app/assets/gateway-operator/v1.0.3/all_controllers.yaml
  app/assets/gateway-operator/v1.0.3/crds.yaml
  app/assets/gateway-operator/v1.0.3/default.yaml
  app/gateway-operator/changelog.md
Labels: Kubernetes Team, review:general

#6487 docs: add KIC 3.0 missing docs updates
  app/_src/kic-v2/references/version-compatibility.md
  app/_src/kubernetes-ingress-controller/reference/annotations.md
  app/_src/kubernetes-ingress-controller/support-policy.md
Labels: review:general, area/docs

#6473 KIC: Fix GRPC Guide
  app/_data/docs_nav_kic_3.0.x.yml
  app/_includes/md/kic/add-certificate.md
  app/_src/kic-v2/guides/using-ingress-with-grpc.md
  app/_src/kubernetes-ingress-controller/gateway-api.md
  app/_src/kubernetes-ingress-controller/guides/services/grpc.md
Labels: review:general, review:copyedit

#6475 feat: Request Debug Header docs for Kong Gateway 3.5
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_src/gateway/production/debug-request.md
Labels: review:copyedit

#6489 Fix broken links from Mattia's blog post
  app/moved_urls.yml
Labels: review:general

#6488 docs(rbac): update description on 1st super admin creation
  app/_src/gateway/production/access-control/register-admin-api.md
  app/_src/gateway/production/access-control/start-securely.md
Labels: review:general, review:copyedit

#6469 chore: Bump deck version to 1.29.x
  app/_data/docs_nav_deck_1.29.x.yml
  app/_data/kong_versions.yml
Labels: review:general

#6491 chore: Remove influxdb from list of supported 3rd party dependencies in 3.5
  app/_data/tables/support/gateway/versions/35.yml
Labels: review:general, skip-changelog

#6492 chore: Update sbom.md
  app/_src/gateway/support/sbom.md
Labels: review:general, skip-changelog

#6493 chore: Update sbom.md
  app/_src/gateway/support/sbom.md
Labels: review:general, skip-changelog

#6494 chore: Kic 3.0 nitpicks
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/concepts/ingress.md
  app/_src/kubernetes-ingress-controller/gateway-api.md
  app/_src/kubernetes-ingress-controller/index.md
  app/_src/kubernetes-ingress-controller/production/deployment-topologies/db-backed.md
  app/_src/kubernetes-ingress-controller/production/deployment-topologies/index.md
Labels: review:copyedit

#6501 [URGENT] Remove 2 unwanted changelog entries from 3.5.0.0
  app/gateway/changelog.md
Labels: review:general

#6490 Release Gateway 3.4.2.0
  app/_data/docs_nav_gateway_3.4.x.yml
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation, pending:release

#6506 Fix: Banner for using plugins in konnect
  app/_layouts/extension.html
Labels: review:general

#6509 Update gw manager docs
  app/konnect/gateway-manager/index.md
Labels: review:general

#6505 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6507 docs(changelog): consolidate the lua-resty-aws version bump changelog
  app/gateway/changelog.md
Labels: review:general

#6514 Add spec for 'Using plugins in Konnect' banner
  spec/templates/plugin_with_versions_spec.rb
Labels: review:general

#6497 chore: improve docs about support of gRPC in KIC
  app/_src/kubernetes-ingress-controller/guides/services/grpc.md
Labels: Kubernetes Team, review:tech, review:general

#6516 Fix Kong Vault in KIC styling
  app/_src/kubernetes-ingress-controller/guides/security/kong-vault.md
Labels: review:general

#6517 Redirect to KIC in Konnect on cloud install pages
  app/_includes/md/kic/konnect-setup.md
  app/_src/kubernetes-ingress-controller/install/cloud/aks.md
  app/_src/kubernetes-ingress-controller/install/cloud/eks.md
  app/_src/kubernetes-ingress-controller/install/cloud/gke.md
Labels: review:general

#6485 kic: fix the description of kic's leader election permission
  app/_src/kic-v2/concepts/ha-and-scaling.md
  app/_src/kubernetes-ingress-controller/guides/high-availability/kic.md
Labels: Kubernetes Team, review:general

#6523 Add ruby-lsp to Gemfile
  Gemfile
  Gemfile.lock
Labels: review:tech

#6525 Fix custom Docker build instructions
  app/_src/gateway/install/docker/build-custom-images.md
Labels: review:general, ci:manual-approve:link-validation

#6508 (chore) 3.5.0.1 changelog
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general, pending:release

#6526 Azure Key Vault docs for Konnect
  app/konnect/gateway-manager/configuration/vaults/how-to.md
  app/konnect/gateway-manager/configuration/vaults/index.md
Labels: review:general

#6529 Fix: Remove dev portal entries from 3.5 changelog
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation, skip-changelog

#6527 (chore) Konnect + 3.5 support
  app/konnect/compatibility.md
  app/konnect/updates.md
Labels: review:general

#6512 (chore) Add end off support dates to Konnect/GW compatibility table
  app/konnect/compatibility.md
Labels: review:general

#6510 Update Konnect curl request in renew-certificates.md
  app/konnect/gateway-manager/data-plane-nodes/renew-certificates.md
Labels: review:general

#6531 kgo: make api reference versioned
  app/_data/docs_nav_kgo_1.0.x.yml
  app/_src/gateway-operator/reference/custom-resources/1.0.x.md
Labels: Kubernetes Team, review:general

#6532 Update: Set max version for app registration plugin
  app/_hub/kong-inc/application-registration/versions.yml
Labels: review:general, skip-changelog

#6522 feat(dbless): add compatibility warning for Kong Manager
  app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
Labels: review:copyedit

#6539 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6540 Chore: Update Changelog for Gateway Milestone updates
  app/konnect/updates.md
Labels: review:copyedit, pending:release

#6436 Automated OAS Update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
  api-specs/Konnect/v0/yaml/mesh-control-planes.yaml
  api-specs/Konnect/v2/yaml/analytics-reports.yaml
  api-specs/Konnect/v2/yaml/analytics-requests.yaml
  api-specs/Konnect/v2/yaml/api-products.yaml
  api-specs/Konnect/v2/yaml/audit-logs.yaml
  api-specs/Konnect/v2/yaml/control-planes.yaml
  api-specs/Konnect/v2/yaml/portal-management.yaml
  api-specs/Konnect/v3/yaml/identity.yaml
Labels: review:general

#6518 kgo: add kgo version compatibility matrix
  app/_data/docs_nav_kgo_1.0.x.yml
  app/_src/gateway-operator/version-compatibility.md
Labels: Kubernetes Team, review:general

#6499 feat: Multi-geo GA
  app/_data/docs_nav_konnect.yml
  app/_src/deck/guides/konnect.md
  app/konnect/account-management/index.md
  app/konnect/api-products/service-documentation.md
  app/konnect/api/index.md
  app/konnect/dev-portal/access.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/dev-portal/dev-reg.md
  app/konnect/gateway-manager/configuration/index.md
  app/konnect/geo.md
  app/konnect/getting-started/access-account.md
  app/konnect/getting-started/productize-service.md
  app/konnect/index.md
  app/konnect/network.md
  app/konnect/org-management/teams-and-roles/index.md
  app/konnect/org-management/teams-and-roles/manage.md
  app/konnect/org-management/teams-and-roles/roles-reference.md
  app/konnect/org-management/teams-and-roles/teams-reference.md
  app/konnect/updates.md
Labels: review:general, pending:release

#6543 fix: Typo on aria attribute in modal
  app/_assets/javascripts/modal.js
Labels: review:general

#6437 update: Rewrite the expressions router Gateway doc
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_src/gateway/admin-api/admin-api-3.0.x.md
  app/_src/gateway/admin-api/admin-api-3.1.x.md
  app/_src/gateway/admin-api/admin-api-3.4.x.md
  app/_src/gateway/admin-api/index.md
  app/_src/gateway/key-concepts/routes/expressions.md
  app/_src/gateway/key-concepts/routes/index.md
  app/_src/gateway/reference/expressions-language/index.md
  app/_src/gateway/reference/expressions-language/language-references.md
  app/_src/gateway/reference/expressions-language/performance.md
  app/_src/gateway/reference/router-expressions-language.md
  app/assets/images/products/gateway/reference/expressions-language/predicate.png
  app/assets/images/products/gateway/reference/expressions-language/router-matching-flow.png
Labels: review:general, review:copyedit, ci:prevent-merge:generated-files, ci:manual-approve:generated-files

#6379 Update: Linux installation pages cleanup & consistency
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_includes/md/gateway/install-linux-os.md
  app/_includes/md/gateway/install-traditional-mode.md
  app/_includes/md/gateway/root-user-note.md
  app/_redirects
  app/_src/gateway/install/linux/amazon-linux.md
  app/_src/gateway/install/linux/debian.md
  app/_src/gateway/install/linux/rhel.md
  app/_src/gateway/install/linux/ubuntu.md
  app/_src/gateway/install/post-install/set-up-data-store.md
  app/_src/gateway/licenses/deploy.md
Labels: review:copyedit

#6549 style(expressions): fix typo in `performance.md`
  app/_src/gateway/reference/expressions-language/index.md
  app/_src/gateway/reference/expressions-language/performance.md
Labels: review:copyedit

#6565 fix: update deck schema URL
  app/_src/deck/faqs.md
  app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
Labels: review:general

#6563 docs(mesh): try to clarify what an AccessRole type is
  app/_src/mesh/features/rbac.md
Labels: review:general

#6560 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6547 Update: Listing a license requires license added via Admin API to begin with
  app/_src/gateway/licenses/examples.md
Labels: review:general, review:copyedit

#6546 remove Kubernetes requirements and put the OpenShift requirements
  app/_src/gateway/install/kubernetes/openshift.md
Labels: review:general

#6564 Automated OAS Update
  api-specs/Konnect/v3/yaml/identity.yaml
Labels: review:general

#6521 chore: add tips for encoding errors
  README.md
Labels: review:tech, review:general

#6568 chore: Add postgres 16 as a supported version for Kong Gateway 3.4 and 3.5
  app/_data/tables/support/gateway/versions/34.yml
  app/_data/tables/support/gateway/versions/35.yml
Labels: review:general

#6569 Chore: 2.8.4.5 Kong Gateway changelog
  app/gateway/2.8.x/reference/configuration.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation, skip-changelog

#6574 fix: Add missing Azure vault table entry
  app/_src/gateway/kong-enterprise/secrets-management/backends/index.md
Labels: review:general

#6542 docs(KIC): improved KIC ingress to gateway migration guide
  app/_src/kubernetes-ingress-controller/guides/migrate/ingress-to-gateway.md
Labels: review:copyedit

#6576 chore: Add missing search aliases and supported versions for 3rd party plugins
  app/_hub/TheLEGOGroup/aws-request-signing/_metadata.yml
  app/_hub/amberflo/kong-plugin-amberflo/_metadata.yml
  app/_hub/datadome/kong-plugin-datadome/_metadata.yml
  app/_hub/imperva/imp-appsec-connector/_metadata.yml
  app/_hub/moesif/kong-plugin-moesif/_metadata.yml
  app/_hub/nonamesecurity/nonamesecurity-kongprevention/_metadata.yml
  app/_hub/nonamesecurity/nonamesecurity-kongtrafficsource/_metadata.yml
  app/_hub/optum/kong-response-size-limiting/_metadata.yml
  app/_hub/optum/kong-service-virtualization/_metadata.yml
  app/_hub/optum/kong-spec-expose/_metadata.yml
  app/_hub/optum/kong-splunk-log/_metadata.yml
  app/_hub/optum/kong-upstream-jwt/_metadata.yml
  app/_hub/salt/salt/_metadata.yml
Labels: review:general

#6581 (chore) Delete blank custom plugins troubleshooting page
  app/konnect/gateway-manager/plugins/troubleshoot-custom-plugins.md
Labels: review:general, skip-changelog

#6582 (chore) Delete app/kong-kubernetes-changelog.md
  app/kong-kubernetes-changelog.md
Labels: review:general, skip-changelog

#6583 fix: Broken links to APIOps guide
  app/_src/deck/index.md
Labels: review:general

#6551 fix: add the missing part of kong gateway vault's secrets versioning description
  app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
  app/_src/gateway/kong-enterprise/secrets-management/reference-format.md
Labels: review:tech, review:general

#6502 fix: mention required secret field for JWT plugin in KIC how to
  app/_includes/md/kic/consumer.md
  app/_src/kic-v2/guides/configure-acl-plugin.md
  app/_src/kubernetes-ingress-controller/plugins/acl.md
  app/kubernetes-ingress-controller/1.0.x/guides/configure-acl-plugin.md
  app/kubernetes-ingress-controller/1.1.x/guides/configure-acl-plugin.md
  app/kubernetes-ingress-controller/1.2.x/guides/configure-acl-plugin.md
  app/kubernetes-ingress-controller/1.3.x/guides/configure-acl-plugin.md
  app/kubernetes-ingress-controller/2.0.x/guides/configure-acl-plugin.md
  app/kubernetes-ingress-controller/2.2.x/guides/configure-acl-plugin.md
Labels: Kubernetes Team, review:general

#6524 Add reference page for required permissions to install KIC
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/reference/required-permissions.md
Labels: Kubernetes Team, review:general

#6511 docs: clarify on rate-limit redis cluster support
  app/_hub/kong-inc/rate-limiting/overview/_index.md
Labels: review:general
