Repository Kong/docs.konghq.com, pull requests merged in 2023-07, with the labels that each got.

#5771 Update _metadata.yml
  app/_hub/kong-inc/oas-validation/_metadata.yml
Labels: review:general

#5777 fix: redirect /mesh/konnect to /mesh/latest
  app/_redirects
Labels: review:tech

#5780 Update reference.md to explicitly include the Audit Log's retention p…
  app/konnect/org-management/audit-logging/reference.md
Labels: review:copyedit

#5756 2.8.4.2 Changelog
  app/gateway/changelog.md
Labels: review:sme, pending:release

#5774 Fix breadcrumbs for plugins how-to
  app/_plugins/generators/plugin_single_source/pages/base.rb
  app/_plugins/generators/plugin_single_source/pages/configuration_examples.rb
  app/_plugins/generators/plugin_single_source/pages/how_to.rb
  spec/app/_plugins/generators/plugin_single_source/pages/changelog_spec.rb
  spec/app/_plugins/generators/plugin_single_source/pages/configuration_examples_spec.rb
  spec/app/_plugins/generators/plugin_single_source/pages/configuration_spec.rb
  spec/app/_plugins/generators/plugin_single_source/pages/how_to_spec.rb
  spec/app/_plugins/generators/plugin_single_source/pages/overview_spec.rb
  spec/app/_plugins/generators/plugin_single_source/plugin/unversioned_spec.rb
  spec/app/_plugins/generators/plugin_single_source_generator_spec.rb
  spec/app/_plugins/generators/seo/index_spec.rb
  spec/app/_plugins/generators/seo/sitemap_spec.rb
  spec/fixtures/app/_hub/acme/kong-plugin/how-to/_local-testing.md
Labels: review:tech

#5775 [DOCU-3293] KIC+K GA release
  app/_assets/images/docs/konnect/konnect-runtime-instance-kic.png
  app/konnect/runtime-manager/kic.md
  app/konnect/updates.md
Labels: review:copyedit, ci:manual-approve:link-validation, pending:release

#5762 [DOCU-3062] Composite runtime groups
  app/_assets/images/docs/konnect/konnect-composite-rg.svg
  app/_assets/images/docs/konnect/konnect-invariances-child.png
  app/_assets/images/docs/konnect/konnect-invariances-composite.png
  app/_assets/images/docs/konnect/konnect-invariances-members.png
  app/_assets/images/docs/konnect/konnect-standard-rg.svg
  app/_data/docs_nav_konnect.yml
  app/konnect/analytics/index.md
  app/konnect/runtime-manager/composite-runtime-groups/conflicts.md
  app/konnect/runtime-manager/composite-runtime-groups/how-to.md
  app/konnect/runtime-manager/composite-runtime-groups/index.md
  app/konnect/runtime-manager/composite-runtime-groups/migrate.md
  app/konnect/runtime-manager/configuration/index.md
  app/konnect/runtime-manager/index.md
  app/konnect/updates.md
Labels: review:copyedit, ci:manual-approve:link-validation, review:sme, pending:release

#5781 mention requirement for outbound traffic for kic+konnect
  app/_src/kubernetes-ingress-controller/concepts/deployment.md
  app/konnect/network.md
  app/konnect/runtime-manager/kic.md
Labels: Kubernetes Team, review:general, pending:release

#5784 Removing note that KIC in Konnect is only for Enterprise tier today
  app/konnect/runtime-manager/kic.md
Labels: review:copyedit

#5776 Add missing urls to broken-link-checker's ignored_targets
  tools/broken-link-checker/config/ignored_targets.json
Labels: review:general

#5791 Update release versions for 2.8.4.2 & 3.3.1.0
  app/_data/kong_versions.yml
Labels: review:general

#5792 Fix kong.tools.queue changelog entry
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#5793 Fix Mesh changelog duplicate
  app/mesh/CHANGELOG.md
  app/mesh/changelog.md
Labels: review:general

#5794 chore: Fix broken links
  app/enterprise/2.1.x/deployment/installation/overview.md
  app/enterprise/2.2.x/deployment/installation/overview.md
  app/enterprise/2.3.x/deployment/installation/overview.md
  app/enterprise/2.4.x/deployment/installation/overview.md
  app/enterprise/2.5.x/deployment/installation/overview.md
  app/konnect/runtime-manager/index.md
  app/mesh/1.2.x/install.md
  app/mesh/1.3.x/install.md
  app/mesh/1.4.x/install.md
  app/mesh/1.5.x/install.md
  app/mesh/1.6.x/install.md
  archive/enterprise/1.3-x/deployment/installation/overview.md
  archive/enterprise/1.5.x/deployment/installation/overview.md
Labels: review:general

#5798 Change Services title to API Products on Roles reference
  app/konnect/org-management/teams-and-roles/roles-reference.md
Labels: review:general

#5796 Remove twitter and facebook sdks.
  app/_layouts/default.html
Labels: review:tech

#5778 Fix performance issue caused by plugin pages without `source_file`
  app/_plugins/generators/plugin_single_source/pages/configuration.rb
  app/_plugins/generators/plugin_single_source/pages/configuration_examples.rb
  app/_plugins/generators/plugin_single_source/plugin/release.rb
  app/_plugins/generators/plugin_single_source/plugin/schemas/base.rb
  spec/app/_plugins/generators/plugin_single_source/pages/configuration_examples_spec.rb
  spec/app/_plugins/generators/plugin_single_source/pages/configuration_spec.rb
  spec/app/_plugins/generators/plugin_single_source/plugin/release_spec.rb
Labels: review:tech

#5799 few wording tweaks prior to beta
  app/_data/docs_nav_konnect.yml
  app/konnect/getting-started/configure-mesh.md
  app/konnect/mesh-manager/index.md
  app/konnect/mesh-manager/service-mesh.md
Labels: review:copyedit

#5800 fix(request-transformer): header examples
  app/_hub/kong-inc/request-transformer/_index.md
Labels: review:copyedit

#5795 Clean up multiple auth methods doc
  app/_src/gateway/kong-plugins/authentication/allowing-multiple-authentication-methods.md
Labels: review:general

#5810 Change lighthouse config
  netlify.toml
Labels: review:general

#5809 feat(opentelemetry): support the parameter as referenceable
  app/_hub/kong-inc/opentelemetry/_changelog.md
Labels: review:tech

#5807 Update the output of /clustering/data-planes, which is out-of-date.
  app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Labels: review:general

#5812 Update using-ingress-with-grpc.md
  app/_src/kubernetes-ingress-controller/guides/using-ingress-with-grpc.md
Labels: review:general

#5811 Add hook that displays the total number of pages generated
  app/_plugins/hooks/total_pages.rb
Labels: review:tech

#5790 kic: add mention about FillIDs feature gate
  app/_src/kubernetes-ingress-controller/references/feature-gates.md
Labels: Kubernetes Team, review:general

#5783 DOCU-3314 Post-GA release of API Product Builder spec
  app/_data/docs_nav_konnect.yml
  app/konnect/updates.md
Labels: review:general, pending:release

#5819 decK file commands
  app/_data/docs_nav_deck_1.24.x.yml
  app/_src/deck/reference/deck_file.md
  app/_src/deck/reference/deck_file_add-plugins.md
  app/_src/deck/reference/deck_file_add-tags.md
  app/_src/deck/reference/deck_file_convert.md
  app/_src/deck/reference/deck_file_list-tags.md
  app/_src/deck/reference/deck_file_merge.md
  app/_src/deck/reference/deck_file_openapi2kong.md
  app/_src/deck/reference/deck_file_patch.md
  app/_src/deck/reference/deck_file_remove-tags.md
  app/_src/deck/reference/deck_file_validate.md
Labels: review:copyedit

#5818 Add sentence to ssl_cipher description
  app/_src/gateway/reference/configuration.md
Labels: review:copyedit

#5803 [DOCU-3224] Remove cassandra from 3.4
  app/_data/tables/support/gateway/versions/34.yml
  app/_includes/md/gateway/setup.md
  app/_includes/md/installation.md
  app/_src/deck/faqs.md
  app/_src/gateway/install/docker/index.md
  app/_src/gateway/kong-enterprise/analytics/index.md
  app/_src/gateway/kong-enterprise/analytics/reports.md
  app/_src/gateway/kong-enterprise/audit-log.md
  app/_src/gateway/kong-enterprise/fips-support/index.md
  app/_src/gateway/kong-plugins/authentication/oidc/cognito.md
  app/_src/gateway/kong-plugins/rate-limiting/algorithms/rate-limiting.md
  app/_src/gateway/plugin-development/access-the-datastore.md
  app/_src/gateway/plugin-development/custom-entities.md
  app/_src/gateway/production/clustering.md
  app/_src/gateway/production/deployment-topologies/index.md
  app/_src/gateway/production/deployment-topologies/traditional/index.md
  app/_src/gateway/production/tracing/index.md
  app/_src/gateway/reference/cli.md
  app/_src/gateway/reference/configuration.md
  app/_src/gateway/upgrade-v2.md
  app/konnect/getting-started/import.md
  autodoc-conf-ee/run.lua
Labels: review:general, review:copyedit, ci:manual-approve:link-validation

#5822 Add data-panel attribute to navtabs
  app/_plugins/blocks/navtabs.rb
Labels: review:general

#5832 Fix cookie_domain example
  app/_src/gateway/install/kubernetes/helm.md
  app/_src/gateway/install/kubernetes/openshift.md
  app/enterprise/2.1.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.2.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.3.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.4.x/deployment/installation/kong-on-kubernetes.md
  app/enterprise/2.5.x/deployment/installation/kong-on-kubernetes.md
  app/gateway/2.6.x/install-and-run/helm.md
  app/gateway/2.6.x/install-and-run/openshift.md
  app/gateway/2.7.x/install-and-run/helm.md
  app/gateway/2.7.x/install-and-run/openshift.md
  app/gateway/2.8.x/install-and-run/helm.md
  app/gateway/2.8.x/install-and-run/openshift.md
Labels: review:general

#5830 Update enable-rbac.md
  app/_src/gateway/production/access-control/enable-rbac.md
Labels: review:general, area/docs

#5827 Resolve DOCU-2969, update request parameters
  app/konnect/api/identity-management/identity-integration.md
Labels: review:general

#5834 Resolve DOCU-1791. Clarify db-backed instances only.
  app/_src/gateway/licenses/report.md
Labels: review:general

#5843 fix(.github): add missing group to sync-kuma-submodule
  .github/workflows/sync-kuma-submodule.yml
Labels: review:tech

#5816 Adding deck 1.24 including apiops guide
  app/_data/docs_nav_deck_1.24.x.yml
  app/_data/kong_versions.yml
  app/_src/deck/guides/apiops.md
  app/_src/deck/index.md
  app/_src/deck/reference/deck_file.md
  app/_src/deck/reference/deck_file_add-plugins.md
  app/_src/deck/reference/deck_file_add-tags.md
  app/_src/deck/reference/deck_file_list-tags.md
  app/_src/deck/reference/deck_file_merge.md
  app/_src/deck/reference/deck_file_openapi2kong.md
  app/_src/deck/reference/deck_file_patch.md
  app/_src/deck/reference/deck_file_remove-tags.md
Labels: review:copyedit

#5820 [DOCU-3301] Add PostgreSQL 15 note to upgrade doc
  app/_src/gateway/upgrade-v2.md
Labels: review:copyedit

#5847 Revert "[KAG-1585] Convert install pages to use Cloudsmith"
  .github/workflows/install-instructions-test.yml
  app/_data/installation/gateway.yml
  app/_plugins/generators/versions.rb
  app/_src/gateway/install/docker/build-custom-images.md
  app/_src/gateway/install/linux/amazon-linux.md
  app/_src/gateway/install/linux/debian.md
  app/_src/gateway/install/linux/rhel.md
  app/_src/gateway/install/linux/ubuntu.md
  app/_src/gateway/kong-enterprise/fips-support.md
  app/_src/gateway/kong-enterprise/fips-support/install.md
  app/gateway/2.6.x/install-and-run/amazon-linux.md
  app/gateway/2.6.x/install-and-run/centos.md
  app/gateway/2.6.x/install-and-run/debian.md
  app/gateway/2.6.x/install-and-run/rhel.md
  app/gateway/2.6.x/install-and-run/ubuntu.md
  app/gateway/2.7.x/install-and-run/amazon-linux.md
  app/gateway/2.7.x/install-and-run/centos.md
  app/gateway/2.7.x/install-and-run/debian.md
  app/gateway/2.7.x/install-and-run/rhel.md
  app/gateway/2.7.x/install-and-run/ubuntu.md
  app/gateway/2.8.x/install-and-run/amazon-linux.md
  app/gateway/2.8.x/install-and-run/centos.md
  app/gateway/2.8.x/install-and-run/debian.md
  app/gateway/2.8.x/install-and-run/rhel.md
  app/gateway/2.8.x/install-and-run/ubuntu.md
  jekyll-dev.yml
  jekyll.yml
  tools/install-tester/.gitignore
  tools/install-tester/README.md
  tools/install-tester/config/expected-failures.yaml
  tools/install-tester/config/jobs.yaml
  tools/install-tester/config/setup.yaml
  tools/install-tester/execute-in-docker.js
  tools/install-tester/index.js
  tools/install-tester/instruction-extractor.js
  tools/install-tester/package-lock.json
  tools/install-tester/package.json
Labels: review:general, ci:manual-approve:link-validation

#5846 Pin vale version
  .github/workflows/linting.yml
Labels: review:general

#5849 Use environment instead of branch-specific context
  netlify.toml
Labels: review:tech

#5848 fix: Remove inaccurate note about runtime instances
  app/konnect/compatibility.md
Labels: review:general

#5808 Add Identity Admin and Audit Logs Setting Roles
  app/konnect/org-management/teams-and-roles/roles-reference.md
  app/konnect/updates.md
Labels: review:copyedit

#5855 Fix mobile experience
  app/_assets/javascripts/app.js
  app/_assets/javascripts/navbar.js
  app/_includes/nav-v2.html
Labels: review:tech

#5852 Fix anchor links generation
  app/_includes/anchor_links.html
Labels: review:tech

#5845 Update kong-enterprise.md
  app/_src/kubernetes-ingress-controller/deployment/kong-enterprise.md
Labels: review:general

#5831 chore(*): add more explanation when using EKS IRSA to access RDS database
  app/_src/gateway/kong-enterprise/aws-iam-auth-to-rds-database.md
Labels: review:general

#5826 Update for v2.8, resolve DOCU-2334.
  app/gateway/2.8.x/get-started/comprehensive/expose-services.md
Labels: review:general

#5823 Add ability to render specific products and plugin hub
  .vale.ini
  README.md
  app/_plugins/generators/plugin_single_source_generator.rb
  app/_plugins/hooks/products_renderer.rb
  spec/app/_plugins/generators/hooks/products_renderer_spec.rb
Labels: review:tech

#5859 Revert "Revert "[KAG-1585] Convert install pages to use Cloudsmith""
  .github/workflows/install-instructions-test.yml
  app/_data/installation/gateway.yml
  app/_plugins/generators/versions.rb
  app/_src/gateway/install/docker/build-custom-images.md
  app/_src/gateway/install/linux/amazon-linux.md
  app/_src/gateway/install/linux/debian.md
  app/_src/gateway/install/linux/rhel.md
  app/_src/gateway/install/linux/ubuntu.md
  app/_src/gateway/kong-enterprise/fips-support.md
  app/_src/gateway/kong-enterprise/fips-support/install.md
  app/gateway/2.6.x/install-and-run/amazon-linux.md
  app/gateway/2.6.x/install-and-run/centos.md
  app/gateway/2.6.x/install-and-run/debian.md
  app/gateway/2.6.x/install-and-run/rhel.md
  app/gateway/2.6.x/install-and-run/ubuntu.md
  app/gateway/2.7.x/install-and-run/amazon-linux.md
  app/gateway/2.7.x/install-and-run/centos.md
  app/gateway/2.7.x/install-and-run/debian.md
  app/gateway/2.7.x/install-and-run/rhel.md
  app/gateway/2.7.x/install-and-run/ubuntu.md
  app/gateway/2.8.x/install-and-run/amazon-linux.md
  app/gateway/2.8.x/install-and-run/centos.md
  app/gateway/2.8.x/install-and-run/debian.md
  app/gateway/2.8.x/install-and-run/rhel.md
  app/gateway/2.8.x/install-and-run/ubuntu.md
  jekyll-dev.yml
  jekyll.yml
  tools/install-tester/.gitignore
  tools/install-tester/README.md
  tools/install-tester/config/expected-failures.yaml
  tools/install-tester/config/jobs.yaml
  tools/install-tester/config/setup.yaml
  tools/install-tester/execute-in-docker.js
  tools/install-tester/index.js
  tools/install-tester/instruction-extractor.js
  tools/install-tester/package-lock.json
  tools/install-tester/package.json
Labels: review:general

#5861 fix(admin-api): typos in admins reference
  app/_src/gateway/admin-api/admins/reference.md
  app/enterprise/2.1.x/admin-api/admins/reference.md
  app/enterprise/2.2.x/admin-api/admins/reference.md
  app/enterprise/2.3.x/admin-api/admins/reference.md
  app/enterprise/2.4.x/admin-api/admins/reference.md
  app/enterprise/2.5.x/admin-api/admins/reference.md
  app/gateway/2.6.x/admin-api/admins/reference.md
  app/gateway/2.7.x/admin-api/admins/reference.md
  app/gateway/2.8.x/admin-api/admins/reference.md
  archive/enterprise/0.35-x/admin-api/admins/reference.md
  archive/enterprise/0.36-x/admin-api/admins/reference.md
  archive/enterprise/1.3-x/admin-api/admins/reference.md
  archive/enterprise/1.5.x/admin-api/admins/reference.md
Labels: review:general

#5770 Add new distros, drop End-Of-Life distributions, and rename amazonlinux-2022 to 2023
  app/_data/tables/support/gateway/packages.yml
  app/_data/tables/support/gateway/versions/28.yml
  app/_data/tables/support/gateway/versions/30.yml
  app/_data/tables/support/gateway/versions/31.yml
  app/_data/tables/support/gateway/versions/32.yml
  app/_data/tables/support/gateway/versions/33.yml
  app/_data/tables/support/gateway/versions/34.yml
  app/_src/gateway/support/index.md
Labels: review:sme

#5844 Update minikube.md
  app/_src/kubernetes-ingress-controller/deployment/minikube.md
Labels: review:general

#5863 chore: 3.3 > 3.4 nav changes
  app/_data/docs_nav_gateway_3.4.x.yml
Labels: review:general

#5872 Add foreman gem to Gemfile
  Gemfile
  Gemfile.lock
  Makefile
Labels: review:tech

#5873 docs(consumer-groups): add api-specs for first-class consumer-group changes
  api-specs/Gateway-EE/3.3/kong-ee-3.3.json
  api-specs/Gateway-EE/3.3/kong-ee-3.3.yaml
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-EE/3.4/overlay.yaml
  api-specs/Gateway-OSS/3.3/kong-oss-33.json
  api-specs/Gateway-OSS/3.3/kong-oss-33.yaml
  api-specs/Gateway-OSS/yaml/overlay.yaml
Labels: review:general
