Repository Kong/docs.konghq.com, pull requests merged in 2023-03, with the labels that each got.

#5223 chore: Add datadog-tracing to konnect plugin priority list
  app/_includes/md/plugin-priority.md
  app/_src/gateway/plugin-development/custom-logic.md
  app/konnect/runtime-manager/plugins.md
Labels: review:general

#5226 Fix: Disable icon expanding on install overview
  app/_src/gateway/install/index.md
Labels: review:general

#5225 Fix some security vulnerabilities
  app/_includes/head.html
  package-lock.json
  package.json
Labels: review:tech

#5232 Update openshift.md
  app/_src/gateway/install/kubernetes/openshift.md
Labels: review:general

#5216 docs: GRPCRoute guide
  app/_src/kubernetes-ingress-controller/guides/using-ingress-with-grpc.md
  app/_src/kubernetes-ingress-controller/references/gateway-api-support.md
Labels: Kubernetes Team, review:general

#5196 Update KIC troubleshooting for 2.9 and add GWAPI port note
  .github/styles/kong/auto-ignore.txt
  app/_data/docs_nav_kic_2.8.x.yml
  app/_src/kubernetes-ingress-controller/deployment/admission-webhook.md
  app/_src/kubernetes-ingress-controller/guides/using-gateway-api.md
  app/_src/kubernetes-ingress-controller/troubleshooting.md
Labels: do not merge, review:general, review:copyedit

#5224 Fix Konnect nav link for vaults
  app/_data/docs_nav_konnect.yml
Labels: review:general

#5235 fix(correlation-id): example log correct header
  app/_hub/kong-inc/correlation-id/_index.md
Labels: review:general

#5229 Make ruby check fail instead of printing a warning
  Makefile
Labels: review:tech

#5220 docs(mesh): update version support table with kong mesh 2.1.x
  app/_src/mesh/support-policy.md
Labels: review:general

#5238 Update dictionary.txt with word: exfiltration
  .github/styles/kongplugins/dictionary.txt
Labels: review:general

#5247 The metric's section in StatsD plugin doesn't render a table
  app/_hub/kong-inc/statsd/_index.md
Labels: review:copyedit

#5227 fix(getting-started) app reg is now on all runtimes
  app/konnect/getting-started/app-registration.md
Labels: ready, review:copyedit

#5243 chore: bump .ruby-version to 3.1.3 to allow building on arm64
  .ruby-version
  Gemfile.lock
Labels: review:tech

#5256 chore(kic): extract common docs to includes
  app/_includes/md/kic/deploy-kic.md
  app/_includes/md/kic/kong-enterprise-license-secret.md
  app/_src/kubernetes-ingress-controller/deployment/aks.md
  app/_src/kubernetes-ingress-controller/deployment/eks.md
  app/_src/kubernetes-ingress-controller/deployment/gke.md
  app/_src/kubernetes-ingress-controller/deployment/k4k8s-enterprise.md
  app/_src/kubernetes-ingress-controller/deployment/kong-enterprise.md
  app/_src/kubernetes-ingress-controller/deployment/minikube.md
  app/_src/kubernetes-ingress-controller/guides/cert-manager.md
  app/_src/kubernetes-ingress-controller/guides/using-gateway-discovery.md
Labels: Kubernetes Team, review:general

#5236 Backport deck entities topic to avoid broken links
  app/_data/docs_nav_deck_1.10.x.yml
  app/_data/docs_nav_deck_1.11.x.yml
  app/_data/docs_nav_deck_1.12.x.yml
  app/_data/docs_nav_deck_1.13.x.yml
  app/_data/docs_nav_deck_1.14.x.yml
  app/_data/docs_nav_deck_1.15.x.yml
  app/_data/docs_nav_deck_1.16.x.yml
  app/_data/docs_nav_deck_1.7.x.yml
  app/_data/docs_nav_deck_1.8.x.yml
  app/_data/docs_nav_deck_1.9.x.yml
Labels: review:general

#5209 [DOCU-2985] Mention document_objects as not managed by decK
  app/_src/deck/reference/entities.md
Labels: review:copyedit

#5207 [DOCU-2837] Fix OpenTelemetry plugin example
  app/_hub/kong-inc/opentelemetry/_index.md
Labels: review:general

#5248 [DOCU-2526] Removed outdated steps from Konnect Docker install
  app/konnect/getting-started/configure-runtime.md
Labels: review:general

#5250 chore(mocking): clarify support for Swagger 2.0 and OpenAPI 3.0
  app/_hub/kong-inc/mocking/_index.md
Labels: review:general

#5233 fix: align examples to behaviour of add.headers
  app/_hub/kong-inc/response-transformer/_index.md
Labels: review:general

#5211 [DOCU-2845] SAML plugin: Don't include header and footer with cert
  app/_hub/kong-inc/saml/_index.md
Labels: review:copyedit

#5264 Fix top-cta link
  app/_includes/nav-v2.html
Labels: review:general

#5263 Datadog plugin fix: add enterprise tag
  app/_hub/kong-inc/datadog-tracing/_index.md
Labels: review:general

#5261 fixed the url for OSS
  app/_src/gateway/install/kubernetes/kubectl.md
Labels: review:general

#5230 fix(kic): fix kubernetes ingress controller docs
  .github/styles/kong/dictionary.txt
  app/_src/kubernetes-ingress-controller/concepts/deployment.md
  app/_src/kubernetes-ingress-controller/guides/upgrade-kong-3x.md
  app/_src/kubernetes-ingress-controller/references/annotations.md
  app/_src/kubernetes-ingress-controller/references/cli-arguments.md
Labels: review:sme

#5146 docs(kic): update prometheus labels for KIC 2.9.x
  app/_src/kubernetes-ingress-controller/references/prometheus.md
Labels: Kubernetes Team, review:general

#5269 fix(kic): router_flavor mode
  app/_src/kubernetes-ingress-controller/references/supported-router-flavors.md
Labels: review:general

#5268 Typo in Configure Data Plane Resilience
  app/_src/gateway/kong-enterprise/cp-outage-handling.md
Labels: review:copyedit

#5244 Update sync-submodules
  .github/workflows/sync-submodules.yml
Labels: review:tech

#5277 Fix absolute links in link checker
  tools/broken-link-checker/lib/src-to-urls.js
Labels: review:tech

#5276 [DOCU-3031] Split RM troubleshooting topic
  app/konnect/runtime-manager/runtime-instances/install.md
  app/konnect/runtime-manager/runtime-instances/upgrade.md
  app/konnect/runtime-manager/troubleshoot.md
  app/konnect/runtime-manager/version-compatibility.md
Labels: review:general

#5273 chore(*): docker read-only mode docs
  app/_src/gateway/install/docker/index.md
Labels: review:copyedit

#5265 Fix KIC install links
  app/gateway-oss/2.1.x/kong-for-kubernetes/install.md
  app/gateway-oss/2.2.x/kong-for-kubernetes/install.md
  app/gateway-oss/2.3.x/kong-for-kubernetes/install.md
  app/gateway-oss/2.4.x/kong-for-kubernetes/install.md
  app/gateway-oss/2.5.x/kong-for-kubernetes/install.md
  app/gateway/2.6.x/install-and-run/kubernetes.md
  app/gateway/2.7.x/install-and-run/kubernetes.md
  app/gateway/2.8.x/install-and-run/kubernetes.md
  app/kubernetes-ingress-controller/1.0.x/deployment/kong-enterprise.md
  app/kubernetes-ingress-controller/1.1.x/deployment/kong-enterprise.md
  app/kubernetes-ingress-controller/1.2.x/deployment/kong-enterprise.md
  app/kubernetes-ingress-controller/1.3.x/deployment/kong-enterprise.md
  app/kubernetes-ingress-controller/2.0.x/deployment/kong-enterprise.md
  app/kubernetes-ingress-controller/2.1.x/deployment/kong-enterprise.md
  app/kubernetes-ingress-controller/2.2.x/deployment/kong-enterprise.md
  archive/gateway-oss/1.4.x/kong-for-kubernetes/install.md
  archive/gateway-oss/1.5.x/kong-for-kubernetes/install.md
  archive/gateway-oss/2.0.x/kong-for-kubernetes/install.md
Labels: review:general

#5278 docs(mesh): don't refer to Kuma in UBI instructions
  app/_src/mesh/features/ubi-images.md
  app/mesh/1.6.x/features/ubi-images.md
Labels: review:general

#5283 [DOCU-3044] Remove datadog-tracing plugin
  app/_data/tables/plugin_index.yml
  app/_data/tables/version_errors_konnect.yml
  app/_hub/kong-inc/datadog-tracing/_index.md
  app/_hub/kong-inc/datadog-tracing/versions.yml
  app/_includes/md/plugin-priority.md
  app/gateway/changelog.md
  app/konnect/updates.md
Labels: review:general

#5279 Aumotate Kong Mesh redirects generation from Kuma
  app/_mesh_redirects
  app/_plugins/generators/alias_generator.rb
  app/_redirects
  spec/fixtures/app/_src/.repos/kuma/app/_common_redirects
Labels: review:tech

#5286 [DOCU-3045] Remove MacOS installation docs
  app/_data/docs_nav_gateway_2.6.x.yml
  app/_data/docs_nav_gateway_2.7.x.yml
  app/_data/docs_nav_gateway_2.8.x.yml
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/tables/install_options.yml
  app/_redirects
  app/_src/gateway/install/macos.md
  app/gateway-oss/2.1.x/index.md
  app/gateway-oss/2.2.x/index.md
  app/gateway/2.6.x/install-and-run/index.md
  app/gateway/2.6.x/install-and-run/macos.md
  app/gateway/2.7.x/install-and-run/index.md
  app/gateway/2.7.x/install-and-run/macos.md
  app/gateway/2.8.x/install-and-run/index.md
  app/gateway/2.8.x/install-and-run/macos.md
Labels: review:general

#5237 fix(upstreams): health api schema
  app/_src/gateway/admin-api/index.md
Labels: review:general

#5287 Add a note about integrating Kong Manager with MFA
  app/_src/gateway/kong-manager/auth/index.md
Labels: review:copyedit

#5289 fix routes endpoint in jwt plugin
  app/_hub/kong-inc/jwt/_index.md
Labels: review:general

#5290 [DOCU-2506] Style guide updates
  app/_data/docs_nav_contributing.yml
  app/_hub/_init/my-extension/_index.md
  app/contributing/markdown-rules.md
  app/contributing/notices.md
  app/contributing/plugin-docs.md
  app/contributing/style-guide.md
  app/contributing/user-interfaces.md
Labels: review:copyedit

#5291 3.2.2.0 Changelog
  app/gateway/changelog.md
Labels: review:general

#5270 feat(proxy-cache): add ignore_uri_case to configuring cache-key uri to be handled as lowercase
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/proxy-cache/_index.md
Labels: blocked:kong, do not merge, review:general

#5131 Added aws-request-signing.
  .github/styles/kongplugins/auto-ignore.txt
  app/_assets/images/icons/hub/TheLEGOGroup_aws-request-signing.png
  app/_hub/TheLEGOGroup/aws-request-signing/_index.md
Labels: pending:plugin, review:sme

#5300 Add system accounts UI description.
  app/konnect/org-management/system-accounts.md
Labels: review:copyedit

#5301 chore(kic): fix dead links
  app/_src/kubernetes-ingress-controller/troubleshooting.md
  app/kubernetes-ingress-controller/1.0.x/troubleshooting.md
  app/kubernetes-ingress-controller/1.1.x/troubleshooting.md
  app/kubernetes-ingress-controller/1.2.x/troubleshooting.md
  app/kubernetes-ingress-controller/1.3.x/troubleshooting.md
  app/kubernetes-ingress-controller/2.0.x/troubleshooting.md
  app/kubernetes-ingress-controller/2.1.x/troubleshooting.md
  app/kubernetes-ingress-controller/2.2.x/troubleshooting.md
Labels: review:general

#5297 Fix navbar spacing issues
  app/_assets/stylesheets/base.less
  app/_assets/stylesheets/header-v2.less
  app/_includes/nav-v2.html
Labels: review:general

#5298 docs(expressions): use `--form-string` for curl
  app/_src/gateway/key-concepts/routes/expressions.md
Labels: review:tech, review:general

#5296 decK: consumer groups support
  app/_src/deck/reference/entities.md
Labels: review:general

#5302 chore(kic): add missing nav section for gateway API in 2.4
  app/_data/docs_nav_kic_2.4.x.yml
Labels: Kubernetes Team, review:general

#5295 Fix default rate limiting strategy in Konnect
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
  app/_hub/kong-inc/rate-limiting-advanced/_v1.md
  app/_hub/kong-inc/rate-limiting/_index.md
  app/_hub/kong-inc/response-ratelimiting/_index.md
  app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md
Labels: review:general

#5294 [DOCU-3027] Combine runtime instance overview w/ Dashboard topic.
  app/_assets/images/icons/documentation/cloud-icon-color.svg
  app/_data/docs_nav_konnect.yml
  app/_data/tables/install_options_konnect.yml
  app/_includes/install.html
  app/konnect/runtime-manager/runtime-instances/index.md
Labels: review:copyedit

#5319 Fix: Plugin priority changelog for 3.0
  app/_src/gateway/upgrade.md
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#5320 [Fix] Add passphrase param to certificates object
  app/_src/gateway/admin-api/admin-api-3.0.x.md
  app/_src/gateway/admin-api/index.md
  app/gateway/2.8.x/admin-api/index.md
Labels: review:general

#5323 GatewayAlpha feature-gate added to grpc guide
  app/_src/kubernetes-ingress-controller/guides/using-ingress-with-grpc.md
Labels: Kubernetes Team, review:copyedit, area/gateway-api

#5202 Fix upgrade paths for 3.2
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_src/gateway/migrate-ce-to-ke.md
  app/_src/gateway/upgrade-v2.md
Labels: do not merge, review:general, review:sme

#5315 Release: decK 1.19.1
  app/_data/kong_versions.yml
  app/_src/deck/reference/deck_dump.md
  app/_src/deck/reference/deck_reset.md
  app/_src/deck/reference/deck_sync.md
Labels: do not merge, review:general, ci:manual-approve:generated-files

#5010 [DOCU-2759] Updated Service Hub Overview & Service Overview
  .github/styles/kong/dictionary.txt
  app/_assets/images/docs/konnect/konnect-service-package-versions.png
  app/_assets/images/docs/konnect/konnect-service-package.png
  app/_assets/images/docs/konnect/konnect-servicehub-placeholder.png
  app/_assets/images/docs/konnect/konnect-servicehub.png
  app/_assets/images/docs/konnect/konnect_service_docs_description.png
  app/_assets/images/docs/konnect/konnect_service_docs_spec.png
  app/_assets/images/docs/konnect/konnect_service_docs_spec_edit.png
  app/_assets/images/docs/konnect/konnect_service_docs_spec_view.png
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/dev-portal/index.md
  app/konnect/getting-started/publish-service.md
  app/konnect/runtime-manager/gateway-config.md
  app/konnect/servicehub/enable-route-plugin.md
  app/konnect/servicehub/enable-service-plugin.md
  app/konnect/servicehub/index.md
  app/konnect/servicehub/manage-services.md
  app/konnect/servicehub/service-documentation.md
  app/konnect/servicehub/service-versions.md
  app/konnect/updates.md
Labels: do not merge, review:sme, pending:release

#5251 feat(logging): add workspace name in the logging payload
  app/_includes/md/plugins-hub/json-object-log.md
  app/_includes/md/plugins-hub/log-format.md
Labels: review:copyedit

#5328 docs(hybrid): config are cached in LMDB instead of JSON after 3.0
  app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Labels: review:copyedit

#5329 Add initial draft of Konnect API errors
  app/_data/konnect_errors.yml
  app/konnect/api/errors.md
Labels: review:general

#5334 [DOCU-3047] Release: Gateway 3.2.2.0
  app/gateway/changelog.md
Labels: review:general

#5333 AppDynamics: Set `bundled:false` to default for all versions
  app/_hub/kong-inc/app-dynamics/_index.md
  app/_hub/kong-inc/app-dynamics/versions.yml
Labels: review:general

#3719 Update index.md to include details about JWK cache duration
  app/_hub/kong-inc/openid-connect/_index.md
Labels: review:sme

#5098 [docu-2785] Custom reports
  .github/styles/kong/dictionary.txt
  .prettierignore
  app/_assets/images/docs/konnect/custom-reports/api-usage-by-application.png
  app/_assets/images/docs/konnect/custom-reports/latency-payments-api-30.png
  app/_assets/images/docs/konnect/custom-reports/total-api-requests.png
  app/_assets/images/docs/konnect/custom-reports/total-api-usage-by-application-minute.png
  app/_assets/images/docs/konnect/custom-reports/total-usage-accounts-api-30.png
  app/_assets/stylesheets/page.less
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/analytics/generate-reports.md
  app/konnect/analytics/index.md
  app/konnect/analytics/reference.md
  app/konnect/analytics/services-and-routes.md
  app/konnect/analytics/summary-dashboard.md
  app/konnect/analytics/use-cases.md
  app/konnect/org-management/teams-and-roles/teams-reference.md
  app/konnect/updates.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation, review:sme, pending:release

#5330 Clarified where admin SMTP properties are set in Hybrid deployment
  app/_src/gateway/kong-manager/configuring-to-send-email.md
Labels: review:general

#5246 Update src files that are in the new Kuma in Production section
  app/_data/docs_nav_mesh_2.1.x.yml
  tests/edit_link.test.js
Labels: review:general

#5321 [Fix] Update Support policy table
  app/_data/docs_nav_gateway_2.8.x.yml
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_src/gateway/support/index.md
  app/gateway/2.8.x/support-policy.md
Labels: review:general

#5348 Add the ability to customise the stability banner
  app/_layouts/docs-v2.html
  app/_src/kubernetes-ingress-controller/guides/using-multiple-backends.md
Labels: review:general

#5322 [DOCU-3025] Combine runtime manager and runtime groups overviews
  app/_redirects
  app/konnect/runtime-manager/index.md
  app/konnect/runtime-manager/runtime-groups/index.md
Labels: review:general

#5356 Update Kong Gateway patch version
  app/_data/kong_versions.yml
Labels: review:general

#5314 feat(kaudit): Add info about log messages
  app/_data/docs_nav_konnect.yml
  app/konnect/org-management/audit-logging/reference.md
Labels: review:general, review:sme

#5339 Imperva API Security plugin
  .github/styles/kongplugins/dictionary.txt
  .github/styles/kongplugins/plugin-ignore.txt
  app/_assets/images/icons/hub/imperva_imp-appsec-connector.png
  app/_hub/imperva/imp-appsec-connector/_index.md
Labels: review:copyedit

#5326 docs(http-log): plugin schema update for 3.3
  app/_hub/kong-inc/http-log/_index.md
Labels: review:general

#5357 [DOCU-3024] Runtime manager IA
  app/_assets/images/icons/documentation/cloud-icon-color.svg
  app/_data/docs_nav_konnect.yml
  app/_data/tables/install_options_konnect.yml
  app/_includes/install.html
  app/_redirects
  app/konnect/api/index.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/reference/plugins.md
  app/konnect/runtime-manager/backup-restore.md
  app/konnect/runtime-manager/configuration/consumer-groups.md
  app/konnect/runtime-manager/configuration/index.md
  app/konnect/runtime-manager/configuration/vaults/how-to.md
  app/konnect/runtime-manager/configuration/vaults/index.md
  app/konnect/runtime-manager/declarative-config.md
  app/konnect/runtime-manager/index.md
  app/konnect/runtime-manager/runtime-groups/dashboard.md
  app/konnect/runtime-manager/runtime-groups/index.md
  app/konnect/runtime-manager/runtime-groups/manage.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-aws.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-azure.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-conf.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-docker.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-kubernetes.md
  app/konnect/runtime-manager/runtime-instances/index.md
  app/konnect/runtime-manager/runtime-instances/upgrade.md
  app/konnect/runtime-manager/runtime-instances/verify-instance.md
  app/konnect/runtime-manager/troubleshoot.md
  app/konnect/runtime-manager/version-compatibility.md
  app/konnect/updates.md
Labels: review:general

#5327 [DOCU-2994] Release: Gateway 2.8.4.0
  .github/styles/kongplugins/dictionary.txt
  app/_data/kong_versions.yml
  app/_hub/kong-inc/aws-lambda/_index.md
  app/gateway/2.8.x/reference/configuration.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation, ci:prevent-merge:generated-files, ci:manual-approve:generated-files

#5369 fix deck > konnect link
  app/_src/deck/reference/deck.md
Labels: review:general

#5362 [DOCU-3145] Third-party plugin layout adjustments
  app/_hub/imperva/imp-appsec-connector/_index.md
  app/_includes/header.html
  app/_includes/hub_cards.html
  app/_layouts/extension.html
Labels: review:general

#5370 [DOCU-3149] Referenceable plugin fields table
  app/_src/gateway/kong-enterprise/secrets-management/index.md
Labels: review:general, review:copyedit

#5375 Fix Imperva plug-in name to be more clear.
  app/_hub/imperva/imp-appsec-connector/_index.md
Labels: review:general

#5364 Contributing guide: add missing front matter options
  app/contributing/markdown-rules.md
Labels: review:copyedit

#5363 Remove ArecaBay plugin
  app/_assets/images/icons/hub/arecabay_ab-microsensor.png
  app/_hub/arecabay/ab-microsensor/_index.md
  app/_redirects
Labels: review:general
