Repository Kong/docs.konghq.com, pull requests merged in 2023-10, with the labels that each got.

#6186 chore: 3.4.1.0 changelog
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general, review:sme, pending:release

#6201 feat: support HTTP query parameters in expression routes.
  app/_src/gateway/reference/router-expressions-language.md
Labels: review:tech, pending:release, 3.4.x

#6212 chore: Remove summit hackathon banner
  app/_assets/entrypoints/application.js
  app/_assets/stylesheets/header.less
  app/_includes/nav-v2.html
Labels: review:general, skip-changelog

#6155 Feat: PKI Certs for CP/DP authentication
  app/_data/docs_nav_konnect.yml
  app/konnect/gateway-manager/data-plane-nodes/renew-certificates.md
  app/konnect/gateway-manager/data-plane-nodes/secure-communications.md
  app/konnect/updates.md
Labels: review:general, pending:release

#6210 Update: Docs 404 page
  app/404.html
  app/_assets/stylesheets/pages/404.less
Labels: review:general, review:copyedit

#6166 feat: OIDC IdP Team Mapping functionality
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/access-and-approval/add-teams.md
  app/konnect/dev-portal/access-and-approval/manage-teams.md
  app/konnect/updates.md
Labels: review:copyedit

#6222 Revert "feat: OIDC IdP Team Mapping functionality (#6166)"
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/access-and-approval/add-teams.md
  app/konnect/dev-portal/access-and-approval/manage-teams.md
  app/konnect/updates.md
Labels: review:general, skip-changelog

#6220 Update: Add link to example spec for decK APIOps guide
  .github/styles/kong/dictionary.txt
  app/_src/deck/guides/apiops.md
Labels: review:copyedit

#6205 Update: Add latency units to JSON log format reference for logging plugins
  app/_includes/md/plugins-hub/json-object-log.md
Labels: review:general

#6221 Update: Mark the canary plugin as not recommended for use with KIC
  app/_hub/kong-inc/canary/_metadata.yml
  app/_hub/kong-inc/canary/overview/_index.md
Labels: review:copyedit

#6225 Fix broken variable in Gateway overview doc
  app/_src/gateway/index.md
Labels: review:general, skip-changelog

#6206 Update: Add cache names to mem_cache_size
  app/_src/gateway/reference/configuration.md
  app/gateway/2.8.x/reference/configuration.md
Labels: review:general, ci:manual-approve:link-validation, ci:manual-approve:generated-files

#6226 fix: Use framework instead of philosophy [skip ci]
  app/_hub/kong-inc/canary/_metadata.yml
  app/_hub/kong-inc/canary/overview/_index.md
Labels: review:general, skip-changelog

#6214 Automated Changelog update
  changelog.md
Labels: do not merge, review:copyedit, skip-changelog

#6229 chore: Minor adjustments to changelog generator [skip ci]
  .github/workflows/generate-changelog.yml
  tools/changelog-generator/changelog.js
Labels: review:general, skip-changelog

#6227 Patching add-teams.md
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/access-and-approval/add-teams.md
  app/konnect/dev-portal/access-and-approval/manage-teams.md
  app/konnect/updates.md
Labels: review:copyedit, pending:release

#6241 fix: Fix the URLs
  app/_data/docs_nav_kic_2.11.x.yml
  app/_data/docs_nav_kic_2.12.x.yml
Labels: review:general, skip-changelog

#6240 docs(mesh): adjust external ca verification docs since 2.4.0
  app/_src/mesh/features/acmpca.md
  app/_src/mesh/features/cert-manager.md
  app/_src/mesh/features/vault.md
Labels: review:tech, review:general

#6235 fix: Plugin tiers for konnect-incompatible plugins
  app/_assets/stylesheets/page.less
  app/_hub/kong-inc/jwt-signer/_metadata.yml
  app/_hub/kong-inc/key-auth-enc/_metadata.yml
  app/_hub/kong-inc/openwhisk/_metadata.yml
  app/_hub/kong-inc/vault-auth/_0.3.0/_metadata.yml
  app/_hub/kong-inc/vault-auth/_metadata.yml
  app/_layouts/extension.html
Labels: review:general

#6193 Fix issue with Vale reporting incorrect things as broken
  .github/workflows/linting.yml
Labels: do not merge, review:general

#6242 Set concurrency.cancel-in-progress for PRs
  .github/workflows/check-links.yml
  .github/workflows/generate-changelog.yml
  .github/workflows/linting.yml
  .github/workflows/run-tests.yml
  .github/workflows/scheduled-broken-link-checker.yml
Labels: review:tech

#6204 Fix: Add missing info endpoints to Gateway Admin API EE spec [skip ci]
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
Labels: review:general

#6243 chore: update changelog
  app/konnect/updates.md
Labels: review:general, skip-changelog

#6219 fix: Kong Ingress on Minikube
  app/_includes/md/kic/deploy-kic.md
  app/_includes/md/kic/http-test-routing-resource.md
  app/_src/kubernetes-ingress-controller/deployment/minikube.md
Labels: review:tech

#6237 fix: Kong for Kubernetes
  app/_src/kubernetes-ingress-controller/deployment/k4k8s.md
Labels: review:tech

#6233 fix: Configuring ACL Plugin
  app/_includes/md/kic/http-test-routing-resource.md
  app/_includes/md/kic/http-test-routing.md
  app/_src/kubernetes-ingress-controller/guides/configure-acl-plugin.md
  app/_src/kubernetes-ingress-controller/guides/using-external-service.md
Labels: review:tech

#6246 Fix Auto Close Kong Issues GH action
  .github/workflows/auto-close-kong-issues.yml
Labels: review:general

#6245 Fix: Badge alignment
  app/_assets/stylesheets/badges.less
  app/_src/gateway/index.md
  app/contributing/markdown-rules.md
Labels: review:general, skip-changelog

#6259 Raise an exception when two or more pages have the same output path
  app/_plugins/hooks/url_conflicts.rb
Labels: review:general

#6255 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6263 update Konnect docs screenshots to include MM
  app/assets/images/products/konnect/api-products/api-products-docs.png
  app/assets/images/products/konnect/api-products/api-products-manage.png
  app/assets/images/products/konnect/api-products/api-products-overview.png
  app/assets/images/products/konnect/gateway-manager/konnect-control-plane-dashboard.png
  app/assets/images/products/konnect/gateway-manager/konnect-runtime-instance-kic.png
  app/assets/images/products/konnect/gateway-manager/konnect-vaults.png
  app/assets/images/products/konnect/gateway-manager/plugins/konnect-plugin-list.png
  app/assets/images/products/konnect/konnect-dashboard.png
  tools/screenshots/konnect/api-products/api-products-dashboard.yaml
  tools/screenshots/konnect/overview/control-plane-dashboard.yaml
  tools/screenshots/konnect/overview/konnect-dashboard.yaml
  tools/screenshots/konnect/plugins/plugin-list.yaml
  tools/screenshots/konnect/runtimes/kic.yaml
  tools/screenshots/konnect/vaults/overview.yaml
Labels: review:general, skip-changelog

#6260 fix path of HTTPBin in KIC auth guide
  app/_src/kic-v2/guides/allowing-multiple-authentication-methods.md
Labels: bug, review:general

#6252 Fix: curl examples for custom plugins schemas in Konnect
  app/konnect/gateway-manager/plugins/add-custom-plugin.md
  app/konnect/gateway-manager/plugins/update-custom-plugin.md
Labels: review:copyedit

#6267 Add github star button to Kong manager oss page
  app/_layouts/docs-v2.html
  app/_src/gateway/kong-manager-oss/index.md
Labels: review:general

#6278 Prevent link checker from running if `[skip ci]` is present in the PR's title
  .github/workflows/check-links.yml
Labels: review:general

#6275 Add Github Action that syncs kong-plugins submodule
  .github/workflows/sync-submodules.yml
Labels: review:tech

#6274 Don't run lighthouse on `dev`
  netlify.toml
Labels: review:general

#6272 update: Add generated mesh changelog to vale ignore list
  .github/workflows/linting.yml
Labels: review:tech, skip-changelog

#6280 Update: Salt plugin now supports new queue in 3.3+
  app/_hub/salt/salt/_metadata.yml
Labels: review:general, ci:manual-approve:linting

#6192 Update: Add info on cache locations in Gateway 2.x vs 3.x
  app/konnect/network-resiliency.md
Labels: review:general, review:copyedit

#6236 update: Third-party categorization
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/page.less
  app/_assets/stylesheets/pages/extension.less
  app/_hub/TheLEGOGroup/aws-request-signing/_metadata.yml
  app/_hub/amberflo/kong-plugin-amberflo/_metadata.yml
  app/_hub/imperva/imp-appsec-connector/_metadata.yml
  app/_hub/moesif/kong-plugin-moesif/_metadata.yml
  app/_hub/okta/okta/_metadata.yml
  app/_hub/optum/kong-response-size-limiting/_metadata.yml
  app/_hub/optum/kong-service-virtualization/_metadata.yml
  app/_hub/optum/kong-spec-expose/_metadata.yml
  app/_hub/optum/kong-splunk-log/_metadata.yml
  app/_hub/optum/kong-upstream-jwt/_metadata.yml
  app/_hub/salt/salt/_metadata.yml
  app/_hub/wallarm/wallarm/_metadata.yml
  app/_includes/hub_cards.html
  app/_includes/md/about-plugins.md
  app/_includes/plugins/about_this.html
  app/_layouts/extension.html
  app/hub/index.html
  jekyll-dev.yml
  jekyll.yml
Labels: do not merge, review:sme

#6277 DOCU-2842: Add `run-debug` command to Makefile
  Makefile
Labels: review:general

#6269 DOCU-3320: Add support for Mesh's `dev` release
  app/_data/docs_nav_mesh_dev.yml
  app/_plugins/generators/seo/index_entry_builder.rb
  app/_plugins/generators/utils/version.rb
  app/_plugins/generators/versions.rb
  jekyll-dev.yml
  jekyll.yml
  spec/app/_plugins/generators/seo/index_entry/versioned_page_spec.rb
  spec/fixtures/app/_data/docs_nav_mesh_dev.yml
  spec/fixtures/app/_data/kong_versions.yml
Labels: review:tech

#6287 Fix broken-link checker
  .github/workflows/check-links.yml
Labels: review:tech

#6294 Use `secrets.PAT` as token for submodule sync action
  .github/workflows/sync-submodules.yml
Labels: review:tech

#6285 Chore: Rename badge back to ENTERPRISE
  app/_assets/stylesheets/badges.less
Labels: review:general, skip-changelog

#6265 Update changelog generator [skip-ci]
  tools/changelog-generator/changelog.js
Labels: review:general, skip-changelog

#6304 Fix: Missing `ldaps` option in Kong Manager LDAP setup. Resolves DOCU-2529.
  app/_src/gateway/kong-manager/auth/ldap/configure.md
Labels: review:general

#6300 Fix: Konnect OIDC sign-in & sign-out redirect URIs
  app/konnect/org-management/oidc-idp.md
Labels: review:general

#6297 update: Remove Gateway 3.0 from supported versions and move to older versions table
  app/_src/gateway/support/browser.md
  app/_src/gateway/support/index.md
  app/_src/gateway/support/third-party.md
Labels: review:general

#6298 Release: Changelog and version bump for Gateway 3.4.1.1 and 3.4.2
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#6299 Release: Changelog and version bump for Gateway 3.3.1.1
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#6301 Release: Changelog and version bump for Gateway 3.2.2.5
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#6302 Release: Changelog and version bump for Gateway 3.1.1.6
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#6303 Release: Changelog and version bump for Gateway 2.8.4.4
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#6293 Set repository to ${{ github.event.pull_request.head.repo.full_name }}
  .github/workflows/ci-autofix.yml
Labels: review:tech

#6173 feat(labels): add on premise dp labels
  app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Labels: review:general, review:copyedit

#6318 Fix changelog-generator
  tools/changelog-generator/changelog.js
Labels: review:tech

#6281 update: Portal OIDC teams mapping post-GA improvements for IdP config instructions
  app/konnect/dev-portal/access-and-approval/add-teams.md
Labels: review:copyedit

#6254 kgo: update docs with 1.0.1
  app/_src/gateway-operator/get-started/kic/create-gateway.md
  app/gateway-operator/changelog.md
Labels: review:general

#6308 Fix full broken link checker.
  tools/broken-link-checker/full.js
Labels: review:tech

#6282 fix: Proxy TCP request
  app/_includes/md/kic/prerequisites.md
  app/_src/kubernetes-ingress-controller/guides/services/tcp.md
Labels: review:tech, ci:manual-approve:link-validation, skip-changelog

#6291 fix: Proxy UDP requests
  app/_src/kubernetes-ingress-controller/guides/services/udp.md
Labels: review:tech, ci:manual-approve:link-validation, skip-changelog

#6295 fix: External Service
  app/_includes/md/kic/http-test-routing-resource.md
  app/_src/kubernetes-ingress-controller/guides/services/external.md
Labels: review:tech, ci:manual-approve:link-validation, skip-changelog

#6324 fix: Prerequisites
  app/_includes/md/kic/prerequisites.md
Labels: review:tech, skip-changelog

#6264 update: Add Portal RBAC diagram to Managing Developer Team Access Page
  app/assets/images/diagrams/diagram-dev-portal-team-access.png
  app/konnect/dev-portal/access-and-approval/manage-teams.md
Labels: review:general

#6317 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6326 Fix: Kong Gateway support matrix
  app/_data/tables/support/gateway/packages.yml
  app/_data/tables/support/gateway/third-party.yml
  app/_data/tables/support/gateway/versions/28.yml
  app/_data/tables/support/gateway/versions/31.yml
  app/_data/tables/support/gateway/versions/33.yml
  app/_data/tables/support/gateway/versions/34.yml
  app/gateway/changelog.md
Labels: review:general, review:copyedit

#6325 DOCU-3435: Find in page counts hidden elements in the result
  app/_assets/stylesheets/accordion.less
Labels: review:tech

#6247 fix: Kong for Kubernetes Enterprise
  app/_includes/md/kic/kong-enterprise-license-secret.md
  app/_src/kic-v2/deployment/k4k8s-enterprise.md
Labels: review:tech, skip-changelog

#6310 fix: Access Control List plugin
  app/_includes/md/kic/http-test-routing-resource.md
  app/_includes/md/kic/http-test-routing.md
  app/_includes/md/kic/http-test-service.md
  app/_src/kubernetes-ingress-controller/plugins/acl.md
Labels: review:tech, ci:manual-approve:link-validation, skip-changelog

#6311 fix: Rate limiting plugin
  app/_includes/md/kic/class.md
  app/_includes/md/kic/prerequisites.md
  app/_src/kubernetes-ingress-controller/plugins/rate-limiting.md
Labels: review:tech, skip-changelog

#6271 Add Overlays for tag description [skip-ci]
  api-specs/overlays/docs/docs.md
  api-specs/overlays/ee/api-description.yaml
  api-specs/overlays/ee/tag-descriptions.yaml
  api-specs/overlays/oss/api-description.yaml
  api-specs/overlays/oss/tag-descriptions.yaml
Labels: review:general, skip-changelog

#6097 Feat: Noname plugins for Kong
  .github/styles/kong/dictionary.txt
  app/_hub/nonamesecurity/nonamesecurity-kongprevention/_metadata.yml
  app/_hub/nonamesecurity/nonamesecurity-kongprevention/examples/_index.yml
  app/_hub/nonamesecurity/nonamesecurity-kongprevention/overview/_index.md
  app/_hub/nonamesecurity/nonamesecurity-kongprevention/schemas/_index.json
  app/_hub/nonamesecurity/nonamesecurity-kongtrafficsource/_metadata.yml
  app/_hub/nonamesecurity/nonamesecurity-kongtrafficsource/examples/_index.yml
  app/_hub/nonamesecurity/nonamesecurity-kongtrafficsource/overview/_index.md
  app/_hub/nonamesecurity/nonamesecurity-kongtrafficsource/schemas/_index.json
  app/assets/images/icons/hub/nonamesecurity_nonamesecurity-kongprevention.png
  app/assets/images/icons/hub/nonamesecurity_nonamesecurity-kongtrafficsource.png
Labels: review:copyedit

#6334 kgo: update docs with 1.0.2
  app/gateway-operator/changelog.md
Labels: Kubernetes Team, review:general

#6330 add a note to FIPS index page
  app/_src/gateway/kong-enterprise/fips-support/index.md
Labels: review:copyedit

#6328 Chore: Add search aliases for plugins
  app/_hub/kong-inc/acme/_metadata.yml
  app/_hub/kong-inc/app-dynamics/_metadata.yml
  app/_hub/kong-inc/application-registration/_metadata.yml
  app/_hub/kong-inc/aws-lambda/_metadata.yml
  app/_hub/kong-inc/azure-functions/_metadata.yml
  app/_hub/kong-inc/basic-auth/_metadata.yml
  app/_hub/kong-inc/bot-detection/_metadata.yml
  app/_hub/kong-inc/correlation-id/_metadata.yml
  app/_hub/kong-inc/exit-transformer/_metadata.yml
  app/_hub/kong-inc/file-log/_metadata.yml
  app/_hub/kong-inc/forward-proxy/_metadata.yml
  app/_hub/kong-inc/graphql-proxy-cache-advanced/_metadata.yml
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_metadata.yml
  app/_hub/kong-inc/grpc-gateway/_metadata.yml
  app/_hub/kong-inc/grpc-web/_metadata.yml
  app/_hub/kong-inc/hmac-auth/_metadata.yml
  app/_hub/kong-inc/http-log/_metadata.yml
  app/_hub/kong-inc/ip-restriction/_metadata.yml
  app/_hub/kong-inc/jwe-decrypt/_metadata.yml
  app/_hub/kong-inc/jwt-signer/_metadata.yml
  app/_hub/kong-inc/jwt/_metadata.yml
  app/_hub/kong-inc/kafka-log/_metadata.yml
  app/_hub/kong-inc/kafka-upstream/_metadata.yml
  app/_hub/kong-inc/key-auth-enc/_metadata.yml
  app/_hub/kong-inc/key-auth/_metadata.yml
  app/_hub/kong-inc/ldap-auth-advanced/_metadata.yml
  app/_hub/kong-inc/ldap-auth/_metadata.yml
  app/_hub/kong-inc/mtls-auth/_metadata.yml
  app/_hub/kong-inc/oas-validation/_metadata.yml
  app/_hub/kong-inc/oauth2-introspection/_metadata.yml
  app/_hub/kong-inc/opa/_metadata.yml
  app/_hub/kong-inc/openid-connect/_metadata.yml
  app/_hub/kong-inc/opentelemetry/_metadata.yml
  app/_hub/kong-inc/proxy-cache-advanced/_metadata.yml
  app/_hub/kong-inc/proxy-cache/_metadata.yml
  app/_hub/kong-inc/rate-limiting-advanced/_metadata.yml
  app/_hub/kong-inc/rate-limiting/_metadata.yml
  app/_hub/kong-inc/request-size-limiting/_metadata.yml
  app/_hub/kong-inc/request-termination/_metadata.yml
  app/_hub/kong-inc/request-transformer-advanced/_metadata.yml
  app/_hub/kong-inc/request-transformer/_metadata.yml
  app/_hub/kong-inc/request-validator/_metadata.yml
  app/_hub/kong-inc/response-ratelimiting/_metadata.yml
  app/_hub/kong-inc/response-transformer-advanced/_metadata.yml
  app/_hub/kong-inc/response-transformer/_metadata.yml
  app/_hub/kong-inc/route-by-header/_metadata.yml
  app/_hub/kong-inc/route-transformer-advanced/_metadata.yml
  app/_hub/kong-inc/saml/_metadata.yml
  app/_hub/kong-inc/session/_metadata.yml
  app/_hub/kong-inc/statsd/_metadata.yml
  app/_hub/kong-inc/tcp-log/_metadata.yml
  app/_hub/kong-inc/tls-handshake-modifier/_metadata.yml
  app/_hub/kong-inc/tls-metadata-headers/_metadata.yml
  app/_hub/kong-inc/udp-log/_metadata.yml
  app/_hub/kong-inc/upstream-timeout/_metadata.yml
  app/_hub/kong-inc/vault-auth/_metadata.yml
  app/_hub/kong-inc/websocket-size-limit/_metadata.yml
  app/_hub/kong-inc/websocket-validator/_metadata.yml
  app/_hub/kong-inc/xml-threat-protection/_metadata.yml
Labels: review:general, review:copyedit, ci:check-skipped:generated-files

#6305 Update: SSH access note for instances deployed using Konnect Tech Preview install platforms
  app/konnect/gateway-manager/data-plane-nodes/index.md
Labels: review:general, review:copyedit

#6319 feat(multiple-metrics): updated latency section and images
  app/assets/images/products/konnect/analytics/custom-reports/api-usage-by-application.png
  app/assets/images/products/konnect/analytics/custom-reports/kong-latency.png
  app/assets/images/products/konnect/analytics/custom-reports/kong-vs-upstream-latency.png
  app/assets/images/products/konnect/analytics/custom-reports/latency-payments-api-30.png
  app/assets/images/products/konnect/analytics/custom-reports/total-api-requests.png
  app/assets/images/products/konnect/analytics/custom-reports/total-usage-accounts-api-30.png
  app/assets/images/products/konnect/analytics/custom-reports/upstream-latency.png
  app/konnect/analytics/reference.md
  app/konnect/analytics/use-cases/latency.md
  app/konnect/updates.md
  tools/screenshots/konnect/analytics/upstream-latency-report.yaml
Labels: review:copyedit, pending:release

#6339 noname security plugin metadata.yml fix
  app/_hub/nonamesecurity/nonamesecurity-kongprevention/_metadata.yml
  docs/templates/partner-plugin-template/_metadata.yml
Labels: review:general, skip-changelog

#6284 feat(oidc): certificate bound access tokens
  app/_hub/kong-inc/openid-connect/overview/_index.md
  app/assets/images/products/plugins/openid-connect/keycloak-client-cert-bound-settings.png
  app/assets/images/products/plugins/openid-connect/keycloak.json
Labels: review:general, review:copyedit

#6342 fix: Enable Admission webhook
  app/_src/kic-v2/deployment/admission-webhook.md
Labels: review:tech, skip-changelog

#6320 Guide to migrate Zone CP from On-Prem Global CP to Konnect
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/assets/images/diagrams/diagram-mesh-migration-after.png
  app/assets/images/diagrams/diagram-mesh-migration-before.png
  app/konnect/mesh-manager/migrate-zone.md
Labels: review:general

#6353 fix(jwt): state what happens when multiple JWTs are provided
  app/_hub/kong-inc/jwt/overview/_index.md
Labels: review:general, review:copyedit

#6351 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6286 Update: reflect latest FIPS support status
  app/_src/gateway/kong-enterprise/fips-support.md
  app/_src/gateway/kong-enterprise/fips-support/index.md
  app/_src/gateway/kong-enterprise/fips-support/plugins.md
Labels: review:general

#6357 Fix API URL in Konnect Custom Plugin docs
  .github/workflows/linting.yml
  app/konnect/gateway-manager/plugins/add-custom-plugin.md
Labels: review:general

#6354 Automated OAS Update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
  api-specs/Konnect/v0/yaml/mesh-control-planes.yaml
  api-specs/Konnect/v2/yaml/analytics-reports.yaml
  api-specs/Konnect/v2/yaml/analytics-requests.yaml
  api-specs/Konnect/v2/yaml/api-products.yaml
  api-specs/Konnect/v2/yaml/audit-logs.yaml
  api-specs/Konnect/v2/yaml/control-planes.yaml
  api-specs/Konnect/v3/yaml/identity.yaml
Labels: review:general

#6358 fix(portal) remove examples with path in portal gui host
  app/_src/gateway/reference/configuration-3.0-3.3.md
  app/_src/gateway/reference/configuration.md
Labels: review:general, ci:manual-approve:generated-files

#6355 fix: Using mtls-auth plugin
  app/_includes/md/kic/prerequisites.md
  app/_src/kic-v2/guides/using-mtls-auth-plugin.md
Labels: review:tech, skip-changelog

#6367 fix: Custom Resources
  app/_src/kubernetes-ingress-controller/concepts/custom-resources.md
Labels: review:tech, review:copyedit, ci:manual-approve:link-validation, skip-changelog

#6364 fix: Ingress
  app/_src/kubernetes-ingress-controller/concepts/ingress.md
Labels: review:tech, review:copyedit, ci:manual-approve:link-validation, skip-changelog

#6366 fix: Gateway API
  app/_src/kubernetes-ingress-controller/concepts/gateway-api.md
Labels: review:tech, review:copyedit, ci:manual-approve:link-validation, skip-changelog

#6363 Add HTTP routing guide
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/guides/services/http.md
Labels: review:general

#6346 fix: Azure guide
  app/_src/kubernetes-ingress-controller/install/cloud/aks.md
Labels: review:tech, ci:manual-approve:link-validation, skip-changelog

#6347 Feat: Add /schemas/vaults/:name endpoint [skip-ci]
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
  api-specs/Gateway-OSS/3.5/kong-oss-3.5.yaml
Labels: review:general, review:sme

#6215 docs(vaults): add docs for Azure Key Vault support in Kong Gateway
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_src/gateway/kong-enterprise/secrets-management/backends/azure-key-vaults.md
  app/_src/gateway/kong-enterprise/secrets-management/index.md
Labels: review:general, review:copyedit

#6356 KIC 3.0: Introduction
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/gateway-api.md
  app/_src/kubernetes-ingress-controller/index.md
  app/_src/kubernetes-ingress-controller/support-policy.md
  app/assets/images/products/kubernetes-ingress-controller/kic-gateway-arch.png
Labels: ci:manual-approve:link-validation, review:sme

#6362 fix: Architecture
  app/_src/kubernetes-ingress-controller/concepts/architecture.md
Labels: review:tech, review:copyedit, ci:manual-approve:link-validation, skip-changelog

#6181 feat: kong gateway's aws vault backend now supports automatic IAM credential fetch and role assuming
  app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
Labels: review:tech, review:general

#6371 Update cert-manager guide to use Kuma labels
  app/_src/kic-v2/guides/cert-manager.md
Labels: review:general

#6349 fix: cert bound access token conditional rendering
  app/_hub/kong-inc/openid-connect/overview/_index.md
Labels: review:general

#6365 Fix: Use placeholder token in TBAC examples instead of hashed value
  app/_src/gateway/production/access-control/enable-rbac.md
Labels: review:general

#6375 noname description update
  app/_hub/nonamesecurity/nonamesecurity-kongprevention/overview/_index.md
Labels: review:copyedit

#6329 Feat: Insomnia buttons for API catalog landing page
  api-specs/Gateway-EE/portal-api.yaml
  api-specs/Gateway-OSS/gateway-status.yaml
  api-specs/Konnect/v2/yaml/portal-api.yaml
  api-specs/Konnect/v2/yaml/portal-rbac.yaml
  app/_api/dev-portal/_index.md
  app/_api/gateway/admin-ee/_index.md
  app/_api/gateway/admin-oss/_index.md
  app/_api/gateway/status/_index.md
  app/_api/konnect/api-products/_index.md
  app/_api/konnect/api-requests/_index.md
  app/_api/konnect/audit-logs/_index.md
  app/_api/konnect/control-plane-configuration/_index.md
  app/_api/konnect/control-planes/_index.md
  app/_api/konnect/identity-management/_index.md
  app/_api/konnect/mesh-manager/_index.md
  app/_api/konnect/portal-rbac/_index.md
  app/_api/konnect/portal/_index.md
  app/_assets/stylesheets/pages/docs.less
  app/_assets/stylesheets/pages/landing-oas.less
  app/_layouts/oas/index.html
Labels: do not merge, review:tech

#6376 [Sitemap] Only include `latest` version for gateway-operator
  app/_plugins/generators/seo/index_entry_builder.rb
Labels: review:general, skip-changelog

#6373 fix: Preserving Client IP Address
  app/_src/kubernetes-ingress-controller/guides/security/client-ip.md
Labels: review:tech, skip-changelog

#6374 fix: KIC Annotations
  app/_src/kubernetes-ingress-controller/reference/annotations.md
Labels: review:tech, ci:manual-approve:link-validation, skip-changelog

#6327 feat: Kong Manager forced workspace deletion
  app/_src/gateway/kong-manager/workspaces.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#6331 update the admin_gui_auth_conf of the OIDC
  app/_src/gateway/kong-manager/auth/oidc/configure.md
Labels: review:copyedit

#6292 fix: Fallback Service for requests
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/guides/services/fallback.md
Labels: review:tech, skip-changelog

#6335 doc(kic) add GWAPI redirect instructions
  app/_includes/md/kic/add-tls-conf.md
  app/_src/kic-v2/guides/configuring-https-redirect.md
  app/_src/kic-v2/guides/getting-started.md
Labels: review:general, review:copyedit

#6381 fix: HTTPS redirects
  app/_includes/md/kic/add-tls-conf.md
  app/_src/kubernetes-ingress-controller/guides/services/https-redirect.md
Labels: review:tech, ci:manual-approve:link-validation, skip-changelog

#6370 KIC 3.0: Getting Started guides
  app/_assets/javascripts/copy-code-snippet-support.js
  app/_includes/md/kic/prerequisites.md
  app/_src/kubernetes-ingress-controller/get-started/index.md
  app/_src/kubernetes-ingress-controller/get-started/key-authentication.md
  app/_src/kubernetes-ingress-controller/get-started/proxy-caching.md
  app/_src/kubernetes-ingress-controller/get-started/rate-limiting.md
  app/_src/kubernetes-ingress-controller/get-started/services-and-routes.md
Labels: review:copyedit

#6383 fix: CLI Arguments
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/reference/cli-arguments.md
Labels: review:tech, skip-changelog

#6309 fix: Health checks
  app/_includes/md/kic/http-service-httpbin.md
  app/_includes/md/kic/prerequisites.md
  app/_src/kubernetes-ingress-controller/guides/high-availability/health-checks.md
  app/assets/kubernetes-ingress-controller/examples/httpbin-service.yaml
  app/assets/kubernetes-ingress-controller/examples/tcp-echo-service.yaml
Labels: review:tech, ci:manual-approve:link-validation, skip-changelog

#6399 Fix KIC prerequisites
  app/_includes/md/kic/prerequisites.md
Labels: review:general

#6384 KIC 3.0: Annotations + Admission Webhook
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kic-v2/deployment/admission-webhook.md
  app/_src/kubernetes-ingress-controller/concepts/admission-controller.md
  app/_src/kubernetes-ingress-controller/concepts/admission-webhook.md
  app/_src/kubernetes-ingress-controller/concepts/annotations.md
Labels: review:copyedit

#6401 Document in FAQ running KIC as DaemonSet
  app/_src/kic-v2/faq.md
Labels: review:tech

#6404 fix: fix changelog entry for openssl version bump
  app/gateway/changelog.md
Labels: review:general

#6380 Fix: Add missing docker image options to Gateway install overview
  app/_data/tables/install_options.yml
  app/_data/tables/install_options_34x.yml
Labels: review:general

#6406 fix(opentelemetry): address invalid request to set up plugin
  app/_hub/kong-inc/opentelemetry/overview/_index.md
Labels: review:general

#6405 fix: Rewriting hosts and paths
  app/_src/kic-v2/guides/using-rewrites.md
  app/_src/kic-v2/references/annotations.md
  app/_src/kic-v2/references/feature-gates.md
Labels: review:tech, skip-changelog

#6408 fix: Rewrite hosts and Paths
  app/_src/kubernetes-ingress-controller/guides/requests/rewrite-host.md
Labels: review:tech, ci:manual-approve:link-validation, skip-changelog

#6409 fix: Integrate the Kong Ingress Controller with Prometheus/Grafana
  app/_assets/javascripts/copy-code-snippet-support.js
  app/_src/kic-v2/guides/prometheus-grafana.md
  app/assets/kubernetes-ingress-controller/examples/multiple-services.yaml
Labels: review:tech, skip-changelog

#6411 fix: Prometheus Grafana Integration
  app/_src/kic-v2/guides/prometheus-grafana.md
  app/_src/kubernetes-ingress-controller/production/observability/prometheus.md
Labels: review:tech, ci:manual-approve:link-validation, skip-changelog

#6412 Fix install link
  app/_includes/md/mesh/install-universal-run.md
Labels: review:general

#6396 fix: Prometheus
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/production/observability/prometheus-grafana.md
  app/_src/kubernetes-ingress-controller/production/observability/prometheus.md
Labels: review:tech, ci:manual-approve:link-validation, skip-changelog

#6359 Automated OAS Update
  api-specs/Konnect/v2/yaml/api-products.yaml
  api-specs/Konnect/v2/yaml/portal-management.yaml
Labels: do not merge, review:general
