Repository Kong/docs.konghq.com, pull requests merged in 2023-05, with the labels that each got.

#5514 Fixed reference to hybrid mode in docs
  app/_src/gateway/production/deployment-topologies/index.md
Labels: review:general

#5517 docs(3.3) remove references to 'default tracing_sampling_rate'
  app/_src/gateway/production/tracing/api.md
Labels: review:copyedit

#5366 docs(acme): support redis namespace
  .github/styles/kongplugins/auto-ignore.txt
  app/_hub/kong-inc/acme/_index.md
Labels: review:general

#5520 [fix] Broken link in Linux installation docs
  app/_redirects
  app/_src/gateway/install/linux/amazon-linux.md
  app/_src/gateway/install/linux/centos.md
  app/_src/gateway/install/linux/debian.md
  app/_src/gateway/install/linux/rhel.md
  app/_src/gateway/install/linux/ubuntu.md
  app/moved_urls.yml
Labels: review:general

#5527 fix(graphql) Removes reference to an unsupported GraphQL Example
  app/_src/gateway/kong-plugins/graphql.md
Labels: review:general

#5518 Add Konnect DP Certificate renewal with OpenSSL instructions
  app/konnect/runtime-manager/runtime-instances/renew-certificates.md
Labels: review:general

#5529 Adding additional info for Portal Admin
  app/konnect/org-management/teams-and-roles/teams-reference.md
Labels: review:general

#5509 Update konnect_errors.yml to include 429 - Too Many Requests
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_errors.yml
  app/konnect/api/errors.md
Labels: review:copyedit, area/docs

#5528 Update prometheus-grafana.md
  app/_src/kubernetes-ingress-controller/guides/prometheus-grafana.md
Labels: review:general

#5530 Update Password Criteria
  app/konnect/getting-started/access-account.md
Labels: review:general

#5421 fix(request-validator): fix content-type breaking change
  app/_hub/kong-inc/request-validator/_index.md
Labels: review:general

#5420 feat(proxy-cache): add wildcard and parameter match support for content_type
  app/_hub/kong-inc/proxy-cache-advanced/_index.md
  app/_hub/kong-inc/proxy-cache/_index.md
Labels: review:general

#5524 Bump ruby version
  .ruby-version
Labels: review:tech

#5526 Add shared rate limit example to Rate Limiting Advanced docs
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
Labels: review:general

#5522 StatsD plugin: Clarify shdict_name variable
  app/_hub/kong-inc/statsd/_index.md
Labels: review:copyedit

#5525 fix(kic/faq): replace broken links for K8s docs
  app/_src/kubernetes-ingress-controller/faq.md
  app/kubernetes-ingress-controller/1.0.x/faq.md
  app/kubernetes-ingress-controller/1.1.x/faq.md
  app/kubernetes-ingress-controller/1.2.x/faq.md
  app/kubernetes-ingress-controller/1.3.x/faq.md
  app/kubernetes-ingress-controller/2.0.x/faq.md
  app/kubernetes-ingress-controller/2.1.x/faq.md
  app/kubernetes-ingress-controller/2.2.x/faq.md
Labels: review:general

#5532 Make Org Management a Konnect nav item
  app/_data/docs_nav_konnect.yml
Labels: review:general

#5541 [DOCU-3216] Status Endpoint link
  app/_data/docs_nav_gateway_3.3.x.yml
Labels: review:general

#5533 Fix description of routing priorities with multiple paths
  app/_src/gateway/key-concepts/routes/index.md
Labels: review:general, review:copyedit

#5540 Fix indentation filter
  app/_plugins/filters/indent_filter.rb
Labels: review:tech

#5548 fix(oauth2): add a changelog entry
  app/_hub/kong-inc/oauth2/_index.md
Labels: review:general

#5545 Typo in Keys reference doc
  app/_src/gateway/reference/key-management.md
Labels: review:general, ci:manual-approve:link-validation

#5419 [DOCU-2921] Status endpoint + Kong health check
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_src/gateway/production/monitoring/index.md
  app/_src/gateway/production/monitoring/readiness-check.md
Labels: review:general

#5088 Reworked plugin queues
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_hub/kong-inc/datadog/_index.md
  app/_hub/kong-inc/http-log/_index.md
  app/_hub/kong-inc/opentelemetry/_index.md
  app/_hub/kong-inc/statsd/_index.md
  app/_hub/kong-inc/zipkin/_index.md
  app/_includes/md/plugins-hub/queue-parameters.md
  app/_src/gateway/kong-plugins/queue/index.md
  app/_src/gateway/kong-plugins/queue/reference.md
  app/_src/gateway/production/sizing-guidelines.md
Labels: review:general, review:copyedit, ci:check-skipped:generated-files

#5549 [DOCU-3051] Auto docs 3.3
  app/_src/gateway/admin-api/index.md
  app/_src/gateway/plugin-development/pdk/kong.request.md
  app/_src/gateway/plugin-development/pdk/kong.response.md
  app/_src/gateway/plugin-development/pdk/kong.service.md
  app/_src/gateway/plugin-development/pdk/kong.tracing.md
  app/_src/gateway/plugin-development/pdk/kong.vault.md
  app/_src/gateway/reference/configuration.md
  app/konnect/api/runtime-groups-config/index.md
Labels: review:general, ci:prevent-merge:generated-files, ci:check-skipped:generated-files, ci:manual-approve:generated-files

#5550 Timeout support for dynamic log levels
  app/_src/gateway/production/logging/update-log-level-dynamically.md
Labels: review:copyedit, ci:check-skipped:generated-files

#5553 Spec links
  app/_src/gateway/admin-api/index.md
Labels: review:general, ci:prevent-merge:generated-files, ci:check-skipped:generated-files

#5554 [DOCU-3065] Data plane labels in konnect
  app/_data/docs_nav_konnect.yml
  app/konnect/reference/labels.md
  app/konnect/runtime-manager/runtime-instances/custom-dp-labels.md
Labels: review:copyedit, ci:manual-approve:link-validation

#5536 [DOCU-3167] Add Amazon Linux 2023 to support page
  app/_data/tables/support/gateway/packages.yml
  app/_data/tables/support/gateway/versions/33.yml
  app/_src/gateway/install/linux/amazon-linux.md
  app/_src/gateway/install/linux/ubuntu.md
  app/_src/gateway/support/browser.md
  app/_src/gateway/support/index.md
  app/_src/gateway/support/third-party.md
Labels: review:general, ci:manual-approve:link-validation

#5572 [plugin hub] fix rebase error in request termination
  app/_hub/kong-inc/request-termination/_index.md
Labels: review:general

#5568 Fix bug for ACME plugin in Configure plugin section
  app/_hub/kong-inc/acme/_index.md
Labels: review:general

#5535 [Update] WebSocket Validator
  app/_hub/kong-inc/websocket-validator/_index.md
Labels: review:general

#5534 [Update] MeshGlobalRateLimit Policy
  app/_src/mesh/features/meshglobalratelimit.md
Labels: review:general

#5551 Release: Gateway 3.1.1.4
  app/_data/kong_versions.yml
  app/_src/gateway/kong-manager/auth/oidc/mapping.md
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#5579 Hub breadcrumbs
  app/_hub/kong-inc/oas-validation/_metadata.yml
  app/_plugins/generators/plugin_single_source/pages/base.rb
  app/_plugins/generators/plugin_single_source/pages/overview.rb
Labels: review:tech

#5577 Plugin k8s examples
  app/_includes/plugins/hub-examples/consumer.html
  app/_includes/plugins/hub-examples/kubernetes.html
  app/_includes/plugins/hub-examples/route.html
  app/_includes/plugins/hub-examples/service.html
Labels: review:general

#5556 Add instructions to import additional GPG key for RPMs
  app/_assets/keys/2023-rpm.asc
  app/_includes/md/gateway/rpm-gpg-key-2023.md
  app/_src/gateway/install/linux/amazon-linux.md
  app/_src/gateway/install/linux/centos.md
  app/_src/gateway/install/linux/rhel.md
  gulpfile.js
Labels: review:general, ci:manual-approve:link-validation, review:sme

#5581 Remove centos from 3.x
  app/_data/tables/support/gateway/versions/32.yml
  app/_src/gateway/install/linux/centos.md
Labels: review:general

#5582 Fix kong mesh images
  app/_plugins/generators/kuma_to_kong_mesh.rb
  spec/app/_plugins/generators/kuma_to_kong_mesh_spec.rb
  spec/fixtures/app/kuma-to-kong-mesh.md
Labels: review:tech

#5583 Plugin queuing diagrams
  app/_assets/images/docs/konnect/konnect-plugin-queuing-1.png
  app/_assets/images/docs/konnect/konnect-plugin-queuing-2.png
  app/_src/gateway/kong-plugins/queue/index.md
Labels: review:general

#5587 Rename kong-mesh images to kuma
  app/_assets/images/diagrams/gslides/kuma_cross_zone_gateway.svg
  app/_assets/images/diagrams/gslides/kuma_multizone.svg
  app/_assets/images/diagrams/gslides/kuma_multizone_without_egress.svg
Labels: review:tech

#5591 Add KIC FeatureGate with Helm instructions
  app/_src/kubernetes-ingress-controller/references/feature-gates.md
Labels: review:general

#5580 Fix badges styles
  app/_assets/stylesheets/badges.less
Labels: review:tech

#5542 kic: update feature gates table
  app/_src/kubernetes-ingress-controller/references/feature-gates.md
Labels: Kubernetes Team, review:general

#5594 Clarify Third Party support text
  app/_src/gateway/support/third-party.md
Labels: review:general

#5588 Add Helm instructions when enabling KIC debug endpoint
  app/_src/kubernetes-ingress-controller/troubleshooting.md
Labels: review:general

#5562 [DOCU-3169] Changelog for gateway 3.3.0.0
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#5590 [DOCU-3215] 3.3 upgrade guide
  app/_src/gateway/upgrade-v2.md
Labels: review:copyedit

#5595 adjusted defaults based on latest values for plugin
  app/_hub/moesif/kong-plugin-moesif/schemas/_index.json
Labels: review:general

#5597 Removing remnants of non-existent third-party plugins
  app/_assets/images/icons/hub/justeat_kongverge.png
  app/_assets/images/icons/hub/zillowgroup_kong-terraform.png
  app/_hub/zillowgroup/kong-terraform/_index.md
  app/_hub/zillowgroup/kong-terraform/_metadata.yml
  app/_hub/zillowgroup/kong-terraform/schemas/_index.json
Labels: review:general

#5558 [docu-3186] SOBM page
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_src/gateway/support/sbom.md
Labels: do not merge, review:general, ci:manual-approve:link-validation

#5598 Update access-account.md
  app/konnect/getting-started/access-account.md
Labels: review:general

#5463 [DOCU-3162] changelog for runtime instance filtering
  app/konnect/updates.md
Labels: do not merge, review:general

#5600 Typo. Fix for #5145.
  app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md
Labels: review:general, ci:manual-approve:linting

#5592 Release: Gateway 3.2.2.2
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#5604 Increase timeout for flaky test
  tests/seo.test.js
Labels: review:general

#5603 Fix trailing / on URLs with fragments
  app/_plugins/drops/sidenav.rb
  spec/app/_plugins/drops/plugins/sidenav_menu_item_spec.rb
Labels: review:general

#5601 docs(expressions): fix typo
  app/_src/gateway/key-concepts/routes/expressions.md
Labels: review:general

#5596 [DOCU-3229] Tech partner badges for third-party plugins
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/badges.less
  app/_hub/imperva/imp-appsec-connector/_metadata.yml
  app/_hub/moesif/kong-plugin-moesif/_metadata.yml
  app/_hub/okta/okta/_metadata.yml
  app/_hub/salt/salt/_metadata.yml
  app/_hub/wallarm/wallarm/_metadata.yml
  app/_includes/header.html
  app/_includes/hub_cards.html
  app/_includes/plugins/badges.html
  app/_layouts/plugins/show.html
  app/_plugins/drops/plugins/badges.rb
Labels: review:tech, review:general

#5602 kic: Gateway Discovery only works with DB-less deployments of Kong
  app/_src/kubernetes-ingress-controller/concepts/deployment.md
Labels: review:general

#5605 [fix] 3.2.2 changelog
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#5599 Add known issues to 3.3 changelog
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#5607 Fix konnect compatibility table
  app/hub/plugins/compatibility/index.md
  app/konnect/compatibility.md
Labels: review:general

#5543 Align all samples
  app/_hub/kong-inc/jwt/_index.md
Labels: review:general

#5613 Add directory for Insomnia button generation
  api-specs/Gateway-EE/json/kong-ee-33.json
  api-specs/Gateway-EE/yaml/kong-ee-33.yaml
  api-specs/Gateway-OSS/json/kong-oss-33.json
  api-specs/Gateway-OSS/yaml/kong-oss-33.yaml
  api-specs/readme.md
Labels: review:general

#5614 [DOCU-3225] Add AWS Graviton support to OS support table
  app/_data/tables/support/gateway/packages.yml
  app/_data/tables/support/gateway/versions/32.yml
  app/_data/tables/support/gateway/versions/33.yml
  app/_includes/gateway-support.html
  app/_src/gateway/install/linux/amazon-linux.md
  app/_src/gateway/install/linux/ubuntu.md
Labels: review:general, review:sme

#5615 Add insomnia button for specs
  app/_src/gateway/admin-api/index.md
Labels: review:general

#5622 Fix PDF generation with submodules
  .github/workflows/build-docs-pdf.yml
Labels: review:tech

#5552 Release: Gateway 2.8.4.1
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#5617 fix(mesh-policy): fixed paths to kong mesh specific policies
  app/_data/docs_nav_mesh_2.1.x.yml
  app/_data/docs_nav_mesh_2.2.x.yml
  app/_redirects
  app/_src/mesh/index.md
  app/_src/mesh/policies/meshglobalratelimit.md
  app/_src/mesh/policies/meshopa.md
Labels: review:general

#5620 Update sessions.md
  app/_src/gateway/kong-manager/auth/sessions.md
Labels: review:general

#5630 Update deprecation notice for Cassandra
  app/_includes/md/enterprise/cassandra-deprecation.md
  app/_src/deck/faqs.md
  app/gateway/2.7.x/install-and-run/upgrade-oss.md
  app/gateway/2.8.x/install-and-run/upgrade-oss.md
  app/gateway/changelog.md
Labels: ci:manual-approve:link-validation, review:sme

#5636 kic: add konnect integration to deployment article
  app/_assets/images/docs/kubernetes-ingress-controller/kic-konnect-diagram.png
  app/_src/kubernetes-ingress-controller/concepts/deployment.md
Labels: Kubernetes Team, review:general

#5639 Update build-custom-images.md
  app/_src/gateway/install/docker/build-custom-images.md
Labels: review:general, ci:manual-approve:link-validation

#5624 Bring removal & deprecation reminders to top of changelog
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#5638 Fix referenceable fields.
  app/_plugins/drops/plugins/schema.rb
  spec/app/_plugins/drops/plugins/schema_field_spec.rb
Labels: review:tech

#5644 kic: add k8s events reference
  app/_data/docs_nav_kic_2.10.x.yml
  app/_data/kong_versions.yml
  app/_src/kubernetes-ingress-controller/references/kubernetes-events.md
  app/_src/kubernetes-ingress-controller/troubleshooting.md
Labels: Kubernetes Team, review:general

#5651 Update support-policy.md
  app/_src/kubernetes-ingress-controller/support-policy.md
Labels: review:general

#5648 Remove newrelic
  app/_includes/head.html
  app/_includes/newrelic.html
Labels: review:tech

#5365 adding kind install instructions for KIC
  app/_data/docs_nav_kic_2.9.x.yml
  app/_src/kubernetes-ingress-controller/deployment/kind.md
Labels: review:tech, review:general, review:copyedit, ci:manual-approve:link-validation, review:sme

#5647 docs: remove the excess "#"
  app/_src/gateway/admin-api/index.md
Labels: review:general

#5642 Update Organization Path
  app/konnect/org-management/oidc-idp.md
  app/konnect/org-management/okta-idp.md
Labels: do not merge, review:general
