Repository Kong/docs.konghq.com, pull requests merged in 2023-12, with the labels that each got.

#6585 kgo: enhance installation page
  app/_src/gateway-operator/get-started/kic/install.md
Labels: Kubernetes Team, review:tech, review:general

#6601 Fix: Remove mention of vitals and dev portal from 3.5 intro paragraph
  app/_src/gateway/kong-enterprise/index.md
Labels: review:general

#6597 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6567 kic: update and extend gRPC how-to
  app/_src/kubernetes-ingress-controller/guides/services/grpc.md
Labels: Kubernetes Team, review:tech, review:general

#6438 POC:Feat: Mermaid.js
  Gemfile
  app/_assets/entrypoints/application.js
  app/_assets/stylesheets/page.less
  app/_plugins/blocks/mermaid.rb
Labels: review:general, ci:manual-approve:linting

#6594 chore: Update readme to include make install-prerequisites
  README.md
Labels: review:tech

#6600 update: OAuth 2.0 Authentication
  app/_hub/kong-inc/oauth2/overview/_index.md
Labels: review:copyedit

#6591 Chore: Assign metadescriptions to pages by `description`
  app/_includes/head.html
Labels: review:general

#6602 fix: Mermaid rubocop fail
  app/_plugins/blocks/mermaid.rb
  app/_src/gateway/index.md
Labels: review:general

#6603 Remove stray diagram
  app/_src/gateway/index.md
Labels: review:general, skip-changelog

#6607 tls-metadata-headers is compatible with Konnect
  app/_hub/kong-inc/tls-metadata-headers/_metadata.yml
Labels: review:general

#6618 tls-handshake-modifier is compatible with Konnect
  app/_hub/kong-inc/tls-handshake-modifier/_metadata.yml
Labels: review:general

#6614 fix: add missing references to Azure Key Vault
  app/_data/tables/support/gateway/third-party.yml
  app/_data/tables/support/gateway/versions/35.yml
  app/_src/gateway/kong-enterprise/index.md
Labels: review:general

#6631 Fix: Add cross-links between kong.conf guides and reference
  app/_src/gateway/production/environment-variables.md
  app/_src/gateway/production/kong-conf.md
  app/_src/gateway/reference/configuration.md
Labels: review:copyedit

#6621 fix: fix URL of services page
  app/_src/gateway/get-started/services-and-routes.md
Labels: review:general

#6620 Add a step to publish API Product and version docs
  app/konnect/getting-started/publish-service.md
Labels: review:copyedit

#6616 fix: Update title of add service documentation doc.
  app/konnect/api-products/service-documentation.md
Labels: review:general, skip-changelog

#6550 Update auth0.md to include developer managed scopes UI steps
  app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
  app/konnect/updates.md
Labels: review:copyedit, pending:release

#6612 Update:JWT plugin overview section
  app/_hub/kong-inc/jwt/overview/_index.md
Labels: review:copyedit

#6608 fix: Clear up confusion with plugin tiering
  app/konnect/compatibility.md
Labels: review:general, skip-changelog

#6496 feat(plugin): How to rate limit Oauth2 token endpoint
  app/_hub/kong-inc/oauth2/how-to/_oauth2rla.md
Labels: review:tech, review:copyedit

#6586 feat(plugin): Rate Limiting Advanced window types explanation
  app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
Labels: review:copyedit

#6629 doc(decK): Update authentication instructions
  app/_includes/md/deck-global-flags.md
  app/_src/deck/guides/konnect.md
Labels: review:general, review:sme

#6534 Feat: Gateway Upgrade Refactoring + LTS upgrade guide
  app/_assets/stylesheets/page.less
  app/_data/docs_nav_gateway_2.8.x.yml
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_data/tables/breaking_changes_lts.yml
  app/_includes/lts-changes.html
  app/_includes/md/gateway/db-less-upgrade.md
  app/_includes/md/gateway/hybrid-upgrade.md
  app/_includes/md/gateway/traditional-upgrade.md
  app/_includes/md/gateway/upgrade-backup.md
  app/_includes/md/gateway/upgrade-flow.md
  app/_src/deck/installation.md
  app/_src/gateway/breaking-changes/28x.md
  app/_src/gateway/breaking-changes/30x.md
  app/_src/gateway/breaking-changes/31x.md
  app/_src/gateway/breaking-changes/32x.md
  app/_src/gateway/breaking-changes/33x.md
  app/_src/gateway/breaking-changes/34x.md
  app/_src/gateway/breaking-changes/35x.md
  app/_src/gateway/upgrade-v3.md
  app/_src/gateway/upgrade/backup-and-restore.md
  app/_src/gateway/upgrade/blue-green.md
  app/_src/gateway/upgrade/dual-cluster.md
  app/_src/gateway/upgrade/in-place.md
  app/_src/gateway/upgrade/index.md
  app/_src/gateway/upgrade/lts-upgrade.md
  app/_src/gateway/upgrade/rolling-upgrade.md
Labels: do not merge, review:sme

#6633 Fix: Remove inaccurate note and links about decK in db-less mode doc
  app/_src/deck/faqs.md
  app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
Labels: review:copyedit

#6498 Add permissions and token to sync-konnect-oas-data
  .github/workflows/sync-konnect-oas-data.yml
Labels: review:tech, skip-changelog

#6641 Fix: Upgrade guide include links
  app/_includes/md/gateway/db-less-upgrade.md
  app/_includes/md/gateway/hybrid-upgrade.md
  app/_includes/md/gateway/upgrade-backup.md
  app/_src/gateway/upgrade/index.md
  app/_src/gateway/upgrade/lts-upgrade.md
Labels: review:general, skip-changelog

#6639 docs(gateway-upgrade): fix an argument error
  app/_src/gateway/upgrade/backup-and-restore.md
Labels: review:general, review:copyedit

#6617 Add x-errors support to OAS docs
  app/_plugins/generators/oas_definition/error_page.rb
  app/_plugins/generators/oas_definition/product.rb
  app/_plugins/generators/seo/index_entry/oas_page.rb
Labels: review:tech

#6530 Add missing KIC 3.0 docs
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/concepts/gateway-api.md
  app/_src/kubernetes-ingress-controller/guides/customize/image.md
  app/_src/kubernetes-ingress-controller/guides/high-availability/last-known-good-config.md
Labels: review:general

#6590 Update: Meta description for community-expectations.md
  app/contributing/community-expectations.md
Labels: review:copyedit, skip-changelog

#6643 Add link to `Catalog` to OAS pages
  app/_assets/javascripts/views/SpecView.vue
Labels: review:general

#6403 Document in FAQ running KIC as DaemonSet
  app/_src/kic-v2/faq.md
Labels: Kubernetes Team, review:tech, review:general

#6645 Update debug-request.md
  app/_src/gateway/production/debug-request.md
Labels: review:general

#6649 (fix) correct spacing on developer managed scopes changelog
  app/konnect/updates.md
Labels: review:general, skip-changelog

#6637 Feat: Add some basic docs for making diagrams with mermaid
  app/_data/docs_nav_contributing.yml
  app/contributing/diagrams.md
Labels: review:copyedit

#6654 Update debug-request.md
  app/_src/gateway/production/debug-request.md
Labels: review:general, review:sme

#6624 Update reviewdog reporter
  .github/workflows/linting.yml
Labels: do not merge, review:tech

#6377 DocSearch v3 migration
  .github/workflows/algolia.yml
  algolia/config-full-docs.json
  app/_assets/entrypoints/search.js
  app/_assets/javascripts/navbar.js
  app/_assets/javascripts/views/SearchApp/App.css
  app/_assets/javascripts/views/SearchApp/App.mobile.css
  app/_assets/javascripts/views/SearchApp/Index.vue
  app/_assets/javascripts/views/SearchApp/NoResults.vue
  app/_assets/javascripts/views/SearchApp/Theme.css
  app/_assets/javascripts/views/SearchApp/routing.js
  app/_assets/stylesheets/docsearch.less
  app/_assets/stylesheets/header-v2.less
  app/_assets/stylesheets/index.less
  app/_assets/stylesheets/pages/docs.less
  app/_assets/stylesheets/pages/landing-page.less
  app/_includes/head.html
  app/_includes/nav-v2.html
  app/_layouts/default.html
  app/_layouts/landing-page.html
  app/_plugins/generators/algolia/base.rb
  app/_plugins/generators/algolia/doc.rb
  app/_plugins/generators/algolia/home.rb
  app/_plugins/generators/algolia/hub.rb
  app/_plugins/generators/algolia/oas_page.rb
  app/_plugins/generators/algolia/versions/mesh.rb
  app/_plugins/generators/algolia_filters.rb
  app/search.html
  docs/search.md
  package-lock.json
  package.json
  spec/app/_plugins/generators/seo/index_spec.rb
  spec/app/_plugins/generators/seo/sitemap_spec.rb
  spec/fixtures/app/search.html
Labels: review:general

#6661 Update Insomnia buttons to point to v3.5.x
  app/_api/gateway/admin-ee/_index.md
  app/_api/gateway/admin-oss/_index.md
Labels: review:general

#6640 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6664 Automated OAS Update
  api-specs/Konnect/v0/yaml/ksearch.yaml
Labels: review:general

#6666 Make port 8100 consistent in all examples
  app/_src/gateway/production/monitoring/readiness-check.md
Labels: review:general

#6651 (feat) 3.4.3.1 changelog
  app/gateway/changelog.md
Labels: review:general, pending:release

#6667 Use extn_slug when setting name for non-bundled plugins
  app/_layouts/extension.html
Labels: review:general

#6672 fix(kgo): proper rbac for 1.1.X in KIC Get Started
  app/assets/gateway-operator/v1.1.0/all_controllers.yaml
Labels: Kubernetes Team, review:tech, review:general

#6674 Add a `Deprecated` section to the OAS Catalog page
  app/_assets/stylesheets/pages/landing-oas.less
  app/_includes/oas/card.html
  app/_layouts/oas/index.html
  app/_plugins/drops/oas/product.rb
Labels: review:general

#6675 Add aria-labels to buttons
  app/_includes/sidebar/item.html
Labels: review:general

#6670 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6676 (chore) Add Mesh and KIC variables
  app/contributing/variables.md
Labels: review:general

#6572 feat: OpenShift Quickstart guide with Kong Mesh
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_mesh_2.5.x.yml
  app/_data/docs_nav_mesh_dev.yml
  app/_src/mesh/features/openshift-quickstart.md
Labels: review:copyedit

#6224 fix: MinK Post-summit docs cleanup
  app/konnect/architecture.md
  app/konnect/mesh-manager/index.md
  app/konnect/mesh-manager/service-mesh.md
Labels: review:copyedit

#6682 (chore) Update kong_versions.yml
  app/_data/kong_versions.yml
Labels: review:general, skip-changelog

#6665 fix: add missing `X-Kong-Request-Debug-Token` header of request-debug docs
  app/_src/gateway/production/debug-request.md
Labels: review:general

#6662 feat: Konnect custom DCR docs
  .github/styles/kong/auto-ignore.txt
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/applications/dynamic-client-registration/custom.md
Labels: review:copyedit, pending:release

#6685 chore(KIC): update references for v2.12.x
  app/_src/kic-v2/references/cli-arguments-2.12.x.md
  app/_src/kic-v2/references/custom-resources-2.12.x.md
Labels: review:general

#6687 chore: update AppDynamics installation guide
  app/_hub/kong-inc/app-dynamics/overview/_index.md
Labels: review:general

#6690 (chore) correct port number in readiness check
  app/_src/gateway/production/monitoring/readiness-check.md
Labels: review:general

#6693 kic: gateway API concepts update
  app/_src/kubernetes-ingress-controller/concepts/gateway-api.md
Labels: review:copyedit

#6696 Remove assets from sitemap
  app/_plugins/generators/seo/index_entry_builder.rb
  spec/app/_plugins/generators/seo/index_entry_builder_spec.rb
Labels: review:general

#6697 Fix: Add missing changelog entries for 3.4.3.1 and more
  app/gateway/changelog.md
Labels: review:general
