Repository Kong/docs.konghq.com, pull requests merged in 2023-06, with the labels that each got.

#5649 Legacy Site: Remove search
  app/_assets/javascripts/navbar.js
  app/_includes/nav-v2.html
  app/_layouts/landing-page.html
Labels: review:tech

#5646 Fix external links hook.
  app/_plugins/hooks/external_links.rb
Labels: review:tech

#5641 Run a full broken links scan every sunday
  .github/workflows/scheduled-broken-link-checker.yml
  tools/broken-link-checker/excluded.json
Labels: review:tech

#5654 [DOCU-3232] Plugin hub home icon
  app/_assets/images/icons/documentation/hub/icn-breadcrumbs.svg
Labels: review:general

#5655 Remove merge conflict from datadog plugin
  app/_hub/kong-inc/datadog/_index.md
Labels: review:tech

#5658 doc: add documentation for limits on configuration resources
  app/konnect/runtime-manager/configuration/index.md
Labels: review:copyedit

#5652 [DOCU-2925] HTTPie cleanout
  app/_hub/kong-inc/exit-transformer/_index.md
  app/_hub/kong-inc/mocking/_index.md
  app/_src/deck/guides/defaults-v2.md
  app/_src/gateway/admin-api/developers/reference.md
  app/_src/gateway/install/helm-quickstart.md
  app/_src/gateway/install/kubernetes/helm-quickstart.md
  app/_src/gateway/kong-enterprise/audit-log.md
  app/_src/gateway/kong-enterprise/consumer-groups/index.md
  app/_src/gateway/kong-enterprise/dev-portal/applications/enable-key-auth-plugin.md
  app/_src/gateway/kong-enterprise/dev-portal/authentication/azure-oidc-config.md
  app/_src/gateway/kong-enterprise/event-hooks/index.md
  app/_src/gateway/kong-enterprise/plugin-ordering/get-started.md
  app/_src/gateway/kong-enterprise/secrets-management/advanced-usage.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/env.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/gcp-sm.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
  app/_src/gateway/kong-enterprise/workspaces/index.md
  app/_src/gateway/licenses/examples.md
  app/_src/gateway/production/access-control/enable-rbac.md
  app/_src/gateway/production/access-control/register-admin-api.md
  app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
  app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
  app/_src/gateway/reference/key-management.md
Labels: review:general, review:copyedit

#5650 kic: add FAQ section for 2.10+ for EndpointSlices
  app/_src/kubernetes-ingress-controller/faq.md
Labels: Kubernetes Team, review:general, area/docs

#5662 (chore) Bump deck versions for 1.20 and 1.21
  app/_data/docs_nav_deck_1.20.x.yml
  app/_data/docs_nav_deck_1.21.x.yml
  app/_data/kong_versions.yml
Labels: review:general

#5668 Fixing the spelling mistake "query string" parameter
  app/_hub/kong-inc/jwt/_index.md
Labels: review:general

#5671 Update ignored_targets.json and remove duplicated file
  tools/broken-link-checker/config/ignored_targets.json
  tools/broken-link-checker/excluded.json
  tools/broken-link-checker/full.js
Labels: review:tech

#5663 Reformat compatibility issues
  app/_data/tables/version_errors_konnect.yml
Labels: review:general

#5640 add concept page for kic using expression router
  app/_data/docs_nav_kic_2.10.x.yml
  app/_src/kubernetes-ingress-controller/concepts/expression-based-router.md
Labels: Kubernetes Team, review:general

#5645 release: KIC v2.10.0
  app/_assets/images/docs/kubernetes-ingress-controller/kic-konnect-diagram.png
  app/_data/docs_nav_kic_2.10.x.yml
  app/_data/kong_versions.yml
  app/_src/kubernetes-ingress-controller/concepts/deployment.md
  app/_src/kubernetes-ingress-controller/concepts/expression-based-router.md
  app/_src/kubernetes-ingress-controller/faq.md
  app/_src/kubernetes-ingress-controller/references/custom-resources-2.10.x.md
  app/_src/kubernetes-ingress-controller/references/kubernetes-events.md
  app/_src/kubernetes-ingress-controller/references/version-compatibility.md
  app/_src/kubernetes-ingress-controller/support-policy.md
  app/_src/kubernetes-ingress-controller/troubleshooting.md
Labels: review:general

#5674 Konnect May Changelog
  app/konnect/compatibility.md
  app/konnect/updates.md
Labels: review:general

#5673 [DOCU-3246] 3.2.2.3 changelog
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#5680 Fix release date for 3.2.2.3
  app/gateway/changelog.md
Labels: review:general

#5678 add support status of kong router flavors of kic 2.10
  app/_src/kubernetes-ingress-controller/references/supported-router-flavors.md
Labels: Kubernetes Team, review:general

#5681 Plugin Hub doc templates and instructions
  app/_data/docs_nav_contributing.yml
  app/_hub/_init/my-extension/_index.md
  app/_redirects
  app/contributing/contribution-templates.md
  app/contributing/kong-plugins.md
  app/contributing/partner-plugins.md
  app/contributing/plugin-docs.md
  docs/templates/kong-plugin-template/_changelog.md
  docs/templates/kong-plugin-template/_index.md
  docs/templates/kong-plugin-template/_metadata.yml
  docs/templates/kong-plugin-template/how-to/_index.md
  docs/templates/kong-plugin-template/versions.yml
  docs/templates/partner-plugin-template/_changelog.md
  docs/templates/partner-plugin-template/_index.md
  docs/templates/partner-plugin-template/_metadata.yml
  docs/templates/partner-plugin-template/examples/_index.yml
  docs/templates/partner-plugin-template/schemas/_index.json
Labels: review:copyedit, ci:manual-approve:link-validation

#5676 Chore: Add more style rules to Vale
  .github/styles/kong/First-person.yml
  .github/styles/kong/Relativeurls.yml
  .github/styles/kong/We.yml
Labels: review:general

#5679 Chore: Remove autogen text in API markdown doc
  app/_src/gateway/admin-api/index.md
  app/gateway/2.6.x/admin-api/index.md
  app/gateway/2.7.x/admin-api/index.md
  app/gateway/2.8.x/admin-api/index.md
  app/konnect/api/runtime-groups-config/index.md
Labels: review:general

#5446 [DOCU-3161] Certificate metadata in Konnect
  app/konnect/runtime-manager/runtime-instances/renew-certificates.md
  app/konnect/updates.md
Labels: review:general

#5696 chore: Insomnia button creation add specs
  api-specs/Konnect/json/konnect.json
  api-specs/Konnect/yaml/konnect.yaml
Labels: review:general

#5697 Chore: Konnect API add links + button
  app/konnect/api/index.md
  app/konnect/api/runtime-groups-config/index.md
Labels: review:general

#5698 fix default tracing_sampling_rate value
  app/_src/gateway/reference/configuration.md
Labels: review:general

#5693 Fix grammar error in key-authentication.md
  app/_src/gateway/get-started/key-authentication.md
Labels: review:copyedit

#5694 Update import.md
  app/konnect/getting-started/import.md
Labels: review:general

#5699 chore: Fix URL in plugin endpoint
  app/konnect/api/runtime-groups-config/index.md
Labels: review:general

#5585 feat(logging): add workspace name in the logging payload (#5251)
  app/_includes/md/plugins-hub/json-object-log.md
  app/_includes/md/plugins-hub/log-format.md
Labels: review:copyedit

#5703 chore: remove specs
  app/konnect/api/index.md
  app/konnect/api/runtime-groups-config/index.md
Labels: review:general

#5686 Plugin templates: adjustments for clarity
  docs/templates/kong-plugin-template/_metadata.yml
  docs/templates/partner-plugin-template/_metadata.yml
Labels: review:copyedit

#5687 Audit logs: verify signatures
  app/_data/docs_nav_konnect.yml
  app/konnect/org-management/audit-logging/index.md
  app/konnect/org-management/audit-logging/reference.md
  app/konnect/org-management/audit-logging/replay-job.md
  app/konnect/org-management/audit-logging/verify-signatures.md
  app/konnect/org-management/audit-logging/webhook.md
Labels: review:copyedit

#5669 Update systemd.md
  app/_src/gateway/production/running-kong/systemd.md
Labels: review:tech

#5700 Add docs on using Kong Enterprise with KIC
  app/_data/docs_nav_kic_2.10.x.yml
  app/_data/docs_nav_kic_2.6.x.yml
  app/_data/docs_nav_kic_2.7.x.yml
  app/_data/docs_nav_kic_2.8.x.yml
  app/_data/docs_nav_kic_2.9.x.yml
  app/_src/kubernetes-ingress-controller/guides/choose-gateway-image.md
Labels: review:general

#5710 new specs
  api-specs/Konnect/v1/json/konnect.json
  api-specs/Konnect/v1/yaml/konnect.yaml
  api-specs/Konnect/v2/json/konnect-2.json
  api-specs/Konnect/v2/yaml/konnect-2.yaml
Labels: review:general

#5708 fix(kic): rbac permission for Endpoints is redundant for KIC >=2.10
  app/_src/kubernetes-ingress-controller/concepts/deployment.md
Labels: review:general

#5709 Updating the description for RLA
  app/_hub/kong-inc/rate-limiting-advanced/_metadata.yml
Labels: review:general

#5707 feat(api-products): updated analytics reports reference page
  app/konnect/analytics/reference.md
Labels: review:copyedit

#5714 Reordered 3.2.2.3 to be below 3.3.0.0 in the changelog
  app/gateway/changelog.md
Labels: review:general

#5684 [DOCU-2966] Add MinK permissions
  app/konnect/org-management/teams-and-roles/manage.md
  app/konnect/org-management/teams-and-roles/roles-reference.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#5716 Prevent badges' tooltips from being loaded in /hub
  app/_assets/javascripts/app.js
Labels: review:tech

#5717 Make rightnav collpasible on plugin pages
  app/_assets/stylesheets/pages/docs.less
  app/_assets/stylesheets/pages/extension.less
  app/_includes/plugins/right_nav.html
Labels: review:tech

#5432 [DOCU-3172] MinK: Overview + UI screenshot
  app/_assets/images/docs/konnect/konnect-control-plane-dashboard.png
  app/_assets/images/icons/konnect/icn-mesh-manager-nav.svg
  app/_data/docs_nav_konnect.yml
  app/konnect/mesh-manager/index.md
  app/konnect/mesh-manager/service-mesh.md
Labels: review:sme

#5705 fix(kic) update TLS listen creation
  app/_includes/md/kic/class.md
  app/_src/kubernetes-ingress-controller/guides/getting-started.md
  app/_src/kubernetes-ingress-controller/guides/using-gateway-api.md
Labels: review:general

#5735 Plugin configuration edit links
  .gitmodules
  app/_includes/plugins/header.html
  app/_plugins/generators/plugin_single_source/pages/base.rb
  app/_plugins/generators/plugin_single_source/pages/configuration.rb
  app/_plugins/generators/plugin_single_source/pages/configuration_examples.rb
  app/_plugins/generators/plugin_single_source/plugin/release.rb
  spec/app/_plugins/generators/plugin_single_source/pages/configuration_examples_spec.rb
  spec/app/_plugins/generators/plugin_single_source/pages/configuration_spec.rb
  spec/app/_plugins/generators/plugin_single_source/plugin/release_spec.rb
  spec/fixtures/app/_hub/kong-inc/jq/_metadata.yml
  spec/support/shared_contexts/site.rb
Labels: review:tech

#5732 feat(opentelemetry): add AWS header propagation
  app/_hub/kong-inc/opentelemetry/_changelog.md
  app/_hub/kong-inc/opentelemetry/_index.md
Labels: review:tech

#5055 [DOCU-2804] Konnect audit logging
  app/_assets/images/docs/konnect/konnect-audit-log-replay.png
  app/_assets/images/docs/konnect/konnect-audit-log-webhook.png
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/network.md
  app/konnect/org-management/audit-logging/index.md
  app/konnect/org-management/audit-logging/reference.md
  app/konnect/org-management/audit-logging/replay-job.md
  app/konnect/org-management/audit-logging/verify-signatures.md
  app/konnect/org-management/audit-logging/webhook.md
  app/konnect/updates.md
Labels: review:copyedit, ci:manual-approve:link-validation, review:sme, pending:release

#5715 Update: Kong Plugin Moesif Docs
  app/_hub/moesif/kong-plugin-moesif/_index.md
  app/_hub/moesif/kong-plugin-moesif/_metadata.yml
  app/_hub/moesif/kong-plugin-moesif/schemas/_index.json
Labels: review:copyedit

#5741 Audit logs: Uncomment access logs list item
  app/konnect/org-management/audit-logging/reference.md
Labels: review:general

#5660 Plugin API references + splitting ACL and ACME plugins to test
  app/_assets/images/icons/documentation/hub/icn-reference.svg
  app/_hub/kong-inc/acl/_api.md
  app/_hub/kong-inc/acl/_changelog.md
  app/_hub/kong-inc/acl/_index.md
  app/_hub/kong-inc/acl/_metadata.yml
  app/_hub/kong-inc/acl/how-to/_index.md
  app/_hub/kong-inc/acme/_api.md
  app/_hub/kong-inc/acme/_changelog.md
  app/_hub/kong-inc/acme/_index.md
  app/_hub/kong-inc/acme/_metadata.yml
  app/_hub/kong-inc/acme/how-to/_index.md
  app/_hub/kong-inc/acme/how-to/_local-testing-development.md
  app/_hub/kong-inc/acme/how-to/_redis.md
  app/_layouts/extension.html
  app/_layouts/plugins/configuration_examples.html
  app/_plugins/generators/plugin_single_source/pages/configuration.rb
  app/_plugins/generators/plugin_single_source/pages/configuration_examples.rb
  app/_plugins/generators/plugin_single_source/pages/references.rb
  app/_plugins/generators/plugin_single_source/plugin/pages_builder.rb
  app/_plugins/generators/plugin_single_source/plugin/release.rb
  spec/app/_plugins/generators/plugin_single_source/pages/configuration_spec.rb
  spec/app/_plugins/generators/plugin_single_source/plugin/release_spec.rb
  spec/app/_plugins/generators/seo/index_spec.rb
  spec/app/_plugins/generators/seo/sitemap_spec.rb
  spec/templates/plugins/configuration_spec.rb
  tests/plugin.test.js
Labels: review:tech, review:general

#5744 Bump mesh version
  app/_data/docs_nav_mesh_2.3.x.yml
  app/_data/kong_versions.yml
Labels: review:general

#5743 fix(kic): remove redundant comma
  app/_src/gateway/install/kubernetes/helm.md
  app/_src/gateway/install/kubernetes/kubectl.md
  app/_src/gateway/install/kubernetes/openshift.md
  app/_src/kubernetes-ingress-controller/guides/getting-started-istio.md
  app/gateway/2.6.x/install-and-run/helm.md
  app/gateway/2.6.x/install-and-run/kubernetes.md
  app/gateway/2.6.x/install-and-run/openshift.md
  app/gateway/2.7.x/install-and-run/helm.md
  app/gateway/2.7.x/install-and-run/kubernetes.md
  app/gateway/2.7.x/install-and-run/openshift.md
  app/gateway/2.8.x/install-and-run/helm.md
  app/gateway/2.8.x/install-and-run/kubernetes.md
  app/gateway/2.8.x/install-and-run/openshift.md
  app/kubernetes-ingress-controller/2.0.x/guides/getting-started-istio.md
  app/kubernetes-ingress-controller/2.1.x/guides/getting-started-istio.md
  app/kubernetes-ingress-controller/2.2.x/guides/getting-started-istio.md
Labels: review:general, area/docs

#5738 Add workspace name to redirect URIs
  app/_src/gateway/kong-enterprise/dev-portal/authentication/oidc.md
  app/_src/gateway/kong-manager/auth/oidc/configure.md
  app/_src/gateway/kong-plugins/authentication/oidc/curity.md
  app/gateway/2.8.x/configure/auth/oidc-curity.md
  app/gateway/2.8.x/developer-portal/configuration/authentication/oidc.md
Labels: review:general

#5749 POC: OAS Overlays
  api-specs/Gateway-EE/yaml/overlay.yaml
  api-specs/Gateway-OSS/yaml/overlay.yaml
  api-specs/Konnect/v0.1/json/konnect.json
  api-specs/Konnect/v0.1/yaml/konnect.yaml
  api-specs/Konnect/v2/yaml/overlay.yaml
  api-specs/readme.md
Labels: review:general

#5758 docs(KM): Kong Manager does not fix the issue in 2.8.4.0
  app/gateway/changelog.md
Labels: review:general

#5754 chore(kic): add istio 1.18 to version matrix
  app/_src/kubernetes-ingress-controller/references/version-compatibility.md
Labels: Kubernetes Team, review:general

#5490 [DOCU-3068] Portal Client API
  app/_data/docs_nav_konnect.yml
  app/konnect/api/index.md
  app/konnect/updates.md
Labels: review:general, pending:release

#5631 [DOCU-3188] OSS Client Portal
  app/_assets/images/docs/konnect/konnect-dev-portal-urls.png
  app/_assets/images/docs/konnect/konnect-self-hosted-portal-architecture.png
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/access.md
  app/konnect/dev-portal/customization/index.md
  app/konnect/dev-portal/customization/netlify.md
  app/konnect/dev-portal/customization/self-hosted-portal.md
  app/konnect/updates.md
Labels: review:copyedit, pending:release

#5737 Clarify group claims / team mapping in Konnect Okta setup
  app/konnect/org-management/okta-idp.md
Labels: review:tech, review:general

#5677 [DOCU-3157] Portal Client API SDK
  app/_data/docs_nav_konnect.yml
Labels: review:general, pending:release

#5733 Update jwt _index.md
  app/_hub/kong-inc/jwt/_index.md
Labels: review:general

#5765 fix: correcting dead example link on ACL plugin page
  app/_hub/kong-inc/acl/_index.md
Labels: review:general

#5764 Fix CP outage handling missing param
  app/_src/gateway/kong-enterprise/cp-outage-handling.md
Labels: review:general

#5376 DOCU-3061 Custom OIDC Scope Requests
  app/konnect/updates.md
Labels: review:copyedit, ci:manual-approve:link-validation, pending:release

#5752 Add advanced settings instructions
  app/konnect/org-management/oidc-idp.md
Labels: review:copyedit, ci:manual-approve:link-validation, pending:release
