Repository Kong/docs.konghq.com, pull requests merged in 2023-01, with the labels that each got.

#4917 refactor(portal-cli): clarify details about variables
  app/_src/gateway/kong-enterprise/dev-portal/cli.md
Labels: review:general

#4983 Update changelog.md
  app/mesh/changelog.md
Labels: review:general

#4973 Fixed extra http in API call
  app/konnect/api/runtime-groups-config/index.md
Labels: review:general, ci:check-skipped:generated-files

#4945 Updating how to pass env variables
  app/_src/gateway/kong-enterprise/secrets-management/backends/env.md
Labels: review:general

#4984 Minor fixes to konnect deck onboarding
  app/konnect/getting-started/configure-runtime.md
  app/konnect/runtime-manager/runtime-groups/declarative-config.md
Labels: review:general

#4954 plugin(RLA): custom response
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
Labels: review:general

#4894 Revise KIC plugin and auth guides for GWAPI
  app/_data/docs_nav_kic_1.0.x.yml
  app/_data/docs_nav_kic_1.1.x.yml
  app/_data/docs_nav_kic_1.2.x.yml
  app/_data/docs_nav_kic_1.3.x.yml
  app/_data/docs_nav_kic_2.0.x.yml
  app/_data/docs_nav_kic_2.1.x.yml
  app/_data/docs_nav_kic_2.2.x.yml
  app/_data/docs_nav_kic_2.3.x.yml
  app/_data/docs_nav_kic_2.4.x.yml
  app/_data/docs_nav_kic_2.5.x.yml
  app/_data/docs_nav_kic_2.6.x.yml
  app/_data/docs_nav_kic_2.7.x.yml
  app/_data/docs_nav_kic_2.8.x.yml
  app/_includes/md/kic/consumer.md
  app/_includes/md/kic/http-test-routing-resource.md
  app/_includes/md/kic/http-test-routing.md
  app/_includes/md/kic/key-auth.md
  app/_src/kubernetes-ingress-controller/guides/cert-manager.md
  app/_src/kubernetes-ingress-controller/guides/configure-acl-plugin.md
  app/_src/kubernetes-ingress-controller/guides/configuring-fallback-service.md
  app/_src/kubernetes-ingress-controller/guides/configuring-health-checks.md
  app/_src/kubernetes-ingress-controller/guides/configuring-https-redirect.md
  app/_src/kubernetes-ingress-controller/guides/getting-started.md
  app/_src/kubernetes-ingress-controller/guides/redis-rate-limiting.md
  app/_src/kubernetes-ingress-controller/guides/routing-by-header.md
  app/_src/kubernetes-ingress-controller/guides/using-consumer-credential-resource.md
  app/_src/kubernetes-ingress-controller/guides/using-external-service.md
  app/_src/kubernetes-ingress-controller/guides/using-gateway-api.md
  app/_src/kubernetes-ingress-controller/guides/using-kong-with-knative.md
  app/_src/kubernetes-ingress-controller/guides/using-kongclusterplugin-resource.md
  app/_src/kubernetes-ingress-controller/guides/using-kongingress-resource.md
  app/_src/kubernetes-ingress-controller/guides/using-kongplugin-resource.md
  app/_src/kubernetes-ingress-controller/guides/using-oidc-plugin.md
  app/kubernetes-ingress-controller/1.0.x/guides/overview.md
  app/kubernetes-ingress-controller/1.1.x/guides/overview.md
  app/kubernetes-ingress-controller/1.2.x/guides/overview.md
  app/kubernetes-ingress-controller/1.3.x/guides/overview.md
  app/kubernetes-ingress-controller/2.0.x/guides/overview.md
  app/kubernetes-ingress-controller/2.1.x/guides/overview.md
  app/kubernetes-ingress-controller/2.2.x/guides/overview.md
Labels: review:general, review:copyedit

#4921 feat(key-auth-enc): support tags of a key (FTI-4084)
  app/_hub/kong-inc/key-auth-enc/_index.md
Labels: ready, review:copyedit

#4976 python pdk doc improvements
  app/_src/gateway/plugin-development/pluginserver/python.md
Labels: review:tech, review:general

#4987 [fix] Spelling in Route By Header plugin
  app/_hub/kong-inc/route-by-header/_index.md
Labels: review:general

#4888 fix(route): update route.protocols document
  app/_src/gateway/admin-api/index.md
Labels: review:general, ci:check-skipped:generated-files

#4989 docs(mesh): add changelog for 1.9.2
  app/mesh/changelog.md
Labels: review:general

#4979 add datadog & statsd plugin missing doc
  app/_hub/kong-inc/datadog/_index.md
  app/_hub/kong-inc/statsd/_index.md
Labels: review:general

#4908 [FTI-2972] bump the default `pg_ssl_version` to `tlsv1_2` and update the accepted values
  app/_src/gateway/reference/configuration.md
Labels: review:general, ci:prevent-merge:generated-files, ci:check-skipped:generated-files

#4988 feat(mtls-auth): document the new allow_partial_chain parameter
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/mtls-auth/_index.md
Labels: review:copyedit

#4924 Makes the PDK file structure slightly more consistent
  app/_src/gateway/plugin-development/file-structure.md
Labels: review:general

#4996 Getting started mention advanced docs
  app/_src/gateway/get-started/index.md
Labels: review:general

#4998 [fix] broken link in vault-auth plugin doc.
  app/_hub/kong-inc/vault-auth/_index.md
Labels: review:general

#4993 Gateway 2.8.2.3: Changelog and parameters
  app/_data/kong_versions.yml
  app/gateway/2.8.x/reference/configuration.md
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:check-skipped:generated-files, ci:manual-approve:generated-files

#4972 New kong.conf directives for Prometheus plugin
  app/_hub/kong-inc/prometheus/_1.6.0.md
  app/_hub/kong-inc/prometheus/_index.md
Labels: review:copyedit

#4986 [docu-2892] Konnect CP Upgrade faq
  app/_data/docs_nav_konnect.yml
  app/konnect/upgrade-faq.md
Labels: review:copyedit

#5000 Use variable for kong gateway version in Konnect K8s doc
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-kubernetes.md
Labels: review:general

#4982 mesh: new policy rbac qualifiers
  app/_src/mesh/features/rbac.md
Labels: review:general

#4994 Updated ingress declaration examples to match
  app/_src/kubernetes-ingress-controller/concepts/ingress-versions.md
Labels: review:copyedit

#5001 Remove note about decK support
  app/_src/gateway/kong-enterprise/consumer-groups/index.md
Labels: review:general

#5007 Version support pages show a single product
  app/_includes/md/support-policy.md
  app/_src/gateway/support-policy.md
  app/_src/kubernetes-ingress-controller/support-policy.md
  app/_src/mesh/support-policy.md
  app/gateway/2.8.x/support-policy.md
Labels: review:general

#4990 Add placeholders for `kuma` and `kuma/kuma` used in Mesh docs
  jekyll-dev.yml
  jekyll.yml
Labels: review:tech

#5002 Add tags to key-auth-enc plugin; update examples
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/key-auth-enc/_index.md
  app/_hub/kong-inc/key-auth/_index.md
Labels: review:general

#5009 Helm Chart README moved to official documentation
  .github/styles/kong/dictionary.txt
  app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
Labels: review:tech, review:general, review:copyedit

#5005 docs(portal): add warning for auth0 configuration [TDX-2739]
  app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
Labels: review:general

#4934 Add description of basic routing logic of Kong Gateway
  app/_src/gateway/get-started/services-and-routes.md
  app/_src/gateway/how-kong-works/routing-traffic.md
  app/_src/gateway/key-concepts/routes/index.md
Labels: review:copyedit

#5012 [DOCU-2880] Plugin konnect examples
  app/_hub/kong-inc/app-dynamics/_index.md
  app/_hub/kong-inc/degraphql/_index.md
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
  app/_hub/kong-inc/tls-handshake-modifier/_index.md
  app/_hub/kong-inc/tls-metadata-headers/_index.md
Labels: review:general

#5015 docs(prometheus): update dashboard url
  app/_hub/kong-inc/prometheus/_index.md
Labels: review:general

#5013 [DOCU-2900] Add tags to consumer groups examples and reference
  app/_src/gateway/admin-api/consumer-groups/reference.md
  app/_src/gateway/kong-enterprise/consumer-groups/index.md
Labels: review:general

#5011 Rate Limiting Advanced plugin: Improve config.namespace description
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
Labels: review:copyedit

#5016 [DOCU-2373] Key auth encrypted plugin: Re-add ttl when parameter is available
  app/_hub/kong-inc/key-auth-enc/_index.md
Labels: review:general

#5025 ft(rate-limiting-advanced): allow 'cluster' strategy with 'sync_rate …
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
Labels: review:copyedit

#5023 [DOCU-669] Datatypes for serverless functions plugin
  app/_hub/kong-inc/serverless-functions/_index.md
Labels: review:general

#5028 DCR Curity [GA]
  app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
Labels: review:general, pending:release

#5024 [DOCU-2212] Zipkin: Document missing parameter default_service_name
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/zipkin/_index.md
Labels: review:copyedit

#5031 docs(mesh): add changelog for 1.6.3, 1.7.5, 1.8.4
  app/mesh/changelog.md
Labels: review:general

#5022 [DOCU-2840] AppDynamics plugin: Prereqs section with platform info
  .github/styles/kongplugins/dictionary.txt
  app/_hub/kong-inc/app-dynamics/_index.md
Labels: review:copyedit

#5021 Add missing anchor link on upgrade page
  app/_src/gateway/upgrade-31x.md
Labels: review:general

#5020 OAS Validation plugin: Not supported in Konnect
  app/_data/tables/plugin_index.yml
  app/_hub/kong-inc/oas-validation/_index.md
Labels: review:general

#5003 Clarify redis.username on all plugins that support it
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_index.md
  app/_hub/kong-inc/openid-connect/_index.md
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
  app/_hub/kong-inc/rate-limiting/_index.md
  app/_hub/kong-inc/response-ratelimiting/_index.md
  app/_hub/kong-inc/saml/_index.md
Labels: review:general

#5017 Add note about seeding super-admin password
  app/_includes/md/gateway/setup.md
Labels: review:tech, review:general

#5029 Simplify PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/styles/kong/dictionary.txt
  .github/workflows/require-review-label.yml
Labels: review:tech

#5037 Update kuma submodule with `make install`
  Makefile
Labels: review:tech

#5036 PR template fixes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: review:general

#5034 Tweak: Adds minor copy edits to the workspaces and teams page
  app/_src/gateway/kong-manager/auth/workspaces-and-teams.md
Labels: review:general

#5041 FTI-4690: Notes a limitation in Kong 2.8.2.3 in regard to dynamically linked PCRE library
  app/gateway/changelog.md
Labels: review:general

#5033 docs(mesh): add new release changelog and fix old one
  app/mesh/changelog.md
Labels: do not merge, review:general

#5035 Add auto-close Kong issues workflow
  .github/workflows/auto-close-kong-issues.yml
Labels: review:tech

#5047 Remove Amazon Linux segfaults fix from changelog
  app/gateway/changelog.md
Labels: review:general

#5018 [DOCU-2582] Add single source docs to the Contributing guide
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_contributing.yml
  app/contributing/community-expectations.md
  app/contributing/community.md
  app/contributing/conditional-rendering.md
  app/contributing/contribution-templates.md
  app/contributing/hackathons.md
  app/contributing/includes.md
  app/contributing/index.md
  app/contributing/markdown-rules.md
  app/contributing/plugin-docs.md
  app/contributing/single-sourced-plugins.md
  app/contributing/single-sourced-versions.md
  app/contributing/style-guide.md
  app/contributing/variables.md
  app/contributing/word-choice.md
  docs/single-sourced-plugins.md
  docs/single-sourced-versions.md
  jekyll-dev.yml
  jekyll.yml
Labels: review:copyedit

#5051 [cherry-pick] how-to configure Auth0 DCR [TDX-2715] (#4952)
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
  app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
Labels: review:general

#5056 Add some common issues to style guide
  app/contributing/style-guide.md
Labels: review:copyedit

#5061 Update _index.md
  app/_hub/kong-inc/opentelemetry/_index.md
Labels: review:general

#4911 [DOCU-2776] Consumer Groups for Konnect
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/konnect/runtime-manager/consumer-groups.md
Labels: review:copyedit, pending:release

#5049 [DOCU-2911] Request transformer advanced plugin: JSON object and array parameters
  app/_hub/kong-inc/request-transformer-advanced/_index.md
Labels: review:copyedit

#5057 Release: Gateway 2.8.2.4
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#5065 fix: remove hardcoded region [TDX-2826]
  app/konnect/api/portal-auth/portal-rbac-guide.md
Labels: review:tech

#5066 Fix Typo in the additional abilities listing
  app/_hub/kong-inc/response-transformer/_index.md
Labels: review:general

#5060 Add prometheus to supported strategies list
  app/_src/gateway/kong-enterprise/analytics/index.md
  app/gateway/2.8.x/vitals/index.md
Labels: review:general

#4966 docs(rate-limiting-advanced): revise parameters descriptions
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
Labels: review:tech, review:general

#5045 feat(opa): support custom message from OPA server (FTI-4574)
  app/_hub/kong-inc/opa/_index.md
Labels: review:copyedit

#5067 [fix] Mention where to find the Dev Portal Portal ID
  app/konnect/api/portal-auth/portal-rbac-guide.md
Labels: review:general

#5068 Fix indent in release notes
  app/konnect/updates.md
Labels: review:general

#5063 OIDC plugin: Add PKCE to list of supported credentials and grants
  app/_hub/kong-inc/openid-connect/_index.md
Labels: review:general

#5048 Release: Gateway 3.1.1.2 (changelog)
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#5038 [DOCU-2906] OAS validation plugin is bundled with Kong
  app/_hub/kong-inc/oas-validation/_index.md
  app/_hub/kong-inc/oas-validation/versions.yml
Labels: review:general

#5032 DOCU-2908 Endpoint deprecation note and instruction
  app/_src/gateway/kong-enterprise/analytics/index.md
Labels: review:copyedit

#5069 chore: Bump deck version to 1.17.2
  app/_data/kong_versions.yml
Labels: review:general

#4919 [DOCU-2795] Plugin ordering Konnect
  app/_data/docs_nav_konnect.yml
  app/konnect/runtime-manager/index.md
  app/konnect/runtime-manager/plugins.md
Labels: review:copyedit, ci:check-skipped:generated-files, pending:release

#4902 [docu-2805] Update docker script
  app/_includes/md/konnect/runtime-certs.md
  app/konnect/runtime-manager/runtime-instances/gateway-runtime-docker.md
Labels: review:general, pending:release

#5082 Custom Reports part 1
  app/konnect/analytics/custom-reports/use-cases.md
Labels: review:general

#5014 remove Important warning from the top of the Event Hooks reference page
  app/_src/gateway/admin-api/event-hooks/reference.md
Labels: review:general

#5071 Chore/updateirma
  app/konnect/dev-portal/applications/enable-app-reg.md
Labels: review:copyedit

#5080 [DOCU-857] Using workspaces in an Admin API request
  app/_includes/md/gateway/admin-api-workspaces.md
  app/_src/gateway/admin-api/admin-api-3.0.x.md
  app/_src/gateway/admin-api/developers/reference.md
  app/_src/gateway/admin-api/index.md
  app/_src/gateway/admin-api/workspaces/reference.md
  app/_src/gateway/kong-enterprise/workspaces/index.md
  app/gateway/2.8.x/admin-api/index.md
  app/gateway/2.8.x/admin-api/workspaces/examples.md
  app/gateway/2.8.x/admin-api/workspaces/reference.md
Labels: review:copyedit, ci:manual-approve:linting, ci:manual-approve:generated-files

#5077 docs: update kong mesh changelog
  app/mesh/changelog.md
Labels: review:general

#5078 docs(policies): add note about one policy for kong mesh opa
  app/_src/mesh/features/opa.md
  app/mesh/1.2.x/features/opa.md
  app/mesh/1.3.x/features/opa.md
  app/mesh/1.4.x/features/opa.md
  app/mesh/1.5.x/features/opa.md
  app/mesh/1.6.x/features/opa.md
Labels: review:general

#5076 docs(kong-mesh): initial mesh opa docs
  app/_data/docs_nav_mesh_2.1.x.yml
  app/_src/mesh/features/meshopa.md
Labels: review:general

#5086 Adding additional roles to the reference table
  app/konnect/org-management/teams-and-roles/roles-reference.md
Labels: review:general

#5091 docs(meshopa): fix missing container and namespace
  app/_src/mesh/features/meshopa.md
Labels: review:general

#5084 Remove stray line in app reg doc
  app/konnect/dev-portal/applications/enable-app-reg.md
Labels: review:general

#5095 docs(mesh): fixed model of MeshOPA and removed mesh name
  app/_src/mesh/features/meshopa.md
Labels: review:general

#5100 Fix Konnect api link
  app/konnect/api/runtime-groups-config/index.md
Labels: review:general, ci:prevent-merge:generated-files

#5096 docs(openid-connect): docs improvements
  app/_hub/kong-inc/openid-connect/_index.md
Labels: review:general, review:copyedit

#5099 Release/Gateway 3.1.1.3: Changelog and version bump
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit

#5093 chore(docs) add Kong Mesh 2.1.0 changelog
  app/mesh/changelog.md
Labels: review:copyedit
