Repository Kong/docs.konghq.com, pull requests merged in 2023-08, with the labels that each got.

#5878 Set `kong_version` to hub pages.
  app/_plugins/blocks/inline_plugin_example/config.rb
  app/_plugins/generators/plugin_single_source/plugin/base.rb
  app/_plugins/generators/plugin_single_source/plugin/page_data.rb
  app/_plugins/generators/plugin_single_source/plugin/release.rb
  app/_plugins/generators/plugin_single_source/plugin/unversioned.rb
  spec/app/_plugins/blocks/inline_plugin_example/config_spec.rb
  spec/app/_plugins/generators/plugin_single_source/plugin/unversioned_spec.rb
  spec/app/_plugins/generators/plugin_single_source/plugin/versioned_spec.rb
  spec/app/_plugins/generators/versions_spec.rb
Labels: review:tech

#5877 Install foreman before running scheduled broken link checker
  .github/workflows/scheduled-broken-link-checker.yml
Labels: review:tech

#5879 fix: Adjust the margin on the "old version" header in plugin docs
  app/_assets/stylesheets/pages/extension.less
Labels: review:general

#5882 [Autodocs] PDK and API documentation
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_src/gateway/plugin-development/pdk/index.md
  app/_src/gateway/plugin-development/pdk/kong.client.md
  app/_src/gateway/plugin-development/pdk/kong.plugin.md
  app/_src/gateway/plugin-development/pdk/kong.request.md
  app/_src/gateway/plugin-development/pdk/kong.service.md
  app/_src/gateway/plugin-development/pdk/kong.tracing.md
  app/_src/gateway/plugin-development/pdk/kong.vault.md
Labels: review:general

#5759 feat(DCR): add Azure DCR instructions
  app/_data/docs_nav_konnect.yml
  app/_data/tables/support/gateway/third-party.yml
  app/konnect/dev-portal/applications/dynamic-client-registration/azure.md
  app/konnect/dev-portal/applications/dynamic-client-registration/index.md
  app/konnect/updates.md
Labels: review:general, review:sme, pending:release

#5888 chore: update docs for more clarity around oss portal
  app/konnect/dev-portal/customization/index.md
Labels: review:general, review:copyedit

#5885 Migrate from Cassandra to PostgreSQL
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_src/gateway/migrate-cassandra-to-postgres.md
  app/assets/images/docs/gateway/migration.png
Labels: review:copyedit

#5887 Add: badges for Konnect/free support, fix landing pages
  app/_hub/moesif/kong-plugin-moesif/_index.md
  app/_hub/moesif/kong-plugin-moesif/_metadata.yml
Labels: review:general

#5894 AdminAPI - Add cascade query param to workspace endpoints, fix issue with validate plugin endpoint.
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
Labels: review:general

#5890 Fix static assets
  app/assets/kubernetes-ingress-controller/examples/echo-service.yaml
  app/assets/kubernetes-ingress-controller/examples/echo-services.yaml
  app/assets/kubernetes-ingress-controller/examples/tcp-echo-service.yaml
  config/vite.json
  jekyll-dev.yml
  jekyll.yml
Labels: review:tech

#5886 feat: Remove Alpine instructions from Docker install instructions for 3.4
  app/_data/tables/install_options_34x.yml
  app/_src/gateway/install/docker/build-custom-images.md
  app/_src/gateway/install/index.md
Labels: review:general

#5779 docs(secrets-management): update docs with vault rotation and some small adjustments
  .github/styles/kong/auto-ignore.txt
  app/_src/gateway/kong-enterprise/secrets-management/advanced-usage.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/gcp-sm.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
  app/_src/gateway/kong-enterprise/secrets-management/secrets-rotation.md
  app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/hashicorp-vault.md
Labels: review:general, review:copyedit, review:sme, pr/please review

#5841 [DOCU-3167] Update references to Amazon Linux 2023
  app/_data/tables/install_options.yml
  app/_data/tables/support/gateway/packages.yml
  app/_src/gateway/install/linux/amazon-linux.md
Labels: review:general

#5889 Update expression router documentation for kong 3.4
  app/_src/gateway/reference/router-expressions-language.md
Labels: review:tech, review:sme

#5907 deprecated `overrides` endpoint note, cascade endpoint added to workspace delete.
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  app/_src/gateway/admin-api/index.md
  app/_src/gateway/admin-api/workspaces/reference.md
Labels: review:general

#5908 chore: Copy over nav changes from 3.3 to 3.4
  app/_data/docs_nav_gateway_3.4.x.yml
Labels: review:general

#5902 Update index.md
  app/_src/gateway/support/index.md
Labels: review:copyedit

#5910 fix: modify language around patches
  app/gateway/2.8.x/support-policy.md
Labels: review:general

#5895 Chore: Fix vale, Update Github action
  .github/styles/kong/Terms.yml
  .github/workflows/linting.yml
  app/_src/gateway/plugin-development/tests.md
Labels: review:general

#5911 chore: Add 3.4 version to Gateway upgrade doc
  app/_src/gateway/upgrade-v2.md
Labels: review:general

#5840 Add documentation for Gateway 3.4 Wasm support
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_src/gateway/plugin-development/wasm.md
  app/_src/gateway/reference/wasm.md
Labels: review:copyedit

#5905 chore: Changelog for Kong Gateway 3.4.0.0
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_changelog.md
  app/_hub/kong-inc/kafka-log/_changelog.md
  app/_hub/kong-inc/kafka-log/_index.md
  app/_hub/kong-inc/openid-connect/_changelog.md
  app/_hub/kong-inc/opentelemetry/_changelog.md
  app/_hub/kong-inc/rate-limiting-advanced/_changelog.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#5914 chore: Breaking changes in Kong Gateway 3.4
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_src/gateway/breaking-changes/32x.md
  app/_src/gateway/breaking-changes/34x.md
  app/_src/gateway/migrate-cassandra-to-postgres.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation, ci:manual-approve:linting

#5919 chore: Add gpg/rsa gateway-34 repo keys
  app/_data/installation/gateway.yml
Labels: review:general

#5918 chore: add compatibility issues for v3.4
  app/_data/tables/version_errors_konnect.yml
Labels: review:general

#5891 increased display limit improvement [KP-312]
  app/konnect/analytics/index.md
  app/konnect/updates.md
Labels: review:copyedit

#5922 Update Insomnia buttons in Admin API spec
  api-specs/Gateway-EE/3.4/kong-ee-3.4.json
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.json
  app/_src/gateway/admin-api/index.md
Labels: review:general

#5923 fix: Ubuntu installation links are using old release
  app/_src/gateway/install/docker/build-custom-images.md
  app/_src/gateway/install/linux/debian.md
  app/_src/gateway/install/linux/ubuntu.md
Labels: review:general

#5925 Fix: Issue with override message in the wrong field
  api-specs/Gateway-EE/3.4/kong-ee-3.4.json
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
Labels: review:general

#5926 fix: Amazon Linux 2023 installation links
  app/_src/gateway/install/linux/amazon-linux.md
Labels: review:general

#5927 fix: malformed yml
  app/_data/tables/version_errors_konnect.yml
Labels: bug, review:general

#5928 Fix Gateway 3.4 LTS date
  app/_src/gateway/support/index.md
Labels: review:general

#5930 Fix: Add date to gateway changelog
  app/gateway/changelog.md
Labels: review:general

#5766 [DOCU-3304][DOCU-3305] Fonts and sidebar
  app/_assets/stylesheets/accordion.less
  app/_assets/stylesheets/base.less
  app/_assets/stylesheets/footer.less
  app/_assets/stylesheets/navtabs.less
  app/_assets/stylesheets/page.less
  app/_assets/stylesheets/pages/docs.less
  app/_assets/stylesheets/pages/extension.less
  app/_assets/stylesheets/utils.less
  app/_assets/stylesheets/variables.less
  app/_layouts/extension.html
  app/assets/images/icons/documentation/icn-admin-api-color.svg
  app/assets/images/icons/documentation/icn-api-plugins-color.svg
  app/assets/images/icons/documentation/icn-brain-color.svg
  app/assets/images/icons/documentation/icn-deployment-color.svg
  app/assets/images/icons/documentation/icn-dev-portal-color.svg
  app/assets/images/icons/documentation/icn-developer.svg
  app/assets/images/icons/documentation/icn-documentation-small.svg
  app/assets/images/icons/documentation/icn-enterprise-blue.svg
  app/assets/images/icons/documentation/icn-faq-color.svg
  app/assets/images/icons/documentation/icn-flag.svg
  app/assets/images/icons/documentation/icn-immunity-color.svg
  app/assets/images/icons/documentation/icn-kubernetes-color.svg
  app/assets/images/icons/documentation/icn-learning.svg
  app/assets/images/icons/documentation/icn-manager-color.svg
  app/assets/images/icons/documentation/icn-overview-color.svg
  app/assets/images/icons/documentation/icn-quickstart-color.svg
  app/assets/images/icons/documentation/icn-references-color.svg
  app/assets/images/icons/documentation/icn-runtime-manager-color.svg
  app/assets/images/icons/documentation/icn-service-hub-color.svg
  app/assets/images/icons/documentation/icn-solution-guide.svg
  app/assets/images/icons/documentation/icn-vitals.svg
  app/assets/images/icons/konnect/icn-analytics-nav.svg
  app/assets/images/icons/konnect/icn-api-product.svg
  app/assets/images/icons/konnect/icn-cogwheel-nav.svg
  app/assets/images/icons/konnect/icn-dev-portal-nav.svg
  app/assets/images/icons/konnect/icn-organizations-nav.svg
  app/assets/images/icons/konnect/icn-runtimes-nav.svg
  app/assets/images/icons/konnect/icn-servicehub-nav.svg
Labels: do not merge, review:tech, review:general

#5904 feat: Update docs for Konnect support of vault secret TTL rotation
  app/konnect/runtime-manager/configuration/vaults/how-to.md
  app/konnect/runtime-manager/configuration/vaults/index.md
  app/konnect/updates.md
Labels: review:general, pending:release

#5892 feat(gha): allow verbose link checking
  .github/workflows/check-links.yml
Labels: review:tech

#5875 chore: Split app reg plugin how-tos
  .github/styles/kongplugins/plugin-ignore.txt
  app/_hub/kong-inc/application-registration/_index.md
  app/_hub/kong-inc/application-registration/how-to/_index.md
Labels: review:copyedit

#5876 chore: Move Rate limiting library to references
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_redirects
  app/_src/gateway/kong-plugins/rate-limiting/algorithms/fixed-bucket.md
  app/_src/gateway/kong-plugins/rate-limiting/index.md
  app/_src/gateway/reference/rate-limiting.md
  app/moved_urls.yml
Labels: review:general

#5939 Update azure.md
  app/konnect/dev-portal/access-and-approval/azure.md
Labels: review:general

#5940 Updated deck file add-plugins reference
  app/_src/deck/reference/deck_file_add-plugins.md
Labels: review:copyedit, ci:prevent-merge:generated-files

#5941 Chore: Update changelog to add note about overrides endpoint deprecation.
  app/_hub/kong-inc/rate-limiting-advanced/_changelog.md
  app/_src/gateway/breaking-changes/34x.md
Labels: review:general

#5944 Fix automated package installation tests
  app/_src/gateway/install/linux/amazon-linux.md
  app/_src/gateway/install/linux/ubuntu.md
  tools/install-tester/execute-in-docker.js
  tools/install-tester/index.js
Labels: review:sme

#5946 Konnect support for Gateway 3.4
  app/konnect/updates.md
Labels: review:general, skip-changelog

#5945 Consumer groups scoping support for Konnect
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/updates.md
Labels: review:general

#5949 Fix Ubuntu 3.4 package install instructions
  app/_src/gateway/install/linux/ubuntu.md
Labels: review:general

#5935 feat: last valid config in KIC
  app/_src/kubernetes-ingress-controller/concepts/ha-and-scaling.md
Labels: review:copyedit

#5950 Fix link to docker installation
  app/_includes/md/enterprise/deploy-license.md
Labels: review:general

#5951 Fix: Fix links to consumer groups API documentation
  app/_src/gateway/kong-enterprise/index.md
Labels: review:general, skip-changelog

#5948 Update Konnect Runtime Install Options image
  app/konnect/runtime-manager/runtime-instances/index.md
Labels: review:general

#5952 fix: Broken step indents in Mesh license guide
  app/_src/mesh/production/cp-deployment/license.md
Labels: review:general

#5954 Change directories in Konnect section as a foundation for renaming
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/gateway-manager/backup-restore.md
  app/konnect/gateway-manager/configuration/consumer-groups.md
  app/konnect/gateway-manager/configuration/index.md
  app/konnect/gateway-manager/configuration/vaults/how-to.md
  app/konnect/gateway-manager/configuration/vaults/index.md
  app/konnect/gateway-manager/control-plane-groups/conflicts.md
  app/konnect/gateway-manager/control-plane-groups/how-to.md
  app/konnect/gateway-manager/control-plane-groups/index.md
  app/konnect/gateway-manager/control-plane-groups/migrate.md
  app/konnect/gateway-manager/data-plane-nodes/custom-dp-labels.md
  app/konnect/gateway-manager/data-plane-nodes/index.md
  app/konnect/gateway-manager/data-plane-nodes/renew-certificates.md
  app/konnect/gateway-manager/data-plane-nodes/runtime-parameter-reference.md
  app/konnect/gateway-manager/data-plane-nodes/upgrade.md
  app/konnect/gateway-manager/data-plane-nodes/verify-instance.md
  app/konnect/gateway-manager/declarative-config.md
  app/konnect/gateway-manager/enable-route-plugin.md
  app/konnect/gateway-manager/enable-service-plugin.md
  app/konnect/gateway-manager/index.md
  app/konnect/gateway-manager/kic.md
  app/konnect/gateway-manager/plugins.md
  app/konnect/gateway-manager/troubleshoot.md
  app/konnect/gateway-manager/version-compatibility.md
Labels: review:general, skip-changelog

#5955 fix: Add changelog entry for RHEL 9 support
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#5958 Fix kic broken link
  app/_includes/md/kic/crd-ref/kong_consumer_group_description.md
Labels: review:general

#5963 fix(.github): use correct token in sync-kuma-submodule
  .github/workflows/sync-kuma-submodule.yml
Labels: review:tech

#5965 (fix) Remove Docker from RHEL8 in 3.4 matrix
  app/_data/tables/support/gateway/versions/34.yml
Labels: review:general

#5966 fix(_redirects): add missing mesh opa redirect
  app/_redirects
Labels: review:general

#5968 (fix) Add Runtime Groups limit
  app/konnect/runtime-manager/configuration/index.md
Labels: review:general

#5962 Fix: Rendering issue on clusering reference page.
  app/_src/gateway/production/clustering.md
Labels: review:general, skip-changelog

#5967 (Fix) RHEL8 Docker Image deprecation
  app/gateway/changelog.md
Labels: review:general

#5740 DOCU-3261 Makelog changelog entry
  app/konnect/updates.md
Labels: review:general, pending:release

#5976 Fix: Status badge on README
  README.md
Labels: review:general, skip-changelog

#5977 Chore: Add path parameter style note to style guide
  app/contributing/style-guide.md
Labels: review:general, skip-changelog

#5985 Add `consumer_group` section to the plugin schemas
  app/_includes/plugins/schema.html
Labels: review:general

#5986 fix: Indent in Konnect Getting Started Guide step
  app/konnect/getting-started/deploy-service.md
Labels: review:general

#5983 Fix fields name in router expression reference
  app/_src/gateway/reference/router-expressions-language.md
Labels: review:tech

#5865 Add KongConsumerGroup documentation for KIC
  app/_src/kubernetes-ingress-controller/concepts/custom-resources.md
  app/_src/kubernetes-ingress-controller/guides/using-kongplugin-resource.md
Labels: review:general, review:copyedit, review:sme

#5975 Update consumer groups documentation
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
  app/_src/gateway/kong-enterprise/consumer-groups/index.md
Labels: do not merge, review:general

#5988 fix example
  app/_hub/kong-inc/response-transformer/_index.md
Labels: review:copyedit

#5990 Updated Kong Gateway upgrade guide to be the source of truth for future docs updates
  app/_src/gateway/upgrade-v2.md
Labels: review:general

#5829 feat(opentelemetry): propagate GCP trace header
  app/_hub/kong-inc/opentelemetry/_changelog.md
  app/_hub/kong-inc/opentelemetry/_index.md
Labels: review:copyedit

#5970 feat: Konnect API examples for plugins
  app/_hub/kong-inc/app-dynamics/_metadata.yml
  app/_hub/kong-inc/application-registration/_metadata.yml
  app/_hub/kong-inc/datadog/_metadata.yml
  app/_hub/kong-inc/exit-transformer/_metadata.yml
  app/_hub/kong-inc/jq/_metadata.yml
  app/_hub/kong-inc/key-auth-enc/_metadata.yml
  app/_hub/kong-inc/oauth2-introspection/_metadata.yml
  app/_hub/kong-inc/oauth2/_metadata.yml
  app/_hub/kong-inc/opentelemetry/_metadata.yml
  app/_hub/kong-inc/openwhisk/_metadata.yml
  app/_hub/kong-inc/request-size-limiting/_metadata.yml
  app/_hub/kong-inc/request-transformer-advanced/_metadata.yml
  app/_hub/kong-inc/request-transformer/_metadata.yml
  app/_hub/kong-inc/response-transformer-advanced/_metadata.yml
  app/_hub/kong-inc/route-by-header/_metadata.yml
  app/_hub/kong-inc/route-transformer-advanced/_metadata.yml
  app/_hub/kong-inc/serverless-functions/_metadata.yml
  app/_hub/kong-inc/vault-auth/_0.3.0/_metadata.yml
  app/_hub/kong-inc/vault-auth/_metadata.yml
  app/_hub/kong-inc/zipkin/_metadata.yml
  app/_includes/plugins/hub-examples/consumer.html
  app/_includes/plugins/hub-examples/consumer_groups.html
  app/_includes/plugins/hub-examples/global.html
  app/_includes/plugins/hub-examples/konnect.html
  app/_includes/plugins/hub-examples/route.html
  app/_includes/plugins/hub-examples/service.html
  app/_includes/plugins/schema.html
  app/_plugins/blocks/inline_plugin_example/config.rb
  app/_plugins/drops/plugins/examples/curl.rb
  app/_plugins/drops/plugins/examples/konnect.rb
  app/_plugins/drops/plugins/examples/yaml.rb
  app/_plugins/drops/plugins/hub_examples.rb
  app/_plugins/generators/plugin_single_source/plugin/page_data.rb
  app/contributing/conditional-rendering.md
  app/contributing/markdown-rules.md
  app/contributing/style-guide.md
  spec/app/_plugins/drops/plugins/example_spec.rb
  spec/app/_plugins/drops/plugins/examples/curl_spec.rb
  spec/app/_plugins/drops/plugins/examples/yaml_spec.rb
  spec/fixtures/app/_hub/_init/my-extension/_index.md
  spec/fixtures/app/_hub/kong-inc/jq/_metadata.yml
Labels: do not merge, review:tech, review:copyedit

#6004 Don't prevent default behaviour on enter
  app/_assets/javascripts/navbar.js
Labels: review:tech

#6005 Bump activesupport
  Gemfile.lock
Labels: review:tech

#5999 fix: Add missing metadata to appdynamics and serverless functions plugins
  app/_hub/kong-inc/app-dynamics/_metadata.yml
  app/_hub/kong-inc/serverless-functions/_metadata.yml
Labels: review:general

#5987 Konnect rename: references
  app/konnect/reference/labels.md
  app/konnect/reference/plugins.md
Labels: review:general, skip-changelog

#5991 Konnect Rename: API section
  app/konnect/api/identity-management/identity-integration.md
  app/konnect/api/index.md
  app/konnect/api/portal-auth/portal-rbac-guide.md
  app/konnect/org-management/audit-logging/reference.md
  app/konnect/org-management/deactivation.md
Labels: review:general, skip-changelog

#5953 Rename: Konnect introduction section
  app/_redirects
  app/konnect/architecture.md
  app/konnect/gateway-manager/data-plane-nodes/index.md
  app/konnect/index.md
  app/konnect/network-resiliency.md
  app/konnect/network.md
  app/konnect/upgrade-faq.md
Labels: review:general, skip-changelog

#5973 Konnect rename: Servicehub section
  app/konnect/servicehub/index.md
Labels: review:general, skip-changelog

#6006 Chore: Bump GW to version 3.1.1.5
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general, pending:release

#5974 Konnect Rename: Dev Portal section
  app/konnect/dev-portal/access-and-approval/azure.md
  app/konnect/dev-portal/access-and-approval/manage-app-connections.md
  app/konnect/dev-portal/applications/application-overview.md
  app/konnect/dev-portal/applications/dev-reg-app-service.md
  app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
  app/konnect/dev-portal/applications/dynamic-client-registration/azure.md
  app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
  app/konnect/dev-portal/applications/dynamic-client-registration/index.md
  app/konnect/dev-portal/applications/dynamic-client-registration/okta.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/dev-portal/customization/index.md
  app/konnect/dev-portal/customization/self-hosted-portal.md
  app/konnect/dev-portal/index.md
  app/konnect/dev-portal/troubleshoot/index.md
Labels: review:general, skip-changelog

#6023 Konnect rename: Renames the analytics section.
  app/konnect/analytics/index.md
  app/konnect/analytics/reference.md
  app/konnect/analytics/troubleshoot.md
  app/konnect/analytics/use-cases/latency.md
Labels: review:general, skip-changelog

#6009 feat(pre-built-reports): added changelog entry and an intro sentence
  app/konnect/index.md
  app/konnect/updates.md
Labels: review:copyedit, pending:release

#6025 Add summit hackaton banner
  app/_assets/entrypoints/application.js
  app/_assets/javascripts/promo-banner.js
  app/_assets/stylesheets/header.less
  app/_includes/nav-v2.html
Labels: review:general

#6028 (Fix) Cross-ref CP-DP communication through forward proxy in Konnect docs
  app/konnect/network.md
Labels: review:general

#5901 Add new konnect cta to docs
  app/_assets/entrypoints/application.js
  app/_assets/javascripts/app.js
  app/_assets/javascripts/modal.js
  app/_assets/stylesheets/index.less
  app/_assets/stylesheets/modal.less
  app/_assets/stylesheets/pages/docs.less
  app/_layouts/docs-v2.html
  app/_src/gateway/index.md
  app/_src/gateway/install/docker/index.md
  app/assets/images/icons/documentation/close.svg
  app/hub/index.html
Labels: review:tech

#6021 Add if_versions tags so windows support does not show up in KM v2.4
  app/_data/tables/features/mesh.yml
  app/_src/mesh/features/index.md
  app/_src/mesh/features/windows.md
  app/_src/mesh/gettingstarted.md
  app/_src/mesh/install.md
  app/_src/mesh/installation/windows.md
Labels: review:general, skip-changelog

#5998 fix: Docker installation for Kong Gateway OSS missing port for Kong Manager OSS
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_src/gateway/install/docker/index.md
  app/_src/gateway/kong-manager-oss/troubleshoot.md
Labels: review:copyedit

#6031 Fix banner styles
  app/_assets/stylesheets/header.less
Labels: review:general

#6032 Konnect rename: Administer section
  app/konnect/account-management/index.md
  app/konnect/org-management/system-accounts.md
  app/konnect/org-management/teams-and-roles/index.md
  app/konnect/org-management/teams-and-roles/manage.md
  app/konnect/org-management/teams-and-roles/roles-reference.md
  app/konnect/org-management/teams-and-roles/teams-reference.md
  app/konnect/org-management/users.md
Labels: review:general, skip-changelog

#6034 Update changelog.md
  app/gateway/changelog.md
Labels: review:general, skip-changelog

#5932 feat: Konnect Dev Portal RBAC documentation
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/dev-portal/access-and-approval/manage-teams.md
  app/konnect/updates.md
Labels: review:copyedit, pending:release

#6033 Fix menus on mobile
  app/_assets/javascripts/modal.js
  app/_assets/javascripts/navbar.js
Labels: review:general

#6042 Update index.md
  app/konnect/runtime-manager/composite-runtime-groups/index.md
Labels: review:copyedit

#6039 feat: Rename Konnect "runtimes" on the docs homepage
  app/_data/landing_page.yml
Labels: review:general

#6040 fix: Update OSS install instructions for Kong Manager
  app/_includes/md/gateway/setup.md
  app/_src/gateway/install/docker/index.md
Labels: review:general

#6046 Add info about how IP address is determined for IP Restriction plugin
  app/_hub/kong-inc/ip-restriction/_index.md
Labels: review:general

#6044 Updated RLA index page to share some details from RL plugin
  app/_hub/kong-inc/rate-limiting-advanced/_index.md
Labels: review:general

#6045 Added info about limiting by IP address
  app/_hub/kong-inc/rate-limiting/_index.md
Labels: review:general
