Repository Kong/docs.konghq.com, pull requests merged in 2024-03, with the labels that each got.

#7021 Delete app/assets/images/icons/hub/nonamesecurity_nonamesecurity-kong…
  app/assets/images/icons/hub/nonamesecurity_nonamesecurity-kongprevention.png
Labels: review:general, skip-changelog

#6900 fix(mesh): remove duplicated getting started page
  app/_data/docs_nav_mesh_2.6.x.yml
  app/_data/docs_nav_mesh_2.7.x.yml
Labels: review:tech

#7022 Feat: Convert navbar to dark theme
  app/_assets/stylesheets/docsearch.less
  app/_assets/stylesheets/header-v2.less
  app/_assets/stylesheets/hub-landing-page.less
  app/_assets/stylesheets/page-header.less
  app/_includes/nav-v2.html
  app/assets/images/logos/docslogo-dark-theme.svg
  app/assets/images/logos/konglogo-dark-theme.svg
Labels: review:tech

#6985 chore: add chart version and CRD info
  app/_includes/md/kic-crd-upgrades.md
  app/_src/kubernetes-ingress-controller/support-policy.md
  app/_src/kubernetes-ingress-controller/upgrade/kic.md
Labels: review:general, review:copyedit

#7028 fix: Add missing license behavior content from 3.5
  app/_src/gateway/licenses/index.md
Labels: review:general

#7031 Chore: Update Kong logo in footer
  app/_includes/footer.html
  app/assets/images/logos/konglogo-light-theme-primary.svg
Labels: review:general

#7026 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7029 fix: Updated HTTP method for setting targets health
  app/_src/gateway/how-kong-works/health-checks.md
Labels: review:general

#7036 Fix: rephrase 'sugar parameter' into more common terms
  app/_src/gateway/admin-api/admin-api-3.0.x.md
  app/_src/gateway/admin-api/admin-api-3.1.x.md
  app/_src/gateway/admin-api/index.md
  app/_src/gateway/how-kong-works/routing-traffic.md
  app/gateway/2.6.x/admin-api/index.md
  app/gateway/2.6.x/reference/proxy.md
  app/gateway/2.7.x/admin-api/index.md
  app/gateway/2.7.x/reference/proxy.md
  app/gateway/2.8.x/admin-api/index.md
  app/gateway/2.8.x/reference/proxy.md
Labels: review:copyedit

#7024 Fix: Enable Kong Manager in Docker command fix
  app/_src/gateway/kong-manager/enable.md
Labels: review:general, skip-changelog

#7040 kic: fix kongCredType leftover
  app/_src/kubernetes-ingress-controller/concepts/ingress.md
Labels: review:general

#7038 Fix: TCL/TCP typo
  app/_src/gateway/how-kong-works/routing-traffic.md
  app/gateway/2.6.x/reference/proxy.md
  app/gateway/2.7.x/reference/proxy.md
  app/gateway/2.8.x/reference/proxy.md
Labels: review:general

#7032 chore(*): remove references to Dev Portal and Vitals
  app/_hub/kong-inc/mocking/_metadata/_index.yml
  app/_hub/kong-inc/oauth2/how-to/_oauth2rla.md
  app/_hub/kong-inc/openid-connect/how-to/third-party/_cognito.md
  app/_src/gateway/install/kubernetes/proxy.md
  app/_src/gateway/kong-manager/configuring-to-send-email.md
  app/_src/gateway/kong-manager/index.md
  app/_src/gateway/kong-manager/workspaces.md
  app/_src/gateway/licenses/index.md
  app/_src/gateway/production/networking/dns-considerations.md
  app/_src/gateway/production/sizing-guidelines.md
Labels: review:copyedit

#7043 Explain --dump-config gives access via diagnostic server
  app/_src/kubernetes-ingress-controller/reference/troubleshooting.md
Labels: review:general

#7046 Release: Gateway 3.6.1.1
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#7045 fix: decK file merge example
  app/_src/deck/reference/deck_file_merge.md
Labels: review:general, ci:manual-approve:generated-files

#6834 feat: Added download button to documents UI in Konnect
  app/konnect/updates.md
Labels: review:general, skip-changelog

#7023 Automated OAS Update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
  api-specs/Konnect/v0/yaml/ksearch.yaml
  api-specs/Konnect/v2/yaml/analytics-requests.yaml
  api-specs/Konnect/v2/yaml/api-products.yaml
  api-specs/Konnect/v2/yaml/portal-management.yaml
  api-specs/Konnect/v3/yaml/identity.yaml
Labels: review:general

#7047 Update: Add note about Google ACME and DNS requirement
  app/konnect/dev-portal/customization/index.md
Labels: review:general

#7037 Update: Kong Gateway overview diagram
  app/_src/gateway/index.md
  app/assets/images/products/gateway/kong-gateway-features.png
Labels: review:general

#7050 Fix: Removes Proxy and test a service doc
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/api-products/index.md
  app/konnect/gateway-manager/deploy-service.md
Labels: review:general, skip-changelog

#7051 Chore: Update the 'No support available' plugins category and language
  app/_hub/TheLEGOGroup/aws-request-signing/_metadata/_index.yml
  app/_hub/amberflo/kong-plugin-amberflo/_metadata/_index.yml
  app/_hub/appsentinels/appsentinels/_metadata/_index.yml
  app/_hub/datadome/kong-plugin-datadome/_metadata/_index.yml
  app/_hub/imperva/imp-appsec-connector/_metadata/_index.yml
  app/_hub/moesif/kong-plugin-moesif/_metadata/_index.yml
  app/_hub/nonamesecurity/nonamesecurity-kongtrafficsource/_metadata/_index.yml
  app/_hub/okta/okta/_metadata/_index.yml
  app/_hub/optum/kong-response-size-limiting/_metadata/_index.yml
  app/_hub/optum/kong-service-virtualization/_metadata/_index.yml
  app/_hub/optum/kong-spec-expose/_metadata/_index.yml
  app/_hub/optum/kong-splunk-log/_metadata/_index.yml
  app/_hub/optum/kong-upstream-jwt/_metadata/_index.yml
  app/_hub/salt/salt/_metadata/_index.yml
  app/_hub/wallarm/wallarm/_metadata/_index.yml
  app/_includes/md/about-plugins.md
  app/_layouts/extension.html
  app/hub/index.html
  docs/templates/partner-plugin-template/_metadata.yml
  jekyll-dev.yml
  jekyll.yml
Labels: review:general

#7020 docs(traceableai) - Initial docs for traceable.ai plugin
  app/_hub/traceableai/traceableai/_metadata.yml
  app/_hub/traceableai/traceableai/examples/_index.yml
  app/_hub/traceableai/traceableai/overview/_index.md
  app/_hub/traceableai/traceableai/schemas/_index.json
  app/assets/images/icons/hub/traceableai_traceableai.png
Labels: review:copyedit

#7052 chore: Adjust landing page card styling
  app/_assets/stylesheets/pages/landing-page.less
  app/_layouts/landing-page.html
  app/assets/images/icons/icn-script2.svg
Labels: review:tech

#7054 fix: Metadata file for traceable plugin
  app/_hub/traceableai/traceableai/_metadata/_index.yml
Labels: review:general, skip-changelog

#7053 Update default-ports.md
  app/_src/gateway/production/networking/default-ports.md
Labels: review:tech

#7035 fix: Konnect Get Started Guide fast follows
  app/konnect/getting-started/add-api.md
  app/konnect/getting-started/import.md
  app/konnect/getting-started/index.md
  app/konnect/index.md
Labels: review:copyedit

#7034 Fix: Plugin name and instance_name descriptions
  api-specs/Gateway-EE/latest/kong-ee.yaml
  api-specs/Gateway-OSS/latest/kong-oss.yaml
  app/_includes/plugins/hub-examples/consumer.html
  app/_includes/plugins/hub-examples/consumer_groups.html
  app/_includes/plugins/hub-examples/global.html
  app/_includes/plugins/hub-examples/route.html
  app/_includes/plugins/hub-examples/service.html
  app/_includes/plugins/schema.html
Labels: review:copyedit

#7049 Adds --populate-env-vars to deck file render command reference
  app/_src/deck/reference/deck_file_render.md
Labels: review:general

#6333 Update: Add major version to PDK version num example
  app/_src/gateway/plugin-development/pdk/index.md
Labels: do not merge, review:general, ci:prevent-merge:generated-files

#7058 docs(gateway): adjust references to `ulimit -n`.
  app/_src/gateway/breaking-changes/36x.md
  app/gateway/changelog.md
Labels: review:copyedit

#7059 Feat: Topology diagrams for gateway docs
  app/_includes/md/gateway/deployment-topologies.md
  app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
  app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md
  app/_src/gateway/production/deployment-topologies/index.md
  app/_src/gateway/production/deployment-topologies/traditional/index.md
Labels: review:general

#7064 Fix: Update `get-admins` endpoint description
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
  app/_src/gateway/admin-api/admins/reference.md
Labels: review:copyedit

#7062 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7066 Fix: Typo in generate changelog GHA
  .github/workflows/generate-changelog.yml
Labels: review:general

#7065 Chore: Productize a service API instructions
  app/konnect/api-products/productize-service.md
Labels: review:copyedit, skip-changelog

#7071 Sync Konnect OAS Data
  app/_data/konnect_oas_data.json
Labels: review:general, skip-changelog

#7069 Chore: Remove developer portal access guide
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/dev-portal/access.md
  app/konnect/dev-portal/dev-reg.md
  app/konnect/dev-portal/index.md
  app/konnect/geo.md
Labels: review:general, skip-changelog

#7073 fix if blocks for license part in KGO
  app/_includes/md/kgo/prerequisites-kic.md
  app/_src/gateway-operator/get-started/kic/install.md
Labels: review:tech, review:general

#7074 Automated OAS Update
  api-specs/Konnect/v2/yaml/portal-management.yaml
Labels: review:general, skip-changelog

#7075 Automated OAS Update
  api-specs/Konnect/v2/yaml/portal-management.yaml
Labels: review:general, skip-changelog

#7044 KGO managed gateways
  app/_data/docs_nav_kgo_1.2.x.yml
  app/_src/gateway-operator/concepts/gateway-configuration.md
  app/_src/gateway-operator/concepts/managed-gateways.md
  app/_src/gateway-operator/customization/data-plane-image.md
  app/_src/gateway-operator/get-started/kic/create-gateway.md
  app/_src/gateway-operator/get-started/kic/create-route.md
  app/_src/gateway-operator/get-started/kic/install.md
  app/_src/gateway-operator/get-started/konnect/create-route.md
  app/_src/gateway-operator/guides/upgrade/data-plane/rolling.md
Labels: review:general

#7080 Fixes plugin install directions for Dockerfile entrypoint
  app/_src/gateway/plugin-development/distribution.md
Labels: review:general

#7078 KGO: AIGateway docs
  app/_data/docs_nav_kgo_1.2.x.yml
  app/_includes/md/kgo/prerequisites-kic.md
  app/_includes/snippets/gateway-operator/install_with_helm.md
  app/_plugins/hooks/products_renderer.rb
  app/_src/gateway-operator/guides/ai-gateway.md
  app/assets/gateway-operator/ai-gateway-crd.yaml
  spec/app/_plugins/generators/hooks/products_renderer_spec.rb
Labels: review:general

#7094 Fix Gateway > 3.1 docker install instructions
  app/_src/gateway/install/docker/build-custom-images.md
Labels: review:general

#7092 Feat: Cloud Gateways network and peering information
  app/konnect/network-resiliency.md
Labels: review:copyedit

#7089 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7100 Release KGO 1.2
  app/_data/docs_nav_kgo_1.3.x.yml
  app/_data/kong_versions.yml
  app/_includes/md/kgo/prerequisites-kic.md
  app/_includes/snippets/gateway-operator/install_with_helm.md
Labels: review:general

#7102 add changelogs for KGO 1.2
  app/gateway-operator/changelog.md
Labels: review:general

#7106 kgo: fix Prometheus query in the guide which intermittently produced 0s which caused the targeted workload to scale down to 0
  app/_src/gateway-operator/guides/autoscaling-workloads/prometheus.md
Labels: review:general

#7114 Automated OAS Update
  api-specs/Konnect/v2/yaml/control-planes.yaml
Labels: review:general

#7076 Release: Gateway 3.4.3.5
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_data/kong_versions.yml
  app/_data/tables/breaking_changes_lts.yml
  app/_src/gateway/breaking-changes/34x.md
  app/_src/gateway/key-concepts/routes/expressions.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/azure-key-vaults.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/index.md
  app/_src/gateway/plugin-development/custom-logic.md
  app/_src/gateway/reference/configuration/configuration-3.0-3.3.md
  app/_src/gateway/reference/configuration/configuration-3.4.x.md
  app/_src/gateway/reference/configuration/configuration-3.5.x.md
  app/_src/gateway/reference/configuration/configuration-3.6.x.md
  app/_src/gateway/reference/expressions-language/language-references.md
  app/gateway/changelog.md
  autodoc-conf-ee/run.lua
Labels: review:general, ci:manual-approve:link-validation, ci:manual-approve:generated-files

#7108 kgo: use helm as installation method
  app/_includes/md/kgo/prerequisites.md
  app/_includes/snippets/gateway-operator/install_with_kubectl.md
  app/_src/gateway-operator/get-started/kic/install.md
  app/_src/gateway-operator/get-started/konnect/install.md
  app/_src/gateway-operator/guides/ai-gateway.md
  app/_src/gateway-operator/guides/autoscaling-workloads/overview.md
  app/_src/gateway-operator/install.md
Labels: Kubernetes Team, review:general

#7112 kgo: update version compat table for 1.2
  app/_data/kong_versions.yml
  app/_src/gateway-operator/reference/version-compatibility.md
Labels: Kubernetes Team, review:general

#7018 Feature: UI support for DP Error Notifications
  app/assets/images/products/konnect/changelog/konnect-error-log.png
  app/konnect/updates.md
Labels: review:general, pending:release, skip-changelog

#7115 Fix: Generate 3.6 Gateway kong.conf reference
  app/_src/gateway/reference/configuration/configuration-3.6.x.md
  autodoc-conf-ee/data.lua
  autodoc-conf-ee/run.lua
Labels: review:general, ci:check-skipped:generated-files, ci:manual-approve:generated-files

#7122 (fix) Update auth0 instructions to include warning on trailing forward slash in URL
  app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
Labels: review:general

#7121 Fix broken links
  app/_includes/md/2.6.x/ldap/ldap-service-directory-mapping.md
  app/_includes/md/2.7.x/ldap/ldap-service-directory-mapping.md
  app/_includes/md/2.8.x/ldap/ldap-service-directory-mapping.md
  app/_includes/md/gateway/ldap-service-directory-mapping.md
  tools/broken-link-checker/config/ignored_targets.json
Labels: review:general

#7077 Update: add latencies.receive to file-log JSON property docs
  app/_includes/md/plugins-hub/json-object-log.md
Labels: review:general, review:copyedit

#7098 Update: Document custom annotations for decK APIOps
  app/_src/deck/guides/apiops.md
Labels: review:general, review:sme

#7125 Automated OAS Update
  api-specs/Konnect/v2/yaml/portal-management.yaml
Labels: review:tech, skip-changelog

#7133 docs(*): fix docs related to Kong Gateway Tracing
  app/_src/gateway/production/tracing/api.md
Labels: review:general, review:copyedit

#7136 Release: Gateway 2.8.4.8
  app/_data/kong_versions.yml
  app/gateway/2.8.x/reference/configuration.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation, ci:manual-approve:generated-files

#7143 style(gateway/expressions-language): fix incorrect formatting
  app/_src/gateway/reference/expressions-language/index.md
Labels: review:general

#7142 docs(3.4.3.5): add missing version bump of kong-lua-resty-kafka
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#7117 chore: Clarify our use of SemVer with Kong Gateway
  .github/styles/kong/dictionary.txt
  app/_includes/md/availability-stages.md
  app/_src/gateway/index.md
  app/_src/gateway/support-policy.md
  app/_src/gateway/support/index.md
  app/_src/gateway/upgrade-v2.md
  app/_src/gateway/upgrade-v3.md
  app/_src/gateway/upgrade/index.md
  app/gateway/2.6.x/index.md
  app/gateway/2.6.x/install-and-run/upgrade-enterprise.md
  app/gateway/2.6.x/install-and-run/upgrade-oss.md
  app/gateway/2.7.x/index.md
  app/gateway/2.7.x/install-and-run/upgrade-enterprise.md
  app/gateway/2.7.x/install-and-run/upgrade-oss.md
  app/gateway/2.8.x/index.md
  app/gateway/2.8.x/install-and-run/upgrade-enterprise.md
  app/gateway/2.8.x/install-and-run/upgrade-oss.md
  app/gateway/2.8.x/support-policy.md
Labels: review:copyedit

#7118 Feat: UX improvements to Control Plane Groups
  app/konnect/updates.md
Labels: review:general, pending:release, skip-changelog
