Repository Kong/docs.konghq.com, pull requests merged in 2024-12, with the labels that each got.

#8154 feat: Service Catalog Datadog integration
  app/_data/docs_nav_konnect.yml
  app/_data/tables/konnect/integrations.yml
  app/konnect/service-catalog/integrations/datadog.md
Labels: review:sme

#8199 chore(kgo): bump to CRD docs 1.4.1
  app/_src/gateway-operator/reference/custom-resources/1.4.x.md
Labels: team-k8s, review:general

#8190 Fix: missing changelog entry for dependency bump
  app/gateway/changelog.md
Labels: review:copyedit

#8208 chore(kic): update version compat matrix
  app/_src/kubernetes-ingress-controller/reference/version-compatibility.md
Labels: team-k8s, review:general

#8180 Fix: use prereq styling for KIC and KGO
  app/_assets/stylesheets/collapsible-sections.less
  app/_includes/md/kgo/prerequisites.md
  app/_includes/md/kic/prerequisites.md
Labels: review:general

#8205 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7471 Feat: Ubuntu 24.04 (Noble Numbat)
  app/_data/tables/os_support.yml
  app/_data/tables/support/gateway/versions/39.yml
  app/_src/gateway/install/linux/ubuntu.md
Labels: review:general

#8209 Fix: KGO prereq styling
  app/_includes/md/kgo/konnect-entities-prerequisites.md
Labels: review:general

#8188 Fix: remove upgrade paths table
  app/_includes/md/gateway/upgrade-paths.md
  app/_src/gateway/upgrade/index.md
Labels: review:general, ci:manual-approve:link-validation

#8212 chore: Generate 3.9 config ref
  app/_data/docs_nav_gateway_3.9.x.yml
  app/_src/gateway/reference/configuration/configuration-3.9.x.md
Labels: review:general, ci:prevent-merge:generated-files, skip-changelog

#8210 chore: Update 3.9 support tables
  app/_data/tables/support/gateway/packages.yml
  app/_src/gateway/support/index.md
  app/_src/gateway/support/third-party.md
Labels: review:general

#8211 Feat: RHEL UBI 9 support
  app/_data/tables/install_options.yml
  app/_src/gateway/install/docker/build-custom-images.md
Labels: review:general

#8184 Update: Guardrail for Bedrock
  app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md
  app/_hub/kong-inc/ai-proxy/overview/_index.md
Labels: review:general

#8214 Header Cert Auth plugin: cert format FAQ
  app/_hub/kong-inc/header-cert-auth/overview/_index.md
Labels: review:general

#8222 Revert #8183
  app/_hub/kong-inc/ai-rate-limiting-advanced/how-to/_index.md
Labels: review:general

#8224 fix(mesh): add lost SBOM sections in 2.9 and 2.10
  app/_data/docs_nav_mesh_2.10.x.yml
  app/_data/docs_nav_mesh_2.9.x.yml
Labels: review:general

#8223 fix(mesh): remove Beta from MeshOPA sidebar
  app/_data/docs_nav_mesh_2.10.x.yml
  app/_data/docs_nav_mesh_2.8.x.yml
  app/_data/docs_nav_mesh_2.9.x.yml
Labels: review:general

#8228 Update opentelemetry _changelog.md to include deprecation of config.endpoint in 3.8
  app/_hub/kong-inc/opentelemetry/_changelog.md
Labels: review:general

#8128 Update config-store.md for referencing the secret in Konnect
  app/konnect/gateway-manager/configuration/config-store.md
Labels: review:general

#8153 kic: update Custom Entities guide for GA in 3.4
  app/_src/kubernetes-ingress-controller/guides/services/custom-entity.md
  app/_src/kubernetes-ingress-controller/reference/feature-gates.md
Labels: team-k8s, review:general

#8158 Chore: 3.9 api specs prep
  api-specs/Gateway-EE/3.8/kong-ee.yaml
  api-specs/Gateway-EE/3.9/kong-ee.yaml
  api-specs/Gateway-OSS/3.8/kong-oss.yaml
  api-specs/Gateway-OSS/3.9/kong-oss.yaml
Labels: review:general

#8231 Chore: update public keys
  app/_data/installation/gateway.yml
Labels: review:general

#8218 Feat: Redirect plugin
  app/_hub/kong-inc/redirect/_changelog.md
  app/_hub/kong-inc/redirect/_metadata/_index.yml
  app/_hub/kong-inc/redirect/overview/_index.md
  app/_hub/kong-inc/redirect/versions.yml
  app/assets/images/icons/hub/kong-inc_redirect.png
Labels: review:sme

#8182 Feat: Add Hugging Face as LLM provider
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_huggingface.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_openai.md
  app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_huggingface.md
  app/_hub/kong-inc/ai-proxy/overview/_index.md
  app/_includes/md/plugins-hub/ai-providers-prereqs-advanced.md
  app/_includes/md/plugins-hub/ai-providers-prereqs.md
Labels: review:copyedit, review:sme

#8213 feat: serverless custom domains docs
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/dev-portal/customization/custom-dns.md
  app/konnect/dev-portal/customization/index.md
  app/konnect/gateway-manager/dedicated-cloud-gateways/custom-dns.md
  app/konnect/gateway-manager/dedicated-cloud-gateways/index.md
  app/konnect/gateway-manager/serverless-gateways/custom-dns.md
  app/konnect/gateway-manager/serverless-gateways/index.md
Labels: do not merge, review:general, review:copyedit, area/docs

#7785 Inigo plugin initial docs
  .github/styles/kong/dictionary.txt
  app/_hub/inigo/inigo/_changelog.md
  app/_hub/inigo/inigo/_metadata/_index.yml
  app/_hub/inigo/inigo/overview/_index.md
  app/_hub/inigo/inigo/schemas/_index.json
  app/assets/images/icons/hub/inigo_inigo.png
Labels: review:copyedit

#8240 Automated Konnect changelog update [skip-ci]
  app/konnect/updates.md
Labels: review:general, skip-changelog

#8229 chore: Remove deprecated APIs
  api-specs/Konnect/v2/yaml/portal-api.yaml
  api-specs/Konnect/v2/yaml/portal-rbac.yaml
  app/_api/konnect/portal/_index.md
  app/_api/konnect/runtime-groups-configuration/_index.md
  app/_api/konnect/runtime-groups/_index.md
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_oas_data.json
  app/_layouts/oas/index.html
  app/_redirects
  app/konnect/dev-portal/customization/index.md
  app/konnect/dev-portal/customization/netlify.md
  app/konnect/dev-portal/customization/self-hosted-portal.md
  app/konnect/updates.md
Labels: review:general

#8237 Update performance-testing.md for 3.9 rc4
  app/_src/gateway/production/performance/performance-testing.md
Labels: review:general

#8236 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8152 feat: Service Protection plugin
  app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md
  app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
  app/_hub/kong-inc/rate-limiting/overview/_index.md
  app/_hub/kong-inc/service-protection/_changelog.md
  app/_hub/kong-inc/service-protection/_metadata/_index.yml
  app/_hub/kong-inc/service-protection/how-to/_index.md
  app/_hub/kong-inc/service-protection/overview/_index.md
  app/_hub/kong-inc/service-protection/versions.yml
  app/_includes/md/plugins-hub/rl-table.md
  app/assets/images/icons/hub/kong-inc_service-protection.png
Labels: review:sme

#8245 Fix: Add missing vault config link
  app/konnect/gateway-manager/configuration/vaults/how-to.md
Labels: review:general

#8251 Update ingress.md
  app/_src/kubernetes-ingress-controller/concepts/ingress.md
Labels: team-k8s, review:general, review:copyedit

#8177 feat: Injection Protection plugin for 3.9
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/injection-protection/_changelog.md
  app/_hub/kong-inc/injection-protection/_metadata/_index.yml
  app/_hub/kong-inc/injection-protection/overview/_index.md
  app/_hub/kong-inc/injection-protection/versions.yml
  app/assets/images/icons/hub/kong-inc_injection-protection.png
Labels: review:sme

#8118 feat: Dev Portal SAML SSO
  app/_data/docs_nav_konnect.yml
  app/_includes/md/konnect/generic-sso.md
  app/_includes/md/konnect/okta-sso.md
  app/konnect/dev-portal/access-and-approval/okta-idp.md
  app/konnect/dev-portal/access-and-approval/sso.md
  app/konnect/org-management/okta-idp.md
  app/konnect/org-management/sso.md
  app/konnect/reference/saml-idp-mappings.md
Labels: review:sme

#8254 Fix: Consumer groups compatible plugins list
  app/_src/gateway/kong-enterprise/consumer-groups/index.md
Labels: review:copyedit

#8255 Fix: Add schema for event hooks
  api-specs/Gateway-EE/3.9/kong-ee.yaml
Labels: review:general, skip-changelog

#8252 Sync Konnect OAS Data
  app/_data/konnect_oas_data.json
Labels: review:general, skip-changelog

#8244 Release: Gateway 3.9
  app/_data/docs_nav_gateway_3.10.x.yml
  app/_data/kong_versions.yml
Labels: review:general

#8243 chore: Changelog for Gateway 3.9
  app/_data/docs_nav_gateway_3.9.x.yml
  app/_hub/kong-inc/ai-prompt-guard/_changelog.md
  app/_hub/kong-inc/ai-proxy-advanced/_changelog.md
  app/_hub/kong-inc/ai-proxy/_changelog.md
  app/_hub/kong-inc/ai-rate-limiting-advanced/_changelog.md
  app/_hub/kong-inc/ai-request-transformer/_changelog.md
  app/_hub/kong-inc/ai-response-transformer/_changelog.md
  app/_hub/kong-inc/ai-semantic-cache/_changelog.md
  app/_hub/kong-inc/ai-semantic-prompt-guard/_changelog.md
  app/_hub/kong-inc/app-dynamics/changelog.md
  app/_hub/kong-inc/aws-lambda/_changelog.md
  app/_hub/kong-inc/correlation-id/_changelog.md
  app/_hub/kong-inc/degraphql/_changelog.md
  app/_hub/kong-inc/exit-transformer/_changelog.md
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_changelog.md
  app/_hub/kong-inc/json-threat-protection/_changelog.md
  app/_hub/kong-inc/jwe-decrypt/_changelog.md
  app/_hub/kong-inc/jwt-signer/_changelog.md
  app/_hub/kong-inc/jwt/_changelog.md
  app/_hub/kong-inc/kafka-log/_changelog.md
  app/_hub/kong-inc/key-auth/_changelog.md
  app/_hub/kong-inc/loggly/_changelog.md
  app/_hub/kong-inc/oas-validation/_changelog.md
  app/_hub/kong-inc/openid-connect/_changelog.md
  app/_hub/kong-inc/prometheus/_changelog.md
  app/_hub/kong-inc/rate-limiting-advanced/_changelog.md
  app/_hub/kong-inc/rate-limiting/_changelog.md
  app/_hub/kong-inc/request-validator/_changelog.md
  app/_src/gateway/breaking-changes/39x.md
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#8248 Chore: Update konnect compatibility for 3.9
  app/konnect/compatibility.md
Labels: review:general, skip-changelog

#8258 Fix: adjust datakit doc to clear jekyll warning
  app/_src/gateway/kong-enterprise/datakit/configuration.md
Labels: review:general, skip-changelog

#8169 feat: Konnect IN geo
  app/_src/deck/guides/konnect.md
  app/konnect/geo.md
  app/konnect/network.md
Labels: review:general

#8260 feat(sdk): automated oas update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
Labels: review:general

#8261 Update performance-testing.md for 3.9 rc5
  app/_src/gateway/production/performance/performance-testing.md
Labels: review:general

#8259 kic: drop 'beta' from feature gates toc heading
  app/_data/docs_nav_kic_3.0.x.yml
  app/_data/docs_nav_kic_3.1.x.yml
  app/_data/docs_nav_kic_3.2.x.yml
  app/_data/docs_nav_kic_3.3.x.yml
  app/_data/docs_nav_kic_3.4.x.yml
  app/_src/kubernetes-ingress-controller/reference/feature-gates.md
Labels: team-k8s, review:general

#8247 kic: add /debug/config/raw-error mention for KIC 3.4+
  app/_src/kubernetes-ingress-controller/reference/troubleshooting.md
Labels: team-k8s, review:general

#8138 docs(kic): fix ingress to gateway migration plugins conversion
  app/_src/kubernetes-ingress-controller/reference/ingress-to-gateway-migration.md
Labels: review:general

#8178 Fix: Inaccurate OS support for AppD C SDK agent
  app/_hub/kong-inc/app-dynamics/overview/_index.md
Labels: review:copyedit

#8262 Fix: clarify license propagation in Konnect
  app/konnect/account-management/index.md
  app/konnect/gateway-manager/kic.md
Labels: review:copyedit

#8257 Fix: Consumer groups docs
  app/_data/docs_nav_konnect.yml
  app/_src/gateway/kong-enterprise/consumer-groups/index.md
  app/_src/gateway/kong-manager/consumer-groups.md
  app/konnect/api/index.md
  app/konnect/dev-portal/access-and-approval/manage-teams.md
  app/konnect/gateway-manager/configuration/consumer-groups.md
  app/konnect/gateway-manager/declarative-config.md
  app/konnect/org-management/access-tokens.md
Labels: review:copyedit

#8246 kic: add events section to custom entities guide
  .github/styles/kong/dictionary.txt
  app/_src/kubernetes-ingress-controller/guides/services/custom-entity.md
Labels: team-k8s, review:general

#7551 update gateway part in splitting traffic page
  app/_includes/md/kic/http-test-routing-resource.md
  app/_src/kubernetes-ingress-controller/guides/custom-class/internal-external.md
Labels: team-k8s, review:general

#8269 Fix: Prometheus AI metrics
  app/_hub/kong-inc/prometheus/overview/_index.md
Labels: review:general

#8264 Fix: Clean out "unreleased" links
  app/_hub/kong-inc/graphql-proxy-cache-advanced/_changelog.md
  app/_src/gateway-operator/guides/konnect-entities/faq.md
  app/_src/kubernetes-ingress-controller/plugins/custom.md
  app/gateway/changelog.md
Labels: review:general

#8233 feat(Deck): add feature online plugins filter flag
  app/_src/deck/reference/deck_gateway_validate.md
Labels: review:copyedit, ci:prevent-merge:generated-files

#8273 Release: Deck 1.4.1 and 1.4.2
  app/_data/docs_nav_deck_1.42.x.yml
  app/_data/docs_nav_deck_1.43.x.yml
  app/_data/kong_versions.yml
  app/_src/deck/reference/deck_file_kong2tf.md
Labels: review:general

#8277 kic: minor fixes in ACL guide
  app/_includes/md/kic/http-test-routing-resource.md
  app/_src/kubernetes-ingress-controller/plugins/acl.md
Labels: team-k8s, review:general

#8283 kgo: add UPGRADE.md in upgrade guide
  app/_src/gateway-operator/production/upgrade/gateway-operator.md
Labels: team-k8s, review:general

#8274 Release: Gateway 3.4.3.14
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#8271 Update changelog.md
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#8268 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8288 chore: Dynatrace tile
  app/_hub/dynatrace/dynatrace/_metadata/_index.yml
  app/_hub/dynatrace/dynatrace/overview/_index.md
  app/_hub/dynatrace/dynatrace/schemas/_index.json
  app/_hub/kong-inc/opentelemetry/how-to/_dynatrace.md
  app/_includes/md/plugins-hub/dynatrace.md
  app/assets/images/icons/hub/dynatrace_dynatrace.png
Labels: review:general

#8289 Fix: dynatrace tile category
  app/_hub/dynatrace/dynatrace/_metadata/_index.yml
  app/_includes/md/plugins-hub/dynatrace.md
  app/_layouts/extension.html
Labels: review:general, skip-changelog

#8281 kic: add secret credential labels upon creation
  app/_src/kubernetes-ingress-controller/plugins/acl.md
Labels: team-k8s, review:general

#8285 fix: AI Gateway metrics info
  app/_hub/kong-inc/prometheus/overview/_index.md
  app/_src/gateway/ai-gateway/index.md
Labels: review:sme

#8201 docs(kic): add upstream TLS verification guide
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_kic_3.4.x.yml
  app/_includes/md/kic/ca-certificates-note.md
  app/_includes/md/kic/http-test-routing-resource.md
  app/_includes/md/kic/prerequisites.md
  app/_includes/md/kic/verify-upstream-tls-backendtlspolicy.md
  app/_includes/md/kic/verify-upstream-tls-ca.md
  app/_src/kubernetes-ingress-controller/guides/security/verify-upstream-tls.md
  app/_src/kubernetes-ingress-controller/plugins/mtls.md
  app/_src/kubernetes-ingress-controller/reference/annotations.md
Labels: team-k8s, review:general, area/docs

#8293 feat(sdk): automated oas update
  api-specs/portal.yaml
Labels: review:general

#8241 Feat: Jump to explorer
  app/assets/images/products/konnect/analytics/custom-reports/api-usage-by-application.png
  app/assets/images/products/konnect/analytics/custom-reports/kong-vs-upstream-latency.png
  app/assets/images/products/konnect/analytics/custom-reports/latency-payments-api-30.png
  app/assets/images/products/konnect/analytics/custom-reports/total-api-requests.png
  app/assets/images/products/konnect/analytics/custom-reports/total-usage-accounts-api-30.png
  app/assets/images/products/konnect/analytics/konnect-analytics-api-requests.png
  app/assets/images/products/konnect/analytics/konnect-api-usage-summary.png
  app/assets/images/products/konnect/analytics/konnect-explorer-dashboard.png
  app/assets/images/products/konnect/analytics/konnect-summary-dashboard.png
  app/konnect/analytics/dashboard.md
  app/konnect/analytics/explorer.md
  app/konnect/analytics/index.md
  app/konnect/analytics/use-cases.md
Labels: do not merge, review:general

#8270 KIC: feat: add introduction about combined service from different httproutes
  app/_data/docs_nav_kic_3.4.x.yml
  app/_src/kubernetes-ingress-controller/reference/combined-services-from-different-httproutes.md
  app/_src/kubernetes-ingress-controller/reference/feature-gates.md
Labels: team-k8s, review:general

#8299 feat(sdk): automated oas update
  api-specs/portal.yaml
Labels: review:general

#8290 fix the status code in the 1st Demonstration
  app/_hub/kong-inc/exit-transformer/overview/_index.md
Labels: review:general

#8301 feat: add compatibility updates for Gateway 3.9 release
  app/_data/tables/version_errors_konnect.yml
Labels: do not merge, review:general

#8286 fix: Add example Injection Protection plugin log
  app/_hub/kong-inc/injection-protection/overview/_index.md
Labels: review:general

#8306 kgo: do not require `serverHostname` for KonnectExtension for KGO >=1.5.x
  app/_src/gateway-operator/get-started/konnect/deploy-data-plane.md
Labels: team-k8s, review:general

#8302 feat: Public labels search syntax for Dev Portal
  app/konnect/reference/search.md
Labels: review:general

#8297 kic: add update guide for gateway API 1.2
  app/_src/kubernetes-ingress-controller/upgrade/kic.md
Labels: team-k8s, review:general

#8287 docs(kic): provide correct field name from helm chart values.yaml
  app/_src/gateway-operator/get-started/kic/create-gateway.md
Labels: review:general
