Repository Kong/docs.konghq.com, pull requests merged in 2024-08, with the labels that each got.

#7711 feat(sdk): automated oas update
  api-specs/Konnect/v2/yaml/analytics-requests.yaml
Labels: review:general

#7712 Sync Konnect OAS Data
  app/_data/konnect_oas_data.json
Labels: review:general, skip-changelog

#7710 Fix: API Docs need update to reflect the current API response format
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
Labels: review:general, skip-changelog

#7686 kgo: make Gateway API APIVersion, depend on KGO version
  app/_plugins/blocks/kgo_podtemplatespec_example.rb
  app/_src/gateway-operator/customization/data-plane-image.md
  app/_src/gateway-operator/get-started/kic/create-gateway.md
  app/_src/gateway-operator/get-started/kic/create-route.md
  app/_src/gateway-operator/guides/ai-gateway.md
  app/_src/gateway-operator/guides/autoscaling-workloads/overview.md
  app/_src/gateway-operator/topologies/dbless.md
Labels: Kubernetes Team, review:general

#7722 Fix: Typos in Gateway get started
  app/_src/gateway/get-started/index.md
  app/_src/gateway/get-started/key-authentication.md
  app/_src/gateway/get-started/rate-limiting.md
  app/_src/gateway/get-started/services-and-routes.md
Labels: review:general, skip-changelog

#7718 docs(mesh): document caCert for cert-manager
  app/_src/mesh/features/cert-manager.md
Labels: review:general

#7725 Fix: key-auth-enc plugin request must use key_id
  app/_hub/kong-inc/key-auth-enc/overview/_index.md
Labels: review:general, skip-changelog

#7481 Feat: Saml Login support in Konnect
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/org-management/auth.md
  app/konnect/org-management/oidc-idp.md
  app/konnect/org-management/okta-idp.md
  app/konnect/org-management/sso.md
  app/konnect/org-management/teams-and-roles/manage.md
  app/konnect/org-management/users.md
  app/konnect/updates.md
Labels: review:copyedit, review:sme

#7733 Update changelog for SAML release
  app/konnect/updates.md
Labels: review:general, skip-changelog

#7734 fix: troubleshooting -> reference saml doc
  app/konnect/org-management/sso.md
Labels: review:general, skip-changelog

#7730 feat(sdk): automated oas update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
Labels: review:general

#7735 Fix: decK select tag examples
  app/_src/deck/guides/multi-file-state.md
Labels: review:general

#7728 chore: add more explanations about aws secret with slash in kong gateway
  app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
Labels: review:tech, review:general

#7737 Update key-auth request behaviour matrix
  app/_hub/kong-inc/key-auth/overview/_index.md
Labels: review:general

#7727 Release: Gateway 3.4.3.12
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7736 feat(sdk): automated oas update
  api-specs/Konnect/v3/yaml/identity.yaml
Labels: review:general

#7742 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7743 chore: Banner for summit hackathon
  app/_assets/entrypoints/application.js
  app/_assets/javascripts/promo-banner.js
  app/_assets/stylesheets/header.less
  app/_includes/nav-v2.html
Labels: review:general, skip-changelog

#7748 Fix: Remove mention of free
  app/konnect/dev-portal/index.md
Labels: review:general, skip-changelog

#7749 Update: Add image of developer dashboard
  app/assets/images/products/konnect/dev-portal/konnect-developer-analytics.png
  app/konnect/dev-portal/index.md
Labels: review:general, skip-changelog

#7750 Update _templates.md
  app/_hub/kong-inc/request-transformer-advanced/how-to/_templates.md
Labels: review:general

#7755 Fix: Control planes can be deleted.
  app/konnect/gateway-manager/index.md
  app/konnect/updates.md
Labels: review:general, skip-changelog

#7638 feat: Misc Dev Portal updates from previous feedback
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/dev-portal/access-and-approval/auto-approve-devs-apps.md
  app/konnect/dev-portal/access-and-approval/manage-app-connections.md
  app/konnect/dev-portal/access-and-approval/manage-app-reg-requests.md
  app/konnect/dev-portal/applications/application-overview.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/dev-portal/configuration-prep.md
  app/konnect/dev-portal/create-dev-portal.md
  app/konnect/dev-portal/index.md
Labels: review:copyedit, review:sme

#7766 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7768 Fix a few broken links
  app/_redirects
  app/contributing/user-interfaces.md
  tools/broken-link-checker/config/ignored_targets.json
Labels: review:general, skip-changelog

#7767 fix: Document Request ID in debugging, tracing, and logging
  app/_src/gateway/production/debug-request.md
  app/_src/gateway/production/logging/log-reference.md
  app/_src/gateway/production/tracing/index.md
Labels: review:general

#7763 Fix: Health Check Probes
  app/_src/gateway/production/monitoring/healthcheck-probes.md
Labels: review:general

#7745 Fix: Clarify workspace instead of environment for Dynamic Plugin Ordering feature
  app/_src/gateway/kong-enterprise/plugin-ordering/index.md
Labels: review:general

#7769 feat(sdk): automated oas update
  api-specs/portal.yaml
Labels: review:general

#7779 fix(gateway): update resources.requests to minimum hardware requirements
  app/_src/gateway/production/performance/benchmark.md
Labels: review:copyedit, skip-changelog

#7781 Fix: Flip terms in Azure config section
  app/konnect/org-management/sso.md
Labels: review:general, skip-changelog

#7774 Fix: Add changelog entry for deprecated OTEL parameters in 3.7
  app/_hub/kong-inc/opentelemetry/_changelog.md
Labels: review:copyedit

#7691 Feat/add ai metrics docs
  app/_hub/kong-inc/prometheus/overview/_index.md
  app/_src/gateway/production/logging/ai-analytics.md
  app/_src/gateway/production/monitoring/ai-metrics.md
Labels: review:copyedit

#7790 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7760 docs(traceableai) - Add timeout config, specify konnect compatibility, add kong versions
  app/_hub/traceableai/traceableai/_metadata/_index.yml
  app/_hub/traceableai/traceableai/schemas/_index.json
Labels: review:general

#7643 chore: Rename Servicehub -> Service Catalog
  app/_data/docs_nav_konnect.yml
  app/_includes/md/gateway/deployment-topologies.md
  app/_includes/md/konnect/deployment-topologies.md
  app/_redirects
  app/_src/gateway/production/deployment-topologies/index.md
  app/contributing/word-choice.md
  app/konnect/geo.md
  app/konnect/index.md
  app/konnect/service-catalog/index.md
  app/konnect/updates.md
  jekyll-dev.yml
  jekyll.yml
Labels: review:general, ci:manual-approve:link-validation

#7799 Lock spec-renderer and kongponents to the version without the toggle bug
  package-lock.json
  package.json
Labels: review:tech, skip-changelog

#7806 chore(3.8): Update support matrix
  app/_data/tables/support/gateway/versions/38.yml
  app/_src/gateway/support/index.md
Labels: review:general, skip-changelog
