Repository Kong/docs.konghq.com, pull requests merged in 2024-04, with the labels that each got.

#7067 Add gateway image build provenance verification docs
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_data/tables/features/gateway.yml
  app/_src/gateway/kong-enterprise/index.md
  app/_src/gateway/kong-enterprise/provenance-verification.md
Labels: review:general, review:sme

#6788 Feat: Update OIDC examples
  app/_hub/kong-inc/openid-connect/how-to/authentication/_authorization-code-flow.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_client-credentials.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_introspection.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_jwt-access-token.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_kong-oauth-token.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_password-grant.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_refresh-token.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_session.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_user-info.md
  app/_hub/kong-inc/openid-connect/how-to/authorization/_acl.md
  app/_hub/kong-inc/openid-connect/how-to/authorization/_claims.md
  app/_hub/kong-inc/openid-connect/how-to/authorization/_consumer.md
  app/_hub/kong-inc/openid-connect/how-to/third-party/_cognito.md
  app/_hub/kong-inc/openid-connect/how-to/third-party/_curity.md
  app/_includes/md/plugins-hub/oidc-prereqs.md
Labels: do not merge, review:general

#7162 Fix: Spacing on Gateway Docker install page
  app/_src/gateway/install/docker/index.md
Labels: review:general

#7140 Feat: Interactive markdown renderer
  app/_data/docs_nav_konnect.yml
  app/assets/images/products/konnect/api-products/konnect_service_docs_description.png
  app/assets/images/products/konnect/changelog/konnect-interactive-markdown.png
  app/konnect/api-products/index.md
  app/konnect/api-products/service-documentation.md
  app/konnect/dev-portal/index.md
  app/konnect/updates.md
Labels: review:general, review:copyedit

#7164 Fix: Add to Image Provenance & Signing Documents
  app/_src/gateway/kong-enterprise/provenance-verification.md
  app/_src/gateway/kong-enterprise/signed-images.md
Labels: review:general

#7168 cleanup(mesh): remove extra page
  app/_src/mesh/production/gateway/kic.md
Labels: review:general

#7171 Updated the references to Team Yellow to Team Green to reflect the colors in the diagram
  app/konnect/gateway-manager/control-plane-groups/index.md
Labels: review:copyedit, skip-changelog

#7145 Update: latencies.kong description
  app/_includes/md/plugins-hub/json-object-log.md
Labels: review:general, review:copyedit

#7093 feat: Cloud Gateway terminology updates
  app/_includes/md/konnect/konnect-architecture.md
  app/konnect/gateway-manager/data-plane-nodes/index.md
  app/konnect/gateway-manager/data-plane-nodes/upgrade.md
  app/konnect/gateway-manager/index.md
  app/konnect/getting-started/index.md
  app/konnect/index.md
Labels: review:general

#6937 Fix: Moesif Plugin Version Support and Support
  app/_hub/moesif/kong-plugin-moesif/_metadata/_index.yml
Labels: do not merge, review:general

#7182 Add tls.mode=Terminate to KIC Gateway API concept
  app/_src/kubernetes-ingress-controller/concepts/gateway-api.md
Labels: review:general

#7179 Correct append config example
  app/_hub/kong-inc/request-transformer-advanced/how-to/_index.md
Labels: review:general

#7186 Release: decK 1.36.x
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_deck_1.37.x.yml
  app/_data/kong_versions.yml
  app/_src/deck/reference/deck_file_namespace.md
Labels: review:general, ci:manual-approve:generated-files

#7170 Release: Gateway 3.6.1.2
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7155 Cloud gateways: How to upgrade data plane nodes
  app/konnect/gateway-manager/data-plane-nodes/upgrade.md
Labels: review:general, skip-changelog

#7188 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7139 Automated OAS Update
  api-specs/Konnect/v0/yaml/mesh-control-planes.yaml
  api-specs/Konnect/v2/yaml/application-auth-strategies.yaml
  api-specs/Konnect/v2/yaml/portal-management.yaml
  api-specs/Konnect/v3/yaml/identity.yaml
Labels: review:general

#7163 Cloud Gateways: Custom DNS management
  app/_data/docs_nav_konnect.yml
  app/konnect/dev-portal/customization/index.md
  app/konnect/reference/custom-dns.md
Labels: review:copyedit

#7195 fix(mesh): fix mesh RBAC documentation
  app/_src/mesh/features/rbac.md
Labels: review:general, review:copyedit

#7193 Fix: KIC overview grammar and punctuation
  app/_src/kubernetes-ingress-controller/index.md
Labels: review:copyedit

#7190 chore(kic): update latest to 3.1.3
  app/_data/kong_versions.yml
Labels: Kubernetes Team, review:general

#7196 Fix: Replace `plain` with `plaintext` for syntax highlighting
  app/_src/gateway/plugin-development/pdk/kong.log.md
  app/gateway/2.6.x/pdk/kong.log.md
  app/gateway/2.7.x/pdk/kong.log.md
  app/gateway/2.8.x/pdk/kong.log.md
Labels: review:general, ci:manual-approve:link-validation

#7174 Update: Licensing Admin API updates and Troubleshooting section links
  app/_includes/md/enterprise/deploy-license.md
  app/_src/gateway/licenses/deploy.md
  app/_src/gateway/licenses/examples.md
Labels: review:general

#7084 feat: Dedicated cloud gateway overview and changelog
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/_includes/md/konnect/deployment-topologies.md
  app/assets/images/products/konnect/gateway-manager/konnect-control-plane-cloud-gateway-wizard.png
  app/assets/images/products/konnect/gateway-manager/konnect-control-plane-cloud-gateway.png
  app/konnect/dedicated-cloud-gateways.md
  app/konnect/gateway-manager/index.md
  app/konnect/updates.md
Labels: review:copyedit

#7151 Feat: Update get started with Konnect and transit gateway documentation
  app/_data/docs_nav_konnect.yml
  app/konnect/gateway-manager/data-plane-nodes/transit-gateways.md
  app/konnect/getting-started/index.md
Labels: review:general, skip-changelog

#7205 kic: fix version compat table for v3 versions
  app/_data/docs_nav_kic_3.0.x.yml
  app/_data/docs_nav_kic_3.1.x.yml
  app/_data/docs_nav_kic_3.2.x.yml
  app/_src/kubernetes-ingress-controller/reference/version-compatibility.md
Labels: Kubernetes Team, review:general

#7197 Cloud Gateways: Update troubleshooting section
  app/konnect/gateway-manager/troubleshoot.md
Labels: review:copyedit

#7211 chore: set shell in makefile
  Makefile
Labels: review:tech

#7213 Update run instructions
  README.md
Labels: review:general

#7183 docs(kaudit): document the 'skip_ssl_verification' webhook configuration option [TPS-2050]
  app/konnect/org-management/audit-logging/webhook.md
Labels: review:copyedit, pending:release

#7215 Remove br from install page note
  app/_src/gateway/install/index.md
Labels: review:general

#7208 Fix: Add missing client-bound access tokens doc to OIDC plugin
  app/_hub/kong-inc/openid-connect/how-to/_cert-bound-access-tokens.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_introspection.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_jwt-access-token.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_session.md
Labels: review:general

#7156 feat: Cloud Gateway operations
  app/_data/docs_nav_konnect.yml
  app/konnect/gateway-manager/provision-cloud-gateway.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7199 Fix {:.warning} in Kong mesh
  app/_plugins/kuma-specific/warning.rb
Labels: review:general

#7217 Update: Diagrams for cloud gateways
  app/_includes/md/gateway/deployment-topologies.md
  app/assets/images/products/konnect/gateway-manager/konnect-control-planes-example.png
  app/assets/images/products/konnect/konnect-intro.png
  app/konnect/gateway-manager/index.md
Labels: review:general

#7216 Update: Plugin compatibility in dedicated cloud gateways
  app/_hub/kong-inc/app-dynamics/_metadata/_index.yml
  app/_hub/kong-inc/aws-lambda/_metadata/_index.yml
  app/_hub/kong-inc/file-log/_metadata/_index.yml
  app/_hub/kong-inc/prometheus/_metadata/_index.yml
  app/_hub/kong-inc/syslog/_metadata/_index.yml
  app/hub/plugins/compatibility/index.md
  app/konnect/compatibility.md
  app/konnect/gateway-manager/plugins/add-custom-plugin.md
  app/konnect/gateway-manager/plugins/index.md
Labels: review:copyedit

#7202 Exclude moesif page from broken link checker
  tools/broken-link-checker/config/ignored_targets.json
Labels: review:general

#7210 Set max-width to 1280px
  app/_assets/entrypoints/oas.less
  app/_assets/entrypoints/search.js
  app/_assets/javascripts/components/Sidebar.vue
  app/_assets/javascripts/views/SearchApp/App.css
  app/_assets/stylesheets/footer.less
  app/_assets/stylesheets/header-v2.less
  app/_assets/stylesheets/hub-landing-page.less
  app/_assets/stylesheets/page-header.less
  app/_assets/stylesheets/page.less
  app/_assets/stylesheets/pages/extension.less
  app/_assets/stylesheets/pages/landing-page.less
  app/_assets/stylesheets/variables.less
  app/_includes/nav-v2.html
Labels: review:general

#7207 Cloud Gateways: Chore PR
  api-specs/Konnect/v2/yaml/cloud-gateways.yaml
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_oas_data.json
  app/_includes/md/konnect/konnect-architecture.md
  app/konnect/gateway-manager/control-plane-groups/index.md
  app/konnect/gateway-manager/data-plane-nodes/index.md
  app/konnect/gateway-manager/data-plane-nodes/transit-gateways.md
  app/konnect/gateway-manager/dedicated-cloud-gateways.md
  app/konnect/gateway-manager/index.md
  app/konnect/gateway-manager/provision-cloud-gateway.md
  app/konnect/geo.md
  app/konnect/getting-started/index.md
  app/konnect/index.md
  app/konnect/reference/custom-dns.md
  app/konnect/updates.md
Labels: review:general

#7221 Chore: Update diagrams with "fully-managed" terminology
  app/_includes/md/konnect/deployment-topologies.md
  app/konnect/gateway-manager/dedicated-cloud-gateways.md
  app/konnect/gateway-manager/index.md
Labels: review:general

#7203 kic: add section about events for cluster scoped resources
  app/_src/kubernetes-ingress-controller/production/observability/events.md
Labels: Kubernetes Team, review:general, review:sme

#7222 (fix) Update to GW install page
  app/_data/tables/install_options_34x.yml
  app/_src/gateway/install/index.md
Labels: review:general

#7224 Cloud Gateways terminology
  app/_includes/md/konnect/introducing-konnect.md
  app/_includes/md/konnect/konnect-architecture.md
  app/konnect/gateway-manager/index.md
  app/konnect/network-resiliency.md
Labels: review:copyedit

#7223 feat(SLSA/provenance): publish provenance to central notary repository
  app/_src/gateway/kong-enterprise/provenance-verification.md
Labels: review:general, review:sme

#7233 Remove old and unused includes
  app/_includes/md/2.6.x/docker-install-steps.md
  app/_includes/md/2.6.x/ee-kong-user.md
  app/_includes/md/2.6.x/ldap/ldap-service-directory-mapping.md
  app/_includes/md/2.6.x/migrations/migrate-dev-portal.md
  app/_includes/md/2.7.x/deployment-options-k8s.md
  app/_includes/md/2.7.x/deployment-options.md
  app/_includes/md/2.7.x/docker-install-steps.md
  app/_includes/md/2.7.x/ee-kong-user.md
  app/_includes/md/2.7.x/ldap/ldap-service-directory-mapping.md
  app/_includes/md/2.7.x/migrations/migrate-dev-portal.md
  app/_includes/md/2.8.x/deployment-options-k8s.md
  app/_includes/md/2.8.x/deployment-options.md
  app/_includes/md/2.8.x/docker-install-steps.md
  app/_includes/md/2.8.x/ee-kong-user.md
  app/_includes/md/2.8.x/ldap/ldap-service-directory-mapping.md
  app/_includes/md/2.8.x/migrations/migrate-dev-portal.md
Labels: review:general

#7230 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7226 Feat: Cloud gateways networking diagram
  app/_includes/md/konnect/cloud-gateway-networking.md
  app/assets/images/icons/third-party/aws-transit-gateway-attachment.svg
  app/assets/images/icons/third-party/aws-transit-gateway.svg
  app/konnect/gateway-manager/data-plane-nodes/transit-gateways.md
  app/konnect/gateway-manager/dedicated-cloud-gateways.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7239 Make Docker page show all available base images
  app/_assets/javascripts/app.js
  app/_data/tables/install_options_34x.yml
  app/_src/gateway/install/docker/index.md
Labels: review:general

#7240 Cloud gateway: Add Insomnia link, and set max-width to overview page
  app/_api/konnect/cloud-gateways/_index.md
  app/konnect/gateway-manager/dedicated-cloud-gateways.md
Labels: review:general

#7097 Feat: Cloud Gateways Documentation
  .github/styles/kong/dictionary.txt
  api-specs/Konnect/v2/yaml/cloud-gateways.yaml
  app/_api/konnect/cloud-gateways/_index.md
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_oas_data.json
  app/_hub/kong-inc/app-dynamics/_metadata/_index.yml
  app/_hub/kong-inc/aws-lambda/_metadata/_index.yml
  app/_hub/kong-inc/file-log/_metadata/_index.yml
  app/_hub/kong-inc/prometheus/_metadata/_index.yml
  app/_hub/kong-inc/syslog/_metadata/_index.yml
  app/_includes/md/gateway/deployment-topologies.md
  app/_includes/md/konnect/cloud-gateway-networking.md
  app/_includes/md/konnect/deployment-topologies.md
  app/_includes/md/konnect/introducing-konnect.md
  app/_includes/md/konnect/konnect-architecture.md
  app/assets/images/icons/third-party/aws-transit-gateway-attachment.svg
  app/assets/images/icons/third-party/aws-transit-gateway.svg
  app/assets/images/products/konnect/gateway-manager/konnect-control-plane-cloud-gateway-wizard.png
  app/assets/images/products/konnect/gateway-manager/konnect-control-plane-cloud-gateway.png
  app/assets/images/products/konnect/gateway-manager/konnect-control-planes-example.png
  app/assets/images/products/konnect/konnect-intro.png
  app/hub/plugins/compatibility/index.md
  app/konnect/compatibility.md
  app/konnect/dev-portal/customization/index.md
  app/konnect/gateway-manager/data-plane-nodes/index.md
  app/konnect/gateway-manager/data-plane-nodes/transit-gateways.md
  app/konnect/gateway-manager/data-plane-nodes/upgrade.md
  app/konnect/gateway-manager/dedicated-cloud-gateways.md
  app/konnect/gateway-manager/index.md
  app/konnect/gateway-manager/plugins/add-custom-plugin.md
  app/konnect/gateway-manager/plugins/index.md
  app/konnect/gateway-manager/provision-cloud-gateway.md
  app/konnect/gateway-manager/troubleshoot.md
  app/konnect/geo.md
  app/konnect/getting-started/index.md
  app/konnect/index.md
  app/konnect/network-resiliency.md
  app/konnect/reference/custom-dns.md
  app/konnect/updates.md
Labels: review:general, review:sme

#7232 Bump jekyll-generator-single-source
  Gemfile
  Gemfile.lock
Labels: review:general

#7220 Release: Gateway 3.4.3.6
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7225 Fix -correct conflict statement in debug-request.md
  app/_src/gateway/production/debug-request.md
Labels: review:general

#7244 Add Konnect Terraform tab to plugin examples
  app/_includes/plugins/create-consumer/terraform.html
  app/_includes/plugins/hub-examples/consumer.html
  app/_includes/plugins/hub-examples/consumer_groups.html
  app/_includes/plugins/hub-examples/global.html
  app/_includes/plugins/hub-examples/route.html
  app/_includes/plugins/hub-examples/service.html
  app/_includes/plugins/hub-examples/terraform.html
  app/_plugins/drops/plugins/hub_examples.rb
  app/_plugins/filters/quote_filter.rb
  app/_plugins/generators/plugin_single_source/plugin/page_data.rb
Labels: review:general

#7158 Add helm repo add example
  app/_includes/snippets/gateway-operator/install_with_helm.md
Labels: review:general

#7227 Fix: Session plugin missing links and minor cleanup
  app/_hub/kong-inc/session/overview/_index.md
Labels: review:copyedit

#7201 chore: fix request transformer changelog links
  app/_hub/kong-inc/request-transformer-advanced/_changelog.md
  app/_hub/kong-inc/request-transformer/_changelog.md
Labels: review:general

#7242 Fix: Upstream URL for llama2 completion example
  app/_hub/kong-inc/ai-proxy/how-to/_llama2.md
Labels: review:general

#7247 Bump single-source-generator
  Gemfile.lock
Labels: review:general

#7219 Release: Gateway 3.6.1.3
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7250 Fix: Vale for kgo template
  .vale.ini
Labels: review:general, skip-changelog

#7184 feat(portal): describe developer auto approval behavior when using SSO login
  app/konnect/dev-portal/access-and-approval/auto-approve-devs-apps.md
  app/konnect/dev-portal/dev-reg.md
Labels: review:copyedit

#7251 (fix) Revert "Make Docker page show all available base images" + condense Docker install to single row
  app/_assets/javascripts/app.js
  app/_data/tables/install_options_34x.yml
  app/_src/gateway/install/docker/index.md
Labels: review:general

#7218 feat: change path to `v1/messages` api for anthropic
  app/_hub/kong-inc/ai-proxy/overview/_index.md
Labels: review:general, review:copyedit

#7253 Set labels automatically when updating kuma
  .github/workflows/sync-kuma-submodule.yml
Labels: review:tech

#7160 plugins(jwt): support more algorithms
  app/_hub/kong-inc/jwt/overview/_index.md
Labels: review:general, review:copyedit

#7254 docs(*): add a deprecated message to granular tracing
  app/_src/gateway/production/tracing/index.md
Labels: review:copyedit

#7258 Get Started: httpbin.org doesn't return a content-type charset
  app/_src/gateway/get-started/index.md
  app/_src/gateway/get-started/proxy-caching.md
Labels: review:general

#7260 Fix: Broken ordered list in getting started guide
  app/_src/gateway/get-started/proxy-caching.md
Labels: review:general

#7256 (fix) upload current docker logos
  app/_data/tables/install_options_34x.yml
  app/assets/images/icons/third-party/docker.png
Labels: review:general

#7264 Chore: Remove quickstart link
  app/konnect/architecture.md
Labels: review:general, skip-changelog

#7161 feat(plugins): tracing headers propagation
  app/_hub/kong-inc/opentelemetry/overview/_index.md
  app/_hub/kong-inc/zipkin/overview/_index.md
  app/_includes/md/plugins-hub/tracing-headers-propagation.md
Labels: review:general, review:copyedit

#7266 Fix: Change versioned spec links to working links
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
  api-specs/Gateway-OSS/3.5/kong-oss-3.5.yaml
  api-specs/Gateway-OSS/latest/kong-oss.yaml
  api-specs/overlays/ee/tag-descriptions.yaml
  api-specs/overlays/oss/tag-descriptions.yaml
Labels: review:general

#7265 Chore: add the ability to run vale on modified files locally to make file
  Makefile
Labels: review:general, skip-changelog

#7269 Chore: LTS labels
  app/_includes/docs-sidebar.html
  app/_layouts/docs-v2.html
  app/_src/gateway/support/index.md
Labels: review:general

#7268 fix: Add two missing OTEL images to Kong Mesh docs
  app/assets/images/guides/otel-metrics/grafana-dataplane-view.png
  app/assets/images/guides/otel-metrics/prometheus_otel_source.png
Labels: review:general

#7270 Fix: Add mapping information to transit gateways documentation
  app/konnect/gateway-manager/data-plane-nodes/transit-gateways.md
Labels: review:copyedit, skip-changelog

#7273 Fix: Clear up filtering endpoints issue
  app/konnect/api/filtering.md
Labels: review:general, skip-changelog

#7278 Changed from: Any to from: All
  app/_src/kubernetes-ingress-controller/guides/services/cross-namespace.md
Labels: review:general

#7281 Fix KONG_PRODUCTS so that it filters the right
  app/_plugins/hooks/products_renderer.rb
Labels: review:general

#7282 Add supported public cloud deployment platforms
  app/_src/gateway/support/index.md
Labels: review:copyedit

#7284 fix(vaults): envars are not vaults
  app/_src/gateway/kong-enterprise/secrets-management/backends/index.md
Labels: review:copyedit

#7285 Fix: update docker logo on Mesh docs
  app/_src/mesh/install.md
Labels: review:general

#7277 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7267 Fix: Upgrade paths
  app/_src/gateway/upgrade/index.md
Labels: review:general

#7262 Run submodule-sync on repository_dispatch
  .github/workflows/sync-submodules.yml
Labels: review:tech

#7287 Release: Gateway 3.4.3.7
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7120 docs(plugins): updates the description for app-reg
  app/_hub/kong-inc/application-registration/how-to/_index.md
  app/_hub/kong-inc/application-registration/overview/_index.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7296 Automated OAS Update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
  api-specs/Konnect/v0/yaml/ksearch.yaml
  api-specs/Konnect/v2/yaml/api-products.yaml
  api-specs/Konnect/v2/yaml/audit-logs.yaml
  api-specs/Konnect/v2/yaml/control-planes.yaml
  api-specs/Konnect/v2/yaml/portal-management.yaml
Labels: review:general

#7300 Automated OAS Update
  api-specs/Konnect/v3/yaml/identity.yaml
Labels: review:general

#7303 Add Kong 3.6.x to the list of supported versions by the Noname Security plugin.
  app/_hub/nonamesecurity/nonamesecurity-kongtrafficsource/_metadata/_index.yml
Labels: review:general

#7307 Chore: Dynamic Client Registration fixes
  app/konnect/dev-portal/applications/dynamic-client-registration/index.md
  app/konnect/updates.md
Labels: review:general, skip-changelog

#7308 Chore: Remove image from DP nodes overview page
  app/assets/images/products/konnect/gateway-manager/konnect-install-options.png
  app/konnect/gateway-manager/data-plane-nodes/index.md
Labels: review:general, skip-changelog

#7298 chore(kgo): KGO 1.2.3
  .github/styles/kong/dictionary.txt
  app/_data/kong_versions.yml
  app/gateway-operator/changelog.md
Labels: Kubernetes Team, review:general

#7312 Fix multiple typos under app/_src/gateway
  app/_src/gateway/breaking-changes/30x.md
  app/_src/gateway/install/kubernetes/proxy.md
  app/_src/gateway/plugin-development/custom-entities.md
  app/_src/gateway/plugin-development/pdk/kong.request.md
  app/_src/gateway/plugin-development/pdk/kong.tracing.md
  app/_src/gateway/production/access-control/enable-rbac.md
  app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
  app/_src/gateway/production/monitoring/index.md
  app/_src/gateway/production/tracing/api.md
  app/_src/gateway/reference/configuration/configuration-3.0-3.3.md
  app/_src/gateway/reference/configuration/configuration-3.4.x.md
  app/_src/gateway/reference/configuration/configuration-3.5.x.md
  app/_src/gateway/reference/rate-limiting.md
  app/_src/gateway/upgrade-v3.md
  app/_src/gateway/upgrade/backup-and-restore.md
Labels: review:general, ci:manual-approve:generated-files

#7311 Fix multiple typos under app/konnect directory
  app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
  app/konnect/dev-portal/applications/dynamic-client-registration/azure.md
  app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
  app/konnect/dev-portal/applications/dynamic-client-registration/okta.md
  app/konnect/gateway-manager/troubleshoot.md
  app/konnect/updates.md
Labels: review:general

#7299 Move lts to kong versions
  Gemfile
  Gemfile.lock
  app/_data/kong_versions.yml
  app/_includes/docs-sidebar.html
  app/_layouts/docs-v2.html
  app/_plugins/drops/releases_dropdown.rb
Labels: review:general

#7320 Fix guide docs about using configPatches
  app/_src/kubernetes-ingress-controller/guides/security/plugin-secrets.md
Labels: review:general

#7314 Chore: change 'outdated' to 'older' in version banner
  app/_layouts/docs-v2.html
  tests/sidebar.test.js
  tools/admonition-summary/scrape.js
Labels: review:general

#7318 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7321 Bump jekyll-generator-single-source to v0.0.14
  Gemfile
  Gemfile.lock
Labels: review:general

#7304 Feat: new expressions flavor in 3.7
  app/_src/gateway/key-concepts/routes/expressions.md
Labels: review:tech
