Repository Kong/docs.konghq.com, pull requests merged in 2024-01, with the labels that each got.

#6711 Fix: Spacing on gateway overview page
  app/_src/gateway/index.md
Labels: review:general

#6691 feat: Debian 12 support
  app/_data/tables/support/gateway/packages.yml
  app/_data/tables/support/gateway/versions/36.yml
Labels: review:general

#6702 fix: use more informative example for request-debug docs
  app/_src/gateway/production/debug-request.md
Labels: review:general

#6714 fix: typo in ingress redirect docs
  app/_src/kubernetes-ingress-controller/guides/services/https-redirect.md
Labels: review:copyedit

#6680 Add KIC configFrom guide
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/guides/security/plugin-secrets.md
Labels: review:copyedit

#6626 (feat) how to guides for mTLS-auth plugin
  app/_hub/kong-inc/mtls-auth/how-to/_add-cert-authorities.md
  app/_hub/kong-inc/mtls-auth/how-to/_manual-mapping-cert-consumers.md
  app/_hub/kong-inc/mtls-auth/overview/_index.md
Labels: do not merge, review:general

#6592 Feat: health check guide
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_src/gateway/production/monitoring/healthcheck-probes.md
  app/_src/gateway/production/monitoring/index.md
  app/_src/gateway/production/monitoring/readiness-check.md
Labels: review:general, review:copyedit, review:sme

#6712 Feat: Debian 12 support
  app/_data/tables/support/gateway/packages.yml
  app/_data/tables/support/gateway/versions/34.yml
  app/_data/tables/support/gateway/versions/35.yml
Labels: review:general

#6634 feat: Kong Functions (Pre-Plugins)
  app/_hub/kong-inc/pre-function/how-to/_ratelimit.md
  app/_hub/kong-inc/pre-function/overview/_index.md
  app/_hub/kong-inc/rate-limiting-advanced/how-to/_peak-traffic-rate-limit.md
  app/_includes/md/plugins-hub/rate-limit-peak-non-peak.md
Labels: review:tech, review:copyedit

#6630 feat: Create Benchmark Guide for Kong Gateway
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_src/gateway/production/benchmark.md
Labels: review:copyedit

#6689 rewrite the loadbalancing document
  .github/styles/kong/dictionary.txt
  app/_src/gateway/how-kong-works/load-balancing.md
  app/_src/gateway/production/blue-green.md
  app/_src/gateway/production/canary.md
Labels: review:general

#6587 (Feat) add support for Azure Linux to 3.5 matrix
  app/_data/tables/support/gateway/packages.yml
  app/_data/tables/support/gateway/versions/35.yml
Labels: do not merge, review:sme

#6720 Revert "(Feat) add support for Azure Linux to 3.5 matrix"
  app/_data/tables/support/gateway/packages.yml
  app/_data/tables/support/gateway/versions/35.yml
Labels: review:general, skip-changelog

#6725 Set `cloneSubmodules` to true in renovate's config
  .github/renovate.json
Labels: review:general

#6715 Add internal/external traffic KIC guide
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/guides/custom-class/internal-external.md
Labels: review:copyedit

#6650 (feat) Konnect in GCP Changelog
  app/konnect/updates.md
Labels: review:general, pending:release

#6726 Fix KIC TLS Termination guide
  app/_src/kubernetes-ingress-controller/guides/services/tls.md
Labels: review:general

#6717 Update: Rework style guide and add guidelines for writing recommendations
  app/contributing/style-guide.md
Labels: review:copyedit

#6724 fix: fixed link to kong prometheus plugin reference
  app/_src/gateway/production/monitoring/prometheus.md
Labels: review:general

#6721 (Feat) add support for Azure Linux to 3.5 matrix
  app/_data/tables/support/gateway/packages.yml
  app/_data/tables/support/gateway/versions/35.yml
Labels: review:general, review:sme

#6677 doc(kic) add reference grant guide
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/guides/services/cross-namespace.md
Labels: review:tech, review:general, review:copyedit

#6728 Automated OAS Update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
Labels: review:general

#6480 feat(KIC): add reference page for resources requiring ingress class
  app/_data/docs_nav_kic_3.0.x.yml
  app/_src/kubernetes-ingress-controller/reference/ingress-class-requirement.md
Labels: Kubernetes Team, review:general

#6734 Automated OAS Update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
Labels: review:general

#6710 kgo: add horizontal dataplane autoscaling section
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_kgo_1.2.x.yml
  app/_data/kong_versions.yml
  app/_src/gateway-operator/production/horizontal-autoscaling.md
  app/_src/gateway-operator/reference/custom-resources/1.2.x.md
Labels: Kubernetes Team, review:copyedit

#6735 fix: Update label on generate OAS action
  .github/workflows/sync-konnect-oas-data.yml
Labels: review:general

#6739 fix: broken link to support policy doc in the Gateway Upgrade guide
  app/_src/gateway/upgrade/index.md
Labels: review:general, skip-changelog

#6740 Update: Prerequisite to review version compatibility before Gateway upgrade
  app/_src/gateway/upgrade/index.md
  app/_src/gateway/upgrade/lts-upgrade.md
Labels: review:general

#6745 fix: do not mention default router change
  app/_src/kubernetes-ingress-controller/reference/faq/router.md
Labels: review:general

#6746 fix: small update to Oauth2 warning message
  app/_hub/kong-inc/oauth2/overview/_index.md
Labels: review:general, skip-changelog

#6663 feat(new-consumer): release notes and reference updates
  app/konnect/analytics/reference.md
  app/konnect/updates.md
Labels: review:copyedit, pending:release

#6695 Revamped Gateway on Kubernetes install guide
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_data/tables/install_options.yml
  app/_data/tables/install_options_34x.yml
  app/_includes/md/k8s/cloud/aks/annotations.md
  app/_includes/md/k8s/cloud/aks/install.md
  app/_includes/md/k8s/cloud/aks/test-with-public-lb.md
  app/_includes/md/k8s/cloud/eks/annotations.md
  app/_includes/md/k8s/cloud/eks/install.md
  app/_includes/md/k8s/cloud/eks/test-with-public-lb.md
  app/_includes/md/k8s/cloud/gke/annotations.md
  app/_includes/md/k8s/cloud/gke/install.md
  app/_includes/md/k8s/cloud/gke/test-with-public-lb.md
  app/_includes/md/k8s/cloud/kic/annotations.md
  app/_includes/md/k8s/cloud/kic/install.md
  app/_includes/md/k8s/cloud/kic/test-with-public-lb.md
  app/_includes/md/k8s/controller-install-tabs.md
  app/_includes/md/k8s/ingress-setup.md
  app/_includes/md/k8s/ingress-tabs.md
  app/_includes/md/k8s/single-ingress.md
  app/_includes/md/kic/support.md
  app/_plugins/generators/book.rb
  app/_redirects
  app/_src/gateway/install/kubernetes/admin.md
  app/_src/gateway/install/kubernetes/deployment-options.md
  app/_src/gateway/install/kubernetes/helm-quickstart.md
  app/_src/gateway/install/kubernetes/helm.md
  app/_src/gateway/install/kubernetes/index.md
  app/_src/gateway/install/kubernetes/kubectl.md
  app/_src/gateway/install/kubernetes/manager.md
  app/_src/gateway/install/kubernetes/openshift.md
  app/_src/gateway/install/kubernetes/portal.md
  app/_src/gateway/install/kubernetes/proxy.md
  app/_src/kubernetes-ingress-controller/support-policy.md
  app/moved_urls.yml
  tests/seo.test.js
  tools/broken-link-checker/config/ignored_targets.json
Labels: review:copyedit

#6694 feat(acl): add consumer-group support and examples
  app/_hub/kong-inc/acl/how-to/_examples.md
  app/_hub/kong-inc/acl/overview/_index.md
Labels: review:general, review:copyedit

#6751 Add redirect for Openshift install docs for Gateway
  app/_redirects
Labels: review:general

#6730 Add enterprise image signing verification docs
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_data/tables/features/gateway.yml
  app/_src/gateway/kong-enterprise/index.md
  app/_src/gateway/kong-enterprise/signed-images.md
Labels: review:general

#6741 Update: custom_fields_by_lua precedence in logging plugins
  app/_includes/md/plugins-hub/log_custom_fields_by_lua.md
Labels: review:copyedit

#6752 Automated OAS Update
  api-specs/Konnect/v0/yaml/ksearch.yaml
  api-specs/Konnect/v2/yaml/analytics-requests.yaml
Labels: review:general, skip-changelog

#6758 Plugin consumer examples
  app/_includes/plugins/create-consumer/curl.html
  app/_includes/plugins/create-consumer/konnect.html
  app/_includes/plugins/create-consumer/kubernetes.html
  app/_includes/plugins/create-consumer/yaml.html
  app/_includes/plugins/hub-examples/global.html
  app/_includes/plugins/hub-examples/route.html
  app/_includes/plugins/hub-examples/service.html
Labels: review:general

#6757 Fix linked to `Verify signatures for Signed Images`
  app/_src/gateway/kong-enterprise/index.md
Labels: review:general

#6755 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6753 Fix: Correct default value for proxy-timeout-seconds in KIC 2.11
  app/_src/kic-v2/references/cli-arguments-lte-2.11.x.md
Labels: review:general

#6763 chore: Add nested sidenav items to plugin
  app/_plugins/generators/plugin_single_source/pages/base.rb
  app/_plugins/generators/plugin_single_source/plugin/pages_builder.rb
  app/_plugins/generators/plugin_single_source/plugin/sidenav.rb
  spec/app/_plugins/generators/plugin_single_source/pages/how_to_spec.rb
  spec/fixtures/app/_hub/kong-inc/jwt-signer/how-to/_index.md
  spec/fixtures/app/_hub/kong-inc/jwt-signer/how-to/nested/_tutorial.md
  spec/templates/plugin_with_versions_spec.rb
Labels: review:general, skip-changelog

#6767 [Plugin Hub] Position nested sidenav subitems before links
  app/_plugins/generators/plugin_single_source/plugin/sidenav.rb
  spec/templates/plugin_with_versions_spec.rb
Labels: review:general

#6769 Fix TLS parentRef when using Gateway API
  app/_src/kubernetes-ingress-controller/guides/services/tls.md
Labels: review:general

#6750 Release: Gateway version 3.4.3.3
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#6762 Release: Changelog and version bump for Gateway 2.8.4.6
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#6772 Remove "feat(acl): add consumer-group support and examples"
  app/_hub/kong-inc/acl/how-to/_examples.md
  app/_hub/kong-inc/acl/overview/_index.md
Labels: review:general, skip-changelog

#6744 Update for DP resilience new changes
  app/_src/gateway/kong-enterprise/cp-outage-handling.md
Labels: review:general, pr/please review

#6782 kic: bump latest patch versions
  app/_data/kong_versions.yml
Labels: review:general

#6761 Feat: Update Kong Gateway EE specs [skip ci]
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
Labels: review:general

#6784 Feat: AppDynamics certificate env variables
  app/_hub/kong-inc/app-dynamics/overview/_index.md
Labels: review:copyedit

#6768 Self-host Google Fonts Stylesheet
  app/_assets/stylesheets/index.less
  app/_assets/stylesheets/roboto-fonts.css
  app/_includes/head.html
Labels: review:tech

#6800 Add trailing slash to urls analyzed by lighthouse
  netlify.toml
Labels: review:general, skip-changelog

#6793 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6803 Chore: fixes for a minor change in the Quickstart script output
  app/_src/gateway/get-started/index.md
  app/_src/gateway/production/monitoring/prometheus.md
  app/_src/gateway/production/monitoring/statsd.md
Labels: review:general

#6766 Remove unused google reCaptcha script
  app/_includes/footer.html
  app/_includes/head.html
Labels: review:tech

#6807 Bootstrap KIC 3.1 docs
  app/_data/docs_nav_kic_3.1.x.yml
  app/_data/kong_versions.yml
Labels: review:general

#6809 kgo: merge 1.2.x related changes
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_kgo_1.2.x.yml
  app/_data/kong_versions.yml
  app/_src/gateway-operator/production/horizontal-autoscaling.md
  app/_src/gateway-operator/reference/custom-resources/1.2.x.md
Labels: review:general

#6808 Add `font-display: swap`
  app/_assets/stylesheets/roboto-fonts.css
Labels: review:tech

#6804 Update: Add admin token auth to Gateway EE spec [skip ci]
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
Labels: review:tech

#6776 Add gateway-37 repo keys
  app/_data/installation/gateway.yml
Labels: review:tech

#6814 feat: update Konnect changelog for Gateway manager updates
  app/konnect/updates.md
Labels: review:general, skip-changelog

#6815 Automated OAS Update
  api-specs/Konnect/v2/yaml/control-planes.yaml
Labels: review:general, skip-changelog

#6797 Add WebAssembly filter chains to Gateway OSS 3.4 and 3.5 OpenAPI specs
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
  api-specs/Gateway-OSS/3.5/kong-oss-3.5.yaml
Labels: review:general, review:copyedit

#6816 Fix: remove unused 3.4.x Admin API file #6799
  app/_src/gateway/admin-api/admin-api-3.4.x.md
Labels: review:general, skip-changelog

#6818 Update: Fix broken link
  app/_hub/kong-inc/openid-connect/overview/_index.md
Labels: review:general

#6826 Add explicit RHEL7 and RHEL9 test targets
  tools/install-tester/config/jobs.yaml
  tools/install-tester/config/setup.yaml
  tools/install-tester/index.js
Labels: review:tech

#6821 Fix: Use config.scopes instead of config.scopes_required in OIDC okta guide
  app/_hub/kong-inc/openid-connect/how-to/third-party/_auth0.md
  app/_hub/kong-inc/openid-connect/how-to/third-party/_azure-ad.md
  app/_hub/kong-inc/openid-connect/how-to/third-party/_curity.md
  app/_hub/kong-inc/openid-connect/how-to/third-party/_google.md
  app/_hub/kong-inc/openid-connect/how-to/third-party/_okta.md
Labels: review:copyedit

#6819 Fix: Incorrect value listed for OIDC consumer claim field
  app/_src/gateway/kong-enterprise/dev-portal/authentication/okta-config.md
  app/gateway/2.6.x/developer-portal/administration/application-registration/okta-config.md
  app/gateway/2.7.x/developer-portal/administration/application-registration/okta-config.md
  app/gateway/2.8.x/developer-portal/administration/application-registration/okta-config.md
Labels: review:copyedit

#6835 Fix sitemap generation
  app/_plugins/generators/seo/index_entry_builder.rb
  app/_plugins/generators/utils/canonical_url.rb
  spec/app/_plugins/generators/seo/index_entry_builder_spec.rb
  spec/app/_plugins/generators/utils/canonical_url_spec.rb
Labels: review:general

#6810 Fix: update azure vault variable names
  app/_src/gateway/kong-enterprise/secrets-management/backends/azure-key-vaults.md
Labels: review:general

#6577 feat(cpg-updates): updated statements and added release notes
  app/konnect/analytics/index.md
  app/konnect/updates.md
Labels: review:copyedit, pending:release

#6839 Update: PR template update for version conditionals [skip ci]
  .github/PULL_REQUEST_TEMPLATE.md
Labels: review:copyedit, skip-changelog

#6813 Release: Gateway 3.5.0.3
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:general, ci:manual-approve:link-validation

#6845 Feat: OSS badges
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/badges.less
  app/_includes/hub_cards.html
  app/_includes/plugins/badges.html
  app/_layouts/plugins/show.html
  app/_plugins/drops/plugins/badges.rb
Labels: review:tech, review:general

#6837 Fix: Incorrect request format in DB-less and declarative config doc
  app/_src/gateway/production/deployment-topologies/db-less-and-declarative-config.md
Labels: review:general

#6842 KIC: Use standard repository in Helm example instructions
  app/_src/kubernetes-ingress-controller/install/helm.md
Labels: review:general

#6831 chore: add notice for trusting vault backend's ssl certificate
  app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/gcp-sm.md
Labels: review:tech, review:general

#6851 Bump ruby to 3.3.0
  .ruby-version
  Gemfile
  Gemfile.lock
  app/_plugins/blocks/plugin_version_block.rb
  app/_plugins/drops/plugins/examples/kubernetes.rb
  app/_plugins/generators/oas_definition/error_page.rb
  app/_plugins/generators/pages/nav_items_data.rb
  app/_plugins/generators/plugin_single_source/pages/configuration_examples.rb
  app/_plugins/generators/plugin_single_source/plugin/examples/base.rb
  app/_plugins/generators/utils/version.rb
Labels: review:tech

#6853 kic: add explanation for Gateway's publish service
  app/_src/kubernetes-ingress-controller/concepts/gateway-api.md
Labels: review:copyedit

#6849 Update workspaces.md
  app/_src/gateway/kong-manager/workspaces.md
Labels: review:copyedit, skip-changelog

#6862 Fix: cascade delete note appearing for wrong version
  app/_src/gateway/kong-manager/workspaces.md
Labels: review:general, skip-changelog

#6794 docs(kong-manager): OIDC and LDAP updates
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_src/gateway/kong-manager/auth/ldap/service-directory-mapping.md
  app/_src/gateway/kong-manager/auth/oidc/configure.md
  app/_src/gateway/kong-manager/auth/oidc/mapping.md
  app/_src/gateway/kong-manager/auth/oidc/migrate.md
Labels: review:copyedit, skip-changelog

#6865 Bump jekyll-generator-single-source to v0.0.11
  Gemfile
  Gemfile.lock
Labels: review:general

#6867 Bundle `development` group in development
  netlify.toml
  package.json
Labels: review:general

#6838 chore: 3.6: Support matrix updates
  app/_src/gateway/support/browser.md
  app/_src/gateway/support/index.md
  app/_src/gateway/support/third-party.md
Labels: review:general, skip-changelog

#6844 chore: Add 3.6 upgrade path table
  app/_src/gateway/migrate-cassandra-to-postgres.md
  app/_src/gateway/upgrade/index.md
Labels: review:general, skip-changelog

#6848 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog
