Repository Kong/docs.konghq.com, pull requests merged in 2024-02, with the labels that each got.

#6872 chore: Update PR template again [skip ci]
  .github/PULL_REQUEST_TEMPLATE.md
Labels: review:copyedit, skip-changelog

#6878 Cache products and use them in generators
  app/_plugins/generators/pages/productable.rb
  app/_plugins/generators/pages/version_data.rb
  app/_plugins/generators/versions.rb
Labels: review:general

#6856 Update enable-app-reg.md
  app/konnect/dev-portal/applications/enable-app-reg.md
Labels: review:general

#6860 Chore: remove and redirect portal RBAC to portal management API
  app/_api/konnect/portal-rbac/_index.md
  app/_redirects
Labels: review:general, skip-changelog

#6880 Fix: Admin API markdown doc edits
  app/_src/gateway/admin-api/index_latest.md
Labels: review:copyedit, skip-changelog

#6833 Feat: Improved Proxy URL support in Konnect
  app/konnect/updates.md
Labels: review:general, skip-changelog

#6870 Adding Konnect CTA
  app/_src/gateway/get-started/index.md
Labels: review:general

#6903 chore: Remove anchor link redirects
  app/_redirects
Labels: review:general, skip-changelog

#6841 Refactor title tag generation
  app/_includes/head.html
  app/_layouts/default.html
  app/_plugins/generators/oas_definition/page_data.rb
  app/_plugins/generators/seo/tags/title.rb
  app/_plugins/generators/seo/tags/version/base.rb
  app/_plugins/generators/seo/tags/version/no_version.rb
  app/_plugins/generators/seo/tags/version/oas.rb
  app/_plugins/generators/seo_tags_generator.rb
  app/_plugins/generators/utils/page_product_name.rb
  app/_plugins/generators/utils/version.rb
  app/search.html
  jekyll-dev.yml
  jekyll.yml
  spec/app/_plugins/generators/oas_definition/page_data_spec.rb
  spec/app/_plugins/generators/seo/tags/title_spec.rb
  tests/titles.test.js
Labels: review:general

#6901 Fix: grammatical error
  app/_src/gateway/index.md
Labels: review:general, skip-changelog

#6899 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6906 Chore: Add an unreleased/dev version for decK
  app/_data/docs_nav_deck_1.34.x.yml
  app/_data/kong_versions.yml
Labels: review:general, skip-changelog

#6909 kic: document konghq.com/tags annotation
  app/_src/kubernetes-ingress-controller/reference/annotations.md
Labels: review:general, area/docs

#6908 Update Kong/k8s support matrix
  app/_includes/md/kic/support.md
Labels: review:general

#6916 fix(mesh): add missing delegated gateway image
  app/assets/images/docs/diagram-delegated-gateway-detailed@3x.jpg
Labels: review:general, skip-changelog

#6912 chore: Set explicit timeouts for all workflows [skip ci]
  .github/workflows/auto-close-kong-issues.yml
  .github/workflows/autogenerated-warning.yml
  .github/workflows/check-links.yml
  .github/workflows/ci-autofix.yml
  .github/workflows/generate-changelog.yml
  .github/workflows/linting.yml
  .github/workflows/require-review-label.yml
  .github/workflows/run-tests.yml
  .github/workflows/sync-konnect-oas-data.yml
  .github/workflows/sync-kuma-submodule.yml
  .github/workflows/sync-submodules.yml
Labels: review:tech, ci:manual-approve:link-validation

#6778 Feat: Appsentinels plugin
  app/_hub/appsentinels/appsentinels/_metadata.yml
  app/_hub/appsentinels/appsentinels/examples/_index.yml
  app/_hub/appsentinels/appsentinels/overview/_index.md
  app/_hub/appsentinels/appsentinels/schemas/_index.json
  app/assets/images/icons/hub/appsentinels_appsentinels.png
Labels: review:general, review:copyedit

#6904 Chore: Plan and usage UI changes
  app/assets/images/products/konnect/api-products/api-products-manage.png
  app/assets/images/products/konnect/api-products/api-products-overview.png
  app/assets/images/products/konnect/billing/billing-and-usage.png
  app/assets/images/products/konnect/dashboard/konnect-dashboard.png
  app/assets/images/products/konnect/gateway-manager/konnect-control-plane-dashboard.png
  app/assets/images/products/konnect/gateway-manager/konnect-runtime-instance-gateway.png
  tools/screenshots/konnect/api-products/api-products-dashboard.yaml
  tools/screenshots/konnect/api-products/api-products-manage.yaml
  tools/screenshots/konnect/overview/control-plane-dashboard.yaml
  tools/screenshots/konnect/overview/konnect-dashboard.yaml
  tools/screenshots/konnect/runtimes/runtime-instances-overview.yaml
Labels: review:general

#6918 chore: Fix up Appsentinels formatting and phrasing
  app/_hub/appsentinels/appsentinels/overview/_index.md
Labels: review:copyedit, skip-changelog

#6921 Fix: ACL doc appearing in 3.5 when it should be in 3.6
  app/_hub/kong-inc/acl/_3.5.x/overview/_index.md
Labels: review:general, skip-changelog

#6910 kic: extend license guide with KongLicense CRD
  app/_src/kubernetes-ingress-controller/license.md
Labels: review:general, area/docs

#6917 kic: extend vault guide with KongVault CRD usage
  app/_src/kubernetes-ingress-controller/guides/security/kong-vault.md
Labels: review:general, area/docs

#6926 kic: extend secrets in plugins guide with configFrom field
  app/_src/kubernetes-ingress-controller/guides/security/plugin-secrets.md
Labels: review:general, area/docs

#6925 Fix a typo
  app/_hub/kong-inc/key-auth/overview/_index.md
Labels: review:general

#6927 Bootstrap KIC 3.2 docs
  app/_data/docs_nav_kic_3.2.x.yml
  app/_data/kong_versions.yml
Labels: review:general, skip-changelog

#6922 Fix: Reference lua package path location in Exit Transformer plugin
  app/_hub/kong-inc/exit-transformer/overview/_index.md
Labels: review:general

#6923 chore: kong.conf updates for 3.6
  app/_src/gateway/reference/configuration.md
Labels: review:general, ci:manual-approve:generated-files, skip-changelog

#6653 feat: Konnect YAML and JSON Format for Gateway Config
  app/assets/images/products/konnect/gateway-manager/konnect-config-export.png
  app/konnect/gateway-manager/configuration/index.md
  app/konnect/gateway-manager/declarative-config.md
  app/konnect/updates.md
Labels: review:copyedit, pending:release

#6920 Chore: PDK docs
  app/_src/gateway/plugin-development/pdk/kong.plugin.md
  app/_src/gateway/plugin-development/pdk/kong.response.md
  app/_src/gateway/plugin-development/pdk/kong.service.request.md
  app/_src/gateway/plugin-development/pdk/kong.service.response.md
  app/_src/gateway/plugin-development/pdk/kong.tracing.md
Labels: review:general, ci:check-skipped:generated-files, skip-changelog

#6911 Release: Gateway 2.8.4.7
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#6931 fix(rt-plugin): fix description of variables
  app/_hub/kong-inc/request-transformer-advanced/how-to/_templates.md
  app/_hub/kong-inc/request-transformer/how-to/_templates.md
Labels: review:general

#6829 feat: Add filterchains to the Admin EE spec
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
Labels: review:general, skip-changelog

#6919 Chore: Update Admin API Docs for 3.6 [skip-ci]
  api-specs/Gateway-EE/latest/kong-ee.yaml
  api-specs/Gateway-OSS/latest/kong-oss.yaml
Labels: review:general, skip-changelog

#6932 Release: Gateway 3.4.3.4
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#6938 Feat: Add cert expiry to clustering/data-planes output
  app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Labels: review:general, skip-changelog

#6942 Fix: Add missing items from changelog to API specs [skip-ci]
  api-specs/Gateway-EE/latest/kong-ee.yaml
  api-specs/Gateway-OSS/latest/kong-oss.yaml
Labels: review:general, skip-changelog

#6941 fix: 3.4.3.4 release date
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation, skip-changelog

#6930 Update enable-app-reg.md for app reg v2 changes
  app/konnect/dev-portal/applications/enable-app-reg.md
Labels: review:general, skip-changelog

#6943 kic: split CRD reference types into sections
  app/_src/kubernetes-ingress-controller/reference/custom-resources-3.1.x.md
Labels: area/docs, review:sme

#6928 Feat: Add new performance testing results doc for Gateway 3.6
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_redirects
  app/_src/gateway/production/performance/benchmark.md
  app/_src/gateway/production/performance/performance-testing.md
  app/_src/gateway/production/sizing-guidelines.md
Labels: review:copyedit

#6882 Feat/ai plugins get started
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_hub/kong-inc/ai-prompt-decorator/_metadata.yml
  app/_hub/kong-inc/ai-prompt-guard/_metadata.yml
  app/_hub/kong-inc/ai-prompt-template/_metadata.yml
  app/_hub/kong-inc/ai-proxy/_metadata.yml
  app/_hub/kong-inc/ai-request-transformer/_metadata.yml
  app/_hub/kong-inc/ai-response-transformer/_metadata.yml
  app/_layouts/extension.html
  app/_src/gateway/get-started/ai-gateway.md
  app/assets/images/products/gateway/getting-started-guide/ai-gateway.png
Labels: review:general

#6945 chore: Update partner plugins statement
  app/contributing/partner-plugins.md
Labels: review:copyedit, skip-changelog

#6779 Feat: AI plugins
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/tables/features/gateway.yml
  app/_hub/kong-inc/ai-prompt-decorator/_changelog.md
  app/_hub/kong-inc/ai-prompt-decorator/_metadata.yml
  app/_hub/kong-inc/ai-prompt-decorator/how-to/_index.md
  app/_hub/kong-inc/ai-prompt-decorator/overview/_index.md
  app/_hub/kong-inc/ai-prompt-decorator/versions.yml
  app/_hub/kong-inc/ai-prompt-guard/_changelog.md
  app/_hub/kong-inc/ai-prompt-guard/_metadata.yml
  app/_hub/kong-inc/ai-prompt-guard/how-to/_index.md
  app/_hub/kong-inc/ai-prompt-guard/overview/_index.md
  app/_hub/kong-inc/ai-prompt-guard/versions.yml
  app/_hub/kong-inc/ai-prompt-template/_changelog.md
  app/_hub/kong-inc/ai-prompt-template/_metadata.yml
  app/_hub/kong-inc/ai-prompt-template/how-to/_index.md
  app/_hub/kong-inc/ai-prompt-template/overview/_index.md
  app/_hub/kong-inc/ai-prompt-template/versions.yml
  app/_hub/kong-inc/ai-proxy/_changelog.md
  app/_hub/kong-inc/ai-proxy/_metadata.yml
  app/_hub/kong-inc/ai-proxy/how-to/_anthropic.md
  app/_hub/kong-inc/ai-proxy/how-to/_azure.md
  app/_hub/kong-inc/ai-proxy/how-to/_cohere.md
  app/_hub/kong-inc/ai-proxy/how-to/_llama2.md
  app/_hub/kong-inc/ai-proxy/how-to/_mistral.md
  app/_hub/kong-inc/ai-proxy/how-to/_openai.md
  app/_hub/kong-inc/ai-proxy/overview/_index.md
  app/_hub/kong-inc/ai-proxy/versions.yml
  app/_hub/kong-inc/ai-request-transformer/_changelog.md
  app/_hub/kong-inc/ai-request-transformer/_metadata.yml
  app/_hub/kong-inc/ai-request-transformer/how-to/_index.md
  app/_hub/kong-inc/ai-request-transformer/overview/_index.md
  app/_hub/kong-inc/ai-request-transformer/versions.yml
  app/_hub/kong-inc/ai-response-transformer/_changelog.md
  app/_hub/kong-inc/ai-response-transformer/_metadata.yml
  app/_hub/kong-inc/ai-response-transformer/how-to/_index.md
  app/_hub/kong-inc/ai-response-transformer/overview/_index.md
  app/_hub/kong-inc/ai-response-transformer/versions.yml
  app/_includes/md/plugins-hub/ai-providers-prereqs.md
  app/_includes/plugins/header.html
  app/_layouts/extension.html
  app/_layouts/plugins/show.html
  app/_plugins/drops/plugins/versions_dropdown.rb
  app/_src/gateway/get-started/ai-gateway.md
  app/assets/images/icons/hub/kong-inc_ai-data-sanitization.png
  app/assets/images/icons/hub/kong-inc_ai-prompt-decorator.png
  app/assets/images/icons/hub/kong-inc_ai-prompt-guard.png
  app/assets/images/icons/hub/kong-inc_ai-prompt-template.png
  app/assets/images/icons/hub/kong-inc_ai-proxy.png
  app/assets/images/icons/hub/kong-inc_ai-request-transformer.png
  app/assets/images/icons/hub/kong-inc_ai-response-transformer.png
  app/assets/images/nav/hub/ai.svg
  app/assets/images/products/gateway/getting-started-guide/ai-gateway.png
  app/assets/images/products/plugins/ai-proxy/ai-proxy-azure-1.png
  app/assets/images/products/plugins/ai-proxy/ai-proxy-azure-2.png
  app/hub/index.html
  jekyll-dev.yml
  jekyll.yml
  spec/app/_plugins/drops/plugins/versions_dropdown_option_spec.rb
Labels: review:copyedit, ci:check-skipped:generated-files, review:sme

#6929 Release: Gateway 3.6
  app/_data/kong_versions.yml
Labels: review:general

#6939 chore: Changelogs and breaking changes for 3.6
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_hub/kong-inc/acl/_changelog.md
  app/_hub/kong-inc/acme/_changelog.md
  app/_hub/kong-inc/app-dynamics/changelog.md
  app/_hub/kong-inc/azure-functions/_changelog.md
  app/_hub/kong-inc/basic-auth/_changelog.md
  app/_hub/kong-inc/datadog/_changelog.md
  app/_hub/kong-inc/forward-proxy/_changelog.md
  app/_hub/kong-inc/ip-restriction/_changelog.md
  app/_hub/kong-inc/jwt-signer/_changelog.md
  app/_hub/kong-inc/ldap-auth-advanced/_changelog.md
  app/_hub/kong-inc/mocking/_changelog.md
  app/_hub/kong-inc/oas-validation/_changelog.md
  app/_hub/kong-inc/oauth2-introspection/_changelog.md
  app/_hub/kong-inc/openid-connect/_changelog.md
  app/_hub/kong-inc/opentelemetry/_changelog.md
  app/_hub/kong-inc/prometheus/_changelog.md
  app/_hub/kong-inc/proxy-cache-advanced/_changelog.md
  app/_hub/kong-inc/proxy-cache/_changelog.md
  app/_hub/kong-inc/rate-limiting-advanced/_changelog.md
  app/_hub/kong-inc/rate-limiting/_changelog.md
  app/_hub/kong-inc/request-termination/_changelog.md
  app/_hub/kong-inc/request-validator/_changelog.md
  app/_hub/kong-inc/response-ratelimiting/_changelog.md
  app/_hub/kong-inc/route-transformer-advanced/changelog.md
  app/_hub/kong-inc/saml/_changelog.md
  app/_src/gateway/breaking-changes/36x.md
  app/_src/gateway/reference/configuration.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation, ci:manual-approve:generated-files, skip-changelog

#6883 chore: add compatibility updates for Gateway 3.6 release
  app/_data/tables/version_errors_konnect.yml
Labels: do not merge, review:general

#6940 chore: 3.6 sbom link
  app/_src/gateway/support/sbom.md
Labels: review:general, skip-changelog

#6949 Sync Konnect OAS Data
  app/_data/konnect_oas_data.json
Labels: review:general, skip-changelog

#6950 chore: Generate insomnia buttons for 3.6 [skip ci]
  app/_api/gateway/admin-ee/_index.md
  app/_api/gateway/admin-oss/_index.md
Labels: review:general, skip-changelog

#6914 fix(kong-manager): add more details for OIDC breaking changes
  app/_src/gateway/breaking-changes/36x.md
  app/_src/gateway/kong-manager/auth/oidc/configure.md
  app/_src/gateway/kong-manager/auth/oidc/migrate.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation, skip-changelog

#6951 Fix: Move StatsD plugins to Analytics and Monitoring category
  app/_hub/kong-inc/statsd-advanced/_metadata.yml
  app/_hub/kong-inc/statsd/_metadata.yml
Labels: review:general, skip-changelog

#6902 Feat(plugins): Collapsible sections styling
  app/_assets/stylesheets/collapsible-sections.less
  app/_assets/stylesheets/index.less
  app/_includes/md/plugins-hub/oidc-prereqs.md
  app/_layouts/extension.html
Labels: review:general

#6955 fix(mistral): docs are a copy of llama2
  app/_hub/kong-inc/ai-proxy/how-to/_mistral.md
Labels: review:tech

#6957 chore: Comment out links to private benchmark repo
  app/_src/gateway/production/performance/performance-testing.md
Labels: review:general

#6956 fix(ai-proxy): missing provider for mistral.ai
  app/_hub/kong-inc/ai-proxy/how-to/_mistral.md
Labels: review:tech, skip-changelog

#6952 release deck 1.34.0
  app/_data/docs_nav_deck_1.34.x.yml
  app/_data/kong_versions.yml
  app/_src/deck/reference/deck_file_namespace.md
Labels: review:general, review:copyedit, ci:manual-approve:generated-files

#6936 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6958 chore: Adjust collapsible sections to apply everywhere
  app/_assets/stylesheets/collapsible-sections.less
  app/_includes/md/kic/prerequisites.md
Labels: review:general

#6959 chore: Create 1.35 unreleased deck version
  app/_data/docs_nav_deck_1.35.x.yml
  app/_data/kong_versions.yml
Labels: review:general

#6962 chore: Add gateway version to konnect compat list
  app/konnect/compatibility.md
Labels: review:general

#6963 chore: Uncomment links to benchmarking repo
  app/_src/gateway/production/performance/performance-testing.md
Labels: review:general

#6968 Fix: Remove sentence stating Analytics for a control plane group are only available at the group level.
  app/konnect/gateway-manager/control-plane-groups/index.md
Labels: review:general, skip-changelog

#6978 chore: Bump unreleased Gateway version to 3.7
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_data/kong_versions.yml
Labels: review:general, skip-changelog

#6975 Fix: remove if_version on the Or operator in the table
  app/_src/gateway/reference/expressions-language/language-references.md
Labels: review:general

#6971 fix(kong-manager): add ignored params to the OIDC migration guide
  app/_src/gateway/kong-manager/auth/oidc/migrate.md
Labels: review:copyedit

#6979 Fix: Links to KIC cli-arguments reference
  app/_data/docs_nav_kic_3.1.x.yml
  app/_data/docs_nav_kic_3.2.x.yml
  app/_src/kubernetes-ingress-controller/reference/cli-arguments-3.1.x.md
Labels: review:general

#6974 fix: Add 3.6 conditional rendering for single backup nodes
  app/_src/gateway/kong-enterprise/cp-outage-handling.md
Labels: do not merge, review:general

#6984 Add documentation on higher ulimit requirement for 3.6.0.0
  .github/styles/kong/dictionary.txt
  app/_src/gateway/breaking-changes/36x.md
  app/gateway/changelog.md
Labels: review:copyedit

#6982 add more info about cache key generation in proxy-cache-advanced
  app/_hub/kong-inc/proxy-cache-advanced/overview/_index.md
Labels: review:general

#6986 Fix spec
  app/_plugins/drops/plugins/versions_dropdown.rb
  spec/app/_plugins/drops/plugins/versions_dropdown_option_spec.rb
Labels: review:tech, skip-changelog

#6988 fix: Remove inaccurate note in OAuth2 plugin
  app/_hub/kong-inc/oauth2/overview/_index.md
Labels: review:general

#6944 docs(mesh/rbac): add information how to unlock yourself
  app/_src/mesh/features/rbac.md
Labels: review:general

#6964 docs(mesh): in Vault docs switch to orphan tokens
  app/_src/mesh/features/vault.md
Labels: review:tech

#6991 Fix: Remove extra identical heading from konnect installation docs
  app/konnect/gateway-manager/data-plane-nodes/index.md
Labels: review:general, skip-changelog

#6812 feat: Add changelog for additional plugin support for consumer groups in Konnect
  app/konnect/updates.md
Labels: review:general, pending:release

#6987 Fix links to plugins
  app/_layouts/extension.html
Labels: review:general

#6994 Release: Gateway 3.6.1.0
  app/_data/kong_versions.yml
  app/_src/gateway/breaking-changes/36x.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#6993 Automated Changelog update [skip ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#6996 Updated example of Auth0 configuration _auth0.md
  app/_hub/kong-inc/openid-connect/how-to/third-party/_auth0.md
Labels: review:sme

#6998 Add Gateway 3.6 to KIC compatibility matrix
  app/_src/kic-v2/references/version-compatibility.md
Labels: review:general

#6861 feat: Rework Konnect getting started section
  .github/styles/kong/auto-ignore.txt
  app/_assets/stylesheets/page.less
  app/_data/docs_nav_konnect.yml
  app/_includes/md/konnect/introducing-konnect.md
  app/_includes/md/konnect/konnect-architecture.md
  app/_redirects
  app/assets/images/icons/brand-icons/icn-customers.svg
  app/assets/images/icons/brand-icons/icn-extensibility.svg
  app/assets/images/icons/brand-icons/icn-key-auth.png
  app/assets/images/icons/brand-icons/icn-operation.svg
  app/assets/images/icons/brand-icons/icn-rl.png
  app/assets/images/icons/brand-icons/icn-teams.svg
  app/assets/images/icons/brand-icons/icn-upload.svg
  app/assets/images/logos/kong-konnect-logo.svg
  app/assets/images/products/konnect/getting-started/konnect-gateway-entities.png
  app/konnect/api-products/productize-service.md
  app/konnect/architecture.md
  app/konnect/dev-portal/publish-service.md
  app/konnect/gateway-manager/deploy-service.md
  app/konnect/getting-started/access-account.md
  app/konnect/getting-started/add-api.md
  app/konnect/getting-started/app-registration.md
  app/konnect/getting-started/configure-data-plane-node.md
  app/konnect/getting-started/import.md
  app/konnect/getting-started/index.md
  app/konnect/index.md
  app/konnect/updates.md
Labels: review:copyedit, pending:release

#6997 chore: Fix broken links
  app/_data/tables/version_errors_konnect.yml
  app/_src/gateway/breaking-changes/30x.md
  app/_src/gateway/upgrade-v3.md
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation, skip-changelog

#6855 Feat: Appreg v2 updates
  .github/styles/kong/dictionary.txt
  app/_api/konnect/application-auth-strategies/_index.md
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_oas_data.json
  app/_redirects
  app/konnect/dev-portal/access-and-approval/manage-app-connections.md
  app/konnect/dev-portal/access-and-approval/manage-app-reg-requests.md
  app/konnect/dev-portal/access.md
  app/konnect/dev-portal/applications/application-overview.md
  app/konnect/dev-portal/applications/dev-apps.md
  app/konnect/dev-portal/applications/dev-reg-app-service.md
  app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
  app/konnect/dev-portal/applications/dynamic-client-registration/azure.md
  app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
  app/konnect/dev-portal/applications/dynamic-client-registration/index.md
  app/konnect/dev-portal/applications/dynamic-client-registration/okta.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/getting-started/app-registration.md
  app/konnect/updates.md
Labels: review:general, pending:release

#7002 Revert "Feat: Appreg v2 updates"
  .github/styles/kong/dictionary.txt
  app/_api/konnect/application-auth-strategies/_index.md
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_oas_data.json
  app/_redirects
  app/konnect/dev-portal/access-and-approval/manage-app-connections.md
  app/konnect/dev-portal/access-and-approval/manage-app-reg-requests.md
  app/konnect/dev-portal/access.md
  app/konnect/dev-portal/applications/application-overview.md
  app/konnect/dev-portal/applications/dev-apps.md
  app/konnect/dev-portal/applications/dev-reg-app-service.md
  app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
  app/konnect/dev-portal/applications/dynamic-client-registration/azure.md
  app/konnect/dev-portal/applications/dynamic-client-registration/curity.md
  app/konnect/dev-portal/applications/dynamic-client-registration/index.md
  app/konnect/dev-portal/applications/dynamic-client-registration/okta.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/getting-started/app-registration.md
  app/konnect/updates.md
Labels: review:general, skip-changelog

#7005 document HTTP/2 compatibility breaking change for 3.6
  .github/styles/kong/dictionary.txt
  app/_src/gateway/breaking-changes/36x.md
Labels: review:copyedit

#6948 docs(mesh): update MeshGlobalRateLimit and MeshOPA targetref support table
  app/_src/mesh/features/meshglobalratelimit.md
  app/_src/mesh/features/meshopa.md
Labels: review:general

#7008 chore: Fix OS EOLs in Gateway support matrix
  app/_data/tables/support/gateway/packages.yml
  app/_data/tables/support/gateway/versions/28.yml
  app/_data/tables/support/gateway/versions/32.yml
  app/_data/tables/support/gateway/versions/33.yml
  app/_data/tables/support/gateway/versions/34.yml
  app/_data/tables/support/gateway/versions/35.yml
  app/_data/tables/support/gateway/versions/36.yml
Labels: review:general

#7010 Chore: add deprecation policy statement
  app/_includes/md/support-policy.md
  app/_src/gateway/support/index.md
Labels: review:general

#7012 chore: Add step to stop kong before uninstalling
  app/_src/gateway/install/linux/amazon-linux.md
  app/_src/gateway/install/linux/debian.md
  app/_src/gateway/install/linux/rhel.md
  app/_src/gateway/install/linux/ubuntu.md
Labels: review:general

#7004 Chore: Move Gateway 3.2 to sunset versions
  app/_src/gateway/support/browser.md
  app/_src/gateway/support/index.md
  app/_src/gateway/support/third-party.md
Labels: do not merge, review:general

#6983 Fix: replace benchmark redirect with moved url entry
  app/_redirects
  app/moved_urls.yml
Labels: review:general

#6905 deck file kong2kic docs
  app/_data/docs_nav_deck_1.35.x.yml
  app/_includes/md/deck-reference-links.md
  app/_src/deck/index.md
  app/_src/deck/reference/deck_file_kong2kic.md
  app/_src/deck/use-case.md
Labels: review:sme, ci:manual-approve:generated-files

#7015 Release: decK 1.35
  app/_data/docs_nav_deck_1.36.x.yml
  app/_data/kong_versions.yml
Labels: review:general

#7000 Chore: Convert diagrams to mermaid.js
  app/_plugins/blocks/mermaid.rb
  app/_src/gateway/get-started/load-balancing.md
  app/_src/gateway/get-started/services-and-routes.md
  app/_src/gateway/migrate-cassandra-to-postgres.md
  app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md
  app/assets/images/logos/kogo-white.svg
  app/konnect/gateway-manager/control-plane-groups/index.md
Labels: review:general, skip-changelog

#7016 Fix: Consumer groups links and descriptions
  app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
  app/_src/gateway/kong-enterprise/index.md
Labels: review:copyedit

#7017 Fix: Stray month in changelog
  app/konnect/updates.md
Labels: review:general, skip-changelog

#6934 Chore: spec endpoint links open in new tab
  app/_src/gateway/admin-api/index_latest.md
Labels: review:general, skip-changelog

#7019 fix: Typos in oidc for kong manager doc
  app/_src/gateway/kong-manager/auth/oidc/configure.md
Labels: review:general, skip-changelog

#7007 Fix: Delete Kong prevention plugin directory and update metadata show compatibility with Konnect
  app/_hub/nonamesecurity/nonamesecurity-kongprevention/_metadata.yml
  app/_hub/nonamesecurity/nonamesecurity-kongprevention/examples/_index.yml
  app/_hub/nonamesecurity/nonamesecurity-kongprevention/overview/_index.md
  app/_hub/nonamesecurity/nonamesecurity-kongprevention/schemas/_index.json
  app/_hub/nonamesecurity/nonamesecurity-kongtrafficsource/_metadata.yml
  app/_hub/nonamesecurity/nonamesecurity-kongtrafficsource/overview/_index.md
  app/assets/images/icons/hub/nonamesecurity_nonamesecurity-kongtrafficsource.png
Labels: review:general
