Repository Kong/docs.konghq.com, pull requests merged in 2024-06, with the labels that each got.

#7453 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7457 Fix Terraform example generation
  app/_includes/plugins/hub-examples/terraform.html
  app/_plugins/drops/plugins/examples/terraform.rb
  app/_plugins/drops/plugins/hub_examples.rb
Labels: review:tech

#7325 chore(kgo): add version support matrix
  app/_data/docs_nav_kgo_1.0.x.yml
  app/_data/docs_nav_kgo_1.1.x.yml
  app/_data/docs_nav_kgo_1.2.x.yml
  app/_data/docs_nav_kgo_1.3.x.yml
  app/_data/kong_versions.yml
  app/_plugins/tags/support_policy_tag.rb
  app/_src/gateway-operator/support.md
  app/_src/gateway-operator/version-compatibility.md
Labels: Kubernetes Team, review:general

#7461 fix(changelog): correct broken link
  app/gateway/changelog.md
Labels: review:general

#7436 doc(*): update api docs and added missing the API of groups
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:copyedit, skip-changelog

#7459 Fix link to Go plugin examples
  app/_src/gateway/plugin-development/pluginserver/go.md
Labels: review:general, review:copyedit

#7428 Fixes reversed descriptions of post and put.
  app/_hub/kong-inc/acl/_api.md
Labels: review:tech

#7405 Feat: integrated markdown feature update
  app/konnect/api-products/service-documentation.md
  app/konnect/updates.md
Labels: review:general

#7455 feat(rate-limiting): add the doc for the added interface in rate-limiting library
  app/_src/gateway/reference/rate-limiting.md
Labels: review:general

#7441 feat: Document Request ID in debugging, tracing, and logging
  .github/styles/kong/dictionary.txt
  app/_src/gateway/production/debug-request.md
  app/_src/gateway/production/logging/log-reference.md
  app/_src/gateway/production/tracing/index.md
Labels: review:copyedit

#7466 Release: decK 1.37 and 1.38
  app/_data/docs_nav_deck_1.38.x.yml
  app/_data/docs_nav_deck_1.39.x.yml
  app/_data/kong_versions.yml
  app/_src/deck/reference/deck_file_add-plugins.md
  app/_src/deck/reference/deck_file_openapi2kong.md
  app/_src/deck/reference/deck_gateway_validate.md
  app/_src/deck/reference/deck_validate.md
Labels: review:general

#7464 Fix: Move Ubuntu install distro note into steps
  app/_src/gateway/install/linux/ubuntu.md
Labels: review:general

#7327 Feat: Plugin examples
  app/assets/hub/kong-inc/ai-proxy/anthropic.yaml
  app/assets/hub/kong-inc/ai-proxy/azure.yaml
  app/assets/hub/kong-inc/ai-proxy/cohere.yaml
  app/assets/hub/kong-inc/ai-proxy/llama2.yaml
  app/assets/hub/kong-inc/ai-proxy/mistral.yaml
  app/assets/hub/kong-inc/ai-proxy/openai.yaml
  app/assets/hub/kong-inc/http-log/splunk.yaml
  app/assets/hub/kong-inc/openid-connect/auth0.yaml
  app/assets/hub/kong-inc/openid-connect/azure-ad.yaml
  app/assets/hub/kong-inc/openid-connect/cognito.yaml
  app/assets/hub/kong-inc/openid-connect/curity.yaml
  app/assets/hub/kong-inc/openid-connect/google.yaml
  app/assets/hub/kong-inc/openid-connect/okta.yaml
  app/assets/hub/kong-inc/rate-limiting-advanced/fixed-window-200-requests-per-30-min.yaml
  app/assets/hub/kong-inc/rate-limiting-advanced/fixed-window-500-requests-per-hour.yaml
  app/assets/hub/kong-inc/rate-limiting-advanced/fixed-window-5000-requests-per-day.yaml
  app/assets/hub/kong-inc/rate-limiting-advanced/sliding-window-100-requests-per-hour.yaml
  app/assets/hub/kong-inc/rate-limiting-advanced/sliding-window-300-requests-per-30-min.yaml
  app/assets/hub/kong-inc/rate-limiting-advanced/sliding-window-500-requests-per-hour.yaml
Labels: review:tech

#7472 Chore: Convert codeblock diagrams into mermaid format
  app/_hub/kong-inc/websocket-size-limit/overview/_index.md
  app/_hub/kong-inc/websocket-validator/overview/_index.md
Labels: review:general

#7473 docs(changelog): correct the page subject to kong gateway enterprise …
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation, skip-changelog

#7483 Add gateway-38 repo keys
  app/_data/installation/gateway.yml
Labels: review:general

#7352 chore(kic): list all CRDs that supports konghq.com/plugins annotation
  app/_includes/md/kic/crd-ref/kong_plugin_description.md
  app/_src/kubernetes-ingress-controller/concepts/annotations.md
  app/_src/kubernetes-ingress-controller/concepts/custom-resources.md
  app/_src/kubernetes-ingress-controller/reference/annotations.md
Labels: Kubernetes Team, review:general

#7468 docs(kic): explicitly document SanitizeKonnectConfigDumps
  .github/styles/kong/dictionary.txt
  app/_src/kubernetes-ingress-controller/reference/feature-gates.md
Labels: Kubernetes Team, review:general

#7489 chore: Set up unreleased 3.8 version
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_data/kong_versions.yml
  app/_data/tables/support/gateway/versions/38.yml
  app/_src/gateway/breaking-changes/38x.md
  app/_src/gateway/support/index.md
  app/_src/gateway/support/third-party.md
Labels: review:general

#7484 Fix: Typo in JWT mapping order and clarify behavior
  app/_hub/kong-inc/jwt-signer/overview/_index.md
Labels: review:copyedit

#6817 Update: Document Admin API endpoints used by decK
  app/_src/deck/guides/kong-enterprise.md
  app/_src/deck/reference/entities.md
Labels: review:copyedit, review:sme

#7351 kic: document newly added `konghq.com/headers-separator` annotation
  app/_src/kubernetes-ingress-controller/reference/annotations.md
Labels: Kubernetes Team, review:general, area/docs

#7486 docs(kic 3.2) add guide page for example in configuring custom entity
  .github/styles/kong/auto-ignore.txt
  app/_data/docs_nav_kic_3.2.x.yml
  app/_src/kubernetes-ingress-controller/guides/customize/image.md
  app/_src/kubernetes-ingress-controller/guides/services/custom-entity.md
Labels: Kubernetes Team, review:general

#7432 Release: Gateway 3.4.3.9
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7470 fix: Table that expresses all HTTP responses returned by the admin API
  app/_src/gateway/admin-api/index_latest.md
Labels: review:general

#7492 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7467 docs(kic): update observability references for fallback config feature
  .github/styles/kong/auto-ignore.txt
  app/_src/kubernetes-ingress-controller/production/observability/events.md
  app/_src/kubernetes-ingress-controller/production/observability/prometheus.md
Labels: Kubernetes Team, review:general, area/docs

#7469 docs(kic): update rewrite-host guide with URLRewrite filter
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_kic_3.0.x.yml
  app/_data/docs_nav_kic_3.1.x.yml
  app/_data/docs_nav_kic_3.2.x.yml
  app/_includes/md/kic/http-test-routing-resource.md
  app/_src/kubernetes-ingress-controller/guides/requests/rewrite-host-and-paths.md
  app/moved_urls.yml
Labels: Kubernetes Team, review:general

#7496 Fix: Replace list of consumer groups plugins with link
  app/_src/gateway/kong-manager/consumer-groups.md
Labels: review:copyedit

#7463 docs(kic): fallback configuration guide
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_kic_3.2.x.yml
  app/_src/kubernetes-ingress-controller/guides/high-availability/fallback-config.md
Labels: Kubernetes Team, review:general, review:copyedit

#7497 docs(kic): update version compatibilities of KIC 3.2
  app/_src/kubernetes-ingress-controller/reference/version-compatibility.md
Labels: Kubernetes Team, review:general

#7504 Fix: Remove extra word in plugin metadata
  app/_hub/TheLEGOGroup/aws-request-signing/_metadata/_index.yml
Labels: review:general

#7513 chore: Replace Kuma with AI Gateway in top nav
  app/_data/docs_top_nav.yml
Labels: review:general, skip-changelog

#7501 docs(kic): update about gRPC routing
  app/_src/kubernetes-ingress-controller/guides/services/grpc.md
Labels: Kubernetes Team, review:general, area/gateway-api

#7515 Fix DockerHub links in Docker custom image instructions
  app/_src/gateway/install/docker/build-custom-images.md
Labels: review:general

#7516 fix: enable config dumps in fallback guide
  app/_src/kubernetes-ingress-controller/guides/high-availability/fallback-config.md
Labels: review:general, area/docs

#7514 Update okta-idp.md
  app/konnect/org-management/okta-idp.md
Labels: review:sme

#7500 Add Konnect Terraform reference page
  app/_data/docs_nav_konnect.yml
  app/konnect/reference/terraform.md
Labels: review:general

#7518 Chore: Remove beta label from Admin API specs
  app/_data/konnect_oas_data.json
  app/_src/gateway/admin-api/index_latest.md
  app/konnect/api/index.md
Labels: review:general

#7519 Fix: fix 3.7 naming convention
  app/_data/konnect_oas_data.json
Labels: review:general, skip-changelog

#7517 Fix: Fix rendering on version compatibility table
  app/_src/kic-v2/references/version-compatibility.md
Labels: review:general, skip-changelog

#7522 Fix: typo in OIDC doc
  app/_src/kubernetes-ingress-controller/plugins/oidc.md
Labels: review:general, skip-changelog

#7534 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7542 Remove -alpine in the image tag
  app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Labels: review:general

#7540 GRPCRoute is no longer experimental
  app/_includes/md/kic/prerequisites.md
  app/_src/kubernetes-ingress-controller/guides/services/grpc.md
Labels: review:general

#7523 Fix: Adjust description for consumer scoped plugin limitation
  app/_src/gateway/kong-enterprise/plugin-ordering/index.md
Labels: review:copyedit

#7524 Update: Clarify that `/debug` doesn't work for DPs
  app/_src/gateway/production/logging/update-log-level-dynamically.md
Labels: review:copyedit

#7495 Fix: Use consistent/accurate product name for Google Cloud/GCP secret manager and HashiCorp
  api-specs/Gateway-EE/3.3/kong-ee-3.3.json
  api-specs/Gateway-EE/3.3/kong-ee-3.3.yaml
  api-specs/Gateway-EE/3.4/kong-ee-3.4.json
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
  api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
  api-specs/Gateway-OSS/3.3/kong-oss-33.json
  api-specs/Gateway-OSS/3.3/kong-oss-33.yaml
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.json
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
  api-specs/Gateway-OSS/3.5/kong-oss-3.5.yaml
  api-specs/Gateway-OSS/3.6/kong-oss-3.6.yaml
  api-specs/Gateway-OSS/latest/kong-oss.yaml
  app/_data/docs_nav_gateway_2.8.x.yml
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_data/tables/support/gateway/third-party.yml
  app/_src/gateway/admin-api/admin-api-3.0.x.md
  app/_src/gateway/admin-api/admin-api-3.1.x.md
  app/_src/gateway/admin-api/index.md
  app/_src/gateway/breaking-changes/37x.md
  app/_src/gateway/kong-enterprise/index.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/gcp-sm.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/index.md
  app/_src/gateway/kong-enterprise/secrets-management/how-to/aws-secrets-manager.md
  app/_src/gateway/kong-enterprise/secrets-management/index.md
  app/_src/gateway/kong-enterprise/secrets-management/secrets-rotation.md
  app/_src/gateway/reference/configuration/configuration-3.0-3.3.md
  app/_src/gateway/reference/configuration/configuration-3.4.x.md
  app/_src/gateway/reference/configuration/configuration-3.5.x.md
  app/_src/gateway/reference/configuration/configuration-3.6.x.md
  app/_src/gateway/reference/configuration/configuration-3.7.x.md
  app/_src/kubernetes-ingress-controller/guides/security/kong-vault.md
  app/gateway/2.8.x/admin-api/index.md
  app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/gcp-sm.md
  app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/hashicorp-vault.md
  app/gateway/2.8.x/plan-and-deploy/security/secrets-management/backends/index.md
  app/gateway/2.8.x/plan-and-deploy/security/secrets-management/index.md
  app/gateway/changelog.md
  app/konnect/gateway-manager/configuration/vaults/index.md
Labels: review:general, ci:manual-approve:link-validation, ci:prevent-merge:generated-files, ci:check-skipped:generated-files

#7525 Release: Gateway 3.7.1.0
  app/_data/kong_versions.yml
  app/_hub/kong-inc/request-validator/_changelog.md
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7527 Release: Gateway 3.6.1.5
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7528 Release: Gateway 3.5.0.5
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7529 Release: Gateway 3.4.3.10
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit

#7530 Release: Gateway 2.8.4.10
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7556 Fix: instead of Update Cluster Config should be Edit or Resize Cluster
  app/konnect/gateway-manager/data-plane-nodes/upgrade.md
Labels: review:general

#7549 fix(dpop): ambiguity of key validation description
  app/_hub/kong-inc/openid-connect/how-to/_demonstrating-proof-of-possession.md
Labels: review:tech

#7559 Update distribution.md
  app/_src/gateway/plugin-development/distribution.md
Labels: review:general

#7465 TD: Update Plugins overview page
  app/_includes/md/about-plugins.md
  app/_src/gateway/glossary.md
Labels: review:copyedit

#7568 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7570 Release: Gateway 3.7.1.1
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7571 Release: Gateway 3.6.1.6
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7572 Release: Gateway 3.5.0.6
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7573 Release: Gateway 3.4.3.11
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#7574 Release: Gateway 2.8.4.11
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#7575 Fix: GW changelog heading levels
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#7562 Fix: JavaScript PDK page title
  app/_src/gateway/plugin-development/pluginserver/javascript.md
Labels: review:general

#7506 docs(workspaces): add description about entities that have no workspaces or should be unique across workspaces.
  app/_src/gateway/kong-enterprise/workspaces/index.md
Labels: review:general

#7550 fix(ai-proxy): fix several configs in docs
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_llama2.md
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_mistral.md
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_openai.md
  app/assets/hub/kong-inc/ai-proxy/llama2.yaml
  app/assets/hub/kong-inc/ai-proxy/mistral.yaml
  app/assets/hub/kong-inc/ai-proxy/openai.yaml
Labels: review:general

#7576 chore(release): docs for KGO 1.3.0
  app/_data/kong_versions.yml
  app/_src/gateway-operator/reference/cli-arguments/1.3.x.md
  app/_src/gateway-operator/reference/custom-resources/1.3.x.md
  app/_src/gateway-operator/reference/version-compatibility.md
  app/gateway-operator/changelog.md
Labels: Kubernetes Team, review:tech, area/docs

#7586 fix: Gateway install on GKE
  app/_includes/md/k8s/single-ingress.md
Labels: review:general

#7231 docs(mesh)[SEC-1079]: Mesh SLSA build provenance and image signatures for verification
  app/_data/docs_nav_mesh_2.7.x.yml
  app/_data/docs_nav_mesh_2.8.x.yml
  app/_data/tables/features/mesh.yml
  app/_src/gateway/kong-enterprise/provenance-verification.md
  app/_src/mesh/features/index.md
  app/_src/mesh/features/provenance-verification-binaries.md
  app/_src/mesh/features/provenance-verification-images.md
  app/_src/mesh/features/signed-images.md
  app/_src/mesh/sbom.md
Labels: ready, review:general, area/docs

#7587 Add missing : to if_version tags in KIC docs
  app/_src/kubernetes-ingress-controller/guides/requests/rewrite-host-and-paths.md
Labels: review:general

#7589 add workspaces_ and fix a formatting issue to EE admin API
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:general, skip-changelog

#7585 Feat: decK gateway CLI
  app/_data/docs_nav_deck_1.28.x.yml
  app/_data/docs_nav_deck_1.29.x.yml
  app/_data/docs_nav_deck_1.30.x.yml
  app/_data/docs_nav_deck_1.34.x.yml
  app/_data/docs_nav_deck_1.35.x.yml
  app/_data/docs_nav_deck_1.36.x.yml
  app/_data/docs_nav_deck_1.37.x.yml
  app/_data/docs_nav_deck_1.38.x.yml
  app/_data/docs_nav_deck_1.39.x.yml
  app/_hub/kong-inc/pre-function/how-to/_index.md
  app/_includes/md/gateway/db-less-upgrade.md
  app/_src/deck/design-architecture.md
  app/_src/deck/faqs.md
  app/_src/deck/guides/apiops.md
  app/_src/deck/guides/backup-restore.md
  app/_src/deck/guides/best-practices.md
  app/_src/deck/guides/ci-driven-configuration.md
  app/_src/deck/guides/deduplicate-plugin-configuration.md
  app/_src/deck/guides/defaults-v2.md
  app/_src/deck/guides/defaults.md
  app/_src/deck/guides/distributed-configuration.md
  app/_src/deck/guides/environment-variables.md
  app/_src/deck/guides/getting-started.md
  app/_src/deck/guides/kong-enterprise.md
  app/_src/deck/guides/konnect.md
  app/_src/deck/guides/multi-file-state.md
  app/_src/deck/guides/run-with-docker-1.28.md
  app/_src/deck/guides/vaults.md
  app/_src/deck/reference/deck_gateway_diff.md
  app/_src/deck/reference/deck_gateway_sync.md
  app/_src/deck/reference/deck_gateway_validate.md
  app/_src/gateway/breaking-changes/30x.md
  app/_src/gateway/kong-enterprise/plugin-ordering/get-started.md
  app/_src/gateway/migrate-cassandra-to-postgres.md
  app/_src/gateway/upgrade-v3.md
  app/_src/gateway/upgrade/backup-and-restore.md
  app/konnect/dev-portal/troubleshoot/index.md
  app/konnect/gateway-manager/backup-restore.md
  app/konnect/gateway-manager/control-plane-groups/conflicts.md
  app/konnect/gateway-manager/control-plane-groups/migrate.md
  app/konnect/gateway-manager/declarative-config.md
Labels: review:copyedit, ci:check-skipped:generated-files
