Repository Kong/docs.konghq.com, pull requests merged in 2024-09, with the labels that each got.

#7819 Fix: broken table in Konnect SSO doc
  app/konnect/org-management/sso.md
Labels: review:general, skip-changelog

#7747 docs(json-threat-protection): add docs for json-threat-protection plugin
  app/_hub/kong-inc/json-threat-protection/_changelog.md
  app/_hub/kong-inc/json-threat-protection/_metadata/_index.yml
  app/_hub/kong-inc/json-threat-protection/overview/_index.md
  app/_hub/kong-inc/json-threat-protection/versions.yml
  app/assets/images/icons/hub/kong-inc_json-threat-protection.png
Labels: review:general

#7787 Chore: Cloud launchers deprecation announcement
  app/konnect/gateway-manager/data-plane-nodes/index.md
  app/konnect/updates.md
Labels: do not merge, review:general, skip-changelog

#7822 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7829 Fix: Konnect example in mtls plugin
  app/_hub/kong-inc/mtls-auth/how-to/_add-cert-authorities.md
Labels: review:general

#7827 chore: Update banner CTA text
  app/_includes/nav-v2.html
Labels: review:copyedit, skip-changelog

#7830 Fix: Errors in mTLS Auth examples
  app/_hub/kong-inc/mtls-auth/how-to/_add-cert-authorities.md
Labels: review:general

#7836 Fix: note in data plane nodes doc
  app/konnect/gateway-manager/data-plane-nodes/index.md
Labels: review:general, skip-changelog

#7835 feat(gateway): document keyring license encryption for 3.8
  app/_src/gateway/kong-enterprise/db-encryption.md
Labels: review:general, review:copyedit

#7778 update latest patches of KIC
  app/_data/kong_versions.yml
Labels: Kubernetes Team, review:general

#7841 Fix: HMAC signing string in plugin example
  app/_hub/kong-inc/hmac-auth/overview/_index.md
Labels: review:general

#7842 Fix: Key set examples
  app/_src/gateway/reference/key-management.md
Labels: review:general

#7843 Fix: Consumer groups versioned links
  app/_redirects
  app/_src/gateway/kong-enterprise/consumer-groups/index.md
  app/_src/gateway/kong-manager/consumer-groups.md
Labels: review:general

#7844 Fix: Links to Konnect APIs
  app/konnect/gateway-manager/configuration/index.md
Labels: review:general, ci:manual-approve:link-validation

#7846 Update performance-testing.md for 3.8 rc2
  app/_src/gateway/production/performance/performance-testing.md
Labels: review:general

#7825 docs(admins): update the admin's API.
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:copyedit

#7818 chore: 3.8 breaking changes
  app/_src/gateway/breaking-changes/38x.md
Labels: review:copyedit

#7773 docs[confluent]: add docs for new confluent plugin
  app/_hub/kong-inc/confluent/_changelog.md
  app/_hub/kong-inc/confluent/_metadata/_index.yml
  app/_hub/kong-inc/confluent/overview/_index.md
  app/_hub/kong-inc/confluent/versions.yml
  app/assets/images/icons/hub/kong-inc_confluent.png
Labels: review:sme

#7786 Chore: PDK and CLI docs for Gateway 3.8
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_src/gateway/plugin-development/pdk/kong.client.md
  app/_src/gateway/plugin-development/pdk/kong.client.tls.md
  app/_src/gateway/plugin-development/pdk/kong.request.md
  app/_src/gateway/plugin-development/pdk/kong.service.md
  app/_src/gateway/plugin-development/pdk/kong.service.request.md
  app/_src/gateway/plugin-development/pdk/kong.telemetry.log.md
  app/_src/gateway/reference/cli.md
Labels: review:general, ci:manual-approve:generated-files, skip-changelog

#7845 fix: Remove AI RLA plugin from traffic control category on plugin hub
  app/_hub/kong-inc/ai-rate-limiting-advanced/_metadata/_index.yml
Labels: review:general

#7834 Chore: Generate the 3.8.x config reference
  app/_src/gateway/reference/configuration/configuration-3.8.x.md
Labels: review:general, skip-changelog

#7772 docs(*): added missing endpoints and tags for 3.3 and 3.4
  api-specs/Gateway-EE/3.3/kong-ee-3.3.json
  api-specs/Gateway-EE/3.3/kong-ee-3.3.yaml
  api-specs/Gateway-EE/3.4/kong-ee-3.4.json
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
  api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:copyedit

#7854 Revert "docs(admins): update the admin's API."
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:copyedit

#7850 Fix: AWS Lambda plugin changelog entry for base64_encode_body
  app/_hub/kong-inc/aws-lambda/_changelog.md
Labels: review:copyedit

#7858 Fix: Event hooks missing delete
  api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml
  api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:general, skip-changelog

#7860 Fix: Add a third option to close your Plus or Enterprise account
  app/konnect/org-management/deactivation.md
Labels: review:general

#7848 Fix: Exit Transformer plugin handle_unknown description
  app/_hub/kong-inc/exit-transformer/overview/_index.md
Labels: review:copyedit

#7864 docs(consumer_groups): add prefix `/{workspace}` for consumer_groups's endpoint in 3.3 and 3.4
  api-specs/Gateway-EE/3.3/kong-ee-3.3.json
  api-specs/Gateway-EE/3.3/kong-ee-3.3.yaml
  api-specs/Gateway-EE/3.4/kong-ee-3.4.json
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
Labels: review:copyedit

#7861 Feat: AppD analytics_enable
  app/_hub/kong-inc/app-dynamics/overview/_index.md
Labels: review:copyedit, review:sme

#7868 Chore: Update link to kong.conf in 3.8 nav file
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_src/gateway/reference/configuration/configuration-3.8.x.md
Labels: review:general, skip-changelog

#7775 Feat: Header Cert Auth plugin
  app/_hub/kong-inc/header-cert-auth/_changelog.md
  app/_hub/kong-inc/header-cert-auth/_metadata/_index.yml
  app/_hub/kong-inc/header-cert-auth/how-to/_add-cert-authorities.md
  app/_hub/kong-inc/header-cert-auth/how-to/_aws-alb-integration.md
  app/_hub/kong-inc/header-cert-auth/how-to/_manual-mapping-cert-consumers.md
  app/_hub/kong-inc/header-cert-auth/overview/_index.md
  app/_hub/kong-inc/header-cert-auth/versions.yml
  app/assets/images/icons/hub/kong-inc_header-cert-auth.png
Labels: review:copyedit

#7873 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7762 feat(aws): add custom sts endpoint configuration field for various aws features in kong gateway
  app/_src/gateway/kong-enterprise/aws-iam-auth-to-rds-database.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
Labels: review:tech, review:general

#7877 Update: Konnect resource limits note
  app/konnect/gateway-manager/configuration/index.md
Labels: review:copyedit

#7871 chore: upgrade paths for 3.8
  app/_includes/md/gateway/upgrade-paths.md
Labels: review:general

#7880 Fix: Correct the URL for Nginx proxy_next_upstream property
  app/_src/gateway/how-kong-works/routing-traffic.md
Labels: review:general

#7808 Feat: Standard Webhooks plugin
  app/_hub/kong-inc/standard-webhooks/_changelog.md
  app/_hub/kong-inc/standard-webhooks/_metadata/_index.yml
  app/_hub/kong-inc/standard-webhooks/overview/_index.md
  app/_hub/kong-inc/standard-webhooks/versions.yml
  app/assets/images/icons/hub/kong-inc_standard-webhooks.png
Labels: do not merge, review:sme

#7879 Chore: Update changelog entries
  app/konnect/updates.md
  tools/beamer/fetch-beamer-posts.js
Labels: review:general, skip-changelog

#7878 Fix: broken links
  .ruby-version
  app/_hub/kong-inc/mtls-auth/how-to/_manual-mapping-cert-consumers.md
  app/contributing/variables.md
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation, skip-changelog

#7805 Feat: New DNS client for Gateway 3.8
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_src/gateway/migrate-to-new-dns-client.md
  app/_src/gateway/production/networking/dns-considerations.md
  app/_src/gateway/production/performance/benchmark.md
Labels: review:general

#7814 Feat: Upstream Oauth plugin
  app/_hub/kong-inc/upstream-oauth/_changelog.md
  app/_hub/kong-inc/upstream-oauth/_metadata/_index.yml
  app/_hub/kong-inc/upstream-oauth/overview/_index.md
  app/_hub/kong-inc/upstream-oauth/versions.yml
  app/assets/images/icons/hub/kong-inc_upstream-oauth.png
Labels: review:copyedit, review:sme

#7884 Update: Add info about Header Cert Auth size limits
  app/_hub/kong-inc/header-cert-auth/overview/_index.md
Labels: review:copyedit

#7886 Update performance-testing.md for 3.8 rc4
  app/_src/gateway/production/performance/performance-testing.md
Labels: review:general

#7713 Feat/add ai semantic caching plugin
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md
  app/_hub/kong-inc/ai-semantic-cache/_changelog.md
  app/_hub/kong-inc/ai-semantic-cache/_metadata/_index.yml
  app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_mistral.md
  app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_openai.md
  app/_hub/kong-inc/ai-semantic-cache/overview/_index.md
  app/_hub/kong-inc/ai-semantic-cache/versions.yml
  app/_includes/md/ai-plugins-links.md
  app/_src/gateway/ai-gateway/index.md
  app/assets/images/icons/hub/kong-inc_ai-semantic-cache.png
Labels: review:copyedit

#7862 feat: Service Catalog Integrations landing page
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/_data/tables/konnect/integrations.yml
  app/_includes/service-catalog-discovery.html
  app/_includes/service-catalog-integrations.html
  app/assets/images/icons/third-party/github.svg
  app/assets/images/icons/third-party/pagerduty.svg
  app/assets/images/icons/third-party/traceable.svg
  app/konnect/service-catalog/integrations/github.md
  app/konnect/service-catalog/integrations/index.md
  app/konnect/service-catalog/integrations/pagerduty.md
  app/konnect/service-catalog/integrations/traceable.md
Labels: review:tech, review:general

#7891 Chore: update legal links
  app/_includes/footer.html
  app/konnect/org-management/deactivation.md
  app/konnect/updates.md
Labels: review:general

#7881 Feat: OTEL with Dynatrace + plugin doc refactor
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/opentelemetry/_metadata/_index.yml
  app/_hub/kong-inc/opentelemetry/how-to/_dynatrace.md
  app/_hub/kong-inc/opentelemetry/how-to/_getting-started.md
  app/_hub/kong-inc/opentelemetry/how-to/_spans.md
  app/_hub/kong-inc/opentelemetry/overview/_index.md
Labels: review:copyedit

#7894 Fix: Konnect changelog
  app/konnect/updates.md
Labels: review:general, skip-changelog

#7900 Fix: Traceable overview title
  app/_hub/traceableai/traceableai/overview/_index.md
Labels: review:general

#7901 Fix: Add missing prerequisites to AI semantic prompt guard plugin
  app/_hub/kong-inc/ai-semantic-prompt-guard/how-to/_index.md
Labels: review:general

#7817 Feat: AI proxy advanced
  app/_hub/kong-inc/ai-proxy-advanced/_changelog.md
  app/_hub/kong-inc/ai-proxy-advanced/_metadata/_index.yml
  app/_hub/kong-inc/ai-proxy-advanced/how-to/_cloud-provider-authentication.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/_sdk-usage.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/_streaming.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_anthropic.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_azure.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_cohere.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_llama2.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_mistral.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_openai.md
  app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md
  app/_hub/kong-inc/ai-proxy-advanced/versions.yml
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_azure.md
  app/_includes/md/plugins-hub/ai-providers-prereqs-advanced.md
  app/_src/gateway/ai-gateway/index.md
  app/assets/images/icons/hub/kong-inc_ai-proxy-advanced.png
Labels: review:copyedit, ci:manual-approve:link-validation, review:sme

#7890 feat: 3.8 tracked changes docs
  app/_data/tables/version_errors_konnect.yml
Labels: do not merge, review:general

#7897 Feat: premium partner badges and category
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/badges.less
  app/_hub/kong-inc/confluent/_metadata/_index.yml
  app/_hub/kong-inc/opentelemetry/how-to/_dynatrace.md
  app/_hub/traceableai/traceableai/_metadata/_index.yml
  app/_includes/hub_cards.html
  app/_includes/md/about-plugins.md
  app/_includes/plugins/badges.html
  app/_layouts/extension.html
  app/_layouts/plugins/show.html
  app/_plugins/drops/plugins/badges.rb
  app/_src/gateway/glossary.md
  app/hub/index.html
  docs/templates/partner-plugin-template/_metadata.yml
  jekyll-dev.yml
  jekyll.yml
Labels: review:general

#7903 Chore: Konnect changelog update
  app/konnect/updates.md
Labels: review:general

#7904 Fix: broken links in 3.8
  app/_hub/kong-inc/ai-semantic-cache/overview/_index.md
  app/_includes/md/ai-plugins-links.md
Labels: review:general, skip-changelog

#7870 Feat: Azure Vnet peering for Cloud Gateways
  app/_data/docs_nav_konnect.yml
  app/_includes/md/konnect/azure-peering.md
  app/konnect/gateway-manager/data-plane-nodes/azure-peering.md
Labels: review:general

#7832 Chore: Update Cloud Gateways geos
  app/konnect/gateway-manager/dedicated-cloud-gateways.md
  app/konnect/geo.md
Labels: review:general, skip-changelog

#7889 feat: Service Catalog
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/_data/tables/konnect/integrations.yml
  app/_includes/service-catalog-discovery.html
  app/_includes/service-catalog-integrations.html
  app/assets/images/icons/third-party/github.svg
  app/assets/images/icons/third-party/pagerduty.svg
  app/assets/images/icons/third-party/traceable.svg
  app/konnect/org-management/teams-and-roles/roles-reference.md
  app/konnect/org-management/teams-and-roles/teams-reference.md
  app/konnect/service-catalog/index.md
  app/konnect/service-catalog/integrations/github.md
  app/konnect/service-catalog/integrations/index.md
  app/konnect/service-catalog/integrations/pagerduty.md
  app/konnect/service-catalog/integrations/traceable.md
Labels: review:general

#7909 Automated Konnect changelog update [skip-ci]
  app/konnect/updates.md
Labels: review:general, skip-changelog

#7831 feat: Gemini and Bedrock for AI Proxy
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_data/tables/support/gateway/third-party.yml
  app/_data/tables/support/gateway/versions/38.yml
  app/_hub/kong-inc/ai-proxy-advanced/how-to/machine-learning-platform-integrations/gemini.md
  app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md
  app/_hub/kong-inc/ai-proxy/how-to/machine-learning-platform-integration-guides/gemini.md
  app/_hub/kong-inc/ai-proxy/overview/_index.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7910 Fix: Peering doc grammar
  app/konnect/gateway-manager/data-plane-nodes/azure-peering.md
Labels: review:general, skip-changelog

#7912 fix: adjust table widths
  app/hub/plugins/license-tiers.md
Labels: review:general, skip-changelog

#7913 feat: Bedrock docs for AI Proxy and AI Proxy Advanced
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_hub/kong-inc/ai-proxy-advanced/how-to/machine-learning-platform-integrations/bedrock.md
  app/_hub/kong-inc/ai-proxy/how-to/machine-learning-platform-integration-guides/bedrock.md
Labels: review:copyedit

#7907 Fix: OTEL + dynatrace feedback
  app/_hub/kong-inc/opentelemetry/how-to/_dynatrace.md
  app/_hub/kong-inc/opentelemetry/overview/_index.md
Labels: do not merge, review:copyedit, review:sme

#7847 Feat: Advanced AI Analytics
  app/assets/images/products/konnect/analytics/custom-reports/api-usage-by-application.png
  app/assets/images/products/konnect/analytics/custom-reports/kong-vs-upstream-latency.png
  app/assets/images/products/konnect/analytics/custom-reports/latency-payments-api-30.png
  app/assets/images/products/konnect/analytics/custom-reports/total-api-requests.png
  app/assets/images/products/konnect/analytics/custom-reports/total-usage-accounts-api-30.png
  app/assets/images/products/konnect/analytics/konnect-analytics-api-requests.png
  app/assets/images/products/konnect/analytics/konnect-api-usage-summary.png
  app/assets/images/products/konnect/analytics/konnect-explorer-dashboard.png
  app/assets/images/products/konnect/analytics/konnect-summary-dashboard.png
  app/konnect/analytics/explorer.md
  app/konnect/analytics/index.md
  app/konnect/analytics/use-cases.md
  app/konnect/updates.md
Labels: review:general

#7919 Fix: correct the Konnect compatibility of the JSON-Threat-Protection Plugin
  app/_hub/kong-inc/json-threat-protection/_metadata/_index.yml
Labels: review:general

#7914 Update: Plugin Hub cards show both EE and OSS when both are supported
  app/_plugins/drops/plugins/badges.rb
  spec/app/_plugins/drops/plugins/badges_spec.rb
Labels: review:general

#7911 fix: broken entity links
  app/_data/tables/version_errors_konnect.yml
Labels: review:general

#7920 Chore: Adjust badge spacing on hub landing page
  app/_assets/stylesheets/hub-landing-page.less
Labels: review:general

#7859 Add docker copy command to move cert and key into container before restarting the gateway
  app/konnect/gateway-manager/data-plane-nodes/renew-certificates.md
Labels: review:general

#7922 chore: disable summit hackathon banner
  app/_assets/entrypoints/application.js
  app/_assets/stylesheets/header.less
  app/_includes/nav-v2.html
Labels: review:general

#7925 Automated Konnect changelog update [skip-ci]
  app/konnect/updates.md
Labels: review:general, skip-changelog

#7915 Enable Terraform examples for all plugins
  app/_plugins/blocks/inline_plugin_example/config.rb
  app/_plugins/drops/plugins/examples/terraform.rb
  app/_plugins/drops/plugins/hub_examples.rb
  spec/app/_plugins/drops/plugins/example_spec.rb
Labels: review:tech

#7899 Documentation for new deck command kong2tf
  app/_data/docs_nav_deck_1.40.x.yml
  app/_data/docs_nav_deck_1.41.x.yml
  app/_data/kong_versions.yml
  app/_includes/md/deck-reference-links.md
  app/_src/deck/index.md
  app/_src/deck/reference/deck_file_kong2tf.md
Labels: review:general

#7923 Fix: broken command examples for running decK with Docker
  app/_src/deck/guides/run-with-docker-1.28.md
  app/_src/deck/guides/run-with-docker.md
Labels: review:copyedit

#7924 Update: 3.8 known issue for JSON threat protection plugin
  app/_hub/kong-inc/json-threat-protection/_changelog.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7929 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7921 Fix: AppD plugin missing info + broken collapsible note
  app/_hub/kong-inc/app-dynamics/overview/_index.md
  app/_layouts/extension.html
Labels: review:copyedit

#7933 Fix: Remove AI Semantic Cache plugin from traffic control category
  app/_hub/kong-inc/ai-semantic-cache/_metadata/_index.yml
Labels: review:general

#7936 Fix: Prometheus status code metrics description
  app/_hub/kong-inc/prometheus/overview/_index.md
Labels: review:general, skip-changelog

#7940 Fix: Add missing prerequisite for Rewrite URI annotation
  app/_src/kubernetes-ingress-controller/guides/requests/rewrite-annotation.md
Labels: review:general

#7932 fix: Convert to AI Semantic Cache LLM examples to `plugin_example`
  app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_mistral.md
  app/_hub/kong-inc/ai-semantic-cache/how-to/llm-provider-integration-guides/_openai.md
  app/contributing/kong-plugins.md
Labels: review:general

#7935 Chore: Clustering endpoints
  api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml
  api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
  api-specs/Gateway-OSS/3.6/kong-oss-3.6.yaml
  api-specs/Gateway-OSS/3.7/kong-oss-3.7.yaml
  api-specs/Gateway-OSS/latest/kong-oss.yaml
Labels: review:general, skip-changelog

#7948 Fix: Logging plugins log format + descriptions
  app/_hub/kong-inc/file-log/overview/_index.md
  app/_hub/kong-inc/kafka-log/overview/_index.md
  app/_hub/kong-inc/loggly/overview/_index.md
  app/_hub/kong-inc/syslog/overview/_index.md
  app/_hub/kong-inc/tcp-log/overview/_index.md
  app/_hub/kong-inc/udp-log/overview/_index.md
  app/_includes/md/plugins-hub/json-object-log.md
  app/_includes/md/plugins-hub/log-format.md
Labels: review:general

#7946 Chore: Add AI Gateway to sidebar dropdown
  app/_includes/docs-sidebar.html
Labels: review:general

#7945 Fix: Add missing `_APPD` to env variables
  app/_hub/kong-inc/app-dynamics/overview/_index.md
Labels: review:general

#7944 fix: decK latest version
  app/_data/kong_versions.yml
Labels: review:general, skip-changelog

#7926 chore: Add terraform tab to plugin_examples blocks
  app/_hub/kong-inc/acl/how-to/_consumer-groups.md.md
  app/_hub/kong-inc/ai-azure-content-safety/how-to/_index.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/_cloud-provider-authentication.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_anthropic.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_azure.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_cohere.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_llama2.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_mistral.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_openai.md
  app/_hub/kong-inc/ai-proxy/how-to/_cloud-provider-authentication.md
  app/_hub/kong-inc/http-log/how-to/_splunk.md
  app/_hub/kong-inc/openid-connect/how-to/_demonstrating-proof-of-possession.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_authorization-code-flow.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_client-credentials.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_introspection.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_jwt-access-token.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_kong-oauth-token.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_password-grant.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_refresh-token.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_session.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_user-info.md
  app/_hub/kong-inc/openid-connect/how-to/authorization/_acl.md
  app/_hub/kong-inc/openid-connect/how-to/authorization/_claims.md
  app/_hub/kong-inc/openid-connect/how-to/authorization/_consumer.md
  app/_hub/kong-inc/openid-connect/how-to/client-authentication/_mtls.md
  app/_hub/kong-inc/opentelemetry/how-to/_dynatrace.md
  app/_hub/kong-inc/opentelemetry/how-to/_getting-started.md
  app/_plugins/blocks/plugin_example.rb
Labels: review:general, skip-changelog

#7807 Chore: Third-party plugins template update
  docs/templates/partner-plugin-template/_metadata/_index.yml
Labels: review:general, skip-changelog

#7955 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7954 Update: Adjust decK Konnect flag phrasing to remove ambiguity
  app/_src/deck/guides/konnect.md
Labels: review:general

#7957 Update deck_file_kong2tf.md
  app/_src/deck/reference/deck_file_kong2tf.md
Labels: review:copyedit

#7942 Release: Gateway 2.8.4.13
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7777 Add `shared` to list of available substitution sources in _templates.md
  app/_hub/kong-inc/request-transformer/how-to/_templates.md
Labels: review:general

#7839 docs(kic): update metrics reference
  .github/styles/kong/auto-ignore.txt
  app/_src/kubernetes-ingress-controller/production/observability/prometheus.md
Labels: Kubernetes Team, review:general

#7962 Chore: Move CGW docs
  app/_data/docs_nav_konnect.yml
  app/_includes/md/konnect/konnect-architecture.md
  app/_redirects
  app/contributing/style-guide.md
  app/konnect/gateway-manager/dedicated-cloud-gateways/azure-peering.md
  app/konnect/gateway-manager/dedicated-cloud-gateways/index.md
  app/konnect/gateway-manager/dedicated-cloud-gateways/provision-cloud-gateway.md
  app/konnect/gateway-manager/dedicated-cloud-gateways/transit-gateways.md
  app/konnect/getting-started/index.md
Labels: review:general

#7961 Chore: remove orphaned dev portal RBAC topic
  app/_redirects
  app/konnect/api/portal-auth/portal-rbac-guide.md
Labels: review:general, skip-changelog

#7898 add introduction of --disable-consumer-sync in konnect KIC section
  app/konnect/gateway-manager/kic.md
Labels: Kubernetes Team, review:general

#7793 Add KIC failure mode page
  app/_data/docs_nav_kic_3.3.x.yml
  app/_src/kubernetes-ingress-controller/reference/failure-modes.md
Labels: Kubernetes Team, review:general

#7972 Chore: Update self-hosted portals
  app/konnect/dev-portal/customization/self-hosted-portal.md
Labels: review:general, skip-changelog

#7853 docs(kic): add konnect integration troubleshooting section
  app/_src/kubernetes-ingress-controller/reference/troubleshooting.md
Labels: review:general

#7928 fix(gateway/request-validator): mention format keyword only supported in draft4 version
  app/_hub/kong-inc/request-validator/overview/_index.md
Labels: review:general

#7979 Chore: Service Catalog beta tag
  app/konnect/service-catalog/index.md
  app/konnect/service-catalog/integrations/github.md
  app/konnect/service-catalog/integrations/index.md
  app/konnect/service-catalog/integrations/pagerduty.md
  app/konnect/service-catalog/integrations/traceable.md
Labels: review:general, skip-changelog

#7978 Chore: Set AI Semantic Prompt Guard as Konnect-compatible
  app/_hub/kong-inc/ai-semantic-prompt-guard/_metadata/_index.yml
Labels: review:general, skip-changelog

#7974 Fix: Mention Azure in last table entry
  app/konnect/gateway-manager/index.md
Labels: review:general

#7963 Chore: minor cleanup to moved API docs
  app/_src/gateway/production/clustering.md
  app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Labels: review:general, skip-changelog

#7982 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7983 fix(plugins): ai semantic prompt guard is EE-only
  app/_hub/kong-inc/ai-semantic-prompt-guard/_metadata/_index.yml
Labels: review:general
