Repository Kong/docs.konghq.com, pull requests merged in 2024-07, with the labels that each got.

#7592 Switch to mise for managing Ruby/Node versions
  .node-version
  Makefile
  docs/platform-install.md
Labels: review:tech, review:general

#7596 fix(ai-proxy): clarify model support
  app/_hub/kong-inc/ai-proxy/overview/_index.md
Labels: review:general

#7595 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7588 Update: DeGraphQL diagram
  app/_hub/kong-inc/degraphql/overview/_index.md
  app/assets/images/icons/third-party/graphql-logo.svg
Labels: review:general

#7512 Feat: Consumers key concept/reference page
  app/_assets/stylesheets/collapsible-sections.less
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_src/gateway/key-concepts/consumers.md
Labels: review:general, review:copyedit

#7598 Update default-ports.md
  app/_src/gateway/production/networking/default-ports.md
Labels: review:tech

#7590 Fix: GraphQL RLA example needs a warning to not run in prod
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_metadata/_index.yml
  app/_layouts/plugins/configuration_examples.html
  docs/templates/kong-plugin-template/_metadata/_index.yml
Labels: review:copyedit

#7606 feat(sdk): automated oas update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
  api-specs/Konnect/v2/yaml/control-planes.yaml
Labels: review:general

#7607 chore(rate-limiting): clarify rate-limiting accuracy
  app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
  app/_hub/kong-inc/rate-limiting/overview/_index.md
Labels: review:general

#7600 Feat: Konnect analytics ingestion toggle
  app/konnect/analytics/index.md
  app/konnect/updates.md
Labels: review:general, review:copyedit

#7617 Remove version from Terraform plugin examples
  app/_includes/plugins/hub-examples/terraform.html
Labels: review:general

#7622 Fix Ubuntu install script versions
  app/_src/gateway/install/linux/ubuntu.md
Labels: review:general

#7450 feat: add Dev Portal one pager for developers for
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/konnect/dev-portal/applications/dev-apps.md
  app/konnect/dev-portal/applications/dev-gen-creds.md
  app/konnect/dev-portal/dev-reg.md
  app/konnect/dev-portal/index.md
  app/konnect/dev-portal/register-and-create-app.md
Labels: review:copyedit

#7618 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7599 Add pagination to consumers and consumer_groups endpoints in Admin API specs
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
  api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:general

#7626 Fix: Vale ignored classes line.
  .vale.ini
Labels: review:general, skip-changelog

#7623 Chore: Documenting third-party tools instructions
  app/contributing/style-guide.md
Labels: review:general

#7621 feat(sdk): automated oas update
  api-specs/Konnect/v2/yaml/application-auth-strategies.yaml
  api-specs/portal.yaml
Labels: review:general

#7601 Release: Gateway 3.7.1.2
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7603 Release: Gateway 3.5.0.7
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7602 Release: Gateway 3.6.1.7
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7561 feat: Multi Dev Portal
  app/_data/docs_nav_konnect.yml
  app/konnect/api-products/productize-service.md
  app/konnect/dev-portal/access-and-approval/manage-app-reg-requests.md
  app/konnect/dev-portal/access-and-approval/manage-teams.md
  app/konnect/dev-portal/applications/enable-app-reg.md
  app/konnect/dev-portal/create-dev-portal.md
  app/konnect/dev-portal/customization/index.md
  app/konnect/dev-portal/index.md
  app/konnect/dev-portal/publish-service.md
  app/konnect/updates.md
Labels: review:general, review:sme

#7628 fix description about the execution order of the ai-request-transformer plugin
  app/_hub/kong-inc/ai-request-transformer/overview/_index.md
Labels: bug, review:tech, review:copyedit

#7630 chore: Move the plugins CTA into sidebar
  app/_assets/stylesheets/sidebar.less
  app/_includes/plugins/sidebar.html
  app/_layouts/extension.html
  spec/templates/plugin_with_versions_spec.rb
Labels: review:tech, review:general

#7636 feat(sdk): automated oas update
  api-specs/Konnect/v1/yaml/ksearch.yaml
  api-specs/Konnect/v2/yaml/api-products.yaml
  api-specs/Konnect/v2/yaml/portal-management.yaml
  api-specs/Konnect/v3/yaml/identity.yaml
Labels: review:general

#7635 Fix: Key Auth Encrypted note and "not applicable" konnect labels
  app/_hub/kong-inc/key-auth-enc/_metadata/_index.yml
  app/hub/plugins/compatibility/index.md
  app/konnect/compatibility.md
Labels: review:copyedit

#7639 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7634 Feat: Azure support in dedicated cloud gateways
  app/assets/images/products/konnect/gateway-manager/konnect-azure-cgw.png
  app/assets/images/products/konnect/gateway-manager/konnect-control-plane-cloud-gateway-wizard.png
  app/konnect/gateway-manager/dedicated-cloud-gateways.md
  app/konnect/gateway-manager/index.md
  app/konnect/updates.md
Labels: review:copyedit

#7637 fix(404): update link to plugin development guide
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_data/docs_nav_gateway_3.8.x.yml
Labels: review:general

#7611 Fix: An attempt at making our readme more concise
  README.md
  docs/autodocs.md
  docs/ci-cd.md
  docs/testing.md
  docs/troubleshooting/troubleshoot.md
Labels: review:general, skip-changelog

#7642 Fix: Updated kong-oss.yaml
  api-specs/Gateway-OSS/latest/kong-oss.yaml
Labels: review:general

#7647 Fix: Broken relative links in Okta IDP documentation
  app/konnect/org-management/okta-idp.md
Labels: review:general, skip-changelog

#7645 Fix: Make Service Catalog a variable
  app/_includes/md/gateway/deployment-topologies.md
  app/_includes/md/konnect/deployment-topologies.md
  app/_src/gateway/production/deployment-topologies/index.md
  app/contributing/word-choice.md
  app/konnect/index.md
  app/konnect/service-catalog/index.md
  app/konnect/servicehub/index.md
  app/konnect/updates.md
  jekyll-dev.yml
  jekyll.yml
Labels: review:general

#7646 Update _local-testing-development.md
  app/_hub/kong-inc/acme/how-to/_local-testing-development.md
Labels: review:general

#7663 fix: Add urls to the broken link checker's list of ignored_targets
  tools/broken-link-checker/config/ignored_targets.json
Labels: review:general, skip-changelog

#7660 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7664 Fixing small typo
  app/_src/gateway/production/performance/performance-testing.md
Labels: review:general

#7665 Linkify link to deduplicate guide
  app/_src/deck/guides/getting-started.md
Labels: review:general

#7653 Added fix information for HTTP/2 content length breaking change
  app/_src/gateway/breaking-changes/36x.md
Labels: review:general

#7667 Fix: Broken links
  app/_hub/kong-inc/ai-azure-content-safety/how-to/_index.md
  app/_includes/md/k8s/cloud/aks/install.md
  app/_src/kubernetes-ingress-controller/upgrade/kic.md
  app/contributing/kong-plugins.md
  app/contributing/partner-plugins.md
Labels: review:general, skip-changelog

#7656 Provide link to limitations of dynamic plugin ordering
  app/konnect/reference/plugins.md
Labels: review:copyedit

#7640 docs(mesh): add prod usage helm values
  app/_data/docs_nav_mesh_2.8.x.yml
  app/_data/docs_nav_mesh_2.9.x.yml
  app/_src/mesh/production/cp-deployment/production-usage-values.md
Labels: review:general

#7652 Fix: Add alt text to Kong Mesh diagrams
  app/_src/mesh/index.md
Labels: review:general

#7583 feat(observability): OpenTelemetry logs
  app/_hub/kong-inc/opentelemetry/overview/_index.md
Labels: review:general, review:copyedit

#7671 feat(sdk): automated oas update
  api-specs/Konnect/v3/yaml/identity.yaml
Labels: review:general

#7482 Adding migration guide for on-prem to konnect
  app/_data/docs_nav_konnect.yml
  app/_redirects
  app/_src/deck/guides/konnect.md
  app/konnect/dev-portal/access-and-approval/manage-teams.md
  app/konnect/gateway-manager/declarative-config.md
  app/konnect/getting-started/import.md
  app/konnect/getting-started/index.md
  app/konnect/getting-started/migration.md
  app/konnect/updates.md
Labels: review:general

#7673 Update migration.md
  app/konnect/getting-started/migration.md
Labels: review:general

#7650 chore: add more explanation for hashicorp vault's authentication and secret fetching
  app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
Labels: review:tech, review:general

#7675 fix(gateway/request-validator): update document
  app/_hub/kong-inc/request-validator/overview/_index.md
Labels: review:general

#7669 fix: Use inline if_version blocks
  app/_includes/md/admin-listen.md
  app/_includes/md/gateway/setup.md
Labels: review:general, skip-changelog

#7651 feat: add documentation about assume role support for rds iam authentication
  app/_src/gateway/kong-enterprise/aws-iam-auth-to-rds-database.md
Labels: review:tech, review:general

#7684 fix(changelog): fix some changelog entry related to lua-resty-healthcheck bump
  app/gateway/changelog.md
Labels: review:tech, review:general, ci:manual-approve:link-validation

#7685 adds idling_timeout session parameter
  app/_src/gateway/kong-manager/auth/sessions.md
Labels: review:general

#7683 Fix: wrong postgres key in plugin migrations examples
  app/_src/gateway/plugin-development/custom-entities.md
Labels: review:general

#7681 Update: Add API instructions for finding Konnect hostnames
  app/konnect/network.md
Labels: review:copyedit

#7677 AI Proxy plugin: fix incorrect format in example
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_mistral.md
Labels: review:general

#7676 Fix: Remove extra backslash
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_llama2.md
Labels: review:general

#7699 Update nginx-directives.md to list supported namespaces
  app/_src/gateway/reference/nginx-directives.md
Labels: review:copyedit

#7698 docs(mesh): update ECS env variables
  app/_src/mesh/installation/ecs.md
Labels: review:general, skip-changelog

#7701 (feat/refresh): added release notes for new refresh button
  app/konnect/updates.md
Labels: review:copyedit

#7702 License expiration adjustment
  app/_src/gateway/licenses/index.md
Labels: review:general

#7693 Release: Gateway 2.8.4.12
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7706 typo fix: availibilty to availability
  app/gateway/changelog.md
Labels: review:copyedit

#7692 Feat: Brotli support
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_src/gateway/production/performance/brotli.md
  app/_src/gateway/reference/nginx-directives.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7704 fix: Phrasing and typos in AI RLA plugin
  app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md
Labels: review:copyedit, skip-changelog

#7703 Fix: Hardcode gateway version in centos doc
  app/gateway/2.8.x/install-and-run/centos.md
Labels: review:general

#7708 Add clarifying statement about private dev portals
  app/konnect/dev-portal/create-dev-portal.md
Labels: review:copyedit
