Repository Kong/docs.konghq.com, pull requests merged in 2024-10, with the labels that each got.

#7984 Chore: Small spelling errors
  app/_src/gateway/get-started/ratelimiting.md
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation, skip-changelog

#7813 fix kong mesh access role examples
  app/_src/mesh/features/rbac.md
Labels: review:copyedit

#7986 Fix: update konnect predefined teams
  app/konnect/org-management/teams-and-roles/teams-reference.md
Labels: review:general

#7969 fix(portal): replace GATEWAY_SERVICE_ID with API_PRODUCT_ID [TDX-4644]
  app/konnect/dev-portal/access-and-approval/manage-teams.md
Labels: review:general, skip-changelog

#7987 Fix: remove link to get.konghq.com repo
  app/_src/gateway/get-started/index.md
Labels: review:copyedit

#7993 Fix: Protobuf structure issue
  app/_hub/kong-inc/grpc-gateway/how-to/_index.md
Labels: review:general, ci:manual-approve:link-validation

#7995 Fix: typos
  app/_src/deck/faqs.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/env.md
  app/_src/gateway/plugin-development/custom-entities.md
  app/_src/kubernetes-ingress-controller/get-started/rate-limiting.md
Labels: review:general, skip-changelog

#7994 Fix: Config file structure
  app/_src/gateway/production/running-kong/secure-admin-api.md
Labels: review:general

#8005 bug bash: Managed Identity seems to be failing for Azure Container Apps for secret manager integration
  app/_src/gateway/kong-enterprise/secrets-management/backends/azure-key-vaults.md
Labels: review:general, skip-changelog

#8004 Bug bash: Wrong statement about cache hit meaning
  app/_src/gateway/get-started/proxy-caching.md
Labels: review:general, skip-changelog

#8007 Bug bash: Expose plugin example must link to raw spec
  app/_hub/optum/kong-spec-expose/examples/_index.yml
Labels: review:general, skip-changelog

#7997 Bug-bash: Remove dev portal prereqs
  app/konnect/dev-portal/create-dev-portal.md
Labels: review:general, skip-changelog

#8002 Bug bash: remove transperent proxy section
  app/_src/gateway/production/networking/firewall.md
Labels: review:general, skip-changelog

#7996 ACME plugin storage types
  app/_hub/kong-inc/acme/how-to/_index.md
  app/_hub/kong-inc/acme/how-to/_local-testing-development.md
  app/_hub/kong-inc/acme/overview/_index.md
Labels: review:copyedit

#8003 fix: Change Gateway changelog dates to ISO 8601 format
  app/gateway/changelog.md
Labels: review:general

#8000 fix: Add notes about OpenAPI spec version compatibility
  app/konnect/api-products/service-documentation.md
  app/konnect/dev-portal/publish-service.md
Labels: review:copyedit

#8008 Change the demo app used in the mesh manager example
  app/konnect/mesh-manager/service-mesh.md
Labels: review:general

#7999 Bug bash: status endpoint not clear on port
  api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:general, skip-changelog

#8013 Fix version variable on old mesh docker installs
  app/_src/mesh/installation/docker.md
Labels: review:general

#8010 Fix: upgrade paths in 3.1.x
  app/_includes/md/gateway/upgrade-paths.md
Labels: review:copyedit

#8011 Adjust Request Transformer Advanced plugin link text
  app/_hub/kong-inc/request-transformer-advanced/overview/_index.md
Labels: review:general

#8012 Add Enterprise badges to websocket PDK references
  app/_src/gateway/plugin-development/pdk/kong.websocket.client.md
  app/_src/gateway/plugin-development/pdk/kong.websocket.upstream.md
Labels: review:general, ci:manual-approve:generated-files

#8014 Update supported Debian versions in upgrade guide table
  app/_data/tables/breaking_changes_lts.yml
Labels: review:general

#7990 Fix: Broken link in Konnect KIC page
  app/konnect/gateway-manager/kic.md
Labels: review:general

#8020 chore: update konnect compatibility
  app/konnect/compatibility.md
Labels: review:general, ci:manual-approve:link-validation

#8006 Bug bash: Logging correlation IDs doc does not specify the nginx context
  app/_hub/kong-inc/correlation-id/overview/_index.md
Labels: review:general

#8001 bug-bash: Change phase to directive in custom logic doc
  app/_src/gateway/plugin-development/custom-logic.md
Labels: review:general

#8028 Update benchmark.md
  app/_src/gateway/production/performance/benchmark.md
Labels: review:copyedit

#8029 chore: Remove backport lines from Gateway changelog
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation, skip-changelog

#8031 fix(docs): fix the quickstart help command
  app/_src/gateway/get-started/index.md
Labels: review:general, papercut

#8041 fix: fix capitalization of GitHub
  app/konnect/service-catalog/index.md
  app/konnect/service-catalog/integrations/github.md
Labels: review:copyedit

#8045 Fix broken table in AI RLA plugin
  app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md
Labels: review:general

#8025 docs(admin): added missing status of the endpoint `/admins`
  api-specs/Gateway-EE/3.3/kong-ee-3.3.json
  api-specs/Gateway-EE/3.3/kong-ee-3.3.yaml
  api-specs/Gateway-EE/3.4/kong-ee-3.4.json
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
  api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml
  api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:copyedit

#7804 feat(sdk): automated oas update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
  api-specs/Konnect/v0/yaml/mesh-control-planes.yaml
  api-specs/Konnect/v1/yaml/ksearch.yaml
  api-specs/Konnect/v2/yaml/analytics-requests.yaml
  api-specs/Konnect/v2/yaml/api-products.yaml
  api-specs/Konnect/v2/yaml/application-auth-strategies.yaml
  api-specs/Konnect/v2/yaml/audit-logs.yaml
  api-specs/Konnect/v2/yaml/control-planes.yaml
  api-specs/Konnect/v2/yaml/portal-management.yaml
  api-specs/Konnect/v3/yaml/identity.yaml
  api-specs/portal.yaml
Labels: review:general

#7976 docs(gui): update docs for Kong Manager
  app/_src/gateway/kong-manager/enable.md
Labels: review:copyedit

#8046 fix: Update Service Catalog tile on docs home page
  app/_data/landing_page.yml
Labels: review:general

#8052 Fix: Add consumer group member to config limits page
  app/konnect/gateway-manager/configuration/index.md
Labels: review:general, skip-changelog

#8051 Release: Gateway 3.6.1.8
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#8053 Remove unstable warning from WebSocket plugin handler docs
  app/_src/gateway/plugin-development/custom-logic.md
Labels: review:copyedit, skip-changelog

#8057 Update request-validator content-type validation
  app/_hub/kong-inc/request-validator/overview/_index.md
Labels: review:general

#8058 Fix: glossary typo
  app/_src/gateway/glossary.md
Labels: review:general, skip-changelog

#7971 Update: AI proxy advanced load balancing
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_data/docs_nav_gateway_3.9.x.yml
  app/_hub/kong-inc/ai-proxy-advanced/how-to/_load-balancing.md
  app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md
Labels: review:general, review:sme

#8056 Update: Rewrite AI Gateway Getting Started guide
  app/_src/gateway/ai-gateway/index.md
  app/_src/gateway/get-started/ai-gateway.md
Labels: review:copyedit

#7947 Chore: Cloud Manager changes
  app/assets/images/products/konnect/gateway-manager/konnect-control-plane-dashboard.png
  app/konnect/gateway-manager/control-plane-groups/how-to.md
  app/konnect/gateway-manager/dedicated-cloud-gateways/provision-cloud-gateway.md
  app/konnect/gateway-manager/kic.md
Labels: review:general, skip-changelog

#8054 feat: serverless gateways
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/_hub/kong-inc/acme/_metadata/_index.yml
  app/_hub/kong-inc/ai-rate-limiting-advanced/_metadata/_index.yml
  app/_hub/kong-inc/app-dynamics/_metadata/_index.yml
  app/_hub/kong-inc/file-log/_metadata/_index.yml
  app/_hub/kong-inc/graphql-proxy-cache-advanced/_metadata/_index.yml
  app/_hub/kong-inc/graphql-rate-limiting-advanced/_metadata/_index.yml
  app/_hub/kong-inc/mtls-auth/_metadata/_index.yml
  app/_hub/kong-inc/openid-connect/_metadata/_index.yml
  app/_hub/kong-inc/prometheus/_metadata/_index.yml
  app/_hub/kong-inc/proxy-cache-advanced/_metadata/_index.yml
  app/_hub/kong-inc/rate-limiting-advanced/_metadata/_index.yml
  app/_hub/kong-inc/rate-limiting/_metadata/_index.yml
  app/_hub/kong-inc/response-ratelimiting/_metadata/_index.yml
  app/_hub/kong-inc/saml/_metadata/_index.yml
  app/_hub/kong-inc/syslog/_metadata/_index.yml
  app/_hub/kong-inc/tls-handshake-modifier/_metadata/_index.yml
  app/_hub/kong-inc/tls-metadata-headers/_metadata/_index.yml
  app/_hub/kong-inc/upstream-oauth/_metadata/_index.yml
  app/assets/images/products/konnect/gateway-manager/konnect-control-plane-serverless-gateway-overview.png
  app/assets/images/products/konnect/gateway-manager/konnect-control-plane-serverless-gateway-proxy.png
  app/hub/plugins/compatibility/index.md
  app/konnect/gateway-manager/serverless-gateways/index.md
  app/konnect/gateway-manager/serverless-gateways/provision-serverless-gateway.md
  app/konnect/gateway-manager/serverless-gateways/securing-backend-traffic.md
Labels: review:general, review:copyedit

#8048 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8063 feat(sdk): automated oas update
  api-specs/Konnect/v2/yaml/audit-logs.yaml
  api-specs/Konnect/v2/yaml/portal-management.yaml
Labels: review:general

#8038 feat: swaggerhub integration
  app/_data/docs_nav_konnect.yml
  app/_data/tables/konnect/integrations.yml
  app/assets/images/icons/third-party/swaggerhub.svg
  app/konnect/service-catalog/integrations/github.md
  app/konnect/service-catalog/integrations/pagerduty.md
  app/konnect/service-catalog/integrations/swaggerhub.md
  app/konnect/service-catalog/integrations/traceable.md
Labels: do not merge, review:copyedit

#8064 Automated Konnect changelog update [skip-ci]
  app/konnect/updates.md
Labels: review:general, skip-changelog

#8065 Fix: Konnect roles reference
  app/konnect/org-management/teams-and-roles/roles-reference.md
Labels: review:general

#8068 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7989 Update: Keyring docs
  api-specs/Gateway-EE/latest/kong-ee.yaml
  app/_src/gateway/kong-enterprise/db-encryption.md
Labels: review:general

#8079 Fix: Clean up diagram description
  app/konnect/gateway-manager/control-plane-groups/index.md
Labels: review:copyedit, skip-changelog

#8077 chore: decK tabs for the AI gateway getting started guide
  app/_src/gateway/get-started/ai-gateway.md
Labels: review:copyedit

#8082 refactor(plugins/kuma): refactor custom block plugins specific to Kuma
  app/_plugins/kuma-specific/custom_block.rb
  app/_plugins/kuma-specific/tip.rb
  app/_plugins/kuma-specific/warning.rb
Labels: review:tech

#7998 fix: Replace old KIC images with mermaid diagrams
  app/_src/kubernetes-ingress-controller/concepts/architecture.md
  app/_src/kubernetes-ingress-controller/concepts/custom-resources.md
  app/_src/kubernetes-ingress-controller/get-started/services-and-routes.md
Labels: review:general

#8080 fix: tidy some serverless docs
  app/konnect/gateway-manager/index.md
  app/konnect/gateway-manager/serverless-gateways/index.md
  app/konnect/gateway-manager/serverless-gateways/provision-serverless-gateway.md
Labels: review:general, review:copyedit, skip-changelog

#8088 Fix: Incorrect URL in SSO doc
  app/konnect/org-management/okta-idp.md
Labels: review:general, skip-changelog

#8089 fix: Mesh GUI broken images
  app/assets/images/gui/dataplane-outbound-overview.png
  app/assets/images/gui/dataplane-overview.png
  app/assets/images/gui/mesh-overview.png
  app/assets/images/gui/overview.png
Labels: review:general

#8059 docs(*): add more tips while using multiple domains
  app/_src/gateway/kong-manager/enable.md
Labels: review:copyedit

#8091 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8092 docs(workspace): Add warnings to kong migrations
  app/_includes/md/enterprise/migration-finish-warning.md
  app/_src/gateway/admin-api/workspaces/reference.md
  app/_src/gateway/breaking-changes/34x.md
  app/_src/gateway/migrate-ce-to-ke.md
  app/_src/gateway/reference/cli.md
  app/_src/gateway/upgrade/blue-green.md
  app/_src/gateway/upgrade/in-place.md
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation, ci:manual-approve:generated-files

#8096 chore: Remove "tech partner" plugin category
  app/_assets/javascripts/app.js
  app/_assets/stylesheets/badges.less
  app/_hub/datadome/kong-plugin-datadome/_metadata/_index.yml
  app/_hub/imperva/imp-appsec-connector/_metadata/_index.yml
  app/_hub/okta/okta/_metadata/_index.yml
  app/_includes/hub_cards.html
  app/_includes/md/about-plugins.md
  app/_includes/plugins/badges.html
  app/_layouts/extension.html
  app/_layouts/plugins/show.html
  app/_plugins/drops/plugins/badges.rb
  app/_src/gateway/glossary.md
  app/hub/index.html
  docs/templates/partner-plugin-template/_metadata/_index.yml
  jekyll-dev.yml
  jekyll.yml
Labels: review:general

#8034 kgo: document KongPluginInstallation
  app/_data/docs_nav_kgo_1.4.x.yml
  app/_includes/md/custom-plugin.md
  app/_includes/md/kgo/prerequisites.md
  app/_src/gateway-operator/guides/plugin-distribution.md
  app/_src/kubernetes-ingress-controller/plugins/custom.md
Labels: team-k8s, review:general, area/docs, review:sme

#7729 docs(kgo): add PodDisruptionBudget guide
  app/_data/docs_nav_kgo_1.4.x.yml
  app/_src/gateway-operator/customization/pod-disruption-budget.md
Labels: review:general

#8095 Fix: typo in k8s install
  app/_src/kubernetes-ingress-controller/install/helm.md
Labels: review:general, skip-changelog

#8084 docs(kgo): add Konnect entities documentation
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_kgo_1.4.x.yml
  app/_includes/md/kgo/check-condition.md
  app/_includes/md/kgo/konnect-entities-prerequisites.md
  app/_includes/md/kgo/prerequisites.md
  app/_includes/snippets/gateway-operator/install_with_helm.md
  app/_src/gateway-operator/guides/konnect-entities/architecture.md
  app/_src/gateway-operator/guides/konnect-entities/certificate-and-cacertificate.md
  app/_src/gateway-operator/guides/konnect-entities/consumer-and-consumergroup.md
  app/_src/gateway-operator/guides/konnect-entities/dpcertificate.md
  app/_src/gateway-operator/guides/konnect-entities/gatewaycontrolplane.md
  app/_src/gateway-operator/guides/konnect-entities/key-and-keyset.md
  app/_src/gateway-operator/guides/konnect-entities/service-and-route.md
  app/_src/gateway-operator/guides/konnect-entities/tagging-and-labeling.md
  app/_src/gateway-operator/guides/konnect-entities/upstream-and-target.md
  app/_src/gateway-operator/guides/konnect-entities/vault.md
Labels: team-k8s, review:general

#8106 docs(kgo): pass feature flags to install with helm
  app/_includes/md/kgo/konnect-entities-prerequisites.md
  app/_includes/md/kgo/prerequisites.md
  app/_includes/snippets/gateway-operator/install_with_helm.md
  app/_src/gateway-operator/guides/plugin-distribution.md
Labels: team-k8s, review:general, area/docs

#8097 feat: KGO konnectExtension docs
  app/_includes/snippets/gateway-operator/install_with_helm.md
  app/_src/gateway-operator/get-started/konnect/deploy-data-plane.md
  app/_src/gateway-operator/get-started/konnect/install.md
  app/_src/gateway-operator/guides/ai-gateway.md
Labels: team-k8s, review:general

#8105 KGO Doc Updates
  app/_data/docs_nav_kgo_1.4.x.yml
  app/_includes/md/kgo/konnect-entities-prerequisites.md
  app/_src/gateway-operator/guides/konnect-entities/architecture.md
  app/_src/gateway-operator/guides/konnect-entities/faq.md
  app/_src/gateway-operator/guides/plugin-distribution.md
Labels: team-k8s, review:general

#8107 chore(kgo): update generated crd and cli references
  app/_src/gateway-operator/reference/cli-arguments/1.4.x.md
  app/_src/gateway-operator/reference/custom-resources/1.4.x.md
Labels: team-k8s, review:general

#8049 KGO: add guide for kongpluginbinding
  app/_src/gateway-operator/guides/konnect-plugin-binding.md
Labels: team-k8s, review:general

#8075 Feat: Eventing support in Service Catalog
  app/_assets/stylesheets/badges.less
  app/_data/tables/konnect/integrations.yml
  app/_includes/service-catalog-integrations.html
  app/konnect/service-catalog/index.md
  app/konnect/service-catalog/integrations/github.md
  app/konnect/service-catalog/integrations/index.md
Labels: review:general, review:copyedit, ci:manual-approve:link-validation

#8108 kgo: kongpluginbinding guide
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_kgo_1.4.x.yml
  app/_includes/md/kgo/check-condition.md
  app/_includes/md/kgo/konnect-entities-prerequisites.md
  app/_src/gateway-operator/guides/konnect-entities/dpcertificate.md
  app/_src/gateway-operator/guides/konnect-entities/key-and-keyset.md
  app/_src/gateway-operator/guides/konnect-entities/konnect-plugin-binding.md
  app/_src/gateway-operator/guides/konnect-entities/upstream-and-target.md
  app/_src/gateway-operator/guides/konnect-entities/vault.md
Labels: team-k8s, review:general
