Repository Kong/docs.konghq.com, pull requests merged in 2024-05, with the labels that each got.

#7317 Fix typos under app/
  app/_assets/javascripts/views/SearchApp/App.mobile.css
  app/_assets/stylesheets/kong-summit.less
  app/_data/docs_nav_gateway_3.0.x.yml
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/tables/breaking_changes_lts.yml
  app/_hub/kong-inc/post-function/how-to/_index.md
  app/_includes/md/kic-crd-upgrades.md
  app/_src/gateway-operator/production/monitoring/status/gateway.md
  app/_src/gateway/admin-api/admin-api-3.1.x.md
  app/_src/gateway/production/logging.md
  app/_src/gateway/reference/configuration/configuration-3.5.x.md
  app/_src/kubernetes-ingress-controller/reference/required-permissions.md
  app/api/identity.yaml
  app/assets/mesh/2.1.x/raw/crds/kuma.io_meshratelimits.yaml
  app/assets/mesh/2.2.x/raw/crds/kuma.io_meshratelimits.yaml
  app/assets/mesh/2.3.x/raw/crds/kuma.io_meshratelimits.yaml
  app/assets/mesh/2.3.x/raw/kuma-cp.yaml
  app/assets/mesh/2.4.x/raw/crds/kuma.io_meshratelimits.yaml
  app/assets/mesh/2.4.x/raw/kuma-cp.yaml
  app/assets/mesh/2.5.x/raw/crds/kuma.io_meshratelimits.yaml
  app/assets/mesh/2.5.x/raw/kuma-cp.yaml
  app/assets/mesh/2.6.x/raw/crds/kuma.io_meshratelimits.yaml
  app/assets/mesh/2.6.x/raw/kuma-cp.yaml
  app/assets/mesh/2.7.x/raw/crds/kuma.io_meshratelimits.yaml
  app/assets/mesh/2.7.x/raw/kuma-cp.yaml
  app/assets/mesh/dev/raw/crds/kuma.io_meshratelimits.yaml
  app/assets/mesh/dev/raw/kuma-cp.yaml
  app/assets/mesh/raw/CHANGELOG.md
  app/gateway/2.6.x/plugin-development/custom-entities.md
  app/gateway/2.6.x/reference/configuration.md
  app/gateway/2.7.x/reference/configuration.md
  app/gateway/2.7.x/reference/rate-limiting.md
  app/gateway/2.8.x/plugin-development/custom-entities.md
  app/gateway/2.8.x/reference/configuration.md
  app/gateway/2.8.x/reference/rate-limiting.md
  app/gateway/changelog.md
Labels: review:general

#7330 Update auth0.md
  app/konnect/dev-portal/applications/dynamic-client-registration/auth0.md
Labels: review:copyedit

#7329 Fix: fix chart in secure comms update doc
  app/konnect/gateway-manager/data-plane-nodes/secure-communications.md
Labels: review:general, skip-changelog

#7324 Improved readability and detatched some commands from their output
  app/_src/gateway-operator/guides/autoscaling-kong.md
Labels: review:copyedit

#7274 Chore: Split AI Gateway into its own section
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_src/gateway/ai-gateway/index.md
  app/_src/gateway/get-started/ai-gateway.md
  app/assets/images/icons/documentation/icn-ai.svg
  tests/sidebar.test.js
Labels: review:general

#7331 Add paragraph to explain queue parameter scope
  app/_hub/kong-inc/datadog/overview/_index.md
  app/_hub/kong-inc/http-log/overview/_index.md
  app/_hub/kong-inc/opentelemetry/overview/_index.md
  app/_hub/kong-inc/statsd/overview/_index.md
  app/_hub/kong-inc/zipkin/overview/_index.md
  app/_src/gateway/kong-plugins/queue/reference.md
Labels: review:copyedit

#6655 feat: Konnect Search Improvements (M1&M2)
  .github/styles/kong/dictionary.txt
  app/_api/konnect/search/_index.md
  app/_data/docs_nav_konnect.yml
  app/_data/konnect_oas_data.json
  app/konnect/reference/search.md
  app/konnect/updates.md
Labels: review:general, pending:release

#7339 docs(consumergroups): add paragraph about undefined behavior
  app/_includes/md/about-plugins.md
Labels: review:general

#7236 feat(openid-connect): fapi docs
  app/_hub/kong-inc/openid-connect/how-to/_fapi.md
Labels: review:general, review:copyedit, review:sme

#7310 feat(gateway/oas-validation): OpenAPI 3.1.0 documentation
  app/_hub/kong-inc/oas-validation/overview/_index.md
Labels: review:general

#7336 Chore: Generate 3.7 kong.conf reference
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_src/gateway/reference/configuration/configuration-3.7.x.md
Labels: review:general

#7333 chore: Add 3.7 support tabs/pages and fix typo
  app/_data/tables/support/gateway/third-party.yml
  app/_data/tables/support/gateway/versions/37.yml
  app/_src/gateway/support/index.md
  app/_src/gateway/support/third-party.md
Labels: review:general

#7340 chore: Add links to graphql paper
  app/_hub/kong-inc/graphql-proxy-cache-advanced/how-to/_index.md
  app/_hub/kong-inc/graphql-proxy-cache-advanced/overview/_index.md
  app/_hub/kong-inc/graphql-rate-limiting-advanced/how-to/_index.md
  app/_hub/kong-inc/graphql-rate-limiting-advanced/overview/_index.md
Labels: review:copyedit

#7342 Fix: Link to the Konnect policy page from the Gateway page
  app/_src/gateway/support/index.md
Labels: review:copyedit, skip-changelog

#7189 Feat: PKI Cert Improvements in Konnect
  app/konnect/updates.md
Labels: review:general, skip-changelog

#7214 New AI Rate Limiting Advanced plugin
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_data/tables/version_errors_konnect.yml
  app/_hub/kong-inc/ai-prompt-decorator/overview/_index.md
  app/_hub/kong-inc/ai-prompt-guard/overview/_index.md
  app/_hub/kong-inc/ai-prompt-template/overview/_index.md
  app/_hub/kong-inc/ai-proxy/overview/_index.md
  app/_hub/kong-inc/ai-rate-limiting-advanced/_changelog.md
  app/_hub/kong-inc/ai-rate-limiting-advanced/_metadata/_index.yml
  app/_hub/kong-inc/ai-rate-limiting-advanced/how-to/_index.md
  app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md
  app/_hub/kong-inc/ai-rate-limiting-advanced/versions.yml
  app/_hub/kong-inc/ai-request-transformer/overview/_index.md
  app/_hub/kong-inc/ai-response-transformer/overview/_index.md
  app/_redirects
  app/_src/gateway/ai-gateway/index.md
  app/_src/gateway/get-started/ai-gateway.md
  app/_src/gateway/production/logging/ai-analytics.md
  app/assets/images/icons/hub/kong-inc_ai-rate-limiting-advanced.png
Labels: review:copyedit

#7345 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7245 feat: add OCI plugin distribution docs
  .github/styles/kong/auto-ignore.txt
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_src/gateway/plugin-development/distribution.md
Labels: review:general, review:copyedit, review:sme

#7350 (fix) Remove "enterprise" category from Datadome
  app/_hub/datadome/kong-plugin-datadome/_metadata/_index.yml
Labels: review:general

#7290 Plugins troubleshooting
  app/_layouts/plugins/troubleshooting.html
  app/_plugins/generators/plugin_single_source/pages/troubleshooting.rb
  app/_plugins/generators/plugin_single_source/plugin/pages_builder.rb
  app/_plugins/generators/plugin_single_source/plugin/release.rb
  app/_plugins/generators/plugin_single_source/plugin/sidenav.rb
  app/assets/images/icons/hub-layout/icn-troubleshooting.svg
Labels: review:general

#7346 chore: Upgrade paths for 3.7.x
  app/_includes/md/gateway/upgrade-paths.md
  app/_src/gateway/upgrade/index.md
Labels: review:general, skip-changelog

#7354 Chore: Generate PDK and CLI for Gateway 3.7
  app/_src/gateway/plugin-development/pdk/index.md
  app/_src/gateway/plugin-development/pdk/kong.jwe.md
  app/_src/gateway/plugin-development/pdk/kong.log.md
  app/_src/gateway/plugin-development/pdk/kong.tracing.md
  app/_src/gateway/reference/cli.md
Labels: review:general, ci:check-skipped:generated-files, skip-changelog

#7306 docs(api): describe before & after filters of audit log
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:general

#7357 Fix: Visual error in AI plugin admonition
  app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md
Labels: review:general, skip-changelog

#7359 Fix: Remove beta label from Ksearch API, add Insomnia link
  api-specs/Konnect/v1/yaml/ksearch.yaml
  app/_api/konnect/search/_index.md
  app/_data/konnect_oas_data.json
Labels: review:general, skip-changelog

#7361 Remove duplicated entry
  app/konnect/reference/search.md
Labels: review:general

#7367 Add https://openai.com to scheduled broken links' ignored targets
  tools/broken-link-checker/config/ignored_targets.json
Labels: review:general

#7366 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7332 feat: Add Mermaid export instructions to contributing guide
  .github/styles/kong/auto-ignore.txt
  app/contributing/diagrams.md
Labels: review:copyedit, skip-changelog

#7382 Fixes check-links.yml
  tools/_utilities/lib/nav-to-urls.js
Labels: review:tech

#7383 Fix: Update Konnect compatibility dates
  app/konnect/compatibility.md
Labels: review:general, skip-changelog

#7358 request-termination and forward-proxy incompatibility
  app/_hub/kong-inc/request-termination/overview/_index.md
Labels: review:copyedit

#7323 docs(oidc): supporting dpop
  app/_hub/kong-inc/openid-connect/how-to/_cert-bound-access-tokens.md
  app/_hub/kong-inc/openid-connect/how-to/_demonstrating-proof-of-possession.md
  app/_hub/kong-inc/openid-connect/how-to/_fapi.md
  app/_includes/md/plugins-hub/oidc-prereqs.md
Labels: review:tech

#7377 Release: Gateway 3.6.1.4
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7384 Fix: Move Konnect policy note in Gateway support doc
  app/_src/gateway/support/index.md
Labels: review:general

#7368 fix(sandbox): add more explanation about kong.cache instance inside serverless function sandbox
  app/_includes/md/plugins-hub/sandbox.md
Labels: review:tech, review:general

#7369 Automated OAS Update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
  api-specs/Konnect/v0/yaml/mesh-control-planes.yaml
  api-specs/Konnect/v1/yaml/ksearch.yaml
  api-specs/Konnect/v2/yaml/analytics-requests.yaml
  api-specs/Konnect/v2/yaml/api-products.yaml
  api-specs/Konnect/v2/yaml/application-auth-strategies.yaml
  api-specs/Konnect/v2/yaml/audit-logs.yaml
  api-specs/Konnect/v2/yaml/control-planes.yaml
  api-specs/Konnect/v2/yaml/portal-management.yaml
  api-specs/Konnect/v3/yaml/identity.yaml
Labels: review:general

#7387 feat: add filter chains to Admin OSS spec
  api-specs/Gateway-OSS/latest/kong-oss.yaml
  app/_src/gateway/admin-api/index_latest.md
Labels: review:general

#7379 Release: Gateway 3.4.3.8
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#7391 Automated OAS Update
  api-specs/Konnect/v2/yaml/portal-management.yaml
Labels: review:general

#7389 update the perf stats for 3.7
  app/_src/gateway/production/performance/performance-testing.md
Labels: review:general

#7390 feat(ai-proxy): added Azure native auth explanation
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/ai-proxy/how-to/_cloud-provider-authentication.md
Labels: review:copyedit

#7393 Fix: Validate schemas endpoint
  api-specs/Gateway-OSS/3.3/kong-oss-33.yaml
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
  api-specs/Gateway-OSS/latest/kong-oss.yaml
Labels: review:general

#7386 chore: Set source URLs for moved EE plugins
  app/_hub/kong-inc/app-dynamics/_metadata/_index.yml
  app/_hub/kong-inc/canary/_metadata/_index.yml
  app/_hub/kong-inc/degraphql/_metadata/_index.yml
  app/_hub/kong-inc/exit-transformer/_metadata/_index.yml
  app/_hub/kong-inc/forward-proxy/_metadata/_index.yml
  app/_hub/kong-inc/graphql-proxy-cache-advanced/_metadata/_index.yml
  app/_hub/kong-inc/jq/_metadata/_index.yml
  app/_hub/kong-inc/jwe-decrypt/_metadata/_index.yml
  app/_hub/kong-inc/key-auth-enc/_metadata/_index.yml
  app/_hub/kong-inc/mocking/_metadata/_index.yml
  app/_hub/kong-inc/oauth2-introspection/_metadata/_index.yml
  app/_hub/kong-inc/request-transformer-advanced/_metadata/_index.yml
  app/_hub/kong-inc/response-transformer-advanced/_metadata/_index.yml
  app/_hub/kong-inc/route-by-header/_metadata/_index.yml
  app/_hub/kong-inc/route-transformer-advanced/_metadata/_index.yml
  app/_hub/kong-inc/statsd-advanced/_metadata/_2.6.x.yml
  app/_hub/kong-inc/statsd-advanced/_metadata/_2.7.x.yml
  app/_hub/kong-inc/statsd-advanced/_metadata/_2.8.x.yml
  app/_hub/kong-inc/statsd-advanced/_metadata/_index.yml
  app/_hub/kong-inc/tls-handshake-modifier/_metadata/_index.yml
  app/_hub/kong-inc/tls-metadata-headers/_metadata/_index.yml
  app/_hub/kong-inc/upstream-timeout/_metadata/_index.yml
  app/_hub/kong-inc/websocket-size-limit/_metadata/_index.yml
  app/_hub/kong-inc/websocket-validator/_metadata/_index.yml
  app/_hub/kong-inc/xml-threat-protection/_metadata/_index.yml
  app/_plugins/generators/plugin_single_source/pages/configuration.rb
  spec/app/_plugins/generators/plugin_single_source/pages/configuration_spec.rb
Labels: review:tech

#7388 fix(admin-oss): Plugin ordering is an EE-only feature
  api-specs/Gateway-OSS/3.3/kong-oss-33.json
  api-specs/Gateway-OSS/3.3/kong-oss-33.yaml
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.json
  api-specs/Gateway-OSS/3.4/kong-oss-3.4.yaml
  api-specs/Gateway-OSS/3.5/kong-oss-3.5.yaml
  api-specs/Gateway-OSS/latest/kong-oss.yaml
Labels: review:general

#7401 chore: Disable promo banner
  app/_assets/entrypoints/application.js
  app/_assets/stylesheets/header.less
  app/_includes/nav-v2.html
Labels: review:general

#7400 Fix: Set accurate EOL for RHEL8
  app/_data/tables/support/gateway/versions/28.yml
  app/_data/tables/support/gateway/versions/34.yml
  app/_data/tables/support/gateway/versions/35.yml
  app/_data/tables/support/gateway/versions/36.yml
  app/_data/tables/support/gateway/versions/37.yml
Labels: review:general

#7403 Update performance-testing.md for 3.7 rc5
  app/_src/gateway/production/performance/performance-testing.md
Labels: review:general

#7378 Release: Gateway 3.5.0.4
  app/_data/kong_versions.yml
  app/_src/gateway/key-concepts/routes/expressions.md
  app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
  app/_src/gateway/reference/expressions-language/language-references.md
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7406 chore: update 3.3 for end of full support
  app/_src/gateway/support/index.md
  app/_src/gateway/support/third-party.md
Labels: review:general, skip-changelog

#7395 chore: Clean up plugin version tags
  .github/PULL_REQUEST_TEMPLATE.md
  app/_hub/kong-inc/acl/how-to/_index.md
  app/_hub/kong-inc/acl/overview/_index.md
  app/_hub/kong-inc/acme/how-to/_redis.md
  app/_hub/kong-inc/app-dynamics/overview/_index.md
  app/_hub/kong-inc/aws-lambda/overview/_index.md
  app/_hub/kong-inc/bot-detection/overview/_index.md
  app/_hub/kong-inc/canary/overview/_index.md
  app/_hub/kong-inc/datadog/overview/_index.md
  app/_hub/kong-inc/http-log/how-to/_splunk.md
  app/_hub/kong-inc/http-log/overview/_index.md
  app/_hub/kong-inc/http-log/overview/_log-format.md
  app/_hub/kong-inc/http-log/overview/_using-custom-fields.md
  app/_hub/kong-inc/ip-restriction/overview/_index.md
  app/_hub/kong-inc/kafka-log/overview/_index.md
  app/_hub/kong-inc/kafka-upstream/overview/_index.md
  app/_hub/kong-inc/ldap-auth-advanced/overview/_index.md
  app/_hub/kong-inc/mocking/overview/_index.md
  app/_hub/kong-inc/mtls-auth/overview/_index.md
  app/_hub/kong-inc/oas-validation/overview/_index.md
  app/_hub/kong-inc/oauth2/how-to/_oauth2rla.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_introspection.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_jwt-access-token.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_session.md
  app/_hub/kong-inc/openid-connect/how-to/third-party/_cognito.md
  app/_hub/kong-inc/openid-connect/how-to/third-party/_curity.md
  app/_hub/kong-inc/openid-connect/how-to/third-party/_okta.md
  app/_hub/kong-inc/openid-connect/overview/_index.md
  app/_hub/kong-inc/opentelemetry/overview/_index.md
  app/_hub/kong-inc/prometheus/overview/_index.md
  app/_hub/kong-inc/rate-limiting-advanced/how-to/_index.md
  app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
  app/_hub/kong-inc/request-transformer-advanced/how-to/_templates.md
  app/_hub/kong-inc/session/overview/_index.md
  app/_hub/kong-inc/statsd-advanced/overview/_index.md
  app/_hub/kong-inc/statsd/overview/_index.md
  app/_hub/kong-inc/vault-auth/overview/_index.md
  app/_hub/kong-inc/zipkin/overview/_index.md
  app/_includes/md/plugins-hub/json-object-log.md
  app/_includes/md/plugins-hub/log-format.md
  app/_includes/md/plugins-hub/oidc-prereqs.md
  app/_includes/md/plugins-hub/upstream-headers.md
  app/_includes/plugins/schema.html
  app/_plugins/blocks/plugin_version_block.rb
  app/_plugins/hooks/plugin_version_block.rb
  app/contributing/conditional-rendering.md
  app/contributing/single-sourced-plugins.md
  spec/fixtures/app/_hub/kong-inc/jwt-signer/overview/_index.md
Labels: review:general, skip-changelog

#7410 Fix: Add content types to Konnect API page
  app/konnect/api/index.md
Labels: review:general, skip-changelog

#7347 chore: Breaking changes page for 3.7
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_src/gateway/breaking-changes/37x.md
  app/_src/gateway/production/tracing/index.md
Labels: review:copyedit

#7376 [Plugin Hub] Display deprecated fields
  app/_includes/plugins/schema.html
  app/_includes/plugins/schemas/field.html
  app/_plugins/drops/plugins/schema.rb
  spec/app/_plugins/drops/plugins/schema_field_spec.rb
  spec/app/_plugins/drops/plugins/schema_spec.rb
Labels: review:general

#7293 feat: AI Proxy streaming
  .github/styles/kong/auto-ignore.txt
  app/_hub/kong-inc/ai-proxy/_changelog.md
  app/_hub/kong-inc/ai-proxy/how-to/_sdk-usage.md
  app/_hub/kong-inc/ai-proxy/how-to/_streaming.md
  app/_hub/kong-inc/ai-proxy/overview/_index.md
Labels: do not merge, review:sme

#7415 chore: set version tags around table
  app/_hub/kong-inc/ai-proxy/overview/_index.md
Labels: review:general

#7416 Chore: AI Gateway docs cleanup
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_hub/kong-inc/ai-azure-content-safety/overview/_index.md
  app/_hub/kong-inc/ai-prompt-decorator/overview/_index.md
  app/_hub/kong-inc/ai-prompt-guard/overview/_index.md
  app/_hub/kong-inc/ai-prompt-template/overview/_index.md
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_anthropic.md
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_azure.md
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_cohere.md
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_llama2.md
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_mistral.md
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_openai.md
  app/_hub/kong-inc/ai-proxy/overview/_index.md
  app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md
  app/_hub/kong-inc/ai-request-transformer/overview/_index.md
  app/_hub/kong-inc/ai-response-transformer/overview/_index.md
  app/_includes/md/ai-plugins-links.md
  app/_redirects
  app/_src/gateway/ai-gateway/index.md
Labels: review:general, review:copyedit, ci:manual-approve:link-validation, skip-changelog

#7348 add content-type and body-validation explanation in _index.md
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/request-validator/overview/_index.md
Labels: review:general

#7349 added example in javascript custom plugin
  app/_src/gateway/plugin-development/pluginserver/javascript.md
Labels: review:general

#7420 fix: Pass release variable to links include
  app/_hub/kong-inc/ai-azure-content-safety/overview/_index.md
  app/_hub/kong-inc/ai-prompt-decorator/overview/_index.md
  app/_hub/kong-inc/ai-prompt-guard/overview/_index.md
  app/_hub/kong-inc/ai-prompt-template/overview/_index.md
  app/_hub/kong-inc/ai-proxy/overview/_index.md
  app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md
  app/_hub/kong-inc/ai-request-transformer/overview/_index.md
  app/_hub/kong-inc/ai-response-transformer/overview/_index.md
Labels: review:general, skip-changelog

#7421 WIP: Don't install netlify-cli globally when running smoke tests
  .github/workflows/build-docs-pdf.yml
  .github/workflows/build-plugin-pdf.yml
  .github/workflows/run-tests.yml
  .github/workflows/scheduled-broken-link-checker.yml
Labels: review:tech, skip-changelog

#7427 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#7433 Update: Make license update info easier to find
  app/_includes/md/enterprise/deploy-license.md
  app/_includes/md/gateway/setup.md
Labels: review:copyedit

#7412 Release: Gateway 3.7.0.0
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_data/kong_versions.yml
Labels: do not merge, review:general

#7411 chore: Changelog for 3.7.0.0
  app/_hub/kong-inc/acme/_changelog.md
  app/_hub/kong-inc/ai-prompt-guard/_changelog.md
  app/_hub/kong-inc/ai-proxy/_changelog.md
  app/_hub/kong-inc/aws-lambda/_changelog.md
  app/_hub/kong-inc/degraphql/_changelog.md
  app/_hub/kong-inc/graphql-proxy-cache-advanced/_changelog.md
  app/_hub/kong-inc/jwt-signer/_changelog.md
  app/_hub/kong-inc/jwt/_changelog.md
  app/_hub/kong-inc/key-auth/_changelog.md
  app/_hub/kong-inc/ldap-auth-advanced/_changelog.md
  app/_hub/kong-inc/mocking/_changelog.md
  app/_hub/kong-inc/mtls-auth/_changelog.md
  app/_hub/kong-inc/oas-validation/_changelog.md
  app/_hub/kong-inc/openid-connect/_changelog.md
  app/_hub/kong-inc/opentelemetry/_changelog.md
  app/_hub/kong-inc/prometheus/_changelog.md
  app/_hub/kong-inc/rate-limiting-advanced/_changelog.md
  app/_hub/kong-inc/rate-limiting/_changelog.md
  app/_hub/kong-inc/response-ratelimiting/_changelog.md
  app/_src/gateway/breaking-changes/37x.md
  app/gateway/changelog.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#7408 Chore: Update Konnect changelog for Gateway 3.7
  app/konnect/updates.md
Labels: review:general

#7372 chore: add compatibility updates for Gateway 3.7 release
  app/_data/tables/version_errors_konnect.yml
Labels: review:general

#7439 Fix: konnect 3.7 changelog
  app/konnect/updates.md
Labels: review:general, skip-changelog

#7424 Fixed Context-Type
  app/konnect/org-management/audit-logging/reference.md
Labels: review:general

#7422 chore: Convert remaining OIDC topic that uses httpie to curl
  app/_hub/kong-inc/openid-connect/how-to/_cert-bound-access-tokens.md
Labels: review:general

#7434 Update: Telemetry FAQs for Konnect
  app/konnect/analytics/index.md
  app/konnect/network-resiliency.md
Labels: review:copyedit

#7440 chore: add compatibility updates for Gateway 3.7 release
  app/_data/tables/version_errors_konnect.yml
Labels: review:general, skip-changelog

#7423 fix log format indentation
  app/_includes/md/plugins-hub/log-format.md
Labels: review:copyedit

#7443 Fix: remove inaccurate note about AppDynamics library
  app/_hub/kong-inc/app-dynamics/overview/_index.md
Labels: review:general

#7337 chore: 3.7 SBOM link
  app/_src/gateway/support/sbom.md
Labels: do not merge, review:general

#7446 Automated OAS Update
  api-specs/Konnect/v2/yaml/api-products.yaml
Labels: review:general

#7442 Fix installation docs for 3.7
  app/_data/installation/gateway.yml
Labels: review:general

#7447 chore: Update label for install workflow [skip ci]
  .github/workflows/install-instructions-test.yml
Labels: review:general, skip-changelog

#7414 fix(mesh): remove beta on MeshOPA
  app/_data/docs_nav_mesh_2.8.x.yml
  app/_src/mesh/features/meshopa.md
Labels: review:general

#7449 Revert "Fix: Set accurate EOL for RHEL8"
  app/_data/tables/support/gateway/versions/28.yml
  app/_data/tables/support/gateway/versions/34.yml
  app/_data/tables/support/gateway/versions/35.yml
  app/_data/tables/support/gateway/versions/36.yml
  app/_data/tables/support/gateway/versions/37.yml
Labels: review:general

#7394 Fix: Unifiy Kong Manager and Kong Manager OSS sections in GW docs
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_redirects
  app/_src/gateway/index.md
  app/_src/gateway/kong-manager-oss/index.md
  app/_src/gateway/kong-manager/consumer-groups.md
  app/_src/gateway/kong-manager/enable.md
  app/_src/gateway/kong-manager/get-started/consumers.md
  app/_src/gateway/kong-manager/get-started/load-balancing.md
  app/_src/gateway/kong-manager/get-started/proxy-caching.md
  app/_src/gateway/kong-manager/get-started/rate-limiting.md
  app/_src/gateway/kong-manager/get-started/services-and-routes.md
  app/_src/gateway/kong-manager/index.md
  app/_src/gateway/kong-manager/troubleshoot.md
  tests/sidebar.test.js
Labels: review:general, ci:manual-approve:link-validation
