Repository Kong/docs.konghq.com, pull requests merged in 2024-11, with the labels that each got.

#8104 chore: Add link to logging module
  app/_hub/kong-inc/opentelemetry/overview/_index.md
Labels: review:copyedit

#8103 chore: Move Bedrock and Gemini into LLM providers nav sections
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_data/docs_nav_gateway_3.9.x.yml
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_bedrock.md
  app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_gemini.md
  app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_bedrock.md
  app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_gemini.md
  app/_hub/kong-inc/ai-proxy/overview/_index.md
  app/_redirects
  changelog.md
Labels: review:general

#8109 chore(kgo-ee): update API reference for v1.4.0
  app/_src/gateway-operator/reference/custom-resources/1.4.x.md
Labels: team-k8s, review:general

#8110 Release: KGO 1.4.x
  app/_data/kong_versions.yml
Labels: review:general

#8101 chore(kgo): add changelog for 1.4.0
  app/gateway-operator/changelog.md
Labels: team-k8s, review:general

#8112 Update title to Impart Security
  app/_hub/impart-security/kong-plugin-impart/overview/_index.md
Labels: review:general

#8115 Bump jekyll-generator-single-source
  Gemfile
  Gemfile.lock
Labels: review:tech, skip-changelog

#8116 Feat: Changelog for Filtering
  app/konnect/updates.md
Labels: review:general, skip-changelog

#7939 Feat: Konnect native config store
  app/_data/docs_nav_konnect.yml
  app/_src/deck/guides/vaults.md
  app/assets/images/products/konnect/gateway-manager/konnect-vaults.png
  app/konnect/gateway-manager/configuration/config-store.md
  app/konnect/gateway-manager/configuration/vaults/how-to.md
  app/konnect/gateway-manager/configuration/vaults/index.md
  tools/screenshots/konnect/vaults/overview.yaml
Labels: review:general

#8120 fix(mesh): correct invalid sidebar reference
  app/_data/docs_nav_mesh_2.9.x.yml
Labels: review:general

#8100 Mesh CVE policy
  app/_data/docs_nav_mesh_2.10.x.yml
  app/_data/docs_nav_mesh_2.4.x.yml
  app/_data/docs_nav_mesh_2.5.x.yml
  app/_data/docs_nav_mesh_2.6.x.yml
  app/_data/docs_nav_mesh_2.7.x.yml
  app/_data/docs_nav_mesh_2.8.x.yml
  app/_data/docs_nav_mesh_2.9.x.yml
  app/_src/mesh/features/access-audit.md
  app/_src/mesh/features/acmpca.md
  app/_src/mesh/features/ca-rotation.md
  app/_src/mesh/features/cert-manager.md
  app/_src/mesh/features/fips-support.md
  app/_src/mesh/features/index.md
  app/_src/mesh/features/kds-auth.md
  app/_src/mesh/features/meshopa.md
  app/_src/mesh/features/opa.md
  app/_src/mesh/features/openshift-quickstart.md
  app/_src/mesh/features/rbac.md
  app/_src/mesh/features/ubi-images.md
  app/_src/mesh/features/vault.md
  app/_src/mesh/features/windows.md
  app/_src/mesh/gettingstarted.md
  app/_src/mesh/vulnerability-patching-process.md
Labels: review:general, review:sme

#8121 Automated Konnect changelog update [skip-ci]
  app/konnect/updates.md
Labels: review:general, skip-changelog

#8119 Update: Add 'development' entry for cluster resource allocations table
  app/_src/gateway/production/sizing-guidelines.md
Labels: review:general

#8073 Fix: Admins examples broken steps formatting
  app/_src/gateway/production/access-control/register-admin-api.md
Labels: review:general

#8132 fix(docs): correct the latest version on the API admin page
  api-specs/Gateway-EE/latest/kong-ee.yaml
  api-specs/Gateway-OSS/latest/kong-oss.yaml
Labels: review:general, skip-changelog

#8131 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8094 Release: Gateway 3.8.1.0
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:copyedit

#8015 Release: Gateway 3.4.3.13
  app/_data/kong_versions.yml
  app/_src/gateway/kong-enterprise/aws-iam-auth-to-rds-database.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#8145 Feat: Support policy change
  app/_includes/md/availability-stages.md
Labels: review:general, skip-changelog

#8137 docs(kic): refer to kubernetes-configuration in KIC 3.4 >= docs
  app/_data/docs_nav_kic_3.4.x.yml
  app/_data/kong_versions.yml
  app/_includes/md/kic-crd-upgrades.md
  app/_src/kubernetes-ingress-controller/upgrade/kic.md
Labels: review:general

#8134 kic: document 2 new metrics for configuration push size
  .github/styles/kong/auto-ignore.txt
  app/_src/kubernetes-ingress-controller/production/observability/prometheus.md
Labels: team-k8s, review:sme

#8123 Update: Add AI Gateway tile to landing page
  app/_assets/stylesheets/pages/landing-page.less
  app/_data/landing_page.yml
Labels: review:general

#8148 Revert "Feat/add privatelink docs"
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/konnect/private-connections/aws-privatelink.md
Labels: review:general, skip-changelog

#8151 Fix: network requirements
  app/konnect/network.md
Labels: bug, review:general

#8144 fix: correct config store queries
  app/konnect/gateway-manager/configuration/config-store.md
Labels: bug, review:copyedit

#8157 Fix plugins filters after a bad rebase
  app/_data/hub_filters.yml
  jekyll-dev.yml
  jekyll.yml
Labels: review:general

#7488 Add KIC in Konnect with KGO example
  app/_src/gateway-operator/get-started/kic/create-gateway.md
  app/_src/gateway-operator/get-started/kic/create-route.md
  app/_src/gateway-operator/get-started/kic/install.md
Labels: team-k8s, review:general

#8159 Fix hreflangs, they should have the full url
  app/_includes/head.html
Labels: review:general

#8117 feat(sdk): automated oas update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
  api-specs/Konnect/v0/yaml/mesh-control-planes.yaml
  api-specs/Konnect/v1/yaml/ksearch.yaml
  api-specs/Konnect/v2/yaml/api-products.yaml
  api-specs/Konnect/v2/yaml/application-auth-strategies.yaml
  api-specs/Konnect/v2/yaml/audit-logs.yaml
  api-specs/Konnect/v2/yaml/control-planes.yaml
  api-specs/Konnect/v2/yaml/portal-management.yaml
  api-specs/Konnect/v3/yaml/identity.yaml
  api-specs/portal.yaml
Labels: review:general

#8155 Fix: extra sentence
  app/konnect/dev-portal/index.md
Labels: bug, review:general

#8167 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8163 kong2tf -g typically used in combination with gateway dump --with-id
  app/_src/deck/reference/deck_file_kong2tf.md
Labels: review:copyedit

#8111 fix: Request Validator incorrectly refers to Kong format schema
  app/_hub/kong-inc/request-validator/overview/_index.md
Labels: review:general

#8161 feat: serverless provisioning clarification
  app/konnect/gateway-manager/serverless-gateways/index.md
  app/konnect/gateway-manager/serverless-gateways/provision-serverless-gateway.md
Labels: review:general, area/docs

#8171 chore: Gateway 3.5 moves into sunset support
  app/_src/gateway/support/index.md
  app/_src/gateway/support/third-party.md
Labels: review:general

#8170 Release: Gateway 3.7.1.3
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#8179 Fix: Heading level in KIC custom entities guide
  app/_src/kubernetes-ingress-controller/guides/services/custom-entity.md
Labels: review:general, skip-changelog

#8165 Update secure-communications.md
  app/konnect/gateway-manager/data-plane-nodes/secure-communications.md
Labels: review:general, review:copyedit

#8149 Feat: PrivateLink connection
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/konnect/private-connections/aws-privatelink.md
Labels: do not merge, review:general

#8186 fix: step formatting in Secure Comms
  app/konnect/gateway-manager/data-plane-nodes/secure-communications.md
Labels: review:general

#8187 Automated Konnect changelog update [skip-ci]
  app/konnect/updates.md
Labels: review:general, skip-changelog

#7578 Add cross-namespace KongPlugin doc
  app/_data/docs_nav_kic_3.2.x.yml
  app/_data/docs_nav_kic_3.3.x.yml
  app/_includes/md/kic/consumer.md
  app/_includes/md/kic/prerequisites.md
  app/_src/kubernetes-ingress-controller/plugins/cross-namespace.md
Labels: team-k8s, review:general, review:copyedit, review:sme

#8193 chore(kgo): bump to 1.4.1
  app/_data/kong_versions.yml
  app/gateway-operator/changelog.md
Labels: team-k8s, review:general
