Repository Kong/docs.konghq.com, pull requests merged in 2025-06, with the labels that each got.

#8824 Open link to dev site on the same tab
  app/_includes/nav-v2.html
Labels: review:general

#8780 fix: Update vectordb options for AI Proxy Advanced
  app/_hub/kong-inc/ai-proxy-advanced/how-to/_load-balancing.md
Labels: review:general

#8798 Fix link name to audit logs api
  app/konnect/dev-portal/audit-logging/index.md
Labels: review:general

#8830 chore: Update links in banner
  redirects.yaml
Labels: review:general

#8833 Update Dev Portal pages and snippets redirects
  redirects.yaml
Labels: review:general

#8840 KM networking and FIPS redirects
  redirects.yaml
Labels: review:general

#8842 fix(mesh): fix nav reference in 2.12.x mesh docs
  app/_data/docs_nav_mesh_2.12.x.yml
Labels: review:tech

#8846 fix: Add KM basic auth redirect, fix the changelog dates
  app/gateway/changelog.md
  redirects.yaml
Labels: review:general, ci:manual-approve:link-validation, ci:manual-approve:linting

#8847 Add Dev Portal RBAC redirect
  redirects.yaml
Labels: review:general

#8848 Fix: Konnect audit logs migration
  redirects.yaml
Labels: review:general

#8851 Fix: Redirect for Authenticate your Kong Gateway Amazon RDS database with AWS IAM
  redirects.yaml
Labels: review:general

#8836 StatsD how-to migration
  redirects.yaml
Labels: review:general

#8860 redirects: Datadog with prometheus and Konnect audit log webhook how to
  redirects.yaml
Labels: review:general

#8864 Redirect: Konnect search
  app/_redirects
Labels: review:general

#8855 mesh-manager docs redirects
  app/_redirects
  redirects.yaml
Labels: review:general

#8870 Update _redirects
  app/_redirects
Labels: review:general
