Repository Kong/docs.konghq.com, pull requests merged in 2025-01, with the labels that each got.

#8314 Add minimum decK version to Konnect docs
  app/_src/deck/guides/konnect.md
Labels: review:general

#8315 Update _index.md
  app/_hub/kong-inc/ai-prompt-template/overview/_index.md
Labels: review:general

#8311 Fix: typos in plugin development
  app/_src/gateway/plugin-development/custom-entities.md
  app/_src/gateway/plugin-development/entities-cache.md
Labels: review:general

#8318 chore(kic): update latest to 3.4.1
  app/_data/kong_versions.yml
Labels: team-k8s, review:general

#8320 Fix: RHEL7 deprecation version
  app/gateway/changelog.md
Labels: review:general

#8316 docs: update the key calculation expression of proxy cache
  app/_hub/kong-inc/proxy-cache/overview/_index.md
Labels: review:copyedit

#8324 Update konnect.md
  app/_src/deck/guides/konnect.md
Labels: review:general

#8327 Run netlify dev with npx
  .github/workflows/build-docs-pdf.yml
  .github/workflows/build-plugin-pdf.yml
  .github/workflows/run-tests.yml
  .github/workflows/scheduled-broken-link-checker.yml
Labels: review:general

#8326 Add tool to error with missing unreleased version
  .github/workflows/linting.yml
  tools/check-unreleased-label/package-lock.json
  tools/check-unreleased-label/package.json
  tools/check-unreleased-label/run.js
Labels: review:tech

#8322 Don't scroll the page when setting a tab via query param
  app/_assets/javascripts/app.js
Labels: review:general

#7480 Add page on KIC vs Hybrid mode for Kubernetes
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/docs_nav_gateway_3.10.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_data/docs_nav_gateway_3.9.x.yml
  app/_src/gateway/production/deployment-topologies/kubernetes.md
Labels: review:general

#8332 fix: workspace collision
  app/_src/gateway/kong-enterprise/workspaces/index.md
Labels: review:general

#8331 Fix: Update decK compatible version with Konnect
  app/_src/deck/faqs.md
  app/_src/deck/guides/konnect.md
  app/konnect/compatibility.md
  app/konnect/gateway-manager/control-plane-groups/migrate.md
  app/konnect/gateway-manager/declarative-config.md
Labels: review:copyedit

#8335 Add KIC + Portal warning to Kubernetes topology
  app/_src/gateway/production/deployment-topologies/kubernetes.md
Labels: review:general

#8338 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8333 fix: Datakit guide
  app/_src/gateway/kong-enterprise/datakit/get-started.md
Labels: review:general

#8341 feat(sdk): automated oas update
  api-specs/Konnect/v0/yaml/mesh-control-planes.yaml
Labels: review:general

#8342 Fix: Add Admins and groups schemas
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml
  api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml
  api-specs/Gateway-EE/3.8/kong-ee.yaml
  api-specs/Gateway-EE/3.9/kong-ee.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:general

#8346 Release: Gateway 3.4.3.16
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#8347 Fix: OIDC plugin params listed as strings instead of arrays
  app/_hub/kong-inc/openid-connect/how-to/_demonstrating-proof-of-possession.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_authorization-code-flow.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_client-credentials.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_introspection.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_jwt-access-token.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_kong-oauth-token.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_password-grant.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_refresh-token.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_session.md
  app/_hub/kong-inc/openid-connect/how-to/authentication/_user-info.md
  app/_hub/kong-inc/openid-connect/how-to/authorization/_acl.md
  app/_hub/kong-inc/openid-connect/how-to/authorization/_claims.md
  app/_hub/kong-inc/openid-connect/how-to/authorization/_consumer.md
  app/_hub/kong-inc/openid-connect/how-to/client-authentication/_mtls.md
Labels: review:general

#8351 docs(kgo): add global KongPluginBinding description
  app/_data/docs_nav_kgo_1.5.x.yml
  app/_data/kong_versions.yml
  app/_src/gateway-operator/guides/konnect-entities/konnect-plugin-binding.md
Labels: review:general

#8353 Sync Konnect OAS Data
  app/_data/konnect_oas_data.json
Labels: review:general, skip-changelog

#8354 Feat: notification hub
  app/_api/konnect/notification-hub/_index.md
Labels: review:general

#8359 Add schema for consumer groups
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
  api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml
  api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml
  api-specs/Gateway-EE/3.8/kong-ee.yaml
  api-specs/Gateway-EE/3.9/kong-ee.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:tech

#8361 Push gateway OAS to the dev site
  .github/raise-pr-on-change.json
  .github/workflows/push-oas-downstream.yaml
Labels: review:tech

#8370 Update the license report response in Admin EE spec
  api-specs/Gateway-EE/3.4/kong-ee-3.4.yaml
  api-specs/Gateway-EE/3.5/kong-ee-3.5.yaml
  api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml
  api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml
  api-specs/Gateway-EE/3.8/kong-ee.yaml
  api-specs/Gateway-EE/3.9/kong-ee.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:general

#8329 feat: Service Catalog GitLab integration
  app/_data/docs_nav_konnect.yml
  app/_data/tables/konnect/integrations.yml
  app/_includes/service-catalog-discovery.html
  app/assets/images/icons/third-party/gitlab.svg
  app/konnect/service-catalog/integrations/datadog.md
  app/konnect/service-catalog/integrations/github.md
  app/konnect/service-catalog/integrations/gitlab.md
  app/konnect/service-catalog/integrations/pagerduty.md
  app/konnect/service-catalog/integrations/swaggerhub.md
  app/konnect/service-catalog/integrations/traceable.md
Labels: do not merge, review:copyedit, ci:manual-approve:link-validation

#8355 Update: Gateway LTS policy
  app/_assets/stylesheets/blockquote-notes.less
  app/_src/gateway/support/index.md
Labels: review:general

#8371 Fix: Vault shema to match generated one
  api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml
  api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml
  api-specs/Gateway-EE/3.8/kong-ee.yaml
  api-specs/Gateway-EE/3.9/kong-ee.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:general

#8372 Fix: Upstream algo section should be enum
  api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml
  api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml
  api-specs/Gateway-EE/3.8/kong-ee.yaml
  api-specs/Gateway-EE/3.9/kong-ee.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:general

#8339 Feat: Secure back end traffic
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_konnect.yml
  app/konnect/gateway-manager/dedicated-cloud-gateways/securing-backend-traffic.md
  app/konnect/gateway-manager/serverless-gateways/index.md
Labels: review:general

#8373 Fix: Vault sync endpoint
  api-specs/Gateway-EE/3.6/kong-ee-3.6.yaml
  api-specs/Gateway-EE/3.7/kong-ee-3.7.yaml
  api-specs/Gateway-EE/3.8/kong-ee.yaml
  api-specs/Gateway-EE/3.9/kong-ee.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:general

#8375 Update push-oas-downstream.yaml
  .github/workflows/push-oas-downstream.yaml
Labels: review:tech

#8377 Fix path to files
  .github/raise-pr-on-change.json
Labels: review:tech

#8374 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8367 docs(kgo): update references for 1.4.x
  app/_data/kong_versions.yml
  app/_src/gateway-operator/reference/custom-resources/1.4.x.md
  app/gateway-operator/changelog.md
Labels: team-k8s, review:general

#8384 Fix: Add missing mesh variables
  jekyll-dev.yml
  jekyll.yml
Labels: review:general

#8385 fix(mesh): fix I'm using mesh service checkbox
  app/_assets/entrypoints/application.js
  app/_assets/javascripts/tabs.js
  app/_assets/stylesheets/navtabs.less
  app/_plugins/kuma-specific/tabs/tabs.rb
  app/_plugins/kuma-specific/tabs/template.erb
Labels: review:tech, review:general

#8390 Fix rubocop issues
  app/_plugins/kuma-specific/tabs/tabs.rb
Labels: review:tech

#8387 docs(mesh): fix navbar to use kong-mesh instead of kuma
  app/_data/docs_nav_mesh_2.10.x.yml
  app/_data/docs_nav_mesh_2.6.x.yml
  app/_data/docs_nav_mesh_2.7.x.yml
  app/_data/docs_nav_mesh_2.8.x.yml
  app/_data/docs_nav_mesh_2.9.x.yml
Labels: review:general

#8381 docs(opentelemetry): better description of OTel logs
  app/_hub/kong-inc/opentelemetry/overview/_index.md
Labels: review:copyedit

#8389 Fix: label KIC 3.4 as LTS
  app/_data/kong_versions.yml
Labels: review:general

#8365 chore: Adjust messaging around Vitals sustaining mode
  app/_src/gateway/breaking-changes/35x.md
  app/gateway/changelog.md
Labels: review:copyedit, ci:manual-approve:link-validation

#8313 docs(gui): update the multiple session feature for Kong Manager.
  app/_src/gateway/kong-manager/auth/sessions.md
Labels: review:copyedit

#8383 Fix SSO Instructions
  app/_includes/md/konnect/okta-sso.md
  app/konnect/dev-portal/access-and-approval/okta-idp.md
  app/konnect/dev-portal/access-and-approval/sso.md
  app/konnect/org-management/auth.md
  app/konnect/org-management/okta-idp.md
  app/konnect/org-management/sso.md
Labels: review:general, review:copyedit

#8150 Feat: Add reserved entity names to References section
  app/_data/docs_nav_gateway_3.9.x.yml
  app/_src/gateway/reference/reserved-entity-names.md
Labels: review:general, review:copyedit

#8340 feat(ai): Community LLM libraries documentation and demonstrations
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_gateway_3.10.x.yml
  app/_data/docs_nav_gateway_3.9.x.yml
  app/_src/gateway/ai-gateway/llm-library-integration-guides/langchain.md
  app/assets/images/guides/llm-libraries/kong-analytics.png
  app/assets/images/guides/llm-libraries/kong-logs.png
Labels: review:tech, review:general, review:copyedit

#8379 Feat: Empty states and new dimensions
  app/konnect/analytics/explorer.md
Labels: review:general

#8395 Automated Konnect changelog update [skip-ci]
  app/konnect/updates.md
Labels: review:general, skip-changelog

#8380 Feat: Dedicated Cloud Gateways logs
  app/_data/docs_nav_konnect.yml
  app/konnect/gateway-manager/dedicated-cloud-gateways/data-plane-logs.md
  app/konnect/gateway-manager/dedicated-cloud-gateways/index.md
Labels: review:general

#8397 Fix: Add missing queue parameter to table
  app/_src/gateway/kong-plugins/queue/reference.md
  app/gateway/changelog.md
Labels: review:general

#8399 Update custom-dns.md
  app/konnect/gateway-manager/dedicated-cloud-gateways/custom-dns.md
Labels: review:general

#8400 Update custom-dns.md
  app/konnect/gateway-manager/serverless-gateways/custom-dns.md
Labels: review:general, ci:manual-approve:link-validation
