Repository Kong/docs.konghq.com, pull requests merged in 2025-02, with the labels that each got.

#8386 kgo: add guide for customizing cluster CA
  app/_data/docs_nav_kgo_1.4.x.yml
  app/_data/docs_nav_kgo_1.5.x.yml
  app/_includes/md/kgo/prerequisites.md
  app/_includes/snippets/gateway-operator/install_with_helm.md
  app/_src/gateway-operator/get-started/kic/create-gateway.md
  app/_src/gateway-operator/get-started/kic/install.md
  app/_src/gateway-operator/production/certificates/custom_ca.md
Labels: team-k8s, review:general, review:sme

#8402 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8403 Update the Dynatrace integration description
  app/_hub/kong-inc/dynatrace/overview/_index.md
  app/_hub/kong-inc/opentelemetry/how-to/_dynatrace.md
Labels: review:general

#8406 extra space between period
  app/_src/gateway/kong-enterprise/fips-support/index.md
Labels: review:general

#8413 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8418 Fix versioning issues with OAS and insomnia buttons
  api-specs/Gateway-EE/3.9/kong-ee.yaml
  api-specs/Gateway-EE/latest/kong-ee.yaml
  api-specs/Gateway-OSS/3.9/kong-oss.yaml
  api-specs/Gateway-OSS/latest/kong-oss.yaml
  app/_plugins/generators/pages/version_data.rb
  app/_src/gateway/admin-api/index_latest.md
Labels: review:general

#8419 Fix: Remove old security policy
  app/_data/docs_nav_gateway_3.10.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_data/docs_nav_gateway_3.9.x.yml
  app/_redirects
Labels: review:general

#8421 docs(plugin/request-validator): clarify supported validators
  app/_hub/kong-inc/request-validator/overview/_index.md
Labels: review:general

#8431 Add kong2kic and kong2tf examples
  app/deck/file/kong2kic.md
  app/deck/file/kong2tf.md
Labels: review:general

#8412 Add dev portals to geo-specific objects list
  app/konnect/geo.md
Labels: review:general

#8432 Add upgrade instructions to decK
  app/deck/file/manipulation/index.md
  app/deck/install/binary.md
  app/deck/install/docker.md
Labels: review:general

#8433 Use KonnectExtension in KGO hybrid topology doc
  app/_src/gateway-operator/topologies/hybrid.md
Labels: review:general

#8414 add docs for konnect entity operation metrics
  app/_src/gateway-operator/production/monitoring/metrics.md
Labels: team-k8s, review:general

#8440 Add signals script tag
  app/_layouts/default.html
Labels: review:general

#8457 Fix: route priority info
  app/_src/gateway/key-concepts/routes/index.md
Labels: review:general

#8456 Fix: transit gateways
  app/konnect/gateway-manager/dedicated-cloud-gateways/transit-gateways.md
Labels: review:general

#8438 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8435 chore: update version compatibility for KIC
  app/_includes/md/kic/support.md
  app/_src/kubernetes-ingress-controller/reference/version-compatibility.md
Labels: team-k8s, review:general

#8447 Update request-transformer-advanced examples to include replace.uri
  app/_hub/kong-inc/request-transformer-advanced/how-to/_index.md
Labels: review:general

#8407 remove try-in-konnect for incompatible plugins
  app/_includes/plugins/sidebar.html
  spec/templates/plugin_with_versions_spec.rb
Labels: review:general

#8462 Fix: Loggly plugin description update
  app/_hub/kong-inc/loggly/overview/_index.md
Labels: review:general

#8467 kgo: fix KongPluginInstallation link
  app/_src/kubernetes-ingress-controller/plugins/custom.md
Labels: team-k8s, review:general

#8454 Release: Gateway 3.7.1.4
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#8468 chore: Gateway 3.6 moves into sunset support
  app/_src/gateway/support/index.md
  app/_src/gateway/support/third-party.md
Labels: review:general

#8469 Archive gateway 3.1
  app/_data/docs_nav_gateway_3.1.x.yml
  app/_data/kong_versions.yml
  app/_redirects
Labels: review:general

#8475 Remove fips plugin doc as inaccurate/misleading
  app/_data/docs_nav_gateway_3.10.x.yml
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/docs_nav_gateway_3.3.x.yml
  app/_data/docs_nav_gateway_3.4.x.yml
  app/_data/docs_nav_gateway_3.5.x.yml
  app/_data/docs_nav_gateway_3.6.x.yml
  app/_data/docs_nav_gateway_3.7.x.yml
  app/_data/docs_nav_gateway_3.8.x.yml
  app/_data/docs_nav_gateway_3.9.x.yml
  app/_src/gateway/kong-enterprise/fips-support/plugins.md
  changelog.md
Labels: review:general, skip-changelog

#8473 docs(mesh/rbac): add warning about unbounded access actions granting full access
  app/_src/mesh/features/rbac.md
Labels: review:general

#8476 Fix fips install
  app/_src/gateway/kong-enterprise/fips-support/install.md
Labels: review:general

#8478 Fix Konnect cluster and telemetry hostnames
  app/konnect/network.md
Labels: review:general

#8483 kic: update latest version to 3.4.3
  app/_data/kong_versions.yml
Labels: team-k8s, review:general

#8459 docs(json-threat-protection): add a description for the supported HTTP methods
  app/_hub/kong-inc/json-threat-protection/overview/_index.md
Labels: review:general, pr/please review

#8470 Archive gateway 3.2
  app/_data/docs_nav_gateway_3.2.x.yml
  app/_data/kong_versions.yml
  app/_redirects
Labels: review:general

#8410 Feat: service catalog score cards
  app/_data/docs_nav_konnect.yml
  app/assets/images/products/konnect/konnect-service-catalog-scorecards.png
  app/konnect/service-catalog/index.md
  app/konnect/service-catalog/scorecards/index.md
Labels: review:general
