Repository Kong/docs.konghq.com, pull requests merged in 2025-05, with the labels that each got.

#8741 feat(kgo): add watchNamespaces docs for KGO 1.6
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_kgo_1.6.x.yml
  app/_src/gateway-operator/guides/hardening/control-plane-watch-namespaces.md
Labels: team-k8s, review:general

#8755 chore(kgo): fix latest Kong CE version variable
  app/_src/gateway-operator/get-started/kic/create-gateway-konnect-crds.md
Labels: team-k8s, review:general

#8758 Update kong-vault.md
  app/_src/kubernetes-ingress-controller/guides/security/kong-vault.md
Labels: review:general

#8748 feat(kgo): Add guide page for managing Konnect transit gateways in KGO
  app/_data/docs_nav_kgo_1.6.x.yml
  app/_src/gateway-operator/guides/konnect-entities/cloud-gateways-transit-gateway.md
Labels: team-k8s, review:general

#8754 feat(dcr): updates the dev portal docs to include dcr details [TDX-5574]
  api-specs/Konnect/v3/yaml/api-builder.yaml
  api-specs/Konnect/v3/yaml/portal-management.yaml
  app/_data/docs_nav_dev-portal.yml
  app/dev-portal/access-and-approvals/developers.md
  app/dev-portal/access-and-approvals/index.md
  app/dev-portal/app-reg/auth-strategies/key-auth/index.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/auth0.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/azure.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/curity.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/custom.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/index.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/okta.md
  app/dev-portal/app-reg/auth-strategies/oidc/dynamic-client-registration/auth0.md
  app/dev-portal/app-reg/auth-strategies/oidc/dynamic-client-registration/azure.md
  app/dev-portal/app-reg/auth-strategies/oidc/dynamic-client-registration/curity.md
  app/dev-portal/app-reg/auth-strategies/oidc/dynamic-client-registration/custom.md
  app/dev-portal/app-reg/auth-strategies/oidc/dynamic-client-registration/index.md
  app/dev-portal/app-reg/auth-strategies/oidc/dynamic-client-registration/okta.md
  app/dev-portal/app-reg/auth-strategies/oidc/index.md
  app/dev-portal/app-reg/auth-strategies/oidc/self-managed-oidc.md
  app/dev-portal/app-reg/index.md
  app/dev-portal/portals/index.md
  app/dev-portal/portals/publishing.md
  app/dev-portal/portals/settings/security.md
  app/konnect/dev-portal/konnect-portal-management-automation.md
Labels: review:tech, review:sme

#8763 Fix: add missing Kong Manager changelog entries
  app/gateway/changelog.md
Labels: review:general

#8766 Automated Konnect changelog update [skip-ci]
  app/konnect/updates.md
Labels: review:general, skip-changelog

#8768 Revert "feat(dcr): updates the dev portal docs to include dcr details [TDX-5574]"
  api-specs/Konnect/v3/yaml/api-builder.yaml
  api-specs/Konnect/v3/yaml/portal-management.yaml
  app/_data/docs_nav_dev-portal.yml
  app/dev-portal/access-and-approvals/developers.md
  app/dev-portal/access-and-approvals/index.md
  app/dev-portal/app-reg/auth-strategies/key-auth/index.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/auth0.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/azure.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/curity.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/custom.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/index.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/okta.md
  app/dev-portal/app-reg/auth-strategies/oidc/dynamic-client-registration/auth0.md
  app/dev-portal/app-reg/auth-strategies/oidc/dynamic-client-registration/azure.md
  app/dev-portal/app-reg/auth-strategies/oidc/dynamic-client-registration/curity.md
  app/dev-portal/app-reg/auth-strategies/oidc/dynamic-client-registration/custom.md
  app/dev-portal/app-reg/auth-strategies/oidc/dynamic-client-registration/index.md
  app/dev-portal/app-reg/auth-strategies/oidc/dynamic-client-registration/okta.md
  app/dev-portal/app-reg/auth-strategies/oidc/index.md
  app/dev-portal/app-reg/auth-strategies/oidc/self-managed-oidc.md
  app/dev-portal/app-reg/index.md
  app/dev-portal/portals/index.md
  app/dev-portal/portals/publishing.md
  app/dev-portal/portals/settings/security.md
  app/konnect/dev-portal/konnect-portal-management-automation.md
Labels: review:general

#8764 update docs for KGO v1.6
  .github/workflows/linting.yml
  app/_data/kong_versions.yml
  app/_src/gateway-operator/reference/cli-arguments/1.6.x.md
  app/_src/gateway-operator/reference/custom-resources/1.6.x.md
  app/_src/gateway-operator/reference/version-compatibility.md
Labels: team-k8s, review:general

#8771 chore(kgo): KGO 1.6 CRD reference update and changelog
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_kgo_1.6.x.yml
  app/_includes/md/k8s/crd-ref/konnect_cloud_gateway_transit_gateway_description.md
  app/_includes/md/k8s/crd-ref/watch_namespace_grant_description.md
  app/_src/gateway-operator/reference/custom-resources/1.6.x.md
  app/gateway-operator/changelog.md
Labels: team-k8s, review:general

#8773 Dev site banner
  app/_assets/entrypoints/application.js
  app/_assets/javascripts/promo-banner.js
  app/_assets/javascripts/views/SpecView.vue
  app/_assets/stylesheets/header-v2.less
  app/_assets/stylesheets/header.less
  app/_assets/stylesheets/hub-landing-page.less
  app/_assets/stylesheets/page-header.less
  app/_assets/stylesheets/page.less
  app/_assets/stylesheets/pages/docs.less
  app/_assets/stylesheets/sidebar.less
  app/_includes/nav-v2.html
  app/_layouts/default.html
  app/_plugins/hooks/dev_site_link.rb
  jekyll-dev.yml
  jekyll.yml
  redirects.yaml
Labels: review:general

#8776 Fix banner spacing and text
  app/_assets/stylesheets/header.less
  app/_includes/nav-v2.html
Labels: review:general

#8775 Update parameter-reference.md for vitals
  app/konnect/gateway-manager/data-plane-nodes/parameter-reference.md
Labels: review:general

#8781 fix: Konnect billing dashboard link
  app/konnect/account-management/index.md
Labels: review:general

#8779 More mobile fixes due to the banner
  app/_assets/javascripts/views/SpecView.vue
  app/_assets/stylesheets/header.less
  app/_assets/stylesheets/page-header.less
  app/_assets/stylesheets/page.less
  app/_assets/stylesheets/sidebar.less
Labels: review:tech

#8786 Fix AI RAG Injector to correct template
  app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
Labels: review:copyedit

#8783 kic: Fix example command for tls termination
  app/_src/kubernetes-ingress-controller/guides/services/tls.md
Labels: team-k8s, review:general

#8711 Feat: Gitlab self-hosted
  app/konnect/service-catalog/integrations/gitlab.md
Labels: do not merge, review:sme

#8806 fix: Add key auth step directly in central consumers doc
  app/konnect/centralized-consumer-management.md
Labels: review:general

#8791 update GatewayAPI version for KGO
  app/_includes/md/kgo/prerequisites.md
Labels: team-k8s, review:general, area/gateway-api

#8815 Update Service Catalog Roles
  app/konnect/org-management/teams-and-roles/roles-reference.md
Labels: review:general

#8818 Fix 3.10 admin API links
  app/_src/gateway/admin-api/index_latest.md
Labels: review:general, ci:manual-approve:linting

#8811 update MeshOPA targetRef support matrix and fix outdated examples
  app/_src/mesh/features/meshopa.md
Labels: review:general
