Repository Kong/docs.konghq.com, pull requests merged in 2025-04, with the labels that each got.

#8648 Fix: Update config-store.md for decK tab steps
  app/konnect/gateway-manager/configuration/config-store.md
Labels: review:general, review:copyedit

#8560 feat: KGO 1.5 konnect dataplanes
  app/_data/docs_nav_kgo_1.5.x.yml
  app/_includes/md/kgo/konnect-dataplanes-prerequisites.md
  app/_includes/md/kgo/konnect-entities-prerequisites.md
  app/_plugins/blocks/navtabs.rb
  app/_src/gateway-operator/customization/custom-konnect-certificates.md
  app/_src/gateway-operator/get-started/kic/create-gateway-konnect-crds.md
  app/_src/gateway-operator/get-started/kic/install.md
  app/_src/gateway-operator/get-started/konnect/create-konnectextension.md
  app/_src/gateway-operator/get-started/konnect/create-route-konnect-crds.md
  app/_src/gateway-operator/get-started/konnect/deploy-data-plane-with-konnectextension.md
  app/_src/gateway-operator/get-started/konnect/deploy-data-plane.md
  app/_src/gateway-operator/guides/migrating/migrate-from-1.4-to-1.5.md
  app/_src/gateway-operator/reference/konnectextension.md
Labels: team-k8s, review:general

#8576 kgo: add KGO 1.5 Cloud Gateways Data Plane Group Configuration guide
  app/_data/docs_nav_kgo_1.5.x.yml
  app/_includes/md/kgo/konnect-cloud-gateways-provider-account.md
  app/_includes/md/kgo/konnect-entities-prerequisites.md
  app/_src/gateway-operator/guides/konnect-entities/cloud-gateways-data-plane-group-configuration.md
  app/_src/gateway-operator/guides/konnect-entities/cloud-gateways-network.md
Labels: team-k8s, review:general

#8651 Fix small typo under the OCI Artifacts section in distribution.md
  app/_src/gateway/plugin-development/distribution.md
Labels: review:general

#8588 kgo: add KGO 1.5 docs
  .github/styles/kong/dictionary.txt
  app/_data/docs_nav_kgo_1.5.x.yml
  app/_data/kong_versions.yml
  app/_src/gateway-operator/reference/cli-arguments/1.5.x.md
  app/_src/gateway-operator/reference/version-compatibility.md
  app/gateway-operator/changelog.md
Labels: team-k8s, review:general

#8653 kgo: make 1.5 latest and fix Konnect DataPlane Group configuration docs
  app/_data/kong_versions.yml
  app/_src/gateway-operator/guides/konnect-entities/cloud-gateways-data-plane-group-configuration.md
  app/_src/gateway-operator/guides/konnect-entities/cloud-gateways-network.md
Labels: team-k8s, review:general

#8654 Fix: spelling
  app/konnect/gateway-manager/data-plane-nodes/upgrade.md
Labels: review:general

#8655 Automated Konnect changelog update [skip-ci]
  app/konnect/updates.md
Labels: review:general, skip-changelog

#8636 Add AI RAG Injector Admin api usage
  app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
Labels: review:copyedit, ci:manual-approve:link-validation

#8656 Fix: Priority load balancing example
  app/_hub/kong-inc/ai-proxy-advanced/how-to/_load-balancing.md
Labels: review:general

#8659 fix(docs): Add missing bracket in URL link
  app/_hub/kong-inc/request-callout/overview/_index.md
Labels: review:general

#8662 Fix version dropdown in plugin pages
  app/_plugins/generators/plugin_single_source/plugin/page_data.rb
Labels: review:general

#8663 fix(mesh): adjust outdated fragment about AccessRoleBinding for versions higher than 2.5
  app/_src/mesh/features/rbac.md
Labels: review:sme

#8668 [AI RAG Injector] How to - Update title of step 2
  app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
Labels: review:copyedit

#8669 Remove outdated Runtime groups parameter
  app/konnect/gateway-manager/control-plane-groups/migrate.md
Labels: review:general

#8671 Fix: Missing Auth Headers & Request Body in Token Creation API Call
  app/konnect/org-management/system-accounts.md
Labels: review:general

#8665 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8670 Fix: Add pagination to rbac endpoints
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:general

#8676 chore(kic): fix KIC vs Gateway API compatibility table
  app/_src/kubernetes-ingress-controller/reference/version-compatibility.md
Labels: team-k8s, review:general

#8661 docs(plugin): only one plugin instance is executed for the current request
  app/_includes/md/about-plugins.md
Labels: review:general

#8679 docs(mesh): don't display feature that was removed
  app/_src/mesh/features/kds-auth.md
Labels: review:general

#8693 Automated Konnect changelog update [skip-ci]
  app/konnect/updates.md
Labels: review:general, skip-changelog

#8330 feat: Service Catalog Slack integration
  app/_data/docs_nav_konnect.yml
  app/_data/tables/konnect/integrations.yml
  app/assets/images/icons/third-party/slack.svg
  app/konnect/service-catalog/integrations/slack.md
Labels: do not merge, review:copyedit

#8694 Automated Konnect changelog update [skip-ci]
  app/konnect/updates.md
Labels: review:general, skip-changelog

#8688 Update cluster_type
  app/konnect/reference/terraform.md
Labels: review:copyedit

#8687 Fix links of ai-semantic-cache
  app/_src/gateway/production/logging/ai-analytics.md
Labels: review:general, pr/please review

#8686 fix: fix ai-proxy-advanced balancer doc link typo
  app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md
Labels: review:general, pr/please review

#8689 Added a note in changelog for ai-rate-limiting-advanced plugin
  app/_hub/kong-inc/ai-rate-limiting-advanced/_changelog.md
  app/_src/gateway/breaking-changes/39x.md
Labels: review:general

#8695 chore: fix Gateway breaking changes changelog for 3.9
  app/_src/gateway/breaking-changes/39x.md
Labels: review:general

#8696 Fix incorrect description of routing conflict rules
  app/_src/gateway/kong-enterprise/workspaces/index.md
Labels: review:general

#8699 feat(sdk): automated oas update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
Labels: review:general

#8702 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8705 Release: Gateway 2.8.4.14
  app/_data/kong_versions.yml
  app/gateway/2.8.x/reference/cli.md
  app/gateway/changelog.md
Labels: review:general

#8672 [TDX-5270] Snippets docs
  app/_data/docs_nav_dev-portal.yml
  app/dev-portal/portals/customization/custom-pages.md
  app/dev-portal/portals/customization/snippets.md
Labels: review:general

#8703 Updated ai-rag-injector docs
  app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
Labels: review:general

#8708 docs(portal): snippets page header
  app/dev-portal/portals/customization/snippets.md
Labels: review:general

#8681 Release: Gateway 3.10.0.1
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#8710 Fix typo
  app/_src/gateway-operator/get-started/konnect/create-konnectextension.md
Labels: review:copyedit

#8714 Add gateway-ee 3.10 api-spec
  api-specs/Gateway-EE/3.10/kong-ee.yaml
Labels: review:general

#8713 Feat: New Request Callout examples
  app/_hub/kong-inc/request-callout/overview/_index.md
Labels: review:general

#8715 fix: Add 3.10 to Konnect compatibility table
  app/konnect/compatibility.md
Labels: review:general

#8716 Update aws-privatelink.md
  app/konnect/private-connections/aws-privatelink.md
Labels: review:general

#8721 Update aws-privatelink.md
  app/konnect/private-connections/aws-privatelink.md
Labels: bug, review:general

#8719 chore(kic): update versions
  app/_data/kong_versions.yml
Labels: team-k8s, review:general

#8720 fix(ai): update options-param templating documentation
  app/_hub/kong-inc/ai-proxy/how-to/_sdk-usage.md
Labels: Core Team review

#8718 update ai-sanitizer doc
  app/_hub/kong-inc/ai-sanitizer/overview/_index.md
Labels: review:general

#8722 chore: Update list of AI plugins links
  app/_includes/md/ai-plugins-links.md
Labels: review:general

#8724 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8730 Update transit-gateways.md
  .github/styles/kong/dictionary.txt
  app/konnect/gateway-manager/dedicated-cloud-gateways/transit-gateways.md
Labels: review:general

#8674 CSRE-4181 Private Link for Konnect Admin API documentation
  app/konnect/private-connections/aws-privatelink.md
Labels: review:sme

#8734 privatelink: remove duplicate region
  app/konnect/private-connections/aws-privatelink.md
Labels: review:sme

#8556 Feat: Custom plugin streaming
  app/_data/docs_nav_konnect.yml
  app/konnect/gateway-manager/dedicated-cloud-gateways/custom-plugins.md
  app/konnect/gateway-manager/dedicated-cloud-gateways/index.md
  app/konnect/gateway-manager/plugins/add-custom-plugin.md
  app/konnect/gateway-manager/plugins/index.md
Labels: review:copyedit

#8735 Automated Konnect changelog update [skip-ci]
  app/konnect/updates.md
Labels: review:general, skip-changelog

#8727 update script for ai-rag
  app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
Labels: review:tech, review:general

#8733 chore: Mention that we don't support kafka 4.0
  app/_hub/kong-inc/confluent-consume/overview/_index.md
  app/_hub/kong-inc/confluent/overview/_index.md
  app/_hub/kong-inc/kafka-consume/overview/_index.md
  app/_hub/kong-inc/kafka-log/overview/_index.md
  app/_hub/kong-inc/kafka-upstream/overview/_index.md
Labels: review:general

#8732 update: Warn users about very high sync rates in RLA
  app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
  app/_hub/kong-inc/rate-limiting/overview/_index.md
Labels: review:copyedit, review:sme

#8739 private-link: fix regions list
  app/konnect/private-connections/aws-privatelink.md
Labels: review:sme

#8743 fix: Remove note about 1:1 Konnect team mapping
  app/_includes/md/konnect/generic-sso.md
Labels: review:general

#8740 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8751 fix: Incorrect links in azure content safety docs
  app/_hub/kong-inc/ai-azure-content-safety/overview/_index.md
Labels: bug, review:general

#8747 fix: update amazon linux 2 eol date
  app/_data/tables/support/gateway/versions/310.yml
  app/_data/tables/support/gateway/versions/34.yml
Labels: review:general, area/gateway-api, pr/please review
