Repository Kong/docs.konghq.com, pull requests merged in 2025-03, with the labels that each got.

#8401 Dev Portal v3 docs
  app/_data/docs_nav_dev-portal.yml
  app/_data/kong_versions.yml
  app/_includes/breadcrumbs.html
  app/_includes/docs-sidebar.html
  app/_plugins/generators/algolia/base.rb
  app/_plugins/generators/site_product_data.rb
  app/assets/images/products/konnect/dev-portal-v3/azure-group-claim.png
  app/assets/images/products/konnect/dev-portal-v3/create-portal.png
  app/assets/images/products/konnect/dev-portal-v3/dcr-bearer-tokens.png
  app/assets/images/products/konnect/dev-portal-v3/kongair-example.png
  app/assets/images/products/konnect/dev-portal-v3/visibility-access-combinations.png
  app/dev-portal/access-and-approvals/developers.md
  app/dev-portal/access-and-approvals/index.md
  app/dev-portal/access-and-approvals/sso.md
  app/dev-portal/access-and-approvals/teams.md
  app/dev-portal/apis/docs.md
  app/dev-portal/apis/gateway-service-link.md
  app/dev-portal/apis/index.md
  app/dev-portal/apis/versioning.md
  app/dev-portal/app-reg/auth-strategies/key-auth/index.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/auth0.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/azure.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/curity.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/custom.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/index.md
  app/dev-portal/app-reg/auth-strategies/oidc/dcr/okta.md
  app/dev-portal/app-reg/auth-strategies/oidc/index.md
  app/dev-portal/app-reg/index.md
  app/dev-portal/index.md
  app/dev-portal/portals/audit-logs/index.md
  app/dev-portal/portals/audit-logs/replay-job.md
  app/dev-portal/portals/audit-logs/webhook.md
  app/dev-portal/portals/customization/appearance.md
  app/dev-portal/portals/customization/custom-pages.md
  app/dev-portal/portals/customization/customization.md
  app/dev-portal/portals/customization/portal-editor.md
  app/dev-portal/portals/index.md
  app/dev-portal/portals/publishing.md
  app/dev-portal/portals/settings/custom-domains.md
  app/dev-portal/portals/settings/general.md
  app/dev-portal/portals/settings/security.md
  app/dev-portal/portals/settings/team-mapping.md
  jekyll-dev.yml
  jekyll.yml
Labels: review:tech, review:general

#8493 Fix Dev Portal icons
  app/_data/docs_nav_dev-portal.yml
  tools/_utilities/lib/nav-to-index-page.js
Labels: review:general

#8495 Sync Konnect OAS Data
  app/_data/konnect_oas_data.json
Labels: review:general, skip-changelog

#8499 Add link to Vacuum to deck file lint
  app/deck/file/lint.md
Labels: review:general

#8490 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8484 docs(mesh/rbac): add subsection to restrict default AccessRoleBinding
  app/_src/mesh/features/rbac.md
Labels: review:general

#8509 Fix: Update cp-dp-proxy.md
  app/_src/gateway/production/networking/cp-dp-proxy.md
Labels: review:general

#8487 feat(gw): SBOMs now hosted on Cloudsmith
  app/_src/gateway/support/sbom.md
Labels: review:general

#8508 Add banner for Portal v3 beta docs
  app/_layouts/docs-v2.html
Labels: review:general

#8507 ADd padding to api specs
  app/_assets/javascripts/views/SpecView.vue
Labels: review:general

#8512 Feat: Metrics api
  api-specs/Konnect/v4/yaml/metrics.yaml
  app/_api/konnect/metrics/_index.md
  app/_data/konnect_oas_data.json
Labels: review:general

#8522 Update index.md
  app/konnect/gateway-manager/serverless-gateways/index.md
Labels: review:general

#8521 Fix: cluster key in hybrid mode setup page
  app/_src/gateway/production/deployment-topologies/hybrid-mode/setup.md
Labels: review:general

#8527 docs(portal): reserved paths
  .github/styles/kong/dictionary.txt
  app/dev-portal/portals/customization/custom-pages.md
Labels: review:general, ci:manual-approve:link-validation, review:sme

#8524 Rename title in transit-gateways.md
  app/konnect/gateway-manager/dedicated-cloud-gateways/transit-gateways.md
Labels: review:general

#8486 Update log_custom_fields_by_lua.md with note of using dots
  app/_includes/md/plugins-hub/log_custom_fields_by_lua.md
Labels: review:copyedit

#8533 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8520 Incremental config sync doc
  app/_data/docs_nav_gateway_3.10.x.yml
  app/_src/gateway/production/deployment-topologies/hybrid-mode/incremental-config-sync.md
  app/_src/gateway/production/deployment-topologies/hybrid-mode/index.md
Labels: review:sme

#8529 Fix: remove url for non-existent page
  app/_data/docs_nav_dev-portal.yml
Labels: review:general

#8535 docs(portal): add reserved path for api proxy
  app/dev-portal/portals/customization/custom-pages.md
Labels: review:general

#8217 Feat: Add Active Tracing Tech preview documentation
  app/_data/docs_nav_konnect.yml
  app/assets/images/products/gateway/active-tracing-spans.png
  app/konnect/gateway-manager/active-tracing.md
Labels: review:sme

#8506 feat: add docs for kafka-consume and confluent-consume
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/confluent-consume/_changelog.md
  app/_hub/kong-inc/confluent-consume/_metadata/_index.yml
  app/_hub/kong-inc/confluent-consume/overview/_index.md
  app/_hub/kong-inc/confluent-consume/versions.yml
  app/_hub/kong-inc/kafka-consume/_changelog.md
  app/_hub/kong-inc/kafka-consume/_metadata/_index.yml
  app/_hub/kong-inc/kafka-consume/overview/_index.md
  app/_hub/kong-inc/kafka-consume/versions.yml
  app/assets/images/icons/hub/kong-inc_confluent-consume.png
  app/assets/images/icons/hub/kong-inc_kafka-consume.png
Labels: review:general

#8551 docs(kic): add introduction of migration scripts in custom plugins
  app/_src/kubernetes-ingress-controller/plugins/custom.md
Labels: team-k8s, review:general

#8546 feat(kafka-upstream): add some how-to document pages for the new feature of kong gateway's kafka-upstream plugin
  app/_hub/kong-inc/kafka-upstream/how-to/_custom-message-format.md
  app/_hub/kong-inc/kafka-upstream/how-to/_multiple-topics-and-acl.md
  app/_hub/kong-inc/kafka-upstream/overview/_index.md
Labels: review:tech, review:general

#8547 kgo: add KGO 1.5 guide for consumer credential Secrets
  app/_src/gateway-operator/guides/konnect-entities/consumer-and-consumergroup.md
Labels: team-k8s, review:general

#8552 kgo: add KGO 1.5 guide for managing Konnect Cloud Gateways Networks
  app/_data/docs_nav_kgo_1.5.x.yml
  app/_includes/md/k8s/crd-ref/ai_gateway_description.md
  app/_includes/md/k8s/crd-ref/control_plane_description.md
  app/_includes/md/k8s/crd-ref/data_plane_description.md
  app/_includes/md/k8s/crd-ref/data_plane_metrics_extension_description.md
  app/_includes/md/k8s/crd-ref/gateway_configuration_description.md
  app/_includes/md/k8s/crd-ref/ingress_class_parameters_description.md
  app/_includes/md/k8s/crd-ref/kong_ca_certificate_description.md
  app/_includes/md/k8s/crd-ref/kong_certificate_description.md
  app/_includes/md/k8s/crd-ref/kong_cluster_plugin_description.md
  app/_includes/md/k8s/crd-ref/kong_consumer_description.md
  app/_includes/md/k8s/crd-ref/kong_consumer_group_description.md
  app/_includes/md/k8s/crd-ref/kong_credential_acl_description.md
  app/_includes/md/k8s/crd-ref/kong_credential_api_key_description.md
  app/_includes/md/k8s/crd-ref/kong_credential_basic_auth_description.md
  app/_includes/md/k8s/crd-ref/kong_credential_hmac_description.md
  app/_includes/md/k8s/crd-ref/kong_credential_jwt_description.md
  app/_includes/md/k8s/crd-ref/kong_custom_entity_description.md
  app/_includes/md/k8s/crd-ref/kong_data_plane_client_certificate_description.md
  app/_includes/md/k8s/crd-ref/kong_ingress_description.md
  app/_includes/md/k8s/crd-ref/kong_key_description.md
  app/_includes/md/k8s/crd-ref/kong_key_set_description.md
  app/_includes/md/k8s/crd-ref/kong_license_description.md
  app/_includes/md/k8s/crd-ref/kong_plugin_binding_description.md
  app/_includes/md/k8s/crd-ref/kong_plugin_description.md
  app/_includes/md/k8s/crd-ref/kong_plugin_installation_description.md
  app/_includes/md/k8s/crd-ref/kong_route_description.md
  app/_includes/md/k8s/crd-ref/kong_service_description.md
  app/_includes/md/k8s/crd-ref/kong_service_facade_description.md
  app/_includes/md/k8s/crd-ref/kong_sni_description.md
  app/_includes/md/k8s/crd-ref/kong_target_description.md
  app/_includes/md/k8s/crd-ref/kong_upstream_description.md
  app/_includes/md/k8s/crd-ref/kong_upstream_policy_description.md
  app/_includes/md/k8s/crd-ref/kong_vault_description.md
  app/_includes/md/k8s/crd-ref/konnect_api_auth_configuration_description.md
  app/_includes/md/k8s/crd-ref/konnect_cloud_gateway_data_plane_group_configuration_description.md
  app/_includes/md/k8s/crd-ref/konnect_cloud_gateway_network_description.md
  app/_includes/md/k8s/crd-ref/konnect_extension_description.md
  app/_includes/md/k8s/crd-ref/konnect_gateway_control_plane_description.md
  app/_includes/md/k8s/crd-ref/tcp_ingress_description.md
  app/_includes/md/k8s/crd-ref/udp_ingress_description.md
  app/_src/gateway-operator/guides/konnect-entities/cloud-gateways-network.md
  app/_src/gateway-operator/reference/custom-resources/1.5.x.md
Labels: team-k8s, review:general

#8572 Pin all GitHub Actions
  .github/workflows/autogenerated-warning.yml
  .github/workflows/build-docs-pdf.yml
  .github/workflows/build-plugin-pdf.yml
  .github/workflows/check-links.yml
  .github/workflows/ci-autofix.yml
  .github/workflows/dispatch-docs-update.yml
  .github/workflows/fetch-konnect-changelog.yml
  .github/workflows/generate-changelog.yml
  .github/workflows/install-instructions-test.yml
  .github/workflows/linting.yml
  .github/workflows/push-oas-downstream.yaml
  .github/workflows/require-review-label.yml
  .github/workflows/run-tests.yml
  .github/workflows/scheduled-broken-link-checker.yml
  .github/workflows/security.yaml
  .github/workflows/send-docs-for-translation.yml
  .github/workflows/send-plugins-for-translation.yml
  .github/workflows/sync-konnect-oas-data.yml
  .github/workflows/sync-kuma-submodule.yml
  .github/workflows/sync-submodules.yml
Labels: review:general

#8575 fix(actions): use kong changed files
  .github/workflows/ci-autofix.yml
  .github/workflows/linting.yml
Labels: review:tech

#8561 Add API for Gateway versions
  app/_data/kong_versions.yml
  app/_plugins/hooks/supported_version_api.rb
Labels: review:tech

#8550 feat: add docs for CSP header in GW 3.10
  app/_data/docs_nav_gateway_3.10.x.yml
  app/_src/gateway/kong-manager/strengthen-security.md
Labels: review:copyedit

#8580 fix(konnect): update Azure SAML claim attributes
  app/konnect/reference/saml-idp-mappings.md
Labels: bug, review:tech

#8578 Update incremental config sync flags
  app/_src/gateway/production/deployment-topologies/hybrid-mode/incremental-config-sync.md
Labels: review:general

#8584 docs(ai-semantic-cache): add note on cache control behaviour
  app/_hub/kong-inc/ai-semantic-cache/overview/_index.md
Labels: review:copyedit

#8530 AI RLA: Support for multiple limits and window sizes
  app/_hub/kong-inc/ai-rate-limiting-advanced/how-to/_index.md
Labels: review:general

#8562 Add cli and pdk docs
  app/_src/gateway/plugin-development/pdk/index.md
  app/_src/gateway/plugin-development/pdk/kong.client.md
  app/_src/gateway/plugin-development/pdk/kong.jwe.md
  app/_src/gateway/plugin-development/pdk/kong.log.md
  app/_src/gateway/plugin-development/pdk/kong.response.md
  app/_src/gateway/plugin-development/pdk/kong.service.request.md
  app/_src/gateway/reference/cli.md
Labels: review:autodoc, skip-changelog

#8555 feat: AppDynamics agent ARM support
  app/_hub/kong-inc/app-dynamics/overview/_index.md
Labels: review:general

#8564 Chore: Generate kong.conf 3.10
  app/_data/docs_nav_gateway_3.10.x.yml
  app/_src/gateway/reference/configuration/configuration-3.10.x.md
Labels: review:general, skip-changelog

#8590 Fix APIOps introduction
  app/deck/apiops/index.md
Labels: review:general

#8593 fix: s/consumer/consume/g
  app/_hub/kong-inc/confluent-consume/overview/_index.md
  app/_hub/kong-inc/kafka-consume/overview/_index.md
Labels: review:general

#8553 feat(mesh): add Mesh Terraform guide
  app/_data/docs_nav_mesh_2.10.x.yml
  app/_src/mesh/guides/deploy-kong-mesh-using-terraform-and-konnect.md
Labels: review:general, review:copyedit, ci:manual-approve:link-validation, review:sme

#8595 CSRE-3763 Added documentation for 2 new edge gateway regions
  app/konnect/private-connections/aws-privatelink.md
Labels: review:sme

#8579 fix: Dynatrace deployment options
  app/_hub/kong-inc/dynatrace/_metadata/_index.yml
Labels: review:general

#8597 Add AI pricing disclaimer
  app/_data/extensions.yml
  app/hub/plugins/license-tiers.md
Labels: review:general

#8583 docs(ai-proxy-advanced): add new feature description for ai-proxy-advanced in 3.10
  app/_hub/kong-inc/ai-proxy-advanced/how-to/_load-balancing.md
  app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md
Labels: review:copyedit

#8577 3.10 API spec changes
  api-specs/Gateway-EE/latest/kong-ee.yaml
Labels: review:general

#8585 feat(mesh): add Terraform import guide
  app/_data/docs_nav_mesh_2.10.x.yml
  app/_src/mesh/guides/import-existing-konnect-kong-mesh-deployment-to-terraform.md
Labels: review:general, review:copyedit, ci:manual-approve:link-validation, review:sme

#8605 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8608 docs(partials): add info about using a parital with custom plugin
  app/_src/gateway/kong-enterprise/partials.md
Labels: review:general

#8609 [KGO] chore: remove readiness probe from gateways
  app/_src/gateway-operator/get-started/kic/create-gateway.md
  app/_src/gateway-operator/guides/autoscaling-workloads/overview.md
  app/_src/gateway-operator/guides/plugin-distribution.md
  app/_src/gateway-operator/guides/upgrade/data-plane/blue-green.md
  app/_src/gateway-operator/topologies/dbless.md
Labels: review:general

#8513 Feat: Request callout plugin
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/request-callout/_metadata/_index.yml
  app/_hub/kong-inc/request-callout/changelog.md
  app/_hub/kong-inc/request-callout/overview/_index.md
  app/_hub/kong-inc/request-callout/versions.yml
  app/assets/images/icons/hub/kong-inc_request-callout.png
Labels: review:sme

#8618 Fix links to api-endpoints
  app/_src/gateway/admin-api/index_latest.md
  app/_src/gateway/kong-enterprise/index.md
  app/_src/gateway/kong-enterprise/partials.md
Labels: review:general

#8619 Fix partials no if_version
  app/_src/gateway/admin-api/index_latest.md
Labels: review:general

#8541 Release: Gateway 3.4.3.17
  app/_data/kong_versions.yml
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation

#8616 Chore: Move Gateway 2.8 into sunset support
  app/_src/gateway/support/index.md
  app/_src/gateway/support/third-party.md
  app/gateway/2.8.x/support-policy.md
Labels: review:general

#8479 Feat: AI sanitizer plugin
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/ai-sanitizer/_changelog.md
  app/_hub/kong-inc/ai-sanitizer/_metadata/_index.yml
  app/_hub/kong-inc/ai-sanitizer/how-to/_index.md
  app/_hub/kong-inc/ai-sanitizer/overview/_index.md
  app/_hub/kong-inc/ai-sanitizer/versions.yml
  app/assets/images/icons/hub/kong-inc_ai-data-sanitization.png
  app/assets/images/icons/hub/kong-inc_ai-sanitizer.png
Labels: review:sme

#8567 chore: Gateway 3.10 SBOM link
  app/_src/gateway/support/sbom.md
Labels: do not merge, review:general

#8607 feat: add ai-rag-injector plugin
  app/_hub/kong-inc/ai-rag-injector/_changelog.md
  app/_hub/kong-inc/ai-rag-injector/_metadata/_index.yml
  app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
  app/_hub/kong-inc/ai-rag-injector/overview/_index.md
  app/_hub/kong-inc/ai-rag-injector/versions.yml
  app/assets/images/icons/hub/kong-inc_ai-rag-injector.png
Labels: review:copyedit

#8623 fix: 3.10 API update
  api-specs/Gateway-EE/latest/kong-ee.yaml
  app/_data/konnect_oas_data.json
Labels: review:general

#8589 Chore: Gateway 3.10 changelog
  .github/styles/kong/dictionary.txt
  app/_hub/kong-inc/ai-proxy-advanced/_changelog.md
  app/_hub/kong-inc/ai-proxy/_changelog.md
  app/_hub/kong-inc/ai-rate-limiting-advanced/_changelog.md
  app/_hub/kong-inc/ai-request-transformer/_changelog.md
  app/_hub/kong-inc/ai-response-transformer/_changelog.md
  app/_hub/kong-inc/ai-semantic-cache/_changelog.md
  app/_hub/kong-inc/ai-semantic-prompt-guard/_changelog.md
  app/_hub/kong-inc/app-dynamics/_changelog.md
  app/_hub/kong-inc/aws-lambda/_changelog.md
  app/_hub/kong-inc/confluent/_changelog.md
  app/_hub/kong-inc/cors/_changelog.md
  app/_hub/kong-inc/file-log/_changelog.md
  app/_hub/kong-inc/forward-proxy/_changelog.md
  app/_hub/kong-inc/grpc-gateway/_changelog.md
  app/_hub/kong-inc/grpc-web/_changelog.md
  app/_hub/kong-inc/jq/_changelog.md
  app/_hub/kong-inc/json-threat-protection/_changelog.md
  app/_hub/kong-inc/jwt-signer/_changelog.md
  app/_hub/kong-inc/kafka-upstream/_changelog.md
  app/_hub/kong-inc/ldap-auth-advanced/_changelog.md
  app/_hub/kong-inc/mocking/_changelog.md
  app/_hub/kong-inc/oas-validation/_changelog.md
  app/_hub/kong-inc/openid-connect/_changelog.md
  app/_hub/kong-inc/opentelemetry/_changelog.md
  app/_hub/kong-inc/pre-function/_changelog.md
  app/_hub/kong-inc/prometheus/_changelog.md
  app/_hub/kong-inc/rate-limiting-advanced/_changelog.md
  app/_hub/kong-inc/response-ratelimiting/_changelog.md
  app/_hub/kong-inc/service-protection/_changelog.md
  app/_hub/kong-inc/session/_changelog.md
  app/gateway/changelog.md
Labels: review:general, ci:manual-approve:link-validation, skip-changelog

#8599 Release: Gateway 3.10
  app/_data/kong_versions.yml
Labels: review:general

#8624 docs(portal): additional idp configuration
  app/dev-portal/access-and-approvals/sso.md
Labels: review:general

#8626 Fix Plugin Hub search
  app/_assets/javascripts/plugin-hub.js
  tests/sidebar.test.js
Labels: review:general

#8625 docs(plugins/request-callout): warn about `forward` behavior
  app/_hub/kong-inc/request-callout/overview/_index.md
Labels: review:general

#8611 Fix: Expressions route limitation on mTLS and TLS Handshake Modifier
  app/_hub/kong-inc/mtls-auth/overview/_index.md
  app/_hub/kong-inc/tls-handshake-modifier/overview/_index.md
Labels: review:copyedit

#8627 Fix: adjust 310 support date for LTS
  app/_src/gateway/support/index.md
Labels: review:general

#8629 Fix: title AI RAG INJECTOR
  app/_hub/kong-inc/ai-rag-injector/how-to/_index.md
Labels: review:general

#8630 Variable for latest gateway OSS version
  app/_data/kong_versions.yml
  app/_includes/md/kic/prerequisites.md
  app/_src/gateway-operator/get-started/kic/create-gateway.md
  app/_src/gateway-operator/guides/upgrade/data-plane/blue-green.md
  app/_src/kubernetes-ingress-controller/get-started/key-authentication.md
  app/_src/kubernetes-ingress-controller/upgrade/gateway.md
  jekyll-dev.yml
  jekyll.yml
Labels: review:general

#8639 Fix: Add note about private Docker image
  app/_hub/kong-inc/ai-sanitizer/how-to/_index.md
  app/_hub/kong-inc/ai-sanitizer/overview/_index.md
  app/_includes/footer.html
Labels: review:general

#8638 Update index.md
  app/_src/gateway/kong-enterprise/event-hooks/index.md
Labels: review:general

#8614 Feat: External consumers api
  api-specs/Konnect/v1/yaml/regional-consumers.yaml
  app/_api/konnect/notification-hub/_index.md
  app/_api/konnect/regional-consumers/_index.md
  app/_data/konnect_oas_data.json
Labels: review:general

#7657 feat: add support for externalized consumers
  .github/styles/kong/auto-ignore.txt
  app/_data/docs_nav_konnect.yml
  app/_hub/kong-inc/key-auth/how-to/_index.md
  app/_hub/kong-inc/key-auth/overview/_index.md
  app/konnect/centralized-consumer-management.md
Labels: do not merge, review:general, ci:manual-approve:link-validation

#8642 Fix: kong.conf broken table
  app/_src/gateway/reference/configuration/configuration-3.10.x.md
Labels: review:general, skip-changelog

#8637 Automated Changelog update [skip-ci]
  changelog.md
Labels: review:copyedit, skip-changelog

#8620 feat(sdk): automated oas update
  api-specs/Konnect/control-planes-config/control-planes-config.yaml
  api-specs/Konnect/v1/yaml/ksearch.yaml
Labels: review:general

#8628 Fix SSO url
  app/_includes/md/konnect/okta-sso.md
Labels: review:general
